### PR TITLE
[bug][db] Table relation_project_user have duplicate record

### LINKED ISSUE #9290: [Bug] [t_ds_relation_project_user] Duplicate data exists
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Duplicate data exists in the database when authorizing projects to users;
There is a cache when writing, suspected to write the first project  repeatedly
image

image

### What you expected to happen

when authorizing projects to users

### How to reproduce

authorizing projects to users，When an item is selected and then deleted and then selected again

### Anything else

nothing

### Version

2.0.3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [ ] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by leiwingqueen**
## Purpose of the pull request

refer to issue close #9290

## Verify this pull request

This pull request is code cleanup without any test coverage.

### CODE REVIEW

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/UsersServiceImpl.java [hunk 1]
```diff
@@ -63,14 +63,7 @@
...
 import java.text.MessageFormat;
-import java.util.ArrayList;
-import java.util.Date;
-import java.util.HashMap;
-import java.util.HashSet;
-import java.util.List;
-import java.util.Map;
-import java.util.Set;
-import java.util.TimeZone;
+import java.util.*;
```
Comment (SbloodyS) [inline dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/UsersServiceImpl.java]: Please avoid ```import *```

File: dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_postgresql.sql [hunk 2]
```diff
@@ -622,7 +622,8 @@ CREATE TABLE t_ds_relation_project_user (
   perm int DEFAULT '1' ,
   create_time timestamp DEFAULT NULL ,
   update_time timestamp DEFAULT NULL ,
-  PRIMARY KEY (id)
+  PRIMARY KEY (id),
```
Comment (SbloodyS) [inline dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_postgresql.sql:628]: Please also add it to ```dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_mysql.sql``` and ```dolphinscheduler-dao/src/main/resources/sql/upgrade/2.0.6_schema```

Comment (leiwingqueen) [reply dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_postgresql.sql:628]: thank you. I have already fix it

File: dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_postgresql.sql [hunk 3]
```diff
@@ -625,7 +625,8 @@ CREATE TABLE t_ds_relation_project_user (
...
+  UNIQUE KEY uniq_uid_pid(user_id,project_id)
```
Comment (SbloodyS) [inline dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_postgresql.sql]: There are syntax error in ```postgresql```.

File: dolphinscheduler-dao/src/main/resources/sql/upgrade/2.0.6_schema/postgresql/dolphinscheduler_ddl.sql [hunk 4]
```diff
@@ -45,4 +45,7 @@ $BODY$;
 
 select dolphin_update_metadata();
 
-d//
\ No newline at end of file
+d//
+
+-- add unique key to t_ds_relation_project_user
+ALTER TABLE t_ds_relation_project_user ADD UNIQUE KEY uniq_uid_pid(user_id,project_id);
```
Comment (SbloodyS) [inline dolphinscheduler-dao/src/main/resources/sql/upgrade/2.0.6_schema/postgresql/dolphinscheduler_ddl.sql]: Same here.

Comment (leiwingqueen) [reply dolphinscheduler-dao/src/main/resources/sql/upgrade/2.0.6_schema/postgresql/dolphinscheduler_ddl.sql]: thanks,I try to fix it

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/UsersServiceImpl.java [hunk 5]
```diff
@@ -557,20 +557,16 @@ public Map<String, Object> grantProject(User loginUser, int userId, String proje
...
-
-        String[] projectIdArr = projectIds.split(",");
-
-        for (String projectId : projectIdArr) {
+        Arrays.stream(projectIds.split(",")).distinct().forEach(pId -> {
             Date now = new Date();
             ProjectUser projectUser = new ProjectUser();
             projectUser.setUserId(userId);
-            projectUser.setProjectId(Integer.parseInt(projectId));
+            projectUser.setProjectId(Integer.parseInt(pId));
```
Comment (SbloodyS) [inline dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/UsersServiceImpl.java]: It is recommended to use ```projectId``` instead of ```pId```.

Comment (SbloodyS) [inline dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/UsersServiceImpl.java]: It is recommended to use ```projectId``` instead of ```pId```.

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/UsersServiceImpl.java [hunk 6]
```diff
@@ -610,14 +606,18 @@ public Map<String, Object> grantProjectByCode(final User loginUser, final int us
...
-        final Date today = new Date();
-        ProjectUser projectUser = new ProjectUser();
-        projectUser.setUserId(userId);
-        projectUser.setProjectId(project.getId());
-        projectUser.setPerm(7);
-        projectUser.setCreateTime(today);
-        projectUser.setUpdateTime(today);
-        this.projectUserMapper.insert(projectUser);
+        // check if already existed
+        ProjectUser pu = projectUserMapper.queryProjectRelation(project.getId(), userId);
```
Comment (SbloodyS) [inline dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/UsersServiceImpl.java]: Same as ```projectId```.

Comment (SbloodyS) [inline dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/UsersServiceImpl.java]: Same as ```projectId```.

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/UsersServiceImpl.java [hunk 7]
```diff
@@ -610,14 +606,18 @@ public Map<String, Object> grantProjectByCode(final User loginUser, final int us
...
         // 4. maintain the relationship between project and user
-        final Date today = new Date();
-        ProjectUser projectUser = new ProjectUser();
-        projectUser.setUserId(userId);
-        projectUser.setProjectId(project.getId());
-        projectUser.setPerm(7);
-        projectUser.setCreateTime(today);
-        projectUser.setUpdateTime(today);
-        this.projectUserMapper.insert(projectUser);
+        // check if already existed
```
Comment (SbloodyS) [inline dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/UsersServiceImpl.java]: Is it better to use ```maintain the relationship between project and user if not exists``` to avoid misunstanding?

Comment (SbloodyS) [inline dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/UsersServiceImpl.java]: Is it better to use ```maintain the relationship between project and user if not exists``` to avoid misunstanding?

Comment (leiwingqueen) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/UsersServiceImpl.java]: we won't change the relationship when the relationship already exist. 
Do you mean that we should throw a error message to user?

Comment (SbloodyS) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/UsersServiceImpl.java]: I mean, change the content of the comment. @leiwingqueen

Comment (leiwingqueen) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/UsersServiceImpl.java]: I see. I have change it

File: dolphinscheduler-dao/src/main/resources/sql/upgrade/2.0.6_schema/mysql/dolphinscheduler_ddl.sql [hunk 8]
```diff
@@ -57,3 +57,8 @@ d//
 delimiter ;
 CALL uc_dolphin_T_t_ds_alert_R_sign;
 DROP PROCEDURE uc_dolphin_T_t_ds_alert_R_sign;
+
+-- add unique key to t_ds_relation_project_user
+ALTER TABLE t_ds_relation_project_user ADD UNIQUE KEY uniq_uid_pid(user_id,project_id);
```
Comment (zhongjiajie) [inline dolphinscheduler-dao/src/main/resources/sql/upgrade/2.0.6_schema/mysql/dolphinscheduler_ddl.sql:62]: i think we should add to new SQL directory named `3.0.0`?

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/UsersServiceImpl.java (hunk 6 above)
Comment (zhongjiajie) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/UsersServiceImpl.java]: but this `getId` is object `project`'s function

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/UsersServiceImpl.java (hunk 5 above)
Comment (leiwingqueen) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/UsersServiceImpl.java]: @SbloodyS got it

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/UsersServiceImpl.java (hunk 6 above)
Comment (leiwingqueen) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/UsersServiceImpl.java]: thanks.but id is the property of project and should not change

Comment (SbloodyS) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/UsersServiceImpl.java]: @leiwingqueen Hi,variable pu did not change to projectUser.

Comment (leiwingqueen) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/UsersServiceImpl.java]: got it.

File: dolphinscheduler-dao/src/main/resources/sql/upgrade/2.0.6_schema/mysql/dolphinscheduler_ddl.sql (hunk 8 above)
Comment (SbloodyS) [reply dolphinscheduler-dao/src/main/resources/sql/upgrade/2.0.6_schema/mysql/dolphinscheduler_ddl.sql:62]: > i think we should add to new SQL directory named `3.0.0`?

It's a bug fix. I think it should be included in 2.0.6-release. WDYT? @zhongjiajie

Comment (zhongjiajie) [reply dolphinscheduler-dao/src/main/resources/sql/upgrade/2.0.6_schema/mysql/dolphinscheduler_ddl.sql:62]: In general, I think change targe branch with `dev` database change should add to 3.0.0_schema, and committer judge whether should release in bug fix version. If it is only put in 2.0.5 and not in 3.0.0, it may be that the 3.0.0-bate release will miss this commit.

But in case, `dev` branch without `3.0.0_schema` folder,(and that is my wrong, i forgot to add it after 3.0.0-release) so i think it could change into 2.0.6 or 3.0.0

**Comment by zhongjiajie** [comment]
code LGTM, but we still have discussion in https://github.com/apache/dolphinscheduler/pull/9536#discussion_r856874838

File: dolphinscheduler-dao/src/main/resources/sql/upgrade/2.0.6_schema/mysql/dolphinscheduler_ddl.sql (hunk 8 above)
Comment (SbloodyS) [reply dolphinscheduler-dao/src/main/resources/sql/upgrade/2.0.6_schema/mysql/dolphinscheduler_ddl.sql:62]: > In general, I think change targe branch with `dev` database change should add to 3.0.0_schema, and committer judge whether should release in bug fix version. If it is only put in 2.0.5 and not in 3.0.0, it may be that the 3.0.0-bate release will miss this commit.
> 
> But in case, `dev` branch without `3.0.0_schema` folder,(and that is my wrong, i forgot to add it after 3.0.0-release) so i think it could change into 2.0.6 or 3.0.0

I agree with you. @zhongjiajie

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/UsersServiceImpl.java [hunk 9]
```diff
@@ -609,15 +605,18 @@ public Map<String, Object> grantProjectByCode(final User loginUser, final int us
...
-        projectUser.setUserId(userId);
-        projectUser.setProjectId(project.getId());
-        projectUser.setPerm(7);
-        projectUser.setCreateTime(today);
-        projectUser.setUpdateTime(today);
-        this.projectUserMapper.insert(projectUser);
+        // 4. maintain the relationship between project and user if not exists
+        ProjectUser projectUser = projectUserMapper.queryProjectRelation(project.getId(), userId);
+        if (projectUser == null) {
+            final Date today = new Date();
```
Comment (litiliu) [inline dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/UsersServiceImpl.java]: Maybe the final identifier is not needed?

**Review by litiliu — COMMENTED** [review]
not necessarily to change

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/UsersServiceImpl.java (hunk 9 above)
Comment (leiwingqueen) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/UsersServiceImpl.java]: I agree. I try to remove it

**Review by zhongjiajie — APPROVED** [review]
LGTM, thanks~
