### PR TITLE
[Fix-17638][API] Optimize workflow lineage update logic

### LINKED ISSUE #17638: [Bug] [API] The workflow cannot be deleted even after removing dependent nodes.
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

The workflow's dependency nodes have been removed, but the workflow still cannot be deleted.

Image

### What you expected to happen

If the workflow dependency node has been removed, the workflow can be deleted.

### How to reproduce

1. Create a workflow, including correctly created dependency nodes, and save the workflow.
2. After deleting the dependency nodes in the workflow, delete the workflow.

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by det101**
## Purpose of the pull request

close #17638 

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

## Pull Request Notice
[Pull Request Notice](https://github.com/apache/dolphinscheduler/blob/dev/docs/docs/en/contribute/join/pull-request.md)

If your pull request contains incompatible change, you should also add it to `docs/docs/en/guide/upgrade/incompatible.md`

### CODE REVIEW

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/WorkflowLineageServiceImpl.java [hunk 1]
```diff
@@ -318,8 +319,26 @@ public int createWorkflowLineage(List<WorkflowTaskLineage> workflowTaskLineages)
...
+
+        boolean hasMismatch = workflowTaskLineages.stream()
+                .anyMatch(lineage -> lineage.getWorkflowDefinitionCode() != workflowDefinitionCode);
+        if (hasMismatch) {
+            log.warn("Skip updating lineage due to workflowDefinitionCode mismatch, expected: {}",
+                    workflowDefinitionCode);
+            throw new IllegalArgumentException(
+                    String.format("All lineage items must belong to workflowDefinitionCode %s",
+                            workflowDefinitionCode));
+        }
```
Comment (ruanwenjun) [inline dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/WorkflowLineageServiceImpl.java]:
```suggestion
```
We don't need to check this here, otherwise we need to do a lot of check logic in every method.

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/WorkflowDefinitionServiceImpl.java [hunk 2]
```diff
@@ -409,14 +409,16 @@ public void saveWorkflowLineage(long projectCode,
...
 
-        int insertWorkflowLineageResult = workflowLineageService.updateWorkflowLineage(workflowTaskLineageList);
-        if (insertWorkflowLineageResult <= 0) {
+        int insertWorkflowLineageResult =
+                workflowLineageService.updateWorkflowLineage(workflowDefinitionCode, workflowTaskLineageList);
+        if (CollectionUtils.isEmpty(workflowTaskLineageList)) {
+            log.info(
+                    "Delete workflow lineage because current lineage is empty, projectCode: {}, workflowDefinitionCode: {}, workflowDefinitionVersion: {}",
+                    projectCode, workflowDefinitionCode, workflowDefinitionVersion);
+        } else if (insertWorkflowLineageResult <= 0) {
```
Comment (ruanwenjun) [inline dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/WorkflowDefinitionServiceImpl.java]:
```suggestion
       if (!CollectionUtils.isNotEmpty(workflowTaskLineageList) && insertWorkflowLineageResult <= 0) {
```
Remove the log here, this service should not be aware of delete operations.
In fact, throwing exceptions should be the responsibility of the DAO layer.

**Review by ruanwenjun — CHANGES_REQUESTED** [review]

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/WorkflowDefinitionServiceImpl.java (hunk 2 above)
Comment (det101) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/WorkflowDefinitionServiceImpl.java]: As you suggested, I refactored: Instead of deleting the logs directly, I moved the lineage logic to WorkflowTaskLineageService.updateWorkflowLineage() and simplified WorkflowDefinitionService.saveWorkflowLineage().

**Review by ruanwenjun — APPROVED** [review]
LGTM

**Comment by ruanwenjun** [comment]
Please fix the new issue.
image

**Review by SbloodyS — APPROVED** [review]
+1
