### PR TITLE
[Fix-17137][CLUSTER-MANAGE] Fix update time not effective

### LINKED ISSUE #17137: [Bug] [CLUSTER-MANAGE] Update time not effective
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Update time not effective

### What you expected to happen

fix

### How to reproduce

Image
Image

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by sdhzwc**
close #17137 

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

## Pull Request Notice
[Pull Request Notice](https://github.com/apache/dolphinscheduler/blob/dev/docs/docs/en/contribute/join/pull-request.md)

If your pull request contains incompatible change, you should also add it to `docs/docs/en/guide/upgrade/incompatible.md`

### CODE REVIEW

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ClusterServiceImpl.java [hunk 1]
```diff
@@ -265,6 +265,7 @@ public Cluster updateClusterByCode(User loginUser,
         clusterExist.setConfig(config);
         clusterExist.setName(name);
         clusterExist.setDescription(desc);
+        clusterExist.setUpdateTime(new Date());
```
Comment (SbloodyS) [inline dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ClusterServiceImpl.java]: Please using `DataUtils.getCurrentDate()` instead.

Comment (sdhzwc) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ClusterServiceImpl.java]: > Please using `DataUtils.getCurrentDate()` instead.

done

**Review by SbloodyS — APPROVED** [review]
LGTM

**Review by ruanwenjun — APPROVED** [review]
