### PR TITLE
fix when the task details are not modified, the predecessor node cannot be modified

### LINKED ISSUE #13421: [Bug] [dolphinscheduler-api] in the task definition list, when the task details are not modified, the predecessor node cannot be modified
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

in the task definition list, 
edit node,
the task detail are not modify, only the process pre code for modify

### What you expected to happen

the task detail are not modify, only the process pre code for modify

### How to reproduce

in the task definition list, 
edit node,
the task detail are not modify, only the process pre code for modify

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by jackfanwan**
fix when the task details are not modified, the predecessor node cannot be modified

closes: #13421

### CODE REVIEW

**Review by SbloodyS — COMMENTED** [review]
Could you provide more details about it? I don't quite understand the problem you have.

**Comment by jackfanwan** [comment]
> Could you provide more details about it? I don't quite understand the problem you have.

image

**Comment by SbloodyS** [comment]
I got you. The root cause that cannot be modified is here. You can try to add the judgment of predecessor tasks to this. @jackfanwan 

https://github.com/apache/dolphinscheduler/blob/66e20271ad04c571dbd05c114ccbc050ee128dfb/dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/TaskDefinition.java#L275-L303

**Comment by jackfanwan** [comment]
> I got you. The root cause that cannot be modified is here. You can try to add the judgment of predecessor tasks to this. @jackfanwan
> 
> https://github.com/apache/dolphinscheduler/blob/66e20271ad04c571dbd05c114ccbc050ee128dfb/dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/TaskDefinition.java#L275-L303

Here is the judgment task, modifying the predecessor node is operated outside
image

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TaskDefinitionServiceImpl.java [hunk 1]
```diff
@@ -820,9 +820,6 @@ public Map<String, Object> updateTaskWithUpstream(User loginUser, long projectCo
         Map<String, Object> result = new HashMap<>();
         TaskDefinitionLog taskDefinitionToUpdate =
                 updateTask(loginUser, projectCode, taskCode, taskDefinitionJsonObj, result);
-        if (result.get(Constants.STATUS) != Status.SUCCESS && taskDefinitionToUpdate == null) {
-            return result;
-        }
```
Comment (SbloodyS) [inline dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TaskDefinitionServiceImpl.java:825]: This is used to ensure that meaningless multiple modifications will not be directly written to the database. We should add the judgement of the predecessor node instead of remove it.

Comment (jackfanwan) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TaskDefinitionServiceImpl.java:825]: image
here have judgment predecessor node and task info, so i deleted first judgement

Comment (SbloodyS) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TaskDefinitionServiceImpl.java:825]: I took a quick look at this part of the code and found that you are right. But if we remove this, each modification will be saved to the database regardless of whether there is a real change. It makes the judgment of equals meaningless.

I'm +0 to this way. What do you guys think? @ruanwenjun @caishunfeng @EricGao888 @zhongjiajie

Comment (jackfanwan) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TaskDefinitionServiceImpl.java:825]: > I took a quick look at this part of the code and found that you are right. But if we remove this, each modification will be saved to the database regardless of whether there is a real change. It makes the judgment of equals meaningless.
> 
> I'm +0 to this way. What do you guys think? @ruanwenjun @caishunfeng @EricGao888 @zhongjiajie

Why invalid modifications affect the database

Comment (SbloodyS) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TaskDefinitionServiceImpl.java:825]: > Why invalid modifications affect the database

Each modification will be insert to the `t_ds_task_definition_log` as a newer version.

https://github.com/apache/dolphinscheduler/blob/8439b5dc69f2a7dfc1043393bbbb21a8277715da/dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TaskDefinitionServiceImpl.java#L754-L775

Comment (jackfanwan) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TaskDefinitionServiceImpl.java:825]: > > Why invalid modifications affect the database
> 
> Each modification will be insert to the `t_ds_task_definition_log` as a newer version.
> 
> https://github.com/apache/dolphinscheduler/blob/8439b5dc69f2a7dfc1043393bbbb21a8277715da/dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TaskDefinitionServiceImpl.java#L754-L775

image
if only modify predecessor node, here can return

Comment (caishunfeng) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TaskDefinitionServiceImpl.java:825]: Looks good to me.
But I found that some useless code, can you delete together?
https://github.com/apache/dolphinscheduler/blob/8be32d4145c851a01d7300cd5a854be9b4a27055/dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TaskDefinitionServiceImpl.java#L839-L841

Comment (jackfanwan) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TaskDefinitionServiceImpl.java:825]: > Looks good to me. But I found that some useless code, can you delete together?
> 
> https://github.com/apache/dolphinscheduler/blob/8be32d4145c851a01d7300cd5a854be9b4a27055/dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TaskDefinitionServiceImpl.java#L839-L841

done

**Review by caishunfeng — APPROVED** [review]
