### PR TITLE
[Fix-#11669][Workflow Instance Page] Fix the duration in Workflow Instance page.

### LINKED ISSUE #11669: [Bug] [WorkflowInstance] the value of duration in Workflow Instance table is wrong
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When the workflow instance is in the process of executing, the result should be empty, regardless of whether the workflow instance 
 was run for the first time or re-run. 
But when we re-run the workflow instance , the status show instance is running, but the ***duration*** is displayed as `(the task re-run start time) - (the last task end time)`, which is obviously wrong.

Because the workflow instance page will keep query the data from api - ProcessInstanceController-queryProcessInstanceList, the source code just use **_Math.abs(startTime - endTime)_**. 

Please check the following code:
`for (ProcessInstance processInstance : processInstances) {
            processInstance.setDuration(
                    DateUtils.format2Duration(processInstance.getStartTime(), processInstance.getEndTime()));
            ...
        }`

### What you expected to happen

When the workflow instanceis running, the duration should be null,

### How to reproduce

Step 1. Create a workflow instance and run it.
Step 2. After the workflow instance finished, then click "re-run" button, and check the duration when the state show executing.

### Anything else

Need to determine in which workflow instance state this duration needs to be empty, i think just **_RUNNING_EXECUTION_** and **_SERIAL_WAIT_**. 

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by DarkAssassinator**
## Purpose of the pull request

fix #11669 
re-open this PR.

## Brief change log

1. If process running, this endTime should be the current time.
2. If endtime < starttime. the duration should be null

## Verify this pull request

This change added tests

### CODE REVIEW

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessInstanceServiceImpl.java [hunk 1]
```diff
@@ -335,6 +339,19 @@ public Result queryProcessInstanceList(User loginUser, long projectCode, long pr
...
+    /**
+     * check if the processInstance is finish
+     * @param processInstance processInstance
+     * @return result
+     */
+    private boolean isFinish(ProcessInstance processInstance){
+        if (processInstance.getState() == null) {
+            return false;
+        }
+        return !processInstance.getState().equals(WorkflowExecutionStatus.RUNNING_EXECUTION)
```
Comment (EricGao888) [inline dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessInstanceServiceImpl.java]: @SbloodyS @caishunfeng I'm not sure about this, could u plz help take a look when available? Thanks : )
https://github.com/apache/dolphinscheduler/blob/2e4a9e6d5395730282a3f105aa815a4095a96433/dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/enums/WorkflowExecutionStatus.java#L29-L41

File: dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ProcessInstanceServiceTest.java [hunk 2]
```diff
@@ -270,20 +270,48 @@ public void testQueryTopNLongestRunningProcessInstance() {
...
                 .queryTopNLongestRunningProcessInstance(loginUser, projectCode, size, startTime, endTime);
-        Assert.assertEquals(Status.PROJECT_NOT_FOUND, proejctAuthFailRes.get(Constants.STATUS));
+        Assert.assertEquals(Status.PROJECT_NOT_FOUND, projectAuthFailRes.get(Constants.STATUS));
 
         // project auth success
         putMsg(result, Status.SUCCESS, projectCode);
         ProcessInstance processInstance = getProcessInstance();
         when(projectMapper.queryByCode(projectCode)).thenReturn(project);
         when(projectService.checkProjectAndAuth(loginUser, project, projectCode, WORKFLOW_INSTANCE)).thenReturn(result);
+        projectAuthFailRes = processInstanceService
```
Comment (EricGao888) [inline dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ProcessInstanceServiceTest.java:282]: This test case is a bit too long with multiple sub cases, it would be better if u could separate it.

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessInstanceServiceImpl.java [hunk 3]
```diff
@@ -335,6 +339,19 @@ public Result queryProcessInstanceList(User loginUser, long projectCode, long pr
         return result;
     }
 
+    /**
```
Comment (EricGao888) [inline dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessInstanceServiceImpl.java]: Since this method is not an open API, and its logic is quite clear, I prefer removing the comments. As u could see, there are many legacy redundant comments in this project which are hard to maintain, we will remove and fix those comments in the future gradually.

Comment (DarkAssassinator) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessInstanceServiceImpl.java]: sure, remove it

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessInstanceServiceImpl.java (hunk 1 above)
Comment (DarkAssassinator) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessInstanceServiceImpl.java]: has removed this new function, use the common `processInstance.getState().isFinished()`

File: dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ProcessInstanceServiceTest.java (hunk 2 above)
Comment (DarkAssassinator) [reply dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ProcessInstanceServiceTest.java:282]: done

**Comment by DarkAssassinator** [comment]
@ruanwenjun could help to review this PR? thx.

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessInstanceServiceImpl.java [hunk 4]
```diff
@@ -320,8 +320,11 @@ public Result queryProcessInstanceList(User loginUser, long projectCode, long pr
         }
 
         for (ProcessInstance processInstance : processInstances) {
-            processInstance.setDuration(
-                    DateUtils.format2Duration(processInstance.getStartTime(), processInstance.getEndTime()));
+            // if processInstance is running, the endTime should be the current time
+            String duration = processInstance.getState() != null && processInstance.getState().isFinished() ?
+                    DateUtils.format2Duration(processInstance.getStartTime(), processInstance.getEndTime()) :
+                    DateUtils.format2Duration(processInstance.getStartTime(), new Date());
```
Comment (fuchanghai) [inline dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessInstanceServiceImpl.java]: #in the method of DateUtils#format2Duration .when endTime is null will return new Date. i mean that maybe we can use 
```java
 DateUtils.format2Duration(processInstance.getStartTime(), processInstance.getEndTime())
``` 
instead of
 ```java
String duration = processInstance.getState() != null && processInstance.getState().isFinished() ?
                    DateUtils.format2Duration(processInstance.getStartTime(), processInstance.getEndTime()) :
                    DateUtils.format2Duration(processInstance.getStartTime(), new Date()); 
```

Comment (DarkAssassinator) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessInstanceServiceImpl.java]: @fuchanghai no, if re-run, this endTime will not be null, so cannot use the processInstance.getEndTime()

Comment (ruanwenjun) [inline dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessInstanceServiceImpl.java]: Can we move these code in a utils, `WorkflowUtils.getWorkflowInstanceDuration(ProcessInstance processInstance)`?

File: dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/DateUtils.java [hunk 5]
```diff
@@ -353,6 +353,9 @@ public static String format2Duration(Date start, Date end) {
         if (end == null) {
             end = new Date();
         }
+        if (start.after(end)) {
```
Comment (ruanwenjun) [inline dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/DateUtils.java:356]: This is an unexpected case, we need to log a warning here.

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessInstanceServiceImpl.java (hunk 4 above)
Comment (DarkAssassinator) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessInstanceServiceImpl.java]: good idea, done

File: dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/DateUtils.java (hunk 5 above)
Comment (DarkAssassinator) [reply dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/DateUtils.java:356]: done

**Review by ruanwenjun — APPROVED** [review]
LGTM
