### PR TITLE
[Fix-14008][registry] cache keep alive lease

### LINKED ISSUE #14008: [Bug] [registry] use etcd lease memory leak
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

image
image

When using the ETCD registry, each put operation creates a Lease that is cached in memory. As shown in the screenshot, both the ETCD server and client have over 170 Leases.

### What you expected to happen

Lease can be released normally

### How to reproduce

Using the ETCD registry

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by eye-gu**
## Purpose of the pull request

fix #14008 

## Brief change log

add `EtcdKeepAliveLeaseManager`

## Verify this pull request

This pull request is code cleanup without any test coverage.

### CODE REVIEW

File: dolphinscheduler-registry/dolphinscheduler-registry-plugins/dolphinscheduler-registry-etcd/src/main/java/org/apache/dolphinscheduler/plugin/registry/etcd/EtcdKeepAliveLeaseManager.java [hunk 1]
```diff
@@ -0,0 +1,59 @@
+package org.apache.dolphinscheduler.plugin.registry.etcd;
```
Comment (SbloodyS) [inline dolphinscheduler-registry/dolphinscheduler-registry-plugins/dolphinscheduler-registry-etcd/src/main/java/org/apache/dolphinscheduler/plugin/registry/etcd/EtcdKeepAliveLeaseManager.java:18]: Missing license header.

**Comment by SbloodyS** [comment]
PTAL @ruanwenjun

**Review by ruanwenjun — APPROVED** [review]
LGTM. 
Since each put operation will create a new leaseId, and we will schedule heartbeat task to execute put to write heartbeat info, so this will cause memory leak.

This PR will hold the mapping of key to leaseId.
