### PR TITLE
[Fix-12356][k8s] fix the null exception when submitting k8s task plugin

### LINKED ISSUE #12356: [Bug] [k8s] null exception when submitting k8s task plugin
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

* Null exception in master's log
```
[ERROR] 2022-10-13 15:51:10.327 +0800 TaskLogLogger-class org.apache.dolphinscheduler.server.master.runner.task.CommonTaskProcessor:[135] - Task dd is submitted to priority queue error
java.lang.NullPointerException: null
	at org.apache.dolphinscheduler.service.process.ProcessServiceImpl.findConfigYamlByName(ProcessServiceImpl.java:3175)
	at org.apache.dolphinscheduler.service.process.ProcessServiceImpl$$FastClassBySpringCGLIB$$9d3e18f9.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
	at org.apache.dolphinscheduler.service.process.ProcessServiceImpl$$EnhancerBySpringCGLIB$$e4fb2474.findConfigYamlByName(<generated>)
	at org.apache.dolphinscheduler.server.master.runner.task.BaseTaskProcessor.setK8sTaskRelation(BaseTaskProcessor.java:659)
	at org.apache.dolphinscheduler.server.master.runner.task.BaseTaskProcessor.getTaskExecutionContext(BaseTaskProcessor.java:329)
	at org.apache.dolphinscheduler.server.master.runner.task.CommonTaskProcessor.dispatchTask(CommonTaskProcessor.java:123)
	at org.apache.dolphinscheduler.server.master.runner.task.BaseTaskProcessor.dispatch(BaseTaskProcessor.java:241)
	at org.apache.dolphinscheduler.server.master.runner.task.BaseTaskProcessor.action(BaseTaskProcessor.java:212)
	at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable.submitTaskExec(WorkflowExecuteRunnable.java:980)
	at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable.submitStandByTask(WorkflowExecuteRunnable.java:1832)
	at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable.submitPostNode(WorkflowExecuteRunnable.java:1360)
	at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable.call(WorkflowExecuteRunnable.java:695)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

### What you expected to happen

submit k8s task plugin without null exception

### How to reproduce

* create cluster
截屏2022-10-13 16 03 56

* create k8s namespace
截屏2022-10-13 16 04 01

* run a k8s task plugin, and failed
image

### Anything else

version: dev, 3.1.0

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by rickchengx**
## Purpose of the pull request

* close: #12356 
* bug version: 3.1.0, dev

## Brief change log

get the k8s config from table `t_ds_cluster` instead of `t_ds_k8s`

## Verify this pull request

the k8s task can be submitted successfully

截屏2022-10-13 16 58 07

截屏2022-10-13 17 02 15

### CODE REVIEW

**Comment by rickchengx** [comment]
Hi, @kezhenxu94 , would you please help review this?

**Comment by kezhenxu94** [comment]
Hi. Did you check that t_ds_k8s is not used?

**Comment by rickchengx** [comment]
> Hi. Did you check that t_ds_k8s is not used?

Hi, @kezhenxu94 , thanks for the comment.

* step 1: create cluster
截屏2022-10-13 16 03 56

* step 2: create k8s namespace
截屏2022-10-13 16 04 01

After my check, `t_ds_cluster` is inserted when creating cluster (step 1) and `t_ds_k8s_namespace` is inserted when creating k8s namespace (step 2).

And `t_ds_k8s` is empty (this is also the reason of null exception because it tries to get config from an empty table).


Furthermore, the k8s cluster info (including `k8s config`) is inserted to the table `t_ds_cluster` (not `t_ds_k8s`) as below:

https://github.com/apache/dolphinscheduler/blob/1e792186d0b1e660dc2299b46827a46c59d393f6/dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ClusterServiceImpl.java#L122-L126

**Comment by pandong2011** [comment]
k8s

It seems that the version iteration will load the k8s configuration from t_ds_k8s to t_ds_k8s_namespace and t_ds_cluster, but it has not been done yet

File: dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessServiceImpl.java [hunk 1]
```diff
@@ -3169,10 +3169,11 @@ public String findConfigYamlByName(String clusterName) {
...
         }
-        QueryWrapper<K8s> nodeWrapper = new QueryWrapper<>();
-        nodeWrapper.eq("k8s_name", clusterName);
-        K8s k8s = k8sMapper.selectOne(nodeWrapper);
-        return k8s.getK8sConfig();
+
+        QueryWrapper<Cluster> nodeWrapper = new QueryWrapper<>();
+        nodeWrapper.eq("name", clusterName);
+        Cluster cluster = clusterMapper.selectOne(nodeWrapper);
+        return cluster.getConfig();
```
Comment (ruanwenjun) [inline dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessServiceImpl.java]: It's better to write a sql rather than use `QueryWrapper`, and when the cluster is null here we might better return null rather than NPE?

**Comment by rickchengx** [comment]
> k8s
> 
> It seems that the version iteration will load the k8s configuration from t_ds_k8s to t_ds_k8s_namespace and t_ds_cluster, but it has not been done yet

Hi, @pandong2011 thanks for the comment.

Actually, I dont quite understand the meaning of this doc...

Do you know what is the usage of `t_ds_k8s`? During my test, it keeps empty.

File: dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessServiceImpl.java (hunk 1 above)
Comment (rickchengx) [reply dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessServiceImpl.java]: > It's better to write a sql rather than use `QueryWrapper`, and when the cluster is null here we might better return null rather than NPE?

Hi, @ruanwenjun , thanks for the comment.

1. I've changed `return cluster.getConfig();` to `return cluster == null ? null : cluster.getConfig();` to avoid the potential NPE.
2. As for writing a SQL rather than using `QueryWrapper`, maybe we could do it in another PR? Since `QueryWrapper` is also used in many other places. Maybe we should fix this bug first since this NPE bug will cause the user cannot submit k8s tasks.

**Comment by pandong2011** [comment]
> > k8s
> > It seems that the version iteration will load the k8s configuration from t_ds_k8s to t_ds_k8s_namespace and t_ds_cluster, but it has not been done yet
> 
> Hi, @pandong2011 thanks for the comment.
> 
> Actually, I dont quite understand the meaning of this doc...
> 
> Do you know what is the usage of `t_ds_k8s`? During my test, it keeps empty.

It should be the configuration table of k8s, but I can't find any entry to write data into it. Combined with the documentation I found, this table should be deprecated in the future

**Comment by rickchengx** [comment]
> > > k8s
> > > It seems that the version iteration will load the k8s configuration from t_ds_k8s to t_ds_k8s_namespace and t_ds_cluster, but it has not been done yet
> > 
> > 
> > Hi, @pandong2011 thanks for the comment.
> > Actually, I dont quite understand the meaning of this doc...
> > Do you know what is the usage of `t_ds_k8s`? During my test, it keeps empty.
> 
> It should be the configuration table of k8s, but I can't find any entry to write data into it. Combined with the documentation I found, this table should be deprecated in the future

It seems that the config of k8s cluster (E.g., `cluster_name` and `k8s_config`) is inserted to the table `t_ds_cluster` rather than `t_ds_k8s`

**Comment by pandong2011** [comment]
> > > > k8s
> > > > It seems that the version iteration will load the k8s configuration from t_ds_k8s to t_ds_k8s_namespace and t_ds_cluster, but it has not been done yet
> > > 
> > > 
> > > Hi, @pandong2011 thanks for the comment.
> > > Actually, I dont quite understand the meaning of this doc...
> > > Do you know what is the usage of `t_ds_k8s`? During my test, it keeps empty.
> > 
> > 
> > It should be the configuration table of k8s, but I can't find any entry to write data into it. Combined with the documentation I found, this table should be deprecated in the future
> 
> It seems that the config of k8s cluster (E.g., `cluster_name` and `k8s_config`) is inserted to the table `t_ds_cluster` rather than `t_ds_k8s`

Now yes, but the beginning should be to t_ds_k8s table to write data, do not know from which version to write data to t_ds_cluster table, but the query did not change, leaving a paragraph of vague text description

File: dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessServiceImpl.java (hunk 1 above)
Comment (caishunfeng) [reply dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessServiceImpl.java]: >As for writing a SQL rather than using QueryWrapper, maybe we could do it in another PR? Since QueryWrapper is also used in many other places. Maybe we should fix this bug first since this NPE bug will cause the user cannot submit k8s tasks.

Hi @rickchengx do you want to do it in another pr?

**Review by caishunfeng — APPROVED** [review]
LGTM

**Comment by caishunfeng** [comment]
> Now yes, but the beginning should be to t_ds_k8s table to write data, do not know from which version to write data to t_ds_cluster table, but the query did not change, leaving a paragraph of vague text description

The k8s task plugin is just exist in 3.1.0, and the `t_ds_k8s` seems the old design, which was replaced with `t_ds_cluster`.

**Comment by danielfree** [comment]
hi @caishunfeng @rickchengx  i also found out this bug and fixed it, need to point out that this pr's solution won't work because `cluster.getConfig();` result is not a valid kubeconfig yaml(it's the json string stored in that table), you have to use this:  `ClusterConfUtils.getK8sConfig(cluster.getConfig());` 

the current change only succeeds to submit the task, but the kubeconfig is not valid so the ds-worker won't submit the job to k8s cluster successfully.

@rickchengx maybe you can submit a new pr for the change.

**Comment by rickchengx** [comment]
> hi @caishunfeng @rickchengx i also found out this bug and fixed it, need to point out that this pr's solution won't work because `cluster.getConfig();` result is not a valid kubeconfig yaml(it's the json string stored in that table), you have to use this: `ClusterConfUtils.getK8sConfig(cluster.getConfig());`
> 
> the current change only succeeds to submit the task, but the kubeconfig is not valid so the ds-worker won't submit the job to k8s cluster successfully.
> 
> @rickchengx maybe you can submit a new pr for the change.

Hi, @danielfree , thanks a lot for the comment. I'll look into it.
Although this PR can successfully submit the job to k8s cluster, it seems that the kubeconfig is automatically read from `
~/.kube/config` instead of `cluster.getConfig()`.
