### PR TITLE
[Fix-16700] [doc] The Vertica datasource is under "Introduction to Function"

### LINKED ISSUE #16700: [Bug] [doc] The Vertica datasource is under "Introduction to Functions" ->"Parameter"
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

The Vertica datasource is under "Introduction to Functions" ->"Parameter"

image

### What you expected to happen

It should in "Introduction to Functions" ->"Data Source"

### How to reproduce

current doc web https://dolphinscheduler.apache.org/en-us/docs/3.2.2/guide/datasource/vertica

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by FrommyMind**
[Bug] [doc] The Vertica datasource is under "Introduction to Functions" ->"Parameter" fix #16700

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

## Pull Request Notice
[Pull Request Notice](https://github.com/apache/dolphinscheduler/blob/dev/docs/docs/en/contribute/join/pull-request.md)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

File: docs/configs/docsdev.js [hunk 1]
```diff
@@ -358,6 +354,10 @@ export default {
                             {
                                 title: 'doris',
                                 link: '/en-us/docs/dev/user_doc/guide/datasource/doris.html',
+                            },
+                            {
+                                title: 'Vertica',
+                                link: '/en-us/docs/dev/user_doc/guide/datasource/vertica.html',
```
Comment (SbloodyS) [inline docs/configs/docsdev.js:360]: Please change the `zh-cn` doc too.

**Review by SbloodyS — APPROVED** [review]
LGTM

**Review by Gallardot — APPROVED** [review]
