### PR TITLE
[Fix-17943][dolphinscheduler-task-dinky] When DolphinScheduler calls a Dinky job and passes date parameters, the actual values are not being replaced

### LINKED ISSUE #17943: [Bug] [dolphinscheduler-task-dinky] When DolphinScheduler calls a Dinky job and passes date parameters, the actual values are not being replaced
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Image

### What you expected to happen

I want the value is today

### How to reproduce

1. create a dinky job

Image

### Anything else

It is guaranteed to happen

### Version

dev

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by shaolei7788**
## Purpose of the pull request

fix #17943

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

## Pull Request Notice
[Pull Request Notice](https://github.com/apache/dolphinscheduler/blob/dev/docs/docs/en/contribute/join/pull-request.md)

If your pull request contains incompatible change, you should also add it to `docs/docs/en/guide/upgrade/incompatible.md`

### CODE REVIEW

File: dolphinscheduler-task-plugin/dolphinscheduler-task-dinky/src/main/java/org/apache/dolphinscheduler/plugin/task/dinky/DinkyTask.java [hunk 1]
```diff
@@ -471,4 +467,4 @@ private String sendJsonStr(String url, String params) {
         return result;
     }
 
-}
+}
```
Comment (SbloodyS) [inline dolphinscheduler-task-plugin/dolphinscheduler-task-dinky/src/main/java/org/apache/dolphinscheduler/plugin/task/dinky/DinkyTask.java]: Revert unnessnary chanage.

**Review by SbloodyS — COMMENTED** [review]
Please do not create multiple PRs repeatedly next time. This will lead to an increase in reviewer's work.

File: dolphinscheduler-task-plugin/dolphinscheduler-task-dinky/src/main/java/org/apache/dolphinscheduler/plugin/task/dinky/DinkyTask.java [hunk 2]
```diff
@@ -339,24 +337,22 @@ public void cancelApplication() throws TaskException {
...
-            variables.put(property.getProp(), value);
+        if (localParams != null) {
+            for (Property property : localParams) {
+                String value = ParameterUtils.convertParameterPlaceholders(property.getValue(), variables);
+                if (value != null && !value.isEmpty()) {
+                    variables.put(property.getProp(), value.trim());
+                }
+            }
         }
+        log.info("sending variables to dinky: {}", variables);
```
Comment (ruanwenjun) [inline dolphinscheduler-task-plugin/dolphinscheduler-task-dinky/src/main/java/org/apache/dolphinscheduler/plugin/task/dinky/DinkyTask.java:355]: Maybe directly use `taskExecutionContext.getPrepareParamsMap()` is enough?

File: dolphinscheduler-task-plugin/dolphinscheduler-task-dinky/src/main/java/org/apache/dolphinscheduler/plugin/task/dinky/DinkyTask.java (hunk 1 above)
Comment (shaolei7788) [reply dolphinscheduler-task-plugin/dolphinscheduler-task-dinky/src/main/java/org/apache/dolphinscheduler/plugin/task/dinky/DinkyTask.java]: > Revert unnessnary chanage.

ok

File: dolphinscheduler-task-plugin/dolphinscheduler-task-dinky/src/main/java/org/apache/dolphinscheduler/plugin/task/dinky/DinkyTask.java (hunk 2 above)
Comment (shaolei7788) [reply dolphinscheduler-task-plugin/dolphinscheduler-task-dinky/src/main/java/org/apache/dolphinscheduler/plugin/task/dinky/DinkyTask.java:355]: > Maybe directly use `taskExecutionContext.getPrepareParamsMap()` is enough?

No,it is not enough. The time function is not converted.

**Comment by shaolei7788** [comment]
> Please do not create multiple PRs repeatedly next time. This will lead to an increase in reviewer's work.

ok

File: dolphinscheduler-task-plugin/dolphinscheduler-task-dinky/src/main/java/org/apache/dolphinscheduler/plugin/task/dinky/DinkyTask.java (hunk 2 above)
Comment (ruanwenjun) [reply dolphinscheduler-task-plugin/dolphinscheduler-task-dinky/src/main/java/org/apache/dolphinscheduler/plugin/task/dinky/DinkyTask.java:355]: Are you sure? please test it on dev branch, this should be handled at master server.

Comment (shaolei7788) [reply dolphinscheduler-task-plugin/dolphinscheduler-task-dinky/src/main/java/org/apache/dolphinscheduler/plugin/task/dinky/DinkyTask.java:355]: Yes,I am sure

**Review by SbloodyS — APPROVED** [review]
LGTM
