### PR TITLE
[Fix-17767][Master] fix execute task in workflow instance not effective

### LINKED ISSUE #17767: [Bug] [Master] "execute task" is not effective
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

 "execute task" is not effective, when I click "run" in workflow instance page, nothing happend.

### What you expected to happen

When I click "run" in workflow instance page,  dolphinscheduler should new a task instance run command.

### How to reproduce

Add command handler for running task instance

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Mrhs121**
## Purpose of the pull request
close https://github.com/apache/dolphinscheduler/issues/17767

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

## Pull Request Notice
[Pull Request Notice](https://github.com/apache/dolphinscheduler/blob/dev/docs/docs/en/contribute/join/pull-request.md)

If your pull request contains incompatible change, you should also add it to `docs/docs/en/guide/upgrade/incompatible.md`

### CODE REVIEW

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/TaskExecutionContextFactory.java [hunk 1]
```diff
@@ -192,20 +193,27 @@ private Optional<String> getEnvironmentConfigFromDB(final TaskInstance taskInsta
         return Optional.ofNullable(environmentOptional.get().getConfig());
     }
 
-    // The successors of the task instance will be used to generate the var pool
-    // All out varPool from the successors will be merged into the var pool of the task instance
-    private List<Property> generateTaskInstanceVarPool(TaskDefinition taskDefinition,
+    // The predecessors of the task instance will be used to generate the var pool.
+    // In execute-task(TASK_ONLY) scenario, the predecessor might be outside current execution sub-graph.
```
Comment (Mrhs121) [inline dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/TaskExecutionContextFactory.java:196]: https://github.com/apache/dolphinscheduler/blob/8ee334fc2f4803d7a628458018d82ca695b920d1/dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java#L1152~L1172
The changes here are based on the old behavior in version 3.2

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/TaskExecutionContextFactory.java [hunk 2]
```diff
@@ -192,20 +193,27 @@ private Optional<String> getEnvironmentConfigFromDB(final TaskInstance taskInsta
...
+    // For this case, fallback to workflow varPool to keep compatibility with historical behavior.
+    private List<Property> generateTaskInstanceVarPool(WorkflowInstance workflowInstance,
```
Comment (ruanwenjun) [inline dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/TaskExecutionContextFactory.java:198]: It's better to use a clear logic, if the task instance is the start node, then use the workflow instance's varpool as the task instance varpool.

Comment (Mrhs121) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/TaskExecutionContextFactory.java:198]: Good idea. I’ve changed it to explicit start-node logic only start node uses workflow instance varPool

**Comment by Mrhs121** [comment]
@ruanwenjun  PTAL, thanks!

**Review by ruanwenjun — APPROVED** [review]
LGTM

**Review by SbloodyS — APPROVED** [review]
+1
