### PR TITLE
[Bug] Fix resource file local path is not correct in worker (Delete Resource/ResourceUser which is deprecated)

### LINKED ISSUE #15343: [Bug] [task-hivecli] Unable to read resource files in Hive CLI
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

I get a error, when i use HiveCLI and read SQL from File:
> Caused by: java.io.FileNotFoundException: /tmp/dolphinscheduler320/exec/process/***/11975691665664/11975844729729_4/17/22/hdfs:/***/user/dolphinscheduler320/***/resources/测试/HIVECLI.hql (No such file or directory)

so, i debug the code in IDEA. and then i find some issues from the file path: 
image
and then i find a filed:
image
so i change the code
image
and return right path
image

### What you expected to happen

return right path, just like issue describe

### How to reproduce

every time when use hiveCLI read SQL from file

### Anything else

_No response_

### Version

3.2.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### LINKED ISSUE #15344: [Bug] [Java] Main class cannot be found or cannot be loaded
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

一、--class-path这个参数在项目里面是写死的，但是对于使用JDK8的用户来说不太友好，因为JDK8没有这个option
二、打包好的jar包，明明在本地可以运行，但是在DolphinScheduler的Java组件里面却一直报错找不到或无法加载主类
三、使用jar运行类型，为什么选择了主程序包，还必须得选资源中心，不然就跑不起来，有点重复选择的感觉
4503F3E75B2D2B2F948D23C995797B02

7F8F3393213B8A42A03A85B0A8DA73EC

### What you expected to happen

java组件还不够友好，本来想着资源中心的东西可以复用，结果还是得用shell组件，然后定时把jar、sh放到每个worker上，太麻烦了

### How to reproduce

去使用一下Java组件即可，并且资源中心的是用的HDFS存储。

### Anything else

_No response_

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by ruanwenjun**
## Purpose of the pull request

In #12076, the resource table has been removed, this pr will remove this code and fix the resource file path in local file system is not correct in after download.

close #15343 
close #15344

## Brief change log

- Fix the resource path is not correct in worker
- Remove unused code about resource/ resource user which will not be used.

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

File: dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/shell/BaseLinuxShellInterceptorBuilder.java [hunk 1]
```diff
@@ -63,7 +63,12 @@
         Path shellAbsolutePath = shellAbsolutePath();
         FileUtils.createFileWith755(shellAbsolutePath);
         Files.write(shellAbsolutePath, finalScript.getBytes(), StandardOpenOption.APPEND);
-        log.info("Final Shell file is : \n{}", finalScript);
+        log.info("Final Shell file is: ");
+        log.info(
+                "****************************** Script Content *****************************************************************");
+        log.info(finalScript);
```
[the remark this answers is not in the document]
Comment (ruanwenjun) [reply dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/shell/BaseLinuxShellInterceptorBuilder.java:69]: We need to mask the log by logback.

File: dolphinscheduler-dao/src/main/resources/sql/upgrade/3.3.0_schema/mysql/dolphinscheduler_ddl.sql [hunk 2]
```diff
@@ -73,4 +73,7 @@ END;
 d//
 delimiter ;
 CALL modify_data_value_t_ds_dq_rule_input_entry;
-DROP PROCEDURE modify_data_value_t_ds_dq_rule_input_entry;
\ No newline at end of file
+DROP PROCEDURE modify_data_value_t_ds_dq_rule_input_entry;
+
+DROP TABLE IF EXISTS `t_ds_resources`;
+DROP TABLE IF EXISTS `t_ds_relation_resources_user`;
```
Comment (caishunfeng) [inline dolphinscheduler-dao/src/main/resources/sql/upgrade/3.3.0_schema/mysql/dolphinscheduler_ddl.sql]: This is a dangerous and irreversible operation, I don't think it should be added in ddl.

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/ResourcesController.java [hunk 3]
```diff
@@ -625,46 +623,6 @@ public Result deleteUdfFunc(@Parameter(hidden = true) @RequestAttribute(value =
...
-     * @return authorized result
-     */
-    @Operation(summary = "authorizedFile", description = "AUTHORIZED_FILE_NOTES")
-    @Parameters({
-            @Parameter(name = "userId", description = "USER_ID", required = true, schema = @Schema(implementation = int.class, example = "100"))
-    })
-    @GetMapping(value = "/authed-file")
-    @ResponseStatus(HttpStatus.CREATED)
-    @ApiException(AUTHORIZED_FILE_RESOURCE_ERROR)
-    public Result authorizedFile(@Parameter(hidden = true) @RequestAttribute(value = Constants.SESSION_USER) User loginUser,
```
Comment (caishunfeng) [inline dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/ResourcesController.java:642]: Should change the ui together?

Comment (ruanwenjun) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/ResourcesController.java:642]: No, this has already been removed from ui.

File: dolphinscheduler-dao/src/main/resources/sql/upgrade/3.3.0_schema/mysql/dolphinscheduler_ddl.sql (hunk 2 above)
Comment (ruanwenjun) [reply dolphinscheduler-dao/src/main/resources/sql/upgrade/3.3.0_schema/mysql/dolphinscheduler_ddl.sql]: Ok, I revert this change, and add `@Deprecated` in `t_ds_relation_resources_user` and `t_ds_resources`.
This will cause we create this two tables in new version.

**Review by caishunfeng — APPROVED** [review]
LGTM overall
