### PR TITLE
fix jdbc connect parameters can not input '@' and '.' character

### LINKED ISSUE #8135: [Bug] [DataSource] jdbc connect parameters can not input '@'
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

In 2.0.2 version, when I create hive datasource with kerberos, then need input principal to jdbc connect parameters, 
when Test connect , The error is reported below
image

### What you expected to happen

when input correct  principal, can connect to hive
image

### How to reproduce

in AbstractDatasourceProcessor.java,  modify PARAMS_PATTER  field, appropriate value is  
> private static final PARAMS_PATTER = Pattern.compile("^[a-zA-Z0-9\\-\\_\\/\\@\\.]+$");

### Anything else

_No response_

### Version

2.0.2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by zhuxt2015**
This closes #8135

## Purpose of the pull request
fix jdbc connect parameters can not input '@' and '.' character

## Verify this pull request

This pull request is already covered by existing tests, such as *(please describe tests)*.

can input '@' or '.' character in jdbc connect parameters 
image

### CODE REVIEW

**Comment by zhongjiajie** [comment]
Could you add some unit test to it? @zhuxt2015

**Comment by zhuxt2015** [comment]
> Could you add some unit test to it? @zhuxt2015

yes, I'll add a unit test

File: dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-api/src/test/java/org/apache/dolphinscheduler/plugin/datasource/api/datasource/AbstractDataSourceProcessorTest.java [hunk 1]
```diff
@@ -0,0 +1,50 @@
...
+ */
+public class AbstractDataSourceProcessorTest {
+
+    @Test
+    public void checkOtherTest() {
+        AbstractDataSourceProcessor mock = mock(AbstractDataSourceProcessor.class);
+        Map<String, String> other = new HashMap<>();
+        other.put("arg0", "1Aa-_/@.");
+        mock.checkOther(other);
+        verify(mock, times(1)).checkOther(other);
```
Comment (zhongjiajie) [inline dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-api/src/test/java/org/apache/dolphinscheduler/plugin/datasource/api/datasource/AbstractDataSourceProcessorTest.java]: I am not sure whether this syntax make actually test, could you please make a double check here @caishunfeng

File: dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-api/src/test/java/org/apache/dolphinscheduler/plugin/datasource/api/datasource/AbstractDataSourceProcessorTest.java [hunk 2]
```diff
@@ -0,0 +1,50 @@
...
+import java.util.HashMap;
+import java.util.Map;
+
+import static org.mockito.Mockito.*;
+
+/**
+ * @author: zhuxuetong
+ * @date: 2022/2/8 16:06
+ * @Description:
+ */
```
Comment (zhongjiajie) [inline dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-api/src/test/java/org/apache/dolphinscheduler/plugin/datasource/api/datasource/AbstractDataSourceProcessorTest.java]: We should remove this comment cause code belong ASF instead of code owner
```suggestion
```

File: dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-api/src/test/java/org/apache/dolphinscheduler/plugin/datasource/api/datasource/AbstractDataSourceProcessorTest.java (hunk 1 above)
Comment (zhongjiajie) [reply dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-api/src/test/java/org/apache/dolphinscheduler/plugin/datasource/api/datasource/AbstractDataSourceProcessorTest.java]: ping @caishunfeng again

**Comment by zhuxt2015** [comment]
Error:  SonarCloud server [https://sonarcloud.io/] can not be reached   @zhongjiajie   I don't know why appear  this error,  can you help me resolve

File: dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-api/src/test/java/org/apache/dolphinscheduler/plugin/datasource/api/datasource/AbstractDataSourceProcessorTest.java (hunk 1 above)
Comment (caishunfeng) [reply dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-api/src/test/java/org/apache/dolphinscheduler/plugin/datasource/api/datasource/AbstractDataSourceProcessorTest.java]: It seems to test checkOther twice, maybe the first one should be removed.

File: dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-api/src/test/java/org/apache/dolphinscheduler/plugin/datasource/api/datasource/AbstractDataSourceProcessorTest.java [hunk 3]
```diff
@@ -0,0 +1,45 @@
...
+import java.util.HashMap;
+import java.util.Map;
+
+import static org.mockito.Mockito.*;
+
+public class AbstractDataSourceProcessorTest {
+
+    @Test
+    public void checkOtherTest() {
+        AbstractDataSourceProcessor mock = mock(AbstractDataSourceProcessor.class);
```
Comment (caishunfeng) [inline dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-api/src/test/java/org/apache/dolphinscheduler/plugin/datasource/api/datasource/AbstractDataSourceProcessorTest.java]:
```suggestion
        AbstractDataSourceProcessor mockDataSourceProcessor = mock(AbstractDataSourceProcessor.class);
```

File: dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-api/src/test/java/org/apache/dolphinscheduler/plugin/datasource/api/datasource/AbstractDataSourceProcessorTest.java [hunk 4]
```diff
@@ -0,0 +1,45 @@
...
+        Map<String, String> other = new HashMap<>();
+        other.put("arg0", "1Aa-_/@.");
```
Comment (caishunfeng) [inline dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-api/src/test/java/org/apache/dolphinscheduler/plugin/datasource/api/datasource/AbstractDataSourceProcessorTest.java]: can you use the real case to test?

**Review by caishunfeng — COMMENTED** [review]
Look good to me if CI pass, thanks for your contribution

**Comment by zhongjiajie** [comment]
I restart the failing CI just now

**Review by caishunfeng — APPROVED** [review]
LGTM

**Comment by zhongjiajie** [comment]
Thanks @caishunfeng for reviewing
