### PR TITLE
[Fix-17906] Fix can't get pod's log in k8s task

### LINKED ISSUE #17906: [Bug] [TaskPlugin-K8s] Can't get pod's log
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

K8s task execute success,but  can't ge pods's log,  worker's log report error: Handle pod log error, java.util.concurrent.ExecutionException: java.lang.RuntimeException: io.fabric8.kubernetes.client.KubernetesClientException: namespace cannot be null
 

logs content:
[WI-0][TI-29] - 2026-01-26 18:40:32.097 INFO  [exclusive-task-executor-container-worker-2] o.a.d.p.t.a.l.TaskInstanceLogHeader:[37] - 🐬 Load Task Instance Plugin
[WI-0][TI-29] - 2026-01-26 18:40:32.097 INFO  [exclusive-task-executor-container-worker-2] o.a.d.s.w.e.PhysicalTaskExecutor:[66] - Initialized physicalTask: K8S successfully
[WI-0][TI-29] - 2026-01-26 18:40:32.097 INFO  [exclusive-task-executor-container-worker-2] o.a.d.p.t.k.K8sTask:[83] - Initialize k8s task params:{
  "localParams" : [ ],
  "varPool" : [ ],
  "image" : "busybox:1.30.1",
  "namespace" : "default",
  "command" : "[\"/bin/sh\", \"-c\", \"date && sleep 20 && date\"]",
  "args" : null,
  "pullSecret" : null,
  "imagePullPolicy" : "IfNotPresent",
  "minCpuCores" : 0.0,
  "minMemorySpace" : 0.0,
  "customizedLabels" : [ ],
  "nodeSelectors" : [ ],
  "kubeConfig" : "apiVersion: v1\nclusters:\n- cluster:\n    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJUm93enZFcW1QMjR3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TmpBeE1USXdPRE01TXpOYUZ3MHpOakF4TVRBd09EUTBNek5hTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURQMnBtc0FCck9KakVqc3Exa2hrZFp4SytldHNLbFgwOTZwMWdVbm9BRnhmVnlYV2ozRE9wUmZoSE8KZ284aU8rVUpVeFdDL1R5ajJiUEZBQTZYbkFTZHhkUlFVcFd5WFFVZWFFRVp1TG1ZcUhQT1dFS3BscmpKNFF6SwpvRUh2THFVMmFRd0VXdXpWaEFSTVBGZUp6NU1KdFdmL0NtdnpBcjBzcFdZUW9rYmN3OW9Hc3BnQmxwanlaSGFLCmF2dXp5YnZWYU1tSmxBVGZ4Ty80T3Nock5WTjAxU0xEa3Q3bGd3ZHZSNGc5RlByNWt3NCtGbWR2K3N0c2xTRUMKOGhFNWV6ekI2YmtZZ3c2QithVHVSczNlTTYwVTE4dkdwNUlNQzl5aVdFelJmOVpsbElYR2krR29XMDNlMVBMMApRc1hrZ1FyMzJtMGZuaHBVVHdxaExYV1VsVCsvQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJRdkk3dzVzSERTczNyY3p6NlFHcFNYeVpuV2l6QVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRRE1WeUlXK0lWNQo1eGQxY3Y5M0tUYU5EeW5VRVk1a0VNd2IvRmFWT1dRZFBPa3RFejA2eng4aEVUWFl1QXRUajJYM1MxdW5pckZNCktCUncxWWpsbWdiY2xTNXlGam5YTHhUKzM5eENsUkN2dlpTTForYXhsKzExZnVNajFQVjVMQk15UjRRNWI1bVYKd25nTFRvMkRodkNUeVpFeVp5bFdHWDlXMVFaMkpva3hFUGhZS2hsM2IvUFV0dUhOY3JRZGxFWkFRaS9XSERvNgpUT1JhUnFZbHNwS3pVTm01NEcxL0hvc3JvN2pGanNudy9VdW8zWDlET0dKdXZGa3ZMSnlyekdIL2lMRUxlWjFrCjBEcVpDa2llblpVWE9ZNnNqNnVTNWFnWXhYaHdIekZVcmhiSU5hV2ZoTjQ0amUwS3duN08wNTRPQzJTY3MyVHcKZnpkNnZYTzNGZ3Z0Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K\n    server: https://192.168.9.210:6443\n  name: kubernetes\ncontexts:\n- context:\n    cluster: kubernetes\n    user: kubernetes-admin\n  name: kubernetes-admin@kubernetes\ncurrent-context: kubernetes-admin@kubernetes\nkind: Config\npreferences: {}\nusers:\n- name: kubernetes-admin\n  user:\n    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJVENDQWdtZ0F3SUJBZ0lJTExJd2RxNEZvbTh3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TmpBeE1USXdPRE01TXpOYUZ3MHlOekF4TVRJd09EUTBNelZhTURReApGekFWQmdOVkJBb1REbk41YzNSbGJUcHRZWE4wWlhKek1Sa3dGd1lEVlFRREV4QnJkV0psY201bGRHVnpMV0ZrCmJXbHVNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXRhY1dvSTV2Vmd4aXpGdGcKSWhiTmovdU5JeTlwSFJ1bkl4SDBFb3BnY1VzaXVZTm5ET29PWXFFV092QTJHejZqR2VEajZUYWdCcDRQZjlmUQpDOEs2eklYU0NDRzdqTEV2UHc0d3BvSWNJYWlFa1hoM1lCajR6RE5zR0hCVkRXS3dqaVJrMStZMzA4VFNwdFRYCkZDRVh4S2loSzFMK05BNUlCenhyanZQWXFzNFIyZm00bnp3ZlRnbXkydEhCWkFpVXBFZWJocHZoRi9uNGZNcmsKLzAvT3JHbHIzZlVPc3UyOUtJR0haZmJabFlGeGMxYVJJUy9hb1dtQ0FXekJBL2lXLzVTY1FremVGYXhVZWFyWQpDUGd1eEEySGExNU83eW1JWEo1eUF2T1puNzVvSTY3UHpqZjE5VUFSeSs5RzlkdEh5Y3lDcU95NDlnYm1CTzlHCm0zTE5Hd0lEQVFBQm8xWXdWREFPQmdOVkhROEJBZjhFQkFNQ0JhQXdFd1lEVlIwbEJBd3dDZ1lJS3dZQkJRVUgKQXdJd0RBWURWUjBUQVFIL0JBSXdBREFmQmdOVkhTTUVHREFXZ0JRdkk3dzVzSERTczNyY3p6NlFHcFNYeVpuVwppekFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBU2hRQ3lqQm9QMkVKZWRuOWplamk4aXplZHl0UlZqbWpYUGd1CjJyNVVqTTBudjFlb2o3Z0dJckJYazBrWnEzb3B3azg3Z1E2d2ovZnd6YTdXZUZ4YzdoTlVTS2p6TmlyejNKWFUKRXlSU3hMUHlhTHRZK0JWUlJ2WDBzZTFMemJya215R2dBNWJOcmw4bm92YmR5MFliYWxsbm8yYkNIaWprZ0J5bApQYU5SckRjZ25Nd3R6c3VNTHhLS2Y3TjNvQXhHeENGMUk4ZHNTbWNPWUJad1NTQ1p1SDB5QUVNR0k3MjdqdmlQCkVKNzVVUnlRVmsyL1RrQkt0ZHNPT25lOWM5eGVYR3RWRm9ZS0pLeU1UcThOU3VzZTZzalI2U0V5eGVKcWlLL2wKb1BNWi9vckg5eml2S2dSSi9zSjg5ZklSMTFLamFyQ2NGYzN3Qk1RaEpUSzhMVXRka3c9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==\n    client-key-data: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBdGFjV29JNXZWZ3hpekZ0Z0loYk5qL3VOSXk5cEhSdW5JeEgwRW9wZ2NVc2l1WU5uCkRPb09ZcUVXT3ZBMkd6NmpHZURqNlRhZ0JwNFBmOWZRQzhLNnpJWFNDQ0c3akxFdlB3NHdwb0ljSWFpRWtYaDMKWUJqNHpETnNHSEJWRFdLd2ppUmsxK1kzMDhUU3B0VFhGQ0VYeEtpaEsxTCtOQTVJQnp4cmp2UFlxczRSMmZtNApuendmVGdteTJ0SEJaQWlVcEVlYmhwdmhGL240Zk1yay8wL09yR2xyM2ZVT3N1MjlLSUdIWmZiWmxZRnhjMWFSCklTL2FvV21DQVd6QkEvaVcvNVNjUWt6ZUZheFVlYXJZQ1BndXhBMkhhMTVPN3ltSVhKNXlBdk9abjc1b0k2N1AKempmMTlVQVJ5KzlHOWR0SHljeUNxT3k0OWdibUJPOUdtM0xOR3dJREFRQUJBb0lCQVFDSnNybzlSUnR5bi9yNApyRCtJTjc3bGFTdEl3N1NyZ3YzRVlPU2lkVkM4TU5lR3h1d0Q1eHkyZVNQUDA2MUFJOUFoV3MrSlJvWXgzZmtqCjBPVjlOTVRES3FIVzFqTkVhRC9IVGF0bFhQV1VNaGtqNkt5ZEpQRGNZaEtMeUFOQkhWRjJ2bkhQRTAyNGN0ZTMKN1ZtSWdibHhzdDVSYUIwWU9zY3c3UVVmblFyZUZnV1VKNzRyTXNVRjErM0R4QzJYMEc2WGhrTW1XTUpVOC9hRgpXYXZ2V1JJdlo3TmRra3Y5T2t6ZjZqaXlzLytUOEJOWUxJbkt2UHlYL2xQV01pbUU4UFhhQTNIS09Xb2Z4cUFkCnhudnE4d1ZkUnVSWERJNGVuZDVFYWF6S0RTb1IzOXR0K0ZWNGcvVkxvTE4zd0lXK1BmWnJuUk1UTlgwSUVEZ1IKV3pQU25kWFJBb0dCQU1kclBkQktrWkVSaEZsSFJaTlNuTWYxZlFjdnR5enpubGZyVmUrZmM0ek5NS2s4VEhqRQptQjBVWk0zUHNWSFRRcmhqMHBweXN1QkRFZjNtc2lRclZKQkFoTU12MUQ0NE1iN3F4SE9KRlFWeWdDd1dzeFpJCmJOU21DdldaR1gzVWtMQzFZdTgwdzIwQTRwb0gvc0tvNGtPVW9EN0p4SitsY3lwbFZ6WlpHMEFUQW9HQkFPa3gKWm41WHFSWDV5enVlTHcvWVl2c0RyY2FBWlpMWmROTEhPUi9rZHZIb3ZDSlg2MjhJWndXR3RMbzRvWi92OXdiUApIT1JONVJHTlpuU29iYTI2S3djald0WXNOR0t6eFdXd2JEN1lBQTdxOC9ZMlRBNzJSUldIRGYvZXVyTXM4c29aCjhtR292MUtZeU5lVnFqWHpBdi9zS3FpeUNkcXRHc043NnZYUjBpL1pBb0dBRUJLQ251RURybTk4L1QwVFRIWmkKRUhPbXFnZWNlZEVBdUJGTmtjeUdJWmtBRFFQQkhoS3FOOTNHNmhlTk1RMFgyWWlpRnJTYjJodE52ZXJ6L0pwSgpiSDdtdEZ5TWZKOUcweDVVeXdNSFlMTUR4WW5tMFNyeEtvcGZZNy85SC9rYjJFSW1RU1U5Z3ZHSlVlVEhFYVZPCjV5ZDVhdFlVTk5HKzRISGVmNURhODJVQ2dZRUF1SGF0ZncvVTMxOWoxdHRBbXlZdTFpV0kxMWRHQWk0bWJYM08Kd0YyM2daRDdFYWUrdzJ4QUltejJsY0NxaVp3SEtzbTNMeG8zTS9WSXNNdHpSMVBYS2FSYi9NT25CTlQwTjRhaAplZXpmenUwbzR3RDhsWEZXSUx0ZTVhTEl5V2VxL3hnYlZnbG9udXZoSkRodUZwTVBNbWNkTDZqMmhwY2NicnFkCm1Lckx1N0VDZ1lCcS9kZ01FWE9XNEFoM0JPVjRHWHhKZkh0V2Y0S3daK2dUczVVWjRUTHB2NTdpbVplUWRreEUKZkl1QWdPNDlBUE1rNTlpOTAvU2ZweElVNFptMno4TkFudGRyL3QzdXhLdGZJUDJjc0hsaWlxVDZhQzZBRWd0Zwp1V205ck1SYXlPSWpnN1F5aExONi9NRnFEZEZNSTZFTnZjeWZlTktiYzZReTZzU3JRcFhrdHc9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=",
  "datasource" : 1,
  "type" : "K8S"
}
[WI-0][TI-29] - 2026-01-26 18:40:32.098 INFO  [exclusive-task-executor-container-worker-2] o.a.d.s.w.e.PhysicalTaskExecutor:[71] - Set taskVarPool: null successfully
[WI-0][TI-29] - 2026-01-26 18:40:32.098 INFO  [exclusive-task-executor-container-worker-2] o.a.d.p.t.a.l.TaskInstanceLogHeader:[41] - 🐬 Execute Task Instance
[WI-0][TI-29] - 2026-01-26 18:40:32.105 INFO  [exclusive-task-executor-container-worker-2] o.a.d.p.t.a.k.i.K8sTaskExecutor:[342] - [K8sJobExecutor-k8s-test-29] start to submit job
[WI-0][TI-29] - 2026-01-26 18:40:32.135 INFO  [PhysicalTaskExecutorEventBusCoordinator-eventbus-coordinator-worker-0] o.a.d.t.e.e.TaskExecutorLifecycleEventRemoteReporter:[111] - Report : {
  "taskInstanceId" : 29,
  "eventCreateTime" : 1769424032086,
  "type" : "DISPATCHED",
  "workflowInstanceId" : 28,
  "taskInstanceHost" : "ds-worker-0.ds-worker-headless:1234",
  "latestReportTime" : null
}
[WI-0][TI-29] - 2026-01-26 18:40:32.135 INFO  [PhysicalTaskExecutorEventBusCoordinator-eventbus-coordinator-worker-0] o.a.d.t.e.e.TaskExecutorEventBusCoordinator:[191] - Success fire TaskExecutorDispatchedLifecycleEvent: {"taskInstanceId":29,"eventCreateTime":1769424032086,"type":"DISPATCHED","workflowInstanceId":28,"taskInstanceHost":"ds-worker-0.ds-worker-headless:1234","latestReportTime":null} 
[WI-0][TI-29] - 2026-01-26 18:40:32.137 INFO  [PhysicalTaskExecutorLifecycleEventReporter] o.a.d.e.m.TaskExecutorEventRemoteReporterClient:[73] - Report: TaskExecutorDispatchedLifecycleEvent(super=AbstractTaskExecutorLifecycleEvent(super=AbstractDelayEvent(delayTime=0, createTimeInNano=1227292260721866, expiredTimeInNano=1227292260722974), taskInstanceId=29, eventCreateTime=1769424032086, type=DISPATCHED), workflowInstanceId=28, taskInstanceHost=ds-worker-0.ds-worker-headless:1234, latestReportTime=1769424032135) to master success
[WI-0][TI-29] - 2026-01-26 18:40:32.172 INFO  [exclusive-task-executor-container-worker-2] o.a.d.p.t.a.k.i.K8sTaskExecutor:[347] - [K8sJobExecutor-k8s-test-29] submitted job successfully
[WI-28][TI-29] - 2026-01-26 18:40:32.176 INFO  [OkHttp https://192.168.9.210:6443/...] o.a.d.p.t.a.k.i.K8sTaskExecutor:[211] - event received : job:k8s-test-29 action:ADDED
[WI-0][TI-29] - 2026-01-26 18:40:32.185 INFO  [PhysicalTaskExecutorEventBusCoordinator-eventbus-coordinator-worker-2] o.a.d.t.e.e.TaskExecutorLifecycleEventRemoteReporter:[111] - Report : {
  "taskInstanceId" : 29,
  "eventCreateTime" : 1769424032096,
  "type" : "RUNNING",
  "workflowInstanceId" : 28,
  "taskInstanceHost" : "ds-worker-0.ds-worker-headless:1234",
  "startTime" : 1769424032091,
  "logPath" : "/opt/dolphinscheduler/logs/20260126/163804963238144/8/28/29.log",
  "executePath" : "/tmp/dolphinscheduler/exec/process/29",
  "latestReportTime" : null
}
[WI-0][TI-29] - 2026-01-26 18:40:32.185 INFO  [PhysicalTaskExecutorEventBusCoordinator-eventbus-coordinator-worker-2] o.a.d.t.e.e.TaskExecutorEventBusCoordinator:[191] - Success fire TaskExecutorStartedLifecycleEvent: {"taskInstanceId":29,"eventCreateTime":1769424032096,"type":"RUNNING","workflowInstanceId":28,"taskInstanceHost":"ds-worker-0.ds-worker-headless:1234","startTime":1769424032091,"logPath":"/opt/dolphinscheduler/logs/20260126/163804963238144/8/28/29.log","executePath":"/tmp/dolphinscheduler/exec/process/29","latestReportTime":null} 
[WI-0][TI-0] - 2026-01-26 18:40:32.196 INFO  [WorkerRpcServer-methodInvoker-19] o.a.d.s.w.r.PhysicalTaskExecutorOperatorImpl:[101] - Receive TaskExecutorLifecycleEventAck: ITaskExecutorLifecycleEventReporter.TaskExecutorLifecycleEventAck(taskExecutorId=29, taskExecutorLifecycleEventType=DISPATCHED)
[WI-0][TI-0] - 2026-01-26 18:40:32.197 INFO  [WorkerRpcServer-methodInvoker-19] o.a.d.t.e.e.TaskExecutorLifecycleEventRemoteReporter:[137] - Success removed TaskExecutorDispatchedLifecycleEvent(super=AbstractTaskExecutorLifecycleEvent(super=AbstractDelayEvent(delayTime=0, createTimeInNano=1227292260721866, expiredTimeInNano=1227292260722974), taskInstanceId=29, eventCreateTime=1769424032086, type=DISPATCHED), workflowInstanceId=28, taskInstanceHost=ds-worker-0.ds-worker-headless:1234, latestReportTime=1769424032135) by ack: ITaskExecutorLifecycleEventReporter.TaskExecutorLifecycleEventAck(taskExecutorId=29, taskExecutorLifecycleEventType=DISPATCHED)
[WI-28][TI-29] - 2026-01-26 18:40:32.199 INFO  [OkHttp https://192.168.9.210:6443/...] o.a.d.p.t.a.k.i.K8sTaskExecutor:[211] - event received : job:k8s-test-29 action:MODIFIED
[WI-28][TI-29] - 2026-01-26 18:40:32.200 INFO  [OkHttp https://192.168.9.210:6443/...] o.a.d.p.t.a.k.i.K8sTaskExecutor:[218] - job k8s-test-29 status 1
[WI-0][TI-29] - 2026-01-26 18:40:32.201 INFO  [PhysicalTaskExecutorLifecycleEventReporter] o.a.d.e.m.TaskExecutorEventRemoteReporterClient:[73] - Report: TaskExecutorStartedLifecycleEvent(super=AbstractTaskExecutorLifecycleEvent(super=AbstractDelayEvent(delayTime=0, createTimeInNano=1227292271200841, expiredTimeInNano=1227292271201759), taskInstanceId=29, eventCreateTime=1769424032096, type=RUNNING), workflowInstanceId=28, taskInstanceHost=ds-worker-0.ds-worker-headless:1234, startTime=1769424032091, logPath=/opt/dolphinscheduler/logs/20260126/163804963238144/8/28/29.log, executePath=/tmp/dolphinscheduler/exec/process/29, latestReportTime=1769424032197) to master success
[WI-0][TI-0] - 2026-01-26 18:40:32.301 INFO  [WorkerRpcServer-methodInvoker-20] o.a.d.s.w.r.PhysicalTaskExecutorOperatorImpl:[101] - Receive TaskExecutorLifecycleEventAck: ITaskExecutorLifecycleEventReporter.TaskExecutorLifecycleEventAck(taskExecutorId=29, taskExecutorLifecycleEventType=RUNNING)
[WI-0][TI-0] - 2026-01-26 18:40:32.301 INFO  [WorkerRpcServer-methodInvoker-20] o.a.d.t.e.e.TaskExecutorLifecycleEventRemoteReporter:[137] - Success removed TaskExecutorStartedLifecycleEvent(super=AbstractTaskExecutorLifecycleEvent(super=AbstractDelayEvent(delayTime=0, createTimeInNano=1227292271200841, expiredTimeInNano=1227292271201759), taskInstanceId=29, eventCreateTime=1769424032096, type=RUNNING), workflowInstanceId=28, taskInstanceHost=ds-worker-0.ds-worker-headless:1234, startTime=1769424032091, logPath=/opt/dolphinscheduler/logs/20260126/163804963238144/8/28/29.log, executePath=/tmp/dolphinscheduler/exec/process/29, latestReportTime=1769424032197) by ack: ITaskExecutorLifecycleEventReporter.TaskExecutorLifecycleEventAck(taskExecutorId=29, taskExecutorLifecycleEventType=RUNNING)
[WI-28][TI-29] - 2026-01-26 18:40:34.809 INFO  [OkHttp https://192.168.9.210:6443/...] o.a.d.p.t.a.k.i.K8sTaskExecutor:[211] - event received : job:k8s-test-29 action:MODIFIED
[WI-28][TI-29] - 2026-01-26 18:40:34.810 INFO  [OkHttp https://192.168.9.210:6443/...] o.a.d.p.t.a.k.i.K8sTaskExecutor:[218] - job k8s-test-29 status 1
[WI-28][TI-29] - 2026-01-26 18:40:54.851 INFO  [OkHttp https://192.168.9.210:6443/...] o.a.d.p.t.a.k.i.K8sTaskExecutor:[211] - event received : job:k8s-test-29 action:MODIFIED
[WI-28][TI-29] - 2026-01-26 18:40:54.852 INFO  [OkHttp https://192.168.9.210:6443/...] o.a.d.p.t.a.k.i.K8sTaskExecutor:[218] - job k8s-test-29 status 1
[WI-28][TI-29] - 2026-01-26 18:40:55.856 INFO  [OkHttp https://192.168.9.210:6443/...] o.a.d.p.t.a.k.i.K8sTaskExecutor:[211] - event received : job:k8s-test-29 action:MODIFIED
[WI-28][TI-29] - 2026-01-26 18:40:55.856 INFO  [OkHttp https://192.168.9.210:6443/...] o.a.d.p.t.a.k.i.K8sTaskExecutor:[218] - job k8s-test-29 status 1
[WI-28][TI-29] - 2026-01-26 18:40:55.866 INFO  [OkHttp https://192.168.9.210:6443/...] o.a.d.p.t.a.k.i.K8sTaskExecutor:[211] - event received : job:k8s-test-29 action:MODIFIED
[WI-28][TI-29] - 2026-01-26 18:40:55.867 INFO  [OkHttp https://192.168.9.210:6443/...] o.a.d.p.t.a.k.i.K8sTaskExecutor:[218] - job k8s-test-29 status 0
[WI-28][TI-29] - 2026-01-26 18:40:55.867 INFO  [OkHttp https://192.168.9.210:6443/...] o.a.d.p.t.a.k.i.K8sTaskExecutor:[384] - [K8sJobExecutor-k8s-test-29] succeed in k8s
[WI-0][TI-29] - 2026-01-26 18:40:55.870 ERROR [exclusive-task-executor-container-worker-2] o.a.d.p.t.a.k.i.K8sTaskExecutor:[314] - Handle pod log error
java.util.concurrent.ExecutionException: java.lang.RuntimeException: io.fabric8.kubernetes.client.KubernetesClientException: namespace cannot be null
  at java.util.concurrent.FutureTask.report(FutureTask.java:122)
  at java.util.concurrent.FutureTask.get(FutureTask.java:192)
  at org.apache.dolphinscheduler.plugin.task.api.k8s.impl.K8sTaskExecutor.run(K8sTaskExecutor.java:312)
  at org.apache.dolphinscheduler.plugin.task.api.k8s.AbstractK8sTask.handle(AbstractK8sTask.java:52)
  at org.apache.dolphinscheduler.server.worker.executor.PhysicalTaskExecutor.doTriggerTaskPlugin(PhysicalTaskExecutor.java:77)
  at org.apache.dolphinscheduler.task.executor.AbstractTaskExecutor.start(AbstractTaskExecutor.java:81)
  at org.apache.dolphinscheduler.task.executor.worker.TaskExecutorWorker.start(TaskExecutorWorker.java:65)
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.RuntimeException: io.fabric8.kubernetes.client.KubernetesClientException: namespace cannot be null
  at org.apache.dolphinscheduler.plugin.task.api.k8s.impl.K8sTaskExecutor.lambda$parsePodLogOutput$0(K8sTaskExecutor.java:283)
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
  ... 3 common frames omitted
Caused by: io.fabric8.kubernetes.client.KubernetesClientException: namespace cannot be null
  at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.inNamespace(BaseOperation.java:235)
  at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.inNamespace(BaseOperation.java:88)
  at org.apache.dolphinscheduler.plugin.task.api.am.KubernetesApplicationManager.getListenPod(KubernetesApplicationManager.java:111)
  at org.apache.dolphinscheduler.plugin.task.api.am.KubernetesApplicationManager.getPodLogWatcher(KubernetesApplicationManager.java:199)
  at org.apache.dolphinscheduler.plugin.task.api.utils.ProcessUtils.getPodLogWatcher(ProcessUtils.java:425)
  at org.apache.dolphinscheduler.plugin.task.api.k8s.impl.K8sTaskExecutor.lambda$parsePodLogOutput$0(K8sTaskExecutor.java:273)
  ... 7 common frames omitted
[WI-0][TI-29] - 2026-01-26 18:40:55.872 INFO  [exclusive-task-executor-container-worker-2] o.a.d.t.e.e.TaskExecutorEventBus:[32] - Publish TaskExecutorSuccessLifecycleEvent: {
  "taskInstanceId" : 29,
  "eventCreateTime" : 1769424055872,
  "type" : "SUCCESS",
  "workflowInstanceId" : 28,
  "taskInstanceHost" : "ds-worker-0.ds-worker-headless:1234",
  "endTime" : 1769424055872,
  "varPool" : null,
  "latestReportTime" : null
}
[WI-0][TI-29] - 2026-01-26 18:40:55.883 INFO  [PhysicalTaskExecutorEventBusCoordinator-eventbus-coordinator-worker-13] o.a.d.t.e.e.TaskExecutorLifecycleEventRemoteReporter:[111] - Report : {
  "taskInstanceId" : 29,
  "eventCreateTime" : 1769424055872,
  "type" : "SUCCESS",
  "workflowInstanceId" : 28,
  "taskInstanceHost" : "ds-worker-0.ds-worker-headless:1234",
  "endTime" : 1769424055872,
  "varPool" : null,
  "latestReportTime" : null
}
[WI-0][TI-29] - 2026-01-26 18:40:55.884 INFO  [PhysicalTaskExecutorEventBusCoordinator-eventbus-coordinator-worker-13] o.a.d.t.e.e.TaskExecutorEventBusCoordinator:[191] - Success fire TaskExecutorSuccessLifecycleEvent: {"taskInstanceId":29,"eventCreateTime":1769424055872,"type":"SUCCESS","workflowInstanceId":28,"taskInstanceHost":"ds-worker-0.ds-worker-headless:1234","endTime":1769424055872,"varPool":null,"latestReportTime":null} 
[WI-0][TI-29] - 2026-01-26 18:40:55.887 INFO  [PhysicalTaskExecutorLifecycleEventReporter] o.a.d.e.m.TaskExecutorEventRemoteReporterClient:[73] - Report: TaskExecutorSuccessLifecycleEvent(super=AbstractTaskExecutorLifecycleEvent(super=AbstractDelayEvent(delayTime=0, createTimeInNano=1227316046622551, expiredTimeInNano=1227316046623411), taskInstanceId=29, eventCreateTime=1769424055872, type=SUCCESS), workflowInstanceId=28, taskInstanceHost=ds-worker-0.ds-worker-headless:1234, endTime=1769424055872, varPool=null, latestReportTime=1769424055884) to master success
[WI-0][TI-0] - 2026-01-26 18:40:55.930 INFO  [WorkerRpcServer-methodInvoker-21] o.a.d.s.w.r.PhysicalTaskExecutorOperatorImpl:[101] - Receive TaskExecutorLifecycleEventAck: ITaskExecutorLifecycleEventReporter.TaskExecutorLifecycleEventAck(taskExecutorId=29, taskExecutorLifecycleEventType=SUCCESS)
[WI-0][TI-0] - 2026-01-26 18:40:55.930 INFO  [WorkerRpcServer-methodInvoker-21] o.a.d.t.e.e.TaskExecutorLifecycleEventRemoteReporter:[137] - Success removed TaskExecutorSuccessLifecycleEvent(super=AbstractTaskExecutorLifecycleEvent(super=AbstractDelayEvent(delayTime=0, createTimeInNano=1227316046622551, expiredTimeInNano=1227316046623411), taskInstanceId=29, eventCreateTime=1769424055872, type=SUCCESS), workflowInstanceId=28, taskInstanceHost=ds-worker-0.ds-worker-headless:1234, endTime=1769424055872, varPool=null, latestReportTime=1769424055884) by ack: ITaskExecutorLifecycleEventReporter.TaskExecutorLifecycleEventAck(taskExecutorId=29, taskExecutorLifecycleEventType=SUCCESS)
[WI-0][TI-0] - 2026-01-26 18:40:55.930 INFO  [WorkerRpcServer-methodInvoker-21] o.a.d.t.e.e.TaskExecutorEventBus:[32] - Publish TaskExecutorFinalizeLifecycleEvent: {
  "taskInstanceId" : 29,
  "eventCreateTime" : 1769424055930,
  "type" : "FINALIZE"
}
[WI-0][TI-29] - 2026-01-26 18:40:55.933 INFO  [PhysicalTaskExecutorEventBusCoordinator-eventbus-coordinator-worker-1] o.a.d.p.t.a.l.TaskInstanceLogHeader:[45] - 🐬 Finalize Task Instance
[WI-0][TI-29] - 2026-01-26 18:40:55.933 INFO  [PhysicalTaskExecutorEventBusCoordinator-eventbus-coordinator-worker-1] o.a.d.t.e.c.AbstractTaskExecutorContainer:[99] - FINALIZE_SESSION
[WI-0][TI-29] - 2026-01-26 18:40:55.934 INFO  [PhysicalTaskExecutorEventBusCoordinator-eventbus-coordinator-worker-1] o.a.d.s.w.u.TaskExecutionContextUtils:[117] - Deleted task exec directory: /tmp/dolphinscheduler/exec/process/29
[WI-0][TI-29] - 2026-01-26 18:40:55.934 INFO  [PhysicalTaskExecutorEventBusCoordinator-eventbus-coordinator-worker-1] o.a.d.t.e.e.TaskExecutorEventBusCoordinator:[191] - Success fire TaskExecutorFinalizeLifecycleEvent: {"taskInstanceId":29,"eventCreateTime":1769424055930,"type":"FINALIZE"} 

### What you expected to happen

nomally,  worker could get k8s pod's log

### How to reproduce

admin user: 
1. Security-- Cluster Manage -- Create a Cluster
2. Security-- K8S Namespace Manage -- Create a Namespace(named default, also test for other name ,like dolphinscheduler)
3. Security-- User Manage -- Create a User -- Authrize DataSource & NameSpace
4. Security-- Tenant Manage -- Create a Tenant

normal user:
1. Project -- Create a project
2. Project -- WorkFlow Definition -- Create a Workflow -- use Cloud-K8S
    select Datasource instances, 
    select Namespace(Cluster), [this step the namespace is setted !!!]
    set Image & Command
4. Online WorkFlow
5. Start WorkFlow --  modify user Tenant -- Confirm

### Anything else

_No response_

### Version

3.4.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by SbloodyS**
## Was this PR generated or assisted by AI?

Yes. UT was created by gpt 5.4.

## Brief change log

close #17906

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

## Pull Request Notice
[Pull Request Notice](https://github.com/apache/dolphinscheduler/blob/dev/docs/docs/en/contribute/join/pull-request.md)

If your pull request contains incompatible change, you should also add it to `docs/docs/en/guide/upgrade/incompatible.md`

### CODE REVIEW

File: dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/parameters/resource/DataSourceParameters.java [hunk 1]
```diff
@@ -19,38 +19,20 @@
 
 import org.apache.dolphinscheduler.spi.enums.DbType;
 
+import lombok.Data;
+import lombok.EqualsAndHashCode;
+
 import com.fasterxml.jackson.annotation.JsonProperty;
 
+@EqualsAndHashCode(callSuper = true)
+@Data
```
Comment (ruanwenjun) [inline dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/parameters/resource/DataSourceParameters.java:28]: Good job

**Review by ruanwenjun — APPROVED** [review]
