### PR TITLE
[Fix-9174] [Alert] Fix deduplication of alarm information

### LINKED ISSUE #9174: [Feature][Alarm] About alarm information deduplication
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

截屏2022-03-24 下午7 30 58
The current implementation uses the above sql in order to avoid duplication of alarm information.

its disadvantages：low performance.

Right way：When an alarm is generated, an alarm ID is generated

Recommended open source library：
[timeflake4j](https://github.com/making/timeflake4j)

### Use case

Improve performance

### Related issues

_No response_

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by czeming**
## Purpose of the pull request

This pr will close https://github.com/apache/dolphinscheduler/issues/9174.
1. Add range for alarm suppression.
2. Optimize query logic.

see https://github.com/apache/dolphinscheduler/commit/f8ecb536b71d6f33b71c73930832b62890b84ea1

## Supplement

I read commit `https://github.com/apache/dolphinscheduler/commit/f8ecb536b71d6f33b71c73930832b62890b84ea1` and class `org.apache.dolphinscheduler.dao.AlertDao`.

It modified method `org.apache.dolphinscheduler.dao.AlertDao#sendServerStopedAlert`, but other logics have not changed. I speculate that the scene this friend is facing is just to reduce the frequency of redundant machine alarms in a time period. Judging by whether the content is equal is the actual demand. I think adding message ID to judge by message ID will lead to the invalidation of the logic he added and make this judgment meaningless, because it is difficult for multiple redundant machine actions of the same host to occur at the same time point (the ID will obviously be different).

In addition, if my understanding is correct, there is a hidden danger in the submission itself. The following logic will cause the same host crash not to be notified in the future.

```
where content = #{alert.content} and alert_status = #{alert.alertStatus.code}
```
and
```
ServerAlertContent serverStopAlertContent = ServerAlertContent.newBuilder()
        .type(serverType)
        .host(host)
        .event(AlertEvent.SERVER_DOWN)
        .warningLevel(AlertWarnLevel.SERIOUS).
        build();
String content = JSONUtils.toJsonString(Lists.newArrayList(serverStopAlertContent));
```

To sum up, the needs of both parties are:
1. The redundant machine will not be notified repeatedly for a period of time
2. Improve processing efficiency

A low-cost change can be to change the judgment condition of SQL to
```
where content = #{alert.content} and alert_status = #{alert.alertStatus.code} and create_time >= ${No alarm start time}
```

However, if table `t_ds_alert` is used for more alarms in the future, its data volume may be more than now. Even if field `create_time` is used as a condition, there is still room for optimization when using field `content` to make an equal judgment.

We can consider adding a field to calculate the content and other information combinations representing the message content to calculate the signature information, and use this field as the judgment basis.

### CODE REVIEW

File: dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/AlertDao.java [hunk 1]
```diff
@@ -81,13 +77,27 @@ public int addAlert(Alert alert) {
...
         alert.setAlertStatus(alertStatus);
         alert.setUpdateTime(new Date());
         alert.setLog(log);
         return alertMapper.updateById(alert);
     }
 
+    /**
+     * 生成通知签名信息
+     * @param alert 通知实体
+     * @return 签名文本
```
Comment (lenboo) [inline dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/AlertDao.java]: @czeming English comments is recommended.

**Comment by lenboo** [comment]
@czeming Thank you for your contribution. Please note that there are some ut failures.

File: dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/AlertDao.java (hunk 1 above)
Comment (czeming) [reply dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/AlertDao.java]: Done

**Comment by czeming** [comment]
@lenboo please review again, thanks.

File: dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/AlertDao.java [hunk 2]
```diff
@@ -17,39 +17,35 @@
...
 import org.apache.dolphinscheduler.common.utils.JSONUtils;
-import org.apache.dolphinscheduler.dao.entity.Alert;
-import org.apache.dolphinscheduler.dao.entity.AlertPluginInstance;
-import org.apache.dolphinscheduler.dao.entity.AlertSendStatus;
-import org.apache.dolphinscheduler.dao.entity.ProcessAlertContent;
-import org.apache.dolphinscheduler.dao.entity.ProcessInstance;
-import org.apache.dolphinscheduler.dao.entity.ProjectUser;
-import org.apache.dolphinscheduler.dao.entity.ServerAlertContent;
-import org.apache.dolphinscheduler.dao.entity.TaskInstance;
+import org.apache.dolphinscheduler.dao.entity.*;
```
Comment (SbloodyS) [inline dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/AlertDao.java]: Please avoid import ```*```

File: dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/AlertDao.java [hunk 3]
```diff
@@ -17,39 +17,35 @@
...
-import java.util.List;
-import java.util.stream.Collectors;
-
+import org.joda.time.DateTime;
 import org.springframework.beans.factory.annotation.Autowired;
+import org.springframework.beans.factory.annotation.Value;
 import org.springframework.stereotype.Component;
 
-import com.google.common.collect.Lists;
+import java.util.*;
```
Comment (SbloodyS) [inline dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/AlertDao.java]: Same here.

Comment (czeming) [reply dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/AlertDao.java]: done, please review again, thanks.

**Comment by czeming** [comment]
@zhuangchong please help me with this review? Thx!

**Comment by zhuangchong** [comment]
Please resolve code conflicts first.

File: dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/AlertDao.java [hunk 4]
```diff
@@ -131,8 +156,11 @@ public void sendServerStopedAlert(int alertGroupId, String host, String serverTy
         alert.setAlertGroupId(alertGroupId);
         alert.setCreateTime(new Date());
         alert.setUpdateTime(new Date());
+        alert.setSign(generateSign(alert));
         // we use this method to avoid insert duplicate alert(issue #5525)
-        alertMapper.insertAlertWhenServerCrash(alert);
+        // we modified this method to optimize performance(issue #9174)
+        Date crashAlarmSuppressionStartTime = DateTime.now().plusMinutes(-crashAlarmSuppression).toDate();
+        alertMapper.insertAlertWhenServerCrash(alert, crashAlarmSuppressionStartTime);
```
Comment (zhuangchong) [inline dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/AlertDao.java:163]: This method is triggered when the master server or worker server stops, which is not a lot, I suggest that you don't need to add. Can be added to the alert server.

**Review by zhuangchong — APPROVED** [review]

File: dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/AlertDao.java (hunk 4 above)
Comment (zhuangchong) [inline dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/AlertDao.java:167]: This method is triggered when the master server or worker server stops, which is not a lot, I suggest that you don't need to add. Can be added to the alert server.

**Review by zhuangchong — CHANGES_REQUESTED** [review]

File: dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/AlertDao.java (hunk 4 above)
Comment (czeming) [reply dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/AlertDao.java:167]: I resolved the conflict.

Add reason for _crashAlarmSuppressionStartTime_: 
1. The addition of this parameter is a key condition for the initial screening of data, which can reduce the performance problems caused by the increase of data.
2. **If this parameter is not added, according to the current logic, the warning after the first time of the same host will not be added.**

Comment (zhuangchong) [reply dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/AlertDao.java:167]: You are right, it's me who didn't understand the requirement. Using `content` to determine is the problem.

**Comment by czeming** [comment]
@zhuangchong  please review again, thx!

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/registry/ServerNodeManager.java [hunk 5]
```diff
@@ -52,13 +54,8 @@
...
 
-import javax.annotation.PreDestroy;
-
-import org.slf4j.Logger;
-import org.slf4j.LoggerFactory;
-import org.springframework.beans.factory.InitializingBean;
-import org.springframework.beans.factory.annotation.Autowired;
-import org.springframework.stereotype.Service;
+import static org.apache.dolphinscheduler.common.Constants.REGISTRY_DOLPHINSCHEDULER_MASTERS;
+import static org.apache.dolphinscheduler.common.Constants.REGISTRY_DOLPHINSCHEDULER_WORKERS;
```
Comment (zhuangchong) [inline dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/registry/ServerNodeManager.java]: This part of checkstyle is wrong. It is not clear that CI has not detected it, but it can be detected locally. It is recommended to modify it.

**Review by zhuangchong — DISMISSED** [review]
+1

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/registry/ServerNodeManager.java (hunk 5 above)
Comment (czeming) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/registry/ServerNodeManager.java]: Is my mistake. I didn't import the style check configuration `style/checkstyle.xml`.

I have solved all the files related to my changes. In addition, I see many codes with the same problems.


I think we can improve the documentation provided to developers, which is expected to improve the quality of subsequent code.

From this configuration `style/checkstyle.xml` > `ImportOrder`:

```
        <module name="ImportOrder">
            <property name="staticGroups" value="org.apache.dolphinscheduler,org.apache,java,javax,org,com"/>
            <property name="separatedStaticGroups" value="true"/>

            <property name="groups" value="org.apache.dolphinscheduler,org.apache,java,javax,org,com"/>
            <property name="ordered" value="true"/>
            <property name="separated" value="true"/>
            <property name="option" value="top"/>
            <property name="sortStaticImportsAlphabetically" value="true"/>
        </module>
```

**Comment by czeming** [comment]
@zhuangchong  I resolve the code conflicts. please review again, thx!

**Review by SbloodyS — APPROVED** [review]
+1

**Comment by SbloodyS** [comment]
@czeming Thanks for your contribution. This is a good beginning. Considering that it's your first contribution, I think we can get deep communication, you can contact me through mail or add WeChat(SbloodyS), when mail or added, please tell me who you are. I think I can help to familiar with the Dolphinscheduler if you meet with problems.
