### PR TITLE
[Bug] [task retry] Clone retry task Instance missing id field

### LINKED ISSUE #13043: [Bug] [task retry] Clone retry task Instance missing id field
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

In WorkflowExecuteRunnable. NewTaskInstance (), lack of the set id field.

task retry causes the NPE to occur.

NPE location: StateWheelExecuteThread. addTaskRetryEvent() set taskInstanceId

### What you expected to happen

The task instance can retry properly

### How to reproduce

task set retry

### Anything else

_No response_

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by jieguangzhou**
## Purpose of the pull request

close: #13043

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

**Comment by jieguangzhou** [comment]
@caishunfeng @ruanwenjun @SbloodyS PTAL, thanks

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/StateWheelExecuteThread.java [hunk 1]
```diff
@@ -422,7 +422,6 @@ private void addProcessStopEvent(ProcessInstance processInstance) {
     private void addTaskRetryEvent(TaskInstance taskInstance) {
         TaskStateEvent stateEvent = TaskStateEvent.builder()
                 .processInstanceId(taskInstance.getProcessInstanceId())
-                .taskInstanceId(taskInstance.getId())
```
Comment (EricGao888) [inline dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/StateWheelExecuteThread.java:425]: Just curious, why you choose to avoid using `getId` here instead of generating and setting an id for the retried task instance?

Comment (jieguangzhou) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/StateWheelExecuteThread.java:425]: We only use the task instance Id to print logs in the TaskRetryStateEventHandler. And we do not copy the id when cloning a new task instance for retried task instance.
If an existing task instance id is set when the task is retried, no new task instance will be created

This is pr solved by setting the id: #13074, and I closed it because I think the new one is simpler to fix the bug.

WDYT?

**Review by caishunfeng — APPROVED** [review]
LGTM
