### PR TITLE
[Fix-4839][Server] Process cannot stop when killed with retry

### LINKED ISSUE #4839: [Bug][Server] Process cannot stop when killed with retry
**For better global communication, Please describe it in English. If you feel the description in English is not clear, then you can append description in Chinese(just for Mandarin(CN)), thx! **
**Describe the bug**
Process cannot stop when killed with retry.

**To Reproduce**
Steps to reproduce the behavior, for example:
1. create a process,and a task with retry
image

2. start the process,then kill it the task will be killed and process in status ready_stop
image
image

image

3. dolphinscheduler-master.log echo log
image

**Expected behavior**

**Which version of Dolphin Scheduler:**
 -[dev]

**Additional context**

**Requirement or improvement**
- Please describe about your requirements or improvement suggestions.

### PR DESCRIPTION
**Pull request by dddyszy**
## *Tips*
- *Thanks very much for contributing to Apache DolphinScheduler.*
- *Please review https://dolphinscheduler.apache.org/en-us/community/index.html before opening a pull request.*

## What is the purpose of the pull request

fix #4839 

## Brief change log

remove KILL status in typeIsFailure

## Verify this pull request

this is usage ofd dev
image
this is usage of release-1.3.5
image
this is the same method in release-1.3.5
image

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

*(example:)*

  - *Added dolphinscheduler-dao tests for end-to-end.*
  - *Added CronUtilsTest to verify the change.*
  - *Manually verified the change by testing locally.*

### CODE REVIEW

File: dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/enums/ExecutionStatus.java [hunk 1]
```diff
@@ -90,7 +90,7 @@ public boolean typeIsSuccess() {
      * @return status
      */
     public boolean typeIsFailure() {
-        return this == FAILURE || this == NEED_FAULT_TOLERANCE || this == KILL;
+        return this == FAILURE || this == NEED_FAULT_TOLERANCE;
     }
```
Comment (CalvinKirs) [inline dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/enums/ExecutionStatus.java:94]: What worries me is that modifying this will cause abnormal business logic judgments elsewhere

Comment (dddyszy) [reply dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/enums/ExecutionStatus.java:94]: i checked the same method in release-1.3.5,it just has two,and i also check the usage of this method,dev branch has one more usage,and i also change it.please see the pictures

**Review by CalvinKirs — APPROVED** [review]
LGTM
