### PR TITLE
[Fix-17643] [registry-jdbc] fix dead client haven't fired JdbcDataChangeEvent issue

### LINKED ISSUE #17643: [Bug] [registry-jdbc] Delete dead client haven't fired JdbcDataChangeEvent
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

In JdbcRegistry senario.
When a master or worker client shutdown not by gracefully shutdown, the other client within the same registry will not discover this change even if this client is deleted after session timeout.

### What you expected to happen

In JdbcRegistry senario.
When a master or worker client shutdown, the other client will discover this change after session timeout.

### How to reproduce

1. My configuration `registry.type=jdbc`
2. Run 2 master clients.
3. Kill master `A` client with `kill -9 PID`
4. Wait until the session timeout. Master `B` will not update the master nodes and the command belong to master `A` will not be executed by master `B`.

### Anything else

_No response_

### Version

3.3.2

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by qiong-zhou**
Delete dead client haven't fired JdbcDataChangeEvent

## Purpose of the pull request

fix #17643

## Brief change log

- *Modified JdbcRegistryClientRepository.java*
- *Modified JdbcRegistryServer.java*

## Verify this pull request

This pull request is code cleanup without any test coverage.

## Pull Request Notice
[Pull Request Notice](https://github.com/apache/dolphinscheduler/blob/dev/docs/docs/en/contribute/join/pull-request.md)

If your pull request contains incompatible change, you should also add it to `docs/docs/en/guide/upgrade/incompatible.md`

### CODE REVIEW

File: dolphinscheduler-registry/dolphinscheduler-registry-plugins/dolphinscheduler-registry-jdbc/src/main/java/org/apache/dolphinscheduler/plugin/registry/jdbc/server/JdbcRegistryServer.java [hunk 1]
```diff
@@ -303,12 +303,18 @@ private void doPurgeJdbcRegistryClientInDB(final List<Long> jdbcRegistryClientId
             return;
         }
         log.info("Begin to delete dead jdbcRegistryClient: {}", jdbcRegistryClientIds);
-        jdbcRegistryDataRepository.deleteEphemeralDateByClientIds(jdbcRegistryClientIds);
+        deleteEphemeralDataByClientIds(jdbcRegistryClientIds);
```
Comment (ruanwenjun) [inline dolphinscheduler-registry/dolphinscheduler-registry-plugins/dolphinscheduler-registry-jdbc/src/main/java/org/apache/dolphinscheduler/plugin/registry/jdbc/server/JdbcRegistryServer.java]: We should remove in this method, we only need to delete the jdbcRegistryClient here.
```java
jdbcRegistryDataRepository.deleteEphemeralDateByClientIds(jdbcRegistryClientIds);
jdbcRegistryLockRepository.deleteByClientIds(jdbcRegistryClientIds);
```

Comment (qiong-zhou) [reply dolphinscheduler-registry/dolphinscheduler-registry-plugins/dolphinscheduler-registry-jdbc/src/main/java/org/apache/dolphinscheduler/plugin/registry/jdbc/server/JdbcRegistryServer.java]: @ruanwenjun  You mean delete these two lines in `doPurgeJdbcRegistryClientInDB` method and let method `purgeInvalidJdbcRegistryMetadata` do the cleaning data and lock jobs?

Comment (ruanwenjun) [reply dolphinscheduler-registry/dolphinscheduler-registry-plugins/dolphinscheduler-registry-jdbc/src/main/java/org/apache/dolphinscheduler/plugin/registry/jdbc/server/JdbcRegistryServer.java]: @qiong-zhou Delete these two lines in doPurgeJdbcRegistryClientInDB, and remove the extra changes in this PR.

**Comment by qiong-zhou** [comment]
@ruanwenjun Please review the code. Already edited according to your suggestion.
BTW, after the dead clients been deleted from the database, the `existJdbcRegistryClientIds` in method `purgeInvalidJdbcRegistryMetadata` should exclude the dead clients.

**Comment by qiong-zhou** [comment]
@SbloodyS Please help me with the failed checks.
The error message is not clear.

**Review by ruanwenjun — APPROVED** [review]
LGTM

**Review by SbloodyS — APPROVED** [review]
+1

**Review by Gallardot — APPROVED** [review]
