### PR TITLE
[Fix-10443][server]fix dependent task always running

### LINKED ISSUE #10443: [Bug] [dependent node] Dependent nodes are always blocked
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Occasionally dependent nodes are blocked all the time. In fact, the upstream node has been completed.

I haven't found an accurate recurrence rule yet. Most of them will appear after I edit the node

image

image

### What you expected to happen

I get this log...

[INFO] 2022-06-10 18:00:10.754 org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteThread:[301] - process event: State Event :key: null type: TASK_STATE_CHANGE executeStatus: RUNNING_EXECUTION task instance id: 471707 process instance id: 136719 context: null

/data/emr/dolphinscheduler/logs/dolphinscheduler-master.2022-06-10_18.9.log:

[INFO] 2022-06-10 18:26:49.211 org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteThread:[301] - process event: State Event :key: 133921-0-133921-0 type: PROCESS_STATE_CHANGE executeStatus: READY_STOP task instance id: 0 process instance id: 133921 context: null

企业微信截图_dbf16b9e-25d5-4933-808b-173f559163ff

### How to reproduce

I haven't found an accurate recurrence rule yet. Most of them will appear after I edit the node

### Anything else

sometimes...

### Version

2.0.5

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by weeway**
resovle dependent task always running bug

close #10443

### CODE REVIEW

File: dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteThread.java [hunk 1]
```diff
@@ -1412,8 +1412,18 @@ private void killAllTasks() {
             }
         }
 
-        this.taskRetryCheckList.clear();
-        this.depStateCheckList.clear();
+        for (Integer taskId : this.taskRetryCheckList.keySet()) {
+            if (taskInstanceHashMap.containsRow(taskId)) {
+                this.taskRetryCheckList.remove(taskId);
+            }
```
Comment (brave-lee) [inline dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteThread.java]: image
I think it might be better to modify it like this

**Review by brave-lee — APPROVED** [review]

File: dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteThread.java (hunk 1 above)
Comment (weeway) [reply dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteThread.java]: updated

**Review by brave-lee — APPROVED** [review]
+1
