### PR TITLE
[Bug] [API] Before deleting a worker group, check whether there is environment that reference the worker group.

### LINKED ISSUE #12490: [Bug] [API] Before deleting a worker group, check whether there is environment that reference the worker group
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

 Before deleting a worker group, check whether there is environment that reference the worker group.

### What you expected to happen

When a worker group is referenced by the environment, the worker group cannot be deleted。

### How to reproduce

1.create worker group
2.create environment ,choose worker group
3.delete worker group

### Anything else

_No response_

### Version

3.1.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by hstdream**
## Purpose of the pull request
close #12490

## Brief change log

Before deleting a worker group, check whether there is environment that reference the worker group.

## Verify this pull request
1.create worker group
2.create environment ,choose worker group
3.delete worker group

### CODE REVIEW

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/enums/Status.java [hunk 1]
```diff
@@ -506,8 +506,8 @@ public enum Status {
     FUNCTION_DISABLED(1400002, "The current feature is disabled.", "当前功能已被禁用"),
     SCHEDULE_TIME_NUMBER(1400003, "The number of complement dates exceed 100.", "补数日期个数超过100"),
     DESCRIPTION_TOO_LONG_ERROR(1400004, "description is too long error", "描述过长"),
-    ;
-
+    DELETE_WORKER_GROUP_BY_ID_FAIL_ENV(1400005,
+            "delete worker group by id fail, for there are {0} enviroments using it", "删除Worker分组失败，有[{0}]个环境正在使用");
```
Comment (caishunfeng) [inline dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/enums/Status.java]: It's better to show what env use.
```suggestion
            "delete worker group by id fail, for there are {0} enviroments using it: {1}", "删除Worker分组失败，有[{0}]个环境正在使用: {1}");
```

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/WorkerGroupServiceImpl.java [hunk 2]
```diff
@@ -343,6 +349,12 @@ public Map<String, Object> deleteWorkerGroupById(User loginUser, Integer id) {
             putMsg(result, Status.DELETE_WORKER_GROUP_BY_ID_FAIL, processInstances.size());
             return result;
         }
+        List<EnvironmentWorkerGroupRelation> environmentWorkerGroupRelationList =
+                environmentWorkerGroupRelationMapper.queryByWorkerGroupName(workerGroup.getName());
+        if (CollectionUtils.isNotEmpty(environmentWorkerGroupRelationList)) {
+            putMsg(result, Status.DELETE_WORKER_GROUP_BY_ID_FAIL_ENV, environmentWorkerGroupRelationList.size(), workerGroup.getName());
```
Comment (caishunfeng) [inline dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/WorkerGroupServiceImpl.java]:
```suggestion
            putMsg(result, Status.DELETE_WORKER_GROUP_BY_ID_FAIL_ENV, environmentWorkerGroupRelationList.size(), StringUtils.join(envNames, Constants.COMMA));
```

Comment (hstdream) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/WorkerGroupServiceImpl.java]: I understand that there is no problem here, one workergroup corresponds to multiple envs.

**Review by caishunfeng — DISMISSED** [review]

**Review by caishunfeng — APPROVED** [review]
