### PR TITLE
[Bug][UI Next]Fix global variable validation condition for save button in workflow definition.

### LINKED ISSUE #9448: [Bug] [UI Next] prop is repeat
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

image

I got the an message "prop is repeat" when the value is the same

### What you expected to happen

I think the value of difference props can be set differently.

### How to reproduce

Setting the same value between two props in saving the workflow

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by labbomb**
## Purpose of the pull request
Please refer to the main `issue`  [#9448](https://github.com/apache/dolphinscheduler/issues/9448).

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

### CODE REVIEW

File: dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/dag-save-modal.tsx [hunk 1]
```diff
@@ -114,16 +114,19 @@ export default defineComponent({
...
         validator() {
           const props = new Set()
+
+          const keys = formValue.value.globalParams.map(item => item.key)
+          const keysSet = new Set(keys)
+          if (keysSet.size !== keys.length) {
+            return new Error(t('project.dag.prop_repeat'))
+          }
+
           for (const param of formValue.value.globalParams) {
```
Comment (Amy0104) [inline dolphinscheduler-ui-next/src/views/projects/workflow/components/dag/dag-save-modal.tsx:124]: It seems to be better that one loop is enough.

**Review by songjianet — APPROVED** [review]
LGTM
