### PR TITLE
Fix queryByTypeAndJobId might error due to multiple result

### LINKED ISSUE #15864: [Bug][Master] Transform command  to WorkflowExecutionRunnable failed due to t_ds_trigger_relation duplicate data
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

can't start workflow

### What you expected to happen

workflow is running ~~~

### How to reproduce

edit workflow and save online and run ,you will see that the workflow cannot run,and master log have this error 

### Anything else

_No response_

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by ruanwenjun**
## Purpose of the pull request

fix https://github.com/apache/dolphinscheduler/issues/15864

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

File: dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/TriggerRelationServiceImpl.java [hunk 1]
```diff
@@ -45,29 +51,44 @@ public void saveTriggerToDb(ApiTriggerType type, Long triggerCode, Integer jobId
...
     public int saveCommandTrigger(Integer commandId, Integer processInstanceId) {
-        TriggerRelation exist = queryByTypeAndJobId(ApiTriggerType.PROCESS, processInstanceId);
-        if (exist == null) {
+        List<TriggerRelation> existTriggers = queryByTypeAndJobId(ApiTriggerType.PROCESS, processInstanceId);
+        if (CollectionUtils.isEmpty(existTriggers)) {
             return 0;
         }
-        saveTriggerToDb(ApiTriggerType.COMMAND, exist.getTriggerCode(), commandId);
-        return 1;
+        existTriggers.forEach(triggerRelation -> saveTriggerToDb(ApiTriggerType.COMMAND,
```
Comment (rickchengx) [inline dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/TriggerRelationServiceImpl.java:66]: If returning more than 1 result is a situation that should not occur, are there any potential problems if they are still stored into db?

Comment (ruanwenjun) [reply dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/TriggerRelationServiceImpl.java:66]: AFAIK, this table is only used for querying the workflow instance by rest-api, it will to affect the other api.

BTW, this table can be removed if we can generate the workflow instance in api-side when manual trigger a workflow instance, I have a plan to create a DSIP for this. This can help to reduce the complexity.

**Review by rickchengx — APPROVED** [review]
LGTM
