### PR TITLE
[Bug] [Server] Once click online schedule time, task will be automatically scheduled

### LINKED ISSUE #13089: [Bug] [Server] Once click online schedule time, task will be automatically scheduled
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

v3.0.2
For a workflow with a schedule time, on the `Cron management` page, when we click offline and then click online, and the task will be automatically scheduled once.

image

### What you expected to happen

Expected  workflow won't be schedule when just  click online

### How to reproduce

we click offline and then click online on the `Cron management` page

### Anything else

_No response_

### Version

3.0.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Radeity**
## Purpose of the pull request
- This PR closes https://github.com/apache/dolphinscheduler/issues/13089

## Brief change log
Current mis-fire strategy is to process cron job immediately. The strategy will be triggered if setting scheduler’s start time earlier than current time. 
- Add check when creating and updating schedule, set the start time to current time if it's earlier than current time. 
## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/SchedulerServiceImpl.java [hunk 1]
```diff
@@ -171,6 +171,9 @@ public Map<String, Object> insertSchedule(User loginUser,
         scheduleObj.setProcessDefinitionName(processDefinition.getName());
 
         ScheduleParam scheduleParam = JSONUtils.parseObject(schedule, ScheduleParam.class);
+        if (now.after(scheduleParam.getStartTime())) {
+            scheduleParam.setStartTime(now);
+        }
```
Comment (DarkAssassinator) [inline dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/SchedulerServiceImpl.java]: could we refactor to a private method?

Comment (Radeity) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/SchedulerServiceImpl.java]: > could we refactor to a private method?

I considered before, actually, there are many duplicated code in `SchedulerServiceImpl`, then i found that codes of api V2 are cleaner. Anyway, i'll refactor some bug-related code part in this file, thx!

Comment (Radeity) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/SchedulerServiceImpl.java]: Hi, @DarkAssassinator, i have thought again, maybe there's not a strong need to move this simple condition judgement into a separate method, like other `startTime` related checks, WDYT?

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/SchedulerServiceImpl.java [hunk 2]
```diff
@@ -171,6 +171,9 @@ public Map<String, Object> insertSchedule(User loginUser,
         scheduleObj.setProcessDefinitionName(processDefinition.getName());
 
         ScheduleParam scheduleParam = JSONUtils.parseObject(schedule, ScheduleParam.class);
+        if (now.after(scheduleParam.getStartTime())) {
+            scheduleParam.setStartTime(now);
```
Comment (ruanwenjun) [inline dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/SchedulerServiceImpl.java]: It's better don't modify the user's input, this may be thought as a bug.

**Review by ruanwenjun — CHANGES_REQUESTED** [review]

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/SchedulerServiceImpl.java (hunk 2 above)
Comment (Radeity) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/SchedulerServiceImpl.java]: > It's better don't modify the user's input, this may be thought as a bug.

Okay, i'll make some changes that return warning message if setting start time earlier than current time, also change the default start time in front-end to 0:00 of the next day? WDYT.

Comment (ruanwenjun) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/SchedulerServiceImpl.java]: Can we rollback the strategy?

Comment (Radeity) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/SchedulerServiceImpl.java]: How to handle the scenario described in https://github.com/apache/dolphinscheduler/issues/12231?

Comment (Radeity) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/SchedulerServiceImpl.java]: @ruanwenjun Any new suggestions?

**Comment by Radeity** [comment]
> Okay, i'll make some changes that return warning message if setting start time earlier than current time, also change the default start time in front-end to 0:00 of the next day? WDYT.

If no more suggestions, i'll follow the logic mentioned above and finish new code at this weekend.

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/SchedulerServiceImpl.java [hunk 3]
```diff
@@ -234,6 +239,10 @@ private void scheduleParamCheck(String scheduleParamStr) {
         if (scheduleParam == null) {
             throw new ServiceException(Status.PARSE_SCHEDULE_PARAM_ERROR, scheduleParamStr);
         }
+        Date now = new Date();
+        if (now.after(scheduleParam.getStartTime())) {
+            throw new ServiceException(Status.START_TIME_BEFORE_CURRENT_TIME_ERROR);
+        }
```
Comment (caishunfeng) [inline dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/SchedulerServiceImpl.java:245]: I think this check can only use for the create action, but not for updating.
I found the `scheduleParamCheck` is called by `updateSchedulesV2`, I think it's better to split it.

**Review by caishunfeng — DISMISSED** [review]

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/SchedulerServiceImpl.java (hunk 3 above)
Comment (Radeity) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/SchedulerServiceImpl.java:245]: > I think this check can only use for the create action, but not for updating. I found the `scheduleParamCheck` is called by `updateSchedulesV2`, I think it's better to split it.

Hi, @caishunfeng, `updateSchedulesV2` is called by updateSchedulesV2, either.
```java
try {
        scheduleUpdate = scheduleUpdateRequest.mergeIntoSchedule(schedule);
        // check update params
        this.scheduleParamCheck(scheduleUpdateRequest.updateScheduleParam(scheduleUpdate));
}
```

**Review by ruanwenjun — DISMISSED** [review]
If no other concern, I will merge this PR.

**Comment by ruanwenjun** [comment]
@Radeity Please rebase the upstream dev to solve the `dead-link` check.

**Comment by Radeity** [comment]
> @Radeity Please rebase the upstream dev to solve the `dead-link` check.

@ruanwenjun Done, thx!

**Review by ruanwenjun — APPROVED** [review]

**Review by EricGao888 — APPROVED** [review]

File: dolphinscheduler-ui/src/views/projects/workflow/definition/components/use-form.ts [hunk 4]
```diff
@@ -95,7 +95,7 @@ export const useForm = () => {
     timingFormRef: ref(),
     timingForm: {
       startEndTime: [
-        new Date(year, month, day),
+        new Date(year, month, day + 1),
```
Comment (EricGao888) [inline dolphinscheduler-ui/src/views/projects/workflow/definition/components/use-form.ts:98]: Just curious, why did u do this here?

Comment (Radeity) [reply dolphinscheduler-ui/src/views/projects/workflow/definition/components/use-form.ts:98]: It will return warning message if setting start time earlier than current time, so default start time should be valid.

**Comment by ruanwenjun** [comment]
@Radeity Hi, I submit https://github.com/apache/dolphinscheduler/pull/13285 to fix this kind of problem, I plan to revert this PR, since the check is not needed now.

**Comment by Radeity** [comment]
> @Radeity Hi, I submit #13285 to fix this kind of problem, I plan to revert this PR, since the check is not needed now.

Okay, anyway, your fix is better, thx!
