### PR TITLE
[Fix-5309][Common] Fix the wrong memory

### LINKED ISSUE #5309: [Bug][Common] memoryUsage is `-33%`
**To Reproduce**

`memoryUsage` is `-33%`

**Expected behavior**
Bug fixed

**Screenshots**
image

**Which version of Dolphin Scheduler:**
 -[1.3.x]
 -[dev]

### PR DESCRIPTION
**Pull request by chengshiwen**
## Purpose of the pull request

*[Fix-5309][Common] Fix the wrong memory*

This pr is a synchronization from a commit of #5195 in `1.3.6-prepare`

This closes #5309

## Brief change log

  - *Fix the wrong memory*
  - *Fix unit test*
  - *Remove unused `DEFAULT_MASTER_RESERVED_MEMORY` and `DEFAULT_WORKER_RESERVED_MEMORY `*
  - *Remove unused `checkResource `*

## Verify this pull request

This change added tests and can be verified as follows:

  - *Manually verified the change by testing locally.*

### CODE REVIEW

File: dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/OSUtils.java [hunk 1]
```diff
@@ -118,11 +117,11 @@ public static double availablePhysicalMemorySize() {
      */
     public static double totalMemorySize() {
```
Comment (ruanwenjun) [inline dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/OSUtils.java]: Maybe it's better to change this method name to `totalPhysicalMemorySize`, it is my personal suggestion, just for reference.

Comment (chengshiwen) [reply dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/OSUtils.java]: Done

**Review by ruanwenjun — APPROVED** [review]

**Review by CalvinKirs — APPROVED** [review]
LGTM
