### PR TITLE
[Bug-#12057][task-plugin] fix when the sql query result is empty, the email fails to send the attachment, and an exception will be reported

### LINKED ISSUE #12057: [Bug] [task-plugin] When the sql query result is empty, the email fails to send the attachment, and an exception will be reported
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

when the sql query result is empty, dolphinscheduler-alert.log screenshot is as follows:
image
Email can't be sent
image

### What you expected to happen

I think we should send an empty attachment and write the table structure and empty results of the query to the attachment
such as
image

### How to reproduce

..

### Anything else

_No response_

### Version

3.0.0

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by fengjian1129**
fix: #12057

describe ： It is mainly used to solve the problem that when the query result is empty, an email with attachments will be sent with runtime exception

### CODE REVIEW

File: dolphinscheduler-task-plugin/dolphinscheduler-task-sql/src/main/java/org/apache/dolphinscheduler/plugin/task/sql/SqlTask.java [hunk 1]
```diff
@@ -255,6 +255,15 @@ private String resultProcess(ResultSet resultSet) throws Exception {
                 resultJSONArray.add(mapOfColValues);
                 rowCount++;
             }
+            // result is null,output table metadata
+            if (resultJSONArray.isEmpty()) {
```
Comment (githublaohu) [inline dolphinscheduler-task-plugin/dolphinscheduler-task-sql/src/main/java/org/apache/dolphinscheduler/plugin/task/sql/SqlTask.java]: 1. int num = md.getColumnCount(); 如果num为零，怎么办？
2. 如果resultJSONArray的数据里全是填充的， 267行的代码就没有意义了

File: dolphinscheduler-task-plugin/dolphinscheduler-task-sql/src/main/java/org/apache/dolphinscheduler/plugin/task/sql/SqlTask.java [hunk 2]
```diff
@@ -255,6 +255,15 @@ private String resultProcess(ResultSet resultSet) throws Exception {
...
+                ObjectNode emptyOfColValues = JSONUtils.createObjectNode();
+                for (int i = 1; i <= num; i++) {
```
Comment (githublaohu) [inline dolphinscheduler-task-plugin/dolphinscheduler-task-sql/src/main/java/org/apache/dolphinscheduler/plugin/task/sql/SqlTask.java]: 是否只需要填充一行就行了

File: dolphinscheduler-task-plugin/dolphinscheduler-task-sql/src/main/java/org/apache/dolphinscheduler/plugin/task/sql/SqlTask.java [hunk 3]
```diff
@@ -255,6 +255,15 @@ private String resultProcess(ResultSet resultSet) throws Exception {
...
+                    emptyOfColValues.set(md.getColumnLabel(i), JSONUtils.toJsonNode(""));
+                }
+                resultJSONArray.add(emptyOfColValues);
```
Comment (caishunfeng) [inline dolphinscheduler-task-plugin/dolphinscheduler-task-sql/src/main/java/org/apache/dolphinscheduler/plugin/task/sql/SqlTask.java]: If put the empty row, the display rows is 1, but it's 0 in fact.

**Review by caishunfeng — CHANGES_REQUESTED** [review]

**Comment by caishunfeng** [comment]
Hi @fengjian1129 Please link the issue or add the detail in pr description, thanks.

File: dolphinscheduler-task-plugin/dolphinscheduler-task-sql/src/main/java/org/apache/dolphinscheduler/plugin/task/sql/SqlTask.java (hunk 1 above)
Comment (caishunfeng) [reply dolphinscheduler-task-plugin/dolphinscheduler-task-sql/src/main/java/org/apache/dolphinscheduler/plugin/task/sql/SqlTask.java]: Hi @githublaohu please use the English comments, which can make more developers understand, thanks.

Comment (githublaohu) [reply dolphinscheduler-task-plugin/dolphinscheduler-task-sql/src/main/java/org/apache/dolphinscheduler/plugin/task/sql/SqlTask.java]: if (resultSet != null)  。resultSet等于null，那么邮件就不发了。是否应该把发邮件的逻辑移出去或则发送一个异常邮件。

Comment (fengjian1129) [reply dolphinscheduler-task-plugin/dolphinscheduler-task-sql/src/main/java/org/apache/dolphinscheduler/plugin/task/sql/SqlTask.java]: If num=0, it is impossible. This "num" represents the number of fields. The query result cannot be without fields

Comment (fengjian1129) [reply dolphinscheduler-task-plugin/dolphinscheduler-task-sql/src/main/java/org/apache/dolphinscheduler/plugin/task/sql/SqlTask.java:259]: @githublaohu

File: dolphinscheduler-task-plugin/dolphinscheduler-task-sql/src/main/java/org/apache/dolphinscheduler/plugin/task/sql/SqlTask.java (hunk 2 above)
Comment (fengjian1129) [reply dolphinscheduler-task-plugin/dolphinscheduler-task-sql/src/main/java/org/apache/dolphinscheduler/plugin/task/sql/SqlTask.java]: Each field needs to be written to json

Comment (fengjian1129) [reply dolphinscheduler-task-plugin/dolphinscheduler-task-sql/src/main/java/org/apache/dolphinscheduler/plugin/task/sql/SqlTask.java]: Each field needs to be written to json

File: dolphinscheduler-task-plugin/dolphinscheduler-task-sql/src/main/java/org/apache/dolphinscheduler/plugin/task/sql/SqlTask.java (hunk 3 above)
Comment (fengjian1129) [reply dolphinscheduler-task-plugin/dolphinscheduler-task-sql/src/main/java/org/apache/dolphinscheduler/plugin/task/sql/SqlTask.java]: If the data is empty, I want to send Excel with header
image

**Comment by fengjian1129** [comment]
@caishunfeng I have completed the issue link and description and answered your questions

File: dolphinscheduler-task-plugin/dolphinscheduler-task-sql/src/main/java/org/apache/dolphinscheduler/plugin/task/sql/SqlTask.java (hunk 3 above)
Comment (caishunfeng) [reply dolphinscheduler-task-plugin/dolphinscheduler-task-sql/src/main/java/org/apache/dolphinscheduler/plugin/task/sql/SqlTask.java]: Yes, I get your point, but what I mean is that the log will show the incorrect empty result. It's better to set empty value before sendAttachment. see https://github.com/apache/dolphinscheduler/pull/12059/files#diff-f54c9e235dbb7e6ab2bd181aaad09f19330e680b8573840d64386401abb47203R269-R273

BTW, I think you can split this code as a function, like `generateEmptyRow`, WDYT?

**Review by davidzollo — DISMISSED** [review]
+1
LGTM

File: dolphinscheduler-task-plugin/dolphinscheduler-task-sql/src/main/java/org/apache/dolphinscheduler/plugin/task/sql/SqlTask.java (hunk 3 above)
Comment (fengjian1129) [reply dolphinscheduler-task-plugin/dolphinscheduler-task-sql/src/main/java/org/apache/dolphinscheduler/plugin/task/sql/SqlTask.java]: yes, I got it

File: dolphinscheduler-task-plugin/dolphinscheduler-task-sql/src/main/java/org/apache/dolphinscheduler/plugin/task/sql/SqlTask.java [hunk 4]
```diff
@@ -279,6 +274,30 @@ private String resultProcess(ResultSet resultSet) throws Exception {
...
+        } else {
+            int displayRows = sqlParameters.getDisplayRows() > 0 ? sqlParameters.getDisplayRows() : TaskConstants.DEFAULT_DISPLAY_ROWS;
+            displayRows = Math.min(displayRows, rowCount);
+            logger.info("display sql result {} rows as follows:", displayRows);
+            for (int i = 0; i < displayRows; i++) {
+                String row = JSONUtils.toJsonString(resultJSONArray.get(i));
+                logger.info("row {} : {}", i + 1, row);
+            }
+        }
+    }
```
Comment (caishunfeng) [inline dolphinscheduler-task-plugin/dolphinscheduler-task-sql/src/main/java/org/apache/dolphinscheduler/plugin/task/sql/SqlTask.java]:
```suggestion
    private ArrayNode generateEmptyRow(ResultSetMetaData md, int metaColumnsNum, int rowCount) throws SQLException {
            ArrayNode resultJSONArray = JSONUtils.createArrayNode();
            ObjectNode emptyOfColValues = JSONUtils.createObjectNode();
            for (int i = 1; i <= metaColumnsNum; i++) {
                emptyOfColValues.set(md.getColumnLabel(i), JSONUtils.toJsonNode(""));
            }
            resultJSONArray.add(emptyOfColValues);
           return resultJSONArray;
    }
```

Comment (caishunfeng) [reply dolphinscheduler-task-plugin/dolphinscheduler-task-sql/src/main/java/org/apache/dolphinscheduler/plugin/task/sql/SqlTask.java]: We should avoid to change the input param in the method.

File: dolphinscheduler-task-plugin/dolphinscheduler-task-sql/src/main/java/org/apache/dolphinscheduler/plugin/task/sql/SqlTask.java [hunk 5]
```diff
@@ -261,13 +261,8 @@ private String resultProcess(ResultSet resultSet) throws Exception {
                 resultJSONArray.add(mapOfColValues);
                 rowCount++;
             }
-            int displayRows = sqlParameters.getDisplayRows() > 0 ? sqlParameters.getDisplayRows() : TaskConstants.DEFAULT_DISPLAY_ROWS;
-            displayRows = Math.min(displayRows, rowCount);
-            logger.info("display sql result {} rows as follows:", displayRows);
-            for (int i = 0; i < displayRows; i++) {
-                String row = JSONUtils.toJsonString(resultJSONArray.get(i));
-                logger.info("row {} : {}", i + 1, row);
-            }
```
Comment (caishunfeng) [inline dolphinscheduler-task-plugin/dolphinscheduler-task-sql/src/main/java/org/apache/dolphinscheduler/plugin/task/sql/SqlTask.java]: This is the normal logic, we should recover it.

File: dolphinscheduler-task-plugin/dolphinscheduler-task-sql/src/main/java/org/apache/dolphinscheduler/plugin/task/sql/SqlTask.java [hunk 6]
```diff
@@ -261,13 +261,8 @@ private String resultProcess(ResultSet resultSet) throws Exception {
...
+            // generate query results
+            generateRow(resultJSONArray, md, num, rowCount);
```
Comment (caishunfeng) [inline dolphinscheduler-task-plugin/dolphinscheduler-task-sql/src/main/java/org/apache/dolphinscheduler/plugin/task/sql/SqlTask.java]: It will not take affect when resultSet == null.

File: dolphinscheduler-task-plugin/dolphinscheduler-task-sql/src/main/java/org/apache/dolphinscheduler/plugin/task/sql/SqlTask.java [hunk 7]
```diff
@@ -261,13 +261,8 @@ private String resultProcess(ResultSet resultSet) throws Exception {
...
         }
         String result = JSONUtils.toJsonString(resultJSONArray);
         if (sqlParameters.getSendEmail() == null || sqlParameters.getSendEmail()) {
```
Comment (caishunfeng) [inline dolphinscheduler-task-plugin/dolphinscheduler-task-sql/src/main/java/org/apache/dolphinscheduler/plugin/task/sql/SqlTask.java:277]: Avoid changing the return result.
```suggestion
        if (sqlParameters.getSendEmail() == null || sqlParameters.getSendEmail()) {
            String attachmentContent = resultJSONArray.isEmpty()? JSONUtils.toJsonString(generateEmptyRow()):result;
            sendAttachment(sqlParameters.getGroupId(), StringUtils.isNotEmpty(sqlParameters.getTitle())
                    ? sqlParameters.getTitle()
                    : taskExecutionContext.getTaskName() + " query result sets", attachmentContent);
```

**Review by caishunfeng — CHANGES_REQUESTED** [review]

File: dolphinscheduler-task-plugin/dolphinscheduler-task-sql/src/main/java/org/apache/dolphinscheduler/plugin/task/sql/SqlTask.java (hunk 6 above)
Comment (fengjian1129) [reply dolphinscheduler-task-plugin/dolphinscheduler-task-sql/src/main/java/org/apache/dolphinscheduler/plugin/task/sql/SqlTask.java]: I think  when resultSet == null then resultJSONArray is empty, it will still result in no content when the email is sent, and an error RuntimeException will be reported.I will process the logic that the resultSet is empty, and write the result into the content as the fixed error content

**Comment by fengjian1129** [comment]
@caishunfeng hi bro, review the code with your help.

File: dolphinscheduler-task-plugin/dolphinscheduler-task-sql/src/main/java/org/apache/dolphinscheduler/plugin/task/sql/SqlTask.java [hunk 8]
```diff
@@ -269,7 +270,10 @@ private String resultProcess(ResultSet resultSet) throws Exception {
                 logger.info("row {} : {}", i + 1, row);
             }
         }
-        String result = JSONUtils.toJsonString(resultJSONArray);
+
+        String result = resultJSONArray.isEmpty() ?
```
Comment (caishunfeng) [inline dolphinscheduler-task-plugin/dolphinscheduler-task-sql/src/main/java/org/apache/dolphinscheduler/plugin/task/sql/SqlTask.java:274]: Is it OK if return the empty row? Because it will deal out param if define the param pass.
see https://dolphinscheduler.apache.org/zh-cn/docs/dev/user_doc/guide/parameter/context.html

Comment (fengjian1129) [reply dolphinscheduler-task-plugin/dolphinscheduler-task-sql/src/main/java/org/apache/dolphinscheduler/plugin/task/sql/SqlTask.java:274]: I tested it according to the document, such as
image
image

I think it is in line with expectations

Comment (fengjian1129) [reply dolphinscheduler-task-plugin/dolphinscheduler-task-sql/src/main/java/org/apache/dolphinscheduler/plugin/task/sql/SqlTask.java:274]: This is the normal case with data
image

**Review by caishunfeng — APPROVED** [review]
LGTM, thanks~
