### PR TITLE
[Optimization] Config module resource relation fix.

### LINKED ISSUE #10717: [Optimization] Config module resource relation fix.
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Config module resource relation fix.

### Use case

Config module resource create.

### Related issues

No

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by WangJPLeo**
## Purpose of the pull request

1. Config module resource relation fix.
2. Add transaction handling on create data resource method that requires transaction.

## Brief change log

close #10717 

## Verify this pull request

Added CronUtilsTest to verify the change.
Manually verified the change by testing locally.

### CODE REVIEW

**Review by lenboo — DISMISSED** [review]
+1

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/QueueServiceImpl.java [hunk 1]
```diff
@@ -160,7 +160,7 @@ public Map<String, Object> createQueue(User loginUser, String queue, String queu
         queueMapper.insert(queueObj);
         result.put(Constants.DATA_LIST, queueObj);
         putMsg(result, Status.SUCCESS);
-
+        resourcePermissionCheckService.postHandle(AuthorizationType.QUEUE, loginUser.getId(), Collections.singletonList(queueObj.getId()), logger);
```
Comment (caishunfeng) [inline dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/QueueServiceImpl.java]: I have some question:

1. Why to check resource permission of the new created queue here? 
2. If check fail, should the db transaction rollback?

File: dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/Constants.java [hunk 2]
```diff
@@ -833,4 +833,6 @@ private Constants() {
     public static final int USER_PASSWORD_MIN_LENGTH = 2;
 
     public static final String FUNCTION_START_WITH = "$";
+
+    public static final Integer DEFAULT_TENANT_ID = 1;
```
Comment (ruanwenjun) [inline dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/Constants.java]: This is a tenant id or user id?

Comment (WangJPLeo) [reply dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/Constants.java]: the default tenant id, which is stored when the database is initialized.

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/QueueServiceImpl.java (hunk 1 above)
Comment (WangJPLeo) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/QueueServiceImpl.java]: This is a post action,  saving the data permission relationship in the external extension.
When an exception occurs, a Runtime exception will be thrown and rolled back.

File: dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/Constants.java (hunk 2 above)
Comment (ruanwenjun) [reply dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/Constants.java]: Ok, but I don't see we have inserted a default tenant into the database.

Comment (WangJPLeo) [reply dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/Constants.java]: Sorry, after I confirm again, the 'DEFAULT_TENANT_ID' constant here is the default queue ID, I will change the variable name.

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/QueueServiceImpl.java (hunk 1 above)
Comment (caishunfeng) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/QueueServiceImpl.java]: But I don't see the @Transactional of this method, is it right?

Comment (ruanwenjun) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/QueueServiceImpl.java]: Yes I still have this question, do we need to rollback here?

Comment (WangJPLeo) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/QueueServiceImpl.java]: I think it is needed, including other methods involving data manipulation. This can be used as an optimization item to do an overall transaction investigation later.

Comment (WangJPLeo) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/QueueServiceImpl.java]: updated checkList. @caishunfeng @ruanwenjun

**Review by caishunfeng — APPROVED** [review]

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/DataSourceServiceImpl.java [hunk 3]
```diff
@@ -139,6 +140,8 @@ public Result<Object> createDataSource(User loginUser, BaseDataSourceParamDTO da
         } catch (DuplicateKeyException ex) {
             logger.error("Create datasource error.", ex);
             putMsg(result, Status.DATASOURCE_EXIST);
+        } catch (RuntimeException e) {
+            throw new RuntimeException(e.getMessage());
         }
```
Comment (ruanwenjun) [inline dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/DataSourceServiceImpl.java:145]: Please don't hide the exception stack.
```suggestion
        }
```

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/WorkerGroupServiceImpl.java [hunk 4]
```diff
@@ -84,6 +84,7 @@ public class WorkerGroupServiceImpl extends BaseServiceImpl implements WorkerGro
      * @return create or update result code
      */
     @Override
+    @Transactional(rollbackFor = Exception.class)
```
Comment (ruanwenjun) [inline dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/WorkerGroupServiceImpl.java:87]: Please don't set the rollbackFor, if you set this then this method will only rollback a checked Exception, but you can know this method will not throw a checked Exception, if you want to rollback in all case, you can set rollbackFor = Throwable.class, but in this case ,you need to use rollbackFor = RuntimeException.class, the defailt rollback strategy is RuntimeException and Error, so you don't need to set.
```suggestion
    @Transactional
```

**Review by ruanwenjun — CHANGES_REQUESTED** [review]
Please check the all transaction you added

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/WorkerGroupServiceImpl.java (hunk 4 above)
Comment (WangJPLeo) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/WorkerGroupServiceImpl.java:87]: yeah, thx for this, 'If no rules are relevant to the exception, it will be treated like DefaultTransactionAttribute (rolling back on runtime exceptions)', without adding properties such as rollbackFor, Spring will roll back when Unchecked Exceptions are encountered, not only RuntimeException, but also Error. I will optimize it later.

Comment (WangJPLeo) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/WorkerGroupServiceImpl.java:87]: Created an improvement [https://github.com/apache/dolphinscheduler/issues/10791] 
Transaction checking and optimization will be handled uniformly in the new pr.  @ruanwenjun

**Review by ruanwenjun — APPROVED** [review]

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/WorkerGroupServiceImpl.java (hunk 4 above)
Comment (ruanwenjun) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/WorkerGroupServiceImpl.java:87]: Please fix this soon.

**Comment by ruanwenjun** [comment]
Note: This PR will introduce some transaction bug, should be fixed at #10747
