### PR TITLE
[fix-10961][alert server]Change the content of alert to an array

### LINKED ISSUE #10961: [Bug] [alert service] email alert failed
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

The alert service is running.
企业微信截图_16577684619245
When running a work flow, see the alert-server log.
企业微信截图_16577684067877

### What you expected to happen

I have installed CDH 6.3.2.Enviroment is healthy.

### How to reproduce

Restart dolphinscheduler, run a new work flow to check this problem.

### Anything else

_No response_

### Version

3.0.0-beta-2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by jackfanwan**
Change the content of alert to an array

close: #10961

### CODE REVIEW

**Comment by jackfanwan** [comment]
@kezhenxu94 Hello, can you take a look at it for me？

**Comment by jackfanwan** [comment]
PTAL @kezhenxu94 @caishunfeng

File: dolphinscheduler-alert/dolphinscheduler-alert-server/src/main/java/org/apache/dolphinscheduler/alert/AlertSenderService.java [hunk 1]
```diff
@@ -93,6 +97,13 @@ public void send(List<Alert> alerts) {
                 continue;
             }
             AlertData alertData = new AlertData();
+            if (Objects.nonNull(alert.getContent())
+                    && !alert.getContent().startsWith("[")
```
Comment (caishunfeng) [inline dolphinscheduler-alert/dolphinscheduler-alert-server/src/main/java/org/apache/dolphinscheduler/alert/AlertSenderService.java]: It's better to check by `jsonNodes instanceof JSONArray`. WDYT?

File: dolphinscheduler-alert/dolphinscheduler-alert-server/src/test/java/org/apache/dolphinscheduler/alert/runner/AlertSenderServiceTest.java [hunk 2]
```diff
@@ -144,7 +146,10 @@ public void testSyncHandler() {
     public void testRun() {
         int alertGroupId = 1;
         String title = "alert mail test title";
-        String content = "alert mail test content";
+        String content = "{\"taskInstanceId\":94,\"taskName\":\"000\",\"taskType\":\"DATA_QUALITY\","
```
Comment (caishunfeng) [inline dolphinscheduler-alert/dolphinscheduler-alert-server/src/test/java/org/apache/dolphinscheduler/alert/runner/AlertSenderServiceTest.java]: please add another case of array type.

File: dolphinscheduler-alert/dolphinscheduler-alert-server/src/main/java/org/apache/dolphinscheduler/alert/AlertSenderService.java (hunk 1 above)
Comment (jackfanwan) [reply dolphinscheduler-alert/dolphinscheduler-alert-server/src/main/java/org/apache/dolphinscheduler/alert/AlertSenderService.java:101]: Since jsonNodes are not related to JSONArray, instanceof cannot be used. I also tried isArray(), but I found that isArray() always returns false

Comment (jackfanwan) [reply dolphinscheduler-alert/dolphinscheduler-alert-server/src/main/java/org/apache/dolphinscheduler/alert/AlertSenderService.java]: > It's better to check by `jsonNodes instanceof JSONArray`. WDYT?

Since jsonNodes are not related to JSONArray, instanceof cannot be used. I also tried isArray(), but I found that isArray() always returns false

File: dolphinscheduler-alert/dolphinscheduler-alert-server/src/main/java/org/apache/dolphinscheduler/alert/AlertSenderService.java [hunk 3]
```diff
@@ -93,6 +100,19 @@ public void send(List<Alert> alerts) {
...
+            if (StringUtils.isNotEmpty(alert.getContent())) {
+                try {
+                    Object contentObject = new JSONTokener(alert.getContent()).nextValue();
+                    if (!(contentObject instanceof JSONArray)) {
+                        ObjectNode jsonNodes = JSONUtils.parseObject(alert.getContent());
+                        String content = JSONUtils.toJsonString(Collections.singletonList(jsonNodes));
+                        alert.setContent(content);
+                    }
+                } catch (JSONException e) {
+                    e.printStackTrace();
```
Comment (tracehh) [inline dolphinscheduler-alert/dolphinscheduler-alert-server/src/main/java/org/apache/dolphinscheduler/alert/AlertSenderService.java]: use  `logger.error("")` to log

Comment (jackfanwan) [reply dolphinscheduler-alert/dolphinscheduler-alert-server/src/main/java/org/apache/dolphinscheduler/alert/AlertSenderService.java]: thanks

**Comment by zhongjiajie** [comment]
@jackfanwan can you solve the conflicts?

**Comment by jackfanwan** [comment]
> @jackfanwan can you solve the conflicts?

ok

File: dolphinscheduler-alert/dolphinscheduler-alert-server/src/main/java/org/apache/dolphinscheduler/alert/AlertSenderService.java [hunk 4]
```diff
@@ -92,6 +99,19 @@ public void send(List<Alert> alerts) {
                 alertDao.updateAlert(AlertStatus.EXECUTION_FAILURE, "no bind plugin instance", alertId);
                 continue;
             }
+
+            if (StringUtils.isNotEmpty(alert.getContent())) {
```
Comment (caishunfeng) [inline dolphinscheduler-alert/dolphinscheduler-alert-server/src/main/java/org/apache/dolphinscheduler/alert/AlertSenderService.java]: I found the issue is just about email, but if change the content here, will take affect to all alert type, it's better to put before the email handle content, WDYT?

Comment (caishunfeng) [reply dolphinscheduler-alert/dolphinscheduler-alert-server/src/main/java/org/apache/dolphinscheduler/alert/AlertSenderService.java]: @jackfanwan BTW, had you found which alert type and content will cause this issue?

Comment (jackfanwan) [reply dolphinscheduler-alert/dolphinscheduler-alert-server/src/main/java/org/apache/dolphinscheduler/alert/AlertSenderService.java]: > I found the issue is just about email, but if change the content here, will take affect to all alert type, it's better to put before the email handle content, WDYT?

Thank you for your advice

Comment (jackfanwan) [reply dolphinscheduler-alert/dolphinscheduler-alert-server/src/main/java/org/apache/dolphinscheduler/alert/AlertSenderService.java]: > 

I find that conversion issues occur when the alert type is email and the content is an object

Comment (jackfanwan) [reply dolphinscheduler-alert/dolphinscheduler-alert-server/src/main/java/org/apache/dolphinscheduler/alert/AlertSenderService.java]: > @jackfanwan BTW, had you found which alert type and content will cause this issue?

I find that conversion issues occur when the alert type is email and the content is an object

File: dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-email/src/main/java/org/apache/dolphinscheduler/plugin/alert/email/EmailAlertChannel.java [hunk 5]
```diff
@@ -38,6 +46,20 @@ public AlertResult process(AlertInfo info) {
         if (null == paramsMap) {
             return new AlertResult("false", "mail params is null");
         }
+        // Converts an object type to an array type to prevent subsequent conversions from reporting errors
+        if (StringUtils.isNotEmpty(alert.getContent())) {
```
Comment (caishunfeng) [inline dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-email/src/main/java/org/apache/dolphinscheduler/plugin/alert/email/EmailAlertChannel.java]: @jackfanwan why not just handle before `getTextTypeMessage`? Because I found the content of the Email Table type is defferent, see `getTableTypeMessage`.

Comment (jackfanwan) [reply dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-email/src/main/java/org/apache/dolphinscheduler/plugin/alert/email/EmailAlertChannel.java]: > @jackfanwan why not just handle before `getTextTypeMessage`? Because I found the content of the Email Table type is defferent, see `getTableTypeMessage`.

@caishunfeng Because I see that the `toList` in the `getTableTypeMessage` method, if it's an object, it won't parse

Comment (jackfanwan) [reply dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-email/src/main/java/org/apache/dolphinscheduler/plugin/alert/email/EmailAlertChannel.java]: > @jackfanwan why not just handle before `getTextTypeMessage`? Because I found the content of the Email Table type is defferent, see `getTableTypeMessage`.

Excuse me, do I still need to make changes?

**Review by caishunfeng — APPROVED** [review]
LGTM

File: dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-email/src/main/java/org/apache/dolphinscheduler/plugin/alert/email/EmailAlertChannel.java (hunk 5 above)
Comment (caishunfeng) [reply dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-email/src/main/java/org/apache/dolphinscheduler/plugin/alert/email/EmailAlertChannel.java]: > > @jackfanwan why not just handle before `getTextTypeMessage`? Because I found the content of the Email Table type is defferent, see `getTableTypeMessage`.
> 
> Excuse me, do I still need to make changes?

Sorry for my late, I think it's need and you had updated it.

**Comment by ruanwenjun** [comment]
@caishunfeng Please clear the commit log when merging PR, there exist a lot of unused log.
image
