### PR TITLE
[Fix-17847] Fix incWorkflowInstanceByStateAndWorkflowDefinitionCode not called in version 3.4.0

### LINKED ISSUE #17847: [Bug][Master] incWorkflowInstanceByStateAndWorkflowDefinitionCode not called in version 3.4.0
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

No data is available for the ds.workflow.instance.count metric.

### What you expected to happen

Collect ds.workflow.instance.count data so that ds_workflow_instance_count_total becomes populated, e.g.
ds_workflow_instance_count_total{process_definition_code="SUCCESS"} 1

### How to reproduce

Access Grafana directly.

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by SbloodyS**
## Was this PR generated or assisted by AI?

Yes. The test was generated using gpt-5.4.

## Purpose of the pull request

fix #17847

## Brief change log

1. Fix warning in CI
```
Found multiple occurrences of org.json.JSONObject on the class path:
	jar:file:/Users/sbloodys/.m2/repository/com/tdunning/json/1.8/json-1.8.jar!/org/json/JSONObject.class
	jar:file:/Users/sbloodys/.m2/repository/com/vaadin/external/google/android-json/0.0.20131108.vaadin1/android-json-0.0.20131108.vaadin1.jar!/org/json/JSONObject.class
```

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

## Pull Request Notice
[Pull Request Notice](https://github.com/apache/dolphinscheduler/blob/dev/docs/docs/en/contribute/join/pull-request.md)

If your pull request contains incompatible change, you should also add it to `docs/docs/en/guide/upgrade/incompatible.md`

### CODE REVIEW

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/metrics/WorkflowInstanceMetrics.java [hunk 1]
```diff
@@ -90,6 +92,39 @@ public void incWorkflowInstanceByStateAndWorkflowDefinitionCode(final String sta
...
+            case FAILURE:
+                incWorkflowInstanceByStateAndWorkflowDefinitionCode("fail", String.valueOf(workflowDefinitionCode));
+                break;
+            case STOP:
+                incWorkflowInstanceByStateAndWorkflowDefinitionCode("stop", String.valueOf(workflowDefinitionCode));
+                break;
+            default:
+                break;
+        }
+    }
```
Comment (ruanwenjun) [inline dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/metrics/WorkflowInstanceMetrics.java]: It's better to directly record the `WorkflowExecutionStatus.name()`

Comment (SbloodyS) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/metrics/WorkflowInstanceMetrics.java]: Done. PTAL @ruanwenjun

**Review by ruanwenjun — DISMISSED** [review]
LGTM

File: dolphinscheduler-master/pom.xml [hunk 2]
```diff
@@ -307,6 +307,10 @@
                     <groupId>org.apache.logging.log4j</groupId>
                     <artifactId>log4j-to-slf4j</artifactId>
                 </exclusion>
+                <exclusion>
+                    <groupId>com.vaadin.external.google</groupId>
+                    <artifactId>android-json</artifactId>
+                </exclusion>
```
Comment (ruanwenjun) [inline dolphinscheduler-master/pom.xml:313]: Why change this?

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/workflow/serial/AbstractSerialCommandHandler.java [hunk 3]
```diff
@@ -86,6 +87,13 @@ public Void doInTransaction(TransactionStatus status) {
                 workflowInstance.setEndTime(DateUtils.getCurrentDate());
                 workflowInstance.setState(WorkflowExecutionStatus.STOP);
                 workflowInstanceDao.upsertWorkflowInstance(workflowInstance);
+                final Long workflowDefinitionCode =
+                        serialCommand.getWorkflowDefinitionCode() != null
+                                ? serialCommand.getWorkflowDefinitionCode()
+                                : workflowInstance.getWorkflowDefinitionCode();
+                WorkflowInstanceMetrics.recordWorkflowInstanceFinish(
+                        WorkflowExecutionStatus.STOP,
+                        workflowDefinitionCode);
```
Comment (ruanwenjun) [inline dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/workflow/serial/AbstractSerialCommandHandler.java]:
```suggestion
                WorkflowInstanceMetrics.recordWorkflowInstanceFinish(
                        WorkflowExecutionStatus.STOP,
                        workflowInstance.getWorkflowDefinitionCode());
```

File: dolphinscheduler-master/src/test/resources/it/metrics/workflow_with_serial_discard_strategy_for_metrics.yaml [hunk 4]
```diff
@@ -0,0 +1,61 @@
...
+    executionType: SERIAL_DISCARD
+
+tasks:
+  - name: A
+    code: 2102001
+    version: 1
+    projectCode: 2102
+    userId: 1
+    taskType: LogicFakeTask
+    taskParams: '{"localParams":null,"varPool":[],"shellScript":"sleep 5"}'
```
Comment (ruanwenjun) [inline dolphinscheduler-master/src/test/resources/it/metrics/workflow_with_serial_discard_strategy_for_metrics.yaml]:
```suggestion
    taskParams: '{"localParams":null,"varPool":[],"shellScript":"sleep 15"}'
```

Since the serial coordinator loop interval is 5s, so we need to make sure the task can running longer than 5s, other the discard stragy might not effect.

**Review by ruanwenjun — COMMENTED** [review]
We can revert the unrelated change of MasterCoordicator

File: dolphinscheduler-master/pom.xml (hunk 2 above)
Comment (SbloodyS) [reply dolphinscheduler-master/pom.xml:313]: I wrote it in PR description, and there are some warning in CI.

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/workflow/serial/AbstractSerialCommandHandler.java (hunk 3 above)
Comment (SbloodyS) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/workflow/serial/AbstractSerialCommandHandler.java]: Done.

File: dolphinscheduler-master/src/test/resources/it/metrics/workflow_with_serial_discard_strategy_for_metrics.yaml (hunk 4 above)
Comment (SbloodyS) [reply dolphinscheduler-master/src/test/resources/it/metrics/workflow_with_serial_discard_strategy_for_metrics.yaml]: Done.

**Review by ruanwenjun — APPROVED** [review]
LGTM
