### PR TITLE
[Fix-17710][Master] Fix master task dispatch failure by filtering out null map keys.

### LINKED ISSUE #17710: [Bug] [Master] Master task dispatch failed due to a null map key, which is not allowed in JsonSerializer
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

**Master task dispatch failed: encountered a null key in a parameter map, which violates JSON serialization rules;
The dolphinscheduler-master.log log file contains a large number of the following error messages**.

`
[WI-751315][TI-2077572] - 2025-11-19 17:00:08.610 ERROR [WorkerGroupTaskDispatcher-default] o.a.d.e.b.s.JsonSerializer:[67] - serializeToString exception!
com.fasterxml.jackson.databind.JsonMappingException: Null key for a Map not allowed in JSON (use a converting NullKeySerializer?) (through reference chain: org.apache.dolphinscheduler.task.executor.operations.TaskExecutorDispatchRequest["taskExecutionContext"]->org.apache.dolphinscheduler.plugin.task.api.TaskExecutionContext["prepareParamsMap"]->java.util.HashMap["null"])
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:283)
	at com.fasterxml.jackson.databind.SerializerProvider.mappingException(SerializerProvider.java:1370)
	at com.fasterxml.jackson.databind.SerializerProvider.reportMappingProblem(SerializerProvider.java:1266)
	at com.fasterxml.jackson.databind.ser.impl.FailingSerializer.serialize(FailingSerializer.java:32)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeFields(MapSerializer.java:791)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeWithoutTypeInfo(MapSerializer.java:764)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:720)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:35)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:732)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:772)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:732)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:772)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:479)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:318)
	at com.fasterxml.jackson.databind.ObjectMapper._writeValueAndClose(ObjectMapper.java:4719)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:3964)
	at org.apache.dolphinscheduler.extract.base.serialize.JsonSerializer.serialize(JsonSerializer.java:65)
	at org.apache.dolphinscheduler.extract.base.StandardRpcRequest.of(StandardRpcRequest.java:42)
	at org.apache.dolphinscheduler.extract.base.client.SyncClientMethodInvoker.invoke(SyncClientMethodInvoker.java:43)
	at org.apache.dolphinscheduler.extract.base.client.ClientInvocationHandler.invoke(ClientInvocationHandler.java:56)
	at com.sun.proxy.$Proxy209.dispatchTask(Unknown Source)
	at org.apache.dolphinscheduler.server.master.engine.task.client.PhysicalTaskExecutorClientDelegator.dispatch(PhysicalTaskExecutorClientDelegator.java:78)
	at org.apache.dolphinscheduler.server.master.engine.task.client.TaskExecutorClient.dispatch(TaskExecutorClient.java:54)
	at org.apache.dolphinscheduler.server.master.engine.task.dispatcher.WorkerGroupDispatcher.doDispatchTask(WorkerGroupDispatcher.java:94)
	at org.apache.dolphinscheduler.server.master.engine.task.dispatcher.WorkerGroupDispatcher.run(WorkerGroupDispatcher.java:79)
[WI-751315][TI-2077572] - 2025-11-19 17:00:08.611 ERROR [WorkerGroupTaskDispatcher-default] o.a.d.s.m.e.t.d.WorkerGroupDispatcher:[102] - Dispatch Task: 2077572 failed will retry after: 60000/ms

`

### What you expected to happen

The Master is able to dispatch this task normally

### How to reproduce

**Whenever there is a parameter with a null key**.

mysql> select id,task_type,workflow_instance_id,task_params from t_ds_task_instance where id = 2077572 \G;
*************************** 1. row ***************************
                  id: 2077572
           task_type: SHELL
workflow_instance_id: 751315
         task_params: {"localParams":[],"rawScript":"#!/bin/bash\nset -e\n\n\n \necho \"====================================\"","resourceList":[{"resourceName":"hdfs://xxx/dolphinscheduler/default/resources/123.sql"}]}

mysql> select global_params from t_ds_workflow_instance where id = 751315 \G;
*************************** 1. row ***************************
global_params: [{**"prop":null**,"direct":"IN","type":"VARCHAR","value":""}]

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by njnu-seafish**
## Purpose of the pull request

close #17710

## Brief change log

add filter some null map keys and unit test

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

## Pull Request Notice
[Pull Request Notice](https://github.com/apache/dolphinscheduler/blob/dev/docs/docs/en/contribute/join/pull-request.md)

If your pull request contains incompatible change, you should also add it to `docs/docs/en/guide/upgrade/incompatible.md`

### CODE REVIEW

File: dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/expand/CuringParamsServiceImpl.java [hunk 1]
```diff
@@ -160,107 +161,177 @@ public Map<String, Property> parseWorkflowFatherParam(@Nullable Map<String, Stri
...
-        // stream pass params
-        List<Property> varPools = parseVarPool(taskInstance);
+        Map<String, Property> prepareParamsMap = new HashMap<>();
 
-        // if it is a complement,
-        // you need to pass in the task instance id to locate the time
-        // of the process instance complement
         ICommandParam commandParam = JSONUtils.parseObject(workflowInstance.getCommandParam(), ICommandParam.class);
-        String timeZone = commandParam.getTimeZone();
+        String timeZone = commandParam != null ? commandParam.getTimeZone() : null;
```
Comment (ruanwenjun) [inline dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/expand/CuringParamsServiceImpl.java]: `commandParam` shouldn't be null.

File: dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/expand/CuringParamsServiceImpl.java [hunk 2]
```diff
@@ -160,107 +161,177 @@ public Map<String, Property> parseWorkflowFatherParam(@Nullable Map<String, Stri
...
 
-        // assign value to definedParams here
-        Map<String, Property> globalParams = parseGlobalParamsMap(workflowInstance);
-
-        // combining local and global parameters
-        Map<String, Property> localParams = parameters.getInputLocalParametersMap();
-
-        // stream pass params
-        List<Property> varPools = parseVarPool(taskInstance);
+        Map<String, Property> prepareParamsMap = new HashMap<>();
```
Comment (ruanwenjun) [inline dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/expand/CuringParamsServiceImpl.java:189]: Revert the unrelated changes.

File: dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/expand/CuringParamsServiceImpl.java [hunk 3]
```diff
@@ -160,107 +161,177 @@ public Map<String, Property> parseWorkflowFatherParam(@Nullable Map<String, Stri
...
-                 */
-                String val = property.getValue();
-
-                // handle some chain parameter assign, such as `{"var1": "${var2}", "var2": 1}` should be convert to
-                // `{"var1": 1, "var2": 1}`
-                val = convertParameterPlaceholders(val, prepareParamsMap);
-                property.setValue(val);
-            }
+        // 7. Resolve placeholders (e.g., "${output_dir}") using the current parameter context
+        resolvePlaceholders(prepareParamsMap);
```
Comment (ruanwenjun) [inline dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/expand/CuringParamsServiceImpl.java]: `preBuildBusinessParams` should before `resolvePlaceholders`?

File: dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/expand/CuringParamsServiceImpl.java (hunk 2 above)
Comment (njnu-seafish) [reply dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/expand/CuringParamsServiceImpl.java]: ok

**Review by SbloodyS — CHANGES_REQUESTED** [review]
Please don't directly use code generated by AI.

**Review by ruanwenjun — COMMENTED** [review]
Need to add IT case.

**Comment by njnu-seafish** [comment]
> Need to add IT case.

ok, it's added

**Review by ruanwenjun — APPROVED** [review]

**Review by SbloodyS — APPROVED** [review]
+1
