### PR TITLE
[DSIP-61][Master] Refactor thread pool and  state event orchestration in master

### LINKED ISSUE #16423: [DSIP-61][Master] Refactor thread pool and  state event orchestration in master
### Search before asking

- [X] I had searched in the [DSIP](https://github.com/apache/dolphinscheduler/issues/14102) and found no similar DSIP.

### Motivation

Right now, the thread model and state control in the master are very complicated, these come from the original code and design and lead to the project being hard to maintain. 

#### Concurrency modification of state

Multiple places can modify a workflow instance state in the master.
Right now we have an RPC thread pool, a failover daemon thread, a WorkflowExecuteThreadpool, and a TaskExecuteThreadpook. All of them might modify a workflow state or metadata, and all of these modification are not atomic, this means the state of a workflow/task can easily be inconsistent.

image

e.g. If the task is successful but the moment we stop the workflow, then the task state might be successful first but change to stop last, since the task state update is not automatic.

Furthermore, the API will also modify the workflow state e.g. when we do a pause or kill operation, once we do a pause or kill operation, the API server will change the workflow state to READY_PAUSE/READY_STOP and then send a request to the master by RPC, if the RPC fails, the state be in unexcepted.

#### No end-to-end task state consistency

Once the master receives a pause/kill request, the master will pause/kill the task in the db first, and then send a pause/kill request to the task executor, the request might handle failed、reject, or loss in a distributed environment.

Then the task state will be inconsistent between the master and task executor.

image

e.g. We stop the workflow, then the task will be killed, but if the master sends a kill request to the worker failed or the worker handles the kill request failed or worker failover, then the status will be killed in db but the task is still running in worker or remote server.

#### State control is very complex

There is no state machine in the master, the translation of state relies on a lot of if-else. There are a lot of bugs and it's impossible to write UT for the state translation. Most of the time, contributors fix a bug but write serial new bugs.

If we want to add a new state, this is impossible, the modification scope will be the whole master.

#### Failover will cause a master crash

The master doesn't use page query to find out the failover workflow instances, in some stress test, the master will directly  OOM once it begins to do master failover or global failover.

The global failover check is too frequent, each time when we do a global failover this will bring a big pressure to db since this will need to scan the whole table of workflow instances. But this only needs when the master startup first.

Seriously, we do failover in the registry client thread, this might block the registry client, since the failover will cost a lot of time.

This DSIP hopes to refactor the master and fix these problems.

### Design Detail

The final architecture in the master might look like below

image

Each workflow instance in runtime will be loaded as a WorkflowExecutionRunnable, and the task in the WorkflowExecutionRunnable is represented as a TaskExecutionRunnable. All changes to workflow and task will be triggered by lifecycle event.

#### WorkflowEventBus

WorkflowEventBus is an event channel that belongs to a specific workflow instance. Each workflow instance has its own EventBus, all operations that will affect the workflow/task running, be transformed into lifecycle events, and put into the EventBus in the order of the order of arrival of events. 

This can make the engine correctly easily handle the event since all events belonging to a workflow will be handled by one thread sequence.

#### WorkflowEventBusCoordinator

The WorkflowEventBusCoordinator is responsible for managing the EventBus and assigns the worker thread for an EventBus.

There are existing configurable workers in the WorkflowEventBusCoordinator. After a WorkflowExecutionRunnable is created, it will be assigned to an EventBusFireWorker, each WorkflowEventBus will only be assigned to one EventBusFireWorker, and one EventBusFireWorker will handle multiple WorkflowEventBus in DFS.

<details>

<summary> WorkflowEventBusCoordinator </summary>

```java
public class WorkflowEventBusCoordinator {

    public void registerWorkflowEventBus(IWorkflowExecutionRunnable workflowExecutionRunnable) {
        final int workerSlot = calculateWorkflowEventBusFireWorkerSlot(workflowExecutionRunnable);
        final WorkflowEventBusFireWorker workflowEventBusFireWorker = workflowEventBusFireWorkers.getWorker(workerSlot);
        workflowEventBusFireWorker.registerWorkflowEventBus(workflowExecutionRunnable);
    }

    public void unRegisterWorkflowEventBus(IWorkflowExecutionRunnable workflowExecutionRunnable) {
        final int workerSlot = calculateWorkflowEventBusFireWorkerSlot(workflowExecutionRunnable);
        final WorkflowEventBusFireWorker workflowEventBusFireWorker = workflowEventBusFireWorkers.getWorker(workerSlot);
        workflowEventBusFireWorker.unRegisterWorkflowEventBus(workflowExecutionRunnable);
    }

}
```

</details>

The worker number in WorkflowEventBusCoordinator is the only configuration you need to take care of, this will affect the performance of the master, a large number of workers does not mean you will have a better performance since this will increase os thread context switching, and most of the event handling will rely on db connection, other is memory operation this is very fast, only little event will rely on PRC. So it's better not to use more than twice the number of threads in your service's database connection pool, you should do some stress tests if you want to get the best configuration. 

#### WorkflowLifecycleEvent

The workflow lifecycle event represents the operation that might happen in the workflow runtime.

<details>

<summary> WorkflowLifecycleEventType </summary>

```java
public enum WorkflowLifecycleEventType implements ILifecycleEventType {

    /**
     * Start the workflow instance
     */
    START,
    /**
     * Notify the workflow instance there exist a task has been finished, and should do DAG topology logic transaction.
     */
    TOPOLOGY_LOGICAL_TRANSACTION_WITH_TASK_FINISH,
    /**
     * Pause the workflow instance
     */
    PAUSE,
    /**
     * The workflow instance has been paused
     */
    PAUSED,
    /**
     * Stop the workflow instance
     */
    STOP,
    /**
     * The workflow instance has been stopped
     */
    STOPPED,
    /**
     * The workflow instance has been success
     */
    SUCCEED,
    /**
     * The workflow instance has been failed
     */
    FAILED,
    /**
     * Finalize the workflow instance.
     */
    FINALIZE,

}
```

</details>

Not all lifecycle is related to a workflow state. The lifecycle event does not correspond to the state.

Since not all lifecycle changes will affect the state change, some are the inner context transform.

#### TaskLifecycleEvent

<details>

<summary> TaskLifecycleEventType </summary>

```java
public enum TaskLifecycleEventType implements ILifecycleEventType {

    /**
     * Start the Task instance.
     */
    START,
    /**
     * Dispatch the task instance to target.
     */
    DISPATCH,
    /**
     * The task instance is dispatched to the target executor server.
     */
    DISPATCHED,
    /**
     * // todo: maybe we can remove this event, once the task has been dispatched it should start
     * The task instance is running at the target executor server.
     */
    RUNNING,
    /**
     * Do Timeout strategy of the task instance.
     */
    TIMEOUT,
    /**
     * Retry the task instance.
     */
    RETRY,
    /**
     * Pause the task instance.
     */
    PAUSE,
    /**
     * The task instance is paused.
     */
    PAUSED,
    /**
     * Failover the task instance.
     */
    FAILOVER,
    /**
     * Kill the task instance.
     */
    KILL,
    /**
     * The task instance is killed.
     */
    KILLED,
    /**
     * The task instance is success.
     */
    SUCCEEDED,
    /**
     * The task instance is failed.
     */
    FAILED,
    ;

}
```

</details>

#### WorkflowExecutionGraph VS WorkflowGraph

WorkflowExecutionGraph represents a real expected DAG in the runtime, it will record the runtime state of each task chain. You can take it as a physis graph.

WorkflowGraph represents the origin DAG before you trigger a workflow, it will only record the origin DAG context. You can take it as a logic graph.

e.g. If we have a DAG(A, B, C), if we run from B, then the WorkflowExecutionGraph will only contains one task.
image

And if we run from A the WorkflowExecutionGraph will have the same DAG with WorkflowGraph. In addition, the WorkflowExecutionGraph will contain more runtime data, if we want to know the state of the Workflow in runtime, we can directly query from the WorkflowExecutionGraph.

<details>

<summary> IWorkflowExecutionGraph </summary>

```java
/**
 * The workflow execution graph represent the real DAG in runtime, it might be a sub DAG of the workflow DAG.
 *
 * @see WorkflowExecutionGraph
 */
public interface IWorkflowExecutionGraph {

    /**
     * Add a new task to the graph.
     */
    void addNode(TaskExecutionRunnable taskExecutionRunnable);

    /**
     * Add a new edge to the graph.
     * <p> Right now, this method call after all the tasks are added to the graph.
     */
    void addEdge(String fromTaskName, Set<String> toTaskName);

    /**
     * Return the start tasks, the start tasks in the workflow execution graph is the tasks which predecessors is empty.
     */
    List<ITaskExecutionRunnable> getStartNodes();

    /**
     * Get the predecessor tasks of the given task.
     */
    List<ITaskExecutionRunnable> getPredecessors(String taskName);

    /**
     * Return the successor tasks of the given task.
     */
    List<ITaskExecutionRunnable> getSuccessors(String taskName);

    /**
     * Return the successor tasks of the given task.
     */
    List<ITaskExecutionRunnable> getSuccessors(ITaskExecutionRunnable taskExecutionRunnable);

    /**
     * Get the ITaskExecutionRunnable by task code.
     */
    ITaskExecutionRunnable getTaskExecutionRunnableByName(String taskName);

    /**
     * Get the ITaskExecutionRunnable by task instance id.
     */
    ITaskExecutionRunnable getTaskExecutionRunnableById(Integer taskInstanceId);

    /**
     * Get the ITaskExecutionRunnable by task code.
     */
    ITaskExecutionRunnable getTaskExecutionRunnableByTaskCode(Long taskCode);

    /**
     * Get the active TaskExecutionRunnable list.
     * <p> The active TaskExecutionRunnable means the task is handling in the workflow execution graph.
     */
    List<ITaskExecutionRunnable> getActiveTaskExecutionRunnable();

    /**
     * Get all the TaskExecutionRunnable in the graph, this method will return all the TaskExecutionRunnable in the graph,
     * include active and inactive TaskExecutionRunnable.
     */
    List<ITaskExecutionRunnable> getAllTaskExecutionRunnable();

    /**
     * Check whether the given task can be trigger now.
     * <p> The task can be trigger if all the predecessors are finished and all predecessors are not failure/pause/kill.
     */
    boolean isTriggerConditionMet(ITaskExecutionRunnable taskExecutionRunnable);

    /**
     * Mark the TaskExecutionRunnable is active.
     * <p> If the TaskExecutionRunnable is active means the task is handling by the workflow.
     * <p> Once we begin to handle a task, we should mark the TaskExecutionRunnable active.
     */
    void markTaskExecutionRunnableActive(ITaskExecutionRunnable taskExecutionRunnable);

    /**
     * Mark the TaskExecutionRunnable is inactive.
     * <p> If the TaskExecutionRunnable is inactive means the task has not been handled by the workflow.
     * <p> Once we finish to handle a task, we should mark the TaskExecutionRunnable inactive.
     */
    void markTaskExecutionRunnableInActive(ITaskExecutionRunnable taskExecutionRunnable);

    /**
     * Mark the TaskExecutionRunnable is skipped.
     * <p> Once the TaskExecutionRunnable is marked as skipped, this means the task will not be trigger.
     */
    void markTaskSkipped(ITaskExecutionRunnable taskExecutionRunnable);

    /**
     * Mark the Task is skipped.
     * <p> Once the Task is marked as skipped, this means the task will not be trigger.
     */
    void markTaskSkipped(String taskName);

    /**
     * Mark the TaskExecutionRunnable chain is failure.
     * <p> Once the TaskExecutionRunnable chain is failure, then the successors will not be trigger, and the workflow execution graph might be failure.
     */
    void markTaskExecutionRunnableChainFailure(ITaskExecutionRunnable taskExecutionRunnable);

    /**
     * Mark the TaskExecutionRunnable chain is pause.
     * <p> Once the TaskExecutionRunnable chain is pause, then the successors will not be trigger, and the workflow execution graph might be paused.
     */
    void markTaskExecutionRunnableChainPause(ITaskExecutionRunnable taskExecutionRunnable);

    /**
     * Mark the TaskExecutionRunnable chain is kill.
     * <p> Once the TaskExecutionRunnable chain is kill, then the successors will not be trigger, and the workflow execution graph might be stop.
     */
    void markTaskExecutionRunnableChainKill(ITaskExecutionRunnable taskExecutionRunnable);

    /**
     * Whether all the TaskExecutionRunnable chain in the graph is finish.
     */
    boolean isAllTaskExecutionRunnableChainFinish();

    /**
     * Whether all the TaskExecutionRunnable chain in the graph is finish with success.
     */
    boolean isAllTaskExecutionRunnableChainSuccess();

    /**
     * Whether there exist the TaskExecutionRunnable chain in the graph is finish with failure.
     */
    boolean isExistFailureTaskExecutionRunnableChain();

    /**
     * Whether there exist the TaskExecutionRunnable chain in the graph is finish with paused.
     */
    boolean isExistPauseTaskExecutionRunnableChain();

    /**
     * Whether there exist the TaskExecutionRunnable chain in the graph is finish with kill.
     */
    boolean isExistKillTaskExecutionRunnableChain();

    /**
     * Check whether the given task is the end of the task chain.
     * <p> If the given task has no successor, then it is the end of the task chain.
     */
    boolean isEndOfTaskChain(String taskName);

    /**
     * Check whether the given task is the end of the task chain.
     * <p> If the given task has no successor, then it is the end of the task chain.
     */
    boolean isEndOfTaskChain(ITaskExecutionRunnable taskExecutionRunnable);

    /**
     * Whether the given task is skipped.
     * <p> Once we mark the task is skipped, then the task will not be trigger, and will trigger its successors.
     */
    boolean isTaskExecutionRunnableSkipped(ITaskExecutionRunnable taskExecutionRunnable);

    /**
     * Whether the given task is forbidden.
     * <p> Once the task is forbidden then it will be passed, and will trigger its successors.
     */
    boolean isTaskExecutionRunnableForbidden(ITaskExecutionRunnable taskExecutionRunnable);

    /**
     * Whether all predecessors task is skipped.
     * <p> Once all predecessors are marked as skipped, then the task will be marked as skipped, and will trigger its successors.
     */
    boolean isAllPredecessorsSkipped(ITaskExecutionRunnable taskExecutionRunnable);

    /**
     * Whether all predecessors task are condition task.
     */
    boolean isAllSuccessorsAreConditionTask(ITaskExecutionRunnable taskExecutionRunnable);
}
```

</details>

#### StateMachine

Use `StateMachine` to control the workflow and task state change.

##### WorkflowStateMachine
The WorkflowStateMachine used to control the state transition in workflow.
Each state in workflow will implement IWorkflowStateAction.

Each state should implement IWorkflowStateAction and provide the function to handle WorkflowLifecycleEvent.

<details>

<summary> IWorkflowStateAction </summary>

```java
/**
 * Represents the action to be taken when a workflow is in a certain state and receive a target event.
 * <p> Each {@link WorkflowExecutionStatus} should have a corresponding {@link IWorkflowStateAction} implementation.
 *
 * @see WorkflowRunningStateAction
 * @see WorkflowReadyPauseStateAction
 * @see WorkflowPausedStateAction
 * @see WorkflowReadyStopStateAction
 * @see WorkflowStoppedStateAction
 * @see WorkflowSerialWaitStateAction
 * @see WorkflowFailedStateAction
 * @see WorkflowSuccessStateAction
 * @see WorkflowFailoverStateAction
 * @see WorkflowWaitToRunStateAction
 */
public interface IWorkflowStateAction {

    /**
     * Perform the necessary actions when the workflow in a certain state receive a {@link WorkflowStartLifecycleEvent}.
     */
    void startEventAction(final IWorkflowExecutionRunnable workflowExecutionRunnable,
                          final WorkflowStartLifecycleEvent workflowStartEvent);

    /**
     * Perform the necessary actions when the workflow in a certain state receive a {@link WorkflowTopologyLogicalTransitionWithTaskFinishLifecycleEvent}.
     */
    void topologyLogicalTransitionEventAction(final IWorkflowExecutionRunnable workflowExecutionRunnable,
                                              final WorkflowTopologyLogicalTransitionWithTaskFinishLifecycleEvent workflowTopologyLogicalTransitionWithTaskFinishEvent);

    /**
     * Perform the necessary actions when the workflow in a certain state receive a {@link WorkflowPauseLifecycleEvent}.
     */
    void pauseEventAction(final IWorkflowExecutionRunnable workflowExecutionRunnable,
                          final WorkflowPauseLifecycleEvent workflowPauseEvent);

    /**
     * Perform the necessary actions when the workflow in a certain state receive a {@link WorkflowStopLifecycleEvent}.
     */
    void pausedEventAction(final IWorkflowExecutionRunnable workflowExecutionRunnable,
                           final WorkflowPausedLifecycleEvent workflowPausedEvent);

    /**
     * Perform the necessary actions when the workflow in a certain state receive a {@link WorkflowStopLifecycleEvent}.
     */
    void stopEventAction(final IWorkflowExecutionRunnable workflowExecutionRunnable,
                         final WorkflowStopLifecycleEvent workflowStopEvent);

    /**
     * Perform the necessary actions when the workflow in a certain state receive a {@link WorkflowStoppedLifecycleEvent}.
     */
    void stoppedEventAction(final IWorkflowExecutionRunnable workflowExecutionRunnable,
                            final WorkflowStoppedLifecycleEvent workflowStoppedEvent);

    /**
     * Perform the necessary actions when the workflow in a certain state receive a {@link WorkflowSucceedLifecycleEvent}.
     */
    void succeedEventAction(final IWorkflowExecutionRunnable workflowExecutionRunnable,
                            final WorkflowSucceedLifecycleEvent workflowSucceedEvent);

    /**
     * Perform the necessary actions when the workflow in a certain state receive a {@link WorkflowFailedLifecycleEvent}.
     */
    void failedEventAction(final IWorkflowExecutionRunnable workflowExecutionRunnable,
                           final WorkflowFailedLifecycleEvent workflowFailedEvent);

    /**
     * Perform the necessary actions when the workflow in a certain state receive a {@link WorkflowFinalizeLifecycleEvent}.
     */
    void finalizeEventAction(final IWorkflowExecutionRunnable workflowExecutionRunnable,
                             final WorkflowFinalizeLifecycleEvent workflowFinalizeEvent);

    /**
     * Get the {@link WorkflowExecutionStatus} that this action match.
     */
    WorkflowExecutionStatus matchState();
}
```

</details>

 
##### TaskStateMachine

The TaskStateAction used to control the state transition in task.
Each state in task will implement ITaskStateAction.

Each state should implement ITaskStateAction and provide the function to handle TaskLifecycleEvent.

<details>

<summary> ITaskStateAction </summary>

```java
/**
 * Represents the action to be taken when a task is in a certain state and receive a target event.
 * <p> Each {@link TaskExecutionStatus} should have a corresponding {@link ITaskStateAction} implementation.
 *
 * @see TaskSubmittedStateAction
 * @see TaskDelayExecutionStateAction
 * @see TaskDispatchStateAction
 * @see TaskRunningStateAction
 * @see TaskPauseStateAction
 * @see TaskKillStateAction
 * @see TaskFailureStateAction
 * @see TaskSuccessStateAction
 * @see TaskForceSuccessStateAction
 * @see TaskFailoverStateAction
 */
public interface ITaskStateAction {

    /**
     * Perform the necessary actions when the task in a certain state receive a {@link TaskStartLifecycleEvent}.
     * <p> This method is called when you want to start a task.
     */
    void startEventAction(final IWorkflowExecutionRunnable workflowExecutionRunnable,
                          final ITaskExecutionRunnable taskExecutionRunnable,
                          final TaskStartLifecycleEvent taskStartEvent);

    /**
     * Perform the necessary actions when the task in a certain state receive a {@link TaskRunningLifecycleEvent}.
     * <p> This method is called when the master receive task running event from executor.
     */
    void startedEventAction(final IWorkflowExecutionRunnable workflowExecutionRunnable,
                            final ITaskExecutionRunnable taskExecutionRunnable,
                            final TaskRunningLifecycleEvent taskRunningEvent);

    /**
     * Perform the necessary actions when the task in a certain state receive a {@link TaskRetryLifecycleEvent}.
     * <p> This method is called when the task need to retry.
     */
    void retryEventAction(final IWorkflowExecutionRunnable workflowExecutionRunnable,
                          final ITaskExecutionRunnable taskExecutionRunnable,
                          final TaskRetryLifecycleEvent taskRetryEvent);

    /**
     * Perform the necessary actions when the task in a certain state receive a {@link TaskDispatchLifecycleEvent}.
     * <p> This method is called when you want to dispatch a task.
     */
    void dispatchEventAction(final IWorkflowExecutionRunnable workflowExecutionRunnable,
                             final ITaskExecutionRunnable taskExecutionRunnable,
                             final TaskDispatchLifecycleEvent taskDispatchEvent);

    /**
     * Perform the necessary actions when the task in a certain state receive a {@link TaskDispatchedLifecycleEvent}.
     * <p> This method is called when the task has been dispatched to executor.
     */
    void dispatchedEventAction(final IWorkflowExecutionRunnable workflowExecutionRunnable,
                               final ITaskExecutionRunnable taskExecutionRunnable,
                               final TaskDispatchedLifecycleEvent taskDispatchedEvent);

    /**
     * Perform the necessary actions when the task in a certain state receive a {@link TaskPauseLifecycleEvent}.
     * <p> This method is called when you want to pause a task.
     */
    void pauseEventAction(final IWorkflowExecutionRunnable workflowExecutionRunnable,
                          final ITaskExecutionRunnable taskExecutionRunnable,
                          final TaskPauseLifecycleEvent taskPauseEvent);

    /**
     * Perform the necessary actions when the task in a certain state receive a {@link TaskPausedLifecycleEvent}.
     * <p> This method is called when the task has been paused.
     */
    void pausedEventAction(final IWorkflowExecutionRunnable workflowExecutionRunnable,
                           final ITaskExecutionRunnable taskExecutionRunnable,
                           final TaskPausedLifecycleEvent taskPausedEvent);

    /**
     * Perform the necessary actions when the task in a certain state receive a {@link TaskKillLifecycleEvent}.
     * <p> This method is called when you want to kill a task.
     */
    void killEventAction(final IWorkflowExecutionRunnable workflowExecutionRunnable,
                         final ITaskExecutionRunnable taskExecutionRunnable,
                         final TaskKillLifecycleEvent taskKillEvent);

    /**
     * Perform the necessary actions when the task in a certain state receive a {@link TaskKilledLifecycleEvent}.
     * <p> This method is called when the task has been killed.
     */
    void killedEventAction(final IWorkflowExecutionRunnable workflowExecutionRunnable,
                           final ITaskExecutionRunnable taskExecutionRunnable,
                           final TaskKilledLifecycleEvent taskKilledEvent);

    /**
     * Perform the necessary actions when the task in a certain state receive a {@link TaskFailedLifecycleEvent}.
     * <p> This method is called when the task has been failed.
     */
    void failedEventAction(final IWorkflowExecutionRunnable workflowExecutionRunnable,
                           final ITaskExecutionRunnable taskExecutionRunnable,
                           final TaskFailedLifecycleEvent taskFailedEvent);

    /**
     * Perform the necessary actions when the task in a certain state receive a {@link TaskSuccessLifecycleEvent}.
     * <p> This method is called when the task has been success.
     */
    void succeedEventAction(final IWorkflowExecutionRunnable workflowExecutionRunnable,
                            final ITaskExecutionRunnable taskExecutionRunnable,
                            final TaskSuccessLifecycleEvent taskSuccessEvent);

    /**
     * Perform the necessary actions when the task in a certain state receive a {@link TaskFailoverLifecycleEvent}.
     * <p> This method is called when the task need to failover.
     */
    void failoverEventAction(final IWorkflowExecutionRunnable workflowExecutionRunnable,
                             final ITaskExecutionRunnable taskExecutionRunnable,
                             final TaskFailoverLifecycleEvent taskFailoverEvent);

    /**
     * Get the {@link TaskExecutionStatus} that this action match.
     */
    TaskExecutionStatus matchState();
}
```
</details>

#### Failover

The failover will use a SystemEventBus to trigger.

image

There are exist three kinds of failover event in DS.

##### GlobalMasterFailover

The GlobalMasterFailover used to failover the history workflow in the systems. Once the master server startup it will publish a GlobalMasterFailoverEvent, the GlobalMasterFailover will scan the not finished workflow instance in DB, and check whether we should failover them, so the GlobalMasterFailover will cost a lot of time.

##### MasterFailover

The MasterFailover is used to failover the workflow under the crashed master. Once the master crashed, then other active masters will receive the master crashed event, then publish a MasterFailoverEvent. If all Master crashed, then failover work will rely on GlobalMasterFailover.

##### WorkerFailover

The WorkerFailover is used to failover the task under the crashed worker. Once the worker crashed, then all active masters will receive the worker crashed event, then publish a WorkerFailoverEvent. Each master will only failover the task which hold on the master and has been dispatched to the crashed worker.

### Compatibility, Deprecation, and Migration Plan

Compatibility with the latest version, but will deprecated some interface which is not used by ui.

### Test Plan

Test by UT, E2E, manual.

#### Master Integration Test
Right now, there is no master integration test, in this DSIP, will add master IT test support.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by ruanwenjun**
## Purpose of the pull request

close https://github.com/apache/dolphinscheduler/issues/16423

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

## Pull Request Notice
[Pull Request Notice](https://github.com/apache/dolphinscheduler/blob/dev/docs/docs/en/contribute/join/pull-request.md)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

**Comment by ruanwenjun** [comment]
> ## [Quality Gate Failed](https://sonarcloud.io/dashboard?id=apache-dolphinscheduler&pullRequest=16327) **Quality Gate failed**
> Failed conditions  [7.8% Coverage on New Code](https://sonarcloud.io/component_measures?id=apache-dolphinscheduler&pullRequest=16327&metric=new_coverage&view=list) (required ≥ 60%)  [C Reliability Rating on New Code](https://sonarcloud.io/dashboard?id=apache-dolphinscheduler&pullRequest=16327) (required ≥ A)
> 
> [See analysis details on SonarCloud](https://sonarcloud.io/dashboard?id=apache-dolphinscheduler&pullRequest=16327)
> 
>  Catch issues before they fail your Quality Gate with our IDE extension  [SonarLint](https://www.sonarsource.com/products/sonarlint/features/connected-mode/?referrer=pull-request)

image
The coverage is incorrect

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/task/lifecycle/handler/TaskStartLifecycleEventHandler.java [hunk 1]
```diff
@@ -0,0 +1,80 @@
...
+
+import org.springframework.beans.factory.annotation.Autowired;
+import org.springframework.stereotype.Component;
+
+@Slf4j
+@Component
+public class TaskStartLifecycleEventHandler extends AbstractTaskLifecycleEventHandler<TaskStartLifecycleEvent> {
+
+    @Autowired
+    private WorkflowRepository workflowRepository;
```
Comment (SbloodyS) [inline dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/task/lifecycle/handler/TaskStartLifecycleEventHandler.java]: This seems no usage?

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/WorkflowEngine.java [hunk 2]
```diff
@@ -0,0 +1,70 @@
...
+
+import org.slf4j.Logger;
+import org.slf4j.LoggerFactory;
+import org.springframework.beans.factory.annotation.Autowired;
+import org.springframework.stereotype.Component;
+
+@Component
+public class WorkflowEngine implements AutoCloseable {
+
+    private static final Logger log = LoggerFactory.getLogger(WorkflowEngine.class);
```
Comment (SbloodyS) [inline dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/WorkflowEngine.java]: Can we use `@Slf4j` instead of this?

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/WorkflowEngine.java [hunk 3]
```diff
@@ -0,0 +1,70 @@
...
+    @Autowired
+    private ICommandFetcher commandFetcher;
```
Comment (SbloodyS) [inline dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/WorkflowEngine.java]: No usage here.

Comment (ruanwenjun) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/WorkflowEngine.java]: Done

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/task/lifecycle/handler/TaskStartLifecycleEventHandler.java (hunk 1 above)
Comment (ruanwenjun) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/task/lifecycle/handler/TaskStartLifecycleEventHandler.java]: Done

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/WorkflowEngine.java (hunk 2 above)
Comment (ruanwenjun) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/WorkflowEngine.java]: Yes, we should avoid directly create Logger.

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/config/MasterConfig.java [hunk 4]
```diff
@@ -48,16 +46,8 @@ public class MasterConfig implements Validator {
...
-     */
-    private int preExecThreads = 10;
-    /**
-     * todo: We may need to split the process/task into different thread size.
-     * The thread number used to handle processInstance and task event.
-     * Will create two thread poll to execute {@link WorkflowExecuteRunnable} and {@link TaskExecuteRunnable}.
-     */
-    private int execThreads = 10;
+
+    private int workflowEventBusFireThreadCount = Runtime.getRuntime().availableProcessors() * 2 + 1;
```
Comment (SbloodyS) [inline dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/config/MasterConfig.java:50]: It's better to add these config to `application.yaml` and add comments in it to let the user know its meaning. Same as `masterSyncTaskExecutorThreadPoolSize` and `masterAsyncTaskExecutorThreadPoolSize`.

Is it too large for `Runtime.getRuntime().availableProcessors() * 2 + 1`? I think `Runtime.getRuntime().availableProcessors()` is enough.

Comment (ruanwenjun) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/config/MasterConfig.java:50]: Done, added to application.yaml, the default value Runtime.getRuntime().availableProcessors() * 2 + 1 is not large, since there exists some DB operation in event firing.

**Review by SbloodyS — DISMISSED** [review]
LGTM. That's really a huge job. 👍🏻

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/executor/workflow/PauseWorkflowInstanceExecutorDelegate.java [hunk 5]
```diff
@@ -0,0 +1,128 @@
...
+            final WorkflowInstancePauseResponse pauseResponse = SingletonJdkDynamicRpcClientProxyFactory
+                    .withService(IWorkflowInstanceController.class)
+                    .withHost(workflowInstance.getHost())
+                    .pauseWorkflowInstance(new WorkflowInstancePauseRequest(workflowInstance.getId()));
+
+            if (pauseResponse != null && pauseResponse.isSuccess()) {
+                log.info("WorkflowInstance: {} pause success", workflowInstance.getName());
+            } else {
+                throw new ServiceException(
+                        "WorkflowInstance: " + workflowInstance.getName() + " stop failed: " + pauseResponse);
```
Comment (caishunfeng) [inline dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/executor/workflow/PauseWorkflowInstanceExecutorDelegate.java]:
```suggestion
                        "WorkflowInstance: " + workflowInstance.getName() + " pause failed: " + pauseResponse);
```

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/executor/workflow/RecoverSuspendedWorkflowInstanceExecutorDelegate.java [hunk 6]
```diff
@@ -0,0 +1,87 @@
...
+@Component
+public class RecoverSuspendedWorkflowInstanceExecutorDelegate
+        implements
+            IExecutorDelegate<RecoverSuspendedWorkflowInstanceExecutorDelegate.RecoverSuspendedWorkflowInstanceOperation, Void> {
+
+    @Autowired
+    private CommandDao commandDao;
+
+    @Override
+    public Void execute(RecoverSuspendedWorkflowInstanceOperation workflowInstanceControlRequest) {
```
Comment (caishunfeng) [inline dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/executor/workflow/RecoverSuspendedWorkflowInstanceExecutorDelegate.java:41]: use void is better and do not need to return null?
```suggestion
    public void execute(RecoverSuspendedWorkflowInstanceOperation workflowInstanceControlRequest) {
```

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/executor/workflow/TriggerWorkflowExecutorDelegate.java [hunk 7]
```diff
@@ -0,0 +1,71 @@
...
+    @Override
+    public Void execute(TriggerWorkflowDTO triggerWorkflowDTO) {
+        final RunWorkflowCommandParam runWorkflowCommandParam =
+                RunWorkflowCommandParam.builder()
+                        .commandParams(triggerWorkflowDTO.getStartParamList())
+                        .startNodes(triggerWorkflowDTO.getStartNodes())
+                        .timeZone(DateUtils.getTimezone())
+                        .build();
+        final Command command = Command.builder()
+                .commandType(triggerWorkflowDTO.getExecType())
```
Comment (caishunfeng) [inline dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/executor/workflow/TriggerWorkflowExecutorDelegate.java:51]: Is it necessary to add type check?

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/executor/workflow/TriggerWorkflowExecutorDelegate.java [hunk 8]
```diff
@@ -0,0 +1,71 @@
...
+public class TriggerWorkflowExecutorDelegate implements IExecutorDelegate<TriggerWorkflowDTO, Void> {
+
+    @Autowired
+    private CommandDao commandDao;
+
+    @Autowired
+    private TriggerRelationService triggerRelationService;
+
+    @Override
+    public Void execute(TriggerWorkflowDTO triggerWorkflowDTO) {
```
Comment (caishunfeng) [inline dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/executor/workflow/TriggerWorkflowExecutorDelegate.java:43]: It's better to check field in `TriggerWorkflowDTO`, such as `getWorkflowDefinition` is not null....

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/executor/workflow/WorkflowInstanceControlRequest.java [hunk 9]
```diff
@@ -15,19 +15,22 @@
...
 import lombok.AllArgsConstructor;
+import lombok.Builder;
 import lombok.Data;
-import lombok.NonNull;
 
 @Data
+@Builder
 @AllArgsConstructor
-public class StopRequest implements ExecuteRequest {
+public class WorkflowInstanceControlRequest {
```
Comment (caishunfeng) [inline dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/executor/workflow/WorkflowInstanceControlRequest.java]: The mean of `xxxxControlRequest` is too broad, please add some docs.

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/validator/workflow/TriggerWorkflowRequestValidator.java [hunk 10]
```diff
@@ -15,18 +15,20 @@
...
-    }
+import org.springframework.stereotype.Component;
 
-    WorkflowStartStatus startWorkflow();
+@Slf4j
+@Component
+public class TriggerWorkflowRequestValidator implements IValidator<TriggerWorkflowDTO> {
 
+    @Override
+    public void validate(final TriggerWorkflowDTO triggerWorkflowDTO) {
```
Comment (caishunfeng) [inline dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/validator/workflow/TriggerWorkflowRequestValidator.java]: It seems need to add some check.

File: dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/executor/workflow/StopWorkflowInstanceExecuteFunctionTest.java [hunk 11]
```diff
@@ -0,0 +1,105 @@
...
+import org.junit.jupiter.params.provider.EnumSource;
+import org.mockito.InjectMocks;
+import org.mockito.Mock;
+import org.mockito.junit.jupiter.MockitoExtension;
+import org.mockito.junit.jupiter.MockitoSettings;
+import org.mockito.quality.Strictness;
+
+@ExtendWith(MockitoExtension.class)
+@MockitoSettings(strictness = Strictness.LENIENT)
+class StopWorkflowInstanceExecuteFunctionTest {
```
Comment (caishunfeng) [inline dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/executor/workflow/StopWorkflowInstanceExecuteFunctionTest.java:40]: :+1:

File: dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/ProcessInstanceMapper.xml [hunk 12]
```diff
@@ -152,10 +152,10 @@
             </foreach>
         </if>
     </update>
-    <update id="updateProcessInstanceByState">
+    <update id="updateWorkflowInstanceState">
         update t_ds_process_instance
         set state = #{destState}
```
Comment (caishunfeng) [inline dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/ProcessInstanceMapper.xml]:
```suggestion
        set state = #{targetState}
```

File: dolphinscheduler-extract/dolphinscheduler-extract-master/src/main/java/org/apache/dolphinscheduler/extract/master/command/ICommandParam.java [hunk 13]
```diff
@@ -0,0 +1,65 @@
...
+    /**
+     * Get the time zone.
+     * todo: we should remove this field.
+     */
+    String getTimeZone();
+
+    /**
+     * Whether the command is used to trigger a sub workflow instance.
+     */
+    boolean isSubWorkflowInstance();
```
Comment (caishunfeng) [inline dolphinscheduler-extract/dolphinscheduler-extract-master/src/main/java/org/apache/dolphinscheduler/extract/master/command/ICommandParam.java:58]: Why need to distinguish whether it is a sub workflow instance?

File: dolphinscheduler-extract/dolphinscheduler-extract-master/src/main/java/org/apache/dolphinscheduler/extract/master/transportor/ITaskExecutionEvent.java [hunk 14]
```diff
@@ -38,9 +42,13 @@ public interface ITaskInstanceExecutionEvent {
     TaskInstanceExecutionEventType getEventType();
 
     enum TaskInstanceExecutionEventType {
+        DISPATCH,
         RUNNING,
+        PAUSED,
+        KILLED,
+        FAILED,
+        SUCCESS,
         FINISH,
```
Comment (caishunfeng) [inline dolphinscheduler-extract/dolphinscheduler-extract-master/src/main/java/org/apache/dolphinscheduler/extract/master/transportor/ITaskExecutionEvent.java]: Is it still need `FINISH` event type?

File: dolphinscheduler-extract/dolphinscheduler-extract-master/src/main/java/org/apache/dolphinscheduler/extract/master/transportor/ITaskExecutionEvent.java [hunk 15]
```diff
@@ -17,7 +17,11 @@
 
 package org.apache.dolphinscheduler.extract.master.transportor;
 
-public interface ITaskInstanceExecutionEvent {
+public interface ITaskExecutionEvent {
```
Comment (caishunfeng) [inline dolphinscheduler-extract/dolphinscheduler-extract-master/src/main/java/org/apache/dolphinscheduler/extract/master/transportor/ITaskExecutionEvent.java:21]: Suggest to add `event source`, which can help troubleshoot.

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/cluster/MasterSlotManager.java [hunk 16]
```diff
@@ -89,13 +89,19 @@ public void doReBalance(List<MasterServerMetadata> normalMasterServers) {
...
         }
 
+        if (totalSlots == normalMasterServers.size() && currentSlot == tmpCurrentSlot) {
+            log.debug("No need to rebalance, the currentSlot: {}, totalSlots: {} doesn't changed", currentSlot,
+                    totalSlots);
+            return;
+        }
         totalSlots = normalMasterServers.size();
         currentSlot = tmpCurrentSlot;
+        log.info("DO rebalance success, current master slot: {}, total master slots: {}", currentSlot, totalSlots);
```
Comment (caishunfeng) [inline dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/cluster/MasterSlotManager.java]:
```suggestion
        log.info("Do rebalance success, current master slot: {}, total master slots: {}", currentSlot, totalSlots);
```

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/TaskGroupCoordinator.java [hunk 17]
```diff
@@ -421,8 +421,11 @@ public boolean needToReleaseTaskGroupSlot(TaskInstance taskInstance) {
      * @throws IllegalArgumentException If the taskInstance is null or the task doesn't use task group.
      */
     public void releaseTaskGroupSlot(TaskInstance taskInstance) {
-        if (taskInstance == null || taskInstance.getTaskGroupId() <= 0) {
-            throw new IllegalArgumentException("The current TaskInstance does not use task group");
+        if (taskInstance == null) {
+            throw new IllegalArgumentException("The TaskInstance is null");
+        }
+        if (taskInstance.getTaskGroupId() <= 0) {
```
Comment (caishunfeng) [inline dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/TaskGroupCoordinator.java:427]: It's better to add some warn log if dirty data.

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/WorkflowEngine.java [hunk 18]
```diff
@@ -0,0 +1,66 @@
...
+import org.apache.dolphinscheduler.server.master.runner.MasterTaskExecutorBootstrap;
+
+import lombok.extern.slf4j.Slf4j;
+
+import org.springframework.beans.factory.annotation.Autowired;
+import org.springframework.stereotype.Component;
+
+@Slf4j
+@Component
+public class WorkflowEngine implements AutoCloseable {
```
Comment (caishunfeng) [inline dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/WorkflowEngine.java:30]: :+1:

**Review by caishunfeng — COMMENTED** [review]
Incomplete review

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/WorkflowEventBusFireWorker.java [hunk 19]
```diff
@@ -0,0 +1,140 @@
...
+                // Since we will print the event count at FinalizeEventHandler
+                // So we increase the event count before the event fired then we can get the correct event count
+                // And if the event handle failed we will decrease the success event count
+                workflowEventBus.getWorkflowEventBusSummary().increaseFireSuccessEventCount();
+                doFireSingleEvent(workflowExecutionRunnable, lifecycleEvent);
+            } catch (Exception ex) {
+                // If the database connection is failed, do not remove the event from the event bus
+                // so that the event can be fired again when the database connection is recovered
+                if (ExceptionUtils.isDatabaseConnectedFailedException(ex)) {
+                    workflowEventBus.publish(lifecycleEvent);
```
Comment (caishunfeng) [inline dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/WorkflowEventBusFireWorker.java:123]: Should return here?  Better to sleep when db connect fail.

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/WorkflowRepository.java [hunk 20]
```diff
@@ -32,47 +32,44 @@
 
 import com.google.common.collect.ImmutableList;
 
-/**
- * cache of process instance id and WorkflowExecuteThread
- */
 @Component
-public class ProcessInstanceExecCacheManagerImpl implements ProcessInstanceExecCacheManager {
+public class WorkflowRepository implements IWorkflowRepository {
```
Comment (caishunfeng) [inline dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/WorkflowRepository.java]: I think we should keep the cache concept because it's not a real dao repository.
```suggestion
public class WorkflowCacheRepository implements IWorkflowRepository {
```

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/command/handler/ReRunWorkflowCommandHandler.java [hunk 21]
```diff
@@ -0,0 +1,102 @@
...
+    @Override
+    protected void assembleWorkflowInstance(final WorkflowExecuteContextBuilder workflowExecuteContextBuilder) {
+        final Command command = workflowExecuteContextBuilder.getCommand();
+        final int workflowInstanceId = command.getProcessInstanceId();
+        final ProcessInstance workflowInstance = workflowInstanceDao.queryOptionalById(workflowInstanceId)
+                .orElseThrow(() -> new IllegalArgumentException("Cannot find WorkflowInstance:" + workflowInstanceId));
+        workflowInstance.setVarPool(null);
+        workflowInstance.setStateWithDesc(WorkflowExecutionStatus.RUNNING_EXECUTION, command.getCommandType().name());
+        workflowInstance.setCommandType(command.getCommandType());
+        workflowInstance.setStartTime(new Date());
```
Comment (caishunfeng) [inline dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/command/handler/ReRunWorkflowCommandHandler.java]: should not update start time when repeat running?

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/command/handler/RecoverFailureTaskCommandHandler.java [hunk 22]
```diff
@@ -0,0 +1,218 @@
...
+        workflowGraphBfsVisitor.visit();
+        return new ArrayList<>(taskInstanceMap.values());
+    }
+
+    /**
+     * Whether the task need to be recreated.
+     * <p> If the task state is FAILURE and KILL, then will mark the task invalid and recreate the task.
+     */
+    private boolean isTaskNeedRecreate(final TaskInstance taskInstance) {
+        return taskInstance.getState() == TaskExecutionStatus.FAILURE
```
Comment (caishunfeng) [inline dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/command/handler/RecoverFailureTaskCommandHandler.java:202]: Need to check task retry

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/graph/AbstractSuccessorParser.java [hunk 23]
```diff
@@ -15,19 +15,23 @@
...
+package org.apache.dolphinscheduler.server.master.engine.graph;
 
-/**
- * This exception represent the exception can not recover, this happens when the event is broken.
- * And when we get this exception, we will drop the event.
- */
-public class StateEventHandleError extends Exception {
+import org.apache.dolphinscheduler.dao.entity.TaskInstance;
+
+public abstract class AbstractSuccessorParser implements ISuccessorParser {
```
Comment (caishunfeng) [inline dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/graph/AbstractSuccessorParser.java]: Can you add some comments for the concept of `Successor Parser`?

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/executor/workflow/RecoverSuspendedWorkflowInstanceExecutorDelegate.java (hunk 6 above)
Comment (ruanwenjun) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/executor/workflow/RecoverSuspendedWorkflowInstanceExecutorDelegate.java:41]: Since the execute should have a response we need to use `Void` here.

```java
public interface IExecutorDelegate<T, R> {

    R execute(T t);
}
```

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/executor/workflow/PauseWorkflowInstanceExecutorDelegate.java (hunk 5 above)
Comment (ruanwenjun) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/executor/workflow/PauseWorkflowInstanceExecutorDelegate.java]: Done

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/executor/workflow/TriggerWorkflowExecutorDelegate.java (hunk 7 above)
Comment (ruanwenjun) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/executor/workflow/TriggerWorkflowExecutorDelegate.java:51]: Yes, I added the type check in TriggerWorkflowDTOValidator.

```java
public class TriggerWorkflowDTOValidator implements IValidator<TriggerWorkflowDTO> {

    @Override
    public void validate(final TriggerWorkflowDTO triggerWorkflowDTO) {
        if (triggerWorkflowDTO.getExecType() != CommandType.START_PROCESS) {
            throw new IllegalArgumentException("The execType should be START_PROCESS");
        }
    }
}
```

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/executor/workflow/TriggerWorkflowExecutorDelegate.java (hunk 8 above)
Comment (ruanwenjun) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/executor/workflow/TriggerWorkflowExecutorDelegate.java:43]: Yes, all check logic should at TriggerWorkflowDTOValidator.

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/executor/workflow/WorkflowInstanceControlRequest.java (hunk 9 above)
Comment (ruanwenjun) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/executor/workflow/WorkflowInstanceControlRequest.java]: This class is never used, I deleted this class. We use `xxWorkflowInstanceOperation` to replace the `xxRequest`

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/validator/workflow/TriggerWorkflowRequestValidator.java (hunk 10 above)
Comment (ruanwenjun) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/validator/workflow/TriggerWorkflowRequestValidator.java]: Yed, added.

File: dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/ProcessInstanceMapper.xml (hunk 12 above)
Comment (ruanwenjun) [reply dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/ProcessInstanceMapper.xml]: Done

File: dolphinscheduler-extract/dolphinscheduler-extract-master/src/main/java/org/apache/dolphinscheduler/extract/master/command/ICommandParam.java (hunk 13 above)
Comment (ruanwenjun) [reply dolphinscheduler-extract/dolphinscheduler-extract-master/src/main/java/org/apache/dolphinscheduler/extract/master/command/ICommandParam.java:58]: Right now it is needed, since the workflow is generated by command. So we need to know whether the command is used to generate or do operation on a sub workflow instance.

If the sub workflow instance is generated at sub logic task, then we can remove this method.

File: dolphinscheduler-extract/dolphinscheduler-extract-master/src/main/java/org/apache/dolphinscheduler/extract/master/transportor/ITaskExecutionEvent.java (hunk 14 above)
Comment (ruanwenjun) [reply dolphinscheduler-extract/dolphinscheduler-extract-master/src/main/java/org/apache/dolphinscheduler/extract/master/transportor/ITaskExecutionEvent.java]: No, we don't need this type, I removed this.

File: dolphinscheduler-extract/dolphinscheduler-extract-master/src/main/java/org/apache/dolphinscheduler/extract/master/transportor/ITaskExecutionEvent.java (hunk 15 above)
Comment (ruanwenjun) [reply dolphinscheduler-extract/dolphinscheduler-extract-master/src/main/java/org/apache/dolphinscheduler/extract/master/transportor/ITaskExecutionEvent.java:21]: Yes, it is needed, e.g. distinguish the event from the task executor or user operation. I add `todo` here.

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/cluster/MasterSlotManager.java (hunk 16 above)
Comment (ruanwenjun) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/cluster/MasterSlotManager.java]: Done

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/TaskGroupCoordinator.java (hunk 17 above)
Comment (ruanwenjun) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/TaskGroupCoordinator.java:427]: Done

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/WorkflowEventBusFireWorker.java (hunk 19 above)
Comment (ruanwenjun) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/WorkflowEventBusFireWorker.java:123]: I added sleep here, and don't direct return, since we still want to record the exception and error handle times.

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/WorkflowRepository.java (hunk 20 above)
Comment (ruanwenjun) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/WorkflowRepository.java]: Agree.

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/command/handler/ReRunWorkflowCommandHandler.java (hunk 21 above)
Comment (ruanwenjun) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/command/handler/ReRunWorkflowCommandHandler.java]: Yes, removed.

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/command/handler/RecoverFailureTaskCommandHandler.java (hunk 22 above)
Comment (ruanwenjun) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/command/handler/RecoverFailureTaskCommandHandler.java:202]: We don't need to check the retry, since we will create a new task instance no matter if the retry times are over the max retry times, since this is repeat running workflow instance.

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/graph/AbstractSuccessorParser.java (hunk 23 above)
Comment (ruanwenjun) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/graph/AbstractSuccessorParser.java]: I removed this class, this is replaced by 
```java
/**
 * Used to adjust the flow of tasks.
 * <p> Only {@link ConditionLogicTask} and {@link SwitchLogicTask} need to adjust the flow of tasks.
 */
@Slf4j
@Component
public class SuccessorFlowAdjuster {

}
```

which is used to control the flow of workflow and adjust the post tasks which should be trigger or skip.

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/graph/WorkflowGraphFactory.java [hunk 24]
```diff
@@ -0,0 +1,57 @@
...
+    @Autowired
+    private TaskDefinitionLogDao taskDefinitionLogDao;
+
+    public IWorkflowGraph createWorkflowGraph(ProcessDefinition workflowDefinition) {
+
+        List<ProcessTaskRelation> processTaskRelations = processService.findRelationByCode(
+                workflowDefinition.getCode(),
+                workflowDefinition.getVersion());
+
+        List<TaskDefinition> taskDefinitions = taskDefinitionLogDao.queryTaskDefineLogList(processTaskRelations)
```
Comment (caishunfeng) [inline dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/graph/WorkflowGraphFactory.java:50]: Check duplication here.

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/system/event/SystemEventType.java [hunk 25]
```diff
@@ -15,10 +15,12 @@
...
 
-package org.apache.dolphinscheduler.server.master.runner.listener;
+package org.apache.dolphinscheduler.server.master.engine.system.event;
 
-public interface ITaskInstanceExecutionEventListenFunction<E> {
+public enum SystemEventType {
 
-    void handleTaskInstanceExecutionEvent(E e);
+    GLOBAL_MASTER_FAILOVER,
+    MASTER_FAILOVER,
```
Comment (caishunfeng) [inline dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/system/event/SystemEventType.java]: It's better to add some comments for the difference.

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/task/client/PhysicalTaskExecutorClientDelegator.java [hunk 26]
```diff
@@ -0,0 +1,81 @@
...
+
+import org.apache.commons.lang3.StringUtils;
+
+import lombok.extern.slf4j.Slf4j;
+
+import org.springframework.stereotype.Component;
+
+@Slf4j
+@Component
+public class PhysicalTaskExecutorClientDelegator implements ITaskExecutorClientDelegator {
```
Comment (caishunfeng) [inline dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/task/client/PhysicalTaskExecutorClientDelegator.java:39]: Is the `PhysicalTask` means The tasks which execute on worker?

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/task/statemachine/AbstractTaskStateAction.java [hunk 27]
```diff
@@ -0,0 +1,310 @@
...
+                    .taskInstanceId(taskExecutionRunnable.getTaskInstance().getId())
+                    .workflowHost(masterConfig.getMasterAddress())
+                    .build();
+            final TakeOverTaskResponse takeOverTaskResponse = SingletonJdkDynamicRpcClientProxyFactory
+                    .withService(ITaskInstanceOperator.class)
+                    .withHost(taskExecutionRunnable.getTaskInstance().getHost())
+                    .takeOverTask(takeOverTaskRequest);
+            return takeOverTaskResponse.isSuccess();
+        } catch (Exception ex) {
+            log.info("Take over task: {} failed", taskExecutionRunnable.getName(), ex);
```
Comment (caishunfeng) [inline dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/task/statemachine/AbstractTaskStateAction.java]:
```suggestion
            log.error("Take over task: {} failed", taskExecutionRunnable.getName(), ex);
```

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/TaskExecutionRunnableRepository.java [hunk 28]
```diff
@@ -0,0 +1,212 @@
...
+import java.util.concurrent.ConcurrentHashMap;
+import java.util.stream.Collectors;
+
+import com.google.common.collect.Sets;
+
+/**
+ * The repository used to store the {@link ITaskExecutionRunnable} in {@link IWorkflowExecutionRunnable}.
+ * This will not store all the {@link ITaskExecutionRunnable} in the memory, it will only store the {@link ITaskExecutionRunnable} which is active.
+ */
+public class TaskExecutionRunnableRepository {
```
Comment (caishunfeng) [inline dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/TaskExecutionRunnableRepository.java]:
```suggestion
public class TaskExecutionRunnableCacheRepository {
```

File: dolphinscheduler-master/src/test/java/org/apache/dolphinscheduler/server/master/AbstractMasterIntegrationTest.java [hunk 29]
```diff
@@ -0,0 +1,50 @@
...
+/**
+ * The abstract class for master integration test.
+ * <p> Used to create a text environment to test master server.
+ * <p> In order to separate the environment for each text case, the context will be dirtied before each test method.
+ */
+@SpringBootTest(classes = {
+        MasterServer.class,
+        DaoConfiguration.class})
+@DirtiesContext(classMode = DirtiesContext.ClassMode.AFTER_EACH_TEST_METHOD)
+public abstract class AbstractMasterIntegrationTest {
```
Comment (caishunfeng) [inline dolphinscheduler-master/src/test/java/org/apache/dolphinscheduler/server/master/AbstractMasterIntegrationTest.java:39]: :+1:

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/system/event/SystemEventType.java (hunk 25 above)
Comment (ruanwenjun) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/system/event/SystemEventType.java]: Done

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/graph/WorkflowGraphFactory.java (hunk 24 above)
Comment (ruanwenjun) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/graph/WorkflowGraphFactory.java:50]: Checked in `WorkflowGraph`.

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/task/client/PhysicalTaskExecutorClientDelegator.java (hunk 26 above)
Comment (ruanwenjun) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/task/client/PhysicalTaskExecutorClientDelegator.java:39]: Yes

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/task/statemachine/AbstractTaskStateAction.java (hunk 27 above)
Comment (ruanwenjun) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/task/statemachine/AbstractTaskStateAction.java]: I changed to warn since if the worker is not alive, there will be exceptions here.

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/TaskExecutionRunnableRepository.java (hunk 28 above)
Comment (ruanwenjun) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/TaskExecutionRunnableRepository.java]: Done, removed this class, never used.

**Review by caishunfeng — APPROVED** [review]
LGTM overall.

**Review by SbloodyS — APPROVED** [review]
+1
