### PR TITLE
[Fix-17597][Master] Fix condition task node not run in workflow when pre-task node failed

### LINKED ISSUE #17597: [Bug] [workflow] version 3.3.1 condition task node not run when parent node failed
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

I build a pipline like below. when node1 run success, condition node that is named check_status run, and success node run. But when node1 run failed, condition node that is named check_status not run.

[workflow_1761270973885.json](https://github.com/user-attachments/files/23111161/workflow_1761270973885.json)

Image

### What you expected to happen

when node1 run failed, condition node that is named check_status should run and shell node that is named failed should run.

### How to reproduce

[workflow_1761270973885.json](https://github.com/user-attachments/files/23111166/workflow_1761270973885.json)   The json file is about the workflow pipline, you can  build a pipline like this to reproduce it

### Anything else

_No response_

### Version

3.3.1

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by sanfeng-lhh**
## Purpose of the pull request

close #17597

## Brief change log
org.apache.dolphinscheduler.server.master.engine.graph.WorkflowExecutionGraph#isEndOfTaskChain add isAllSuccessorsAreConditionTask judge when task execute failed

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

## Pull Request Notice
[Pull Request Notice](https://github.com/apache/dolphinscheduler/blob/dev/docs/docs/en/contribute/join/pull-request.md)

If your pull request contains incompatible change, you should also add it to `docs/docs/en/guide/upgrade/incompatible.md`

### CODE REVIEW

**Comment by sanfeng-lhh** [comment]
@ruanwenjun  I have verified this function on our project's cluster. Please help review it when you have time. Thanks.

**Comment by ruanwenjun** [comment]
@sanfeng-lhh Thanks for your PR, the code look pretty good, but please add test case for this. You can find some example from `WorkflowStartTestCase`.

**Comment by sanfeng-lhh** [comment]
> @sanfeng-lhh Thanks for your PR, the code look pretty good, but please add test case for this. You can find some example from `WorkflowStartTestCase`.
I have add two it cases about condition task. Please help review it when you have time. Thanks.

**Review by ruanwenjun — DISMISSED** [review]
LGTM

**Review by SbloodyS — DISMISSED** [review]
+1

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/graph/WorkflowExecutionGraph.java [hunk 1]
```diff
@@ -335,7 +336,7 @@ public boolean isAllSuccessorsAreConditionTask(final ITaskExecutionRunnable task
         }
         return successors.stream().allMatch(
                 successor -> isTaskExecutionRunnableSkipped(successor)
-                        || TaskTypeUtils.isConditionTask(taskExecutionRunnable.getTaskInstance().getTaskType()));
+                        || TaskTypeUtils.isConditionTask(successor.getTaskDefinition().getTaskType()));
```
Comment (ruanwenjun) [inline dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/graph/WorkflowExecutionGraph.java]: We may need to filter the forbidden susseccors here, 
```java
(TaskTypeUtils.isConditionTask(successor.getTaskDefinition().getTaskType()) && !isTaskExecutionRunnableForbidden(successor))
```
if the successor condition task is forbidden, then should return false.

**Comment by Mrhs121** [comment]
During the debugging process, I also discovered another problem. The judgment logic in the isTriggerConditionMet method also has the same problem. If the predecessor node that the condition node depends on fails, it will return early, so the condition node will not be triggered

https://github.com/apache/dolphinscheduler/blob/f4646cef338d81cc21536be0409cd67e42d00d0b/dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/workflow/statemachine/AbstractWorkflowStateAction.java#L72-L82

**Comment by ruanwenjun** [comment]
> During the debugging process, I also discovered another problem. The judgment logic in the isTriggerConditionMet method also has the same problem. If the predecessor node that the condition node depends on fails, it will return early, so the condition node will not be triggered
> 
> https://github.com/apache/dolphinscheduler/blob/f4646cef338d81cc21536be0409cd67e42d00d0b/dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/workflow/statemachine/AbstractWorkflowStateAction.java#L72-L82

Please use the latest code, I am not sure if this has been fixed by #17601, welcome to add IT case.

**Comment by Mrhs121** [comment]
> > During the debugging process, I also discovered another problem. The judgment logic in the isTriggerConditionMet method also has the same problem. If the predecessor node that the condition node depends on fails, it will return early, so the condition node will not be triggered
> > https://github.com/apache/dolphinscheduler/blob/f4646cef338d81cc21536be0409cd67e42d00d0b/dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/workflow/statemachine/AbstractWorkflowStateAction.java#L72-L82
> 
> Please use the latest code, I am not sure if this has been fixed by #17601, welcome to add IT case.




I checked the code, I found the repair `isAllSuccessorsAreConditionTask` method code just repaired the `triggerTasks` method **potential errors in judgment logic**



https://github.com/apache/dolphinscheduler/blob/24e599760f6b6d20d2a9c2c415243bc2f05840f9/dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/task/statemachine/AbstractTaskStateAction.java#L180-L184
due to `isAllSuccessorsAreConditionTask` method repaired, so failed task will not be marked as a Failure, 
https://github.com/apache/dolphinscheduler/blob/24e599760f6b6d20d2a9c2c415243bc2f05840f9/dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/graph/WorkflowExecutionGraph.java#L261-L264

so `isTaskExecutionRunnableFailed` method return false.
https://github.com/apache/dolphinscheduler/blob/24e599760f6b6d20d2a9c2c415243bc2f05840f9/dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/graph/WorkflowExecutionGraph.java#L183-L185
So the ready condition type task will be retained and thus triggered normally
https://github.com/apache/dolphinscheduler/blob/24e599760f6b6d20d2a9c2c415243bc2f05840f9/dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/graph/WorkflowExecutionGraph.java#L206-L217

**Comment by ruanwenjun** [comment]
@Mrhs121 So this PR has fixed this case.

**Review by ruanwenjun — APPROVED** [review]

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/graph/WorkflowExecutionGraph.java (hunk 1 above)
Comment (sanfeng-lhh) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/graph/WorkflowExecutionGraph.java]: That's right, I've added this condition. Thanks.

**Review by SbloodyS — APPROVED** [review]
