### PR TITLE
[Fix-17316][Task-API] Add check process status after killing task

### LINKED ISSUE #17316: [Bug] [Task-API] When the task is Kill, the task instance shows that the Kill is normal, but the task process is not Killed
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

The latest version was deployed using dolphinscheduler user;
Create a new shell task type, select the default defalut tenant to submit and run, and then Kill the task on the interface;
It was found that the task process on the Worker machine was not really knocked out, but the task instance and workflow instance were shown to be normal knocked out.

### What you expected to happen

After the workflow is killed on the UI interface, if the task instance has been displayed to be normal, the relevant task processes on the Worker machine should be removed normally.

file location: dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/utils/ProcessUtils.java

The method of bugs is:

`
public static boolean kill(@NonNull TaskExecutionContext request) {
        try {
            log.info("Begin killing task instance, processId: {}", request.getProcessId());
            int processId = request.getProcessId();
            if (processId == 0) {
                log.info("Task instance has already finished, no need to kill");
                return true;
            }

            // Get all child processes
            String pids = getPidsStr(processId);
            String[] pidArray = pids.split("\\s+");
            if (pidArray.length == 0) {
                log.warn("No valid PIDs found for process: {}", processId);
                return true;
            }

            // 1. Try to terminate gracefully (SIGINT)
            boolean gracefulKillSuccess = sendKillSignal("SIGINT", pids, request.getTenantCode());
            if (gracefulKillSuccess) {
                log.info("Successfully killed process tree using SIGINT, processId: {}", processId);
                return true;
            }

            // 2. Try to terminate forcefully (SIGTERM)
            boolean termKillSuccess = sendKillSignal("SIGTERM", pids, request.getTenantCode());
            if (termKillSuccess) {
                log.info("Successfully killed process tree using SIGTERM, processId: {}", processId);
                return true;
            }

            // 3. As a last resort, use `kill -9`
            log.warn("SIGINT & SIGTERM failed, using SIGKILL as a last resort for processId: {}", processId);
            boolean forceKillSuccess = sendKillSignal("SIGKILL", pids, request.getTenantCode());
            if (forceKillSuccess) {
                log.info("Successfully sent SIGKILL signal to process tree, processId: {}", processId);
            } else {
                log.error("Error sending SIGKILL signal to process tree, processId: {}", processId);
            }
            return forceKillSuccess;
        } catch (Exception e) {
            log.error("Kill task instance error, processId: {}", request.getProcessId(), e);
            return false;
        }
    }
`

The sendKillSignal method only sends a signal to the Kill process, and does not guarantee that the underlying operating system has actually lost the process. It is necessary to add logic to check whether the process survives after sending the Kill signal.

### How to reproduce

1，The shell task script is as follows:
`
echo ${JAVE_HOME};
sleep 10m
`

2, Kill workflow on the UI interface. After a while, the task instance and workflow instance are displayed as have been Killed. The log of the task instance is as follows:

`
Executing shell command : sudo -u dolphinscheduler -i /data01/dolphinscheduler/exec/process/87/87.sh

process start, process id is: 3502853

......
Begin killing task instance, processId: 3502853

prepare to parse pid, raw pid string: sudo(3502853)---87.sh(3502868)---sleep(3502945)

Sending SIGINT to process group: 3502853 3502868 3502945, command: sudo -u dolphinscheduler kill -s SIGINT 3502853 3502868 3502945

Successfully killed process tree using SIGINT, processId: 3502853

Process tree for task: 87 is killed or already finished, pid: 3502853
`

3，however, using the pstree command on the Worker machine to view the task process still exists and is not Killed
`
$ pstree -p 3502853

sudo(3502853)───87.sh(3502868)───sleep(3502945)
`

### Anything else

_No response_

### Version

3.3.0-alpha

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by njnu-seafish**
## Purpose of the pull request

close https://github.com/apache/dolphinscheduler/issues/17316

## Brief change log

after kill the process, and check process status

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

## Pull Request Notice
[Pull Request Notice](https://github.com/apache/dolphinscheduler/blob/dev/docs/docs/en/contribute/join/pull-request.md)

If your pull request contains incompatible change, you should also add it to `docs/docs/en/guide/upgrade/incompatible.md`

### CODE REVIEW

**Review by SbloodyS — COMMENTED** [review]
I've tested this issue #17316 base on your reproduction steps in macos and ubuntu 24.04 and found this issue does not exist, please describe the specific reproduction environment. @njnu-seafish

**Comment by njnu-seafish** [comment]
> I've tested this issue #17316 base on your reproduction steps in macos and ubuntu 24.04 and found this issue does not exist, please describe the specific reproduction environment. @njnu-seafish

Sorry, I was very busy during the day and didn't have time to reply.
My environment is centos7.
Below is an example I tested directly on my machine.
`
[dolphinscheduler@xxxxx][~]
$ more test.sh 
echo ${JAVE_HOME};
sleep 10m


[dolphinscheduler@xxxxx][~]
$ date
Fri Jul  4 22:59:27 CST 2025


[dolphinscheduler@xxxxx][~]
$ sudo -u dolphinscheduler -i sh test.sh 


[dolphinscheduler@xxxxx][~]
$ ps -ef | grep -i test.sh
root     1259617 1258564  0 22:59 pts/5    00:00:00 sudo -u dolphinscheduler -i sh test.sh


[dolphinscheduler@xxxxx][~]
$ pstree -p 1259617
sudo(1259617)───sh(1259618)───sleep(1259696)


[dolphinscheduler@xxxxx][~]
$ pstree -p 1259617
sudo(1259617)───sh(1259618)───sleep(1259696)

// kill -s SIGINT return 0.  However, the process was not actually killed.
[dolphinscheduler@xxxxx][~]
$ sudo -u dolphinscheduler kill -s SIGINT 1259617 1259618 1259696

[dolphinscheduler@xxxxx][~]
$ echo $?
0

// wating 5m
[dolphinscheduler@xxxxx][~]
$ date
Fri Jul  4 23:04:19 CST 2025

[dolphinscheduler@xxxxx][~]
$ ps -ef | grep -i test.sh
root     1259617 1258564  0 22:59 pts/5    00:00:00 sudo -u dolphinscheduler -i sh test.sh


[dolphinscheduler@xxxxx][~]
$ pstree -p 1259617
sudo(1259617)───sh(1259618)───sleep(1259696)

`

**Comment by njnu-seafish** [comment]
> I've tested this issue #17316 base on your reproduction steps in macos and ubuntu 24.04 and found this issue does not exist, please describe the specific reproduction environment. @njnu-seafish

After fixing the bug according to the code above, the log of the task instance is as follows.
`
Final Shell file is: 

****************************** Script Content *****************************************************************

#!/bin/bash

BASEDIR=$(cd `dirname $0`; pwd)

cd $BASEDIR

source /usr/local/dolphinscheduler/bin/env/dolphinscheduler_env.sh

echo ${JAVE_HOME}

sleep 10m

****************************** Script Content *****************************************************************

Executing shell command : sudo -u dolphinscheduler -i /data01/dolphinscheduler/exec/process/130/130.sh

process start, process id is: 643464

Begin killing task instance, processId: 643464

prepare to parse pid, raw pid string: sudo(643464)---130.sh(643479)---sleep(643559)

Kill command: kill -s SIGINT 643464 643479 643559, trying to terminate process

Kill command: sudo -u dolphinscheduler -i kill -s SIGINT 643464 643479 643559, kill failed, the process: 643464 is still running

Kill command: kill -s SIGTERM 643464 643479 643559, trying to terminate process

Kill command: sudo -u dolphinscheduler -i kill -s SIGTERM 643464 643479 643559, kill succeeded

Successfully killed process tree using SIGTERM, processId: 643464

Process tree for task: 130 is killed or already finished, pid: 643464

`

File: dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/utils/ProcessUtils.java [hunk 1]
```diff
@@ -56,6 +56,9 @@
 @Slf4j
 public final class ProcessUtils {
 
+    // Wait 5 seconds to check process status
+    private static final int CHECK_PROCESS_WAITING_MILLIS = 5000;
```
Comment (SbloodyS) [inline dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/utils/ProcessUtils.java]: Explicit waiting is not a good way for user experience. Some programs take some time to shut down gracefully. We should set this as an implicit wait and put this time in the configuration file for the user to configure.

Comment (njnu-seafish) [reply dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/utils/ProcessUtils.java]: Well，Your suggestion is great, I'll incorporate it into the code.

File: dolphinscheduler-common/src/main/resources/common.properties [hunk 2]
```diff
@@ -104,4 +107,4 @@ shell.env_source_list=
 shell.interceptor.type=bash
 
 # Whether to enable remote logging
-remote.logging.enable=false
+remote.logging.enable=false
```
Comment (SbloodyS) [inline dolphinscheduler-common/src/main/resources/common.properties]: Please add blank lines at the end of each line.

File: dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/resources/docker/file-manage/common.properties [hunk 3]
```diff
@@ -111,4 +114,4 @@ ml.mlflow.preset_repository=https://github.com/apache/dolphinscheduler-mlflow
 ml.mlflow.preset_repository_version="main"
 
 # way to collect applicationId: log(original regex match), aop
-appId.collect: log
+appId.collect=log
```
Comment (SbloodyS) [inline dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/resources/docker/file-manage/common.properties]: Same here.

File: dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/utils/ProcessUtils.java [hunk 4]
```diff
@@ -144,18 +155,54 @@ public static boolean kill(@NonNull TaskExecutionContext request) {
...
+     * Check if a process with the specified PID is alive.
+     *
+     * @param pid the process ID to check
+     * @return true if the process exists and is running, false otherwise
+     */
+    private static boolean isProcessAlive(int pid) {
+        try {
+            // Use kill -0 to check if the process exists; it does not actually send a signal
+            String checkCmd = String.format("kill -0 %d", pid);
+            OSUtils.exeCmd(checkCmd);
```
Comment (SbloodyS) [inline dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/utils/ProcessUtils.java:244]: Using `OSUtils.getSudoCmd` to get `killCmd`

File: dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/utils/ProcessUtils.java [hunk 5]
```diff
@@ -144,18 +155,54 @@ public static boolean kill(@NonNull TaskExecutionContext request) {
      */
     private static boolean sendKillSignal(String signal, String pids, String tenantCode) {
         try {
+            // 1. Send the kill signal
             String killCmd = String.format("kill -s %s %s", signal, pids);
+            log.info("Kill command: {}, trying to terminate process", killCmd);
```
Comment (SbloodyS) [inline dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/utils/ProcessUtils.java]:
```suggestion
```

We don't need this log since we already log it in L162.

File: dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/utils/ProcessUtils.java [hunk 6]
```diff
@@ -144,18 +155,54 @@ public static boolean kill(@NonNull TaskExecutionContext request) {
...
+            String[] pidArray = PID_PATTERN.split(pids);
+            for (String pid : pidArray) {
+                // Check if each PID is still alive
+                if (isProcessAlive(Integer.parseInt(pid))) {
+                    log.info("Kill command: {}, kill failed, the process: {} is still running", killCmd, pid);
+                    // Return false if any process is still alive
+                    return false;
+                }
+            }
+            log.info("Kill command: {}, kill succeeded", killCmd);
```
Comment (SbloodyS) [inline dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/utils/ProcessUtils.java]:
```suggestion
            log.debug("Kill command: {}, kill succeeded", killCmd);
```

File: dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/utils/ProcessUtils.java [hunk 7]
```diff
@@ -244,11 +291,12 @@ public static void cancelApplication(TaskExecutionContext taskExecutionContext)
                     taskExecutionContext.setAppIds(String.join(TaskConstants.COMMA, appIds));
                 }
                 if (CollectionUtils.isEmpty(appIds)) {
-                    log.info("The appId is empty");
+                    log.info("The appId is empty, so there is no need to kill yarn application.");
```
Comment (SbloodyS) [inline dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/utils/ProcessUtils.java]:
```suggestion
                    log.info("The appId is empty");
```

We don't need this since not all shell task are yarn type.

File: dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/utils/ProcessUtils.java (hunk 4 above)
Comment (njnu-seafish) [reply dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/utils/ProcessUtils.java:244]: Yes，I‘m sorry.  I've already made the changes based on your suggestions. thanks

File: dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/utils/ProcessUtils.java [hunk 8]
```diff
@@ -144,18 +155,54 @@ public static boolean kill(@NonNull TaskExecutionContext request) {
...
+     *
+     * @param pid the process ID to check
+     * @return true if the process exists and is running, false otherwise
+     */
+    private static boolean isProcessAlive(int pid, String tenantCode) {
+        try {
+            // Use kill -0 to check if the process exists; it does not actually send a signal
+            String checkCmd = String.format("kill -0 %d", pid);
+            checkCmd = OSUtils.getSudoCmd(tenantCode, checkCmd);
+            OSUtils.exeCmd(checkCmd);
```
Comment (SbloodyS) [inline dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/utils/ProcessUtils.java:244]: I found that `OSUtils.exeCmd` would not return any result or exit code or throw exception if command run normally but exit code is not 0. We need to find a new way to verify the exit code is 0 or not. Otherwise this will always equal true.

Comment (SbloodyS) [reply dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/utils/ProcessUtils.java:244]: I was wrong. It would throw `ExitCodeException`. Please ignore it.

**Comment by SbloodyS** [comment]
Please run `mvn spotless:apply` to format the code. @njnu-seafish

File: deploy/kubernetes/dolphinscheduler/README.md [hunk 9]
```diff
@@ -134,6 +134,7 @@ Please refer to the [Quick Start in Kubernetes](../../../docs/docs/en/guide/inst
 | conf.common."datasource.encryption.enable" | bool | `false` | datasource encryption enable |
 | conf.common."datasource.encryption.salt" | string | `"!@#$%^&*"` | datasource encryption salt |
 | conf.common."development.state" | bool | `false` | development state |
+| conf.common."process.status.check.delay" | int | `5` | The delay before checking the process status after termination (in seconds) |
```
Comment (SbloodyS) [inline deploy/kubernetes/dolphinscheduler/README.md]:
```suggestion
| conf.common."process.status.check.delay" | int | `5` | The delay before checking the shell process status after termination (in seconds) |
```

File: deploy/kubernetes/dolphinscheduler/values.yaml [hunk 10]
```diff
@@ -345,6 +345,9 @@ conf:
     # -- development state
     development.state: false
 
+    # -- The delay before checking the process status after termination (in seconds)
```
Comment (SbloodyS) [inline deploy/kubernetes/dolphinscheduler/values.yaml]:
```suggestion
    # -- The delay before checking the shell process status after termination (in seconds)
```

File: dolphinscheduler-api-test/dolphinscheduler-api-test-case/src/test/resources/docker/file-manage/common.properties [hunk 11]
```diff
@@ -99,6 +99,9 @@ sudo.enable=true
 # development state
 development.state=false
 
+# The delay before checking the process status after termination (in seconds)
```
Comment (SbloodyS) [inline dolphinscheduler-api-test/dolphinscheduler-api-test-case/src/test/resources/docker/file-manage/common.properties]:
```suggestion
# The delay before checking the shell process status after termination (in seconds)
```

**Comment by SbloodyS** [comment]
`Helm-Doc` check failed. I don't know why. PTAL @Gallardot

**Comment by SbloodyS** [comment]
UT also failed. Please check it. @njnu-seafish

**Comment by njnu-seafish** [comment]
> UT also failed. Please check it. @njnu-seafish

update

**Review by SbloodyS — DISMISSED** [review]
LGTM

File: deploy/kubernetes/dolphinscheduler/README.md [hunk 12]
```diff
@@ -141,6 +141,7 @@ Please refer to the [Quick Start in Kubernetes](../../../docs/docs/en/guide/inst
 | conf.common."login.user.keytab.username" | string | `"hdfs-mycluster@ESZ.COM"` | login user from keytab username |
 | conf.common."ml.mlflow.preset_repository" | string | `"https://github.com/apache/dolphinscheduler-mlflow"` | mlflow task plugin preset repository |
 | conf.common."ml.mlflow.preset_repository_version" | string | `"main"` | mlflow task plugin preset repository version |
+| conf.common."process.status.check.delay" | int | `5` | The delay before checking the shell process status after termination (in seconds) |
```
Comment (ruanwenjun) [inline deploy/kubernetes/dolphinscheduler/README.md]:
```suggestion
| conf.common."shell.kill.wait.timeout" | int | `30` | If the shell process still active after this value, then will use kill -9 to kill it(in seconds) |
```

File: dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/utils/ProcessUtils.java [hunk 13]
```diff
@@ -144,18 +156,54 @@ public static boolean kill(@NonNull TaskExecutionContext request) {
...
     private static boolean sendKillSignal(String signal, String pids, String tenantCode) {
         try {
+            // 1. Send the kill signal
             String killCmd = String.format("kill -s %s %s", signal, pids);
             killCmd = OSUtils.getSudoCmd(tenantCode, killCmd);
             log.info("Sending {} to process group: {}, command: {}", signal, pids, killCmd);
             OSUtils.exeCmd(killCmd);
 
+            // 2. Wait for the process to respond to the signal
+            ThreadUtils.sleep(SLEEP_TIME_MILLIS * PROCESS_STATUS_CHECK_DELAY);
```
Comment (ruanwenjun) [inline dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/utils/ProcessUtils.java]: It's better to use while to check whether the process is still alive, if it still alive after timeout, then use `kill -9`

Comment (njnu-seafish) [reply dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/utils/ProcessUtils.java]: The logic for 'kill' already exists：
           
            // 1. Try to terminate gracefully (SIGINT)
            boolean gracefulKillSuccess = sendKillSignal("SIGINT", pids, request.getTenantCode());
            if (gracefulKillSuccess) {
                log.info("Successfully killed process tree using SIGINT, processId: {}", processId);
                return true;
            }

            // 2. Try to terminate forcefully (SIGTERM)
            boolean termKillSuccess = sendKillSignal("SIGTERM", pids, request.getTenantCode());
            if (termKillSuccess) {
                log.info("Successfully killed process tree using SIGTERM, processId: {}", processId);
                return true;
            }

            // 3. As a last resort, use `kill -9`
            log.warn("SIGINT & SIGTERM failed, using SIGKILL as a last resort for processId: {}", processId);
            boolean forceKillSuccess = sendKillSignal("SIGKILL", pids, request.getTenantCode());
            if (forceKillSuccess) {
                log.info("Successfully sent SIGKILL signal to process tree, processId: {}", processId);
            } else {
                log.error("Error sending SIGKILL signal to process tree, processId: {}", processId);
            }
            return forceKillSuccess;

File: deploy/kubernetes/dolphinscheduler/README.md (hunk 12 above)
Comment (njnu-seafish) [reply deploy/kubernetes/dolphinscheduler/README.md]: Sorry,I'm a bit confused.   "shell.kill.wait.timeout"?  the time is for wating to check process status after killing

Comment (ruanwenjun) [reply deploy/kubernetes/dolphinscheduler/README.md]: I think it's better used for waiting the soft kill result. If it timeout then hard kill. This seems make little sense if only wait the process exit. If it doesn't exit, then you should not return.

Comment (njnu-seafish) [reply deploy/kubernetes/dolphinscheduler/README.md]: // 1. Try to terminate gracefully (SIGINT)
        boolean gracefulKillSuccess = sendKillSignal("SIGINT", pids, request.getTenantCode());
        if (gracefulKillSuccess) {
            log.info("Successfully killed process tree using SIGINT, processId: {}", processId);
            return true;
        }

        The key issue is that the soft kill returns success, but the physical process is not actually killed, so we need to add a check process status logic.

Comment (njnu-seafish) [reply deploy/kubernetes/dolphinscheduler/README.md]: > I think it's better used for waiting the soft kill result. If it timeout then hard kill. This seems make little sense if only wait the process exit. If it doesn't exit, then you should not return.


In actual development and operations, do not use SIGKILL right away, as it deprives the process of the opportunity to clean up resources. The recommended approach is:

First send SIGINT, wait for a certain amount of time (e.g., 5–10 seconds), and check the process status.

If the process hasn't exited, send SIGTERM, wait again (e.g., 5–10 seconds), and check the process status.

If the process still hasn't exited, then send SIGKILL.

A key point: even if SIGINT returns successfully, the process may still be running. Therefore, it's essential to add a check logic to confirm whether the process has truly exited.

Comment (ruanwenjun) [reply deploy/kubernetes/dolphinscheduler/README.md]: If the process doesn't exit, there seems to be no point in checking here

File: dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/utils/ProcessUtils.java (hunk 13 above)
Comment (ruanwenjun) [reply dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/utils/ProcessUtils.java]: Once send SIGINT/SIGTERM, the process might have some work to do, so the process will not exist directly, the process can ignore the sig, so we need to check during a window, if timeout and the process exist, then need to kill -9.

File: deploy/kubernetes/dolphinscheduler/README.md (hunk 12 above)
Comment (njnu-seafish) [reply deploy/kubernetes/dolphinscheduler/README.md]: Thank you so much for your suggestions!

File: dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/utils/ProcessUtils.java (hunk 13 above)
Comment (njnu-seafish) [reply dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/utils/ProcessUtils.java]: Thank you so much for your suggestions! I've made revisions based on your input. Could you kindly review it again? Thanks a lot!

File: dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/utils/ProcessUtils.java [hunk 14]
```diff
@@ -100,29 +113,39 @@ public static boolean kill(@NonNull TaskExecutionContext request) {
...
                 return true;
             }
 
+            // Convert PID string to list of integers
+            List<Integer> pidList = new ArrayList<>();
+            for (String pidStr : pidArray) {
+                try {
+                    pidList.add(Integer.parseInt(pidStr));
+                } catch (NumberFormatException e) {
+                    log.warn("Invalid PID: {}", pidStr);
```
Comment (ruanwenjun) [inline dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/utils/ProcessUtils.java]: return false?

**Review by ruanwenjun — DISMISSED** [review]
LGTM

**Comment by ruanwenjun** [comment]
> ## Pull Request Overview
> This PR adds a configurable timeout for waiting on shell process termination and enhances the kill logic to poll process status after sending kill signals. It also updates various resource configurations and bumps the Kubernetes Helm chart version.
> 
> * Introduce `shell.kill.wait.timeout` property in common configs and add `SHELL_KILL_WAIT_TIMEOUT` constant
> * Refactor `ProcessUtils.kill` to parse PIDs into a list, send signals, and poll until processes exit
> * Update E2E/test properties, document new config in Helm values and README, and bump chart version
> 
> ### Reviewed Changes
> Copilot reviewed 10 out of 10 changed files in this pull request and generated no comments.
> 
> Show a summary per file
> File	Description
> dolphinscheduler-task-plugin/.../common.properties	Add `shell.kill.wait.timeout` property
> ProcessUtils.java	Parse PIDs into `List<Integer>`, implement polling with timeout, add `isProcessAlive`
> dolphinscheduler-e2e/.../common.properties	Add timeout property and fix `appId.collect` syntax
> dolphinscheduler-common/.../common.properties	Add `shell.kill.wait.timeout` to test and main resources
> Constants.java	Add `SHELL_KILL_WAIT_TIMEOUT` constant
> values.yaml	Add `shell.kill.wait.timeout` under `conf`
> README.md	Document `shell.kill.wait.timeout` in chart config
> Chart.yaml	Bump `version` and `appVersion` to 3.1.1
> Comments suppressed due to low confidence (4)
> **dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/constants/Constants.java:75**
> 
> * [nitpick] The Javadoc for this constant is minimal. Consider expanding it to explain that this property defines the wait timeout in seconds before using SIGKILL.
> 
> ```
>     public static final String SHELL_KILL_WAIT_TIMEOUT = "shell.kill.wait.timeout";
> ```
> 
> **dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/utils/ProcessUtils.java:54**
> 
> * It looks like `List` and `ArrayList` are used later in this class but not imported here. Please add `import java.util.List;` and `import java.util.ArrayList;` to avoid compile errors.
> 
> ```
> import java.util.stream.Collectors;
> ```
> 
> **dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/utils/ProcessUtils.java:168**
> 
> * [nitpick] Mutating the original `pidList` inside this method can lead to side effects if the list is reused elsewhere. Consider making a defensive copy of the list before polling/removal.
> 
> ```
>     private static boolean sendKillSignal(String signal, List<Integer> pidList, String tenantCode) {
> ```
> 
> **dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/utils/ProcessUtils.java:188**
> 
> * [nitpick] The multiplication here assumes `SLEEP_TIME_MILLIS` maps directly to milliseconds. It might be clearer to calculate `timeoutMillis = TimeUnit.SECONDS.toMillis(SHELL_KILL_WAIT_TIMEOUT)` or document the relationship explicitly.
> 
> ```
>             long timeoutMillis = SLEEP_TIME_MILLIS * SHELL_KILL_WAIT_TIMEOUT;
> ```

Please take care about the comment from copilot.

File: dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/utils/ProcessUtils.java (hunk 14 above)
Comment (njnu-seafish) [reply dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/utils/ProcessUtils.java]: // Convert PID string to list of integers
            List<Integer> pidList = new ArrayList<>();
            for (String pidStr : pidArray) {
                pidList.add(Integer.parseInt(pidStr));
            }                
The outer try-catch block will capture and handle the exception.

**Comment by njnu-seafish** [comment]
> > ## Pull Request Overview
> > This PR adds a configurable timeout for waiting on shell process termination and enhances the kill logic to poll process status after sending kill signals. It also updates various resource configurations and bumps the Kubernetes Helm chart version.
> > 
> > * Introduce `shell.kill.wait.timeout` property in common configs and add `SHELL_KILL_WAIT_TIMEOUT` constant
> > * Refactor `ProcessUtils.kill` to parse PIDs into a list, send signals, and poll until processes exit
> > * Update E2E/test properties, document new config in Helm values and README, and bump chart version
> > 
> > ### Reviewed Changes
> > Copilot reviewed 10 out of 10 changed files in this pull request and generated no comments.
> > Show a summary per file
> > File	Description
> > dolphinscheduler-task-plugin/.../common.properties	Add `shell.kill.wait.timeout` property
> > ProcessUtils.java	Parse PIDs into `List<Integer>`, implement polling with timeout, add `isProcessAlive`
> > dolphinscheduler-e2e/.../common.properties	Add timeout property and fix `appId.collect` syntax
> > dolphinscheduler-common/.../common.properties	Add `shell.kill.wait.timeout` to test and main resources
> > Constants.java	Add `SHELL_KILL_WAIT_TIMEOUT` constant
> > values.yaml	Add `shell.kill.wait.timeout` under `conf`
> > README.md	Document `shell.kill.wait.timeout` in chart config
> > Chart.yaml	Bump `version` and `appVersion` to 3.1.1
> > Comments suppressed due to low confidence (4)
> > **dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/constants/Constants.java:75**
> > 
> > * [nitpick] The Javadoc for this constant is minimal. Consider expanding it to explain that this property defines the wait timeout in seconds before using SIGKILL.
> > 
> > ```
> >     public static final String SHELL_KILL_WAIT_TIMEOUT = "shell.kill.wait.timeout";
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/utils/ProcessUtils.java:54**
> > 
> > * It looks like `List` and `ArrayList` are used later in this class but not imported here. Please add `import java.util.List;` and `import java.util.ArrayList;` to avoid compile errors.
> > 
> > ```
> > import java.util.stream.Collectors;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/utils/ProcessUtils.java:168**
> > 
> > * [nitpick] Mutating the original `pidList` inside this method can lead to side effects if the list is reused elsewhere. Consider making a defensive copy of the list before polling/removal.
> > 
> > ```
> >     private static boolean sendKillSignal(String signal, List<Integer> pidList, String tenantCode) {
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/utils/ProcessUtils.java:188**
> > 
> > * [nitpick] The multiplication here assumes `SLEEP_TIME_MILLIS` maps directly to milliseconds. It might be clearer to calculate `timeoutMillis = TimeUnit.SECONDS.toMillis(SHELL_KILL_WAIT_TIMEOUT)` or document the relationship explicitly.
> > 
> > ```
> >             long timeoutMillis = SLEEP_TIME_MILLIS * SHELL_KILL_WAIT_TIMEOUT;
> > ```
> 
> Please take care about the comment from copilot.

Good，I add new function “getAlivePidList“ to avoid side effects

**Review by SbloodyS — DISMISSED** [review]
LGTM

File: dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/test/java/org/apache/dolphinscheduler/plugin/task/api/utils/ProcessUtilsTest.java [hunk 15]
```diff
@@ -132,7 +132,7 @@ void testKillProcessSuccessWithSigInt() throws Exception {
         boolean result = ProcessUtils.kill(taskRequest);
 
         // Assert
-        Assertions.assertTrue(result);
+        Assertions.assertFalse(result);
```
Comment (ruanwenjun) [inline dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/test/java/org/apache/dolphinscheduler/plugin/task/api/utils/ProcessUtilsTest.java:216]: Why change the assertion? Please fix the test case.

Comment (njnu-seafish) [reply dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/test/java/org/apache/dolphinscheduler/plugin/task/api/utils/ProcessUtilsTest.java:216]: https://github.com/apache/dolphinscheduler/actions/runs/16282257223/job/45974113068  

I also find it quite strange that this test case sometimes passes and sometimes fails. It seems to be related to the machine environment.

File: dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/utils/ProcessUtils.java [hunk 16]
```diff
@@ -100,29 +114,35 @@ public static boolean kill(@NonNull TaskExecutionContext request) {
...
             String pids = getPidsStr(processId);
-            String[] pidArray = pids.split("\\s+");
+            String[] pidArray = PID_PATTERN.split(pids);
             if (pidArray.length == 0) {
                 log.warn("No valid PIDs found for process: {}", processId);
                 return true;
             }
 
+            // Convert PID string to list of integers
+            List<Integer> pidList = new ArrayList<>();
```
[the remark this answers is not in the document]
Comment (njnu-seafish) [reply dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/utils/ProcessUtils.java]: Good Idea

File: dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/test/java/org/apache/dolphinscheduler/plugin/task/api/utils/ProcessUtilsTest.java (hunk 15 above)
Comment (njnu-seafish) [reply dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/test/java/org/apache/dolphinscheduler/plugin/task/api/utils/ProcessUtilsTest.java:216]: > Why change the assertion? Please fix the test case.

update the test case, it is ok now.

File: deploy/kubernetes/dolphinscheduler/Chart.yaml [hunk 17]
```diff
@@ -35,11 +35,11 @@ type: application
 
 # This is the chart version. This version number should be incremented each time you make changes
 # to the chart and its templates, including the app version.
-version: 3.1.0
+version: 3.1.1
```
Comment (ruanwenjun) [inline deploy/kubernetes/dolphinscheduler/Chart.yaml]: Why change this?

**Review by ruanwenjun — DISMISSED** [review]
LGTM

**Comment by njnu-seafish** [comment]
Unit test results varied across different operating systems (e.g., Linux, macOS, Windows), primarily due to:

 mockedOSUtils.when(() -> OSUtils.exeCmd(Mockito.matches(".*pstree.*12345"))).thenReturn("1234 12345");

Should be updated to：
 
 mockedOSUtils.when(() -> OSUtils.exeCmd(Mockito.matches(".*pstree.*12345"))).thenReturn("sudo(12345)---86.sh(1234)");

**Comment by njnu-seafish** [comment]
> ## [Quality Gate Passed](https://sonarcloud.io/dashboard?id=apache-dolphinscheduler&pullRequest=17320) **Quality Gate passed**
> Issues  [2 New issues](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=17320&issueStatuses=OPEN,CONFIRMED&sinceLeakPeriod=true)  [0 Accepted issues](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=17320&issueStatuses=ACCEPTED)
> 
> Measures  [0 Security Hotspots](https://sonarcloud.io/project/security_hotspots?id=apache-dolphinscheduler&pullRequest=17320&issueStatuses=OPEN,CONFIRMED&sinceLeakPeriod=true)  [91.4% Coverage on New Code](https://sonarcloud.io/component_measures?id=apache-dolphinscheduler&pullRequest=17320&metric=new_coverage&view=list)  [0.0% Duplication on New Code](https://sonarcloud.io/component_measures?id=apache-dolphinscheduler&pullRequest=17320&metric=new_duplicated_lines_density&view=list)
> 
> [See analysis details on SonarQube Cloud](https://sonarcloud.io/dashboard?id=apache-dolphinscheduler&pullRequest=17320)

I will remove the "throws Exception" in the test

**Review by ruanwenjun — APPROVED** [review]
LGTM

**Review by SbloodyS — APPROVED** [review]
