### PR TITLE
[Bug][Api-Server]Fix bug when user without tenant uploads file in resource center

### LINKED ISSUE #10293: [Bug] [Api-Server] Improve exception handling when admin user uploads file in resource center
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

* If user logs in with admin role and does not set tenant, there will be `null pointer exception` when he / she tries to upload files in `resource center`.

image

### What you expected to happen

* We need some exception handling here and provide users with instructive error message: https://github.com/apache/dolphinscheduler/blob/8d26d4fe72aa81437103716b22f52ef6dc515a14/dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ResourcesServiceImpl.java#L653-L656

* We need to remind users that tenant should be set before playing with `resource center` if they log in with `admin` role.

### How to reproduce

* Already described above.

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by EricGao888**
## Purpose of the pull request
* Make error msg more instructive when user logged in as `admin` tries to manage files in `resource center` without setting up `tenant`. In this way, user will no more get a `NullPointerException` here.

* Add a reminder in docs.

* This PR closes: #10293 

## Brief change log
* Already described above.

## Verify this pull request
* Verified by manual test and unit test.

### CODE REVIEW

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ResourcesServiceImpl.java [hunk 1]
```diff
@@ -651,7 +666,14 @@ private boolean upload(User loginUser, String fullName, MultipartFile file, Reso
             return false;
         }
         // query tenant
-        String tenantCode = tenantMapper.queryById(loginUser.getTenantId()).getTenantCode();
+        Tenant tenant = tenantMapper.queryById(loginUser.getTenantId());
+        // this could happen when user logs in as admin
+        if (tenant == null) {
+            logger.error("fail to acquire tenant, please set tenant for login user/admin first");
```
Comment (SbloodyS) [inline dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ResourcesServiceImpl.java]: It's better to put this message to the result's ```msg``` to improve user friendly.

Comment (EricGao888) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ResourcesServiceImpl.java]: Sure, will fix it in next commit.

Comment (EricGao888) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ResourcesServiceImpl.java]: @SbloodyS Just for double-check, I've already put some instructions and users will get it on Web UI once triggered. Where else exactly should I put the message you mentioned above?

image

Comment (SbloodyS) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ResourcesServiceImpl.java]: What i mean is the ```logger.error``` should put to WEB UI.

Comment (EricGao888) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ResourcesServiceImpl.java]: Looks like `CURRENT_LOGIN_USER_TENANT_NOT_EXIST` already has instructive message here. Do you have any suggestions on how to put `logger.error` to WEB UI? We also need to think about i18n issue. 
image

**Comment by EricGao888** [comment]
BTW, what's wrong with the `mergeable` bot? Is there any way to fix it?  :rofl:

image

**Comment by zhongjiajie** [comment]
mergeable will have fun with itself sometime

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ResourcesServiceImpl.java (hunk 1 above)
Comment (zhongjiajie) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ResourcesServiceImpl.java]: Are we still need this? in this patch we already have function `verifyTenant` in and function upload only working on `createResource` and `updateResource`. If we add `verifyTenant` to both of them, do we still need this check in `upload`?

Comment (EricGao888) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ResourcesServiceImpl.java]: > Are we still need this? in this patch we already have function `verifyTenant` in and function upload only working on `createResource` and `updateResource`. If we add `verifyTenant` to both of them, do we still need this check in `upload`?

As long as the `verifyTenant` method added to both `createResource` and `updateResource`,  we no more need checks in `upload` method.

Comment (zhongjiajie) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ResourcesServiceImpl.java]: Yeah, that what I mean, I think we could remove the `Tenant tenant = tenantMapper.queryById(loginUser.getTenantId());` in L669 for this reason

Comment (EricGao888) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ResourcesServiceImpl.java]: @zhongjiajie Looks like we only need to `verifyTenant` in `createResource`. `updateResource` has already done it.
https://github.com/apache/dolphinscheduler/blob/a8a5da367ad37911ee2400df894cdf8ff16fb73e/dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ResourcesServiceImpl.java#L400-L404
https://github.com/apache/dolphinscheduler/blob/a8a5da367ad37911ee2400df894cdf8ff16fb73e/dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ResourcesServiceImpl.java#L1515-L1530

Comment (zhongjiajie) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ResourcesServiceImpl.java]: It is a little odd here, since we already have some check func `getTenantCode`, is there a reason we should add new new on named `verifyTenant` to do that?

Comment (EricGao888) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ResourcesServiceImpl.java]: > It is a little odd here, since we already have some check func `getTenantCode`, is there a reason we should add new new on named `verifyTenant` to do that?

Honestly, I just found there is such a `getTenantCode` check. :rofl: What about remove the new `verifyTenant` and add `getTenantCode` in `createResource` to keep consistency? BTW we can keep the unit test to add some coverage.

Comment (zhongjiajie) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ResourcesServiceImpl.java]: I think is OK, and is good for the
> we can keep the unit test to add some coverage.

**Comment by EricGao888** [comment]
> Kudos, SonarCloud Quality Gate passed!    [Quality Gate passed](https://sonarcloud.io/dashboard?id=apache-dolphinscheduler&pullRequest=10303)
> 
> [Bug](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=10303&resolved=false&types=BUG) [A](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=10303&resolved=false&types=BUG) [0 Bugs](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=10303&resolved=false&types=BUG) [Vulnerability](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=10303&resolved=false&types=VULNERABILITY) [A](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=10303&resolved=false&types=VULNERABILITY) [0 Vulnerabilities](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=10303&resolved=false&types=VULNERABILITY) [Security Hotspot](https://sonarcloud.io/project/security_hotspots?id=apache-dolphinscheduler&pullRequest=10303&resolved=false&types=SECURITY_HOTSPOT) [A](https://sonarcloud.io/project/security_hotspots?id=apache-dolphinscheduler&pullRequest=10303&resolved=false&types=SECURITY_HOTSPOT) [0 Security Hotspots](https://sonarcloud.io/project/security_hotspots?id=apache-dolphinscheduler&pullRequest=10303&resolved=false&types=SECURITY_HOTSPOT) [Code Smell](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=10303&resolved=false&types=CODE_SMELL) [A](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=10303&resolved=false&types=CODE_SMELL) [0 Code Smells](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=10303&resolved=false&types=CODE_SMELL)
> 
> [](https://sonarcloud.io/component_measures?id=apache-dolphinscheduler&pullRequest=10303&metric=new_coverage&view=list) [100.0% Coverage](https://sonarcloud.io/component_measures?id=apache-dolphinscheduler&pullRequest=10303&metric=new_coverage&view=list) [](https://sonarcloud.io/component_measures?id=apache-dolphinscheduler&pullRequest=10303&metric=new_duplicated_lines_density&view=list) [0.0% Duplication](https://sonarcloud.io/component_measures?id=apache-dolphinscheduler&pullRequest=10303&metric=new_duplicated_lines_density&view=list)

Got `100% Coverage` for the first time. LOL

**Comment by EricGao888** [comment]
@zhongjiajie @SbloodyS PTAL, Thx~

**Review by SbloodyS — APPROVED** [review]
LGTM

**Review by zhuangchong — APPROVED** [review]

**Comment by EricGao888** [comment]
@SbloodyS BTW, it seems that this case has not been covered in E2E tests. I'm not sure whether there are similar issues (lack of tenant check for admin user) in other scenario.

**Comment by SbloodyS** [comment]
> @SbloodyS BTW, it seems that this case has not been covered in E2E tests. I'm not sure whether there are similar issues (lack of tenant check for admin user) in other scenario.

Currently our E2E test's coverage is very low. Welcome to contribute if you like.

**Comment by EricGao888** [comment]
> > @SbloodyS BTW, it seems that this case has not been covered in E2E tests. I'm not sure whether there are similar issues (lack of tenant check for admin user) in other scenario.
> 
> Currently our E2E test's coverage is very low. Welcome to contribute if you like.

Sure, thx 😊

**Comment by devosend** [comment]
Hi guy, will this pr release in 3.0.0-beta-2? If yes, you can cherry-pick this pr to 3.0.0-beta-2-prepare. @EricGao888

**Comment by EricGao888** [comment]
> Hi guy, will this pr release in 3.0.0-beta-2? If yes, you can cherry-pick this pr to 3.0.0-beta-2-prepare. @EricGao888

I think so, since it is a bug fix. Will cherry pick it later today if no one objects.

**Comment by zhongjiajie** [comment]
> Hi guy, will this pr release in 3.0.0-beta-2? If yes, you can cherry-pick this pr to 3.0.0-beta-2-prepare. @EricGao888

should be cherry-picked to 3.0.0b2, and for @EricGao888 , version 300b2 release manager is @devosend and he will cherry-pick directly locally and push to upstream himself

**Comment by EricGao888** [comment]
> > Hi guy, will this pr release in 3.0.0-beta-2? If yes, you can cherry-pick this pr to 3.0.0-beta-2-prepare. @EricGao888
> 
> should be cherry-picked to 3.0.0b2, and for @EricGao888 , version 300b2 release manager is @devosend and he will cherry-pick directly locally and push to upstream himself

@zhongjiajie Sure, that will be perfect. I had some very bad nightmares about using `cherry-pick` during my time at Amazon.

**Comment by EricGao888** [comment]
> > > Hi guy, will this pr release in 3.0.0-beta-2? If yes, you can cherry-pick this pr to 3.0.0-beta-2-prepare. @EricGao888
> > 
> > 
> > should be cherry-picked to 3.0.0b2, and for @EricGao888 , version 300b2 release manager is @devosend and he will cherry-pick directly locally and push to upstream himself
> 
> @zhongjiajie Sure, that will be perfect. I had some very bad nightmares about using `cherry-pick` during my time at Amazon.

@zhongjiajie @SbloodyS That was a pretty sad story. If you'd like to share a beer with me, I could tell u what happened. 🤣

**Comment by SbloodyS** [comment]
> @zhongjiajie @SbloodyS That was a pretty sad story. If you'd like to share a beer with me, I could tell u what happened. 🤣

I don't drink alcohol. But I drink tea. I can buy you tea if you come to Guangzhou. ^_^

**Comment by devosend** [comment]
> > Hi guy, will this pr release in 3.0.0-beta-2? If yes, you can cherry-pick this pr to 3.0.0-beta-2-prepare. @EricGao888
> 
> should be cherry-picked to 3.0.0b2, and for @EricGao888 , version 300b2 release manager is @devosend and he will cherry-pick directly locally and push to upstream himself

I tried to cherry-pick, but it depend on un-cherry-pick pr #10307 🤣. Need your help @EricGao888

**Comment by EricGao888** [comment]
> > > Hi guy, will this pr release in 3.0.0-beta-2? If yes, you can cherry-pick this pr to 3.0.0-beta-2-prepare. @EricGao888
> > 
> > 
> > should be cherry-picked to 3.0.0b2, and for @EricGao888 , version 300b2 release manager is @devosend and he will cherry-pick directly locally and push to upstream himself
> 
> I tried to cherry-pick, but it depend on un-cherry-pick pr #10307 🤣. Need your help @EricGao888

@devosend May I ask why we haven't picked pr #10307?  This PR has been rebased on #10307. It will be kind of wired if we re-rebase this PR on code before #10307. In that case, maybe we could leave this PR to the next version for release. WDYT @zhongjiajie

**Comment by devosend** [comment]
> > > > Hi guy, will this pr release in 3.0.0-beta-2? If yes, you can cherry-pick this pr to 3.0.0-beta-2-prepare. @EricGao888
> > > 
> > > 
> > > should be cherry-picked to 3.0.0b2, and for @EricGao888 , version 300b2 release manager is @devosend and he will cherry-pick directly locally and push to upstream himself
> > 
> > 
> > I tried to cherry-pick, but it depend on un-cherry-pick pr #10307 🤣. Need your help @EricGao888
> 
> @devosend May I ask why we haven't picked pr #10307? This PR has been rebased on #10307. It will be kind of wired if we re-rebase this PR on code before #10307. In that case, maybe we could leave this PR to the next version for release. WDYT @zhongjiajie

The pr #10307 may be released at 3.1.0-alpha. So this pr can also be released in version 3.1.0-alpha.

**Comment by EricGao888** [comment]
Just curious about the release version naming. May I ask 3.1.0-alpha is ahead of 3.0.0 stable or after? @devosend

**Comment by devosend** [comment]
> May I ask 3.1.0-alpha is ahead of 3.

I don't know. Jiajie might know better. @zhongjiajie

**Comment by zhongjiajie** [comment]
> Just curious about the release version naming. May I ask 3.1.0-alpha is ahead of 3.0.0 stable or after? @devosend

@EricGao888  we do not have the offical release policy and there are two main reason. Our tests coverage is low, and we could not release base on dev branch. And in this case we think https://semver.org/ will be better, but i will take the release manager so many time.
we still trying to find which is better, so we do not pulish the release policy to our website. And you can see in https://semver.org/#spec-item-11  x.y.z-alpha is early than x.y.z
