### PR TITLE
[Fix-17436][Workflow]Task timeout kill throw exception

### LINKED ISSUE #17436: [Bug] [Workflow] Task timeout kill throw exception(The cancelApplication method was called twice for the shellCommandExecutor task)
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### 1. Create a shell task and configure the timeout failure strategy

Image

### 2. Manually kill the task, and the logs show kill success operation. (**Only call the cancelApplication method once.**)

2025-08-15 13:49:33.105 INFO  [WorkerRpcServer-methodInvoker-224] - Publish TaskExecutorKillLifecycleEvent: {
  "taskInstanceId" : 1081,
  "eventCreateTime" : 1755236973105,
  "type" : "KILL"
}
2025-08-15 13:49:33.147 INFO  [PhysicalTaskExecutorEventBusCoordinator-eventbus-coordinator-worker-87] - Begin killing task instance, processId: 749659
2025-08-15 13:49:33.449 INFO  [PhysicalTaskExecutorEventBusCoordinator-eventbus-coordinator-worker-87] - prepare to parse pid, raw pid string: sudo(749659)---1081.sh(749674)---sleep(749748)

2025-08-15 13:49:34.003 INFO  [PhysicalTaskExecutorEventBusCoordinator-eventbus-coordinator-worker-87] - Sending SIGINT to process group: 749659 749674 749748, command: sudo -u dolphinscheduler -i kill -s SIGINT 749659 749674 749748
2025-08-15 13:49:44.992 INFO  [PhysicalTaskExecutorEventBusCoordinator-eventbus-coordinator-worker-87] - Kill command: sudo -u dolphinscheduler -i kill -s SIGINT 749659 749674 749748, timed out, still running PIDs: 749659 749674 749748
2025-08-15 13:49:45.545 INFO  [PhysicalTaskExecutorEventBusCoordinator-eventbus-coordinator-worker-87] - Sending SIGTERM to process group: 749659 749674 749748, command: sudo -u dolphinscheduler -i kill -s SIGTERM 749659 749674 749748
2025-08-15 13:49:46.253 INFO  [PhysicalTaskExecutorEventBusCoordinator-eventbus-coordinator-worker-87] - Successfully killed process tree using SIGTERM, processId: 749659
2025-08-15 13:49:46.254 INFO  [PhysicalTaskExecutorEventBusCoordinator-eventbus-coordinator-worker-87] - Process tree for task: 1081 is killed or already finished, pid: 749659
2025-08-15 13:49:46.254 INFO  [PhysicalTaskExecutorEventBusCoordinator-eventbus-coordinator-worker-87] - Get appIds from worker 192.168.30.121:1234, taskLogPath: /data01/dolphinscheduler/20250815/149143631011392/1/1015/1081.log
2025-08-15 13:49:46.254 INFO  [PhysicalTaskExecutorEventBusCoordinator-eventbus-coordinator-worker-87] - Start finding appId in /data01/dolphinscheduler/20250815/149143631011392/1/1015/1081.log, fetch way: log 
2025-08-15 13:49:46.254 INFO  [PhysicalTaskExecutorEventBusCoordinator-eventbus-coordinator-worker-87] - The appId is empty
2025-08-15 13:49:46.254 INFO  [PhysicalTaskExecutorEventBusCoordinator-eventbus-coordinator-worker-87] - Success fire TaskExecutorKillLifecycleEvent: {
  "taskInstanceId" : 1081,
  "eventCreateTime" : 1755236973105,
  "type" : "KILL"
} 
2025-08-15 13:49:46.360 INFO  [exclusive-task-executor-container-worker-0] - process has exited. execute path:/data01/dolphinscheduler/exec/process/1081, processId:749659 ,exitStatusCode:143 ,processWaitForStatus:true ,processExitValue:143

### 3, However, an exception was thrown when killing due to timeout. (**The cancelApplication method was called twice.**)

2025-08-15 16:55:37.289 INFO  [WorkerRpcServer-methodInvoker-31] - Publish TaskExecutorKillLifecycleEvent: {
  "taskInstanceId" : 1084,
  "eventCreateTime" : 1755248137289,
  "type" : "KILL"
}
2025-08-15 16:55:37.333 INFO  [PhysicalTaskExecutorEventBusCoordinator-eventbus-coordinator-worker-0] - Begin killing task instance, processId: 837363
2025-08-15 16:55:37.730 INFO  [PhysicalTaskExecutorEventBusCoordinator-eventbus-coordinator-worker-0] - prepare to parse pid, raw pid string: sudo(837363)---1084.sh(837379)---sleep(837453)

2025-08-15 16:55:38.316 INFO  [PhysicalTaskExecutorEventBusCoordinator-eventbus-coordinator-worker-0] - Sending SIGINT to process group: 837363 837379 837453, command: sudo -u dolphinscheduler -i kill -s SIGINT 837363 837379 837453
2025-08-15 16:55:49.325 INFO  [PhysicalTaskExecutorEventBusCoordinator-eventbus-coordinator-worker-0] - Kill command: sudo -u dolphinscheduler -i kill -s SIGINT 837363 837379 837453, timed out, still running PIDs: 837363 837379 837453
2025-08-15 16:55:49.876 INFO  [PhysicalTaskExecutorEventBusCoordinator-eventbus-coordinator-worker-0] - Sending SIGTERM to process group: 837363 837379 837453, command: sudo -u dolphinscheduler -i kill -s SIGTERM 837363 837379 837453
2025-08-15 16:55:50.166 ERROR [exclusive-task-executor-container-worker-0] - process has failure, the task timeout configuration value is:60, ready to kill ...
2025-08-15 16:55:50.167 INFO  [exclusive-task-executor-container-worker-0] - Begin killing task instance, processId: 837363
2025-08-15 16:55:50.566 INFO  [exclusive-task-executor-container-worker-0] - prepare to parse pid, raw pid string: 
2025-08-15 16:55:50.567 ERROR [exclusive-task-executor-container-worker-0] - Kill task instance error, processId: 837363
java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:592)
	at java.lang.Integer.parseInt(Integer.java:615)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at org.apache.dolphinscheduler.plugin.task.api.utils.ProcessUtils.kill(ProcessUtils.java:124)
	at org.apache.dolphinscheduler.plugin.task.api.AbstractCommandExecutor.cancelApplication(AbstractCommandExecutor.java:216)
	at org.apache.dolphinscheduler.plugin.task.api.AbstractCommandExecutor.run(AbstractCommandExecutor.java:196)
	at org.apache.dolphinscheduler.plugin.task.shell.ShellTask.handle(ShellTask.java:85)
	at org.apache.dolphinscheduler.server.worker.executor.PhysicalTaskExecutor.doTriggerTaskPlugin(PhysicalTaskExecutor.java:74)
	at org.apache.dolphinscheduler.task.executor.AbstractTaskExecutor.start(AbstractTaskExecutor.java:80)
	at org.apache.dolphinscheduler.task.executor.worker.TaskExecutorWorker.start(TaskExecutorWorker.java:65)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
2025-08-15 16:55:50.567 ERROR [exclusive-task-executor-container-worker-0] - Failed to kill process tree for task: 1084, pid: 837363
2025-08-15 16:55:50.567 INFO  [exclusive-task-executor-container-worker-0] - Get appIds from worker 192.168.30.121:1234, taskLogPath: /data01/dolphinscheduler/20250815/149143631011392/1/1018/1084.log
2025-08-15 16:55:50.567 INFO  [exclusive-task-executor-container-worker-0] - Start finding appId in /data01/dolphinscheduler/20250815/149143631011392/1/1018/1084.log, fetch way: log 
2025-08-15 16:55:50.567 INFO  [exclusive-task-executor-container-worker-0] - The appId is empty
2025-08-15 16:55:50.568 INFO  [exclusive-task-executor-container-worker-0] - process has exited. execute path:/data01/dolphinscheduler/exec/process/1084, processId:837363 ,exitStatusCode:-1 ,processWaitForStatus:false ,processExitValue:143
2025-08-15 16:55:50.568 INFO  [exclusive-task-executor-container-worker-0] - Publish TaskExecutorFailedLifecycleEvent: {
  "taskInstanceId" : 1084,
  "eventCreateTime" : 1755248150568,
  "type" : "FAILED",
  "workflowInstanceId" : 1018,
  "workflowInstanceHost" : "192.168.30.11:5678",
  "taskInstanceHost" : "192.168.30.121:1234",
  "appIds" : "",
  "endTime" : 1755248150568,
  "latestReportTime" : null
}

### What you expected to happen

1, Task timeout kill don't throw exception
2, It's best to trigger the kill action only once.

### How to reproduce

1. Create a shell task and configure the timeout failure strategy

Image

2. Run the workflow, wait to kill the task after timeout 

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by njnu-seafish**
## Purpose of the pull request

close #17436

## Brief change log
1. add string blank check
2. remove redundant cancelApplication call

## Verify this pull request

After fixing the bug, timeout kill logs:

2025-08-21 09:30:25.259 INFO  [WorkerRpcServer-methodInvoker-155] - Publish TaskExecutorKillLifecycleEvent: {
  "taskInstanceId" : 1341,
  "eventCreateTime" : 1755739825259,
  "type" : "KILL"
}
2025-08-21 09:30:25.302 INFO  [PhysicalTaskExecutorEventBusCoordinator-eventbus-coordinator-worker-22] - Begin killing task instance, processId: 1115493
2025-08-21 09:30:25.826 INFO  [PhysicalTaskExecutorEventBusCoordinator-eventbus-coordinator-worker-22] - prepare to parse pid, raw pid string: sudo(1115493)---1341.sh(1115497)---sleep(1115570)

2025-08-21 09:30:26.370 INFO  [PhysicalTaskExecutorEventBusCoordinator-eventbus-coordinator-worker-22] - Sending SIGINT to process group: 1115493 1115497 1115570, command: sudo -u dolphinscheduler -i kill -s SIGINT 1115493 1115497 1115570
2025-08-21 09:30:37.408 INFO  [PhysicalTaskExecutorEventBusCoordinator-eventbus-coordinator-worker-22] - Kill command: sudo -u dolphinscheduler -i kill -s SIGINT 1115493 1115497 1115570, timed out, still running PIDs: 1115493 1115497 1115570
2025-08-21 09:30:37.961 INFO  [PhysicalTaskExecutorEventBusCoordinator-eventbus-coordinator-worker-22] - Sending SIGTERM to process group: 1115493 1115497 1115570, command: sudo -u dolphinscheduler -i kill -s SIGTERM 1115493 1115497 1115570
2025-08-21 09:30:38.156 ERROR [exclusive-task-executor-container-worker-1] - process has failure due to timeout kill, the timeout value is:60, the taskTimeoutStrategy is:FAILED
2025-08-21 09:30:38.157 INFO  [exclusive-task-executor-container-worker-1] - process has killed. execute path:/data01/dolphinscheduler/exec/process/1341, processId:1115493 ,exitStatusCode:-1 ,processWaitForStatus:false ,processExitValue:143
2025-08-21 09:30:38.157 INFO  [exclusive-task-executor-container-worker-1] - Publish TaskExecutorFailedLifecycleEvent: {
  "taskInstanceId" : 1341,
  "eventCreateTime" : 1755739838157,
  "type" : "FAILED",
  "workflowInstanceId" : 1273,
  "workflowInstanceHost" : "192.168.30.11:5678",
  "taskInstanceHost" : "192.168.30.121:1234",
  "appIds" : null,
  "endTime" : 1755739838157,
  "latestReportTime" : null
}
2025-08-21 09:30:38.157 INFO  [exclusive-task-executor-container-worker-1] - Publish TaskExecutorFinalizeLifecycleEvent: {
  "taskInstanceId" : 1341,
  "eventCreateTime" : 1755739838157,
  "type" : "FINALIZE"
}
2025-08-21 09:30:38.676 INFO  [PhysicalTaskExecutorEventBusCoordinator-eventbus-coordinator-worker-22] - Successfully killed process tree using SIGTERM, processId: 1115493
2025-08-21 09:30:38.676 INFO  [PhysicalTaskExecutorEventBusCoordinator-eventbus-coordinator-worker-22] - Process tree for task: 1341 is killed or already finished, pid: 1115493
2025-08-21 09:30:38.677 INFO  [PhysicalTaskExecutorEventBusCoordinator-eventbus-coordinator-worker-22] - Get appIds from worker 192.168.30.121:1234, taskLogPath: /data01/dolphinscheduler/20250821/149143631011392/7/1273/1341.log
2025-08-21 09:30:38.677 INFO  [PhysicalTaskExecutorEventBusCoordinator-eventbus-coordinator-worker-22] - Start finding appId in /data01/dolphinscheduler/20250821/149143631011392/7/1273/1341.log, fetch way: log 
2025-08-21 09:30:38.677 INFO  [PhysicalTaskExecutorEventBusCoordinator-eventbus-coordinator-worker-22] - The appId is empty
2025-08-21 09:30:38.677 INFO  [PhysicalTaskExecutorEventBusCoordinator-eventbus-coordinator-worker-22] - Success fire TaskExecutorKillLifecycleEvent: {
  "taskInstanceId" : 1341,
  "eventCreateTime" : 1755739825259,
  "type" : "KILL"
} 
2025-08-21 09:30:38.718 INFO  [PhysicalTaskExecutorEventBusCoordinator-eventbus-coordinator-worker-20] - Success fire TaskExecutorFailedLifecycleEvent: {
  "taskInstanceId" : 1341,
  "eventCreateTime" : 1755739838157,
  "type" : "FAILED",
  "workflowInstanceId" : 1273,
  "workflowInstanceHost" : "192.168.30.11:5678",
  "taskInstanceHost" : "192.168.30.121:1234",
  "appIds" : null,
  "endTime" : 1755739838157,
  "latestReportTime" : null
} 
2025-08-21 09:30:38.768 INFO  [PhysicalTaskExecutorEventBusCoordinator-eventbus-coordinator-worker-21] - 
************************************************************************************************
*********************************  Finalize task instance  ************************************
***********************************************************************************************
2025-08-21 09:30:38.768 INFO  [PhysicalTaskExecutorEventBusCoordinator-eventbus-coordinator-worker-21] - FINALIZE_SESSION
2025-08-21 09:30:38.768 INFO  [PhysicalTaskExecutorEventBusCoordinator-eventbus-coordinator-worker-21] - Success fire TaskExecutorFinalizeLifecycleEvent: {
  "taskInstanceId" : 1341,
  "eventCreateTime" : 1755739838157,
  "type" : "FINALIZE"
} 

## Pull Request Notice
[Pull Request Notice](https://github.com/apache/dolphinscheduler/blob/dev/docs/docs/en/contribute/join/pull-request.md)

If your pull request contains incompatible change, you should also add it to `docs/docs/en/guide/upgrade/incompatible.md`

### CODE REVIEW

File: dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/utils/ProcessUtils.java [hunk 1]
```diff
@@ -115,13 +115,14 @@
...
             String[] pidArray = PID_PATTERN.split(pids);
-            if (pidArray.length == 0) {
+            if (StringUtils.isBlank(pids) || pidArray.length == 0) {
                 log.warn("No valid PIDs found for process: {}", processId);
                 return true;
             }
 
             // Convert PID string to list of integers
-            List<Integer> pidList = Arrays.stream(pidArray).map(Integer::parseInt).collect(Collectors.toList());
+            List<Integer> pidList = Arrays.stream(pidArray).filter(StringUtils::isNotBlank).map(Integer::parseInt)
```
[the remark this answers is not in the document]
Comment (njnu-seafish) [reply dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/utils/ProcessUtils.java]: List<Integer> pidList = Arrays.stream(pidArray).filter(StringUtils::isNotBlank)
                    .map(s -> {
                        try {
                            return Integer.parseInt(s.trim());
                        } catch (NumberFormatException e) {
                            log.warn("Invalid PID string ignored: {}", s);
                            return null;
                        }
                    })
                    .filter(Objects::nonNull)
                    .collect(Collectors.toList());

File: dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/AbstractCommandExecutor.java [hunk 2]
```diff
@@ -190,13 +191,13 @@ public TaskResponse run(IShellInterceptorBuilder iShellInterceptorBuilder,
...
-                    taskRequest.getTaskTimeout());
+            log.error("process has failure due to timeout kill, timeout value is:{}, timeoutStrategy is:{}",
+                    taskRequest.getTaskTimeout(), taskRequest.getTaskTimeoutStrategy());
             result.setExitStatusCode(EXIT_CODE_FAILURE);
-            cancelApplication();
         }
         int exitCode = this.process.exitValue();
-        String exitLogMessage = EXIT_CODE_KILL == exitCode ? "process has killed." : "process has exited.";
+        String exitLogMessage = (EXIT_CODE_KILL == exitCode || EXIT_CODE_HARD_KILL == exitCode) ? "process has killed."
+                : "process has exited.";
```
Comment (ruanwenjun) [inline dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/AbstractCommandExecutor.java:200]: It's better to check from status in `taskExecutionContext` rather then check from the exit code, we don't care about the exit, only kill from ds then we think it's kill.

File: dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/utils/ProcessUtils.java [hunk 3]
```diff
@@ -115,13 +115,23 @@ public static boolean kill(@NonNull TaskExecutionContext request) {
             // Get all child processes
             String pids = getPidsStr(processId);
             String[] pidArray = PID_PATTERN.split(pids);
-            if (pidArray.length == 0) {
+            if (StringUtils.isBlank(pids) || pidArray.length == 0) {
```
Comment (ruanwenjun) [inline dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/utils/ProcessUtils.java]: if`StringUtils.isEmpty(pids)` then we don't need to execute line 117.

File: dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/utils/ProcessUtils.java [hunk 4]
```diff
@@ -115,13 +115,23 @@ public static boolean kill(@NonNull TaskExecutionContext request) {
...
+                    .map(s -> {
+                        try {
+                            return Integer.parseInt(s.trim());
+                        } catch (NumberFormatException e) {
+                            log.warn("Invalid PID string ignored: {}", s);
+                            return null;
+                        }
+                    })
+                    .filter(Objects::nonNull)
+                    .collect(Collectors.toList());
```
Comment (ruanwenjun) [inline dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/utils/ProcessUtils.java]: It's better to change `getPidsStr` return a validate pid list, rather than parse the pid in up layer.

File: dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/utils/ProcessUtils.java [hunk 5]
```diff
@@ -115,13 +115,23 @@ public static boolean kill(@NonNull TaskExecutionContext request) {
...
 
             // Convert PID string to list of integers
-            List<Integer> pidList = Arrays.stream(pidArray).map(Integer::parseInt).collect(Collectors.toList());
+            List<Integer> pidList = Arrays.stream(pidArray).filter(StringUtils::isNotBlank)
+                    .map(s -> {
+                        try {
+                            return Integer.parseInt(s.trim());
+                        } catch (NumberFormatException e) {
+                            log.warn("Invalid PID string ignored: {}", s);
+                            return null;
```
Comment (ruanwenjun) [inline dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/utils/ProcessUtils.java]: Throw exception here, catch the exception will hide the bug.

File: dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/AbstractCommandExecutor.java (hunk 2 above)
Comment (njnu-seafish) [reply dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/AbstractCommandExecutor.java:200]: > It's better to check from status in `taskExecutionContext` rather then check from the exit code, we don't care about the exit, only kill from ds then we think it's kill.

Here it simply outputs the final execution status of the process, indicating whether it exited normally or was killed.

Comment (ruanwenjun) [reply dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/AbstractCommandExecutor.java:200]: OK

**Review by ruanwenjun — APPROVED** [review]
Pretty good.

**Comment by njnu-seafish** [comment]
@SbloodyS Could u plz help review when available?  Thanks.

**Review by SbloodyS — APPROVED** [review]
+1
