### PR TITLE
[Fix-17004] Fix process termination logic in cancelApplication method

### LINKED ISSUE #17004: [Bug] [dolphinscheduler-task-plugin]  Fix process termination logic in  AbstractCommandExecutor.cancelApplication
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

```
    public void cancelApplication() throws InterruptedException {
        if (process == null) {
            return;
        }

        // soft kill
        log.info("Begin to kill process process, pid is : {}", taskRequest.getProcessId());
        process.destroy();
        if (!process.waitFor(5, TimeUnit.SECONDS)) {
            process.destroyForcibly();
        }
        log.info("Success kill task: {}, pid: {}", taskRequest.getTaskAppId(), taskRequest.getProcessId());
    }
```
The methods AbstractCommandExecutor.cancelApplication need to be reviewed and potentially fixed to ensure they handle process tree termination correctly. The current implementation didn't cover all cases and could lead to child processes not being terminated as expected.

This method can only ensure kill process itself.

### What you expected to happen

Successfully killed all processes by this task

### How to reproduce

You can create a seatunnel task like this (please choose seatunnel cluster mode)

Image

then stop it through button

Image

You will find some child processes(63236 63239) are left when this task is terminated
 
Image

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by davidzollo**
- update the ProcessUtils.kill method to ensure it correctly handles process tree termination and direct process destruction.
- update the AbstractCommandExecutor.cancelApplication method to ensure it correctly handles process termination, including logging and error handling.

close https://github.com/apache/dolphinscheduler/issues/17004

### CODE REVIEW

File: dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/AbstractCommandExecutor.java [hunk 1]
```diff
@@ -216,13 +216,30 @@ public void cancelApplication() throws InterruptedException {
...
+                log.info("Process did not exit after destroy, forcing termination");
+                process.destroyForcibly();
+            }
+            log.info("Successfully killed process tree for task: {}, pid: {}",
+                    taskRequest.getTaskAppId(), taskRequest.getProcessId());
+
+        } catch (Exception e) {
+            log.error("Error while killing process, pid: {}", taskRequest.getProcessId(), e);
+            // Try destroyForcibly as last resort
             process.destroyForcibly();
```
Comment (ruanwenjun) [inline dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/AbstractCommandExecutor.java]: This is not needed.

File: dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/utils/ProcessUtils.java [hunk 2]
```diff
@@ -85,31 +85,105 @@ private ProcessUtils() {
...
      */
-    @Deprecated
     public static boolean kill(@NonNull TaskExecutionContext request) {
         try {
-            log.info("Begin kill task instance, processId: {}", request.getProcessId());
+            log.info("Begin killing task instance, processId: {}", request.getProcessId());
             int processId = request.getProcessId();
             if (processId == 0) {
-                log.error("Task instance kill failed, processId is not exist");
+                log.error("Task instance kill failed, processId is not available");
```
Comment (ruanwenjun) [inline dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/utils/ProcessUtils.java]: We should return true here, the logic is equals with `pidArray` is empty.

File: dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/utils/ProcessUtils.java [hunk 3]
```diff
@@ -85,31 +85,105 @@ private ProcessUtils() {
...
+            // Get all child processes
+            String pids = getPidsStr(processId);
+            String[] pidArray = pids.split("\\s+");
+            if (pidArray.length == 0) {
+                log.warn("No valid PIDs found for process: {}", processId);
+                return true;
+            }
+
+            // 1. Try to terminate gracefully (SIGINT)
+            boolean gracefulKillSuccess = sendKillSignal("SIGINT", pids, request.getTenantCode(), 2000);
```
Comment (ruanwenjun) [inline dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/utils/ProcessUtils.java]: Don't add wait time, this will make RPC failed.

File: dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/utils/ProcessUtils.java [hunk 4]
```diff
@@ -85,31 +85,105 @@ private ProcessUtils() {
...
-            log.info("Success kill task instance, processId: {}", request.getProcessId());
+            // 4. Finally, check if the process is still alive
+            for (String pid : pidArray) {
+                if (isProcessAlive(pid)) {
+                    log.error("Failed to kill process {}, even after multiple attempts", pid);
+                    return false;
+                }
+            }
+
+            log.info("Success: process {} is no longer running", processId);
```
Comment (ruanwenjun) [inline dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/utils/ProcessUtils.java]: Is this needed to do a check here, if the process has set graceful exist, this check will false, but this doesn't mean we kill failed.

**Review by ruanwenjun — COMMENTED** [review]
Is this PR generating by AI? This could potentially lead to high code duplicate with other project.

**Comment by davidzollo** [comment]
> Is this PR generating by AI? This could potentially lead to high code duplicate with other project.

At first, I use cursor generate PR code, but there're many errors it generated, so I have to update a lot to solve this issue.

File: dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/utils/ProcessUtils.java (hunk 4 above)
Comment (davidzollo) [reply dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/utils/ProcessUtils.java]: You're right, it's no need to check here.

File: dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/utils/ProcessUtils.java (hunk 3 above)
Comment (davidzollo) [reply dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/utils/ProcessUtils.java]: I have removed this wait time

File: dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/AbstractCommandExecutor.java (hunk 1 above)
Comment (davidzollo) [reply dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/AbstractCommandExecutor.java]: yes, good suggesion.

**Comment by davidzollo** [comment]
@ruanwenjun Thanks for the review, I have updated the PR, please help review it when you're free, thx

**Comment by ruanwenjun** [comment]
> @ruanwenjun Thanks for the review, I have updated the PR, please help review it when you're free, thx

It's better to remove the extra code in https://github.com/apache/dolphinscheduler/pull/17005#discussion_r1957241984

File: dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/AbstractCommandExecutor.java (hunk 1 above)
Comment (davidzollo) [reply dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/AbstractCommandExecutor.java]: I have been removed these logic,thx

**Comment by davidzollo** [comment]
> > @ruanwenjun Thanks for the review, I have updated the PR, please help review it when you're free, thx
> 
> It's better to remove the extra code in [#17005 (comment)](https://github.com/apache/dolphinscheduler/pull/17005#discussion_r1957241984)

Thanks for the suggestion, I have removed this logic, please help review it when you're free, thx

**Review by ruanwenjun — APPROVED** [review]
LGTM

**Review by SbloodyS — APPROVED** [review]
+1
