### PR TITLE
[BUG-11181] [Document] text check 

### LINKED ISSUE #11181: [BUG] [Document] text check
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

image
缺一个点字。应该为子流程节点

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by fuchanghai**
## Purpose of the pull request
Modify the document to make it easier to read

## Brief change log

modify zh/design.md and class of ExecutorServiceImpl
## Verify this pull request

This pull request is code cleanup without any test coverage.

this close #11181

### CODE REVIEW

**Comment by SbloodyS** [comment]
to target specific issue from PR, we recommend use keyword fix: #issue_id or close: #issue_id or closes: #issue_id in your PR describe(not title, just desc). It would not only connect issue to PR but also close issue automatically when PR is be closed. @fuchanghai

**Review by SbloodyS — DISMISSED** [review]
LGTM

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ExecutorServiceImpl.java [hunk 1]
```diff
@@ -294,7 +294,7 @@ public Map<String, Object> checkProcessDefinitionValid(long projectCode, Process
     }
 
     /**
-     * check if the current process has subprocesses and all subprocesses are valid
+     * check whether the current process has subprocesses and valid all subprocesses
```
Comment (EricGao888) [inline dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ExecutorServiceImpl.java]:
```suggestion
     * check whether the current process has subprocesses and validate all subprocesses
```

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ExecutorServiceImpl.java [hunk 2]
```diff
@@ -607,7 +607,7 @@ private Map<String, Object> insertCommand(User loginUser, Integer instanceId, lo
     }
 
     /**
-     * check if sub processes are offline before starting process definition
+     * check whether sub processes are offline before starting process definition
```
Comment (EricGao888) [inline dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ExecutorServiceImpl.java:610]: `sub processes` or `subprocesses`? I think either one is ok but just keep it consistent.

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ExecutorServiceImpl.java [hunk 3]
```diff
@@ -724,7 +724,7 @@ private int createCommand(CommandType commandType, long processDefineCode, TaskD
                 return createComplementCommandList(schedule, runMode, command, expectedParallelismNumber,
                     complementDependentMode);
             } catch (CronParseException cronParseException) {
-                // this just make compile happy, since we already validate the cron before
+                // this just make compile happen, since we already validate the cron before
```
Comment (EricGao888) [inline dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ExecutorServiceImpl.java]: Not sure what this comment means here. It makes developers confused. If we do not need this, maybe we could just delete it.

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ExecutorServiceImpl.java [hunk 4]
```diff
@@ -940,7 +940,7 @@ private List<DependentProcessDefinition> checkDependentProcessDefinitionValid(
 
     /**
      * @param schedule
-     * @return check error return 0 otherwish 1
+     * @return check error return 0 otherwise 1
```
Comment (EricGao888) [inline dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ExecutorServiceImpl.java]:
```suggestion
     * @return check error return 0, otherwise 1
```

**Review by EricGao888 — CHANGES_REQUESTED** [review]

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ExecutorServiceImpl.java (hunk 2 above)
Comment (fuchanghai) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ExecutorServiceImpl.java:610]: I think with subprocesses

**Comment by fuchanghai** [comment]
@EricGao888 you are right,3q

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ExecutorServiceImpl.java (hunk 3 above)
Comment (fuchanghai) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ExecutorServiceImpl.java]: I just saw a spelling error here, and I was confused at the time, but I don't know if it should be deleted, and I want to see other reviewers' opinions

**Review by EricGao888 — DISMISSED** [review]
Overall LGTM once CI passes, except `this just make compile happen, since we already validate the cron before`. Maybe we could just delete it. WDYT @SbloodyS

**Comment by SbloodyS** [comment]
> Overall LGTM once CI passes, except `this just make compile happen, since we already validate the cron before`. Maybe we could just delete it. WDYT @SbloodyS

I'm not quite sure about it...

**Comment by EricGao888** [comment]
> > Overall LGTM once CI passes, except `this just make compile happen, since we already validate the cron before`. Maybe we could just delete it. WDYT @SbloodyS
> 
> I'm not quite sure about it...

Could you plz take a look when available? Thanks @zhongjiajie

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ExecutorServiceImpl.java (hunk 3 above)
Comment (zhongjiajie) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ExecutorServiceImpl.java]: I think we can delete it

Comment (zhongjiajie) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ExecutorServiceImpl.java]: Oh, I think it add this comment for specific case, The init idea is when even `CronParseException ` throw from function `createComplementCommandList ` or not, we should think it pass.

So maybe this sentence mean, `we add this catch to pass compiler pass, because we throw exception in function CronParseException`.

In this case I think we should remove the error log in L728 but keep this comment, WDYT @EricGao888

Comment (EricGao888) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ExecutorServiceImpl.java]: I got it. Thx @zhongjiajie  for the explanation. We could remove the error logging and update the comment as `We catch the exception here just to make compiler happy, since we have already validated the schedule cron expression before` for better comprehension. @fuchanghai

Comment (fuchanghai) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ExecutorServiceImpl.java]: Are you sure you don't replace happy with happen @EricGao888

> I got it. Thx @zhongjiajie for the explanation. We could remove the error logging and update the comment as `We catch the exception here just to make compiler happy, since we have already validated the schedule cron expression before` for better comprehension. @fuchanghai

**Comment by fuchanghai** [comment]
@SbloodyS @EricGao888 @zhongjiajie I have edited as suggested

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ExecutorServiceImpl.java [hunk 5]
```diff
@@ -724,8 +724,7 @@ private int createCommand(CommandType commandType, long processDefineCode, TaskD
                 return createComplementCommandList(schedule, runMode, command, expectedParallelismNumber,
                     complementDependentMode);
             } catch (CronParseException cronParseException) {
-                // this just make compile happy, since we already validate the cron before
-                logger.error("Parse cron error", cronParseException);
+                // We catch the exception here just to make compiler happen, since we have already validated the schedule cron expression before
```
Comment (EricGao888) [inline dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ExecutorServiceImpl.java]:
```suggestion
                // We catch the exception here just to make compiler happy, since we have already validated the schedule cron expression before
```

Comment (EricGao888) [inline dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ExecutorServiceImpl.java]:
```suggestion
                // We catch the exception here just to make compiler happy, since we have already validated the schedule cron expression before
```

**Review by EricGao888 — APPROVED** [review]
LGTM as long as CI passes. Thanks @fuchanghai for the efforts.

**Comment by davidzollo** [comment]
LGTM
