### PR TITLE
[Fix-17189][UI] Dependent task result status icon error

### LINKED ISSUE #17189: [Bug] [UI] Dependent task result status icon error
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When more than 2 dependent nodes are completed, the displayed status icon is abnormal.

### What you expected to happen

running normally.

### How to reproduce

aboved.

### Anything else

_No response_

### Version

3.3.0-alpha

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by SbloodyS**
## Purpose of the pull request

fix #17189

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

## Pull Request Notice
[Pull Request Notice](https://github.com/apache/dolphinscheduler/blob/dev/docs/docs/en/contribute/join/pull-request.md)

If your pull request contains incompatible change, you should also add it to `docs/docs/en/guide/upgrade/incompatible.md`

### CODE REVIEW

File: dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/TaskInstanceDependentDetails.java [hunk 1]
```diff
@@ -17,15 +17,15 @@
...
-import org.apache.dolphinscheduler.dao.model.ITaskInstanceContext;
+import java.util.List;
 
 import lombok.Data;
 import lombok.EqualsAndHashCode;
 
 @EqualsAndHashCode(callSuper = true)
 @Data
-public class TaskInstanceDependentDetails<T extends ITaskInstanceContext> extends TaskInstance {
+public class TaskInstanceDependentDetails<T extends List<AbstractTaskInstanceContext>> extends TaskInstance {
```
Comment (ruanwenjun) [inline dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/TaskInstanceDependentDetails.java]:
```suggestion
public class TaskInstanceDependentDetails<T extends AbstractTaskInstanceContext> extends TaskInstance {
```

File: dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/TaskInstanceDependentDetails.java [hunk 2]
```diff
@@ -17,15 +17,15 @@
...
 
-    private T taskInstanceDependentResult;
+    private T taskInstanceDependentResults;
```
Comment (ruanwenjun) [inline dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/TaskInstanceDependentDetails.java]:
```suggestion
    private List<T> taskInstanceDependentResults;
```

**Review by ruanwenjun — COMMENTED** [review]
Use `List<T>` seems more clear here.

File: dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/TaskInstanceDependentDetails.java (hunk 2 above)
Comment (SbloodyS) [reply dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/TaskInstanceDependentDetails.java]: Fixed.

File: dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/TaskInstanceDependentDetails.java (hunk 1 above)
Comment (SbloodyS) [reply dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/TaskInstanceDependentDetails.java]: Fixed.

**Review by ruanwenjun — DISMISSED** [review]
LGTM

**Review by ruanwenjun — APPROVED** [review]

**Review by zhongjiajie — APPROVED** [review]
