### PR TITLE
[Fix-17758][Master] Mark task as failed if TaskExecutionContext initialization fails

### LINKED ISSUE #17758: [Bug] [Master] If a task fails during initialization, it will neither be dispatched by the Master nor can it be properly killed.
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

1, import a workflow definition.
2, When running the workflow, the task cann‘t be dispatched.  
 some error info from dolphinscheduler-master.log

> [WI-8][TI-0] - 2025-12-01 15:58:06.007 INFO  [ds-workflow-eventbus-worker-14] o.a.d.s.m.e.WorkflowEventBus:[41] - Publish event: TaskDispatchLifecycleEvent{task=sh01}
[WI-8][TI-0] - 2025-12-01 15:58:06.007 INFO  [ds-workflow-eventbus-worker-14] o.a.d.s.m.e.t.l.h.AbstractTaskLifecycleEventHandler:[47] - Fired task sh01 TaskStartLifecycleEvent{task=sh01} with state SUBMITTED_SUCCESS
[WI-8][TI-0] - 2025-12-01 15:58:06.010 ERROR [ds-workflow-eventbus-worker-14] o.a.d.s.m.e.WorkflowEventBusFireWorker:[88] - Fire event failed for WorkflowExecuteRunnable: flow_condition_import_20251201155754777-20251201155805585
org.apache.dolphinscheduler.server.master.engine.exceptions.WorkflowEventFireException: Failed to fire event: TaskDispatchLifecycleEvent{task=sh01}
	at org.apache.dolphinscheduler.server.master.engine.WorkflowEventBusFireWorker.doFireSingleWorkflowEventBus(WorkflowEventBusFireWorker.java:133)
	at org.apache.dolphinscheduler.server.master.engine.WorkflowEventBusFireWorker.fireAllRegisteredEvent(WorkflowEventBusFireWorker.java:86)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.IllegalArgumentException: Cannot find the environment: 144873539254368
	at org.apache.dolphinscheduler.server.master.runner.TaskExecutionContextFactory.getEnvironmentConfigFromDB(TaskExecutionContextFactory.java:217)
	at org.apache.dolphinscheduler.server.master.runner.TaskExecutionContextFactory.createTaskExecutionContext(TaskExecutionContextFactory.java:102)
	at org.apache.dolphinscheduler.server.master.engine.task.runnable.TaskExecutionRunnable.initializeTaskExecutionContext(TaskExecutionRunnable.java:148)
	at org.apache.dolphinscheduler.server.master.engine.task.statemachine.TaskSubmittedStateAction.onDispatchEvent(TaskSubmittedStateAction.java:112)
	at org.apache.dolphinscheduler.server.master.engine.task.lifecycle.handler.TaskDispatchLifecycleEventHandler.handle(TaskDispatchLifecycleEventHandler.java:40)
	at org.apache.dolphinscheduler.server.master.engine.task.lifecycle.handler.TaskDispatchLifecycleEventHandler.handle(TaskDispatchLifecycleEventHandler.java:31)
	at org.apache.dolphinscheduler.server.master.engine.task.lifecycle.handler.AbstractTaskLifecycleEventHandler.handle(AbstractTaskLifecycleEventHandler.java:46)
	at org.apache.dolphinscheduler.server.master.engine.task.lifecycle.handler.AbstractTaskLifecycleEventHandler.handle(AbstractTaskLifecycleEventHandler.java:32)
	at org.apache.dolphinscheduler.server.master.engine.WorkflowEventBusFireWorker.doFireSingleEvent(WorkflowEventBusFireWorker.java:144)
	at org.apache.dolphinscheduler.server.master.engine.WorkflowEventBusFireWorker.doFireSingleWorkflowEventBus(WorkflowEventBusFireWorker.java:122)

3, When manually killing the workflow, it remains stuck in the "waiting to be killed" state.
 some error info from dolphinscheduler-master.log

> [WI-0][TI-0] - 2025-12-01 18:54:51.752 INFO  [MasterRpcServer-methodInvoker-15] o.a.d.s.m.e.WorkflowEventBus:[41] - Publish event: WorkflowStopLifecycleEvent{workflow=flow_condition_import_20251201155754777-20251201155805585}
[WI-8][TI-0] - 2025-12-01 18:54:51.851 INFO  [ds-workflow-eventbus-worker-0] o.a.d.s.m.e.w.l.h.AbstractWorkflowLifecycleEventHandler:[47] - Begin fire workflow flow_condition_import_20251201155754777-20251201155805585 LifecycleEvent[WorkflowStopLifecycleEvent{workflow=flow_condition_import_20251201155754777-20251201155805585}] with state: RUNNING_EXECUTION
[WI-8][TI-0] - 2025-12-01 18:54:51.863 INFO  [ds-workflow-eventbus-worker-0] o.a.d.s.m.e.w.s.AbstractWorkflowStateAction:[161] - Success set WorkflowExecuteRunnable: flow_condition_import_20251201155754777-20251201155805585 state from: RUNNING_EXECUTION to READY_STOP
[WI-8][TI-0] - 2025-12-01 18:54:51.864 INFO  [ds-workflow-eventbus-worker-0] o.a.d.s.m.e.WorkflowEventBus:[41] - Publish event: TaskKillLifecycleEvent{task=sh01, delayTime=0}
[WI-0][TI-0] - 2025-12-01 18:54:51.865 INFO  [ds-workflow-eventbus-worker-0] o.a.d.s.m.e.w.l.h.AbstractWorkflowLifecycleEventHandler:[52] - Fired workflow flow_condition_import_20251201155754777-20251201155805585 LifecycleEvent[WorkflowStopLifecycleEvent{workflow=flow_condition_import_20251201155754777-20251201155805585}] with state: READY_STOP
[WI-0][TI-0] - 2025-12-01 18:54:51.865 INFO  [ds-workflow-eventbus-worker-0] o.a.d.s.m.e.t.d.WorkerGroupDispatcherCoordinator:[74] - Failed to remove Task[id=14] from WorkerGroupDispatcher[name=default], this task has been dispatched
[WI-0][TI-0] - 2025-12-01 18:54:51.866 INFO  [ds-workflow-eventbus-worker-0] o.a.d.s.m.e.t.s.TaskSubmittedStateAction:[158] - The task[id=14] is submitted and already dispatched, cannot kill, will kill it after 5s
[WI-0][TI-0] - 2025-12-01 18:54:51.866 INFO  [ds-workflow-eventbus-worker-0] o.a.d.s.m.e.WorkflowEventBus:[41] - Publish event: TaskKillLifecycleEvent{task=sh01, delayTime=5000}
[WI-0][TI-0] - 2025-12-01 18:54:51.866 INFO  [ds-workflow-eventbus-worker-0] o.a.d.s.m.e.t.l.h.AbstractTaskLifecycleEventHandler:[47] - Fired task sh01 TaskKillLifecycleEvent{task=sh01, delayTime=0} with state SUBMITTED_SUCCESS
[WI-8][TI-0] - 2025-12-01 18:54:56.878 INFO  [ds-workflow-eventbus-worker-16] o.a.d.s.m.e.t.d.WorkerGroupDispatcherCoordinator:[74] - Failed to remove Task[id=14] from WorkerGroupDispatcher[name=default], this task has been dispatched
[WI-8][TI-0] - 2025-12-01 18:54:56.878 INFO  [ds-workflow-eventbus-worker-16] o.a.d.s.m.e.t.s.TaskSubmittedStateAction:[158] - The task[id=14] is submitted and already dispatched, cannot kill, will kill it after 5s
[WI-8][TI-0] - 2025-12-01 18:54:56.878 INFO  [ds-workflow-eventbus-worker-16] o.a.d.s.m.e.WorkflowEventBus:[41] - Publish event: TaskKillLifecycleEvent{task=sh01, delayTime=5000}
[WI-8][TI-0] - 2025-12-01 18:54:56.878 INFO  [ds-workflow-eventbus-worker-16] o.a.d.s.m.e.t.l.h.AbstractTaskLifecycleEventHandler:[47] - Fired task sh01 TaskKillLifecycleEvent{task=sh01, delayTime=5000} with state SUBMITTED_SUCCESS
[WI-8][TI-0] - 2025-12-01 18:55:01.889 INFO  [ds-workflow-eventbus-worker-13] o.a.d.s.m.e.t.d.WorkerGroupDispatcherCoordinator:[74] - Failed to remove Task[id=14] from WorkerGroupDispatcher[name=default], this task has been dispatched
[WI-8][TI-0] - 2025-12-01 18:55:01.890 INFO  [ds-workflow-eventbus-worker-13] o.a.d.s.m.e.t.s.TaskSubmittedStateAction:[158] - The task[id=14] is submitted and already dispatched, cannot kill, will kill it after 5s
[WI-8][TI-0] - 2025-12-01 18:55:01.890 INFO  [ds-workflow-eventbus-worker-13] o.a.d.s.m.e.WorkflowEventBus:[41] - Publish event: TaskKillLifecycleEvent{task=sh01, delayTime=5000}
[WI-8][TI-0] - 2025-12-01 18:55:01.890 INFO  [ds-workflow-eventbus-worker-13] o.a.d.s.m.e.t.l.h.AbstractTaskLifecycleEventHandler:[47] - Fired task sh01 TaskKillLifecycleEvent{task=sh01, delayTime=5000} with state SUBMITTED_SUCCESS
[WI-8][TI-0] - 2025-12-01 18:55:06.900 INFO  [ds-workflow-eventbus-worker-1] o.a.d.s.m.e.t.d.WorkerGroupDispatcherCoordinator:[74] - Failed to remove Task[id=14] from WorkerGroupDispatcher[name=default], this task has been dispatched
[WI-8][TI-0] - 2025-12-01 18:55:06.901 INFO  [ds-workflow-eventbus-worker-1] o.a.d.s.m.e.t.s.TaskSubmittedStateAction:[158] - The task[id=14] is submitted and already dispatched, cannot kill, will kill it after 5s
[WI-8][TI-0] - 2025-12-01 18:55:06.901 INFO  [ds-workflow-eventbus-worker-1] o.a.d.s.m.e.WorkflowEventBus:[41] - Publish event: TaskKillLifecycleEvent{task=sh01, delayTime=5000}
[WI-8][TI-0] - 2025-12-01 18:55:06.901 INFO  [ds-workflow-eventbus-worker-1] o.a.d.s.m.e.t.l.h.AbstractTaskLifecycleEventHandler:[47] - Fired task sh01 TaskKillLifecycleEvent{task=sh01, delayTime=5000} with state SUBMITTED_SUCCESS
[WI-8][TI-0] - 2025-12-01 18:55:11.912 INFO  [ds-workflow-eventbus-worker-14] o.a.d.s.m.e.t.d.WorkerGroupDispatcherCoordinator:[74] - Failed to remove Task[id=14] from WorkerGroupDispatcher[name=default], this task has been dispatched
[WI-8][TI-0] - 2025-12-01 18:55:11.912 INFO  [ds-workflow-eventbus-worker-14] o.a.d.s.m.e.t.s.TaskSubmittedStateAction:[158] - The task[id=14] is submitted and already dispatched, cannot kill, will kill it after 5s
[WI-8][TI-0] - 2025-12-01 18:55:11.912 INFO  [ds-workflow-eventbus-worker-14] o.a.d.s.m.e.WorkflowEventBus:[41] - Publish event: TaskKillLifecycleEvent{task=sh01, delayTime=5000}
[WI-8][TI-0] - 2025-12-01 18:55:11.913 INFO  [ds-workflow-eventbus-worker-14] o.a.d.s.m.e.t.l.h.AbstractTaskLifecycleEventHandler:[47] - Fired task sh01 TaskKillLifecycleEvent{task=sh01, delayTime=5000} with state SUBMITTED_SUCCESS
[WI-8][TI-0] - 2025-12-01 18:55:16.923 INFO  [ds-workflow-eventbus-worker-13] o.a.d.s.m.e.t.d.WorkerGroupDispatcherCoordinator:[74] - Failed to remove Task[id=14] from WorkerGroupDispatcher[name=default], this task has been dispatched
[WI-8][TI-0] - 2025-12-01 18:55:16.923 INFO  [ds-workflow-eventbus-worker-13] o.a.d.s.m.e.t.s.TaskSubmittedStateAction:[158] - The task[id=14] is submitted and already dispatched, cannot kill, will kill it after 5s
[WI-8][TI-0] - 2025-12-01 18:55:16.923 INFO  [ds-workflow-eventbus-worker-13] o.a.d.s.m.e.WorkflowEventBus:[41] - Publish event: TaskKillLifecycleEvent{task=sh01, delayTime=5000}

### What you expected to happen

A workflow that failed during initialization should be able to be killed normally.

### How to reproduce

1, import a workflow definition(The environment code does not exist.).
2, When running the workflow, the task cann‘t be dispatched.
3, When manually killing the workflow, it remains stuck in the "waiting to be killed" state.

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by njnu-seafish**
## Purpose of the pull request

close #17758 

## Brief change log

Add logic to handle tasks that fail during initialization.

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

## Pull Request Notice
[Pull Request Notice](https://github.com/apache/dolphinscheduler/blob/dev/docs/docs/en/contribute/join/pull-request.md)

If your pull request contains incompatible change, you should also add it to `docs/docs/en/guide/upgrade/incompatible.md`

### CODE REVIEW

**Review by ruanwenjun — COMMENTED** [review]
Should fire a `TaskFailedLifecycleEvent` when task initialize failed.

**Comment by njnu-seafish** [comment]
> Should fire a `TaskFailedLifecycleEvent` when task initialize failed.

yes, add logic to handle TaskFatalLifecycleEvent

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/task/statemachine/TaskSubmittedStateAction.java [hunk 1]
```diff
@@ -109,7 +111,17 @@ public void onDispatchEvent(final IWorkflowExecutionRunnable workflowExecutionRu
...
+            taskExecutionRunnable.initializeTaskExecutionContext();
+        } catch (Exception ex) {
+            log.error("Current taskInstance: {} initializeTaskExecutionContext error", taskInstance.getName(), ex);
+            final TaskFatalLifecycleEvent taskFatalEvent = TaskFatalLifecycleEvent.builder()
+                    .taskExecutionRunnable(taskExecutionRunnable)
+                    .endTime(new Date())
+                    .build();
+            taskExecutionRunnable.getWorkflowEventBus().publish(taskFatalEvent);
+            return;
+        }
```
Comment (ruanwenjun) [inline dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/task/statemachine/TaskSubmittedStateAction.java]: You need to create a `TaskFatalException`, and throw `TaskFatalException` here and handle `TaskFatalException` at `WorkflowEventBusFireWorker`.

**Review by ruanwenjun — CHANGES_REQUESTED** [review]

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/task/statemachine/TaskSubmittedStateAction.java (hunk 1 above)
Comment (njnu-seafish) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/task/statemachine/TaskSubmittedStateAction.java]: > You need to create a `TaskFatalException`, and throw `TaskFatalException` here and handle `TaskFatalException` at `WorkflowEventBusFireWorker`.

ok. first throw TaskFatalException then publish TaskFatalLifecycleEvent

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/task/lifecycle/TaskLifecycleEventType.java [hunk 2]
```diff
@@ -29,6 +29,10 @@ public enum TaskLifecycleEventType implements ILifecycleEventType {
      * Dispatch the task instance to target.
      */
     DISPATCH,
+    /**
+     * Severe and unrecoverable errors, such as initialization failure.
```
Comment (ruanwenjun) [inline dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/task/lifecycle/TaskLifecycleEventType.java]:
```suggestion
     * Task instance encounters catastrophic failure, it will enter a failed state.
```

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/task/statemachine/AbstractTaskStateAction.java [hunk 3]
```diff
@@ -99,6 +100,29 @@ protected void releaseTaskInstanceResourcesIfNeeded(final ITaskExecutionRunnable
...
+    @Override
+    public void onFatalEvent(final IWorkflowExecutionRunnable workflowExecutionRunnable,
+                             final ITaskExecutionRunnable taskExecutionRunnable,
+                             final TaskFatalLifecycleEvent taskFatalEvent) {
+        releaseTaskInstanceResourcesIfNeeded(taskExecutionRunnable);
+
+        final TaskInstance taskInstance = taskExecutionRunnable.getTaskInstance();
+        taskInstance.setState(TaskExecutionStatus.FAILURE);
+        taskInstance.setEndTime(taskFatalEvent.getEndTime());
+        taskInstanceDao.updateById(taskInstance);
```
Comment (ruanwenjun) [inline dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/task/statemachine/AbstractTaskStateAction.java]:
```suggestion
        persistentTaskInstanceFatalEventToDB(taskExecutionRunnable, taskFatalEvent)
```

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/task/statemachine/ITaskStateAction.java [hunk 4]
```diff
@@ -89,7 +91,15 @@ void onRetryEvent(final IWorkflowExecutionRunnable workflowExecutionRunnable,
      */
     void onDispatchEvent(final IWorkflowExecutionRunnable workflowExecutionRunnable,
                          final ITaskExecutionRunnable taskExecutionRunnable,
-                         final TaskDispatchLifecycleEvent taskDispatchEvent);
+                         final TaskDispatchLifecycleEvent taskDispatchEvent) throws TaskFatalException;
+
+    /**
+     * Perform the necessary actions when the task in a certain state receive a {@link TaskFatalLifecycleEvent}.
+     * <p> This method is called when the task encounters an unrecoverable error (e.g., initialization failure).
```
Comment (ruanwenjun) [inline dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/task/statemachine/ITaskStateAction.java]:
```suggestion
     * <p> This method is called when the task encounters catastrophic failure (e.g., initialization failure).
```

We will still retry the task instance if config retry policy.

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/task/statemachine/TaskSubmittedStateAction.java [hunk 5]
```diff
@@ -109,7 +110,12 @@ public void onDispatchEvent(final IWorkflowExecutionRunnable workflowExecutionRu
                     taskInstance.getDelayTime(),
                     remainTimeMills);
         }
-        taskExecutionRunnable.initializeTaskExecutionContext();
+        try {
+            taskExecutionRunnable.initializeTaskExecutionContext();
+        } catch (Exception ex) {
+            log.error("Current taskInstance: {} initializeTaskExecutionContext fail", taskInstance.getName(), ex);
+            throw new TaskFatalException(taskInstance.getName() + " initializeTaskExecutionContext fail");
+        }
```
Comment (ruanwenjun) [inline dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/task/statemachine/TaskSubmittedStateAction.java]:
```suggestion

            taskExecutionRunnable.initializeTaskExecutionContext();
```

It's better to throw `TaskFatalException` in `TaskExecutionContextFactory#createTaskExecutionContext` method. Not all exception should be transformed to `TaskFatalException`.

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/WorkflowEventBusFireWorker.java [hunk 6]
```diff
@@ -128,6 +132,19 @@ private void doFireSingleWorkflowEventBus(final IWorkflowExecutionRunnable workf
                     ThreadUtils.sleep(5_000);
                     return;
                 }
+                // the task encounters an unrecoverable error (e.g., initialization failure).
+                if (ExceptionUtils.isTaskFatalException(ex)) {
+                    log.warn("Task fatal exception occurred during event handling: {}", lifecycleEvent, ex);
+                    if (lifecycleEvent instanceof TaskDispatchLifecycleEvent) {
```
Comment (ruanwenjun) [inline dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/WorkflowEventBusFireWorker.java]:
```suggestion
                    if (lifecycleEvent instanceof AbstractTaskLifecycleEvent) {
```

**Comment by ruanwenjun** [comment]
We need to use more direct titles to indicate the problems addressed by the PR.

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/task/lifecycle/TaskLifecycleEventType.java (hunk 2 above)
Comment (njnu-seafish) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/task/lifecycle/TaskLifecycleEventType.java]: > 

ok

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/task/statemachine/AbstractTaskStateAction.java (hunk 3 above)
Comment (njnu-seafish) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/task/statemachine/AbstractTaskStateAction.java]: ok

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/task/statemachine/ITaskStateAction.java (hunk 4 above)
Comment (njnu-seafish) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/task/statemachine/ITaskStateAction.java]: ok

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/task/statemachine/TaskSubmittedStateAction.java (hunk 5 above)
Comment (njnu-seafish) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/task/statemachine/TaskSubmittedStateAction.java]: > taskExecutionRunnable.initializeTaskExecutionContext();

ok，catch exception and publish TaskFatalLifecycleEvent in doFireSingleWorkflowEventBus

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/WorkflowEventBusFireWorker.java (hunk 6 above)
Comment (njnu-seafish) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/WorkflowEventBusFireWorker.java]: > 

ok

**Review by ruanwenjun — APPROVED** [review]
LGTM

**Review by SbloodyS — APPROVED** [review]
+1
