### PR TITLE
[Fix-12966] Failed to export and then import the project

### LINKED ISSUE #12966: [Bug] Failed to export and then import the project.
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Failed to export and then import the project. The id of the branch flow does not correspond

image

### What you expected to happen

Normal import and export 

### How to reproduce

import and export project with condition task

### Anything else

_No response_

### Version

2.0.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by brave-lee**
Fix #12966

### CODE REVIEW

**Comment by wcmolin** [comment]
+1

File: dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/task/switchtask/SwitchParameters.java [hunk 1]
```diff
@@ -74,21 +76,18 @@ public void setDependTaskList(List<SwitchResultVo> dependTaskList) {
...
-            this.nextNode = nextNodeList;
-        } else if (nextNode instanceof Number) {
-            List<String> nextNodeList = new ArrayList<>();
-            nextNodeList.add(nextNode.toString());
-            this.nextNode = nextNodeList;
+        if (nextNode instanceof Long) {
+            this.nextNode = (Long) nextNode;
         } else {
-            this.nextNode = (ArrayList) nextNode;
+            List<String> nextNodes = (ArrayList) nextNode;
```
Comment (gnailJC) [inline dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/task/switchtask/SwitchParameters.java:87]: image

An CaseError will occur if the nextNode is empty when `branch flow` is not set.

Comment (brave-lee) [reply dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/task/switchtask/SwitchParameters.java:87]: I think it is possible. Can you submit a new issue to describe it
