### PR TITLE
[BUG][TaskGroup] Task group does not take effect

### LINKED ISSUE #10092: [Bug] [TaskGroup] Task group does not take effect
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Detailed scenario: the task group configures three resources and creates a workflow. Six tasks in the workflow (all of which are executed for 30s) use this task group. The priority in the group is 1 to 6, which corresponds to the task name. The six tasks are in parallel relationship. After startup, 2, 3 and 4 run first, and 1, 5 and 6 run in the second batch. According to the description in the document, the higher the priority number, the higher the priority. The expectation should be 4, 5, 6 and then 1, 2 and 3
Task group does not take effect.

### What you expected to happen

Submit higher priority tasks firstly. The order should be 4,5,6 and then 1,2,3

### How to reproduce

up

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by lenboo**
## Purpose of the pull request
Fix #10092 Task group does not take effect.

## Brief change log
1. add task group priority sort in readyToSubmitQueue
2. add task group priority sort in task queue that ready submit to worker.

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

### CODE REVIEW

File: dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/queue/TaskPriority.java [hunk 1]
```diff
@@ -169,15 +182,20 @@ public int compareTo(TaskPriority other) {
...
+        }
         if (this.getTaskId() > other.getTaskId()) {
             return 1;
         }
         if (this.getTaskId() < other.getTaskId()) {
             return -1;
         }
-
-        return this.getGroupName().compareTo(other.getGroupName());
+        if(!this.getGroupName().equals(other.getGroupName())){
```
Comment (caishunfeng) [inline dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/queue/TaskPriority.java]: groupName can be null?

Comment (lenboo) [reply dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/queue/TaskPriority.java]: > groupName can be null?

maybe, i will check it.

**Review by caishunfeng — APPROVED** [review]
+1

**Comment by ruanwenjun** [comment]
LGTM

**Review by WangJPLeo — COMMENTED** [review]
LGTM
