### PR TITLE
[Fix-14646][Worker] Fix match wrong pid on linux server

### LINKED ISSUE #14646: [Bug] [Worker] Match wrong pid on linux server
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

If you deploy DS on linux server, cancel process instance, then it's possible to get error log:
```
[ERROR] 2023-07-27 23:14:54.887 +0800 org.apache.dolphinscheduler.server.worker.processor.WorkerTaskKillProcessor:[196] - kill task error
org.apache.dolphinscheduler.common.shell.AbstractShell$ExitCodeException: kill: (26483): Operation not permitted
kill: (558): No such process
kill: (1493): No such process
```

### What you expected to happen

No error log.

### How to reproduce

Ditto.

### Anything else

That is because in `ProcessUtils.getPidsStr`, only match pids on macos and windows.

```java
        if (SystemUtils.IS_OS_MAC) {
            String pids = OSUtils.exeCmd(String.format("%s -sp %d", TaskConstants.PSTREE, processId));
            if (null != pids) {
                mat = MACPATTERN.matcher(pids);
            }
        } else {
            String pids = OSUtils.exeCmd(String.format("%s -p %d", TaskConstants.PSTREE, processId));
            mat = WINDOWSATTERN.matcher(pids);
        }
```

If run on linux server, will get pids string like: `sudo(6279)---558_1497.sh(6282)---sleep(6354)`, but if use windows matcher,  it will match "6279 558 1497 6282 6354", expected matching results is "6279 6282 6354".

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by CallMeKingsley97**
This closes #14646

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

File: dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/utils/ProcessUtils.java [hunk 1]
```diff
@@ -76,7 +76,12 @@ private ProcessUtils() {
     /**
      * Expression of PID recognition in Windows scene
      */
-    private static final Pattern WINDOWSATTERN = Pattern.compile("(\\d+)");
+    private static final Pattern WINDOWSPATTERN = Pattern.compile("(\\d+)");
+
+    /**
+     * Expression of PID recognition in Linux scene
+     */
+    private static final Pattern LINUXPATTERN = Pattern.compile("\\((\\d+)\\)");
```
Comment (SbloodyS) [inline dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/utils/ProcessUtils.java:84]: Please add some UT.

Comment (CallMeKingsley97) [reply dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/utils/ProcessUtils.java:84]: > Please add some UT.

I added somt UT. Please take a look.

File: dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/test/java/org/apache/dolphinscheduler/plugin/task/api/utils/ProcessUtilsTest.java [hunk 2]
```diff
@@ -0,0 +1,69 @@
...
+        if (StringUtils.isNotEmpty(pids)) {
+            mat = LINUXPATTERN.matcher(pids);
+        }
+        if (null != mat) {
+            while (mat.find()) {
+                sb.append(mat.group(1)).append(" ");
+            }
+        }
+        return sb.toString().trim();
+    }
```
Comment (Radeity) [inline dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/test/java/org/apache/dolphinscheduler/plugin/task/api/utils/ProcessUtilsTest.java]: Please directly use method in `ProcessUtils`.

Comment (CallMeKingsley97) [reply dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/test/java/org/apache/dolphinscheduler/plugin/task/api/utils/ProcessUtilsTest.java]: > Please directly use method in `ProcessUtils`.

image
Can the method "getPidsStr" run right like the screenshot? (Because there is no processes in UT)

Comment (Radeity) [reply dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/test/java/org/apache/dolphinscheduler/plugin/task/api/utils/ProcessUtilsTest.java]: You can mock the return value of `OSUtils.exeCmd`, otherwise, this UT is meaningless without any code coverage.

Comment (CallMeKingsley97) [reply dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/test/java/org/apache/dolphinscheduler/plugin/task/api/utils/ProcessUtilsTest.java]: > You can mock the return value of `OSUtils.exeCmd`, otherwise, this UT is meaningless without any code coverage.
image

If i mock the return value of `OSUtils.exeCmd`, my method is to copy the code from `getPidsStr` from `ProcessUtils`.
Or there is a better way to do that in UT?

Comment (Radeity) [reply dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/test/java/org/apache/dolphinscheduler/plugin/task/api/utils/ProcessUtilsTest.java]: You can refer to other test files, and use Mockito API.

Comment (CallMeKingsley97) [reply dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/test/java/org/apache/dolphinscheduler/plugin/task/api/utils/ProcessUtilsTest.java]: > You can refer to other test files, and use Mockito API.

Please take a look, thanks

Comment (Radeity) [reply dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/test/java/org/apache/dolphinscheduler/plugin/task/api/utils/ProcessUtilsTest.java]: Please check failed UT.

Comment (CallMeKingsley97) [reply dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/test/java/org/apache/dolphinscheduler/plugin/task/api/utils/ProcessUtilsTest.java]: > Please check failed UT.

Ok

**Comment by CallMeKingsley97** [comment]
Please run it again. Thanks @SbloodyS

**Comment by SbloodyS** [comment]
> Please run it again. Thanks @SbloodyS

Done.

**Comment by CallMeKingsley97** [comment]
> > Please run it again. Thanks @SbloodyS
> 
> Done.

Once again, please😂

File: dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/test/java/org/apache/dolphinscheduler/plugin/task/api/utils/ProcessUtilsTest.java (hunk 2 above)
Comment (CallMeKingsley97) [reply dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/test/java/org/apache/dolphinscheduler/plugin/task/api/utils/ProcessUtilsTest.java]: Any other problems? 😉

**Comment by Radeity** [comment]
Hi @CallMeKingsley97 , may I ask why you separate these three test cases? It doesn't seem to cover three different OS.

**Comment by CallMeKingsley97** [comment]
> Hi @CallMeKingsley97 , may I ask why you separate these three test cases? It doesn't seem to cover three different OS.

Sorry, I forgot to read the reply earlier.   These cases just for linux OS, in order to test different types of processes.

**Review by Radeity — APPROVED** [review]
LGTM

**Comment by Radeity** [comment]
Hi @Gallardot , please help check this  `E2E-K8S-Execute`  failure :D

**Comment by Gallardot** [comment]
> Hi @Gallardot , please help check this `E2E-K8S-Execute` failure :D

oops. Due to the recent release of the latest version of Kubernetes, there may be differences in the command. I will fix this issue immediately.
