### PR TITLE
[Fix-8828] [Master] Assign tasks to worker optimization

### LINKED ISSUE #8828: [Bug] [Master] Assign tasks to worker optimization
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When a worker is under high pressure, such as two workers, one of whom is hung up due to high pressure, the task is fault tolerant to the other worker. The other worker can only execute 20 tasks due to the number of threads. All subsequent tasks are waiting. Even if the suspended worker is restarted, no tasks can be assigned

### What you expected to happen

Restart worker can get tasks normally.

### How to reproduce

Please see the process description.

### Anything else

_No response_

### Version

2.0.5

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by brave-lee**
closed: #8828

### CODE REVIEW

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/dispatch/ExecutorDispatcher.java [hunk 1]
```diff
@@ -71,30 +77,24 @@ public ExecutorDispatcher() {
...
-         * host select
-         */
-
+        // host select
         Host host = hostManager.select(context);
         if (StringUtils.isEmpty(host.getAddress())) {
-            throw new ExecuteException(String.format("fail to execute : %s due to no suitable worker, "
-                            + "current task needs worker group %s to execute",
-                    context.getCommand(),context.getWorkerGroup()));
+            ThreadUtils.sleep(Constants.SLEEP_TIME_MILLIS);
```
Comment (caishunfeng) [inline dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/dispatch/ExecutorDispatcher.java]: Why to sleep here? Dispatcher is a single thread, we should avoid to sleep here.

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/dispatch/host/assign/LowerWeightRoundRobin.java [hunk 2]
```diff
@@ -45,7 +51,21 @@ public HostWeight doSelect(Collection<HostWeight> sources) {
...
+    }
 
+    private List<HostWeight> canAssignTaskHost(Collection<HostWeight> sources) {
+        List<HostWeight> zeroWaitingTask = sources.stream().filter(h -> h.getWaitingTaskCount() == 0).collect(Collectors.toList());
+        if (!zeroWaitingTask.isEmpty()) {
+            return zeroWaitingTask;
+        }
+        HostWeight hostWeight = sources.stream().min(Comparator.comparing(HostWeight::getWaitingTaskCount)).get();
+        List<HostWeight> waitingTask = Lists.newArrayList(hostWeight);
+        List<HostWeight> equalWaitingTask = sources.stream().filter(h -> !h.getHost().equals(hostWeight.getHost()) && h.getWaitingTaskCount() == hostWeight.getWaitingTaskCount())
```
Comment (caishunfeng) [inline dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/dispatch/host/assign/LowerWeightRoundRobin.java:63]: Why not just return the hostWeight list which order by waitingTaskCount asc?

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/processor/queue/TaskExecuteThread.java [hunk 3]
```diff
@@ -221,4 +227,23 @@ private void handleResultEvent(TaskEvent taskEvent, TaskInstance taskInstance) {
...
+        try {
+            if (executeThread != null) {
+                executeThread.resubmit(taskInstance.getTaskCode());
+            }
+            if (channel != null) {
+                TaskRecallAckCommand taskRecallAckCommand = new TaskRecallAckCommand(ExecutionStatus.SUCCESS.getCode(), taskInstance.getId());
+                channel.writeAndFlush(taskRecallAckCommand.convert2Command());
+            }
+        } catch (Exception e) {
+            logger.error("worker reject error", e);
```
Comment (caishunfeng) [inline dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/processor/queue/TaskExecuteThread.java]:
```suggestion
            logger.error("handle worker reject event error", e);
```

File: dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/runner/WorkerManagerThread.java [hunk 4]
```diff
@@ -47,7 +51,7 @@ public class WorkerManagerThread implements Runnable {
     /**
      * task queue
      */
-    private final DelayQueue<TaskExecuteThread> workerExecuteQueue = new DelayQueue<>();
```
Comment (caishunfeng) [inline dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/runner/WorkerManagerThread.java:50]: The DelayQueue will take effect of the delay strategy, so it's useful and don't remove it.

**Review by caishunfeng — DISMISSED** [review]

File: dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/runner/WorkerManagerThread.java (hunk 4 above)
Comment (brave-lee) [reply dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/runner/WorkerManagerThread.java:50]: Since the DelayQueue is an infinite queue, our delay strategy is not realized through the queue, so this is meaningless  and can be replaced

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/dispatch/host/assign/LowerWeightRoundRobin.java (hunk 2 above)
Comment (brave-lee) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/dispatch/host/assign/LowerWeightRoundRobin.java:63]: Because the waitingTaskCount is large, the current load may be low

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/dispatch/ExecutorDispatcher.java (hunk 1 above)
Comment (brave-lee) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/dispatch/ExecutorDispatcher.java]: I think hostManager.select(context) failed to get available workers, we can wait 1s to get it again, otherwise Master will output this log frequently

**Comment by caishunfeng** [comment]
This pr is related to the main process, so more people are needed to review.

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/dispatch/ExecutorDispatcher.java (hunk 1 above)
Comment (ruanwenjun) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/dispatch/ExecutorDispatcher.java]: It's better to add a comment or todo in the code, why we sleep. If we find a better way to replace the sleep in the future, we can optimize this.

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/dispatch/host/assign/HostWeight.java [hunk 5]
```diff
@@ -37,10 +37,13 @@ public class HostWeight {
 
     private double currentWeight;
 
-    public HostWeight(HostWorker hostWorker, double cpu, double memory, double loadAverage, long startTime) {
+    private final int waitingTaskCount;
+
+    public HostWeight(HostWorker hostWorker, double cpu, double memory, double loadAverage, int waitingTaskCount, long startTime) {
```
Comment (ruanwenjun) [inline dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/dispatch/host/assign/HostWeight.java:42]: Does the `startTime` be used? If this is not used, we can remove.

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/dispatch/host/assign/LowerWeightRoundRobin.java [hunk 6]
```diff
@@ -45,7 +51,21 @@ public HostWeight doSelect(Collection<HostWeight> sources) {
         }
         lowerNode.setCurrentWeight(lowerNode.getCurrentWeight() + totalWeight);
         return lowerNode;
+    }
 
+    private List<HostWeight> canAssignTaskHost(Collection<HostWeight> sources) {
```
Comment (ruanwenjun) [inline dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/dispatch/host/assign/LowerWeightRoundRobin.java:56]:
```suggestion
    private List<HostWeight> findMinimumWaitingTaskHost(Collection<HostWeight> sources) {
```

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/dispatch/host/assign/HostWeight.java (hunk 5 above)
Comment (brave-lee) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/dispatch/host/assign/HostWeight.java:42]: It is used to calculate the load before the first heartbeat when the worker starts

Comment (ruanwenjun) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/dispatch/host/assign/HostWeight.java:42]: OK, I see the code.

**Comment by ruanwenjun** [comment]
I don't see the whole code, in my knowledge, when master choose worker, it will follow the two steps:
1. Calculate the current load of each worker.
2. Find the minimum load worker and dispatch task. 
So we just need to add the worker's waiting task in heartbeat, and when master calculate the load it should consider the worker's waiting task is enough for this issue. 

Add worker reject command is another improvement, it's ok to me, it can protect the worker, but I think we don't need to cache the reject task, just consider it as unassign task is enough.

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/dispatch/ExecutorDispatcher.java (hunk 1 above)
Comment (brave-lee) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/dispatch/ExecutorDispatcher.java]: I will remove it

**Review by lenboo — APPROVED** [review]
+1

**Comment by caishunfeng** [comment]
> I don't see the whole code, in my knowledge, when master choose worker, it will follow the two steps:
> 
> 1. Calculate the current load of each worker.
> 2. Find the minimum load worker and dispatch task.
>    So we just need to add the worker's waiting task in heartbeat, and when master calculate the load it should consider the worker's waiting task is enough for this issue.
> 
> Add worker reject command is another improvement, it's ok to me, it can protect the worker, but I think we don't need to cache the reject task, just consider it as unassign task is enough.

Yes, I saw the code logic is resubmiting the recall task, I think it means the same thing as you.

**Review by caishunfeng — APPROVED** [review]
LGTM
