### PR TITLE
[Fix-5468][Common] Fix obtaining IP is incorrect

### LINKED ISSUE #5468: [Bug][Common] Obtaining IP is incorrect
**To Reproduce**
In some scenarios, obtaining IP is incorrect

**Expected behavior**
Bug fixed

**Screenshots**

**Scenario 1: IP is null**
image

**Scenario 2: IP incorrect order**
image
image

**Scenario 3: IP is 127.0.0.1**
image
image

**Scenario 4: IP is 0.0.0.0.0.0**
image
image
image

**Which version of Dolphin Scheduler:**
 -[1.3.x]
 -[dev]

**Additional context**

**Requirement or improvement**
- Please describe about your requirements or improvement suggestions.

### PR DESCRIPTION
**Pull request by chengshiwen**
## Purpose of the pull request

*[Fix-5468][Common] Fix obtaining IP is incorrect*

Fix #5468

## Brief change log

  - *Fix obtaining IP is incorrect*
  - *Add `dolphin.scheduler.network.interface.preferred` in `common.properties`*

## Verify this pull request

This change added tests and can be verified as follows:

  - *Manually verified the change by testing locally.*

### CODE REVIEW

File: dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/NetUtils.java [hunk 1]
```diff
@@ -130,7 +128,7 @@ private static synchronized InetAddress getLocalAddress0() {
                     Optional<InetAddress> addressOp = toValidAddress(addresses.nextElement());
                     if (addressOp.isPresent()) {
                         try {
-                            if (addressOp.get().isReachable(100)) {
+                            if (addressOp.get().isReachable(300)) {
```
Comment (CalvinKirs) [inline dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/NetUtils.java]: 100 is actually better. Only in the windows environment will there be a greater delay. 
If the user environment really needs it, it is recommended to modify it yourself.

Comment (chengshiwen) [reply dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/NetUtils.java]: I changed it to 200. I have tested several times before that in some cases on linux, 100 will time out but 200 will not

Comment (chengshiwen) [reply dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/NetUtils.java]: There is a scenario: the 2nd ip is used, not the 1st ip
image
image

**Review by CalvinKirs — APPROVED** [review]
LGTM
