### PR TITLE
[Fix-13828][api] Fix the problem of work groups have two defult records

### LINKED ISSUE #13828: [Bug] [Api] Work group have two default work group records
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

In `Work Group Manage` page, there are two records of the `default` work group when I created work group with the `default` name.
image
After further debugging, I found that the use of `findAny `at https://github.com/apache/dolphinscheduler/blob/dev/dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/WorkerGroupServiceImpl.java#L296 caused the assume that the default worker group did not exist. As a result, a new default worker group was created in the result, even though it already existed.
image

### What you expected to happen

The default work group should be one record.

### How to reproduce

Create multiple other work group records and default work group.

### Anything else

_No response_

### Version

3.1.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by ralphgj**
## Purpose of the pull request
close #13828 

## Brief change log
Fix the problem of work groups have two defult records

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

**Comment by SbloodyS** [comment]
cc @ruanwenjun @caishunfeng

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/WorkerGroupServiceImpl.java [hunk 1]
```diff
@@ -293,7 +293,9 @@ private List<WorkerGroup> getWorkerGroups(List<Integer> ids) {
             workerGroups = workerGroupMapper.queryAllWorkerGroup();
         }
         Optional<Boolean> containDefaultWorkerGroups = workerGroups.stream()
-                .map(workerGroup -> Constants.DEFAULT_WORKER_GROUP.equals(workerGroup.getName())).findAny();
+                .map(workerGroup -> Constants.DEFAULT_WORKER_GROUP.equals(workerGroup.getName()))
+                .filter(result -> result)
```
Comment (rickchengx) [inline dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/WorkerGroupServiceImpl.java]: Hi, @ralphgj , could you please explain more about this filter()?

**Review by Radeity — CHANGES_REQUESTED** [review]
Hi, @ralphgj , my suggestion is to find out why is it possible to create another worker group named `default` and fix that bug, rather than directly filter here, WDYT?

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/WorkerGroupServiceImpl.java (hunk 1 above)
Comment (ralphgj) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/WorkerGroupServiceImpl.java]: The `containDefaultWorkerGroups` method should verify whether it contains the `default` work group. The `map` method only converts the work group into true/false, which indicates whether it is the `default` work group or not. The `findAny` method will select the first one. If the first work group converted by `map` is not the `default` work group, the result of `containDefaultWorkerGroups` will be false, but the actual work group retrieved contains the `default` work group.

**Comment by ralphgj** [comment]
> Hi, @ralphgj , my suggestion is to find out why is it possible to create another worker group named `default` and fix that bug, rather than directly filter here, WDYT?

@Radeity Currently, the default worker group contains all existing worker servers. However, in some cases, I do not want the default worker group include certain special worker servers.

**Comment by Radeity** [comment]
Hi, @ralphgj , thanks for your explanation for the use of `filter` above, i can get you point now, another humble suggestion, maybe use `anyMatch(result -> result)` is better : )

**Comment by ralphgj** [comment]
@Radeity thanks for your suggestion. I have resubmitted it. Could you please review it again?

**Comment by Radeity** [comment]
> @Radeity thanks for your suggestion. I have resubmitted it. Could you please review it again?

LGTM 👍

**Comment by SbloodyS** [comment]
> > Hi, @ralphgj , my suggestion is to find out why is it possible to create another worker group named `default` and fix that bug, rather than directly filter here, WDYT?
> 
> @Radeity Currently, the default worker group contains all existing worker servers. However, in some cases, I do not want the default worker group include certain special worker servers.

In this case, I think we should do a validation logic to avoid creating worker groups with the same name. Removing duplicates may lead to confusion among different users regarding worker groups with the same name.

**Comment by Radeity** [comment]
> In this case, I think we should do a validation logic to avoid creating worker groups with the same name. Removing duplicates may lead to confusion among different users regarding worker groups with the same name.

Hi, @SbloodyS , i think this PR has a correct fix, but wrong issue description which may be confused. Actually, we have this validation, user can not create worker groups with the same name, this bug happens because of using `findAny()`. @ralphgj , can you update your description to make it clearer?

**Comment by SbloodyS** [comment]
> Hi, @SbloodyS , i think this PR has a correct fix, but wrong issue description which may be confused. Actually, we have this validation, user can not create worker groups with the same name, this bug happens because of using `findAny()`. @ralphgj , can you update your description to make it clearer?

Yes. You are right. I didn't look carefully.

**Review by SbloodyS — APPROVED** [review]
+1

**Comment by ralphgj** [comment]
@Radeity Sure, I have updated it.
