### PR TITLE
[Fix-17613] [Master] Task group queue priority always remains 0

### LINKED ISSUE #17613: [Bug] [master] Task group queue priority always remains 0 in DolphinScheduler 3.3.1
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

In DolphinScheduler 3.3.1, when setting the task group priority within a workflow definition, the configuration is saved correctly in the UI. However, after execution, all task group queue priorities become 0, regardless of the configured values.

在 DolphinScheduler 3.3.1 版本中，当在工作流定义中为任务设置 组内优先级 时，界面上配置保存是正常的，但运行后发现任务组的 队列优先级始终为 0，与配置的优先级不一致。

### What you expected to happen

Each task in the workflow should retain and reflect its configured task group priority value during execution, which should affect the scheduling order within the task group queue.

期望在工作流运行时，每个任务能正确继承并体现其配置的 组内优先级 值，从而在任务组队列中正确体现调度优先级顺序。

### How to reproduce

1. Create a new workflow definition.
2. Add multiple tasks to the workflow.
3. Set different task group priorities for each task (e.g., 5, 10, 15).
4. Save and run the workflow definition.
5. Navigate to Resource Center → Task Group Management → Task Group Queue, and check the Group Priority column — all tasks show priority = 0, regardless of the configured values.

--------

1. 新建一个 工作流定义。
2. 添加多个任务。
3. 分别为每个任务设置不同的 组内优先级（如 5、10、15）。
4. 保存并运行该工作流定义。
5. 在 资源中心 → 任务组管理 → 任务组队列 中查看 组内优先级 一栏，可以看到所有任务的优先级都为 0，并未按配置生效。

Image

### Anything else

After checking the source code, the issue is caused by the method
`org.apache.dolphinscheduler.server.master.engine.task.runnable.AbstractTaskInstanceFactory#injectMetadataFromTaskDefinition`
not passing t`askDefinition.taskGroupPriority `to `taskInstance.taskGroupPriority.`

I have fixed this issue locally, and after the modification, the queue priority correctly reflects the configured value. I am willing to submit a Pull Request if needed.

通过查看源码发现，问题的原因在于：
`org.apache.dolphinscheduler.server.master.engine.task.runnable.AbstractTaskInstanceFactory#injectMetadataFromTaskDefinition`
中未将 `taskDefinition.taskGroupPriority` 传递给 `taskInstance.taskGroupPriority`。

我已在本地修复该问题，修复后任务组队列优先级能正确反映配置的值。如有需要，我愿意提交 Pull Request。

Image

### Version

dev

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by KwongHing**
## Purpose of the pull request

close https://github.com/apache/dolphinscheduler/issues/17613

## Brief change log
Pass `taskDefinition.taskGroupPriority` to `taskInstance.taskGroupPriority` to restore the task group queue’s sequential scheduling capability.

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

## Pull Request Notice
[Pull Request Notice](https://github.com/apache/dolphinscheduler/blob/dev/docs/docs/en/contribute/join/pull-request.md)

If your pull request contains incompatible change, you should also add it to `docs/docs/en/guide/upgrade/incompatible.md`

### CODE REVIEW

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/task/runnable/AbstractTaskInstanceFactory.java [hunk 1]
```diff
@@ -79,6 +79,7 @@ protected void injectMetadataFromTaskDefinition(TaskInstance taskInstance, TaskD
         taskInstance.setTaskType(taskDefinition.getTaskType());
         taskInstance.setTaskCode(taskDefinition.getCode());
         taskInstance.setTaskDefinitionVersion(taskDefinition.getVersion());
+        taskInstance.setTaskGroupPriority(taskDefinition.getTaskGroupPriority());
```
Comment (SbloodyS) [inline dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/task/runnable/AbstractTaskInstanceFactory.java]: Please add some tests to verify this.

**Review by ruanwenjun — COMMENTED** [review]
Good catch, this bug also exist at `cloneTaskInstance`, please fix this.
And you can add test case at `WorkflowStartTestCase`, you can add assertion at`testStartWorkflow_with_oneSuccessTaskUsingTaskGroup`.

**Comment by KwongHing** [comment]
@SbloodyS @ruanwenjun all done
IntelliJ IDEA 2025-10-30 23 06 40

**Review by SbloodyS — COMMENTED** [review]
Please run `mvn spotless:apply` to format the code. @KwongHing

**Comment by KwongHing** [comment]
> Please run `mvn spotless:apply` to format the code. 请运行 `mvn spotless:apply` 来格式化代码。@KwongHing

Done.

File: dolphinscheduler-master/src/test/java/org/apache/dolphinscheduler/server/master/integration/Repository.java [hunk 2]
```diff
@@ -87,4 +92,19 @@ public List<TaskInstance> queryAllTaskInstance() {
...
+     * @param workflowDefinition the workflow definition
+     * @return the list of {@link TaskGroupQueue} records ordered by priority descending
+     */
+    public List<TaskGroupQueue> queryTaskGroupQueue(WorkflowDefinition workflowDefinition) {
+        return queryWorkflowInstance(workflowDefinition)
+                .stream()
+                .flatMap(workflowInstance -> taskGroupQueueDao.queryByWorkflowInstanceId(workflowInstance.getId())
+                        .stream())
+                .sorted(Comparator.comparingInt(TaskGroupQueue::getId))
+                .collect(Collectors.toList());
```
Comment (SbloodyS) [inline dolphinscheduler-master/src/test/java/org/apache/dolphinscheduler/server/master/integration/Repository.java]: I'm not sure if we should add this code for a test. cc @ruanwenjun

Comment (ruanwenjun) [reply dolphinscheduler-master/src/test/java/org/apache/dolphinscheduler/server/master/integration/Repository.java]: No need to add this method, it's better to directly assert the priority number at IT.

File: dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/repository/TaskGroupQueueDao.java [hunk 3]
```diff
@@ -92,4 +92,13 @@ public interface TaskGroupQueueDao extends IDao<TaskGroupQueue> {
...
     List<TaskGroupQueue> queryWaitNotifyForceStartTaskGroupQueue(int minTaskGroupQueueId, int limit);
+
+    /**
+     * Query all {@link TaskGroupQueue} belonging to the specified workflow instance.
+     *
+     * @param workflowInstanceId workflowInstanceId
+     * @return TaskGroupQueue
+     */
+    List<TaskGroupQueue> queryByWorkflowInstanceId(Integer workflowInstanceId);
+
```
Comment (ruanwenjun) [inline dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/repository/TaskGroupQueueDao.java]: it's better to remove this method.

**Comment by ruanwenjun** [comment]
We also need to add IT case for retry task instance can clone the queue priority

**Comment by KwongHing** [comment]
PTAL @ruanwenjun 
image

**Comment by SbloodyS** [comment]
This is still unaddressed.
https://github.com/apache/dolphinscheduler/pull/17614#discussion_r2480091977

File: dolphinscheduler-master/src/test/java/org/apache/dolphinscheduler/server/master/integration/cases/WorkflowStartTestCase.java [hunk 4]
```diff
@@ -141,15 +145,32 @@ public void testStartWorkflow_with_oneSuccessTaskUsingTaskGroup() {
...
                             .hasSize(4)
                             .allMatch(taskInstance -> TaskExecutionStatus.SUCCESS.equals(taskInstance.getState())
                                     && taskInstance.getTaskGroupId() == context.getTaskGroups().get(0).getId());
+
+                    Assertions
+                            .assertThat(taskGroupQueueMap)
+                            .hasSize(4)
+                            .allSatisfy((id, taskGroupQueue) -> {
+                                assertThat(taskGroupQueue.getGroupId()).isEqualTo(taskDefinition.getTaskGroupId());
+                                assertThat(taskGroupQueue.getPriority()).isEqualTo(1);
```
Comment (KwongHing) [inline dolphinscheduler-master/src/test/java/org/apache/dolphinscheduler/server/master/integration/cases/WorkflowStartTestCase.java]: I’ve directly asserted the priority number here as suggested. @SbloodyS

Comment (SbloodyS) [reply dolphinscheduler-master/src/test/java/org/apache/dolphinscheduler/server/master/integration/cases/WorkflowStartTestCase.java]: You should remove the newly created method.

Comment (KwongHing) [reply dolphinscheduler-master/src/test/java/org/apache/dolphinscheduler/server/master/integration/cases/WorkflowStartTestCase.java]: I’ve checked the code. The `t_ds_task_instance` table doesn’t contain the `task_group_priority` field.
It only exists in the `t_ds_task_definition` and `t_ds_task_group_queue` tables,
so I believe the priority number can only be verified from `t_ds_task_group_queue` after the workflow starts.

Comment (ruanwenjun) [reply dolphinscheduler-master/src/test/java/org/apache/dolphinscheduler/server/master/integration/cases/WorkflowStartTestCase.java]: You should remove unused method.

Comment (SbloodyS) [reply dolphinscheduler-master/src/test/java/org/apache/dolphinscheduler/server/master/integration/cases/WorkflowStartTestCase.java]: In test cases, we can use `queryAllInQueueTaskGroupQueue` or any other method to achieve it. We don't need to add a new method just for test cases.

Comment (KwongHing) [reply dolphinscheduler-master/src/test/java/org/apache/dolphinscheduler/server/master/integration/cases/WorkflowStartTestCase.java]: Sorry, I just realized what you meant. I’ve made further changes to the code. Please take a look when you have time.

File: dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/TaskGroupQueueMapper.xml [hunk 5]
```diff
@@ -260,4 +260,10 @@
         limit #{limit}
     </select>
 
+    <select id="queryByWorkflowInstanceId" resultType="org.apache.dolphinscheduler.dao.entity.TaskGroupQueue">
+        select
+        <include refid="baseSql" />
+        from t_ds_task_group_queue
+        where workflow_instance_id = #{workflowInstanceId}
+    </select>
```
Comment (SbloodyS) [inline dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/TaskGroupQueueMapper.xml]: We should remove this.

File: dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/repository/impl/TaskGroupQueueDaoImpl.java [hunk 6]
```diff
@@ -92,4 +92,9 @@ public List<TaskGroupQueue> queryWaitNotifyForceStartTaskGroupQueue(int minTaskG
                 minTaskGroupQueueId,
                 limit);
     }
+
+    @Override
+    public List<TaskGroupQueue> queryByWorkflowInstanceId(Integer workflowInstanceId) {
+        return mybatisMapper.queryByWorkflowInstanceId(workflowInstanceId);
+    }
```
Comment (SbloodyS) [inline dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/repository/impl/TaskGroupQueueDaoImpl.java]: Remove this.

File: dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/repository/TaskGroupQueueDao.java [hunk 7]
```diff
@@ -92,4 +92,13 @@ public interface TaskGroupQueueDao extends IDao<TaskGroupQueue> {
...
      */
     List<TaskGroupQueue> queryWaitNotifyForceStartTaskGroupQueue(int minTaskGroupQueueId, int limit);
+
+    /**
+     * Query all {@link TaskGroupQueue} belonging to the specified workflow instance.
+     *
+     * @param workflowInstanceId workflowInstanceId
+     * @return TaskGroupQueue
+     */
+    List<TaskGroupQueue> queryByWorkflowInstanceId(Integer workflowInstanceId);
```
Comment (SbloodyS) [inline dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/repository/TaskGroupQueueDao.java]: Remove this.

File: dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/TaskGroupQueueMapper.java [hunk 8]
```diff
@@ -136,4 +136,6 @@ List<TaskGroupQueue> queryWaitNotifyForceStartTaskGroupQueue(@Param("inQueue") i
                                                                  @Param("forceStart") int forceStart,
                                                                  @Param("minTaskGroupQueueId") int minTaskGroupQueueId,
                                                                  @Param("limit") int limit);
+
+    List<TaskGroupQueue> queryByWorkflowInstanceId(@Param("workflowInstanceId") Integer workflowInstanceId);
```
Comment (SbloodyS) [inline dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/mapper/TaskGroupQueueMapper.java]: Remove this.

File: dolphinscheduler-master/src/test/resources/it/start/workflow_with_one_fake_task_failed_with_retry_using_task_group.yaml [hunk 9]
```diff
@@ -0,0 +1,76 @@
...
+taskGroups:
+  - id: 1
+    name: default
+    projectCode: 1
+    groupSize: 2
+    useSize: 0
+    userId: 1
+    status: YES
+    createTime: 2024-08-12 00:00:00
+    updateTime: 2021-08-12 00:00:00
```
Comment (SbloodyS) [inline dolphinscheduler-master/src/test/resources/it/start/workflow_with_one_fake_task_failed_with_retry_using_task_group.yaml]:
```suggestion
    updateTime: 2021-08-12 00:00:00
    
```

We should leave an blank line at the end of each file.

File: dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/TaskGroupQueueMapper.xml (hunk 5 above)
Comment (KwongHing) [reply dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/TaskGroupQueueMapper.xml]: Sorry, I was too careless. Please take another look.

File: dolphinscheduler-master/src/test/java/org/apache/dolphinscheduler/server/master/integration/cases/WorkflowStartTestCase.java [hunk 10]
```diff
@@ -141,15 +145,32 @@ public void testStartWorkflow_with_oneSuccessTaskUsingTaskGroup() {
...
+
         await()
                 .atMost(Duration.ofMinutes(2))
                 .atLeast(Duration.ofSeconds(20))
                 .untilAsserted(() -> {
+
+                    // Capture TaskGroupQueue records during execution since they are deleted after task completion.
+                    repository.queryAllInQueueTaskGroupQueue().forEach(taskGroupQueue -> {
+                        taskGroupQueueMap.put(taskGroupQueue.getId(), taskGroupQueue);
+                    });
```
Comment (ruanwenjun) [inline dolphinscheduler-master/src/test/java/org/apache/dolphinscheduler/server/master/integration/cases/WorkflowStartTestCase.java]: It's better to remove this assertion, this might easily failure. If we want to do this assertion we should avoid  delete this in db in ci.

Comment (KwongHing) [reply dolphinscheduler-master/src/test/java/org/apache/dolphinscheduler/server/master/integration/cases/WorkflowStartTestCase.java]: I sincerely apologize. I realize that due to my limited experience with IT case writing, this issue has taken up more of your valuable time than it should have. I’d like to request that this bug be reassigned to someone more experienced to handle it properly.

Comment (ruanwenjun) [reply dolphinscheduler-master/src/test/java/org/apache/dolphinscheduler/server/master/integration/cases/WorkflowStartTestCase.java]: I think you should remove these code related to `taskGroupQueueMap` and remove the method `queryAllInQueueTaskGroupQueue`, this PR can be merged.

Comment (KwongHing) [reply dolphinscheduler-master/src/test/java/org/apache/dolphinscheduler/server/master/integration/cases/WorkflowStartTestCase.java]: Do you mean I should delete my changes to the four files under the `dolphinscheduler-master/src/test `directory?

Comment (ruanwenjun) [reply dolphinscheduler-master/src/test/java/org/apache/dolphinscheduler/server/master/integration/cases/WorkflowStartTestCase.java]: @KwongHing I have updated your branch.

Comment (KwongHing) [reply dolphinscheduler-master/src/test/java/org/apache/dolphinscheduler/server/master/integration/cases/WorkflowStartTestCase.java]: Thank you so much for your review, and sorry for taking up your time.

Comment (KwongHing) [reply dolphinscheduler-master/src/test/java/org/apache/dolphinscheduler/server/master/integration/cases/WorkflowStartTestCase.java]: I ran the IT case `testStartWorkflow_with_oneFailedTaskWithRetryUsingTaskGroup` locally, but it failed. I checked the code and noticed that the `taskGroupPriority` field is annotated with `@TableField(exist = false)`, and the `queryTaskInstance` method doesn’t load it. Could it be an issue with the way I’m running it locally?
image

**Review by SbloodyS — DISMISSED** [review]

**Review by ruanwenjun — DISMISSED** [review]
LGTM

**Review by SbloodyS — APPROVED** [review]

**Review by ruanwenjun — APPROVED** [review]
LGTM
