### PR TITLE
[FIX-BUG][Master] Parallel tasks would be Irregularly submitted twice

### LINKED ISSUE #6279: [Bug] [Master] Parallel tasks would be Irregularly submitted twice
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

parallels tasks in one DAG, run the dag, the tasks would  be Irregularly submitted twice.

### What you expected to happen

tasks in one DAG should be submitted once.

### How to reproduce

10 parallel tasks in one DAG.
run the DAG,
find the tasks submit history, you would find some tasks are submitted twice.

### Anything else

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by lenboo**
close #6279  Parallel tasks would be Irregularly submitted twice

There is a thread conflict between submitting the start task and event handling.
So i set 'isStart' flag when the start nodes are submitted completely.

### CODE REVIEW

**Review by brave-lee — COMMENTED** [review]
+1

File: dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteThread.java [hunk 1]
```diff
@@ -460,10 +474,12 @@ private boolean needComplementProcess() {
     }
 
     private void startProcess() throws Exception {
-        buildFlowDag();
         if (this.taskInstanceHashMap.size() == 0) {
+            isStart = false;
```
Comment (CalvinKirs) [inline dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteThread.java:478]: The assignment here is not need

Comment (lenboo) [reply dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteThread.java:478]: In the complement scenario,   the 'start process' will run multiple times.

**Review by CalvinKirs — APPROVED** [review]
