### PR TITLE
[Improvement-1360]: Fix Description length check

### LINKED ISSUE #11373: [Bug] [Api]  Content Center - File Management creates folders, uses extra-long descriptions, and reports an error message that the resource already exists, which does not match the actual problem
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Submission errors will be returned.
183333684-d476a688-67be-47c4-a200-be3c663ee379

### What you expected to happen

Description length check。

### How to reproduce

Enter long string

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### LINKED ISSUE #11374: [Improvement][Module Name] Improvement title
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

The length of some description fields is inconsistent. For example, the length of the description field in table "t_ds_project" and table "t-ds_worker_group" is 200, but the length of the description field in other tables is 255.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Zephyrcf**
## Purpose of the pull request
close https://github.com/apache/dolphinscheduler/issues/11373
close https://github.com/apache/dolphinscheduler/issues/11374

## Brief change log
Fix Description length check

## Verify this pull request
This pull request is already covered by existing tests, such as (please describe tests).

### CODE REVIEW

**Comment by caishunfeng** [comment]
> warning This PR do not change database DDL synchronize.

should change the h2 sql file too.

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/BaseServiceImpl.java [hunk 1]
```diff
@@ -212,4 +212,9 @@ public Map<String, Object> checkAndParseDateParameters(String startDateStr, Stri
         putMsg(result, Status.SUCCESS);
         return result;
     }
+
+    @Override
+    public boolean checkDescriptionLength(String description) {
+        return description!=null && description.codePointCount(0, description.length()) > 255;
```
Comment (caishunfeng) [inline dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/BaseServiceImpl.java:218]: why not just use description.length() > 255?

Comment (Zephyrcf) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/BaseServiceImpl.java:218]: MySQL：In contrast to CHAR, VARCHAR values are stored as a 1-byte or 2-byte length prefix plus data. The length prefix indicates the number of bytes in the value. A column uses one length byte if values require no more than 255 bytes, two length bytes if values may require more than 255 bytes.
Because more than 256 will apply for additional space, lock the table, and then add new fields, it will definitely affect the database performance in the case of high concurrency.

**Review by caishunfeng — DISMISSED** [review]
LGTM if CI pass

**Review by SbloodyS — DISMISSED** [review]
+1

**Comment by SbloodyS** [comment]
@insist777 Hi, please resolve conficts.

**Comment by Zephyrcf** [comment]
> @insist777 Hi, please resolve conficts.

Well, it's been settled

**Review by SbloodyS — APPROVED** [review]
