### PR TITLE
Clear the task group data when delete a project/workflowInstance

### LINKED ISSUE #13382: [Improvement] [TaskGroup] TaskGroup cannot be delete
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When we create a task group, the task group cannot be deleted.

And after we delete the project, the task group will never be used, since the task group should belong to a project.

### What you expected to happen

When we delete a project we should delete the taskGroup which belongs to the project.
When we delete a workflow instance, we should delete the taskGroupQueue which belongs to the workflow instances.

### How to reproduce

1. Create a Project
2. Create a task group, choose the project.
3. Use task group and start a workflow 
4. Delete the workflow instance, see the task group queue data is still in database.
5. Delete the project, see the task group is still in database.

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by ruanwenjun**
## Purpose of the pull request

fix #13382

## Brief change log

- Delete the taskGroupQueue data when delete a workflow instance
- Delete the taskGroup data when delete a project

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProjectServiceImpl.java [hunk 1]
```diff
@@ -74,6 +76,10 @@ public class ProjectServiceImpl extends BaseServiceImpl implements ProjectServic
 
     private static final Logger logger = LoggerFactory.getLogger(ProjectServiceImpl.class);
 
+    @Lazy
```
Comment (caishunfeng) [inline dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProjectServiceImpl.java:79]: can we avoid to use this annotation?

**Review by caishunfeng — APPROVED** [review]
nip

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProjectServiceImpl.java (hunk 1 above)
Comment (ruanwenjun) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProjectServiceImpl.java:79]: After split the process service we can remove @Lazy
