### PR TITLE
[Fix-17838][Bug] [ApiServer] Remove WAIT_TO_RUN and add FAILOVER while querying workflow instances

### LINKED ISSUE #17838: [Bug] [ApiServer] An error occurs when selecting the "Waiting to Run" status while querying workflow instances.
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

 An error occurs when selecting the "Waiting to Run" status while querying workflow instances.

Image

### What you expected to happen

The status of workflow instances no longer includes "Waiting to Run"

### How to reproduce

select the "Waiting to Run" status while querying workflow instances.

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by njnu-seafish**
## Purpose of the pull request

close #17838 

## Brief change log

Remove WAIT_TO_RUN and add FAILOVER while querying workflow instances

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

## Pull Request Notice
[Pull Request Notice](https://github.com/apache/dolphinscheduler/blob/dev/docs/docs/en/contribute/join/pull-request.md)

If your pull request contains incompatible change, you should also add it to `docs/docs/en/guide/upgrade/incompatible.md`

### CODE REVIEW

**Review by SbloodyS — DISMISSED** [review]
LGTM

File: dolphinscheduler-ui/src/locales/zh_CN/home.ts [hunk 1]
```diff
@@ -39,6 +39,5 @@ export default {
   dispatch: '派发',
   ready_block: '准备阻断',
   block: '阻断',
-  wait_to_run: '等待执行',
```
Comment (ruanwenjun) [inline dolphinscheduler-ui/src/locales/zh_CN/home.ts:42]: Could you please remove the other unused state, e.g. `block`, `ready_block`, `waiting_thread`....

Comment (njnu-seafish) [reply dolphinscheduler-ui/src/locales/zh_CN/home.ts:42]: > Could you please remove the other unused state, e.g. `block`, `ready_block`, `waiting_thread`....

ok, I will test in my env firstly.

**Review by SbloodyS — COMMENTED** [review]
You should run `pnpm run lint` to fix CI. @njnu-seafish

File: dolphinscheduler-ui/src/locales/zh_CN/home.ts (hunk 1 above)
Comment (njnu-seafish) [reply dolphinscheduler-ui/src/locales/zh_CN/home.ts:42]: In this PR, can I remove other redundant Java code and improve the documentation (DOC) for better accuracy?   Or should I create a separate PR to handle this instead?

> public class CommandKeyConstants {

        public static final String CMD_PARAM_RECOVERY_WAITING_THREAD = "WaitingThreadInstanceId";

> docs/docs/en/contribute/architecture-design.md
start execution from failed node, complement, timer, rerun, pause, stop, resume waiting thread.

**Comment by njnu-seafish** [comment]
> You should run `pnpm run lint` to fix CI. @njnu-seafish

ok, I'm hearing about this for the first time—I'm an amateur frontend developer.

File: dolphinscheduler-ui/src/views/projects/components/dependencies/dependencies-modal.tsx [hunk 2]
```diff
@@ -59,7 +59,7 @@ export default defineComponent({
     }
 
     const cancelToHandle = () => {
-      ctx.emit('update:show', showRef)
+      ctx.emit('update:show', showRef.value)
```
Comment (SbloodyS) [inline dolphinscheduler-ui/src/views/projects/components/dependencies/dependencies-modal.tsx]: Why change this?

Comment (njnu-seafish) [reply dolphinscheduler-ui/src/views/projects/components/dependencies/dependencies-modal.tsx]: > Why change this?

This wasn't modified by me; it was directly modified by this command: pnpm run lint

Comment (SbloodyS) [reply dolphinscheduler-ui/src/views/projects/components/dependencies/dependencies-modal.tsx]: `pnpm run lint` would not add this. It's just a formatting tool.

Comment (njnu-seafish) [reply dolphinscheduler-ui/src/views/projects/components/dependencies/dependencies-modal.tsx]: > `pnpm run lint` would not add this. It's just a formatting tool.

dolphinscheduler-ui/package.json
"lint": "eslint src --fix --ext .ts,.tsx,.vue"

Comment (SbloodyS) [reply dolphinscheduler-ui/src/views/projects/components/dependencies/dependencies-modal.tsx]: `eslint src --fix` this command will not increase your code, but will only fix the format.

File: dolphinscheduler-ui/src/locales/zh_CN/home.ts (hunk 1 above)
Comment (SbloodyS) [reply dolphinscheduler-ui/src/locales/zh_CN/home.ts:42]: You should create a separate PR.

**Review by SbloodyS — APPROVED** [review]
LGTM

**Review by zhongjiajie — APPROVED** [review]

**Review by Gallardot — APPROVED** [review]
