### PR TITLE
[Fix-4862][Server] Kill yarn application command won't be execute whe…

### LINKED ISSUE #4862: [Bug][Server] Kill yarn application command won't be execute when kill error
**For better global communication, Please describe it in English. If you feel the description in English is not clear, then you can append description in Chinese(just for Mandarin(CN)), thx! **
**Describe the bug**
There are two places used 'yarn application -kill',and both of them are in try catch.So if these is some exception in OSUtils.exeCmd(cmd), kill yarn application command won't be execute

**To Reproduce**
Steps to reproduce the behavior, for example:

**Expected behavior**

**Screenshots**
image
image
image

**Which version of Dolphin Scheduler:**
 -[dev][release-1.3.5]

**Additional context**

**Requirement or improvement**
- Please describe about your requirements or improvement suggestions.

### PR DESCRIPTION
**Pull request by dddyszy**
…n kill error

## *Tips*
- *Thanks very much for contributing to Apache DolphinScheduler.*
- *Please review https://dolphinscheduler.apache.org/en-us/community/development/pull-request.html before opening a pull request.*

## What is the purpose of the pull request
fix #4862 

## Brief change log
move kill yarn command out of try...catch

## Verify this pull request

*(Please pick either of the following options)*

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

*(example:)*

  - *Added dolphinscheduler-dao tests for end-to-end.*
  - *Added CronUtilsTest to verify the change.*
  - *Manually verified the change by testing locally.*

### CODE REVIEW

File: dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/processor/TaskKillProcessor.java [hunk 1]
```diff
@@ -128,18 +128,15 @@ public void process(Channel channel, Command command) {
...
         } catch (Exception e) {
             logger.error("kill task error", e);
         }
-        return Pair.of(false, appIds);
+        // find log and kill yarn job
+        appIds = killYarnJob(Host.of(taskExecutionContext.getHost()).getIp(),
+                taskExecutionContext.getLogPath(),
+                taskExecutionContext.getExecutePath(),
+                taskExecutionContext.getTenantCode());
+        return Pair.of(true, appIds);
```
Comment (zhuangchong) [inline dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/processor/TaskKillProcessor.java]: All kill exceptions are considered successful?

Comment (dddyszy) [reply dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/processor/TaskKillProcessor.java]: i found that problem,and i think process kill error return false,and yarn application kill error might be ignored

File: dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/processor/TaskKillProcessor.java [hunk 2]
```diff
@@ -128,18 +129,16 @@ public void process(Channel channel, Command command) {
...
+            flag = false;
             logger.error("kill task error", e);
         }
-        return Pair.of(false, appIds);
+        // find log and kill yarn job
+        appIds = killYarnJob(Host.of(taskExecutionContext.getHost()).getIp(),
+                taskExecutionContext.getLogPath(),
+                taskExecutionContext.getExecutePath(),
+                taskExecutionContext.getTenantCode());
+        return Pair.of(flag, appIds);
```
Comment (CalvinKirs) [inline dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/processor/TaskKillProcessor.java]: The killYarnJob operation is not absolutely successful

File: dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/processor/TaskKillProcessor.java [hunk 3]
```diff
@@ -192,12 +196,13 @@ private TaskKillResponseCommand buildKillTaskResponseCommand(TaskKillRequestComm
             }
         } catch (Exception e) {
             logger.error("kill yarn job error", e);
+            throw new RuntimeException("kill yarn job error");
```
Comment (CalvinKirs) [inline dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/processor/TaskKillProcessor.java]: Throwing an exception does not seem to be a good way to deal with it. Maybe it would be better if the return parameter of this method is Pair<Boolean, List<String>>

**Review by CalvinKirs — APPROVED** [review]
LGTM

**Comment by CalvinKirs** [comment]
looks good to me, please take a look @zhuangchong

File: dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/utils/ProcessUtils.java [hunk 4]
```diff
@@ -59,7 +59,7 @@
     /**
      * Expression of PID recognition in Windows scene
      */
-    private static final Pattern WINDOWSATTERN = Pattern.compile("(\\d+)");
+    private static final Pattern WINDOWSATTERN = Pattern.compile("\\((\\d+)\\)");
```
Comment (zhuangchong) [inline dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/utils/ProcessUtils.java]: There is a problem with the regular expression, please check.

image

Comment (dddyszy) [reply dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/utils/ProcessUtils.java]: image
test result is like this,not contains "()".and if the threads should be excluded, "\w+\\\\((\d+)\\\\)" take effect，just like this
image
if you think the second one make sense,i'll fix it

Comment (zhuangchong) [reply dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/utils/ProcessUtils.java]: I think it should be the second one, but I checked the regularization, and the result is not correct

image

Comment (dddyszy) [reply dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/utils/ProcessUtils.java]: matcher.group returns the match string in (), website regex utils find the whole match string,they are not the same.You can try it in java code

**Comment by zhuangchong** [comment]
LGTM
