### PR TITLE
[Fix-10103][k8s]Fix k8s Change DataSource Error

### LINKED ISSUE #10103: [Bug] [deploy on k8s]   SPRING_DATASOURCE_DRIVER_CLASS_NAME need add in  templates/_helpers.tpl
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

[Bug] [deploy on k8s]   SPRING_DATASOURCE_DRIVER_CLASS_NAME need add in  templates/_helpers.tpl

### What you expected to happen

[Bug] [deploy on k8s]   SPRING_DATASOURCE_DRIVER_CLASS_NAME need add in  templates/_helpers.tpl

### How to reproduce

[Bug] [deploy on k8s]   SPRING_DATASOURCE_DRIVER_CLASS_NAME need add in  templates/_helpers.tpl

### Anything else

[Bug] [deploy on k8s]   SPRING_DATASOURCE_DRIVER_CLASS_NAME need add in  templates/_helpers.tpl

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by qingwli**
close #10103

### CODE REVIEW

**Comment by qingwli** [comment]
PTAL @kezhenxu94 @SbloodyS

**Review by SbloodyS — DISMISSED** [review]
LGTM

**Comment by qingwli** [comment]
Don't merge, still has bug

**Comment by qingwli** [comment]
When we define the ```-Dspring.profiles.active=upgrade``` and will still use the ```Mysql``` yaml and ```postgresql``` is not working

File: dolphinscheduler-alert/dolphinscheduler-alert-server/src/main/bin/start.sh [hunk 1]
```diff
@@ -19,11 +19,11 @@
 BIN_DIR=$(dirname $0)
 DOLPHINSCHEDULER_HOME=${DOLPHINSCHEDULER_HOME:-$(cd $BIN_DIR/..; pwd)}
 
-source "$DOLPHINSCHEDULER_HOME/conf/dolphinscheduler_env.sh"
 
 JAVA_OPTS=${JAVA_OPTS:-"-server -Duser.timezone=${SPRING_JACKSON_TIME_ZONE} -Xms1g -Xmx1g -Xmn512m -XX:+PrintGCDetails -Xloggc:gc.log -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=dump.hprof"}
 
 if [[ "$DOCKER" == "true" ]]; then
+  source "$DOLPHINSCHEDULER_HOME/conf/dolphinscheduler_env.sh"
```
Comment (SbloodyS) [inline dolphinscheduler-alert/dolphinscheduler-alert-server/src/main/bin/start.sh]: This may cause start error in cluster mode.

Comment (qingwli) [reply dolphinscheduler-alert/dolphinscheduler-alert-server/src/main/bin/start.sh]: This line maybe in ```if [[ "$DOCKER" != "true" ]]; then```

**Comment by qingwli** [comment]
~~If we defined the ```SPRING_DATASOURCE_DRIVER_CLASS_NAME``` in ```deploy/kubernetes/dolphinscheduler/templates/_helpers.tpl```, and do we need to define this in ```pom.xml```?~~
```
# Override by profile

---
spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dolphinscheduler?useUnicode=true&characterEncoding=UTF-8
```

~~Because in my mind, activate profile only defines the ```driver-class-name:```. We define this field in the k8s config file && Docker starts cmd , and Cluster Mode will source dolphinscheduler_env.sh.~~

~~WDYT?~~

**Comment by qingwli** [comment]
Holding, still need update

**Comment by qingwli** [comment]
PTAL @kezhenxu94  @SbloodyS @caishunfeng

File: dolphinscheduler-worker/src/main/resources/application.yaml [hunk 2]
```diff
@@ -89,3 +89,13 @@ management:
...
+
+# Override by profile
+
+---
+spring:
+  config:
+    activate:
+      on-profile: mysql
+  datasource:
+    driver-class-name: com.mysql.jdbc.Driver
```
Comment (kezhenxu94) [inline dolphinscheduler-worker/src/main/resources/application.yaml:101]: Also add the postgresql part ?

```yaml
---
 spring:
   config:
     activate:
       on-profile: postgresql
   datasource:
     driver-class-name: org.postgresql.Driver
```

Comment (qingwli) [reply dolphinscheduler-worker/src/main/resources/application.yaml:101]: Don't need, it because the other YAML file's default is PostgreSQL. Only the tools module needs to define Mysql && PostgreSQL part. Due [this](https://github.com/apache/dolphinscheduler/pull/9997/files#diff-eed87c5c23a714652182ddde16029973958176002fea3b59fb8ec4d359a33893R28)

Comment (kezhenxu94) [reply dolphinscheduler-worker/src/main/resources/application.yaml:101]: Oh right

**Review by kezhenxu94 — APPROVED** [review]

**Comment by zhongjiajie** [comment]
I think we should change milestone to `3.0.0-beta-1` WDYT @caishunfeng

**Comment by caishunfeng** [comment]
> I think we should change milestone to `3.0.0-beta-1` WDYT @caishunfeng

Yes, agree with you.
