### PR TITLE
[Fix-17604][API] Correct logic for assigning and remove worker groups to project

### LINKED ISSUE #17604: [Bug] [api-server] Worker group cannot be assigned to a project
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When I assigned a workgroup to a project, it prompted me: Failed to assign a workgroup to the project

Image

Image

api-server log

Image

2025-10-27 15:04:22.235 ERROR [qtp767266208-12279] o.a.d.a.s.i.ProjectWorkerGroupRelationServiceImpl:[143] - Failed to delete worker groups [[worker-240.118]] for the project [运维].
2025-10-27 15:04:22.235 ERROR [qtp767266208-12279] o.a.d.a.e.ApiExceptionHandler:[40] - org.apache.dolphinscheduler.api.controller.ProjectWorkerGroupController#assignWorkerGroups[3 args] Meet a ServiceException: 给项目分配工作组失败

but, if i create a new project ,  can assign

2025-10-27 15:05:28.525 INFO  [qtp767266208-12436] o.a.d.a.s.i.ProjectServiceImpl:[134] - Project is created and id is :7
2025-10-27 15:05:32.122 INFO  [qtp767266208-12308] o.a.d.a.s.i.ProjectWorkerGroupRelationServiceImpl:[141] - Success to delete worker groups [[default, worker-240.118, Linux-prod, worker-10.10.243.142]] for the project [测试] .
2025-10-27 15:05:32.124 INFO  [qtp767266208-12308] o.a.d.a.s.i.ProjectWorkerGroupRelationServiceImpl:[155] - Success to add worker group [default] for the project [测试] .
2025-10-27 15:05:32.124 INFO  [qtp767266208-12308] o.a.d.a.s.i.ProjectWorkerGroupRelationServiceImpl:[155] - Success to add worker group [worker-240.118] for the project [测试] .
2025-10-27 15:05:32.125 INFO  [qtp767266208-12308] o.a.d.a.s.i.ProjectWorkerGroupRelationServiceImpl:[155] - Success to add worker group [Linux-prod] for the project [测试] .
2025-10-27 15:05:32.125 INFO  [qtp767266208-12308] o.a.d.a.s.i.ProjectWorkerGroupRelationServiceImpl:[155] - Success to add worker group [worker-10.10.243.142] for the project [测试] .

### What you expected to happen

I have no idea

### How to reproduce

assigned a worker group to project, 

### Anything else

_No response_

### Version

3.3.1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Mrhs121**
…roject

## Purpose of the pull request
close https://github.com/apache/dolphinscheduler/issues/17604

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

## Pull Request Notice
[Pull Request Notice](https://github.com/apache/dolphinscheduler/blob/dev/docs/docs/en/contribute/join/pull-request.md)

If your pull request contains incompatible change, you should also add it to `docs/docs/en/guide/upgrade/incompatible.md`

### CODE REVIEW

**Comment by Mrhs121** [comment]
@ruanwenjun cc, please help review it when you have time, thank you.

**Review by SbloodyS — CHANGES_REQUESTED** [review]
This issue has been assigned to someone else. Please reply to the assignment in the issue first next time.

You should add these test cases in `ProjectE2ETest`

**Comment by Mrhs121** [comment]
> This issue has been assigned to someone else. Please reply to the assignment in the issue first next time.
> 
> You should add these test cases in `ProjectE2ETest`

Ok, the test cases have already been added to ProjectE2ETest.

File: dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/cases/ProjectE2ETest.java [hunk 1]
```diff
@@ -69,6 +76,23 @@ void testAssignWorkerGroup() {
...
+            browser.navigate().refresh();
+            assertThat(workerGroupPage.workerGroupList())
+                    .as("workerGroup list should contain newly-created workerGroup")
+                    .extracting(WebElement::getText)
+                    .anyMatch(it -> it.contains(workerGroupTest));
+        });
+
+        ProjectPage backToProjectPage = new ProjectPage(browser).goToNav(ProjectPage.class);
+        backToProjectPage.assignWorkerGroup(project, workerGroupTest);
+        backToProjectPage.verifyAssignedWorkerGroup(project, workerGroupTest);
```
Comment (SbloodyS) [inline dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/cases/ProjectE2ETest.java]: It should be a new test case. And we should put test logic into `ProjectPage`

Comment (Mrhs121) [reply dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/cases/ProjectE2ETest.java]: Done.

**Review by SbloodyS — APPROVED** [review]
LGTM

**Review by ruanwenjun — APPROVED** [review]
LGTM
