### PR TITLE
[Bug][Worker] Fix sql/shell task doesn't replace parameter

### LINKED ISSUE #14869: [Bug] [API] Global and local parameters are not replaced with XX value in SQL/SHELL components
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

1、create process  ”test0907“ && add shell components ”echo ${dt}" 
2、add global parameter： name：“dt”，value：“$[yyyy-MM-dd]” && save process
3、run this process，view logs after finished

### What you expected to happen

Global and local parameters can be replaced correctly.

### How to reproduce

eg. "what happened"
image
image
image

### Anything else

_No response_

### Version

3.2.0-prepare

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by zhongjiajie**
## Brief change log

Fix parameter assign error, fix #14869 which including
* shell task param not work, botch local and global
* others task chain assign not work

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

File: dolphinscheduler-task-plugin/dolphinscheduler-task-shell/src/main/java/org/apache/dolphinscheduler/plugin/task/shell/ShellTask.java [hunk 1]
```diff
@@ -81,7 +81,7 @@ public void init() {
     public void handle(TaskCallBack taskCallBack) throws TaskException {
         try {
             IShellInterceptorBuilder<?, ?> shellActuatorBuilder = ShellInterceptorBuilderFactory.newBuilder()
-                    .properties(ParameterUtils.convert(shellParameters.getLocalParametersMap()))
+                    .properties(ParameterUtils.convert(taskExecutionContext.getPrepareParamsMap()))
```
Comment (ruanwenjun) [inline dolphinscheduler-task-plugin/dolphinscheduler-task-shell/src/main/java/org/apache/dolphinscheduler/plugin/task/shell/ShellTask.java:84]: Does this change will loss local parameters?

Comment (zhongjiajie) [reply dolphinscheduler-task-plugin/dolphinscheduler-task-shell/src/main/java/org/apache/dolphinscheduler/plugin/task/shell/ShellTask.java:84]: it will not, `taskExecutionContext.getPrepareParamsMap()` including all parameter, such as startup param, global param, and local's

Comment (ruanwenjun) [reply dolphinscheduler-task-plugin/dolphinscheduler-task-shell/src/main/java/org/apache/dolphinscheduler/plugin/task/shell/ShellTask.java:84]: If so this PR LGTM, but the method is strange, I will guess if there exists a prepare parameter type.

File: dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/expand/CuringParamsServiceImpl.java [hunk 2]
```diff
@@ -69,8 +70,13 @@ public class CuringParamsServiceImpl implements CuringParamsService {
     private ProjectParameterMapper projectParameterMapper;
 
     @Override
-    public String convertParameterPlaceholders(String val, Map<String, String> allParamMap) {
-        return ParameterUtils.convertParameterPlaceholders(val, allParamMap);
+    public String convertParameterPlaceholders(String val, Map<String, Property> allParamMap) {
+        Map<String, String> paramMap = allParamMap
+                .entrySet()
+                .stream()
+                .filter(entry -> nonNull(entry.getValue().getValue()))
```
Comment (ruanwenjun) [inline dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/expand/CuringParamsServiceImpl.java:77]: I am not clear if we need to filter the null here.

**Review by ruanwenjun — APPROVED** [review]
LGTM

File: dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/expand/CuringParamsServiceImpl.java (hunk 2 above)
Comment (zhongjiajie) [reply dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/expand/CuringParamsServiceImpl.java:77]: seems we have some NPE in some buildint parameter
