### PR TITLE
[Bug] [Common] update IPv4 Pattern

### LINKED ISSUE #11758: [Bug] [Common] IPv4 Pattern is wrong.
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

IPv4 Pattern is not correct.
image
image

### What you expected to happen

can check invaild IPv4

### How to reproduce

just add some wrong IP to test UT

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by DarkAssassinator**
## Purpose of the pull request

fix #11758 

## Brief change log

just update IPv4 Pattern

## Verify this pull request

add some UT

### CODE REVIEW

**Review by davidzollo — DISMISSED** [review]
+1
Looks good to me, if you can increase coverage will be better

> # [Codecov](https://codecov.io/gh/apache/dolphinscheduler/pull/11762?src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=The+Apache+Software+Foundation) Report
> > Merging [#11762](https://codecov.io/gh/apache/dolphinscheduler/pull/11762?src=pr&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=The+Apache+Software+Foundation) ([6b6da12](https://github.com/apache/dolphinscheduler/commit/6b6da1222f1201ca2d2e5ea3aebf037a9621bef3)) into [dev](https://codecov.io/gh/apache/dolphinscheduler/commit/d0f5e7edf34a71e31bd2f5fa376bf235b395ec7d?el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=The+Apache+Software+Foundation) ([d0f5e7e](https://github.com/apache/dolphinscheduler/commit/d0f5e7edf34a71e31bd2f5fa376bf235b395ec7d)) will **decrease** coverage by `0.12%`.
> > The diff coverage is `100.00%`.
> 
> ```diff
> @@             Coverage Diff              @@
> ##                dev   #11762      +/-   ##
> ============================================
> - Coverage     39.73%   39.60%   -0.13%     
> + Complexity     4709     4691      -18     
> ============================================
>   Files          1008     1014       +6     
>   Lines         37878    37937      +59     
>   Branches       4238     4244       +6     
> ============================================
> - Hits          15049    15026      -23     
> - Misses        21218    21305      +87     
> + Partials       1611     1606       -5     
> ```
> 
> [Impacted Files](https://codecov.io/gh/apache/dolphinscheduler/pull/11762?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=The+Apache+Software+Foundation)	Coverage Δ	
> [...apache/dolphinscheduler/common/utils/NetUtils.java](https://codecov.io/gh/apache/dolphinscheduler/pull/11762/diff?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=The+Apache+Software+Foundation#diff-ZG9scGhpbnNjaGVkdWxlci1jb21tb24vc3JjL21haW4vamF2YS9vcmcvYXBhY2hlL2RvbHBoaW5zY2hlZHVsZXIvY29tbW9uL3V0aWxzL05ldFV0aWxzLmphdmE=)	`50.70% <100.00%> (+0.34%)`	⬆️
> [...eduler/server/worker/task/WorkerHeartBeatTask.java](https://codecov.io/gh/apache/dolphinscheduler/pull/11762/diff?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=The+Apache+Software+Foundation#diff-ZG9scGhpbnNjaGVkdWxlci13b3JrZXIvc3JjL21haW4vamF2YS9vcmcvYXBhY2hlL2RvbHBoaW5zY2hlZHVsZXIvc2VydmVyL3dvcmtlci90YXNrL1dvcmtlckhlYXJ0QmVhdFRhc2suamF2YQ==)	`68.08% <0.00%> (-8.52%)`	⬇️
> [...inscheduler/server/log/LoggerRequestProcessor.java](https://codecov.io/gh/apache/dolphinscheduler/pull/11762/diff?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=The+Apache+Software+Foundation#diff-ZG9scGhpbnNjaGVkdWxlci1sb2ctc2VydmVyL3NyYy9tYWluL2phdmEvb3JnL2FwYWNoZS9kb2xwaGluc2NoZWR1bGVyL3NlcnZlci9sb2cvTG9nZ2VyUmVxdWVzdFByb2Nlc3Nvci5qYXZh)	`17.30% <0.00%> (-0.52%)`	⬇️
> [...nscheduler/service/process/ProcessServiceImpl.java](https://codecov.io/gh/apache/dolphinscheduler/pull/11762/diff?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=The+Apache+Software+Foundation#diff-ZG9scGhpbnNjaGVkdWxlci1zZXJ2aWNlL3NyYy9tYWluL2phdmEvb3JnL2FwYWNoZS9kb2xwaGluc2NoZWR1bGVyL3NlcnZpY2UvcHJvY2Vzcy9Qcm9jZXNzU2VydmljZUltcGwuamF2YQ==)	`31.67% <0.00%> (-0.12%)`	⬇️
> [.../org/apache/dolphinscheduler/api/enums/Status.java](https://codecov.io/gh/apache/dolphinscheduler/pull/11762/diff?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=The+Apache+Software+Foundation#diff-ZG9scGhpbnNjaGVkdWxlci1hcGkvc3JjL21haW4vamF2YS9vcmcvYXBhY2hlL2RvbHBoaW5zY2hlZHVsZXIvYXBpL2VudW1zL1N0YXR1cy5qYXZh)	`100.00% <0.00%> (ø)`	
> [...e/dolphinscheduler/dao/entity/ProcessInstance.java](https://codecov.io/gh/apache/dolphinscheduler/pull/11762/diff?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=The+Apache+Software+Foundation#diff-ZG9scGhpbnNjaGVkdWxlci1kYW8vc3JjL21haW4vamF2YS9vcmcvYXBhY2hlL2RvbHBoaW5zY2hlZHVsZXIvZGFvL2VudGl0eS9Qcm9jZXNzSW5zdGFuY2UuamF2YQ==)	`0.00% <0.00%> (ø)`	
> [...cheduler/api/service/impl/ExecutorServiceImpl.java](https://codecov.io/gh/apache/dolphinscheduler/pull/11762/diff?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=The+Apache+Software+Foundation#diff-ZG9scGhpbnNjaGVkdWxlci1hcGkvc3JjL21haW4vamF2YS9vcmcvYXBhY2hlL2RvbHBoaW5zY2hlZHVsZXIvYXBpL3NlcnZpY2UvaW1wbC9FeGVjdXRvclNlcnZpY2VJbXBsLmphdmE=)	`37.91% <0.00%> (ø)`	
> [...r/api/service/impl/ProcessInstanceServiceImpl.java](https://codecov.io/gh/apache/dolphinscheduler/pull/11762/diff?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=The+Apache+Software+Foundation#diff-ZG9scGhpbnNjaGVkdWxlci1hcGkvc3JjL21haW4vamF2YS9vcmcvYXBhY2hlL2RvbHBoaW5zY2hlZHVsZXIvYXBpL3NlcnZpY2UvaW1wbC9Qcm9jZXNzSW5zdGFuY2VTZXJ2aWNlSW1wbC5qYXZh)	`60.85% <0.00%> (ø)`	
> [...server/master/runner/MasterSchedulerBootstrap.java](https://codecov.io/gh/apache/dolphinscheduler/pull/11762/diff?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=The+Apache+Software+Foundation#diff-ZG9scGhpbnNjaGVkdWxlci1tYXN0ZXIvc3JjL21haW4vamF2YS9vcmcvYXBhY2hlL2RvbHBoaW5zY2hlZHVsZXIvc2VydmVyL21hc3Rlci9ydW5uZXIvTWFzdGVyU2NoZWR1bGVyQm9vdHN0cmFwLmphdmE=)	`0.00% <0.00%> (ø)`	
> [...ache/dolphinscheduler/plugin/task/k8s/K8sTask.java](https://codecov.io/gh/apache/dolphinscheduler/pull/11762/diff?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=The+Apache+Software+Foundation#diff-ZG9scGhpbnNjaGVkdWxlci10YXNrLXBsdWdpbi9kb2xwaGluc2NoZWR1bGVyLXRhc2stazhzL3NyYy9tYWluL2phdmEvb3JnL2FwYWNoZS9kb2xwaGluc2NoZWR1bGVyL3BsdWdpbi90YXNrL2s4cy9LOHNUYXNrLmphdmE=)	`89.47% <0.00%> (ø)`	
> ... and [23 more](https://codecov.io/gh/apache/dolphinscheduler/pull/11762/diff?src=pr&el=tree-more&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=The+Apache+Software+Foundation)		
> 📣 We’re building smart automated test selection to slash your CI/CD build times. [Learn more](https://about.codecov.io/iterative-testing/?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=The+Apache+Software+Foundation)

File: dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/NetUtils.java [hunk 1]
```diff
@@ -42,7 +42,8 @@
  */
 public class NetUtils {
 
-    private static final Pattern IP_PATTERN = Pattern.compile("\\d{1,3}(\\.\\d{1,3}){3,5}$");
+    private static final Pattern IP_PATTERN = Pattern
```
Comment (ruanwenjun) [inline dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/NetUtils.java]: It's better to directly use `IPAddressUtil.isIPv4LiteralAddress()`.

**Review by ruanwenjun — CHANGES_REQUESTED** [review]

File: dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/NetUtils.java (hunk 1 above)
Comment (DarkAssassinator) [reply dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/NetUtils.java]: ohh, i agree with u.  I always thought that `IPAddressUtil.isIPv4LiteralAddress()` used the same pattern as DS, but just checked the source code again and found that the maximum value was also judged. i will update it later. thx.
image

Comment (DarkAssassinator) [reply dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/NetUtils.java]: done.

File: dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/utils/NetUtilsTest.java [hunk 2]
```diff
@@ -99,6 +99,21 @@ public void testIsValidAddress() {
...
         when(address.getHostAddress()).thenReturn("1.2.3.4");
         assertTrue(NetUtils.isValidV4Address(address));
+        address = mock(InetAddress.class);
+        when(address.getHostAddress()).thenReturn("1.2.3.4:80");
+        assertFalse(NetUtils.isValidV4Address(address));
+        address = mock(InetAddress.class);
+        when(address.getHostAddress()).thenReturn("256.0.0.1");
+        assertFalse(NetUtils.isValidV4Address(address));
+        address = mock(InetAddress.class);
+        when(address.getHostAddress()).thenReturn("127.1");
```
Comment (ruanwenjun) [inline dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/utils/NetUtilsTest.java]: '127.1' is a validated IpV4 
https://superuser.com/questions/614001/why-can-i-ping-127-1

**Review by ruanwenjun — CHANGES_REQUESTED** [review]

File: dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/utils/NetUtilsTest.java (hunk 2 above)
Comment (DarkAssassinator) [reply dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/utils/NetUtilsTest.java]: do we need to consider these unpopular IP formats? such as 127.1, 127.1.1

Comment (DarkAssassinator) [reply dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/utils/NetUtilsTest.java]: > '127.1' is a validated IpV4 https://superuser.com/questions/614001/why-can-i-ping-127-1

Hi @ruanwenjun , could we use `InetAddress.isReachable()` to define this IP? because Ipv4 has many format

Comment (ruanwenjun) [reply dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/utils/NetUtilsTest.java]: Use `IPAddressUtil.isIPv4LiteralAddress` is enough.

Comment (DarkAssassinator) [reply dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/utils/NetUtilsTest.java]: > Use `IPAddressUtil.isIPv4LiteralAddress` is enough.

OK. done

File: dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/NetUtils.java [hunk 3]
```diff
@@ -183,7 +182,7 @@
         }
         String name = address.getHostAddress();
         return (name != null
-                && IP_PATTERN.matcher(name).matches()
+                && IPAddressUtil.isIPv4LiteralAddress(name)
```
[the remark this answers is not in the document]
Comment (DarkAssassinator) [reply dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/NetUtils.java]: may replace it with `httpclient->org.apache.http.conn.util.InetAddressUtils` to support JDK8+

**Comment by DarkAssassinator** [comment]
`IPAddressUtil.isIPv4LiteralAddress` do not support JDK8+, need to replace with `InetAddressUtils.isIPv4Address`.

**Review by ruanwenjun — APPROVED** [review]
LGTM

**Comment by ruanwenjun** [comment]
Thanks for your patch, this will be released at 3.0.1+ and 3.1.0+.
