### PR TITLE
[Fix-9221] [alert-server] optimization and gracefully close

### LINKED ISSUE #9221: [Improvement] [alert-server] AlertSender optimization and gracefully close, such as MasterServer
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

In alert-server, I have two suggestions
- I think sending alert messages should go out to class of `AlertServer` independently, that it is mainly responsible for the send alert, we can define as `AlertSenderService`
- I think class of `AlertServer` should implements interface of `IStoppable`, and have gracefully close, such as MasterServer or WorkerServer

### Use case

_No response_

### Related issues

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by guoshupei**
This closes #9221

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

### CODE REVIEW

**Comment by guoshupei** [comment]
@caishunfeng Hi，can you help me? What is the reason for the failure of the `E2E/Tenant` check？And I don't have a valid Docker environment, so I am also failure of the `E2E/Tenant` check in local

**Comment by caishunfeng** [comment]
> @caishunfeng Hi，can you help me? What is the reason for the failure of the `E2E/Tenant` check？And I don't have a valid Docker environment, so I am also failure of the `E2E/Tenant` check in local

image
you can check the e2e detail log.

**Comment by guoshupei** [comment]
> > @caishunfeng Hi，can you help me? What is the reason for the failure of the `E2E/Tenant` check？And I don't have a valid Docker environment, so I am also failure of the `E2E/Tenant` check in local
> 
> image you can check the e2e detail log.

yes, I saw this error message, I have no problem starting locally, so `checkPluginDefineTableExist ` is passed, but I don't understand how it is verified on git, and I don't know how to solve it, I have no idea
image

**Comment by caishunfeng** [comment]
I had rerun the CI test.

**Comment by guoshupei** [comment]
OK，thanks，Compared with the correct one, I have some idea. I'll try again.

发自我的iPhone

**Comment by guoshupei** [comment]
Hi, @caishunfeng , finally succeeded, I replace `@Eventlistener` with `@PostConstruct` in `AlertServer`

**Comment by caishunfeng** [comment]
> SonarCloud Quality Gate failed.    [Quality Gate failed](https://sonarcloud.io/dashboard?id=apache-dolphinscheduler&pullRequest=9246)
> 
> [Bug](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=9246&resolved=false&types=BUG) [C](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=9246&resolved=false&types=BUG) [4 Bugs](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=9246&resolved=false&types=BUG) [Vulnerability](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=9246&resolved=false&types=VULNERABILITY) [A](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=9246&resolved=false&types=VULNERABILITY) [0 Vulnerabilities](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=9246&resolved=false&types=VULNERABILITY) [Security Hotspot](https://sonarcloud.io/project/security_hotspots?id=apache-dolphinscheduler&pullRequest=9246&resolved=false&types=SECURITY_HOTSPOT) [A](https://sonarcloud.io/project/security_hotspots?id=apache-dolphinscheduler&pullRequest=9246&resolved=false&types=SECURITY_HOTSPOT) [0 Security Hotspots](https://sonarcloud.io/project/security_hotspots?id=apache-dolphinscheduler&pullRequest=9246&resolved=false&types=SECURITY_HOTSPOT) [Code Smell](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=9246&resolved=false&types=CODE_SMELL) [A](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=9246&resolved=false&types=CODE_SMELL) [3 Code Smells](https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&pullRequest=9246&resolved=false&types=CODE_SMELL)
> 
> [](https://sonarcloud.io/component_measures?id=apache-dolphinscheduler&pullRequest=9246&metric=new_coverage&view=list) [56.6% Coverage](https://sonarcloud.io/component_measures?id=apache-dolphinscheduler&pullRequest=9246&metric=new_coverage&view=list) [](https://sonarcloud.io/component_measures?id=apache-dolphinscheduler&pullRequest=9246&metric=new_duplicated_lines_density&view=list) [5.9% Duplication](https://sonarcloud.io/component_measures?id=apache-dolphinscheduler&pullRequest=9246&metric=new_duplicated_lines_density&view=list)

Please take attention to snoar check.

**Comment by guoshupei** [comment]
Okay, thanks

发自我的iPhone

File: dolphinscheduler-alert/dolphinscheduler-alert-server/src/main/java/org/apache/dolphinscheduler/alert/AlertPluginManager.java [hunk 1]
```diff
@@ -53,25 +52,22 @@
...
+    private PluginDao pluginDao;
 
     private final Map<Integer, AlertChannel> channelKeyedById = new HashMap<>();
 
     private final PluginParams warningTypeParams = getWarningTypeParams();
 
-    public AlertPluginManager(PluginDao pluginDao) {
-        this.pluginDao = pluginDao;
-    }
-
```
Comment (zhuangchong) [inline dolphinscheduler-alert/dolphinscheduler-alert-server/src/main/java/org/apache/dolphinscheduler/alert/AlertPluginManager.java]: This part is a different spring injection method, it is not recommended to modify.

File: dolphinscheduler-alert/dolphinscheduler-alert-server/src/main/java/org/apache/dolphinscheduler/alert/AlertRequestProcessor.java [hunk 2]
```diff
@@ -36,11 +37,8 @@
 public final class AlertRequestProcessor implements NettyRequestProcessor {
     private static final Logger logger = LoggerFactory.getLogger(AlertRequestProcessor.class);
 
-    private final AlertSender alertSender;
-
-    public AlertRequestProcessor(AlertSender alertSender) {
-        this.alertSender = alertSender;
-    }
```
Comment (zhuangchong) [inline dolphinscheduler-alert/dolphinscheduler-alert-server/src/main/java/org/apache/dolphinscheduler/alert/AlertRequestProcessor.java]: same as previous question.

File: dolphinscheduler-alert/dolphinscheduler-alert-server/src/main/java/org/apache/dolphinscheduler/alert/AlertSenderService.java [hunk 3]
```diff
@@ -17,43 +17,60 @@
 
 package org.apache.dolphinscheduler.alert;
 
-import org.apache.dolphinscheduler.alert.api.AlertChannel;
-import org.apache.dolphinscheduler.alert.api.AlertConstants;
-import org.apache.dolphinscheduler.alert.api.AlertData;
-import org.apache.dolphinscheduler.alert.api.AlertInfo;
-import org.apache.dolphinscheduler.alert.api.AlertResult;
+import org.apache.commons.collections.CollectionUtils;
+import org.apache.dolphinscheduler.alert.api.*;
```
Comment (zhuangchong) [inline dolphinscheduler-alert/dolphinscheduler-alert-server/src/main/java/org/apache/dolphinscheduler/alert/AlertSenderService.java]: code style

File: dolphinscheduler-alert/dolphinscheduler-alert-server/src/main/java/org/apache/dolphinscheduler/alert/AlertSenderService.java [hunk 4]
```diff
@@ -17,43 +17,60 @@
...
+    private AlertDao alertDao;
 
-    private final AlertDao alertDao;
-    private final AlertPluginManager alertPluginManager;
+    @Autowired
+    private AlertPluginManager alertPluginManager;
 
-    public AlertSender(AlertDao alertDao, AlertPluginManager alertPluginManager) {
-        this.alertDao = alertDao;
-        this.alertPluginManager = alertPluginManager;
```
Comment (zhuangchong) [inline dolphinscheduler-alert/dolphinscheduler-alert-server/src/main/java/org/apache/dolphinscheduler/alert/AlertSenderService.java]: same as previous question.

**Review by zhuangchong — CHANGES_REQUESTED** [review]

File: dolphinscheduler-alert/dolphinscheduler-alert-server/src/main/java/org/apache/dolphinscheduler/alert/AlertServer.java [hunk 5]
```diff
@@ -17,73 +17,104 @@
...
 import org.springframework.boot.context.event.ApplicationReadyEvent;
 import org.springframework.context.annotation.ComponentScan;
 import org.springframework.context.event.EventListener;
 
+import javax.annotation.PostConstruct;
+
 @SpringBootApplication
 @ComponentScan("org.apache.dolphinscheduler")
-public class AlertServer implements Closeable {
+public class AlertServer implements IStoppable {
```
Comment (zhuangchong) [inline dolphinscheduler-alert/dolphinscheduler-alert-server/src/main/java/org/apache/dolphinscheduler/alert/AlertServer.java]: The stop method of IStoppable is called by a special check method, but it is not available in AlertServer.

**Review by zhuangchong — CHANGES_REQUESTED** [review]

File: dolphinscheduler-alert/dolphinscheduler-alert-server/src/main/java/org/apache/dolphinscheduler/alert/AlertSenderService.java (hunk 3 above)
Comment (guoshupei) [reply dolphinscheduler-alert/dolphinscheduler-alert-server/src/main/java/org/apache/dolphinscheduler/alert/AlertSenderService.java]: okay, thanks

File: dolphinscheduler-alert/dolphinscheduler-alert-server/src/main/java/org/apache/dolphinscheduler/alert/AlertServer.java (hunk 5 above)
Comment (guoshupei) [reply dolphinscheduler-alert/dolphinscheduler-alert-server/src/main/java/org/apache/dolphinscheduler/alert/AlertServer.java]: yes, you are right. The action of interface of `IStoppable`  is to stop by external trigger. such as `RegistryClient`, we can refer to master or worker. At present, `AlertServer` is  not distributed, and stop is not be used, but I think it should be reserved for distributed considerations.

**Comment by zhuangchong** [comment]
@guoshupei Please see the review above.

File: dolphinscheduler-alert/dolphinscheduler-alert-server/src/main/java/org/apache/dolphinscheduler/alert/AlertRequestProcessor.java (hunk 2 above)
Comment (guoshupei) [reply dolphinscheduler-alert/dolphinscheduler-alert-server/src/main/java/org/apache/dolphinscheduler/alert/AlertRequestProcessor.java]: same as previous answer

File: dolphinscheduler-alert/dolphinscheduler-alert-server/src/main/java/org/apache/dolphinscheduler/alert/AlertSenderService.java (hunk 4 above)
Comment (guoshupei) [reply dolphinscheduler-alert/dolphinscheduler-alert-server/src/main/java/org/apache/dolphinscheduler/alert/AlertSenderService.java]: same as previous answer

**Comment by guoshupei** [comment]
> 



> @guoshupei Please see the review above.

Hi, @zhuangchong, sorry, I am using it for the first time, not very familiar with the operation. I have already replied, it seems that you did not receive it. should I click the button of `Resolve conversation`?
image

**Comment by zhuangchong** [comment]
@guoshupei If it has been resolved, click the `Resolve conversation` button, but I did not see your reply on it. I see that there is a reply in the screenshot you sent, please check it.

image

File: dolphinscheduler-alert/dolphinscheduler-alert-server/src/main/java/org/apache/dolphinscheduler/alert/AlertPluginManager.java (hunk 1 above)
Comment (guoshupei) [reply dolphinscheduler-alert/dolphinscheduler-alert-server/src/main/java/org/apache/dolphinscheduler/alert/AlertPluginManager.java]: > This part is a different spring injection method, it is not recommended to modify.

yes, I know, first, this is constructor injection, and has the same effect as @Autowired, both are byType, secondly, keep the style consistent, such as master/worker. What do you think?

**Comment by guoshupei** [comment]
> @guoshupei If it has been resolved, click the `Resolve conversation` button, but I did not see your reply on it. I see that there is a reply in the screenshot you sent, please check it.
> 
> image


@zhuangchong, I know the reason, I need click `submit review` button in `View changes` page

File: dolphinscheduler-alert/dolphinscheduler-alert-server/src/main/java/org/apache/dolphinscheduler/alert/AlertPluginManager.java (hunk 1 above)
Comment (zhuangchong) [reply dolphinscheduler-alert/dolphinscheduler-alert-server/src/main/java/org/apache/dolphinscheduler/alert/AlertPluginManager.java]: I recommend keeping the original constructor injection and see what other small partners have suggestions.

File: dolphinscheduler-alert/dolphinscheduler-alert-server/src/main/java/org/apache/dolphinscheduler/alert/AlertServer.java (hunk 5 above)
Comment (zhuangchong) [reply dolphinscheduler-alert/dolphinscheduler-alert-server/src/main/java/org/apache/dolphinscheduler/alert/AlertServer.java]: You are right, I suggest that the `IStoppable` code and the AlertServer's distributed code are in one PR. If only `IStoppable` code was committed, then `stop` would be an issue during this period.

Comment (guoshupei) [reply dolphinscheduler-alert/dolphinscheduler-alert-server/src/main/java/org/apache/dolphinscheduler/alert/AlertServer.java]: > You are right, I suggest that the `IStoppable` code and the AlertServer's distributed code are in one PR. If only `IStoppable` code was committed, then `stop` would be an issue during this period.

Yes, i agree with you. I will remove `IStoppable` , at persent, I have no idea to complete the distribution of `AlertServer` , mainly because `WorkerServer` is directly connected to `AlertServer`

File: dolphinscheduler-alert/dolphinscheduler-alert-server/src/main/java/org/apache/dolphinscheduler/alert/AlertPluginManager.java (hunk 1 above)
Comment (guoshupei) [reply dolphinscheduler-alert/dolphinscheduler-alert-server/src/main/java/org/apache/dolphinscheduler/alert/AlertPluginManager.java]: > I recommend keeping the original constructor injection and see what other small partners have suggestions.

Okay,  i agree with you.

**Review by zhuangchong — APPROVED** [review]
+1
