### PR TITLE
[Fix-10842] Fix master/worker failover will cause status incorrect

### LINKED ISSUE #10842: [Bug] [Master] When worker down, some taskInstance has been dispatched may not be failovered.
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

I find some taskInstance may not be failovered when the worker down, and the taskInstance's status is DISPATCH.

When we do worker failover, we need to find out which taskInstances belong to the need failover worker, we use taskInstance's host to do this judge, if the taskInstance's host == needFailoveredWorker, then we may failover this task(We have extra judgement).

image

The problem is that when we success dispatch the taskInstance to a worker, the taskIntance's host may still null, if then the worker down, this taskInstance may not be failovered.
image

### What you expected to happen

The worker failover can work will.

### How to reproduce

image

Start some master and worker, and submit a lot of processInstance, then kill one worker. 

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by ruanwenjun**
## Purpose of the pull request

close #10842 
Fix master failover may not update task status

## Brief change log

- Split master failover and worker failover
- Fix worker failover may lost task due to host does update
- Fix master failover may cause the success task rerun again
- Add some failover log for troubleshooting

### CODE REVIEW

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/service/WorkerFailoverService.java [hunk 1]
```diff
@@ -0,0 +1,216 @@
+package org.apache.dolphinscheduler.server.master.service;
```
Comment (SbloodyS) [inline dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/service/WorkerFailoverService.java:18]: Missing license header.

**Comment by ruanwenjun** [comment]
@caishunfeng This PR is ready to review, please take a look.

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/dispatch/executor/NettyExecutorManager.java [hunk 2]
```diff
@@ -117,6 +117,7 @@ public Boolean execute(ExecutionContext context) throws ExecuteException {
                 doExecute(host, command);
                 success = true;
                 context.setHost(host);
+                context.getTaskInstance().setHost(host.getAddress());
```
Comment (caishunfeng) [inline dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/dispatch/executor/NettyExecutorManager.java:122]: It seems duplicated with ExecutorDispatcher.dispatch.

Comment (ruanwenjun) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/dispatch/executor/NettyExecutorManager.java:122]: Yes, I will remove the set host in ExecutorDispatcher.dispatch.

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/StateWheelExecuteThread.java [hunk 3]
```diff
@@ -296,15 +296,19 @@ private void checkTask4Retry() {
...
-                    logger.warn("Task instance retry check failed, can not find taskInstance from workflowExecuteThread, will remove this check");
+                    logger.warn(
+                        "Task instance retry check failed, can not find taskInstance from workflowExecuteThread, will remove this check");
                     taskInstanceRetryCheckList.remove(taskInstanceKey);
                     continue;
                 }
 
                 TaskInstance taskInstance = taskInstanceOptional.get();
-                if (taskInstance.retryTaskIntervalOverTime()) {
+                if (taskInstance.getState() != ExecutionStatus.NEED_FAULT_TOLERANCE
```
Comment (caishunfeng) [inline dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/StateWheelExecuteThread.java:308]: can you add some comments for it?

Comment (ruanwenjun) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/StateWheelExecuteThread.java:308]: Done

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java [hunk 4]
```diff
@@ -784,45 +791,60 @@ private void initTaskQueue() throws StateEventHandleException, CronParseExceptio
         errorTaskMap.clear();
 
         if (!isNewProcessInstance()) {
```
Comment (caishunfeng) [inline dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java:793]: It's better to extract a method

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java [hunk 5]
```diff
@@ -899,6 +928,16 @@ private Optional<TaskInstance> submitTaskExec(TaskInstance taskInstance) {
             validTaskMap.put(taskInstance.getTaskCode(), taskInstance.getId());
             taskInstanceMap.put(taskInstance.getId(), taskInstance);
             activeTaskProcessorMaps.put(taskInstance.getTaskCode(), taskProcessor);
+            // todo: do we need to check the result?
```
Comment (caishunfeng) [inline dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java]: Should remove this comment?

File: dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessServiceImpl.java [hunk 6]
```diff
@@ -276,6 +275,9 @@ public class ProcessServiceImpl implements ProcessService {
     @Autowired
     private CuringParamsService curingGlobalParamsService;
 
+    @Autowired
+    private ProcessService processService;
```
Comment (caishunfeng) [inline dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessServiceImpl.java:279]: Quote itself?

Comment (ruanwenjun) [reply dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessServiceImpl.java:279]: This used to use transaction in spring, otherwise we need to use SprintContext.getBean like before.

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java (hunk 5 above)
Comment (ruanwenjun) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java]: Done

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java (hunk 4 above)
Comment (ruanwenjun) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java:793]: Yes, but I don't want to do this code refactor in this PR. I will submit another PR to refactor this.

**Review by caishunfeng — APPROVED** [review]
LGTM
