### PR TITLE
[fix-11452][Bug] [Logger Server] Incorrect password regular expression

### LINKED ISSUE #11452: [Bug] [Logger Server] Incorrect password regular expression
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

SensitiveDataConverter passwordHandler
/**
     * dataSource sensitive param
     */
    public static final String DATASOURCE_PASSWORD_REGEX = "(?<=((?i)password((\\\\\":\\\\\")|(=')))).*?(?=((\\\\\")|(')))";

The log password printed at runtime is not replaced with * sign

### What you expected to happen

"password":"view1"
can replace to
"password":"****"

### How to reproduce

the old pattern is ok.
DATASOURCE_PASSWORD_REGEX = "(?<=(\"password\":\")).*?(?=(\"))"

### Anything else

_No response_

### Version

3.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by jackfanwan**
Example Change the regular expression of the data source password
close: #11452

### CODE REVIEW

**Comment by jackfanwan** [comment]
@ruanwenjun Excuse me, can these be modified?

File: dolphinscheduler-log-server/src/test/java/org/apache/dolphinscheduler/server/log/SensitiveDataConverterTest.java [hunk 1]
```diff
@@ -62,8 +62,8 @@ public void testPwdLogMsgConverter() {
         logger.info("parameter : {}", logMsg);
         logger.info("parameter : {}", passwordHandler(pwdPattern, logMsg));
 
-        Assert.assertEquals(logMsg, passwordHandler(pwdPattern, logMsg));
-        Assert.assertNotEquals(maskLogMsg, passwordHandler(pwdPattern, logMsg));
+        Assert.assertNotEquals(logMsg, passwordHandler(pwdPattern, logMsg));
```
Comment (ruanwenjun) [inline dolphinscheduler-log-server/src/test/java/org/apache/dolphinscheduler/server/log/SensitiveDataConverterTest.java:65]: This assert is meanless

**Review by ruanwenjun — APPROVED** [review]
LGTM
