### PR TITLE
[common] Make dolphinscheduler_env.sh work when start server

### LINKED ISSUE #9727: [Bug] [common] dolphinscheduler_env.sh not work even though configured
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

`dolphinscheduler_env.sh` not working even though I change the setting. It always will source the file `/etc/profiles` instead of `dolphinscheduler_env.sh` file. So when I want to set spark or flink or other task home, i have to change file `/etc/profiles`

### What you expected to happen

in what happend

### How to reproduce

in what happend

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by zhongjiajie**
* Change dist tarball `dolphinscheduler_env.sh` location
  from `bin/` to `conf/`, which users could finish their
  change configuration operation in one single directory.
  and we only need to add `$DOLPHINSCHEDULER_HOME/conf`
  when we start our sever instead of adding both
  `$DOLPHINSCHEDULER_HOME/conf` and `$DOLPHINSCHEDULER_HOME/bin`
* Change the `start.sh`'s path of `dolphinscheduler_env.sh`
* Change the setting order of `dolphinscheduler_env.sh`
* Change the related docs

close: #9727

### CODE REVIEW

File: dolphinscheduler-master/src/main/bin/start.sh [hunk 1]
```diff
@@ -19,7 +19,7 @@
 BIN_DIR=$(dirname $0)
 DOLPHINSCHEDULER_HOME=${DOLPHINSCHEDULER_HOME:-$(cd $BIN_DIR/..; pwd)}
 
-source "$BIN_DIR/dolphinscheduler_env.sh"
+source "$BIN_DIR/../conf/dolphinscheduler_env.sh"
```
Comment (kezhenxu94) [inline dolphinscheduler-master/src/main/bin/start.sh]: What about just 

```suggestion
source "$DOLPHINSCHEDULER_HOME/conf/dolphinscheduler_env.sh"
```

**Review by kezhenxu94 — DISMISSED** [review]
LGTM overall

File: dolphinscheduler-master/src/main/bin/start.sh (hunk 1 above)
Comment (zhongjiajie) [reply dolphinscheduler-master/src/main/bin/start.sh]: Will change it

Comment (zhongjiajie) [reply dolphinscheduler-master/src/main/bin/start.sh]: Done and could you please take a look again? BTW, why we should add file `dolphinscheduler_env.sh` in all servers instead of using the file in the path `bin/env/dolphinscheduler_env.sh`?

**Comment by SbloodyS** [comment]
I have a suggestion in #9675 . Because I found that many PR and issues are related to this problem. If everyone agrees, I think we can add it to this PR to avoid duplication of work. Then close other related issues.

Please task a look @zhongjiajie @kezhenxu94 @caishunfeng

File: dolphinscheduler-master/src/main/bin/start.sh (hunk 1 above)
Comment (kezhenxu94) [reply dolphinscheduler-master/src/main/bin/start.sh]: > BTW, why we should add file `dolphinscheduler_env.sh` in all servers instead of using the file in the path `bin/env/dolphinscheduler_env.sh`?

See my comment https://github.com/apache/dolphinscheduler/issues/9675#issuecomment-1107996038 . The short answer is that `bin/env/dolphinscheduler_env.sh` is only available when you use `install.sh` to install all components in a single machine. If you install each component in a separate machine, `bin/env/dolphinscheduler_env.sh` is not available there, also cc @SbloodyS

**Review by kezhenxu94 — DISMISSED** [review]

**Comment by zhongjiajie** [comment]
I add feature we metiond in https://github.com/apache/dolphinscheduler/issues/9675#issuecomment-1108041268, and after this patch merged, user s who using commad `./bin/dolphinscheduler_daemon.sh start <server>` or `./bin/install.sh` to start dolphinscheduler, the server env config will be overwrite by `./bin/env/dolphinscheudler_env.sh`.

**Review by SbloodyS — APPROVED** [review]

**Comment by zhongjiajie** [comment]
I going to merge this one
