### PR TITLE
[fix-12721] Fix cannot modify the upstream task in task definition page.

### LINKED ISSUE #13066: [Bug] [dolphinscheduler-api] in the task definition list,  can't just modify upstream task list
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

 in the task definition list,  can't just modify upstream task list

### What you expected to happen

can modify

### How to reproduce

in the task definition list,  select edit, just modify upstream task list

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by jackfanwan**
resolve taskDefinitionServiceImpl code logistic conflict

closes: #13066

### CODE REVIEW

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TaskDefinitionServiceImpl.java [hunk 1]
```diff
@@ -821,7 +821,7 @@ public Map<String, Object> updateTaskWithUpstream(User loginUser, long projectCo
         } else {
             queryUpStreamTaskCodeMap = new HashMap<>();
```
Comment (caishunfeng) [inline dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TaskDefinitionServiceImpl.java:858]: I think it's not a bug, because this else branch will create a empty `queryUpStreamTaskCodeMap`.

BTW, this method is difficult to understand and missing comments,  :cry:

Comment (caishunfeng) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TaskDefinitionServiceImpl.java:858]: cc @fuchanghai @ruanwenjun

Comment (jackfanwan) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TaskDefinitionServiceImpl.java:858]: > I think it's not a bug, because this else branch will create a empty `queryUpStreamTaskCodeMap`.
> 
> BTW, this method is difficult to understand and missing comments, 😢

because upstreamTaskCodes always empty, so the if branch will not execute

**Comment by ruanwenjun** [comment]
I will close this PR, you need to provide the detail if there exist a bug.

We don't plan to change the code in this class, this class should be refactored.

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TaskDefinitionServiceImpl.java [hunk 2]
```diff
@@ -117,6 +120,9 @@ public class TaskDefinitionServiceImpl extends BaseServiceImpl implements TaskDe
     @Autowired
     private ProcessTaskRelationMapper processTaskRelationMapper;
 
+    @Autowired
+    private ProcessTaskRelationLogMapper processTaskRelationLogMapper;
```
Comment (ruanwenjun) [inline dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TaskDefinitionServiceImpl.java]: Please use `ProcessTaskRelationLogDao`

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TaskDefinitionServiceImpl.java [hunk 3]
```diff
@@ -846,10 +852,15 @@ public Map<String, Object> updateTaskWithUpstream(User loginUser, long projectCo
         } else {
             queryUpStreamTaskCodeMap = new HashMap<>();
         }
-        if (CollectionUtils.isNotEmpty(upstreamTaskCodes)) {
+        if (queryUpStreamTaskCodeMap.size() != 0) {
```
Comment (ruanwenjun) [inline dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TaskDefinitionServiceImpl.java]:
```suggestion
        if (MapUtils.isNotEmpty(queryUpStreamTaskCodeMap)) {
```

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TaskDefinitionServiceImpl.java [hunk 4]
```diff
@@ -846,10 +852,15 @@ public Map<String, Object> updateTaskWithUpstream(User loginUser, long projectCo
...
             ProcessTaskRelation taskRelation = upstreamTaskRelations.get(0);
             List<ProcessTaskRelation> processTaskRelations =
                     processTaskRelationMapper.queryByProcessCode(projectCode, taskRelation.getProcessDefinitionCode());
+
+            // set upstream code list
+            updateUpstreamTask(new HashSet<>(queryUpStreamTaskCodeMap.keySet()),
```
Comment (ruanwenjun) [inline dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TaskDefinitionServiceImpl.java:866]:
```suggestion
            updateUpstreamTask(queryUpStreamTaskCodeMap.keySet(),
```
You don't need to new set here?

**Review by ruanwenjun — APPROVED** [review]
LGTM
