### PR TITLE
[Bug] [API-9558]fix homepage task instance count method to use submit time to recount

### LINKED ISSUE #9558: [Bug] [API] home page task instance didn't show dispatch states count
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

image
the program does not count 0 submit success 8 need fault tolerance 9 kill 17 dispatch states task instance.

### What you expected to happen

the program should count 0 submit success 8 need fault tolerance 9 kill 17 dispatch states task instance.

### How to reproduce

start a new process and check

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Tianqi-Dotes**
## Purpose of the pull request

fix homepage task instance count method to use submit time to recount special state
close #9558 
## Brief change log

fix homepage task instance count method to use submit time to recount special state
close #9558 
## Verify this pull request

I have tested locally.

### CODE REVIEW

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/DataAnalysisServiceImpl.java [hunk 1]
```diff
@@ -165,14 +166,25 @@ private Map<String, Object> countStateByProject(User loginUser, long projectCode
...
         }
 
         if (processInstanceStateCounts != null) {
             TaskCountDto taskCountResult = new TaskCountDto(processInstanceStateCounts);
+            int recount = 0;
+            for (TaskStateCount taskCountDto : taskCountResult.getTaskCountDtos()) {
+                if (taskCountDto.getCount() == 0) {
+                    //use submit time to recount when 0
+                    //if have any issues with this code should change to specified states 0 8 9 17 not state count is 0
+                    int count = taskInstanceMapper.countTaskInstanceStateByProjectCodesAndState(start, end, projectCodeArray, taskCountDto.getTaskStateType().getCode());
```
Comment (caishunfeng) [inline dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/DataAnalysisServiceImpl.java]: Why not query all states at once? Avoid multiple db interactions in the query loop

Comment (Tianqi-Dotes) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/DataAnalysisServiceImpl.java]: will do

**Review by caishunfeng — DISMISSED** [review]
LGTM if CI pass

**Review by caishunfeng — APPROVED** [review]
