### PR TITLE
[Fix-16783][Datasource] Fix switching multiple data sources, displaying field errors

### LINKED ISSUE #16783: [Bug] [Datasource] Switching multiple data sources, displaying field errors
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

recording
Switching between multiple data sources, those not belonging to the source also displayed

### What you expected to happen

Display is normal

### How to reproduce

Repair

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by sdhzwc**
## Purpose of the pull request
close #16783 

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

## Pull Request Notice
[Pull Request Notice](https://github.com/apache/dolphinscheduler/blob/dev/docs/docs/en/contribute/join/pull-request.md)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

File: dolphinscheduler-ui/src/views/datasource/list/use-form.ts [hunk 1]
```diff
@@ -269,6 +269,15 @@ export function useForm(id?: number) {
...
       state.showPrincipal = false
     }
+
+    state.showRestEndpoint = false
+    state.showNamespace = false
+    state.showKubeConfig = false
+    state.showAccessKeyId = false
+    state.showAccessKeySecret = false
+    state.showRegionId = false
+    state.showEndpoint = false
```
Comment (SbloodyS) [inline dolphinscheduler-ui/src/views/datasource/list/use-form.ts]: It's better put these into each type's else logic so that it can be better maintained.

Comment (sdhzwc) [reply dolphinscheduler-ui/src/views/datasource/list/use-form.ts]: > It's better put these into each type's else logic so that it can be better maintained.

done

**Review by SbloodyS — APPROVED** [review]
LGTM

**Review by Gallardot — APPROVED** [review]
LGTM
