### PR TITLE
[Fix-16903] Fix monitor page cannot display well

### LINKED ISSUE #16903: [Bug] Monitor of server cannot display well
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When I open the monitor page, there is nothing display.

### What you expected to happen

xx

### How to reproduce

Start a standalone cluster.

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by ruanwenjun**
## Purpose of the pull request

close #16903

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

## Pull Request Notice
[Pull Request Notice](https://github.com/apache/dolphinscheduler/blob/dev/docs/docs/en/contribute/join/pull-request.md)

If your pull request contains incompatible change, you should also add it to `docs/docs/en/guide/upgrade/incompatible.md`

### CODE REVIEW

**Review by SbloodyS — COMMENTED** [review]
Frontend build failed. @ruanwenjun

File: dolphinscheduler-registry/dolphinscheduler-registry-plugins/dolphinscheduler-registry-jdbc/src/main/java/org/apache/dolphinscheduler/plugin/registry/jdbc/KeyUtils.java [hunk 1]
```diff
@@ -0,0 +1,75 @@
...
+     * <p> If the parentPath is equal to the childPath, return false
+     */
+    public static boolean isParent(final String parentPath, final String childPath) {
+        if (StringUtils.isEmpty(parentPath)) {
+            throw new IllegalArgumentException("Invalid parent path string " + parentPath);
+        }
+        if (StringUtils.isEmpty(childPath)) {
+            throw new IllegalArgumentException("Invalid child path string " + childPath);
+        }
+        // 使用"/"分割字符串，判断childPath是否是parentPath的子路径
```
Comment (SbloodyS) [inline dolphinscheduler-registry/dolphinscheduler-registry-plugins/dolphinscheduler-registry-jdbc/src/main/java/org/apache/dolphinscheduler/plugin/registry/jdbc/KeyUtils.java]: Please using english here.

File: dolphinscheduler-registry/dolphinscheduler-registry-plugins/dolphinscheduler-registry-jdbc/src/main/java/org/apache/dolphinscheduler/plugin/registry/jdbc/KeyUtils.java [hunk 2]
```diff
@@ -0,0 +1,75 @@
...
+        checkNotNull(path, "path is null");
+        if (!path.startsWith("/")) {
+            throw new IllegalArgumentException("Invalid path string " + path);
+        }
+        int length = path.length() - 1;
+        while (length >= 0 && path.charAt(length) == '/') {
+            length--;
+        }
+        if (length == -1) {
+            return "/";
```
Comment (SbloodyS) [inline dolphinscheduler-registry/dolphinscheduler-registry-plugins/dolphinscheduler-registry-jdbc/src/main/java/org/apache/dolphinscheduler/plugin/registry/jdbc/KeyUtils.java]: Using constants instead.

File: dolphinscheduler-registry/dolphinscheduler-registry-plugins/dolphinscheduler-registry-jdbc/src/main/java/org/apache/dolphinscheduler/plugin/registry/jdbc/KeyUtils.java (hunk 1 above)
Comment (ruanwenjun) [reply dolphinscheduler-registry/dolphinscheduler-registry-plugins/dolphinscheduler-registry-jdbc/src/main/java/org/apache/dolphinscheduler/plugin/registry/jdbc/KeyUtils.java]: Done

File: dolphinscheduler-registry/dolphinscheduler-registry-plugins/dolphinscheduler-registry-jdbc/src/main/java/org/apache/dolphinscheduler/plugin/registry/jdbc/KeyUtils.java (hunk 2 above)
Comment (ruanwenjun) [reply dolphinscheduler-registry/dolphinscheduler-registry-plugins/dolphinscheduler-registry-jdbc/src/main/java/org/apache/dolphinscheduler/plugin/registry/jdbc/KeyUtils.java]: Done

**Review by SbloodyS — APPROVED** [review]
LGTM

File: dolphinscheduler-meter/src/main/java/org/apache/dolphinscheduler/meter/metrics/DefaultMetricsProvider.java [hunk 3]
```diff
@@ -74,6 +77,9 @@ public SystemMetrics getSystemMetrics() {
                 .systemMemoryUsed(totalSystemMemory - systemMemoryAvailable)
                 .systemMemoryMax(totalSystemMemory)
                 .systemMemoryUsedPercentage((double) (totalSystemMemory - systemMemoryAvailable) / totalSystemMemory)
+                .diskUsed(diskToTalBytes - diskFreeBytes)
+                .diskTotal(diskToTalBytes)
+                .diskUsedPercentage((diskToTalBytes - diskFreeBytes) / diskToTalBytes)
```
Comment (zhongjiajie) [inline dolphinscheduler-meter/src/main/java/org/apache/dolphinscheduler/meter/metrics/DefaultMetricsProvider.java:82]: nothing but want to make sure we store as float in stock and render as '\d %' right?

**Review by zhongjiajie — APPROVED** [review]

File: dolphinscheduler-meter/src/main/java/org/apache/dolphinscheduler/meter/metrics/DefaultMetricsProvider.java (hunk 3 above)
Comment (ruanwenjun) [reply dolphinscheduler-meter/src/main/java/org/apache/dolphinscheduler/meter/metrics/DefaultMetricsProvider.java:82]: We will render as string by 
```
<Gauge
    data={(
      JSON.parse(item.heartBeatInfo).diskUsage * 100
    ).toFixed(2)}
  />
```

It works well 

image
