### PR TITLE
[Fix-16382] Fix the bug of async master task casthread pool invocations ramp-up

### LINKED ISSUE #16460: [Bug] [dolphinscheduler-master] AsyncMasterTask may causing a ramp-up in thread pool invocations
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Here are some mistakes about AsyncMasterTask
1. AsyncTask execute times won't be increased
2. The timeout unit is incorrect, the timeout was supposed to be in minutes, but in the code, it was set to seconds.
3. If a dependent task is set with a timeout, its execution frequency will increase as it gets closer to the timeout, it will cause DB down if you have lots tasks.

### What you expected to happen

1. we should schedule master async task with a fixed delay instead of fixed rate to avoid service crashes caused by resource exhaustion

### How to reproduce

1. create some denpendent Task with timeout (like 1 minutes)
2. watch the execute times for async task execution context.

### Anything else

_No response_

### Version

3.2.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Dyqer**
## Purpose of the pull request

fix https://github.com/apache/dolphinscheduler/issues/16460

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

## Pull Request Notice
[Pull Request Notice](https://github.com/apache/dolphinscheduler/blob/dev/docs/docs/en/contribute/join/pull-request.md)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/execute/AsyncTaskExecutionContext.java [hunk 1]
```diff
@@ -59,19 +59,17 @@ public AsyncTaskExecutionContext(@NonNull TaskExecutionContext taskExecutionCont
...
             currentStartTime = System.currentTimeMillis();
         }
+        executeTimes++;
     }
 
     @Override
     public long getDelay(TimeUnit unit) {
-        long nextExecuteTimeDelay = Math.min(currentStartTime + executeInterval, timeout) - System.currentTimeMillis();
-        return unit.convert(nextExecuteTimeDelay, TimeUnit.MILLISECONDS);
+        return unit.convert(this.executeInterval, TimeUnit.MILLISECONDS);
```
Comment (ruanwenjun) [inline dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/execute/AsyncTaskExecutionContext.java]: Have you test this? Once the element changed in the delay queue, the delay time will recalculate, in this pr the delay time will be a fixed value, this will cause some function will never be triggered.

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/execute/AsyncTaskExecutionContext.java [hunk 2]
```diff
@@ -59,19 +59,17 @@ public AsyncTaskExecutionContext(@NonNull TaskExecutionContext taskExecutionCont
...
-    public void refreshStartTime() {
-        if (executeTimes == 0) {
+    public synchronized void refreshStartTime() {
+        if (executeTimes != 0) {
             // The first time doesn't have delay
-            executeTimes++;
-        } else {
             currentStartTime = System.currentTimeMillis();
         }
+        executeTimes++;
```
Comment (ruanwenjun) [inline dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/execute/AsyncTaskExecutionContext.java:57]: The executeTimes is only a mark flag, it is not used to represent execute the real times.

**Comment by ruanwenjun** [comment]
The key problem related to your issue is the async task doesn't support timeout, the async should stop once it's timeout.

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/execute/AsyncTaskExecutionContext.java (hunk 1 above)
Comment (Dyqer) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/execute/AsyncTaskExecutionContext.java]: sorry for that, I changed it.

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/execute/AsyncTaskExecutionContext.java (hunk 2 above)
Comment (Dyqer) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/execute/AsyncTaskExecutionContext.java:57]: we can record the execute times for monitoring

**Comment by Dyqer** [comment]
> The key problem related to your issue is the async task doesn't support timeout, the async should stop once it's timeout.

but the timeout observer is in master standby list, it may have 1~10 minutes later than real timeout, the functions will be invoked in a dead loop during those 10 minutes.

**Comment by Dyqer** [comment]
> The key problem related to your issue is the async task doesn't support timeout, the async should stop once it's timeout.


@ruanwenjun 
Here are two critical issues about AsyncMasterTask:

1. if the task is set to just warn and not fail on timeout, it will immediately enter an infinite loop after reaching the timeout period.
2. there's a mistake in the timeout unit, should be minute not second, it exacerbates the problem.


I think the best solution is to ignore the timeout logic here and only focus on the execution interval. The timeout event should still be handled by the stateEventhandler.

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/execute/AsyncTaskExecutionContext.java (hunk 2 above)
Comment (ruanwenjun) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/execute/AsyncTaskExecutionContext.java:57]: yes, it's great, we can add this in task metrics.

**Comment by ruanwenjun** [comment]
> > The key problem related to your issue is the async task doesn't support timeout, the async should stop once it's timeout.
> 
> @ruanwenjun Here are two critical issues about AsyncMasterTask:
> 
> 1. if the task is set to just warn and not fail on timeout, it will immediately enter an infinite loop after reaching the timeout period.
> 2. there's a mistake in the timeout unit, should be minute not second, it exacerbates the problem.
> 
> I think the best solution is to ignore the timeout logic here and only focus on the execution interval. The timeout event should still be handled by the stateEventhandler.

Yes, there exist a bug as you mention, and you are right, the task executor don't need to care about the timeout, all timeout event should be controlled by master event engine.

**Review by ruanwenjun — DISMISSED** [review]
LGTM, and we didn't have integration test for the logic task,  after https://github.com/apache/dolphinscheduler/pull/16327, we can easily add this kind of case.

**Review by SbloodyS — DISMISSED** [review]
+1

**Comment by Dyqer** [comment]
@ruanwenjun @SbloodyS anyone can help merge? Seems  github actions stuck

**Comment by SbloodyS** [comment]
> @ruanwenjun @SbloodyS anyone can help merge? Seems github actions stuck

CI failed. You should run `mvn spotless:apply` to format code.

**Comment by Dyqer** [comment]
> > @ruanwenjun @SbloodyS anyone can help merge? Seems github actions stuck
> 
> CI failed. You should run `mvn spotless:apply` to format code.

Oh, Thank you!, please help to review again @ruanwenjun @SbloodyS

**Review by SbloodyS — APPROVED** [review]

**Review by ruanwenjun — APPROVED** [review]
