### PR TITLE
[Fix-12368] [Task Plugin] Fix DataX plugin NPE issue.

### LINKED ISSUE #12368: [Bug] [Task plugin] datax task error
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

[LOG-PATH]: /opt/dolphinscheduler/worker-server/logs/20221014/7195111179040_2-15-22.log, [HOST]:  Host{address='172.16.10.15:1234', ip='172.16.10.15', port=1234}
[INFO] 2022-10-14 08:44:09.886 +0800 - Begin to pulling task
[INFO] 2022-10-14 08:44:09.887 +0800 - Begin to initialize task
[INFO] 2022-10-14 08:44:09.887 +0800 - Set task startTime: Fri Oct 14 08:44:09 CST 2022
[INFO] 2022-10-14 08:44:09.887 +0800 - Set task envFile: /opt/dolphinscheduler/worker-server/conf/dolphinscheduler_env.sh
[INFO] 2022-10-14 08:44:09.887 +0800 - Set task appId: 15_22
[INFO] 2022-10-14 08:44:09.887 +0800 - End initialize task
[INFO] 2022-10-14 08:44:09.888 +0800 - Set task status to TaskExecutionStatus{code=1, desc='running'}
[INFO] 2022-10-14 08:44:09.888 +0800 - TenantCode:root check success
[INFO] 2022-10-14 08:44:09.888 +0800 - ProcessExecDir:/tmp/dolphinscheduler/exec/process/7193666667040/7195111179040_2/15/22 check success
[INFO] 2022-10-14 08:44:09.888 +0800 - Resources:{} check success
[INFO] 2022-10-14 08:44:09.889 +0800 - Task plugin: DATAX create success
[INFO] 2022-10-14 08:44:09.889 +0800 - datax task params {"localParams":[],"resourceList":[],"customConfig":0,"dsType":"MYSQL","dataSource":1,"dtType":"MYSQL","dataTarget":1,"sql":"select id,name from ods.ods_jdx_site","targetTable":"ods_jdx_site_copy1","jobSpeedByte":0,"jobSpeedRecord":1000,"preStatements":[],"postStatements":[],"xms":1,"xmx":1}
[INFO] 2022-10-14 08:44:09.889 +0800 - Success initialized task plugin instance success
[INFO] 2022-10-14 08:44:09.889 +0800 - Success set taskVarPool: null
[ERROR] 2022-10-14 08:44:09.890 +0800 - datax task error
java.lang.NullPointerException: null
	at org.apache.dolphinscheduler.plugin.task.datax.DataxTask.addCustomParameters(DataxTask.java:426)
	at org.apache.dolphinscheduler.plugin.task.datax.DataxTask.buildShellCommandFile(DataxTask.java:400)
	at org.apache.dolphinscheduler.plugin.task.datax.DataxTask.handle(DataxTask.java:157)
	at org.apache.dolphinscheduler.server.worker.runner.DefaultWorkerDelayTaskExecuteRunnable.executeTask(DefaultWorkerDelayTaskExecuteRunnable.java:48)
	at org.apache.dolphinscheduler.server.worker.runner.WorkerTaskExecuteRunnable.run(WorkerTaskExecuteRunnable.java:151)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[ERROR] 2022-10-14 08:44:09.890 +0800 - Task execute failed, due to meet an exception
org.apache.dolphinscheduler.plugin.task.api.TaskException: Execute DataX task failed
	at org.apache.dolphinscheduler.plugin.task.datax.DataxTask.handle(DataxTask.java:171)
	at org.apache.dolphinscheduler.server.worker.runner.DefaultWorkerDelayTaskExecuteRunnable.executeTask(DefaultWorkerDelayTaskExecuteRunnable.java:48)
	at org.apache.dolphinscheduler.server.worker.runner.WorkerTaskExecuteRunnable.run(WorkerTaskExecuteRunnable.java:151)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: null
	at org.apache.dolphinscheduler.plugin.task.datax.DataxTask.addCustomParameters(DataxTask.java:426)
	at org.apache.dolphinscheduler.plugin.task.datax.DataxTask.buildShellCommandFile(DataxTask.java:400)
	at org.apache.dolphinscheduler.plugin.task.datax.DataxTask.handle(DataxTask.java:157)
	... 9 common frames omitted
[INFO] 2022-10-14 08:44:10.900 +0800 - Get a exception when execute the task, will send the task execute result to master, the current task execute result is TaskExecutionStatus{code=6, desc='failure'}

### What you expected to happen

task run success

### How to reproduce

datax task with mysql2mysql

### Anything else

DATAX_HOME=/opt/datax

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by DarkAssassinator**
## Purpose of the pull request

+ This PR will close #12368 

## Brief change log

+ Fix NPE 
+ Refactor some cases
+ Add DataxTask UT

## Verify this pull request
+ This change added tests
+ UT do not cover all provate methods.

### CODE REVIEW

**Review by fuchanghai — APPROVED** [review]

File: dolphinscheduler-task-plugin/dolphinscheduler-task-datax/src/main/java/org/apache/dolphinscheduler/plugin/task/datax/DataxTask.java [hunk 1]
```diff
@@ -393,18 +392,17 @@ private String buildShellCommandFile(String jobConfigFilePath, Map<String, Prope
...
-        sbr.append(getPythonCommand());
-        sbr.append(" ");
-        sbr.append(DATAX_PATH);
-        sbr.append(" ");
-        sbr.append(loadJvmEnv(dataXParameters));
-        sbr.append(addCustomParameters(paramsMap));
-        sbr.append(" ");
-        sbr.append(jobConfigFilePath);
+        String sbr = getPythonCommand() +
+                " " +
```
Comment (fuchanghai) [inline dolphinscheduler-task-plugin/dolphinscheduler-task-datax/src/main/java/org/apache/dolphinscheduler/plugin/task/datax/DataxTask.java:396]: if ```sbr``` use type of String, will it cause the JVM to generate multiple objects?

File: dolphinscheduler-task-plugin/dolphinscheduler-task-datax/src/main/java/org/apache/dolphinscheduler/plugin/task/datax/DataxTask.java [hunk 2]
```diff
@@ -393,18 +392,17 @@ private String buildShellCommandFile(String jobConfigFilePath, Map<String, Prope
...
-        StringBuilder sbr = new StringBuilder();
-        sbr.append(getPythonCommand());
-        sbr.append(" ");
-        sbr.append(DATAX_PATH);
-        sbr.append(" ");
-        sbr.append(loadJvmEnv(dataXParameters));
-        sbr.append(addCustomParameters(paramsMap));
-        sbr.append(" ");
-        sbr.append(jobConfigFilePath);
+        String sbr = getPythonCommand() +
```
Comment (fuchanghai) [inline dolphinscheduler-task-plugin/dolphinscheduler-task-datax/src/main/java/org/apache/dolphinscheduler/plugin/task/datax/DataxTask.java:395]: if `sbr` use type of String, will it cause the JVM to generate multiple objects?

File: dolphinscheduler-task-plugin/dolphinscheduler-task-datax/src/main/java/org/apache/dolphinscheduler/plugin/task/datax/DataxTask.java [hunk 3]
```diff
@@ -393,18 +392,17 @@ private String buildShellCommandFile(String jobConfigFilePath, Map<String, Prope
         }
 
         // datax python command
-        StringBuilder sbr = new StringBuilder();
```
Comment (EricGao888) [inline dolphinscheduler-task-plugin/dolphinscheduler-task-datax/src/main/java/org/apache/dolphinscheduler/plugin/task/datax/DataxTask.java:396]: May I ask why you change to use `String` here?

Comment (DarkAssassinator) [reply dolphinscheduler-task-plugin/dolphinscheduler-task-datax/src/main/java/org/apache/dolphinscheduler/plugin/task/datax/DataxTask.java:396]: @EricGao888 @fuchanghai Sure, because JVM internally compiler will geneate axactly the same bytecode and `String +` and `StringBuilder.append` will have the same performance and the same memory usage, but String will be easier to read. We can get a readability benefit without any performace compromises. The replacement does not result in significant performance drawback on modern JVMs.
Please check the following screenshot, the modern JVM will pptimize `String +` to `StringBuilder.append`, so they are same.
image
If just compare `String` with `StringBuilder`, on most cases, using String is more practical and logical. It is not always better to concatenate string with plus sign (+). For example, StringBuilder's append method is more logical if you change your string in a loop because of its mutability. 
For more details, please check [JLS: 15.18.1. String Concatenation Operator +](https://docs.oracle.com/javase/specs/jls/se8/html/jls-15.html#jls-15.18.1)
And current IDEA is so smart, it will suggests you to change it for better code readability. It is equivalent to the optimization of the compiler, so IDEA detects that the two are equivalent. In order to make the code more concise, it will give some tips. Please check [IDEA:Convert StringBuilder to String concatenation suggestion](https://intellij-support.jetbrains.com/hc/en-us/community/posts/115000093250-Convert-StringBuilder-to-String-concatenation-suggestion)

Comment (EricGao888) [reply dolphinscheduler-task-plugin/dolphinscheduler-task-datax/src/main/java/org/apache/dolphinscheduler/plugin/task/datax/DataxTask.java:396]: Make sense to me. Nice work and thx for the explanation.

**Review by EricGao888 — APPROVED** [review]
LGTM, waiting for CI to pass.

**Review by zhuangchong — APPROVED** [review]
