### PR TITLE
fix: data quality can not use

### LINKED ISSUE #15468: 3.2.0 Data Quality cannot be used
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

在使用3.2.0的Data Quality使用，writers的对象的JSON不完整，导致使用时报错User class threw exception: java.lang.NullPointerException
edcee8888dfd65eec9963d4fe329d41
image

### What you expected to happen

edcee8888dfd65eec9963d4fe329d41
image

### How to reproduce

修复3.2.0

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by zhongjiajie**
fix: #15468, #15249, #14858

### CODE REVIEW

File: dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-api/src/main/java/org/apache/dolphinscheduler/plugin/datasource/api/utils/CommonUtils.java [hunk 1]
```diff
@@ -123,14 +132,56 @@ public static boolean loadKerberosConf(String javaSecurityKrb5Conf, String login
...
+        if (StringUtils.isNotEmpty(DEFAULT_DATA_QUALITY_JAR_PATH)) {
+            return DEFAULT_DATA_QUALITY_JAR_PATH;
+        }
+        try {
+            // not standalone mode
+            String currentAbsolutePath = new ClassPathResource("./").getFile().getAbsolutePath();
+            String currentLibPath = currentAbsolutePath + "/../libs";
+            getDataQualityJarPathFromPath(currentLibPath).ifPresent(jarName -> DEFAULT_DATA_QUALITY_JAR_PATH = jarName);
+
+            // standalone mode
```
Comment (zhongjiajie) [inline dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-api/src/main/java/org/apache/dolphinscheduler/plugin/datasource/api/utils/CommonUtils.java:156]: auto discovery data quality jar path for both standalone mode and not

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/TaskExecutionContextFactory.java [hunk 2]
```diff
@@ -400,15 +394,16 @@ public DataSource getDefaultDataSource() {
...
-            properties.setProperty(OTHER, jdbcInfo.getParams());
-            properties.setProperty(JDBC_URL, jdbcInfo.getAddress() + SINGLE_SLASH + jdbcInfo.getDatabase());
+            //
+            BaseConnectionParam baseConnectionParam = new DefaultConnectionParam();
+            baseConnectionParam.setUser(hikariDataSource.getUsername());
+            baseConnectionParam.setPassword(hikariDataSource.getPassword());
+            baseConnectionParam.setDatabase(jdbcInfo.getDatabase());
+            baseConnectionParam.setAddress(jdbcInfo.getAddress());
+            baseConnectionParam.setJdbcUrl(jdbcInfo.getJdbcUrl());
+            baseConnectionParam.setOther(jdbcInfo.getParams());
```
Comment (zhongjiajie) [inline dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/TaskExecutionContextFactory.java:404]: key change for data quality task can not be use

File: dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/utils/JdbcUrlParser.java [hunk 3]
```diff
@@ -105,8 +109,24 @@ public static JdbcInfo getJdbcInfo(String jdbcUrl) {
...
+            for (String param : paramList) {
+                // handle bad params
+                if (StringUtils.isEmpty(param) || !param.contains(EQUAL_SIGN)) {
+                    continue;
+                }
+                String[] kv = param.split(EQUAL_SIGN);
+                others.put(kv[0], kv[1]);
+            }
+            jdbcInfo.setParams(others);
+        }
```
Comment (zhongjiajie) [inline dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/utils/JdbcUrlParser.java:125]: parse metadata other param to avoid connect error

File: dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-api/src/main/java/org/apache/dolphinscheduler/plugin/datasource/api/utils/CommonUtils.java [hunk 4]
```diff
@@ -123,14 +132,56 @@ public static boolean loadKerberosConf(String javaSecurityKrb5Conf, String login
...
+            if (StringUtils.isEmpty(DEFAULT_DATA_QUALITY_JAR_PATH)) {
+                log.info(
+                        "Can not get data quality jar from path {}, maybe service running in standalone mode, will try to find another path",
+                        currentLibPath);
+                currentLibPath = currentAbsolutePath + "/../../worker-server/libs";
```
Comment (caishunfeng) [inline dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-api/src/main/java/org/apache/dolphinscheduler/plugin/datasource/api/utils/CommonUtils.java:161]: It seems can not auto find in docker image?

Is it better to add env when use standalone mode?

**Review by caishunfeng — APPROVED** [review]
LGTM, some NIP

File: dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-api/src/main/java/org/apache/dolphinscheduler/plugin/datasource/api/utils/CommonUtils.java [hunk 5]
```diff
@@ -123,14 +132,56 @@ public static boolean loadKerberosConf(String javaSecurityKrb5Conf, String login
...
+            log.info("data quality jar path is empty, will try to get it from data quality jar name");
+            return getDefaultDataQualityJarPath();
         }
 
-        return dqsJarName;
+        return dqsJarPath;
+    }
+
+    private static String getDefaultDataQualityJarPath() {
+        if (StringUtils.isNotEmpty(DEFAULT_DATA_QUALITY_JAR_PATH)) {
```
Comment (rickchengx) [inline dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-api/src/main/java/org/apache/dolphinscheduler/plugin/datasource/api/utils/CommonUtils.java:147]: It seems that if the location of the jar package has been found once before, it will be returned directly. Do we need to consider the situation where the user has modified the name or location of the jar package?

Comment (zhongjiajie) [reply dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-api/src/main/java/org/apache/dolphinscheduler/plugin/datasource/api/utils/CommonUtils.java:147]: > It seems that if the location of the jar package has been found once before

correct

> Do we need to consider the situation where the user has modified the name or location of the jar package

I think is ok to keep this, cause this jar is not in class path, They can directly replace the jar with the same name if they rebuild the jar. Or if they want to change de jar name, they should restart worker node, or change `data-quality.jar.name`(actually a path) in `common.properties`

**Review by rickchengx — APPROVED** [review]
LGTM
