### PR TITLE
[bug][task-plugins]fix switch class name and add param check to the switch task plugin

### LINKED ISSUE #10893: [Bug] [SWITCH-PLUGIN] Switch task plugin wrong class name and no param validation
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

the code use switch task plugin names subprocess which goes wrong.
there is no validation to the default next node, so you can create a switch task without default next node. when conditions not triggered, the switch task fails

### What you expected to happen

1. change the subprocess class code name to switch
2. add validations to default next node existence
3. add validations to conditions to check when there is condition there must have next node

### How to reproduce

create new switch task and not fill the default next node, when no condition triggers the task instance fails.

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Tianqi-Dotes**
## Purpose of the pull request

close [#](https://github.com/apache/dolphinscheduler/issues/10893)

## Brief change log

1. change the subprocess class code name to switch
2. add validations to default next node existence
3. add validations to conditions to check when there is condition there must have next node
4. 
## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

Manually verified the change by testing locally.

### CODE REVIEW

File: dolphinscheduler-task-plugin/dolphinscheduler-task-switch/src/main/java/org/apache/dolphinscheduler/plugin/task/switchtask/SwitchCondition.java [hunk 1]
```diff
@@ -0,0 +1,23 @@
+package org.apache.dolphinscheduler.plugin.task.switchtask;
```
Comment (caishunfeng) [inline dolphinscheduler-task-plugin/dolphinscheduler-task-switch/src/main/java/org/apache/dolphinscheduler/plugin/task/switchtask/SwitchCondition.java:18]: license header

File: dolphinscheduler-task-plugin/dolphinscheduler-task-switch/src/main/java/org/apache/dolphinscheduler/plugin/task/switchtask/SwitchTask.java [hunk 2]
```diff
@@ -0,0 +1,80 @@
...
+import org.apache.dolphinscheduler.plugin.task.api.AbstractTaskExecutor;
+import org.apache.dolphinscheduler.plugin.task.api.ShellCommandExecutor;
+import org.apache.dolphinscheduler.plugin.task.api.TaskExecutionContext;
+import org.apache.dolphinscheduler.plugin.task.api.parameters.AbstractParameters;
+import org.apache.dolphinscheduler.spi.utils.JSONUtils;
+
+/**
+ * switch task
+ */
+public class SwitchTask extends AbstractTaskExecutor {
```
Comment (caishunfeng) [inline dolphinscheduler-task-plugin/dolphinscheduler-task-switch/src/main/java/org/apache/dolphinscheduler/plugin/task/switchtask/SwitchTask.java]: It seems unuseful because Switch Task is a logic node in Master, and workers never use it

File: dolphinscheduler-task-plugin/dolphinscheduler-task-switch/src/main/java/org/apache/dolphinscheduler/plugin/task/switchtask/SwitchCondition.java (hunk 1 above)
Comment (Tianqi-Dotes) [reply dolphinscheduler-task-plugin/dolphinscheduler-task-switch/src/main/java/org/apache/dolphinscheduler/plugin/task/switchtask/SwitchCondition.java:18]: added

File: dolphinscheduler-task-plugin/dolphinscheduler-task-switch/src/main/java/org/apache/dolphinscheduler/plugin/task/switchtask/SwitchTask.java (hunk 2 above)
Comment (Tianqi-Dotes) [reply dolphinscheduler-task-plugin/dolphinscheduler-task-switch/src/main/java/org/apache/dolphinscheduler/plugin/task/switchtask/SwitchTask.java]: deleted and tested

**Review by caishunfeng — APPROVED** [review]
+1
