### PR TITLE
Adapt web configurations for UI next

### LINKED ISSUE #8580: [Bug][UI Next][V1.0.0-Alpha] Errors that appear in standalone after packaging and compiling.
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

I'm trying to package ```UI-Next``` into the docker image of ```dev``` branch. I try to replace the ```dist``` folder compiled by ```UI-Next``` with the previous version to the ```ui``` folder under the API module. I start the API module to access the domain/dolphinscheduler and get the following errors.

And then I try to remove the absolute path ```/``` in index.html. I got another errors.

Is it that the compatibility of API modules has not been completed?

### What you expected to happen

above.

### How to reproduce

above.

### Anything else

In standalone mode.

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by kezhenxu94**
Closes https://github.com/apache/dolphinscheduler/issues/8580

@SbloodyS please help to confirm that this solves the issue. Thanks!

### CODE REVIEW

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/DsErrorController.java [hunk 1]
```diff
@@ -0,0 +1,50 @@
...
+public class DsErrorController implements ErrorController {
+    @RequestMapping("/error")
+    public ModelAndView handleError(HttpServletRequest request) {
+        Object status = request.getAttribute(RequestDispatcher.ERROR_STATUS_CODE);
+        ModelAndView modelAndView = new ModelAndView();
+
+        if (status != null) {
+            Integer statusCode = Integer.valueOf(status.toString());
+
+            if (statusCode == HttpStatus.NOT_FOUND.value()) {
```
Comment (caishunfeng) [inline dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/DsErrorController.java:40]: Is it better to add some log here if not found?

Comment (kezhenxu94) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/DsErrorController.java:40]: Writing logs for this case will become very noisy and we don't even care because this is our expected case, but I can write some logs for the other cases than `NOT_FOUND`

Comment (caishunfeng) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/DsErrorController.java:40]: OK, I agree with you.

**Review by caishunfeng — APPROVED** [review]
LGTM

**Review by CalvinKirs — APPROVED** [review]
LGTM
