### PR TITLE
[Fix-17356][Dependent] error creating Dependent

### LINKED ISSUE #17356: [Bug] [Dependent] error creating Dependent
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

[{"code":147187281221184,"delayTime":"0","description":"","environmentCode":146747309992640,"failRetryInterval":"1","failRetryTimes":"0","flag":"YES","isCache":"NO","name":"Dependent","taskParams":{"localParams":[],"resourceList":[],"dependence":{"checkInterval":10,"failurePolicy":"DEPENDENT_FAILURE_FAILURE","relation":"AND","dependTaskList":[{"relation":"OR","dependItemList":[{"dependentType":"DEPENDENT_ON_TASK","projectCode":147079473154816,"definitionCode":147179187707456,"depTaskCode":147179187682880,"cycle":"day","dateValue":"today","parameterPassing":false,"state":null},{"dependentType":"DEPENDENT_ON_TASK","projectCode":147079473154816,"definitionCode":147179187707456,"depTaskCode":147179187684928,"cycle":"week","dateValue":"lastWednesday","parameterPassing":false,"state":null}]},{"relation":"OR","dependItemList":[{"dependentType":"DEPENDENT_ON_TASK","projectCode":147079473154816,"definitionCode":147179187707456,"depTaskCode":147179187682880,"cycle":"week","dateValue":"lastWeek","parameterPassing":false,"state":null},{"dependentType":"DEPENDENT_ON_TASK","projectCode":147079473154816,"definitionCode":147179187707456,"depTaskCode":147179187684928,"cycle":"week","dateValue":"lastMonday","parameterPassing":false,"state":null}]}]}},"taskPriority":"MEDIUM","taskType":"DEPENDENT","timeout":0,"timeoutFlag":"CLOSE","timeoutNotifyStrategy":"","workerGroup":"default","cpuQuota":-1,"memoryMax":-1,"taskExecuteType":"BATCH"}]

Caused by: org.postgresql.util.PSQLException: ERROR: null value in column "id" of relation "t_ds_process_task_lineage" violates not-null constraint

### What you expected to happen

create success

### How to reproduce

[{"code":147187281221184,"delayTime":"0","description":"","environmentCode":146747309992640,"failRetryInterval":"1","failRetryTimes":"0","flag":"YES","isCache":"NO","name":"Dependent","taskParams":{"localParams":[],"resourceList":[],"dependence":{"checkInterval":10,"failurePolicy":"DEPENDENT_FAILURE_FAILURE","relation":"AND","dependTaskList":[{"relation":"OR","dependItemList":[{"dependentType":"DEPENDENT_ON_TASK","projectCode":147079473154816,"definitionCode":147179187707456,"depTaskCode":147179187682880,"cycle":"day","dateValue":"today","parameterPassing":false,"state":null},{"dependentType":"DEPENDENT_ON_TASK","projectCode":147079473154816,"definitionCode":147179187707456,"depTaskCode":147179187684928,"cycle":"week","dateValue":"lastWednesday","parameterPassing":false,"state":null}]},{"relation":"OR","dependItemList":[{"dependentType":"DEPENDENT_ON_TASK","projectCode":147079473154816,"definitionCode":147179187707456,"depTaskCode":147179187682880,"cycle":"week","dateValue":"lastWeek","parameterPassing":false,"state":null},{"dependentType":"DEPENDENT_ON_TASK","projectCode":147079473154816,"definitionCode":147179187707456,"depTaskCode":147179187684928,"cycle":"week","dateValue":"lastMonday","parameterPassing":false,"state":null}]}]}},"taskPriority":"MEDIUM","taskType":"DEPENDENT","timeout":0,"timeoutFlag":"CLOSE","timeoutNotifyStrategy":"","workerGroup":"default","cpuQuota":-1,"memoryMax":-1,"taskExecuteType":"BATCH"}]

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by SbloodyS**
## Purpose of the pull request

fix #17356

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

## Pull Request Notice
[Pull Request Notice](https://github.com/apache/dolphinscheduler/blob/dev/docs/docs/en/contribute/join/pull-request.md)

If your pull request contains incompatible change, you should also add it to `docs/docs/en/guide/upgrade/incompatible.md`

### CODE REVIEW

File: dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_postgresql.sql [hunk 1]
```diff
@@ -1311,7 +1311,7 @@ CREATE INDEX idx_sub_workflow_instance_id ON t_ds_relation_sub_workflow (sub_wor
 -- ----------------------------
 DROP TABLE IF EXISTS t_ds_workflow_task_lineage;
 CREATE TABLE t_ds_workflow_task_lineage (
-    id int NOT NULL,
+    id SERIAL PRIMARY KEY NOT NULL,
```
Comment (ruanwenjun) [inline dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_postgresql.sql]:
```suggestion
    id        serial      NOT NULL,
```

File: dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_postgresql.sql [hunk 2]
```diff
@@ -1320,8 +1320,7 @@ CREATE TABLE t_ds_workflow_task_lineage (
     dept_workflow_definition_code bigint NOT NULL DEFAULT 0,
     dept_task_definition_code bigint NOT NULL DEFAULT 0,
     create_time timestamp NOT NULL DEFAULT current_timestamp,
-    update_time timestamp NOT NULL DEFAULT current_timestamp,
-    PRIMARY KEY (id)
+    update_time timestamp NOT NULL DEFAULT current_timestamp
```
Comment (ruanwenjun) [inline dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_postgresql.sql]:
```suggestion
    update_time timestamp NOT NULL DEFAULT current_timestamp,
    PRIMARY KEY (id)
```

**Review by ruanwenjun — COMMENTED** [review]
It's better to keep style with other table.

Seems we don't have pg e2e😢

**Comment by SbloodyS** [comment]
> It's better to keep style with other table.

Fixed. PTAL

> Seems we don't have pg e2e😢

Yes, at the same time, we don't have the e2e of mysql, but h2 and mysql are completely compatible, so we avoid this in mysql.

**Review by ruanwenjun — APPROVED** [review]
LGTM

**Review by Gallardot — APPROVED** [review]

**Review by zhongjiajie — APPROVED** [review]
