### PR TITLE
[Fix-14171] Add dynamic font sizes to dashboards

### LINKED ISSUE #14171: [Bug] [UI] The cpu and memory dashboard displays abnormally on a 15.6-inch screen with a 1080P resolution.
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

The cpu and memory dashboard displays abnormally on a 15.6-inch screen with a 1080P resolution.

### What you expected to happen

I hope someone fixes it.

### How to reproduce

DolphinScheduler-3.1.6

Please open dolphinscheduler UI on a 15.6-inch screen with a 1080P resolution.

### Anything else

_No response_

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by pppppjcc**
## Purpose of the pull request

The font size of the dashboard now changes dynamically based on the width of the browser

fix: https://github.com/apache/dolphinscheduler/issues/14171

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

File: dolphinscheduler-ui/src/components/chart/index.ts [hunk 1]
```diff
@@ -44,6 +54,24 @@ function initChart<Opt extends ECBasicOption>(
   }
 
   const resize = throttle(() => {
+    if (type === 'gauge') {
```
Comment (devosend) [inline dolphinscheduler-ui/src/components/chart/index.ts]: Why only gauge needs to adapt?

**Comment by caishunfeng** [comment]
Hi @pppppjcc please use the correct title, use [Fix-issueId] or [Bug-issueId], it's not a feature.

File: dolphinscheduler-ui/src/components/chart/index.ts (hunk 1 above)
Comment (zhongjiajie) [reply dolphinscheduler-ui/src/components/chart/index.ts]: will approve CI run when we solve this discuss

**Comment by zhongjiajie** [comment]
I had rerun all failed tests

**Review by devosend — APPROVED** [review]
LGTM
