### PR TITLE
[Fix-16978][Master] Fix AbstractDelayEvent compare method is incorrect

### LINKED ISSUE #16978: [Bug] [Master]  Fix AbstractDelayEvent compare method is incorrect
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

https://github.com/apache/dolphinscheduler/issues/16976#issuecomment-2608725571

### What you expected to happen

If the event is not expired then should use exipre time to compare them, if the event is already expired then should use create time to compare them.

### How to reproduce

- 

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by reele**
## Purpose of the pull request

Fix AbstractDelayEventBus block events issue fix #16978.

## Brief change log

1. Fix AbstractDelayEvent compare method is incorrect.
2. Modify TaskFailureStateAction to allow killEventAction when task instance can retry.
3. modify WorkflowInstanceTopTestCase and WorkflowInstancePauseTestCase, add affected workflow stop and pause with failed retrying task test cases.
4. fix (I)WorkflowExecutionGraph.isTaskExecutionRunnableActive method is incorrect.

## Verify this pull request

Stop a workflow with failed task when waiting to retry.

## Pull Request Notice
[Pull Request Notice](https://github.com/apache/dolphinscheduler/blob/dev/docs/docs/en/contribute/join/pull-request.md)

If your pull request contains incompatible change, you should also add it to `docs/docs/en/guide/upgrade/incompatible.md`

### CODE REVIEW

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/task/statemachine/TaskFailureStateAction.java [hunk 1]
```diff
@@ -130,6 +130,17 @@ public void killEventAction(final IWorkflowExecutionRunnable workflowExecutionRu
...
+        // for now, killEventAction can be fired on failure with retry
+        // there is no task executor now, shouldn't call workflowExecutionGraph.isTaskExecutionRunnableActive()
+        // it's better to call super.killedEventAction() direct
+        if (taskExecutionRunnable.isTaskInstanceCanRetry()
+        // && workflowExecutionGraph.isTaskExecutionRunnableActive(taskExecutionRunnable)
+        ) {
+            super.killedEventAction(workflowExecutionRunnable, taskExecutionRunnable,
+                    TaskKilledLifecycleEvent.of(taskExecutionRunnable));
+            return;
+        }
```
Comment (ruanwenjun) [inline dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/task/statemachine/TaskFailureStateAction.java]: Do we need to do this change? or this is only your test code?

Comment (reele) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/task/statemachine/TaskFailureStateAction.java]: it's not test code, before this pr, the kill event always triggered after retry event, so the kill or start(retry) action always fire on submitted state

this code use to finish the workflow's Topology graph.

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/task/statemachine/TaskFailureStateAction.java [hunk 2]
```diff
@@ -130,6 +130,17 @@
                                 final ITaskExecutionRunnable taskExecutionRunnable,
                                 final TaskKillLifecycleEvent taskKillEvent) {
         throwExceptionIfStateIsNotMatch(taskExecutionRunnable);
+        final IWorkflowExecutionGraph workflowExecutionGraph = taskExecutionRunnable.getWorkflowExecutionGraph();
```
[the remark this answers is not in the document]
Comment (reele) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/task/statemachine/TaskFailureStateAction.java]: Unused code removed.

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/task/statemachine/TaskFailureStateAction.java (hunk 1 above)
Comment (ruanwenjun) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/task/statemachine/TaskFailureStateAction.java]: Ok, I got you.
Please use 
```java
if (taskExecutionRunnable.isTaskInstanceCanRetry()
                && workflowExecutionGraph.isTaskExecutionRunnableActive(taskExecutionRunnable)) {
```
 to replace 
```java
if (taskExecutionRunnable.isTaskInstanceCanRetry()
        // && workflowExecutionGraph.isTaskExecutionRunnableActive(taskExecutionRunnable)
        ) 
```

You can add a new private method for this, this logic also exist in `killedEventAction`
```java
private boolean isTaskRetrying(
            final IWorkflowExecutionRunnable workflowExecutionRunnable,
            final ITaskExecutionRunnable taskExecutionRunnable) {
        final IWorkflowExecutionGraph workflowExecutionGraph = taskExecutionRunnable.getWorkflowExecutionGraph();
        return taskExecutionRunnable.isTaskInstanceCanRetry()
                && workflowExecutionGraph.isTaskExecutionRunnableActive(taskExecutionRunnable);
    }
```

**Comment by ruanwenjun** [comment]
BTW, we are missing test cases in `WorkflowInstanceStopTestCase`, it's better to add a case `kill a workflow which contains retry task`.

**Comment by reele** [comment]
> BTW, we are missing test cases in `WorkflowInstanceStopTestCase`, it's better to add a case `kill a workflow which contains retry task`.

sure, i'll do that.

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/task/statemachine/TaskFailureStateAction.java (hunk 1 above)
Comment (reele) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/task/statemachine/TaskFailureStateAction.java]: >You can add a new private method for this, this logic also exist in killedEventAction

sure.

but i need test `workflowExecutionGraph.isTaskExecutionRunnableActive(taskExecutionRunnable)` more for some case

Comment (ruanwenjun) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/task/statemachine/TaskFailureStateAction.java:142]: OK, `workflowExecutionGraph.isTaskExecutionRunnableActive` is used to judge whether a task is still `running`, once a task is  inactive, then means it will never be triggered.

Comment (reele) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/task/statemachine/TaskFailureStateAction.java]: i'm a bit confused about this:
when task is failed and going to waiting retry, this task was not removed from `WorkflowExecutionGraph.activeTaskExecutionRunnable`, `activeTaskExecutionRunnable.add()` in `isTaskExecutionRunnableActive` will always return `false`, this result prevented the execution of if-block.

or `WorkflowExecutionGraph.isTaskExecutionRunnableActive` should call `activeTaskExecutionRunnable.contains` instead of `activeTaskExecutionRunnable.add()` ?

Comment (ruanwenjun) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/task/statemachine/TaskFailureStateAction.java]: Yes, this is another bug, we should use `contains` rather than `add` here. You can fix this in this PR or submib another pr.

Comment (ruanwenjun) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/task/statemachine/TaskFailureStateAction.java]: BTW, it's better to add a judge method `isTaskRetrying (ITaskExecutionRunnable taskExecutionRunnable)` at `IWorkflowExecutionGraph`.
```java
public boolean isTaskExecutionRunnableRetrying(final ITaskExecutionRunnable taskExecutionRunnable) {
        if (!taskExecutionRunnable.isTaskInstanceInitialized()) {
            return false;
        }
        final TaskInstance taskInstance = taskExecutionRunnable.getTaskInstance();
        return taskInstance.getState() == TaskExecutionStatus.FAILURE && taskExecutionRunnable.isTaskInstanceCanRetry() && isTaskExecutionRunnableActive(taskExecutionRunnable);
    }
```

Comment (reele) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/task/statemachine/TaskFailureStateAction.java]: ok!

**Comment by reele** [comment]
@ruanwenjun
Test cases added, and passed all test in master and worker.

**Review by ruanwenjun — DISMISSED** [review]
High quality PR, looks pretty good.

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/task/statemachine/TaskFailureStateAction.java [hunk 3]
```diff
@@ -179,4 +185,11 @@
     public TaskExecutionStatus matchState() {
         return TaskExecutionStatus.FAILURE;
     }
+
+    private boolean isTaskRetrying(
+                                   final IWorkflowExecutionRunnable workflowExecutionRunnable,
```
[the remark this answers is not in the document]
Comment (reele) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/task/statemachine/TaskFailureStateAction.java]: redundant code removed.

**Comment by reele** [comment]
> High quality PR, looks pretty good.

@ruanwenjun 
thx, there is a new commit to remove the redundant code

**Review by ruanwenjun — APPROVED** [review]

**Review by SbloodyS — APPROVED** [review]
+1
