### PR TITLE
[Fix-17109] Recovered workflow host may incorrect

### LINKED ISSUE #17109: [Bug] [AbstractCommandHandler] Workflow's host may incorrect after recover, cause api operation failed.
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

when recover/failover a workflow from running/failed/stopped/paused state in multi master cluster, the host didn't set to new master's address, the operation may failed.

if old master is not exist, server will report `Connection refused`, if old master exist, server will report `Cannot find the WorkflowExecuteRunnable`

Image

Image

```
2025-03-22 18:51:19.676 ERROR [qtp742969054-35] o.a.d.a.e.w.StopWorkflowInstanceExecutorDelegate:[98] - WorkflowInstance: sleep-20250321085059987 stop failed
org.apache.dolphinscheduler.extract.base.exception.RemoteException: Call method to Host(ip=10.0.6.23, port=15678) failed
	at org.apache.dolphinscheduler.extract.base.client.NettyRemotingClient.sendSync(NettyRemotingClient.java:147)
	at org.apache.dolphinscheduler.extract.base.client.SyncClientMethodInvoker.invoke(SyncClientMethodInvoker.java:51)
	at org.apache.dolphinscheduler.extract.base.client.ClientInvocationHandler.invoke(ClientInvocationHandler.java:56)
	at com.sun.proxy.$Proxy830.stopWorkflowInstance(Unknown Source)
	at org.apache.dolphinscheduler.api.executor.workflow.StopWorkflowInstanceExecutorDelegate.stopInMaster(StopWorkflowInstanceExecutorDelegate.java:87)
	at org.apache.dolphinscheduler.api.executor.workflow.StopWorkflowInstanceExecutorDelegate.execute(StopWorkflowInstanceExecutorDelegate.java:52)
	at org.apache.dolphinscheduler.api.executor.workflow.StopWorkflowInstanceExecutorDelegate$StopWorkflowInstanceOperation.execute(StopWorkflowInstanceExecutorDelegate.java:127)

...

Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /10.0.6.23:15678
Caused by: java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:716)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.lang.Thread.run(Thread.java:750)
```

### What you expected to happen

.

### How to reproduce

in multi master cluster, run a workflow, stop (and start) the master which running the workflow, stop workflow in web

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by reele**
fix #17109

## Brief change log

add `sethost` in `RecoverFailureTaskCommandHandler` and `WorkflowFailoverCommandHandler`

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

## Pull Request Notice
[Pull Request Notice](https://github.com/apache/dolphinscheduler/blob/dev/docs/docs/en/contribute/join/pull-request.md)

If your pull request contains incompatible change, you should also add it to `docs/docs/en/guide/upgrade/incompatible.md`

### CODE REVIEW

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/executor/workflow/StopWorkflowInstanceExecutorDelegate.java [hunk 1]
```diff
@@ -95,6 +95,7 @@ void stopInMaster(WorkflowInstance workflowInstance) {
         } catch (ServiceException e) {
             throw e;
         } catch (Exception e) {
+            log.error("WorkflowInstance: {} stop failed", workflowInstance.getName(), e);
```
Comment (SbloodyS) [inline dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/executor/workflow/StopWorkflowInstanceExecutorDelegate.java]:
```suggestion
            log.error("WorkflowInstance stop failed, workflowInstanceId: {}, workflowInstanceName: {}", workflowInstance.getId(), workflowInstance.getName(), e);
```

**Review by yingh0ng — COMMENTED** [review]
LGTM

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/executor/workflow/StopWorkflowInstanceExecutorDelegate.java [hunk 2]
```diff
@@ -95,6 +95,7 @@ void stopInMaster(WorkflowInstance workflowInstance) {
         } catch (ServiceException e) {
             throw e;
         } catch (Exception e) {
+            log.error("WorkflowInstance stop failed, workflowInstanceId: {}, workflowInstanceName: {}", workflowInstance.getId(), workflowInstance.getName(), e);
```
Comment (ruanwenjun) [inline dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/executor/workflow/StopWorkflowInstanceExecutorDelegate.java]: Can we remove this log? Since the exception stack will be logged by aspect.

**Review by ruanwenjun — DISMISSED** [review]
LGTM, good catch.

**Comment by ruanwenjun** [comment]
Please fix the code style.

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/executor/workflow/StopWorkflowInstanceExecutorDelegate.java (hunk 2 above)
Comment (reele) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/executor/workflow/StopWorkflowInstanceExecutorDelegate.java]: the following ServiceException didn't contain the original call stack, it won't print to api log, so i added this.

Comment (reele) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/executor/workflow/StopWorkflowInstanceExecutorDelegate.java]: it's not a good way, i'll remove it first.

**Comment by reele** [comment]
> Please fix the code style.

fixed

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/executor/workflow/StopWorkflowInstanceExecutorDelegate.java (hunk 2 above)
Comment (ruanwenjun) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/executor/workflow/StopWorkflowInstanceExecutorDelegate.java]: Ok, I got you, since ServiceException are seems as expected exception, although it contains the origin stack, but will not log, so we need to change the aspect code to log the exception stack.

**Review by ruanwenjun — APPROVED** [review]

**Review by SbloodyS — APPROVED** [review]
+1
