### PR TITLE
[Fix][Script] Fix wrong type of variable workersGroupMap, which will …

### LINKED ISSUE #8004: [Bug] [Script]The script of install.sh can only start one work-server node
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

image
To be exact, there is a problem with the script of start-all.sh

### What you expected to happen

Above

### How to reproduce

Above

### Anything else

None

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by paul8263**
…result in failing to start all workers.

## Purpose of the pull request

Fix wrong type of variable workersGroupMap, which will result in failing to start all workers. Also fix the same issue in scp-hosts.sh, status-all.sh and stop-all.sh.

This PR will close: [ISSUE-8004](https://github.com/apache/dolphinscheduler/issues/8004)

## Brief change log

- script/scp-hosts.sh
- script/start-all.sh
- script/status-all.sh
- script/stop-all.sh

## Verify this pull request

This pull request is code cleanup without any test coverage.

### CODE REVIEW

File: script/scp-hosts.sh [hunk 1]
```diff
@@ -28,6 +28,7 @@ if [[ "$OSTYPE" == "darwin"* ]]; then
 fi
 
 workersGroup=(${workers//,/ })
+declare -A workersGroupMap
```
Comment (SbloodyS) [inline script/scp-hosts.sh]: ```declare -A``` is not working in ```mac``` system.

I think a new implementation is needed.

**Review by SbloodyS — CHANGES_REQUESTED** [review]

File: script/scp-hosts.sh (hunk 1 above)
Comment (paul8263) [reply script/scp-hosts.sh]: Hi @SbloodyS ,
Bash version on Mac is 3.x while on Linux its verion is usually 4.x +. Bash 3.x does not support `declare -A`.

If we have to support Bash 3.x, we need to avoid declaring a variable as map.

Comment (paul8263) [reply script/scp-hosts.sh]: We can replace the map with two arrays, with assigning the key value pair the same index. However it seems that the worker groups are not needed in those scripts. Can I just remove worker groups and add them back if they were required in future versions?

Comment (SbloodyS) [reply script/scp-hosts.sh]: Sorry for late reply. Yes. You can remove worker groups since it is not currently used. @paul8263

File: script/scp-hosts.sh [hunk 2]
```diff
@@ -47,11 +42,17 @@ do
...
+    fi
+  done
+
   for dsDir in bin master-server worker-server alert-server api-server ui
   do
-    # if worker in workersGroupMap
-    if [[ "${workersGroupMap[${host}]}" ]]; then
-      echo "export WORKER_GROUPS_0=${workersGroupMap[${host}]}" >> worker-server/bin/dolphinscheduler_env.sh
+    if [[ ! -z ${workerIndex+x} ]]; then
+      echo "export WORKER_GROUPS_0=${groupNames[$workerIndex]}" >> worker-server/bin/dolphinscheduler_env.sh
```
Comment (SbloodyS) [inline script/scp-hosts.sh]: This path has change to ```worker-server/conf/application.yaml```. And the variables ```WORKER_GROUPS_0``` is no longer exists.
https://github.com/apache/dolphinscheduler/blob/a6c14fb23369ae37a1f5f0232ace90fa7a39435f/dolphinscheduler-worker/src/main/resources/application.yaml#L72-L73

File: script/scp-hosts.sh [hunk 3]
```diff
@@ -47,11 +42,17 @@ do
...
+      break
+    fi
+  done
+
   for dsDir in bin master-server worker-server alert-server api-server ui
   do
-    # if worker in workersGroupMap
-    if [[ "${workersGroupMap[${host}]}" ]]; then
-      echo "export WORKER_GROUPS_0=${workersGroupMap[${host}]}" >> worker-server/bin/dolphinscheduler_env.sh
+    if [[ ! -z ${workerIndex+x} ]]; then
```
Comment (SbloodyS) [inline script/scp-hosts.sh]: Why do I need a default value of ```x``` here?

File: script/scp-hosts.sh (hunk 2 above)
Comment (paul8263) [reply script/scp-hosts.sh]: So can I simply remove line 53 and 54 as it has already been defined in each worker's application.yaml?

File: script/scp-hosts.sh (hunk 3 above)
Comment (paul8263) [reply script/scp-hosts.sh]: It is a way to test whether workerIndex has been defined (The IP were included in workers or not ). If we don't need this I will remove it.

File: script/scp-hosts.sh (hunk 2 above)
Comment (SbloodyS) [reply script/scp-hosts.sh]: No. we should adapt this logic to ```application.yaml```

File: script/scp-hosts.sh (hunk 3 above)
Comment (SbloodyS) [reply script/scp-hosts.sh]: Would it be better to use ```if [[ -n ${workerIndex} ]]```?

Comment (paul8263) [reply script/scp-hosts.sh]: Yes. I wrongly used two negative conditions (`! -z`). I will replace it.

**Review by SbloodyS — APPROVED** [review]
LGTM

**Comment by SbloodyS** [comment]
@caishunfeng @kezhenxu94 Do you have time to take a look at this PR? Thanks.

**Review by kezhenxu94 — APPROVED** [review]
Thanks!
