### PR TITLE
[fix-#14447]The judgment in k8sUtils#getPodLog is not accurate

### LINKED ISSUE #14447: [Bug] [K8S-Task] The judgment in ```k8sUtils#getPodLog``` is not accurate
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

The judgment in ```k8sUtils#getPodLog``` is not accurate because some pods may also run in the same namespace as the pods created by DS. Therefore, the naming rules for pods may not necessarily be the same as those generated by DS.

### What you expected to happen

right

### How to reproduce

filter 

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by fuchanghai**
## Purpose of the pull request

plz close : #14447 

## Verify this pull request

This pull request is code cleanup without any test coverage.

### CODE REVIEW

File: dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/utils/K8sUtils.java [hunk 1]
```diff
@@ -96,7 +96,7 @@ public String getPodLog(String jobName, String namespace) {
             String podName = null;
             for (Pod pod : podList) {
                 podName = pod.getMetadata().getName();
-                if (jobName.equals(podName.substring(0, pod.getMetadata().getName().lastIndexOf("-")))) {
+                if (podName.contains("-") && jobName.equals(podName.substring(0, podName.lastIndexOf("-")))) {
```
Comment (Radeity) [inline dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/utils/K8sUtils.java:99]: May I ask why you add this judgement which seems more strict, can you give an example about it?

Comment (fuchanghai) [reply dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/utils/K8sUtils.java:99]: hi @Radeity because some pods may also run in the same namespace as the pods created by DS. Therefore, the naming rules for pods may not necessarily be the same as those generated by DS.

**Comment by zhongjiajie** [comment]
PTAL @Radeity

**Review by Radeity — APPROVED** [review]
