### PR TITLE
[Fix-17971] Fix ProcedureTask can not pass out parameter and can not execute query procedure.

### LINKED ISSUE #17971: [Bug] [worker] When a stored procedure has no return value but a custom OUT parameter is set, the Switch node cannot obtain the parameter
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Based on version 3.3.2 (the [Fix-17967](https://github.com/apache/dolphinscheduler/pull/17968) patch has been applied) (Fix Parameter passing feature is unavailable in Procedure Task), when a stored procedure is configured with custom OUT parameters but no return value, the Switch node fails to retrieve these parameters. This issue does not occur in version 3.2.2.

#Stored Procedure Node Configuration

Image

#Switch Node Configuration

Image

#error log of Switch Node 

[LOG-PATH]: /opt/apache-dolphinscheduler-3.3.2-bin/master-server/logs/20260211/165236478352384/5/45/170.log, [HOST]: xx.xx.xx.xxxx:5678
2026-02-11 15:16:52.185 INFO  [shared-task-executor-container-worker-5] - 🐬 Initialize Task Context
2026-02-11 15:16:52.193 INFO  [shared-task-executor-container-worker-5] - 🐬 Load Task Instance Plugin
2026-02-11 15:16:52.193 INFO  [shared-task-executor-container-worker-5] - Success initialize parameters: 
{
  "localParams" : [ ],
  "varPool" : [ ],
  "switchResult" : {
    "dependTaskList" : [ {
      "condition" : "${outpara1} == '0'",
      "nextNode" : 165236478349314
    }, {
      "condition" : "${outpara1} != '0'",
      "nextNode" : 165236478349316
    } ],
    "nextNode" : null
  },
  "nextBranch" : null
}
2026-02-11 15:16:52.193 INFO  [shared-task-executor-container-worker-5] - Initialized task plugin instance: SWITCH successfully
2026-02-11 15:16:52.193 INFO  [shared-task-executor-container-worker-5] - 🐬 Execute Task Instance
2026-02-11 15:16:52.193 INFO  [shared-task-executor-container-worker-5] - Begin to execute switch item: SwitchResultVo(condition=${outpara1} == '0', nextNode=165236478349314) 
2026-02-11 15:16:52.193 INFO  [shared-task-executor-container-worker-5] - Format condition sentence::${outpara1} == "0" successfully
2026-02-11 15:16:52.213 INFO  [shared-task-executor-container-worker-5] - Execute switch item: SwitchResultVo(condition=${outpara1} == '0', nextNode=165236478349314) failed
javax.script.ScriptException: <eval>:1:118 Expected ; but found {
Object.defineProperty(this, 'engine', {});Object.defineProperty(this, 'context', {});delete this.__noSuchProperty__;$ {
                                                                                                                      ^ in <eval> at line number 1 at column number 118
	at jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:470)
	at jdk.nashorn.api.scripting.NashornScriptEngine.compileImpl(NashornScriptEngine.java:537)
	at jdk.nashorn.api.scripting.NashornScriptEngine.compileImpl(NashornScriptEngine.java:524)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:402)
	at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:155)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at delight.nashornsandbox.internal.EvaluateOperation.executeScriptEngineOperation(EvaluateOperation.java:47)
	at delight.nashornsandbox.internal.NashornSandboxImpl.executeSandboxedOperation(NashornSandboxImpl.java:284)
	at delight.nashornsandbox.internal.NashornSandboxImpl.eval(NashornSandboxImpl.java:267)
	at delight.nashornsandbox.internal.NashornSandboxImpl.eval(NashornSandboxImpl.java:231)
	at org.apache.dolphinscheduler.server.master.utils.SwitchTaskUtils.evaluate(SwitchTaskUtils.java:78)
	at org.apache.dolphinscheduler.server.master.engine.executor.plugin.switchtask.SwitchLogicTask.calculateSwitchBranch(SwitchLogicTask.java:105)
	at org.apache.dolphinscheduler.server.master.engine.executor.plugin.switchtask.SwitchLogicTask.start(SwitchLogicTask.java:70)
	at org.apache.dolphinscheduler.server.master.engine.executor.LogicTaskExecutor.doTriggerTaskPlugin(LogicTaskExecutor.java:59)
	at org.apache.dolphinscheduler.task.executor.AbstractTaskExecutor.start(AbstractTaskExecutor.java:81)
	at org.apache.dolphinscheduler.task.executor.worker.TaskExecutorWorker.start(TaskExecutorWorker.java:65)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: jdk.nashorn.internal.runtime.ParserException: <eval>:1:118 Expected ; but found {
Object.defineProperty(this, 'engine', {});Object.defineProperty(this, 'context', {});delete this.__noSuchProperty__;$ {
                                                                                                                      ^
	at jdk.nashorn.internal.parser.AbstractParser.error(AbstractParser.java:294)
	at jdk.nashorn.internal.parser.AbstractParser.error(AbstractParser.java:279)
	at jdk.nashorn.internal.parser.AbstractParser.expectDontAdvance(AbstractParser.java:350)
	at jdk.nashorn.internal.parser.AbstractParser.expect(AbstractParser.java:337)
	at jdk.nashorn.internal.parser.Parser.endOfLine(Parser.java:3372)
	at jdk.nashorn.internal.parser.Parser.expressionStatement(Parser.java:1160)
	at jdk.nashorn.internal.parser.Parser.statement(Parser.java:967)
	at jdk.nashorn.internal.parser.Parser.sourceElements(Parser.java:773)
	at jdk.nashorn.internal.parser.Parser.program(Parser.java:709)
	at jdk.nashorn.internal.parser.Parser.parse(Parser.java:283)
	at jdk.nashorn.internal.parser.Parser.parse(Parser.java:249)
	at jdk.nashorn.internal.runtime.Context.compile(Context.java:1284)
	at jdk.nashorn.internal.runtime.Context.compileScript(Context.java:1251)
	at jdk.nashorn.internal.runtime.Context.compileScript(Context.java:627)
	at jdk.nashorn.api.scripting.NashornScriptEngine.compileImpl(NashornScriptEngine.java:535)
	... 19 common frames omitted
2026-02-11 15:16:52.213 INFO  [shared-task-executor-container-worker-5] - Begin to execute switch item: SwitchResultVo(condition=${outpara1} != '0', nextNode=165236478349316) 
2026-02-11 15:16:52.213 INFO  [shared-task-executor-container-worker-5] - Format condition sentence::${outpara1} != "0" successfully
2026-02-11 15:16:52.222 INFO  [shared-task-executor-container-worker-5] - Execute switch item: SwitchResultVo(condition=${outpara1} != '0', nextNode=165236478349316) failed
javax.script.ScriptException: <eval>:1:118 Expected ; but found {
Object.defineProperty(this, 'engine', {});Object.defineProperty(this, 'context', {});delete this.__noSuchProperty__;$ {
                                                                                                                      ^ in <eval> at line number 1 at column number 118
	at jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:470)
	at jdk.nashorn.api.scripting.NashornScriptEngine.compileImpl(NashornScriptEngine.java:537)
	at jdk.nashorn.api.scripting.NashornScriptEngine.compileImpl(NashornScriptEngine.java:524)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:402)
	at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:155)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at delight.nashornsandbox.internal.EvaluateOperation.executeScriptEngineOperation(EvaluateOperation.java:47)
	at delight.nashornsandbox.internal.NashornSandboxImpl.executeSandboxedOperation(NashornSandboxImpl.java:284)
	at delight.nashornsandbox.internal.NashornSandboxImpl.eval(NashornSandboxImpl.java:267)
	at delight.nashornsandbox.internal.NashornSandboxImpl.eval(NashornSandboxImpl.java:231)
	at org.apache.dolphinscheduler.server.master.utils.SwitchTaskUtils.evaluate(SwitchTaskUtils.java:78)
	at org.apache.dolphinscheduler.server.master.engine.executor.plugin.switchtask.SwitchLogicTask.calculateSwitchBranch(SwitchLogicTask.java:105)
	at org.apache.dolphinscheduler.server.master.engine.executor.plugin.switchtask.SwitchLogicTask.start(SwitchLogicTask.java:70)
	at org.apache.dolphinscheduler.server.master.engine.executor.LogicTaskExecutor.doTriggerTaskPlugin(LogicTaskExecutor.java:59)
	at org.apache.dolphinscheduler.task.executor.AbstractTaskExecutor.start(AbstractTaskExecutor.java:81)
	at org.apache.dolphinscheduler.task.executor.worker.TaskExecutorWorker.start(TaskExecutorWorker.java:65)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: jdk.nashorn.internal.runtime.ParserException: <eval>:1:118 Expected ; but found {
Object.defineProperty(this, 'engine', {});Object.defineProperty(this, 'context', {});delete this.__noSuchProperty__;$ {
                                                                                                                      ^
	at jdk.nashorn.internal.parser.AbstractParser.error(AbstractParser.java:294)
	at jdk.nashorn.internal.parser.AbstractParser.error(AbstractParser.java:279)
	at jdk.nashorn.internal.parser.AbstractParser.expectDontAdvance(AbstractParser.java:350)
	at jdk.nashorn.internal.parser.AbstractParser.expect(AbstractParser.java:337)
	at jdk.nashorn.internal.parser.Parser.endOfLine(Parser.java:3372)
	at jdk.nashorn.internal.parser.Parser.expressionStatement(Parser.java:1160)
	at jdk.nashorn.internal.parser.Parser.statement(Parser.java:967)
	at jdk.nashorn.internal.parser.Parser.sourceElements(Parser.java:773)
	at jdk.nashorn.internal.parser.Parser.program(Parser.java:709)
	at jdk.nashorn.internal.parser.Parser.parse(Parser.java:283)
	at jdk.nashorn.internal.parser.Parser.parse(Parser.java:249)
	at jdk.nashorn.internal.runtime.Context.compile(Context.java:1284)
	at jdk.nashorn.internal.runtime.Context.compileScript(Context.java:1251)
	at jdk.nashorn.internal.runtime.Context.compileScript(Context.java:627)
	at jdk.nashorn.api.scripting.NashornScriptEngine.compileImpl(NashornScriptEngine.java:535)
	... 19 common frames omitted
2026-02-11 15:16:52.222 INFO  [shared-task-executor-container-worker-5] - All switch item is not satisfied
2026-02-11 15:16:52.222 INFO  [shared-task-executor-container-worker-5] - Begin to move to the default branch
2026-02-11 15:16:52.223 ERROR [shared-task-executor-container-worker-5] - LogicTaskExecutor{id=170, name=判断是否成功, stat=RUNNING} execute failed
java.lang.IllegalArgumentException: The default branch is empty, please check the switch task configuration
	at org.apache.dolphinscheduler.server.master.engine.executor.plugin.switchtask.SwitchLogicTask.moveToDefaultBranch(SwitchLogicTask.java:82)
	at org.apache.dolphinscheduler.server.master.engine.executor.plugin.switchtask.SwitchLogicTask.calculateSwitchBranch(SwitchLogicTask.java:119)
	at org.apache.dolphinscheduler.server.master.engine.executor.plugin.switchtask.SwitchLogicTask.start(SwitchLogicTask.java:70)
	at org.apache.dolphinscheduler.server.master.engine.executor.LogicTaskExecutor.doTriggerTaskPlugin(LogicTaskExecutor.java:59)
	at org.apache.dolphinscheduler.task.executor.AbstractTaskExecutor.start(AbstractTaskExecutor.java:81)
	at org.apache.dolphinscheduler.task.executor.worker.TaskExecutorWorker.start(TaskExecutorWorker.java:65)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
2026-02-11 15:16:52.450 INFO  [LogicTaskExecutorEventBusCoordinator-eventbus-coordinator-worker-0] - 🐬 Finalize Task Instance
2026-02-11 15:16:52.452 INFO  [LogicTaskExecutorEventBusCoordinator-eventbus-coordinator-worker-0] - FINALIZE_SESSION

### What you expected to happen

When no value is assigned to the output parameter in the stored procedure, the Switch node can obtain the default value of the custom parameter from the Stored Procedure node.

### How to reproduce

Based on version 3.3.2 (the [Fix-17967](https://github.com/apache/dolphinscheduler/pull/17968)  patch has been applied)(Fix Parameter passing feature is unavailable in Procedure Task)

#Stored Procedure Node Configuration

Image

#Switch Node Configuration

Image

#error log of Switch Node 

### Anything else

_No response_

### Version

3.3.2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### LINKED ISSUE #17972: [Bug] [worker] Error when executing Stored Procedure node with SELECT statement
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Based on version 3.3.2 (the [Fix-17967] patch has been applied https://github.com/apache/dolphinscheduler/pull/17968 )(Fix Parameter passing feature is unavailable in Procedure Task)

When a stored procedure contains a SELECT statement, an error is thrown when executing the Stored Procedure node

Image

CREATE OR REPLACE Procedure aSP_test20260211(

)As
	V_Term date;
	v_guid varchar2(200);
	v_cur_date date;
    v_proc_date date;
	v_tran varchar(10);
	e_Exception Exception;
BEGIN
	
  select 123 from dual;
  
  Commit;
End;

procedure node configuration:

Image

err log:
/opt/apache-dolphinscheduler-3.3.2-bin/worker-server/logs/20260211/165236478352384/8/47/172.log, [HOST]: xx.xx.xx.xx:1234
2026-02-11 15:28:38.149 INFO  - 🐬 Initialize Task Context
2026-02-11 15:28:38.262 INFO  - Current tenant is default tenant, will use bootstrap user: root to execute the task
2026-02-11 15:28:38.262 INFO  - TenantCode: root check successfully
2026-02-11 15:28:38.264 INFO  - TaskInstance working directory: /tmp/dolphinscheduler/exec/process/172 create successfully
2026-02-11 15:28:38.264 INFO  - Download resources successfully: 
ResourceContext(resourceItemMap={})
2026-02-11 15:28:38.267 INFO  - 🐬 Load Task Instance Plugin
2026-02-11 15:28:38.267 INFO  - Initialize procedure task params {
  "localParams" : [ ],
  "varPool" : [ ],
  "type" : "DAMENG",
  "datasource" : 1,
  "outProperty" : null,
  "method" : "call aSP_test20260211();"
}
2026-02-11 15:28:38.267 INFO  - Initialized physicalTask: PROCEDURE successfully
2026-02-11 15:28:38.267 INFO  - Set taskVarPool: null successfully
2026-02-11 15:28:38.269 INFO  - 🐬 Execute Task Instance
2026-02-11 15:28:38.269 INFO  - procedure type : DAMENG, datasource : 1, method : call aSP_test20260211(); , localParams : []
2026-02-11 15:28:38.269 WARN  - Connect strings must start with jdbc:snowflake://
2026-02-11 15:28:38.275 ERROR - procedure task error
dm.jdbc.driver.DMException: 语句类型不匹配
	at dm.jdbc.driver.DBError.throwz(SourceFile:844)
	at dm.jdbc.driver.DmdbPreparedStatement.do_executeUpdate(SourceFile:546)
	at dm.jdbc.driver.DmdbPreparedStatement$3.run(SourceFile:1418)
	at dm.jdbc.driver.DmdbPreparedStatement$3.run(SourceFile:1)
	at dm.jdbc.driver.DmdbPreparedStatement.executeUpdate(SourceFile:1428)
	at org.apache.dolphinscheduler.plugin.task.procedure.ProcedureTask.handle(ProcedureTask.java:115)
	at org.apache.dolphinscheduler.server.worker.executor.PhysicalTaskExecutor.doTriggerTaskPlugin(PhysicalTaskExecutor.java:77)
	at org.apache.dolphinscheduler.task.executor.AbstractTaskExecutor.start(AbstractTaskExecutor.java:81)
	at org.apache.dolphinscheduler.task.executor.worker.TaskExecutorWorker.start(TaskExecutorWorker.java:65)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
2026-02-11 15:28:38.276 ERROR - PhysicalTaskExecutor{id=172, name=执行存储过程, stat=RUNNING} execute failed
org.apache.dolphinscheduler.plugin.task.api.TaskException: Execute procedure task failed
	at org.apache.dolphinscheduler.plugin.task.procedure.ProcedureTask.handle(ProcedureTask.java:126)
	at org.apache.dolphinscheduler.server.worker.executor.PhysicalTaskExecutor.doTriggerTaskPlugin(PhysicalTaskExecutor.java:77)
	at org.apache.dolphinscheduler.task.executor.AbstractTaskExecutor.start(AbstractTaskExecutor.java:81)
	at org.apache.dolphinscheduler.task.executor.worker.TaskExecutorWorker.start(TaskExecutorWorker.java:65)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: dm.jdbc.driver.DMException: 语句类型不匹配
	at dm.jdbc.driver.DBError.throwz(SourceFile:844)
	at dm.jdbc.driver.DmdbPreparedStatement.do_executeUpdate(SourceFile:546)
	at dm.jdbc.driver.DmdbPreparedStatement$3.run(SourceFile:1418)
	at dm.jdbc.driver.DmdbPreparedStatement$3.run(SourceFile:1)
	at dm.jdbc.driver.DmdbPreparedStatement.executeUpdate(SourceFile:1428)
	at org.apache.dolphinscheduler.plugin.task.procedure.ProcedureTask.handle(ProcedureTask.java:115)
	... 8 common frames omitted
2026-02-11 15:28:38.492 INFO  - 🐬 Finalize Task Instance
2026-02-11 15:28:38.493 INFO  - FINALIZE_SESSION
2026-02-11 15:28:38.494 INFO  - Deleted task exec directory: /tmp/dolphinscheduler/exec/process/172

### What you expected to happen

The procedure node executes successfully.

### How to reproduce

CREATE OR REPLACE Procedure aSP_test20260211(

)As
	V_Term date;
	v_guid varchar2(200);
	v_cur_date date;
    v_proc_date date;
	v_tran varchar(10);
	e_Exception Exception;
BEGIN
  
  select 123 from dual;
  
  Commit;
End;

procedure node configuration:

Image

### Anything else

_No response_

### Version

3.3.2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by ruanwenjun**
## Purpose of the pull request

close #17971 
close #17972

## Brief change log

1. Optimize `ProcedureParameters`, remove get/set/toString method, use lombok `@Data`.
2. Remove `getResourceFilesList` method, since this doesn't change the parent implementation.
3. Remove `outProperty` since this doesn't help.
4. After ProcedureTask successed, merge the varpool with local param.
5. Make out parameter defined at task local param can pass to worker.

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

## Pull Request Notice
[Pull Request Notice](https://github.com/apache/dolphinscheduler/blob/dev/docs/docs/en/contribute/join/pull-request.md)

If your pull request contains incompatible change, you should also add it to `docs/docs/en/guide/upgrade/incompatible.md`

### CODE REVIEW

File: dolphinscheduler-task-plugin/dolphinscheduler-task-procedure/src/main/java/org/apache/dolphinscheduler/plugin/task/procedure/ProcedureTask.java [hunk 1]
```diff
@@ -99,29 +102,27 @@ public void handle(TaskCallBack taskCallBack) throws TaskException {
         ConnectionParam connectionParams =
                 dataSourceProcessor.createConnectionParams(procedureTaskExecutionContext.getConnectionParams());
         try (Connection connection = DataSourceClientProvider.getAdHocConnection(dbType, connectionParams)) {
-            Map<Integer, Property> sqlParamsMap = new HashMap<>();
-            Map<String, Property> paramsMap = taskExecutionContext.getPrepareParamsMap() == null ? Maps.newHashMap()
-                    : taskExecutionContext.getPrepareParamsMap();
-            if (procedureParameters.getOutProperty() != null) {
-                // set out params before format sql
-                paramsMap.putAll(procedureParameters.getOutProperty());
-            }
```
Comment (ruanwenjun) [inline dolphinscheduler-task-plugin/dolphinscheduler-task-procedure/src/main/java/org/apache/dolphinscheduler/plugin/task/procedure/ProcedureTask.java]: The prepareParams already contains localparam, so we don't need to put out param here.

**Comment by ruanwenjun** [comment]
@njnu-seafish @Mrhs121 Please take a look.

File: dolphinscheduler-task-plugin/dolphinscheduler-task-procedure/src/main/java/org/apache/dolphinscheduler/plugin/task/procedure/ProcedureTask.java [hunk 2]
```diff
@@ -154,59 +161,50 @@ public void cancel() throws TaskException {
...
      * @throws Exception Exception
      */
-    private Map<Integer, Property> getOutParameterMap(CallableStatement stmt, Map<Integer, Property> paramsMap,
-                                                      Map<String, Property> totalParamsMap) throws Exception {
+    private Map<Integer, Property> assemblySqlPlaceHolder(CallableStatement stmt,
+                                                          Map<Integer, Property> sqlParams,
+                                                          Map<String, Property> prepareParams) throws Exception {
         Map<Integer, Property> outParameterMap = new HashMap<>();
-        if (procedureParameters.getLocalParametersMap() == null) {
+        if (MapUtils.isEmpty(sqlParams)) {
```
Comment (Mrhs121) [inline dolphinscheduler-task-plugin/dolphinscheduler-task-procedure/src/main/java/org/apache/dolphinscheduler/plugin/task/procedure/ProcedureTask.java:189]: https://github.com/apache/dolphinscheduler/issues/17971 @honkerjha The key fix to solve this issue

**Comment by Mrhs121** [comment]
LGTM

**Comment by njnu-seafish** [comment]
LGTM

**Review by SbloodyS — DISMISSED** [review]
+1

**Review by SbloodyS — APPROVED** [review]
