### PR TITLE
[Fix-7767]Task instance is not deleted while deleting the process instance

### LINKED ISSUE #7767: Delete the log of ‘workflow instance’ The log of ‘task instance’ is not deleted in cascade
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

删除 ‘工作流实例’的日志 ‘任务实例’的日志没有级联删除

### What you expected to happen

删除 ‘工作流实例’的日志 ‘任务实例’的日志级联删除

### How to reproduce

手工删除过 t_ds_task_instance 、t_ds_process_instance、t_ds_relation_process_instance

### Anything else

_No response_

### Version

2.0.1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [ ] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by SbloodyS**
## Purpose of the pull request

close #7767

### CODE REVIEW

File: dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessService.java [hunk 1]
```diff
@@ -529,6 +529,39 @@ public void removeTaskLogFile(Integer processInstanceId) {
...
+        }
+    }
+
+    /**
+     * remove task log file by task instance
+     *
+     * @param taskInstance taskInstance
+     */
+    public void removeTaskLogFile(TaskInstance taskInstance) {
+        try (LogClientService logClient = new LogClientService()) {
```
Comment (caishunfeng) [inline dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessService.java]: It seems that it can be operated by batch and don't have to create logClient and release every time.

Comment (SbloodyS) [reply dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessService.java]: Yes, I'll fix it.

**Comment by SbloodyS** [comment]
@caishunfeng please review again.thx.

**Review by caishunfeng — APPROVED** [review]
LGTM
