### PR TITLE
[fix-10954]Querying the task group list returns empty data

### LINKED ISSUE #10954: [Bug] [TaskGroupOption] Querying the task group list returns empty data
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Querying the task group list returns empty data

### What you expected to happen

Querying the task group list returns data

### How to reproduce

see task group option

### Anything else

image

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by SnowMoon-Dev**
## Brief change log

close [#10954](https://github.com/apache/dolphinscheduler/issues/10954)
## Verify this pull request

Manually verified the change by testing locally

### CODE REVIEW

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TaskGroupServiceImpl.java [hunk 1]
```diff
@@ -189,7 +191,7 @@ public boolean isTheTaskGroupAvailable(int id) {
      */
     @Override
     public Map<String, Object> queryAllTaskGroup(User loginUser, String name, Integer status, int pageNo, int pageSize) {
-        return this.doQuery(loginUser, pageNo, pageSize, loginUser.getUserType().equals(UserType.ADMIN_USER) ? 0 : loginUser.getId(), name, status);
+        return this.doQuery(loginUser, pageNo, pageSize, loginUser.getId(), name, status);
```
Comment (SbloodyS) [inline dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TaskGroupServiceImpl.java:194]: I think we should not change this since admin should be allowed to query all data.

Comment (SnowMoon-Dev) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TaskGroupServiceImpl.java:194]: image
I know that the underlying logic still checks the admin

**Review by SbloodyS — APPROVED** [review]
LGTM
