### PR TITLE
[Fix-17520][TaskExecutor] fix not clear task exec path when set development.state=false in common.properties

### LINKED ISSUE #17520: [Bug] [TaskExecutor] The task execution file is not cleared when development.state is set to false in common.properties
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

1, set development.state=false in common.properties
2, after task is finshed, the task execute file is not cleared. 

### What you expected to happen

1, if development.state=false, will clear the task execute file
2, if development.state=true, will not clear the task execute file

### How to reproduce

1, set development.state=false in common.properties
2, run the task
3, after task is finshed, the task execute file is not cleared. 

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by LourierL**
## Purpose of the pull request

close #17520

## Brief change log

fix bug with modifing AbstractTaskExecutorContainer.handle() after task exec finished

## Verify this pull request

This pull request is code cleanup without any test coverage.

(or)

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

## Pull Request Notice
[Pull Request Notice](https://github.com/apache/dolphinscheduler/blob/dev/docs/docs/en/contribute/join/pull-request.md)

If your pull request contains incompatible change, you should also add it to `docs/docs/en/guide/upgrade/incompatible.md`

### CODE REVIEW

File: dolphinscheduler-task-executor/src/main/java/org/apache/dolphinscheduler/task/executor/container/AbstractTaskExecutorContainer.java [hunk 1]
```diff
@@ -145,4 +149,26 @@
...
+     * Delete task exec Directory if set development.state=false in common.properties explicit
+     * otherwise keep it for debug reason.
+     */
+    private void deleteExecPathIfProduction(ITaskExecutor taskExecutor) {
+        boolean isDev = PropertyUtils.getBoolean(Constants.DEVELOPMENT_STATE, true);
+        if (!isDev) {
+            try {
+                final TaskExecutionContext ctx = taskExecutor.getTaskExecutionContext();
+                final String execPath = (ctx != null ? ctx.getExecutePath() : "");
+                if (!"".equals(execPath)) {
```
[the remark this answers is not in the document]
Comment (LourierL) [reply dolphinscheduler-task-executor/src/main/java/org/apache/dolphinscheduler/task/executor/container/AbstractTaskExecutorContainer.java]: ok, I will use StringUtils.isNotEmpty() api to replace the code here.

File: dolphinscheduler-task-executor/src/main/java/org/apache/dolphinscheduler/task/executor/container/AbstractTaskExecutorContainer.java [hunk 2]
```diff
@@ -98,6 +102,7 @@ public void finalize(final ITaskExecutor taskExecutor) {
         }
         log.info(FINALIZE_SESSION_MARKER, FINALIZE_SESSION_MARKER.toString());
         pushTaskExecutorLogToRemote(taskExecutor);
+        deleteExecPathIfProduction(taskExecutor);
```
Comment (ruanwenjun) [inline dolphinscheduler-task-executor/src/main/java/org/apache/dolphinscheduler/task/executor/container/AbstractTaskExecutorContainer.java]:
```suggestion
        taskExecutor.finalize();
```

File: dolphinscheduler-task-executor/src/main/java/org/apache/dolphinscheduler/task/executor/container/AbstractTaskExecutorContainer.java [hunk 3]
```diff
@@ -145,4 +150,26 @@ private void pushTaskExecutorLogToRemote(final ITaskExecutor taskExecutor) {
...
+                    FileUtils.deleteFile(execPath);
+                    log.info("Deleted task exec directory: {}", execPath);
+                }
+            } catch (Exception e) {
+                log.warn("Failed to delete task exec directory in prod mode.", e);
+            }
+        } else {
+            log.debug("Development mode is on, skip deleting executePath for debug reason");
+        }
+    }
```
Comment (ruanwenjun) [inline dolphinscheduler-task-executor/src/main/java/org/apache/dolphinscheduler/task/executor/container/AbstractTaskExecutorContainer.java]: It's better to add a `finalize` method in `ITaskExecutor` to clear the `taskInstanceWorkingDirectory`.
We can add a method `clearTaskInstanceWorkingDirectory` in `TaskExecutionContextUtils` to do the real clear logic.

Comment (LourierL) [reply dolphinscheduler-task-executor/src/main/java/org/apache/dolphinscheduler/task/executor/container/AbstractTaskExecutorContainer.java]: ok, I understand that will be better. I will invoke the clearTaskInstanceWorkingDirectory() in PhysicalTaskExecutor and do nothing in LogicTaskExecutor. Is that OK?

Comment (ruanwenjun) [reply dolphinscheduler-task-executor/src/main/java/org/apache/dolphinscheduler/task/executor/container/AbstractTaskExecutorContainer.java]: Great, it's OK.

**Comment by njnu-seafish** [comment]
First of all, welcome everyone to join forces in resolving issues and collectively help the community grow.
However, I still have some questions and would like to **further learn about the community rules together**.
This issue has been assigned to me; can others still work on it?
I've always thought the rule was that the assigned person is responsible for solving the issue and submitting the PR.

@ruanwenjun @SbloodyS @LourierL  Welcome to learn and discuss together!

**Comment by LourierL** [comment]
It's my first time to pull a request in this project, and maybe I don't realize something like the assigning rule.
for me It's totally ok that this pull request be handled by the assigner, and it's ok if I can help.
finally, I'm really sorry for that

**Comment by njnu-seafish** [comment]
> It's my first time to pull a request in this project, and maybe I don't realize something like the assigning rule. for me It's totally ok that this pull request be handled by the assigner, and it's ok if I can help. finally, I'm really sorry for that

Wow, you're very welcome to join the DS community family, and I fully support your contribution! Haha, I just wanted to further familiarize myself with and confirm the community rules.

**Comment by SbloodyS** [comment]
For bugfix, this is not a problem, and we will choose one of the best implementations to merge. Of course, when there is a conflict, contributors can also communicate and choose who will carry out bugfix. @LourierL @njnu-seafish

**Comment by ruanwenjun** [comment]
@LourierL LGTM, please fix the code style, you can use `mvn spotless:apply` to fix it.

**Comment by ruanwenjun** [comment]
> First of all, welcome everyone to join forces in resolving issues and collectively help the community grow. However, I still have some questions and would like to **further learn about the community rules together**. This issue has been assigned to me; can others still work on it? I've always thought the rule was that the assigned person is responsible for solving the issue and submitting the PR.
> 
> @ruanwenjun @SbloodyS @LourierL Welcome to learn and discuss together!

@njnu-seafish Sorry, We apologize for the PR conflict here. There aren't actually many restrictions on bug fixes. In my view, code review is just as important as submitting pull requests. In fact, when I first joined the DS community, I haven't submitted any pull requests but only helping review code and checking issues.

**Comment by LourierL** [comment]
@ruanwenjun code coverage failed,may I need to add test method TaskExecutionContextUtilsTest.downloadResourcesIfNeeded()

File: dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/utils/TaskExecutionContextUtils.java [hunk 4]
```diff
@@ -108,4 +111,21 @@ public static ResourceContext downloadResourcesIfNeeded(TaskChannel taskChannel,
         return resourceContext;
     }
 
+    public static void clearTaskInstanceWorkingDirectory(TaskExecutionContext taskExecutionContext) {
+        boolean isDevelopment = PropertyUtils.getBoolean(Constants.DEVELOPMENT_STATE, true);
+        if (!isDevelopment) {
```
Comment (ruanwenjun) [inline dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/utils/TaskExecutionContextUtils.java]: Please move this in `finalizeTask` method, the utils only provide the delete logic here, then you can easilly test this.

Comment (LourierL) [reply dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/utils/TaskExecutionContextUtils.java]: you're right, I will fix this.

**Review by ruanwenjun — APPROVED** [review]
LGTM

**Review by SbloodyS — APPROVED** [review]
+1

**Comment by njnu-seafish** [comment]
> > First of all, welcome everyone to join forces in resolving issues and collectively help the community grow. However, I still have some questions and would like to **further learn about the community rules together**. This issue has been assigned to me; can others still work on it? I've always thought the rule was that the assigned person is responsible for solving the issue and submitting the PR.
> > @ruanwenjun @SbloodyS @LourierL Welcome to learn and discuss together!
> 
> @njnu-seafish Sorry, We apologize for the PR conflict here. There aren't actually many restrictions on bug fixes. In my view, code review is just as important as submitting pull requests. In fact, when I first joined the DS community, I haven't submitted any pull requests but only helping review code and checking issues.

No problem, I completely understand and accept it.  
Welcome everyone to join forces in resolving issues and collectively help the community grow.
