### PR TITLE
[Fix-10918] Close datasource when expire from guava cache

### LINKED ISSUE #10918: [Bug] [DataSource] MySQL Connection number increasing
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

in dolphin worker-server, mysql connection number increasing always, which lead mysql server cannot work.
image

while the mysql connection like below:
image

### What you expected to happen

mysql connection number keep in normal number, 

### How to reproduce

use MySQL DataSource to perform frequent operations, such as query and create table/delete table/update table.

### Anything else

_No response_

### Version

3.0.0-beta-2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by ruanwenjun**
## Purpose of the pull request

If the 

close #10918

## Brief change log

- Add remove listener for guava cache
- Close Datasource when DataSourceClient close.
- Remove extra datasource in HiveDataSourceClient

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

### CODE REVIEW

File: dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-api/src/main/java/org/apache/dolphinscheduler/plugin/datasource/api/plugin/DataSourceClientProvider.java [hunk 1]
```diff
@@ -61,7 +68,7 @@ public static DataSourceClientProvider getInstance() {
     public Connection getConnection(DbType dbType, ConnectionParam connectionParam) throws ExecutionException {
         BaseConnectionParam baseConnectionParam = (BaseConnectionParam) connectionParam;
         String datasourceUniqueId = DataSourceUtils.getDatasourceUniqueId(baseConnectionParam, dbType);
-        logger.info("getConnection datasourceUniqueId {}", datasourceUniqueId);
+        logger.info("Get connection form datasource {}", datasourceUniqueId);
```
Comment (SbloodyS) [inline dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-api/src/main/java/org/apache/dolphinscheduler/plugin/datasource/api/plugin/DataSourceClientProvider.java]:
```suggestion
        logger.info("Get connection from datasource {}", datasourceUniqueId);
```

Comment (ruanwenjun) [reply dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-api/src/main/java/org/apache/dolphinscheduler/plugin/datasource/api/plugin/DataSourceClientProvider.java]: Done

**Review by SbloodyS — APPROVED** [review]
LGTM
