### PR TITLE
[Fix-11583][UI] Fix the API usage of gantt graph

### LINKED ISSUE #11583: [Bug] [UI] Gantt chart does not show
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

**task.status** is expected to get a status string value such as ' SUCCESS ' but the backend returns an object like ' TaskExecutionStatus{code=7, desc=' success'} ' where a mapping is required
image

### What you expected to happen

Open the Gantt chart

### How to reproduce

Open the Gantt chart

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by hezean**
## Purpose of the pull request

Fixes #11583, the backend passed wrong data that cannot be parsed by the frontend.

(The import items were changed because of the spotless check)

## Verify this pull request

This change added tests and can be verified as follows: *Manually verified the change by testing locally.*

### CODE REVIEW

**Comment by hezean** [comment]
@SbloodyS can you help re-run the unit test ci please? I think there may be a flaky test that I tried run the test several times locally without any error

**Comment by SbloodyS** [comment]
> @SbloodyS can you help re-run the unit test ci please? I think there may be a flaky test that I tried run the test several times locally without any error

You can manualy rerun it by `git push` or `close and reopen this pr`.

File: dolphinscheduler-ui/src/views/projects/workflow/instance/gantt/components/gantt-chart.tsx [hunk 1]
```diff
@@ -80,7 +80,7 @@ const GanttChart = defineComponent({
       minTime = minTime < start ? minTime : start
       maxTime = maxTime > end ? maxTime : end
       data[task.status].push({
-        name: task.name,
+        name: task.taskName,
```
Comment (devosend) [inline dolphinscheduler-ui/src/views/projects/workflow/instance/gantt/components/gantt-chart.tsx:83]: You should not change it. Because it is converted from `taskName` to `name` by function `formatGantt`.
image

Comment (hezean) [reply dolphinscheduler-ui/src/views/projects/workflow/instance/gantt/components/gantt-chart.tsx:83]: Thanks for reminding. IMHO we can remove `name` here since it's just a dup of taskName?
Screen Shot 2022-08-29 at 10 35 47

Comment (devosend) [reply dolphinscheduler-ui/src/views/projects/workflow/instance/gantt/components/gantt-chart.tsx:83]: > Thanks for reminding. IMHO we can remove `name` here since it's just a dup of taskName? Screen Shot 2022-08-29 at 10 35 47

sure, you can optimize it.

**Review by labbomb — DISMISSED** [review]
LGTM for the front end

**Comment by devosend** [comment]
Please review the backend @SbloodyS

**Review by SbloodyS — APPROVED** [review]
+1

**Comment by yuanoOo** [comment]
please fix the same bug in branch 3.1.x
