### PR TITLE
[Fix-17451]Fix Parameter passing feature is unavailable in SQL Task

### LINKED ISSUE #17451: [Bug] [Master] Parameter passing feature is unavailable in SQL Task
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Parameter passing feature is unavailable.

Image

test1-task:
Image

test2-task:
Image

log:
Image

### What you expected to happen

 After upstream tasks complete execution, parameters are not merged into global parameters, causing the parameter passing functionality to be unavailable. This feature needs to be restored.

### How to reproduce

--

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Zzih**
## Purpose of the pull request

fix https://github.com/apache/dolphinscheduler/issues/17451

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

## Pull Request Notice
[Pull Request Notice](https://github.com/apache/dolphinscheduler/blob/dev/docs/docs/en/contribute/join/pull-request.md)

If your pull request contains incompatible change, you should also add it to `docs/docs/en/guide/upgrade/incompatible.md`

### CODE REVIEW

**Review by ruanwenjun — COMMENTED** [review]
Please fix this in `SqlTask`
```
taskExecutionContext.setVarPool(sqlParameters.getVarPool());
```
Rather than create a common method.

Before adding the common varpool handling, it is best to modify the task plugin's return result to explicitly return the varpool. Otherwise, we are essentially repeatedly modifying a variable, which is prone to causing problems.

**Comment by ruanwenjun** [comment]
And it's possible to add E2E for this case? This seems to only require adding a new case to the current E2E template.

**Comment by Zzih** [comment]
> Please fix this in `SqlTask`
> 
> ```
> taskExecutionContext.setVarPool(sqlParameters.getVarPool());
> ```
> 
> Rather than create a common method.
> 
> Before adding the common varpool handling, it is best to modify the task plugin's return result to explicitly return the varpool. Otherwise, we are essentially repeatedly modifying a variable, which is prone to causing problems.

Is it about adding varPool replacement in each task (such as `SqlTask`), rather than handling it uniformly in `PhysicalTaskExecutor`?

**Comment by ruanwenjun** [comment]
> > Please fix this in `SqlTask`
> > ```
> > taskExecutionContext.setVarPool(sqlParameters.getVarPool());
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Rather than create a common method.
> > Before adding the common varpool handling, it is best to modify the task plugin's return result to explicitly return the varpool. Otherwise, we are essentially repeatedly modifying a variable, which is prone to causing problems.
> 
> Is it about adding varPool replacement in each task (such as `SqlTask`), rather than handling it uniformly in `PhysicalTaskExecutor`?

Yes

File: dolphinscheduler-task-plugin/dolphinscheduler-task-sql/src/test/java/org/apache/dolphinscheduler/plugin/task/sql/SqlTaskTest.java [hunk 1]
```diff
@@ -173,4 +174,33 @@ void testReplacingSqlHasQuestionMarkAndParams() {
         Assertions.assertEquals(4, sqlParamsMap.size());
         Assertions.assertEquals(expected, formatSql);
     }
+
+    @Test
+    void testVarPoolSetting() {
+        // 创建包含OUT参数的SqlParameters
```
Comment (ruanwenjun) [inline dolphinscheduler-task-plugin/dolphinscheduler-task-sql/src/test/java/org/apache/dolphinscheduler/plugin/task/sql/SqlTaskTest.java]: Please remove Chinese here.

**Review by ruanwenjun — APPROVED** [review]
LGTM

**Review by zhongjiajie — APPROVED** [review]

**Review by SbloodyS — APPROVED** [review]
+1
