### PR TITLE
[Bug] [Master] Workflow keep running when task has no id

### LINKED ISSUE #14314: [Bug] [Master] Workflow keep running when task has no id
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

image
When readyToSubmitTaskQueue contains task without id, will always running

### What you expected to happen

Stop running task

### How to reproduce

Change completeTaskMap to completeTaskSet

### Anything else

Same as #11930

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by qingwli**
- close #14314

### CODE REVIEW

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java [hunk 1]
```diff
@@ -199,10 +199,10 @@ public class WorkflowExecuteRunnable implements Callable<WorkflowSubmitStatus> {
     private final Map<Long, Integer> errorTaskMap = new ConcurrentHashMap<>();
 
     /**
-     * complete task map, taskCode as key, taskInstanceId as value
+     * complete task set
      * in a DAG, only one taskInstance per taskCode is valid
      */
-    private final Map<Long, Integer> completeTaskMap = new ConcurrentHashMap<>();
+    private final Set<Long> completeTaskSet = Sets.newConcurrentHashSet();
```
Comment (rickchengx) [inline dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java:205]: May I ask why to use `set` rather than `map` ?

Comment (qingwli) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java:205]: Please see https://github.com/apache/dolphinscheduler/issues/14314

Comment (qingwli) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java:205]: This map maybe put some task has code but has no id. And will throw npe, and will retry all the time

Comment (rickchengx) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java:205]: Yes, I got you. Could we just check not to put these task (which has no id) into the map ? Since other task collections are also `map`

image

Comment (qingwli) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java:205]: WDYT @ruanwenjun

Comment (ruanwenjun) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java:205]: Use set is ok here. Additional, this class will be refactor future, use set is a hot fix.

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java [hunk 2]
```diff
@@ -2065,8 +2090,8 @@ private boolean isNewProcessInstance() {
         return false;
     }
 
-    public Map<Long, Integer> getCompleteTaskMap() {
-        return completeTaskMap;
+    public Set<Long> getCompleteTaskSet() {
```
Comment (ruanwenjun) [inline dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java]:
```suggestion
    public Set<Long> getCompleteTaskCodes() {
```

**Review by ruanwenjun — DISMISSED** [review]
LGTM

**Review by rickchengx — DISMISSED** [review]
LGTM, wait for CI

**Comment by ruanwenjun** [comment]
Please solve the UT.
image

**Review by rickchengx — APPROVED** [review]
