### PR TITLE
[Fix-16906] Fix tenant has no permission to execute kill command

### LINKED ISSUE #16906: [Bug] [task api] stop spark job on yarn failed
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

I try to stop spark job on yarn but failed.
Logs show that kill yarn application failed with ExitCodeException.  The exit code is 137. Thouth dolphin task instance is set to terminated, spark job is still running.
I then set dolphinscheduler to develop mode, reserve the .kill file and execute command 'sh /xxx/xxx/xxx.kill' manually with user dolphinscheduler. It works, spark job is terminated as expected. 
Is there any difference between dolphinscheduler and execute .kill file manually?
there's logs: 
dolpin_log1
dolpin_log2

### What you expected to happen

dolphinscheduler terminate spark job successfully.  

### How to reproduce

Any attemp to stop spark job failed  in my env. 
I don't know what env config should I provide to help solve the problem. 

### Anything else

_No response_

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by ruanwenjun**
## Purpose of the pull request

close #16906 

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

## Pull Request Notice
[Pull Request Notice](https://github.com/apache/dolphinscheduler/blob/dev/docs/docs/en/contribute/join/pull-request.md)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

**Review by SbloodyS — DISMISSED** [review]
LGTM

File: dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/utils/FileUtilsTest.java [hunk 1]
```diff
@@ -143,4 +143,8 @@ public void tearDown() {
         FileUtils.deleteFile("test");
     }
 
+    @Test
+    void createFileWith755() throws IOException {
+        FileUtils.createFileWith755(Paths.get("/Users/wenjun/a/b/test.txt"));
```
Comment (Gallardot) [inline dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/utils/FileUtilsTest.java]: Perhaps a temporary directory would be more appropriate

Comment (ruanwenjun) [reply dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/utils/FileUtilsTest.java]: Yes, this change should be removed, this is my test code.

**Review by SbloodyS — APPROVED** [review]

**Review by Gallardot — APPROVED** [review]
