### PR TITLE
fix: Save task seatunnel error

### LINKED ISSUE #14114: [Bug] [[Task Plugin]  seatunnel  engine is not available in V3.1.6.
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When When SEATUNNEL_ENGINE\SPARK_V2\FLINKE_V2 engine is selected in seatunnle node ,
the work flow can't be saved,and note an error message:"process node test parameter invaild."
SPARK and FLINK engine is ok!

And I find an error in the api-server log file:
, class: class org.apache.dolphinscheduler.plugin.task.seatunnel.SeatunnelParameters
com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Could not resolve type id 'FLINK_V2' as a subtype of `org.apache.dolphinscheduler.plugin.task.seatunnel.SeatunnelParameters`: known type ids = [FLINK, SPARK, SeatunnelParameters]

### What you expected to happen

seatunnl engine is able to  work.

### How to reproduce

I tried cluster mode ,and standalone mode.Both will throw an error.

### Anything else

_No response_

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by zhongjiajie**
* fix error when save task seatunnel
* support all version of seatunnel startup script by using string instead of engine enum
* Remove unnecessary code in task seatunnel

closed #14114

### CODE REVIEW

File: dolphinscheduler-task-plugin/dolphinscheduler-task-seatunnel/src/main/java/org/apache/dolphinscheduler/plugin/task/seatunnel/EngineEnum.java [hunk 1]
```diff
@@ -1,40 +0,0 @@
...
- * See the License for the specific language governing permissions and
- * limitations under the License.
- */
-
-package org.apache.dolphinscheduler.plugin.task.seatunnel;
-
-public enum EngineEnum {
-
-    FLINK("${SEATUNNEL_HOME}/bin/start-seatunnel-flink.sh"),
-    SPARK("${SEATUNNEL_HOME}/bin/start-seatunnel-spark.sh"),
```
Comment (zhongjiajie) [inline dolphinscheduler-task-plugin/dolphinscheduler-task-seatunnel/src/main/java/org/apache/dolphinscheduler/plugin/task/seatunnel/EngineEnum.java:23]: delete the enum class due to seatunnel changing its startup script, so currently we have to support

```
seatunnel.sh
start-seatunnel-flink-13-connector-v2.sh
start-seatunnel-flink-15-connector-v2.sh
start-seatunnel-flink-connector-v2.sh
start-seatunnel-flink.sh
start-seatunnel-spark-2-connector-v2.sh
start-seatunnel-spark-3-connector-v2.sh
start-seatunnel-spark-connector-v2.sh
start-seatunnel-spark.sh
```

nine startups in both frontend and backend. Since we do not know whether seatunnel will change their startup script in the future or not. So I think we should remove this enum and just use the startup script name from front-end. please notice we do not ask users manually enter the startup script name because we provide drop-down box for it. Add this just for reducing the code change scope when startup script adding/changing

File: docs/docs/en/guide/task/seatunnel.md [hunk 2]
```diff
@@ -16,7 +16,7 @@ Click [here](https://seatunnel.apache.org/) for more information about `Apache S
 [//]: # (- Please refer to [DolphinScheduler Task Parameters Appendix]&#40;appendix.md#default-task-parameters&#41; `Default Task Parameters` section for default parameters.)
 
 - Please refer to [DolphinScheduler Task Parameters Appendix](appendix.md) `Default Task Parameters` section for default parameters.
-- Engine: Supports FLINK, SPARK AND SEATUNNEL_ENGINE
+- Startup script: Script name to start the task, including `seatunnel.sh`, `start-seatunnel-flink-13-connector-v2.sh`, `start-seatunnel-flink-15-connector-v2.sh`, `start-seatunnel-flink-connector-v2.sh`, `start-seatunnel-flink.sh`, `start-seatunnel-spark-2-connector-v2.sh`, `start-seatunnel-spark-3-connector-v2.sh`, `start-seatunnel-spark-connector-v2.sh`, `start-seatunnel-spark.sh`
```
Comment (zhongjiajie) [inline docs/docs/en/guide/task/seatunnel.md]:
```suggestion
- Startup script: Select script name to start the task, including `seatunnel.sh`, `start-seatunnel-flink-13-connector-v2.sh`, `start-seatunnel-flink-15-connector-v2.sh`, `start-seatunnel-flink-connector-v2.sh`, `start-seatunnel-flink.sh`, `start-seatunnel-spark-2-connector-v2.sh`, `start-seatunnel-spark-3-connector-v2.sh`, `start-seatunnel-spark-connector-v2.sh`, `start-seatunnel-spark.sh`
```

File: docs/docs/zh/guide/task/seatunnel.md [hunk 3]
```diff
@@ -16,7 +16,7 @@
 [//]: # (- 默认参数说明请参考[DolphinScheduler任务参数附录]&#40;appendix.md#默认任务参数&#41;`默认任务参数`一栏。)
 
 - 默认参数说明请参考[DolphinScheduler任务参数附录](appendix.md)`默认任务参数`一栏。
-- 引擎：支持 FLINK 、 SPARK 和 SEATUNNEL_ENGINE
+- 启动脚本：你想要通过什么启动脚本启动任务，包括 `seatunnel.sh`, `start-seatunnel-flink-13-connector-v2.sh`, `start-seatunnel-flink-15-connector-v2.sh`, `start-seatunnel-flink-connector-v2.sh`, `start-seatunnel-flink.sh`, `start-seatunnel-spark-2-connector-v2.sh`, `start-seatunnel-spark-3-connector-v2.sh`, `start-seatunnel-spark-connector-v2.sh`, `start-seatunnel-spark.sh`
```
Comment (zhongjiajie) [inline docs/docs/zh/guide/task/seatunnel.md]:
```suggestion
- 启动脚本：选择你想要运行任务的启动脚本，包括 `seatunnel.sh`, `start-seatunnel-flink-13-connector-v2.sh`, `start-seatunnel-flink-15-connector-v2.sh`, `start-seatunnel-flink-connector-v2.sh`, `start-seatunnel-flink.sh`, `start-seatunnel-spark-2-connector-v2.sh`, `start-seatunnel-spark-3-connector-v2.sh`, `start-seatunnel-spark-connector-v2.sh`, `start-seatunnel-spark.sh`
```

File: dolphinscheduler-task-plugin/dolphinscheduler-task-seatunnel/src/main/java/org/apache/dolphinscheduler/plugin/task/seatunnel/SeatunnelTaskChannel.java [hunk 4]
```diff
@@ -38,17 +42,18 @@ public void cancelApplication(boolean status) {
...
-            case FLINK_V2:
-                return new SeatunnelFlinkTask(taskRequest);
-            case SPARK:
-            case SPARK_V2:
-                return new SeatunnelSparkTask(taskRequest);
-            case SEATUNNEL_ENGINE:
-                return new SeatunnelEngineTask(taskRequest);
+        assert seatunnelParameters != null;
+        String startupScript = seatunnelParameters.getStartupScript();
+        if (startupScript.contains(STARTUP_SCRIPT_SPARK)) {
```
Comment (zhongjiajie) [inline dolphinscheduler-task-plugin/dolphinscheduler-task-seatunnel/src/main/java/org/apache/dolphinscheduler/plugin/task/seatunnel/SeatunnelTaskChannel.java:47]: change from equal enums to startup script contain specific string or not

File: dolphinscheduler-task-plugin/dolphinscheduler-task-seatunnel/src/main/java/org/apache/dolphinscheduler/plugin/task/seatunnel/EngineEnum.java (hunk 1 above)
Comment (zhongjiajie) [reply dolphinscheduler-task-plugin/dolphinscheduler-task-seatunnel/src/main/java/org/apache/dolphinscheduler/plugin/task/seatunnel/EngineEnum.java:23]: for reviewer, we have a discussion in https://github.com/apache/dolphinscheduler/pull/14131#issuecomment-1551153028

Comment (zhongjiajie) [reply dolphinscheduler-task-plugin/dolphinscheduler-task-seatunnel/src/main/java/org/apache/dolphinscheduler/plugin/task/seatunnel/EngineEnum.java:23]: The new scream shot look like this
seatunnel

**Comment by zhongjiajie** [comment]
@zhuangchong do you have time to take a look with this PR?

**Review by zhuangchong — APPROVED** [review]
+1
