### PR TITLE
[Fix-14149][master] fix workflow always ready pause

### LINKED ISSUE #14149: [Bug] [master] Pause the workflow, but the status remains ready pause
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Pause the workflow, but the status remains ready pause.

image

### What you expected to happen

success pause

### How to reproduce

Pause the workflow

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by eye-gu**
## Purpose of the pull request

close #14149

### CODE REVIEW

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java [hunk 1]
```diff
@@ -996,6 +998,35 @@ private boolean executeTask(TaskInstance taskInstance) {
         }
     }
 
+    /**
+     * Sometimes (such as pause), if the task instance status has already been finished,
+     * there is no need to dispatch it
+     */
+    @VisibleForTesting
+    void submitOrStateChange(TaskInstance taskInstance, TaskExecuteRunnable taskExecuteRunnable) {
```
Comment (ruanwenjun) [inline dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java]:
```suggestion
    void tryToDispatchTaskInstance(TaskInstance taskInstance, TaskExecuteRunnable taskExecuteRunnable) {
```

**Review by ruanwenjun — APPROVED** [review]
LGTM
