### PR TITLE
[DS-6606] [fix] [common] JSONUtils#getNodeString String type #6606

### LINKED ISSUE #6606: [Bug] [common] JSONUtils#getNodeString get a value of type string with quotes
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

in JSONUtils:
`
public static String getNodeString(String json, String nodeName) {
    try {
        JsonNode rootNode = objectMapper.readTree(json);
        return rootNode.has(nodeName) ? rootNode.get(nodeName).toString() : "";
    } catch (IOException e) {
        return "";
    }
}
`

If the field value is a string, the result will be quoted.

So far it's just "localParams" using this function,
I think, JsonNodeType judgment is missing from JSONUtils#getNodeString,
String type can consider using JsonNode#asText instead of JsonNode#toString.

### What you expected to happen

If this is a function that is likely to be widely used, maybe some changes are needed
### How to reproduce

HashMap<String, Object> map = new HashMap<>();
map.put("localParams", "123");
map.put("test", 123);

// {"test":123,"localParams":"123"}
String json = JSONUtils.toJsonString(map);

String localParams = JSONUtils.getNodeString(json, "localParams");
System.out.println(localParams);  //  "123"

System.out.println("123".equals(localParams));   // false

String localParams1 = objectMapper.readTree(json).get("localParams").asText();
System.out.println("123".equals(localParams1));  // true

### Anything else

_No response_

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by ghost**
fix #6606 
JSONUtils#getNodeString get a value of type String,will get quotes

### CODE REVIEW

File: dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/JSONUtils.java [hunk 1]
```diff
@@ -212,26 +208,28 @@ public static String findValue(JsonNode jsonNode, String fieldName) {
...
 
     /**
      * from the key-value generated json  to get the str value no matter the real type of value
-     * @param json the json str
+     *
+     * @param json     the json str
      * @param nodeName key
      * @return the str value of key
      */
     public static String getNodeString(String json, String nodeName) {
```
Comment (ruanwenjun) [inline dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/JSONUtils.java:232]: I still suggest deleting this method, this is not used now.

Comment (ghost) [reply dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/JSONUtils.java:232]: I'm now modifying the dev branch. In the dev branch, this function refers to a controller api ProcessInstanceImpl#viewVariables.If just delete this function, it will change a lot.I'm not sure if this api will be used in future releases.

Comment (ghost) [reply dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/JSONUtils.java:232]: Or can you specify a merged branch for me? @ruanwenjun

**Review by ruanwenjun — DISMISSED** [review]
LGTM

**Comment by ghost** [comment]
The check failed because nesting of ternary operators was used,please review again ,thx @ruanwenjun @CalvinKirs

**Review by CalvinKirs — APPROVED** [review]
LGTM

**Comment by CalvinKirs** [comment]
thanks for your first contribution. good job
please only submit the related resources for this PR, one PR just solves one issue
I think you will need my help, please contact me freely(wechat: Kris_Evil), when added, please tell me your github id

Welcome to join the DolphinScheduler Community!!!

**Review by ruanwenjun — APPROVED** [review]
