### PR TITLE
[DSIP-45] Polish the Storage SPI

### LINKED ISSUE #16072: [Bug] [resource center] edit json which more than 3000 line will cut off
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

if u upload a json to resource center,and the json more than 3000 line,the web page will only show 3000 line ,and if u click save button,the file in resource center will be 3000 line .

### What you expected to happen

the file should not be cut off to 3000 line when i edit it.

### How to reproduce

1.upload a json whiche is more than 3000 line like 6000 line
2.edit it in resource center
3.save it
4.download the josn and check it,the file will be 3000 line

### Anything else

_No response_

### Version

3.2.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### LINKED ISSUE #16140: [DSIP-45] Polish the Storage SPI
### Search before asking

- [X] I had searched in the [DSIP](https://github.com/apache/dolphinscheduler/issues/14102) and found no similar DSIP.

### Motivation

Right now, the storage api is very complex, there are a lot of issue related to the storage, e.g. CVE, file path is incorrect.
Most of these are due to the usage of storage path. We will use absolute path and relative path with storage, but the api does't announce this. 

In additional, the storage interface is complex, it rely on some business logic, e.g. tenant, default path, once we want to import a new storage, it's difficult. 

This DSIP is aim to refactor the storage api. make it more easy to maintain.

### Design Detail

The new storage spi will focus on filesystem operation.
```java
public interface StorageOperator {

    String FILE_FOLDER_NAME = "resources";
    String UDF_FOLDER_NAME = "udfs";

    String RESOURCE_UPLOAD_PATH = PropertyUtils.getString(Constants.RESOURCE_UPLOAD_PATH, "/dolphinscheduler");

    ResourceMetadata getResourceMetaData(String resourceAbsolutePath);

    /**
     * Get the absolute path of base directory.
     *
     * @return the base directory. e.g. file:///tmp/dolphinscheduler/, /tmp/dolphinscheduler/
     */
    String getStorageBaseDirectory();

    /**
     * Get the absolute path of directory which will be used by the given tenant. the tenant directory is under the base directory.
     *
     * @param tenantCode the tenant code, cannot be empty
     * @return the tenant directory. e.g. file:///tmp/dolphinscheduler/default/
     */
    String getStorageBaseDirectory(String tenantCode);

    /**
     * Get the absolute path of directory which will be used by the given tenant and resource type. the resource directory is under the tenant directory.
     * <p> If the resource type is FILE, will be 'file:///tmp/dolphinscheduler/default/resources/'.
     * <p> If the resource type is UDF, will be 'is file:///tmp/dolphinscheduler/default/udfs/'.
     * <p> If the resource type is ALL, will be 'is file:///tmp/dolphinscheduler/default/'.
     *
     * @param tenantCode   the tenant code, cannot be empty
     * @param resourceType the resource type, cannot be null
     * @return the resource directory. e.g. file:///tmp/dolphinscheduler/default/resources/
     */
    String getStorageBaseDirectory(String tenantCode, ResourceType resourceType);

    /**
     * Get the absolute path of the file in the storage. the file will under the file resource directory.
     *
     * @param tenantCode the tenant code, cannot be empty
     * @param fileName   the file name, cannot be empty
     * @return the file absolute path. e.g. file:///tmp/dolphinscheduler/default/resources/test.sh
     */
    String getStorageFileAbsolutePath(String tenantCode, String fileName);

    /**
     * Create a directory if the directory is already exists will throw exception(Dependent on the storage implementation).
     * <p> If the directory is not exists, will create the directory.
     * <p> If the parent directory is not exists, will create the parent directory.
     * <p> If the directory is already exists, will throw {@link FileAlreadyExistsException}.
     *
     * @param directoryAbsolutePath the directory absolute path
     */
    void createStorageDir(String directoryAbsolutePath);

    /**
     * Check if the resource exists.
     *
     * @param resourceAbsolutePath the resource absolute path
     * @return true if the resource exists, otherwise false
     */
    boolean exists(String resourceAbsolutePath);

    /**
     * Delete the resource, if the resourceAbsolutePath is not exists, will do nothing.
     *
     * @param resourceAbsolutePath the resource absolute path
     * @param recursive            whether to delete all the sub file/directory under the given resource
     */
    void delete(String resourceAbsolutePath, boolean recursive);

    /**
     * Copy the resource from the source path to the destination path.
     *
     * @param srcAbsolutePath the source path
     * @param dstAbsolutePath the destination path
     * @param deleteSource    whether to delete the source path after copying
     * @param overwrite       whether to overwrite the destination path if it exists
     */
    void copy(String srcAbsolutePath, String dstAbsolutePath, boolean deleteSource, boolean overwrite);

    /**
     * Move the resource from the source path to the destination path.
     *
     * @param srcLocalFileAbsolutePath the source local file
     * @param dstAbsolutePath          the destination path
     * @param deleteSource             whether to delete the source path after moving
     * @param overwrite                whether to overwrite the destination path if it exists
     * @return true if the resource is moved successfully, otherwise false
     * @throws IOException
     */
    void upload(String srcLocalFileAbsolutePath, String dstAbsolutePath, boolean deleteSource, boolean overwrite);

    /**
     * Download the resource from the source path to the destination path.
     *
     * @param srcFileAbsolutePath the source path
     * @param dstAbsoluteFile     the destination file
     * @param overwrite           whether to overwrite the destination file if it exists
     * @throws IOException
     */
    void download(String srcFileAbsolutePath, String dstAbsoluteFile, boolean overwrite) throws IOException;

    /**
     * Fetch the content of the file.
     *
     * @param fileAbsolutePath the file path
     * @param skipLineNums     the number of lines to skip
     * @param limit            the number of lines to read
     * @return the content of the file
     */
    List<String> fetchFileContent(String fileAbsolutePath, int skipLineNums, int limit);

    /**
     * Return the {@link StorageEntity} under the given path.
     * <p>If the path is a file, return the file status.
     * <p>If the path is a directory, return the file/directory under the directory.
     * <p>If the path is not exist, will return empty.
     *
     * @param resourceAbsolutePath the resource absolute path, cannot be empty
     */
    List<StorageEntity> listStorageEntity(String resourceAbsolutePath);

    /**
     * Return the {@link StorageEntity} which is file under the given path
     *
     * @param resourceAbsolutePath the resource absolute path, cannot be empty
     */
    List<StorageEntity> listFileStorageEntityRecursively(String resourceAbsolutePath);

    /**
     * Return the {@link StorageEntity} under the current directory
     *
     * @param resourceAbsolutePath the resource absolute path, cannot be empty
     */
    StorageEntity getStorageEntity(String resourceAbsolutePath);

}
```

### Compatibility, Deprecation, and Migration Plan

Compatibility with current version

### Test Plan

Add IT for HDFS(Local mode) / S3

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by ruanwenjun**
## Purpose of the pull request

close https://github.com/apache/dolphinscheduler/issues/16140
close https://github.com/apache/dolphinscheduler/issues/16072

## Brief change log

- Refactor the storage api
- Refactor the storage service
- Add IT for LocalStorage/HdfsStorage/S3Storage
- Remove some mock UT, this is meaningless.
- Fix fetch file content and update file content will cut 3000 lines.

## Verify this pull request

Verify by e2e(s3 case) / IT(local hdfs/ s3 case) and manual test.

### Resource CRUD

image

image

image

### UDF CRUD
image

### Using in task

image

image

### CODE REVIEW

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ResourcesServiceImpl.java [hunk 1]
```diff
@@ -17,1286 +17,404 @@
...
-        // random file name
-        String localFilename = FileUtils.getUploadFilename(tenantCode, UUID.randomUUID().toString());
-
-        // save file to hdfs, and delete original file
-        String resourcePath = storageOperate.getDir(type, tenantCode);
+    @Override
+    public void createFileFromContent(CreateFileFromContentRequest createFileFromContentRequest) {
+        CreateFileFromContentDto createFileFromContentDto =
+                createFileFromContentRequestTransformer.transform(createFileFromContentRequest);
+        createFileFromContentDtoValidator.validate(createFileFromContentDto);
```
Comment (rickchengx) [inline dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ResourcesServiceImpl.java:196]: DTO validation logic is used in many places. How about using AOP to reduce duplicate code through annotations?

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ResourcesServiceImpl.java [hunk 2]
```diff
@@ -17,1286 +17,404 @@
...
-            putMsg(result, Status.SUCCESS);
-        } catch (Exception e) {
-            throw new ServiceException(String.format("create resource directory: %s failed.", fullName));
+            storageOperator.upload(srcLocalTmpFileAbsolutePath, fileAbsolutePath, true, false);
+            ApiServerMetrics.recordApiResourceUploadSize(file.getSize());
+            log.info("Success upload resource file: {} complete.", fileAbsolutePath);
+        } catch (Exception ex) {
+            // If exception, clear the tmp path
+            FileUtils.deleteFile(srcLocalTmpFileAbsolutePath);
+            throw ex;
```
Comment (rickchengx) [inline dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ResourcesServiceImpl.java:188]: It seems that the exception stack information cannot be seen here

**Review by rickchengx — COMMENTED** [review]
Overall LGTM, thanks @ruanwenjun for refactoring Storage API to enhance the robustness and maintainability of this part of the code.

**Review by rickchengx — COMMENTED** [review]
Since this is a refactor of the storage module, it would be better to provide some screenshots.

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ResourcesServiceImpl.java (hunk 2 above)
Comment (ruanwenjun) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ResourcesServiceImpl.java:188]: We direct throw the exception, so the exception stack will be log at `ApiExceptionHandler`

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ResourcesServiceImpl.java (hunk 1 above)
Comment (ruanwenjun) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ResourcesServiceImpl.java:196]: May be we can not use apo, since some case will transform and validate many times. This is not a huge duplicate.

**Comment by ruanwenjun** [comment]
> Since this is a refactor of the storage module, it would be better to provide some screenshots.

Good suggestion, I add some picture in the description

**Review by SbloodyS — COMMENTED** [review]
Please check failed UT.

**Comment by ruanwenjun** [comment]
> Please check failed UT.

Done

**Review by SbloodyS — APPROVED** [review]
LGTM.

**Review by rickchengx — APPROVED** [review]
LGTM
