### PR TITLE
[Fix-17281][alert] Fix The maximum length of cell contents (text) is 32767 characters

### LINKED ISSUE #17281: [Bug] [Alert] ExcelUtils The maximum length of cell contents (text) is 32767 characters
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Caused by: java.lang.IllegalArgumentException: The maximum length of cell contents (text) is 32767 characters
    at org.apache.poi.ss.usermodel.CellBase.checkLength(CellBase.java:309)
    at org.apache.poi.ss.usermodel.CellBase.setCellValue(CellBase.java:290)
    at org.apache.dolphinscheduler.plugin.alert.email.ExcelUtils.genExcelFile(ExcelUtils.java:111)

### What you expected to happen

when the cell value exceed 32767,it will be terminated to 32700+(.... terminated)

### How to reproduce

when you send you data by email table, one record exceed 32767,then it happens

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by hkun0120**
## Purpose of the pull request

fix #17281

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

## Pull Request Notice
[Pull Request Notice](https://github.com/apache/dolphinscheduler/blob/dev/docs/docs/en/contribute/join/pull-request.md)

If your pull request contains incompatible change, you should also add it to `docs/docs/en/guide/upgrade/incompatible.md`

### CODE REVIEW

File: dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-email/src/main/java/org/apache/dolphinscheduler/plugin/alert/email/ExcelUtils.java [hunk 1]
```diff
@@ -108,7 +108,11 @@ public static void genExcelFile(String content, String title, String xlsFilePath
                     if (values[j] instanceof Number) {
                         cell1.setCellValue(Double.parseDouble(String.valueOf(values[j])));
                     } else {
-                        cell1.setCellValue(String.valueOf(values[j]));
+                        String cellValue = String.valueOf(values[j]);
+                        if (cellValue.length() > 32767) {
+                            cellValue = cellValue.substring(0, 32760) + "...(truncated)";
```
Comment (SbloodyS) [inline dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-email/src/main/java/org/apache/dolphinscheduler/plugin/alert/email/ExcelUtils.java]: We should split values into different cells instead of truncated it when values length is greater than 32767.

Comment (hkun0120) [reply dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-email/src/main/java/org/apache/dolphinscheduler/plugin/alert/email/ExcelUtils.java]: > We should split values into different cells instead of truncated it when values length is greater than 32767.

okay,I rewrite the code. Please check it. Will it ok?

File: dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-email/src/main/java/org/apache/dolphinscheduler/plugin/alert/email/ExcelUtils.java [hunk 2]
```diff
@@ -102,13 +102,15 @@ public static void genExcelFile(String content, String title, String xlsFilePath
...
-                    Cell cell1 = row.createCell(j);
-                    cell1.setCellStyle(cellStyle);
                     if (values[j] instanceof Number) {
+                        Cell cell1 = row.createCell(j);
+                        cell1.setCellStyle(cellStyle);
                         cell1.setCellValue(Double.parseDouble(String.valueOf(values[j])));
+                        colIndex++;
                     } else {
-                        cell1.setCellValue(String.valueOf(values[j]));
+                        colIndex = setCellValueWithSplit(row, colIndex, cellStyle, values[j]);
```
Comment (SbloodyS) [inline dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-email/src/main/java/org/apache/dolphinscheduler/plugin/alert/email/ExcelUtils.java]: Please add some unit test for this.

Comment (hkun0120) [reply dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-email/src/main/java/org/apache/dolphinscheduler/plugin/alert/email/ExcelUtils.java]: @SbloodyS please approval CI workflow, thanks

**Comment by SbloodyS** [comment]
You should run `mvn spotless:apply` to format code. @hkun0120

**Comment by hkun0120** [comment]
@SbloodyS ./mvnw spotless:apply in my local, result is all success. My jdk in IDEA is openjdk20,is this the problem?

**Comment by SbloodyS** [comment]
> @SbloodyS ./mvnw spotless:apply in my local, result is all success. My jdk in IDEA is openjdk20,is this the problem?

JDK8 and JDK11 are supported right now.

**Comment by hkun0120** [comment]
> > @SbloodyS ./mvnw spotless:apply in my local, result is all success. My jdk in IDEA is openjdk20,is this the problem?
> 
> JDK8 and JDK11 are supported right now.



> > @SbloodyS ./mvnw spotless:apply in my local, result is all success. My jdk in IDEA is openjdk20,is this the problem?
> 
> JDK8 and JDK11 are supported right now.

@SbloodyS okay，let's try again.

**Comment by hkun0120** [comment]
@SbloodyS why the CI can't load my ExcelUtilsTest.java ?

**Comment by hkun0120** [comment]
@SbloodyS    I think this is a problem in dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-email/src/test/java/org/apache/dolphinscheduler/plugin/alert/email/ExcelUtilsTest.java。Will I make another pull request to fix the testGenExcelFile() method?

**Comment by SbloodyS** [comment]
> @SbloodyS I think this is a problem in dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-email/src/test/java/org/apache/dolphinscheduler/plugin/alert/email/ExcelUtilsTest.java。Will I make another pull request to fix the testGenExcelFile() method?

You should fix it in this PR since this is introduted by this.

**Comment by hkun0120** [comment]
> > @SbloodyS I think this is a problem in dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-email/src/test/java/org/apache/dolphinscheduler/plugin/alert/email/ExcelUtilsTest.java。Will I make another pull request to fix the testGenExcelFile() method?
> 
> You should fix it in this PR since this is introduted by this.

@SbloodyS okay .let's try again.

**Comment by hkun0120** [comment]
ok ,I see,let's try again @SbloodyS

File: dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-email/src/main/java/org/apache/dolphinscheduler/plugin/alert/email/ExcelUtils.java [hunk 3]
```diff
@@ -124,5 +126,35 @@ public static void genExcelFile(String content, String title, String xlsFilePath
...
+     *
+     * @param row       the Excel row to write to
+     * @param colIndex  the starting column index
+     * @param cellStyle the cell style to apply
+     * @param value     the value to write
+     * @return the next available column index after writing
+     */
+    public static int setCellValueWithSplit(Row row, int colIndex, CellStyle cellStyle, Object value) {
+        String cellValue = String.valueOf(value);
+        int maxLen = 32767;
```
Comment (pjfanning) [inline dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-email/src/main/java/org/apache/dolphinscheduler/plugin/alert/email/ExcelUtils.java]: POI provides a way to get this instead of hardcoding this here.
https://github.com/apache/poi/blob/trunk/poi/src/main/java/org/apache/poi/ss/SpreadsheetVersion.java

org.apache.poi.ss.SpreadsheetVersion.EXECEL2007.getMaxTextLength()

**Review by SbloodyS — APPROVED** [review]
LGTM

File: dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-email/src/main/java/org/apache/dolphinscheduler/plugin/alert/email/ExcelUtils.java [hunk 4]
```diff
@@ -102,13 +103,15 @@ public static void genExcelFile(String content, String title, String xlsFilePath
                 // setting excel body height
                 row.setHeight((short) 500);
                 rowIndex++;
+                int colIndex = 0;
```
Comment (ruanwenjun) [inline dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-email/src/main/java/org/apache/dolphinscheduler/plugin/alert/email/ExcelUtils.java]: It seems this is not needed, you just split the value into multiple cell in one row.

**Review by SbloodyS — CHANGES_REQUESTED** [review]
I have carefully tested our output, and the maximum length of a single column will not exceed 32767.

Could you please provide your reproduction steps? @hkun0120

**Comment by hkun0120** [comment]
>  I have carefully tested our output, and the maximum length of a single column will not exceed 32767.
> 
> Could you please provide your reproduction steps? @hkun0120

we use SQL component,send our data in gauss database By Email plugin. For example, f1 field varchar in table t, the length of some f1 data  beyond 32767 ,and then it happens

File: dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-email/src/main/java/org/apache/dolphinscheduler/plugin/alert/email/ExcelUtils.java (hunk 4 above)
Comment (hkun0120) [reply dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-email/src/main/java/org/apache/dolphinscheduler/plugin/alert/email/ExcelUtils.java]: nothing to fix

**Comment by SbloodyS** [comment]
> we use SQL component,send our data in gauss database By Email plugin. For example, f1 field varchar in table t, the length of some f1 data beyond 32767 ,and then it happens

Then I understand that we should actually optimize the export function of sql nodes, not this alarm function.

**Comment by hkun0120** [comment]
> > we use SQL component,send our data in gauss database By Email plugin. For example, f1 field varchar in table t, the length of some f1 data beyond 32767 ,and then it happens
> 
> Then I understand that we should actually optimize the export function of sql nodes, not this alarm function.

Yes, I think it’s reasonable to modify the SQL component. can I/we create a DSIP  for this problem ？And this PR  just focuses on fixing the alert issue? @SbloodyS

**Comment by SbloodyS** [comment]
> can I/we create a DSIP for this problem?

You can create an improvement issue for a problem like this.

> And this PR just focuses on fixing the alert issue? 

Yes. I found that we will display multiple fields separately. If we split the extra-long fields into columns, it will lead to field dislocation, so we should intercept the columns. Sorry for my mistaken.

**Comment by hkun0120** [comment]
> > can I/we create a DSIP for this problem?
> 
> You can create an improvement issue for a problem like this.
> >OK,I will create an improvement.
> > And this PR just focuses on fixing the alert issue?
> 
> Yes. I found that we will display multiple fields separately. If we split the extra-long fields into columns, it will lead to field dislocation, so we should intercept the columns. Sorry for my mistaken.
>>it doesn't matter. Shall I fix the code to the first edition, it means when length more than 32767, I  change them to 32700 + '......terminated'?

**Comment by SbloodyS** [comment]
>  Shall I fix the code to the first edition, it means when length more than 32767, I change them to 32700 + '......terminated'?

Yes.

File: dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-email/src/test/java/org/apache/dolphinscheduler/plugin/alert/email/ExcelUtilsTest.java [hunk 5]
```diff
@@ -74,4 +83,33 @@ public void testGenExcelFileByCheckDir() {
         file.delete();
         Assertions.assertFalse(file.exists());
     }
+    
+    @Test
+    void testGenExcelFile_TruncateLongString() throws Exception {
+        String title = "truncate_test";
+        String longStrKey = "longStr";
+        int maxLen = SpreadsheetVersion.EXCEL2007.getMaxTextLength();
+        // 构造超长字符串
```
Comment (SbloodyS) [inline dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-email/src/test/java/org/apache/dolphinscheduler/plugin/alert/email/ExcelUtilsTest.java]: Please using english to describe.

File: dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-email/src/test/java/org/apache/dolphinscheduler/plugin/alert/email/ExcelUtilsTest.java [hunk 6]
```diff
@@ -74,4 +83,33 @@ public void testGenExcelFileByCheckDir() {
...
+        StringBuilder sb = new StringBuilder();
+        for (int i = 0; i < maxLen + 100; i++) {
+            sb.append('X');
+        }
+        String longValue = sb.toString();
+        // 构造内容
```
Comment (SbloodyS) [inline dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-email/src/test/java/org/apache/dolphinscheduler/plugin/alert/email/ExcelUtilsTest.java]: Same here.

File: dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-email/src/test/java/org/apache/dolphinscheduler/plugin/alert/email/ExcelUtilsTest.java [hunk 7]
```diff
@@ -74,4 +83,33 @@ public void testGenExcelFileByCheckDir() {
...
+        String content = "[{\"" + longStrKey + "\":\"" + longValue + "\"}]";
+    
+        // 生成文件
```
Comment (SbloodyS) [inline dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-email/src/test/java/org/apache/dolphinscheduler/plugin/alert/email/ExcelUtilsTest.java]: Same here.

File: dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-email/src/test/java/org/apache/dolphinscheduler/plugin/alert/email/ExcelUtilsTest.java [hunk 8]
```diff
@@ -74,4 +83,33 @@ public void testGenExcelFileByCheckDir() {
...
+        ExcelUtils.genExcelFile(content, title, xlsFilePath);
+    
+        // 检查生成的Excel内容
```
Comment (SbloodyS) [inline dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-email/src/test/java/org/apache/dolphinscheduler/plugin/alert/email/ExcelUtilsTest.java]: Same here.

**Review by SbloodyS — CHANGES_REQUESTED** [review]

**Review by SbloodyS — APPROVED** [review]
LGTM

**Review by ruanwenjun — APPROVED** [review]
LGTM
