### PR TITLE
[Bug] [Master] WorkflowExecuteRunnable will face a infinite loop #11838

### LINKED ISSUE #11838: [Bug] [Master] WorkflowExecuteRunnable will face a infinite loop
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

when we confige the `Timeout period` and `Failed retry interval` at the same time in Shell task. When shell task failed, it will submit a `TASK_STATE_CHANGE` TaskEvent, and then `TaskStateEventHandler` will call `WorkflowExecuteRunnable.taskFinished`  and remove the _<taskInstanceCode,TaskProcessor>_ in `activeTaskProcessorMaps`
image
Then `StateWheelExecuteThread` will submit a `TASK_TIMEOUT` and a `TASK_RETRY` TaskEvent.
But `TaskTimeoutStateEventHandler` will query a TaskProcessor form `activeTaskProcessorMaps` to process the TIMEOUT, this will casue a NPE:
image
And `WorkflowExecuteRunnable` will not remove this TaskEvent if this taskEventHandler throw a Exception, so it keep loop, but it will no any update,just a infinite loop.
image
Besides, the `WorkflowExecuteThreadPool.executeEvent` will keep print the `The workflow has been executed by another thread` each 100ms, because event count > 0
So u can find the master log prints NPE and `The workflow has been executed by another thread` at the same time like crazy

This bug may cause #11796 
But I think this needs to be discussed separately

### What you expected to happen

this process instance will stop caused by TIMEOUT, not keep a infinite loop, and show it's keep running.

### How to reproduce

just create a shell task like the following screenshot:
image

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by DarkAssassinator**
## Purpose of the pull request

fix #11838 and #11796 

## Brief change log

1. Before invoke the TaskProssor.action(TIME_OUT), checked the taskProssor is not null, avoid NPE.
2. Add a `isHandingEvent` flag in `WorkflowExecuteRunnable`, becasue it can avoid many `The workflow has been executed by another thread` print when  `WorkflowExecuteRunnable` is handing StateEvent
3. Why did not restore the ITaskProcessor when handle the `StateEventType.TASK_TIMEOUT`? 1) we should keep the current logic; 2) i think timeout should depend on the task on worker services.
4. Update some code style by Coogle format plugin.

## Verify this pull request

Create a Shell Task, configre the retry time and timeout at the same time.

### CODE REVIEW

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteThreadPool.java [hunk 1]
```diff
@@ -101,7 +101,8 @@ public void submitStateEvent(StateEvent stateEvent) {
      * Handle the events belong to the given workflow.
      */
     public void executeEvent(final WorkflowExecuteRunnable workflowExecuteThread) {
-        if (!workflowExecuteThread.isStart() || workflowExecuteThread.eventSize() == 0) {
+        if (!workflowExecuteThread.isStart() || workflowExecuteThread.isHandingEvent()
```
Comment (ruanwenjun) [inline dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteThreadPool.java]: Why we need to do this change, if the `workflowExecuteThread` is handing event, it should be filter by `if (multiThreadFilterMap.containsKey(workflowExecuteThread.getKey()))`

**Review by ruanwenjun — CHANGES_REQUESTED** [review]

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/event/TaskTimeoutStateEventHandler.java [hunk 2]
```diff
@@ -34,29 +34,34 @@ public class TaskTimeoutStateEventHandler implements StateEventHandler {
...
-                || TaskTimeoutStrategy.WARNFAILED == taskTimeoutStrategy) {
-            ITaskProcessor taskProcessor = activeTaskProcessMap.get(taskInstance.getTaskCode());
-            taskProcessor.action(TaskAction.TIMEOUT);
+        TaskTimeoutStrategy taskTimeoutStrategy = taskInstance.getTaskDefine()
+            .getTimeoutNotifyStrategy();
+        Map<Long, ITaskProcessor> activeTaskProcessMap = workflowExecuteRunnable
+            .getActiveTaskProcessMap();
+        if ((TaskTimeoutStrategy.FAILED == taskTimeoutStrategy
+            || TaskTimeoutStrategy.WARNFAILED == taskTimeoutStrategy)) {
+            if (activeTaskProcessMap.containsKey(taskInstance.getTaskCode())) {
```
Comment (ruanwenjun) [inline dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/event/TaskTimeoutStateEventHandler.java:62]: In which case the `taskProcessor` will be null? if it's null we need to throw error?

Comment (DarkAssassinator) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/event/TaskTimeoutStateEventHandler.java:62]: if task instance failure, it will submit a `StateEventType.TASK_STATE_CHANGE`, `TaskStateEventHandler` will call `workflowExecuteRunnable.taskFinished(task)` and remove this `taskProcessor`

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteThreadPool.java (hunk 1 above)
Comment (DarkAssassinator) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteThreadPool.java]: > Why we need to do this change, if the `workflowExecuteThread` is handing event, it should be filter by `if (multiThreadFilterMap.containsKey(workflowExecuteThread.getKey()))`

because `workflowExecuteThread ` will not remove the event if occured any exception, and the `WorkflowExecuteThreadPool` will keep print log each 100ms

Comment (ruanwenjun) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteThreadPool.java]: When this case occur, means the system may exist bug or meet some error, like database crash.

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/event/TaskTimeoutStateEventHandler.java (hunk 2 above)
Comment (ruanwenjun) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/event/TaskTimeoutStateEventHandler.java:62]: Ok, it's better to print a warn log if we cannot find the processor here.

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteThreadPool.java (hunk 1 above)
Comment (DarkAssassinator) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteThreadPool.java]: > When this case occur, means the system may exist bug or meet some error, like database crash.

emm. u are correct, i has avoid this change.

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/event/TaskTimeoutStateEventHandler.java (hunk 2 above)
Comment (DarkAssassinator) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/event/TaskTimeoutStateEventHandler.java:62]: > Ok, it's better to print a warn log if we cannot find the processor here.

yes, and i add a warn log print.

**Review by caishunfeng — APPROVED** [review]
LGTM

**Comment by caishunfeng** [comment]
I had rerun the fail CI.

**Review by ruanwenjun — APPROVED** [review]
LGTM

**Comment by caishunfeng** [comment]
I will cherry-pick to 3.0.1-prepare and 3.1.0-prepare.
