### PR TITLE
Fix Recover WorkflowInstance will casue workflow Instance state is success but task insatnce is killed/paused

### LINKED ISSUE #15575: [Bug] [Master] Recover then the workflow instance will not restart task instance
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When we kill a workflow instance which contains a failed task instance and recover it.
Then it might go into success, but the workflow instance contains failed task instance.

### What you expected to happen

The workflow instance status is correct with task instance.

### How to reproduce

1. Start a workflow instance which will contains failed task instance and running tasks instance.
2. Kill it and recovery
3. The workflow instance will go into success but it contains failed task instance.

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by ruanwenjun**
## Purpose of the pull request

close #15575

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

**Review by fuchanghai — APPROVED** [review]
LGTM

File: dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessServiceImpl.java [hunk 1]
```diff
@@ -763,43 +763,34 @@ private Boolean checkCmdParam(Command command, Map<String, String> cmdParam) {
...
-                failedList.addAll(killedList);
-                failedList.addAll(toleranceList);
-                for (Integer taskId : failedList) {
-                    initTaskInstance(taskInstanceDao.queryById(taskId));
+            case RECOVER_SUSPENDED_PROCESS:
+                List<TaskInstance> needToStartTaskInstances = taskInstanceDao
+                        .queryValidTaskListByWorkflowInstanceId(processInstance.getId(), processInstance.getTestFlag())
+                        .stream()
+                        .filter(taskInstance -> {
+                            TaskExecutionStatus state = taskInstance.getState();
```
Comment (rickchengx) [inline dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/process/ProcessServiceImpl.java:771]: Overall LGTM, could we use `state.isFailure() || state.isPause() || state.isKill()` or something like `state.needRestart()` instead of directly check the state here
