### PR TITLE
[FIX][DAO-12277] change t_ds_fav_task column task_name to task_type and related code

### LINKED ISSUE #12277: [Improvement][DAO] the name of task_name of table t_ds_fav_task need to change
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

change task_name  to task_type

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Tianqi-Dotes**
## Purpose of the pull request

close #12277

change t_ds_fav_task column task_name to task_type and related code

## Brief change log

change t_ds_fav_task column task_name to task_type and related code
## Verify this pull request
Manually verified the change by testing locally.

### CODE REVIEW

File: dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/FavTask.java [hunk 1]
```diff
@@ -34,6 +35,8 @@ public class FavTask {
 
     @TableId(value = "id", type = IdType.AUTO)
     private Long id;
+    //task type name
+    @TableField("task_type")
     private String taskName;
```
Comment (zhongjiajie) [inline dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/FavTask.java]: should we also change entity name from `taskName` to `taskType`?

File: dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_mysql.sql [hunk 2]
```diff
@@ -1982,8 +1982,8 @@ CREATE TABLE `t_ds_cluster`(
 DROP TABLE IF EXISTS `t_ds_fav_task`;
 CREATE TABLE `t_ds_fav_task`
 (
-    `id`        bigint      NOT NULL AUTO_INCREMENT COMMENT 'favorite task id',
-    `task_name` varchar(64) NOT NULL COMMENT 'favorite task name',
+    `id`        bigint      NOT NULL AUTO_INCREMENT COMMENT 'id',
+    `task_type` varchar(64) NOT NULL COMMENT 'favorite task type name',
```
Comment (zhongjiajie) [inline dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_mysql.sql:2004]: does this feature already release? If released we should also add this incompatible change into https://dolphinscheduler.apache.org/en-us/docs/dev/user_doc/guide/upgrade/incompatible.html

Comment (ruanwenjun) [reply dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_mysql.sql:2004]: This feature has released in 3.1.0, we need to add DDL

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/FavTaskController.java [hunk 3]
```diff
@@ -84,8 +84,8 @@ public Result listTaskType(@ApiIgnore @RequestAttribute(value = Constants.SESSIO
     @ApiException(DELETE_TASK_TYPE_ERROR)
     @AccessLogAnnotation(ignoreRequestArgs = "loginUser")
     public Result deleteFavTask(@ApiIgnore @RequestAttribute(value = Constants.SESSION_USER) User loginUser,
-                                @PathVariable("taskName") String taskName) {
-        boolean b = favTaskService.deleteFavTask(loginUser, taskName);
+                                @PathVariable("taskName") String taskType) {
```
Comment (ruanwenjun) [inline dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/FavTaskController.java]:
```suggestion
                                @PathVariable("taskType") String taskType) {
```

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/FavTaskController.java [hunk 4]
```diff
@@ -101,8 +101,8 @@ public Result deleteFavTask(@ApiIgnore @RequestAttribute(value = Constants.SESSI
     @ApiException(ADD_TASK_TYPE_ERROR)
     @AccessLogAnnotation(ignoreRequestArgs = "loginUser")
     public Result addFavTask(@ApiIgnore @RequestAttribute(value = Constants.SESSION_USER) User loginUser,
-                             @PathVariable("taskName") String taskName) {
-        int i = favTaskService.addFavTask(loginUser, taskName);
+                             @PathVariable("taskName") String taskType) {
```
Comment (ruanwenjun) [inline dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/FavTaskController.java]:
```suggestion
                             @PathVariable("taskType") String taskType) {
```

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/FavTaskController.java (hunk 3 above)
Comment (Tianqi-Dotes) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/FavTaskController.java]: emmm..i'm trying to use @TableField avoid this, if change need to change frontend. what's your opinion.

Comment (ruanwenjun) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/FavTaskController.java]: It's Ok to change the front end, if someone use open-API, he might be confused by the `taskName`.

File: dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_mysql.sql (hunk 2 above)
Comment (zhongjiajie) [reply dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_mysql.sql:2004]: So it is mean this featrue should work in 3.1.0 but currently not work, am I right?

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/FavTaskController.java (hunk 3 above)
Comment (zhongjiajie) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/FavTaskController.java]: I think it is ok too

**Review by Amy0104 — DISMISSED** [review]
The front end LGTM.

File: dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_mysql.sql (hunk 2 above)
Comment (Tianqi-Dotes) [reply dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_mysql.sql:2004]: > So it is mean this featrue should work in 3.1.0 but currently not work, am I right?

Dear Jiajie, this is an upgrade to make the column name more appropriate. It works without this pr changes.

File: dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/FavTask.java (hunk 1 above)
Comment (Tianqi-Dotes) [reply dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/FavTask.java]: done

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/FavTaskController.java (hunk 3 above)
Comment (Tianqi-Dotes) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/FavTaskController.java]: done

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/FavTaskController.java (hunk 4 above)
Comment (Tianqi-Dotes) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/FavTaskController.java]: done

File: dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_mysql.sql (hunk 2 above)
Comment (caishunfeng) [reply dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_mysql.sql:2004]: The users upgrade by upgrade tools, and it will error if we don't provide this DDL sql.

Comment (Tianqi-Dotes) [reply dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_mysql.sql:2004]: > does this feature already release? If released we should also add this incompatible change into https://dolphinscheduler.apache.org/en-us/docs/dev/user_doc/guide/upgrade/incompatible.html

have submitted dml changes to mysql and postgre

**Comment by zhongjiajie** [comment]
Hi @Tianqi-Dotes , due to 3.1.0 had released  I think we should put dml change to 3.1.1

**Review by zhongjiajie — DISMISSED** [review]
LGTM, thanks

File: dolphinscheduler-dao/src/main/resources/sql/upgrade/3.1.1_schema/mysql/dolphinscheduler_ddl.sql [hunk 5]
```diff
@@ -14,3 +14,19 @@
...
+        AND TABLE_SCHEMA=(SELECT DATABASE())
+        AND COLUMN_NAME='task_name')
+    THEN
+SET sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));
+ALTER TABLE `t_ds_fav_task` change `task_name` `task_type` varchar(64) NOT NULL COMMENT 'favorite task type name';
+END IF;
+END;
+d//
+delimiter ;
+
```
Comment (zhongjiajie) [inline dolphinscheduler-dao/src/main/resources/sql/upgrade/3.1.1_schema/mysql/dolphinscheduler_ddl.sql:35]:
```suggestion
CALL modify_t_ds_fav_task_task_name;
DROP PROCEDURE modify_t_ds_fav_task_task_name;
```

Comment (Tianqi-Dotes) [reply dolphinscheduler-dao/src/main/resources/sql/upgrade/3.1.1_schema/mysql/dolphinscheduler_ddl.sql:35]: done,thanx dear Jiajie

**Review by zhongjiajie — APPROVED** [review]

**Comment by zhongjiajie** [comment]
LGTM, waiting for CI

**Review by caishunfeng — APPROVED** [review]
+1

**Comment by zhuangchong** [comment]
@Tianqi-Dotes Can you cherry-pick this PR to the 3.1.1-prepare branch?
