### PR TITLE
[Fix-14828][master] check task id not null to avoid NPE

### LINKED ISSUE #14828: [Bug] [master] Task retry reported NPE
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

> [ERROR] 2023-08-29 15:56:47.632 +0800 org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable:[435] - [WorkflowInstance-27][TaskInstance-35] - Task finish failed, get a exception, will remove this taskInstance from completeTaskSet
java.lang.NullPointerException: id is marked non-null but is null
	at org.apache.dolphinscheduler.dao.repository.BaseDao.queryById(BaseDao.java:41)
	at org.apache.dolphinscheduler.dao.repository.BaseDao$$FastClassBySpringCGLIB$$ca36ec34.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
	at org.apache.dolphinscheduler.dao.repository.impl.TaskInstanceDaoImpl$$EnhancerBySpringCGLIB$$11409f96.queryById(<generated>)
	at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable.submitStandByTask(WorkflowExecuteRunnable.java:1902)
	at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable.retryTaskInstance(WorkflowExecuteRunnable.java:506)
	at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable.taskFinished(WorkflowExecuteRunnable.java:409)
	at org.apache.dolphinscheduler.server.master.event.TaskStateEventHandler.handleStateEvent(TaskStateEventHandler.java:73)
	at org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable.handleEvents(WorkflowExecuteRunnable.java:285)

### What you expected to happen

task retry success

### How to reproduce

just retry

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by eye-gu**
## Purpose of the pull request

close #14828

### CODE REVIEW

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java [hunk 1]
```diff
@@ -1897,7 +1897,7 @@ public void submitStandByTask() throws StateEventHandleException {
         TaskInstance task;
         while ((task = readyToSubmitTaskQueue.peek()) != null) {
             // stop tasks which is retrying if forced success happens
-            if (task.taskCanRetry()) {
+            if (task.getId() != null && task.taskCanRetry()) {
```
Comment (ruanwenjun) [inline dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java:1900]: In which case, the taskId will be null but it can retry?

Comment (eye-gu) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java:1900]: When a task fails and retried, a new task instance will be created using the retryTaskInstance method, and then inserted into the readyToSubmitTaskQueue using the addTaskToStandByList method. The instance ID is null and the status is failed

**Review by ruanwenjun — APPROVED** [review]
LGTM

**Review by Gallardot — APPROVED** [review]
LGTM. I have tested this PR in our cluster and everything is working fine. It also resolves the reported issue #14723

**Review by caishunfeng — APPROVED** [review]
+1
