### PR TITLE
[Bug] [Service] Use MapUtils to judge globalParamsMap is empty

### LINKED ISSUE #12383: [Bug] [Service] Condition 'globalParamsMap != null' is always 'true'
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Condition 'globalParamsMap != null' is always 'true' 

### What you expected to happen

Condition judge correctly

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by hstdream**
## Purpose of the pull request
close #12383 
fix condition 'globalParamsMap != null' is always 'true' .

## Brief change log

Condition 'globalParamsMap != null' is always 'true' .

## Verify this pull request
 if (!globalParamsMap.isEmpty()) {
            params.putAll(globalParamsMap);
        }

### CODE REVIEW

File: dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/expand/CuringGlobalParams.java [hunk 1]
```diff
@@ -157,7 +157,7 @@ public Map<String, Property> paramParsingPreparation(@NonNull TaskInstance taskI
         String timeZone = cmdParam.get(Constants.SCHEDULE_TIMEZONE);
         Map<String, String> params = BusinessTimeUtils.getBusinessTime(commandType, scheduleTime, timeZone);
 
-        if (globalParamsMap != null) {
+        if (!globalParamsMap.isEmpty()) {
```
Comment (ruanwenjun) [inline dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/expand/CuringGlobalParams.java]:
```suggestion
        if (MapUtils.isNotEmpty(globalParamsMap.isEmpty)) {
```

**Review by ruanwenjun — CHANGES_REQUESTED** [review]
It's better to use utils to do this kind of judge, this can avoid some unexpected NPE.

File: dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/expand/CuringGlobalParams.java (hunk 1 above)
Comment (hstdream) [reply dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/expand/CuringGlobalParams.java]: ok.

**Review by fuchanghai — APPROVED** [review]

**Review by ruanwenjun — APPROVED** [review]
