### PR TITLE
[Fix-6478] [Server] Fix the lack of scheduling time in complement parallelism mode

### LINKED ISSUE #6478: [Bug] [API & SERVICE] Missing history data in complement data mode
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

1.I have an hourly workflow，the crontab is ："0 0 * * * ? *"
我有一个每小时运行的工作流，crontab 是 :"0 0 * * * ? *"
2. I want to add history data 
我去补一个历史数据，数据范围是0点到3点59分
aba7791b47ff5b28599a8f6885eeb52

3.the history data of 2021-10-09 03:00:00  not works
03点的数据没有运行

image

### What you expected to happen

I want the data of 2021-10-09 03:00:00 is works 
我想要3点的数据执行

### How to reproduce

fd5559070e8152804b241e41a2938b3

### Anything else

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by zhuangchong**
## Purpose of the pull request

this pr close #6478 

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

### CODE REVIEW

File: dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ExecutorServiceTest.java [hunk 1]
```diff
@@ -326,4 +329,29 @@ private List zeroSchedulerList() {
...
+        logger.info("In parallel mode, current expectedParallelismNumber:{}", createCount);
+        int chunkSize = listDate.size() / createCount;
+        for (int i = 0; i < createCount; i++) {
+            int rangeStart = i == 0 ? i : (i * chunkSize);
+            int rangeEnd = i == createCount - 1 ? listDate.size() - 1
+                    : rangeStart + chunkSize;
+            if (rangeEnd == listDate.size()) {
+                rangeEnd = listDate.size() - 1;
+            }
+            logger.info("rangeStart:{},rangeEnd:{}",rangeStart, rangeEnd);
```
Comment (lenboo) [inline dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ExecutorServiceTest.java]: it's better to use 'assert' than 'logger.info' in ut.

Comment (zhuangchong) [reply dolphinscheduler-api/src/test/java/org/apache/dolphinscheduler/api/service/ExecutorServiceTest.java]: done.

**Review by lenboo — APPROVED** [review]
+1

**Review by CalvinKirs — APPROVED** [review]
