### PR TITLE
[Bug] [API] If the log file is large but has small number of rows, it will causes the View Log page to hang

### LINKED ISSUE #10609: [Bug] [Worker] If the log file is large but has small number of rows, it will causes the View Log page to hang
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

My task has Produced a lager log file, size is 4.3MB, but number of file is 235. 
When view the task log, the View Log page is hang。
image

### What you expected to happen

The View Logs page is no longer suspended, and the task logs are displayed normally

### How to reproduce

Produce a  large size log file, e.g 4MB, every line of log file is very long, but number of line is less than 1000 rows.
then view the task log

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by zhuxt2015**
## Purpose of the pull request
close  #10609

## Brief change log
- If the single line of log exceeds 65535 bytes, then this line only retains 65535 characters.
- If the number of log lines does not exceed limit (default 1000), and the single line content exceeds 65535 bytes, then the log will not continue to be read, and return the log content and log line number.
- The front end is set to skipLineNum for the next log request based on the response line number.
------------
- 如果单行日志超过65535字节, 那么这一行日志只保留65535个字符
- 如果日志行数不超过limit(默认1000行), 但日志内容超过65535字节,  那么不再继续读取日志, 返回已经读取的日志和日志行数
- 前端根据返回的日志行数设置为下次日志请求的skipLineNum。

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

### CODE REVIEW

File: dolphinscheduler-log-server/src/main/java/org/apache/dolphinscheduler/server/log/LoggerRequestProcessor.java [hunk 1]
```diff
@@ -113,8 +114,22 @@ public void process(Channel channel, Command command) {
...
+                                .append(" [this line' size is exceed ")
+                                .append(MaxResponseLogSize).append(" bytes, so only ")
+                                .append(MaxResponseLogSize).append(" characters are reserved for performance reasons.]")
+                                .append("\r\n");
+                    }else {
+                        builder.append(line).append("\r\n");
+                    }
+
+                    if (builder.toString().getBytes(StandardCharsets.UTF_8).length >= MaxResponseLogSize) {
+                        break;
```
Comment (ruanwenjun) [inline dolphinscheduler-log-server/src/main/java/org/apache/dolphinscheduler/server/log/LoggerRequestProcessor.java]: I worry this method will be very slow, you already calculate the size of each line, you don't need to calculate the size again.

File: dolphinscheduler-ui/src/views/projects/task/instance/index.tsx [hunk 2]
```diff
@@ -76,11 +76,11 @@ const TaskInstance = defineComponent({
           taskInstanceId: Number(row.id),
           limit: variables.limit,
           skipLineNum: variables.skipLineNum
-        }).then((res: string) => {
-          variables.logRef += res
-          if (res) {
+        }).then((res: any) => {
+          variables.logRef += res.message
+          if (res.message) {
```
Comment (ruanwenjun) [inline dolphinscheduler-ui/src/views/projects/task/instance/index.tsx]: Will the res be null here?

**Review by ruanwenjun — COMMENTED** [review]
Backend looks good to me.

**Comment by zhongjiajie** [comment]
do you have time to take a look the frontend part? @songjianet @Amy0104

**Comment by caishunfeng** [comment]
I rerun the fail CI.

**Review by Amy0104 — DISMISSED** [review]
The front end part LGTM.

**Comment by zhongjiajie** [comment]
I restart the failed CI

**Comment by zhongjiajie** [comment]
@zhuxt2015 Could you please rebase on upstream/dev? E2E restart multiple time but still failed

**Review by ruanwenjun — APPROVED** [review]
LGTM
