### PR TITLE
[Fix-16918][Task] Fix wrong permissions configuration while executing shell 

### LINKED ISSUE #16918: [Bug] [Task] Wrong permissions configuration while executing shell
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

https://dolphinscheduler.apache.org/zh-cn/docs/3.2.2/guide/parameter/file-parameter

By default, the shell is executed as the default user, but the working directory is created as root, so the default user does not have permission to create folders.

image
image

### What you expected to happen

The current directory permission should be assigned to default.

### How to reproduce

docker pseudo-distributed deployment

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by BruceWong96**
## Purpose of the pull request

close #16918 

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

## Pull Request Notice
[Pull Request Notice](https://github.com/apache/dolphinscheduler/blob/dev/docs/docs/en/contribute/join/pull-request.md)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

File: dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/FileUtils.java [hunk 1]
```diff
@@ -272,6 +271,12 @@ public static void createDirectoryWith755(@NonNull Path path) throws IOException
         }
     }
 
+    public static Path setOwner(@NonNull Path path, @NonNull String owner) throws IOException {
+        UserPrincipalLookupService lookupService = FileSystems.getDefault().getUserPrincipalLookupService();
+        UserPrincipal user = lookupService.lookupPrincipalByName(owner);
+        return Files.setOwner(path, user);
```
Comment (ruanwenjun) [inline dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/FileUtils.java]: `Files.setOwner` can only be executed by root, this is not expected.

File: dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/utils/TaskExecutionContextUtils.java [hunk 2]
```diff
@@ -51,6 +52,9 @@ public static void createTaskInstanceWorkingDirectory(TaskExecutionContext taskE
                         taskInstanceWorkingDirectory);
             }
             FileUtils.createDirectoryWith755(Paths.get(taskInstanceWorkingDirectory));
+            final Path taskInstanceWorkingDirectoryPath = Paths.get(taskInstanceWorkingDirectory);
```
Comment (ruanwenjun) [inline dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/utils/TaskExecutionContextUtils.java]: If we change to `775` and make bootstrap user has the same group with tenant, then tenant will have permission to create file at working directory.

Comment (BruceWong96) [reply dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/utils/TaskExecutionContextUtils.java]: > If we change to `775` and make bootstrap user has the same group with tenant, then tenant will have permission to create file at working directory.

So, can i create a function createDirectoryWith775() and call it here ?

File: dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/FileUtils.java (hunk 1 above)
Comment (BruceWong96) [reply dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/FileUtils.java]: OK

File: dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/utils/TaskExecutionContextUtils.java (hunk 2 above)
Comment (ruanwenjun) [reply dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/utils/TaskExecutionContextUtils.java]: I think we can. cc @caishunfeng, @SbloodyS

Comment (SbloodyS) [reply dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/utils/TaskExecutionContextUtils.java]: I'm ok with this. If we change the task instance working directory to 775, we should add it to the installation docs to tell users add tenant to ds user's group.

Comment (BruceWong96) [reply dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/utils/TaskExecutionContextUtils.java]: @SbloodyS 
Which part of the document should I update?
Also, please review the code i just committed.

Thanks.

Comment (SbloodyS) [reply dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/utils/TaskExecutionContextUtils.java]: https://github.com/apache/dolphinscheduler/blob/dev/docs/docs/zh/guide/security/security.md
https://github.com/apache/dolphinscheduler/blob/dev/docs/docs/en/guide/security/security.md


The create tenant part.

Comment (BruceWong96) [reply dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/utils/TaskExecutionContextUtils.java]: > https://github.com/apache/dolphinscheduler/blob/dev/docs/docs/zh/guide/security/security.md https://github.com/apache/dolphinscheduler/blob/dev/docs/docs/en/guide/security/security.md
> 
> The create tenant part.

Finished.

File: docs/docs/en/guide/security/security.md [hunk 3]
```diff
@@ -19,7 +19,9 @@ Administrator login, default username/password: admin/dolphinscheduler123
 - Tenant Code: **The tenant code is the user on Linux, unique and cannot be repeated**
 - The administrator enters the `Security Center->Tenant Management` page, and clicks the `Create Tenant` button to create a tenant.
 
-> Note: Currently, only admin users can modify tenant.
+> Note: 
+> 1. Currently, only admin users can modify tenant.
+> 2. If you create a tenant manually in the environment, you need to add the current tenant to the configured group, otherwise the tenant does not have working directory permissions.
```
Comment (SbloodyS) [inline docs/docs/en/guide/security/security.md]:
```suggestion
> 2. If you create a tenant manually in the Linux, you need to add the manually created tenant to the dolphinscheduler bootstrap user's group, so that the tenant will have enough working directory permissions.
```

File: docs/docs/zh/guide/security/security.md [hunk 4]
```diff
@@ -18,7 +18,9 @@
 - 租户编码：**租户编码是 Linux上 的用户，唯一，不能重复**
 - 管理员进入安全中心->租户管理页面，点击“创建租户”按钮，创建租户。
 
-> 注意：目前仅有 admin 用户可以修改租户。
+> 注意：
+> 1. 目前仅有 admin 用户可以修改租户；
+> 2. 如果用户手动在环境中创建租户，需要把当前租户添加到已配置的用户组下，否则该租户不具备工作目录的权限。
```
Comment (SbloodyS) [inline docs/docs/zh/guide/security/security.md]: Same as english.

File: dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/FileUtils.java [hunk 5]
```diff
@@ -289,6 +291,29 @@ public static void setFileTo755(File file) throws IOException {
...
+            if (parent != null && !parent.toFile().exists()) {
+                createDirectoryWith755(parent);
+            }
+
+            try {
+                Files.createDirectory(path);
+                Files.setPosixFilePermissions(path, PERMISSION_775);
+            } catch (FileAlreadyExistsException fileAlreadyExistsException) {
+                // Catch the FileAlreadyExistsException here to avoid create the same parent directory in parallel
+                log.debug("The directory: {} already exists", path);
```
Comment (SbloodyS) [inline dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/FileUtils.java]:
```suggestion
                log.error("The directory: {} already exists", path);
```

File: docs/docs/zh/guide/security/security.md [hunk 6]
```diff
@@ -18,7 +18,9 @@
 - 租户编码：**租户编码是 Linux上 的用户，唯一，不能重复**
 - 管理员进入安全中心->租户管理页面，点击“创建租户”按钮，创建租户。
 
-> 注意：目前仅有 admin 用户可以修改租户。
+> 注意：
+> 1. 目前仅有 admin 用户可以修改租户；
+> 2. 如果您在 Linux 中手动创建一个租户，则需要将手动创建的租户添加到 dolphinscheduler bootstrap 用户组，以便该租户拥有足够的工作目录权限。
```
Comment (SbloodyS) [inline docs/docs/zh/guide/security/security.md]:
```suggestion
> 2. 如果您在 Linux 中手动创建一个租户，则需要将手动创建的租户添加到 dolphinscheduler 启动用户组，以便该租户拥有足够的工作目录权限。
```

**Comment by SbloodyS** [comment]
You should run `mvn spotless:apply` to format the code. @BruceWong96

**Comment by BruceWong96** [comment]
> You should run `mvn spotless:apply` to format the code. @BruceWong96

Finished. Thanks.

**Comment by BruceWong96** [comment]
@caishunfeng @EricGao888  PTAL.

File: dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/FileUtils.java [hunk 7]
```diff
@@ -289,6 +291,29 @@ public static void setFileTo755(File file) throws IOException {
...
+    public static void createDirectoryWith775(@NonNull Path path) throws IOException {
+        if (path.toFile().exists()) {
+            return;
+        }
+        if (OSUtils.isWindows()) {
+            Files.createDirectories(path);
+        } else {
+            Path parent = path.getParent();
+            if (parent != null && !parent.toFile().exists()) {
+                createDirectoryWith755(parent);
```
Comment (ruanwenjun) [inline dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/FileUtils.java]:
```suggestion
                createDirectoryWith775(parent);
```

Can we unify the method `createDirectoryWith755` ? these two method has the same logic.
We can create a new method createDirectory(@NonNull Path path, Set<PosixFilePermission> permissions);

**Review by ruanwenjun — CHANGES_REQUESTED** [review]

File: dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/FileUtils.java [hunk 8]
```diff
@@ -289,6 +291,29 @@ public static void setFileTo755(File file) throws IOException {
         }
     }
 
+    public static void createDirectoryWith775(@NonNull Path path) throws IOException {
+        if (path.toFile().exists()) {
+            return;
+        }
+        if (OSUtils.isWindows()) {
+            Files.createDirectories(path);
+        } else {
```
Comment (SbloodyS) [inline dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/FileUtils.java:279]: I think we can remove this since we don't support running on windows.

Comment (ruanwenjun) [reply dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/FileUtils.java:300]: +1

Comment (ruanwenjun) [reply dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/FileUtils.java:279]: The only one use case is user can debug some tasks like sql task on windows.

Comment (SbloodyS) [reply dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/FileUtils.java:279]: Okay.

File: dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/FileUtils.java (hunk 7 above)
Comment (BruceWong96) [reply dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/FileUtils.java]: Finished, thanks for your advice. PATL. @ruanwenjun

**Review by SbloodyS — APPROVED** [review]
LGTM

**Review by ruanwenjun — APPROVED** [review]
LGTM
