### PR TITLE
[Fix-16934][api] When creating workflows containing switch nodes in different orders, the copied workflows may lose associations.

### LINKED ISSUE #16934: [Bug] [Module Name] When creating workflows containing switch nodes in different orders, the copied workflows may lose associations.
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

当按照不同顺序创建含有switch节点的工作流时，复制出来的工作流存在丢失关联关系的情况。可见文件中的gif
[sw.zip](https://github.com/user-attachments/files/18272248/sw.zip)

### What you expected to happen

*

### How to reproduce

*

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by llllkid**
## Purpose of the pull request

Fix #16934 

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

## Pull Request Notice
[Pull Request Notice](https://github.com/apache/dolphinscheduler/blob/dev/docs/docs/en/contribute/join/pull-request.md)

If your pull request contains incompatible change, you should also add it to `docs/docs/en/guide/upgrade/incompatible.md`

### CODE REVIEW

**Comment by llllkid** [comment]
@SbloodyS @caishunfeng PTAL

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/WorkflowDefinitionServiceImpl.java [hunk 1]
```diff
@@ -2118,37 +2118,38 @@ protected void doBatchOperateWorkflowDefinition(User loginUser,
...
+                        SwitchParameters.SwitchResult switchResult = switchParameters.getSwitchResult();
+                        switchResult.getDependTaskList().forEach(switchResultVo -> {
+                            switchResultVo.setNextNode(taskCodeMap.get(switchResultVo.getNextNode()));
+                        });
+                        if (switchResult.getNextNode() != null) {
+                            switchResult.setNextNode(
+                                    taskCodeMap.get(switchResult.getNextNode()));
+                        }
+                        taskDefinitionLog.setTaskParams(JSONUtils.toJsonString(switchParameters));
+                    }
```
Comment (SbloodyS) [inline dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/WorkflowDefinitionServiceImpl.java:2152]: Why move this code to here?

Comment (llllkid) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/WorkflowDefinitionServiceImpl.java:2152]: > Why move this code to here?

I think this is git's display problem, 
I don't move this code to here, 
I added `taskDefinitionLogs.forEach` before `for (TaskDefinitionLog taskDefinitionLog : taskDefinitionLogs)`, because we need put all taskDefinitionLog's new code into taskCodeMap before `taskDefinitionLog.setTaskParams`.

Comment (SbloodyS) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/WorkflowDefinitionServiceImpl.java:2152]: The commit shows it's not a display issue.
https://github.com/apache/dolphinscheduler/blob/48304f2a6c20de7471739b8889c2d02c41eef17d/dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/WorkflowDefinitionServiceImpl.java

Comment (llllkid) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/WorkflowDefinitionServiceImpl.java:2152]: > The commit shows it's not a display issue. https://github.com/apache/dolphinscheduler/blob/48304f2a6c20de7471739b8889c2d02c41eef17d/dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/WorkflowDefinitionServiceImpl.java

I think I misunderstood your question.  
Do you want to ask me why I move this code after `taskDefinitionLog.setName`?
Because for better readability:
```
 taskDefinitionLog.setCode();
 taskDefinitionLog.setProjectCode();
 taskDefinitionLog.setVersion();
 taskDefinitionLog.setName();
 if (TaskTypeUtils.isSwitchTask(taskDefinitionLog.getTaskType())) {
 ...
      taskDefinitionLog.setTaskParams();
 ...
 }
```
Is better than
```
 taskDefinitionLog.setCode();
 if (TaskTypeUtils.isSwitchTask(taskDefinitionLog.getTaskType())) {
 ...
      taskDefinitionLog.setTaskParams();
 ...
 }
 taskDefinitionLog.setProjectCode();
 taskDefinitionLog.setVersion();
 taskDefinitionLog.setName();

```

Comment (llllkid) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/WorkflowDefinitionServiceImpl.java:2152]: > > The commit shows it's not a display issue. https://github.com/apache/dolphinscheduler/blob/48304f2a6c20de7471739b8889c2d02c41eef17d/dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/WorkflowDefinitionServiceImpl.java
> 
> I think I misunderstood your question. Do you want to ask me why I move this code after `taskDefinitionLog.setName`? Because for better readability:
> 
> ```
>  taskDefinitionLog.setCode();
>  taskDefinitionLog.setProjectCode();
>  taskDefinitionLog.setVersion();
>  taskDefinitionLog.setName();
>  if (TaskTypeUtils.isSwitchTask(taskDefinitionLog.getTaskType())) {
>  ...
>       taskDefinitionLog.setTaskParams();
>  ...
>  }
> ```
> 
> Is better than
> 
> ```
>  taskDefinitionLog.setCode();
>  if (TaskTypeUtils.isSwitchTask(taskDefinitionLog.getTaskType())) {
>  ...
>       taskDefinitionLog.setTaskParams();
>  ...
>  }
>  taskDefinitionLog.setProjectCode();
>  taskDefinitionLog.setVersion();
>  taskDefinitionLog.setName();
> ```

Is that the question you want to ask? @SbloodyS

**Comment by llllkid** [comment]
@SbloodyS @caishunfeng @ruanwenjun PTAL

**Review by ruanwenjun — APPROVED** [review]
LGTM.

The main diff is initialized the task code firstly.

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/WorkflowDefinitionServiceImpl.java (hunk 1 above)
Comment (SbloodyS) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/WorkflowDefinitionServiceImpl.java:2152]: Thanks for clarification.

**Review by SbloodyS — APPROVED** [review]
+1
