### PR TITLE
[Fix-9975] The selected task instance was recreated when the Master service failed over.

### LINKED ISSUE #9975: [Bug-BE] The selected task instance was recreated when the Master service failed over
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

The selected task instance was recreated when the Master service failed over

### What you expected to happen

No new instances should be created.

### How to reproduce

Stop the Master service during workflow execution, and then start the Master again.

### Anything else

No Response.

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by WangJPLeo**
…ed over.

## Purpose of the pull request

The selected task instance was recreated when the Master service failed over.
[#9955 mentioned the issue.]

## Brief change log

close #9975 

## Verify this pull request

Manually verified the change by testing locally.

### CODE REVIEW

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteThread.java [hunk 1]
```diff
@@ -1953,10 +1953,10 @@ private boolean checkTaskQueue() {
      * is new process instance
      */
     private boolean isNewProcessInstance() {
-        if (ExecutionStatus.RUNNING_EXECUTION == processInstance.getState() && processInstance.getRunTimes() == 1) {
-            return true;
-        } else {
+        if (ExecutionStatus.RUNNING_EXECUTION == processInstance.getState() && processInstance.getRunTimes() >= 1) {
```
Comment (zhuangchong) [inline dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteThread.java]: Returns the expression result directly.

Comment (WangJPLeo) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteThread.java]: Good advice, thanks

**Review by caishunfeng — APPROVED** [review]
+1
