### PR TITLE
[Fix-13260][API] Ironed out the issue with lacking the value of user's name when querying the list of workflow definitions.

### LINKED ISSUE #13260: [Bug] [API] When querying the list of workflow definitions the api response result lacks the value of user name.
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When querying the list of workflow definitions the api response result lacks the value of user name.

image

### What you expected to happen

I expect that the user name of workflow definition can be displayed.

### How to reproduce

1.Visit the workflow definition.
2.Look at the column 'Create User' on the table of workflow definitions.

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by calvinjiang**
## Purpose of the pull request

This PR will close #13260 .

## Verify this pull request
- *Manually verified the change by testing locally.* 

image

### CODE REVIEW

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessDefinitionServiceImpl.java [hunk 1]
```diff
@@ -597,8 +597,10 @@ public PageInfo<ProcessDefinition> queryProcessDefinitionListPaging(@NonNull Use
             // todo: use batch query
             ProcessDefinitionLog processDefinitionLog =
                     processDefinitionLogMapper.queryByDefinitionCodeAndVersion(pd.getCode(), pd.getVersion());
-            User user = userMapper.selectById(processDefinitionLog.getOperator());
-            pd.setModifyBy(user.getUserName());
+            User modifiedUser = userMapper.selectById(processDefinitionLog.getOperator());
+            pd.setModifyBy(modifiedUser.getUserName());
+            User createUser = userMapper.selectById(processDefinitionLog.getUserId());
```
Comment (SbloodyS) [inline dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessDefinitionServiceImpl.java]: If the pageSize is large, the number of queries to the database will double. This will increase the load on the database.

**Review by SbloodyS — CHANGES_REQUESTED** [review]

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessDefinitionServiceImpl.java (hunk 1 above)
Comment (calvinjiang) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessDefinitionServiceImpl.java]: Sure. It definitely increases the load on the database. I'll adjust the way to query users.

**Review by zhuangchong — DISMISSED** [review]
+1

**Review by SbloodyS — APPROVED** [review]
+1
