### PR TITLE
[Fix-7654]Dependent node onChangeProjectCode error

### LINKED ISSUE #7654: [Bug] [UI] Dependent node onChangeProjectCode error
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What you expected to happen

change project successfully.

### How to reproduce

An error will be reported when switching items that do not belong to the current project at the dependency node.It seems like ${state}.projectCode did not change.Therefore, the tasks of other projects cannot be queried.

### Anything else

_No response_

### Version

2.0.1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by lenboo**
close #7654  check the project permission.

### CODE REVIEW

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessDefinitionServiceImpl.java [hunk 1]
```diff
@@ -1102,9 +1104,13 @@ private String recursionProcessDefinitionName(long projectCode, String processDe
             putMsg(result, Status.PROCESS_DEFINE_NOT_EXIST, codes);
             return result;
         }
+        HashMap<Long, Project> userProjects =  new HashMap(Constants.DEFAULT_HASH_MAP_SIZE);
```
Comment (caishunfeng) [inline dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessDefinitionServiceImpl.java:1107]: It's better to set the map size by db query result.

Comment (lenboo) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessDefinitionServiceImpl.java:1107]: > It's better to set the map size by db query result.

It's just a default initialize value, and the hash map size can be extended automatically.

**Review by brave-lee — APPROVED** [review]
+1
