### PR TITLE
[Fix-13283][Master] Worker failover cause task repeat run

### LINKED ISSUE #13283: [Bug] [Master] Worker failover cause task repeat run
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

We have a long run mapreduce task, which will duration a few hours, like 12hours. After we doing worker and master rolling restart, this mr task keep submit to yarn every 10 mins, and the old one failed to kill as we found the error log.
Finally, this task repeat submit many mr instance cause out yarn cluster run out of resources.

Our version is 2.0.7
After, we diging into the code, we found something about the worker failover within `MasterRegistryClient`
```
private boolean checkTaskAfterWorkerStart(List<Server> workerServers, TaskInstance taskInstance) {
        if (StringUtils.isEmpty(taskInstance.getHost())) {
            return false;
        }

        Date taskTime = taskInstance.getStartTime() == null ? taskInstance.getSubmitTime() : taskInstance.getStartTime();

        Date workerServerStartDate = getServerStartupTime(workerServers, taskInstance.getHost());
        if (workerServerStartDate != null) {
            return taskTime.after(workerServerStartDate);
        }
        return false;
    }
```
The failover code use the `start_time`  of task intance,  instead of `submit_time`. And `start_time` will not update every `NEED_FAULT_TOLERANCE`, the `submit_time` is the updated one. Which cause task submit again and again, because this mr task will not finsih within the failover check interval, which is 10min

And here is the code in version 3.x
```
// The worker is active, may already send some new task to it
        if (taskInstance.getSubmitTime() != null && taskInstance.getSubmitTime()
            .after(needFailoverWorkerStartTime.get())) {
            LOGGER.info(
                "The taskInstance's submitTime: {} is after the need failover worker's start time: {}, the taskInstance is newly submit, it doesn't need to failover",
                taskInstance.getSubmitTime(),
                needFailoverWorkerStartTime.get());
            return false;
        }
```

### What you expected to happen

Worker failover should use `submit_time` to judge

And also, we wanna to know that, if there is a hive sql task or shell task, and when worker failover happen, will this sql task repeat run, because we can not found the code about kill the hive sql. If not, may it be a problem?

### How to reproduce

1. create process with a mr task, which run longer than the failover check interval
2. submit a process instance
3. restart worker
4. check how many mr task submit on yarn

### Anything else

_No response_

### Version

2.0.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by KEN-LJQ**
## Purpose of the pull request

Fix #13283 

## Brief change log
change to use `submit_time`, instread of `start_time` as failover check

### CODE REVIEW

**Comment by wcmolin** [comment]
+1

File: dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/registry/MasterRegistryClient.java [hunk 1]
```diff
@@ -317,11 +317,14 @@ private boolean checkTaskAfterServerStart(List<Server> servers, TaskInstance tas
...
-
-        Date serverStartDate = getServerStartupTime(servers, taskInstance.getHost());
-        if (serverStartDate != null) {
-            return taskTime.after(serverStartDate);
+        Date taskSubmitTime = taskInstance.getSubmitTime();
+        Date serverStartTime = getServerStartupTime(servers, taskInstance.getHost());
+        if (taskSubmitTime != null && serverStartTime != null && taskSubmitTime.after(serverStartTime)) {
+            logger.info(
+                    "The taskInstance's submitTime: {} is after the need failover server's start time: {}, the taskInstance is newly submit, it doesn't need to failover",
+                    taskSubmitTime,
```
Comment (brave-lee) [inline dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/registry/MasterRegistryClient.java]: Please format time, like `DateUtils.dateToString(taskSubmitTime)`

Comment (KEN-LJQ) [reply dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/registry/MasterRegistryClient.java]: done, please review

**Review by brave-lee — APPROVED** [review]
+1
