### PR TITLE
[fix] Process definition length too long when copy or import

### LINKED ISSUE #10622: [Bug] [Api] The name of the workflow or task exceeds the length limit after the workflow is copied multiple times
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

The name of the workflow or task exceeds the length limit after the workflow is copied multiple times
image

### What you expected to happen

The name length of the workflow or task does not exceed the limit

### How to reproduce

Copy a workflow until an error of "batch copy process definition error" is reported

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by zhuxt2015**
## Purpose of the pull request
Fix workflow name or  task name exceed the length limit when copying or importing workflows

close #10622

## Brief change log
If the name of the workflow or task contains `_copy_` or `_import_`, and the last timestamp can be formatted, the new name only replaces the timestamp of original name

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

### CODE REVIEW

**Comment by SbloodyS** [comment]
please associate the issue @zhuxt2015

**Comment by SbloodyS** [comment]
to target specific issue from PR, we recommend use keyword fix: #issue_id or close: #issue_id or closes: #issue_id in your PR describe(not title, just desc). It would not only connect issue to PR but also close issue automatically when PR is be closed.

**Review by SbloodyS — DISMISSED** [review]
LGTM

**Comment by davidzollo** [comment]
please solve the conflicts, thx

**Comment by zhuxt2015** [comment]
> please solve the conflicts, thx

Done

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessDefinitionServiceImpl.java [hunk 1]
```diff
@@ -1876,6 +1879,31 @@ protected void doBatchOperateProcessDefinition(User loginUser,
...
+     * @param suffix "_copy_" or "_import_"
+     * @return
+     */
+    private String getNewName(String originalName, String suffix) {
+        StringBuilder newName = new StringBuilder();
+        if (originalName.contains(suffix)) {
+            final String originalTimeStamp = originalName.substring(originalName.lastIndexOf(suffix) + suffix.length());
+            try {
+                SimpleDateFormat dateFormat = new SimpleDateFormat(Constants.YYYYMMDDHHMMSSSSS);
+                dateFormat.parse(originalTimeStamp);
```
Comment (ruanwenjun) [inline dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessDefinitionServiceImpl.java]: This is unnecessary?
```suggestion
                
```

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessDefinitionServiceImpl.java [hunk 2]
```diff
@@ -1876,6 +1879,31 @@ protected void doBatchOperateProcessDefinition(User loginUser,
...
+                //replace timestamp in originalName
+                newName.append(originalName, 0, originalName.lastIndexOf(suffix))
+                        .append(suffix)
+                        .append(DateUtils.getCurrentTimeStamp());
+                return newName.toString();
+            } catch (Exception e) {
+                logger.error("error while parse last timestamp in {}", originalName);
```
Comment (ruanwenjun) [inline dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessDefinitionServiceImpl.java]: It's better to directly throw exception here, if the code is right, there are should not exist exception.

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessDefinitionServiceImpl.java [hunk 3]
```diff
@@ -1876,6 +1878,27 @@ protected void doBatchOperateProcessDefinition(User loginUser,
         }
     }
 
+    /**
+     * get new Task name or Process name when copy or import operate
+     * @param originalName Task or Process original name
+     * @param suffix "_copy_" or "_import_"
+     * @return
+     */
+    private String getNewName(String originalName, String suffix) {
```
Comment (zhongjiajie) [inline dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessDefinitionServiceImpl.java]: can we add some test for test function? maybe we can test the public function use it.
BTW, how about the process definition contain `_copy_` or `_import_` in the name? like `wf_copy_all_ods_data_to_dw`

Comment (zhuxt2015) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessDefinitionServiceImpl.java]: use regex match

**Review by zhongjiajie — APPROVED** [review]
LGTM, thanks
