### PR TITLE
[Bug] [Task] SQL task no exception stack trace in task log

### LINKED ISSUE #10655: [Bug] [Task] SQL task and Datax Task no exception stack trace in task log
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

when SQL task or Datax task execution failed, only print exception message, no stack trace, which is not convenient to troubleshoot the cause of the problem

image

### What you expected to happen

print exception stack trace to task log after task execution failed. 
image

### How to reproduce

execute a sql with a column not exist 

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by zhuxt2015**
## Purpose of the pull request
fix: #10655 

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

### CODE REVIEW

File: dolphinscheduler-task-plugin/dolphinscheduler-task-datax/src/main/java/org/apache/dolphinscheduler/plugin/task/datax/DataxTask.java [hunk 1]
```diff
@@ -167,6 +167,7 @@ public void handle() throws Exception {
             setAppIds(commandExecuteResult.getAppIds());
             setProcessId(commandExecuteResult.getProcessId());
         } catch (Exception e) {
+            logger.error("datax task error", e);
```
Comment (ruanwenjun) [inline dolphinscheduler-task-plugin/dolphinscheduler-task-datax/src/main/java/org/apache/dolphinscheduler/plugin/task/datax/DataxTask.java:170]: In fact, the exception will be thrown to upper layer, and will log at the upper layer. I don't suggest we log the exception and throw it again, this will cause the exception occur multiple times in log.

**Comment by ruanwenjun** [comment]
@zhuxt2015 Could you please also remove the log in sql task?

**Comment by zhuxt2015** [comment]
> @zhuxt2015 Could you please also remove the log in sql task?

I think it is better to print out the error stack information when the SQL task reports an error, so that it is convenient to troubleshoot the problem. Instead of going to the worker node to find the error stack information

**Comment by ruanwenjun** [comment]
> > @zhuxt2015 Could you please also remove the log in sql task?
> 
> I think it is better to print out the error stack information when the SQL task reports an error, so that it is convenient to troubleshoot the problem. Instead of going to the worker node to find the error stack information

OK, I got you, sorry for my fault, please add the log print in datax.

**Comment by zhuxt2015** [comment]
> > > @zhuxt2015 Could you please also remove the log in sql task?
> > 
> > 
> > I think it is better to print out the error stack information when the SQL task reports an error, so that it is convenient to troubleshoot the problem. Instead of going to the worker node to find the error stack information
> 
> OK, I got you, sorry for my fault, please add the log print in datax.

That's all right.

**Review by ruanwenjun — APPROVED** [review]
LGTM
