### PR TITLE
[Fix-16929][Meter] Fix startup failed when metrics is disabled.

### LINKED ISSUE #16929: [Bug] [Metric] metrics switch can not work
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

image

when setting this conf to false  in `application.yaml`, master/worker server cannot launch

image

### What you expected to happen

launch server normally

### How to reproduce

when setting this conf to false  in `application.yaml`, master/worker server cannot launch

### Anything else

if anyone wants to disable metric for safety reasons,  set the management port to -1

see https://docs.spring.io/spring-boot/reference/actuator/monitoring.html

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by yingh0ng**
## Purpose of the pull request

close #16929

## Brief change log

- Add new beans implements MetricsProvider which work on metrics-disabled.

## Verify this pull request

This pull request is already covered by existing tests, such as *(please describe tests)*.

## Pull Request Notice
[Pull Request Notice](https://github.com/apache/dolphinscheduler/blob/dev/docs/docs/en/contribute/join/pull-request.md)

If your pull request contains incompatible change, you should also add it to `docs/docs/en/guide/upgrade/incompatible.md`

### CODE REVIEW

File: dolphinscheduler-meter/src/main/java/org/apache/dolphinscheduler/meter/MeterAutoConfiguration.java [hunk 1]
```diff
@@ -42,20 +43,28 @@
  */
 @Configuration(proxyBeanMethods = false)
 @EnableAspectJAutoProxy
-@ConditionalOnProperty(prefix = "metrics", name = "enabled", havingValue = "true")
```
Comment (ruanwenjun) [inline dolphinscheduler-meter/src/main/java/org/apache/dolphinscheduler/meter/MeterAutoConfiguration.java:45]: Can we remove this config? Then we will enable the metrics in all times.

Comment (yingh0ng) [reply dolphinscheduler-meter/src/main/java/org/apache/dolphinscheduler/meter/MeterAutoConfiguration.java:45]: Do you mean, users are not allowed to disable metrics?

Comment (Gallardot) [reply dolphinscheduler-meter/src/main/java/org/apache/dolphinscheduler/meter/MeterAutoConfiguration.java:45]: > Can we remove this config? Then we will enable the metrics in all times.

LGTM.  Enabling metric is a better practice, but why do users need to turn it off?

File: dolphinscheduler-meter/src/main/java/org/apache/dolphinscheduler/meter/MeterAutoConfiguration.java [hunk 2]
```diff
@@ -42,20 +43,28 @@
...
 public class MeterAutoConfiguration {
 
     @Bean
+    @ConditionalOnProperty(prefix = "metrics", name = "enabled", havingValue = "true")
```
Comment (ruanwenjun) [inline dolphinscheduler-meter/src/main/java/org/apache/dolphinscheduler/meter/MeterAutoConfiguration.java]:
```suggestion
```

File: dolphinscheduler-meter/src/main/java/org/apache/dolphinscheduler/meter/MeterAutoConfiguration.java [hunk 3]
```diff
@@ -42,20 +43,28 @@
...
     }
 
     @Bean
+    @ConditionalOnProperty(prefix = "metrics", name = "enabled", havingValue = "false", matchIfMissing = true)
+    public EmptyMetricsProvider emptyMetricsProvider() {
+        return new EmptyMetricsProvider();
+    }
+
+    @Bean
+    @ConditionalOnProperty(prefix = "metrics", name = "enabled", havingValue = "true")
```
Comment (ruanwenjun) [inline dolphinscheduler-meter/src/main/java/org/apache/dolphinscheduler/meter/MeterAutoConfiguration.java]:
```suggestion
```

File: dolphinscheduler-meter/src/main/java/org/apache/dolphinscheduler/meter/MeterAutoConfiguration.java [hunk 4]
```diff
@@ -42,20 +43,28 @@
...
     public TimedAspect timedAspect(MeterRegistry registry) {
         return new TimedAspect(registry);
     }
 
     @Bean
+    @ConditionalOnProperty(prefix = "metrics", name = "enabled", havingValue = "true")
```
Comment (ruanwenjun) [inline dolphinscheduler-meter/src/main/java/org/apache/dolphinscheduler/meter/MeterAutoConfiguration.java]:
```suggestion
```

File: dolphinscheduler-meter/src/main/java/org/apache/dolphinscheduler/meter/metrics/EmptyMetricsProvider.java [hunk 5]
```diff
@@ -0,0 +1,27 @@
...
+package org.apache.dolphinscheduler.meter.metrics;
+
+public class EmptyMetricsProvider implements MetricsProvider {
+
+    @Override
+    public SystemMetrics getSystemMetrics() {
+        return new SystemMetrics();
+    }
+
+}
```
Comment (ruanwenjun) [inline dolphinscheduler-meter/src/main/java/org/apache/dolphinscheduler/meter/metrics/EmptyMetricsProvider.java]:
```suggestion
```

File: dolphinscheduler-meter/src/main/java/org/apache/dolphinscheduler/meter/MeterAutoConfiguration.java (hunk 1 above)
Comment (ruanwenjun) [reply dolphinscheduler-meter/src/main/java/org/apache/dolphinscheduler/meter/MeterAutoConfiguration.java:45]: > Do you mean, users are not allowed to disable metrics?

Yes, the server heartbeat rely on the metrics provider, so this is must.

Comment (yingh0ng) [reply dolphinscheduler-meter/src/main/java/org/apache/dolphinscheduler/meter/MeterAutoConfiguration.java:45]: > Yes, the server heartbeat rely on the metrics provider, so this is must.
LGTM. Fix it later.

**Comment by yingh0ng** [comment]
@ruanwenjun The OWASP dependency check failed. PTAL.
The error is:
> io.github.jeremylong.openvulnerability.client.nvd.NvdApiException: Failed to parse NVD data

**Comment by SbloodyS** [comment]
> @ruanwenjun The OWASP dependency check failed. PTAL. The error is:

You don't need to pay attention to it at present. Just ignore it.

**Review by ruanwenjun — DISMISSED** [review]
LGTM

File: dolphinscheduler-meter/pom.xml [hunk 6]
```diff
@@ -94,6 +94,10 @@
             <groupId>org.springframework.boot</groupId>
             <artifactId>spring-boot-starter-aop</artifactId>
         </dependency>
+        <dependency>
+            <groupId>org.springframework.boot</groupId>
+            <artifactId>spring-boot-starter-test</artifactId>
+        </dependency>
```
Comment (SbloodyS) [inline dolphinscheduler-meter/pom.xml]: Why adding this? I can not see any related code in the pr using this dependency.

Comment (yingh0ng) [reply dolphinscheduler-meter/pom.xml]: Yes, I no longer need it. I'll remove it.

**Review by SbloodyS — APPROVED** [review]
+1

**Review by ruanwenjun — APPROVED** [review]

**Review by Gallardot — APPROVED** [review]
