### PR TITLE
[Fix-4760][api][Repair dolphinscheduler-postgre.sql error sql]

### LINKED ISSUE #4760: [Bug][Api] init dolphinscheduler-postgre.sql error
**For better global communication, Please describe it in English. If you feel the description in English is not clear, then you can append description in Chinese(just for Mandarin(CN)), thx! **
**Describe the bug**
run dolphinscheduler-postgre.sql error about next sql:
INSERT INTO t_ds_alertgroup(id,alert_instance_ids, create_user_id, group_name, description, create_time, update_time)
VALUES (1, '1,2','dolphinscheduler warning group', 'dolphinscheduler warning group', '2018-11-29 10:20:39',
        '2018-11-29 10:20:39');

**To Reproduce**
Steps to reproduce the behavior, for example:
1. run dolphinscheduler-postgre.sql 
2. see error:
[Err] error:  INSERT has more specified fields than expressions
LINE 1: ...te_user_id, group_name, description, create_time, update_tim...

**Expected behavior**
fix this bug

**Screenshots**

**Which version of Dolphin Scheduler:**
 -[dev]

**Additional context**

**Requirement or improvement**
- Please describe about your requirements or improvement suggestions.

### PR DESCRIPTION
**Pull request by yakcy**
## *Tips*
- *Thanks very much for contributing to Apache DolphinScheduler.*
- *Please review https://dolphinscheduler.apache.org/en-us/community/index.html before opening a pull request.*

## What is the purpose of the pull request

This pull request fix dolphinscheduler-postgre.sql error sql

## Brief change log
Only update :
INSERT INTO t_ds_alertgroup(id,alert_instance_ids, create_user_id, group_name, description, create_time, update_time)
VALUES (1,'1,2', 1, 'default admin warning group', 'default admin warning group', '2018-11-29 10:20:39', '2018-11-29 10:20:39');

## Verify this pull request

*(Please pick either of the following options)*

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

example:

  - Just run dolphinscheduler-postgre.sql
  
this   close #issue4760

### CODE REVIEW

File: sql/dolphinscheduler-postgre.sql [hunk 1]
```diff
@@ -769,8 +769,7 @@ VALUES ('admin', '7ad2410b2f4c074479a8937a28a22b8f', '0', 'xxx@qq.com', '', '0',
 
 -- Records of t_ds_alertgroup，dolphinscheduler warning group
 INSERT INTO t_ds_alertgroup(id,alert_instance_ids, create_user_id, group_name, description, create_time, update_time)
-VALUES (1, '1,2','dolphinscheduler warning group', 'dolphinscheduler warning group', '2018-11-29 10:20:39',
-        '2018-11-29 10:20:39');
+VALUES (1,'1,2', 1, 'default admin warning group', 'default admin warning group', '2018-11-29 10:20:39', '2018-11-29 10:20:39');
```
Comment (chengshiwen) [inline sql/dolphinscheduler-postgre.sql:772]: Please replace `dolphinscheduler warning group` with `default admin warning group` globally. There should be four places that need to be modified including comments.

**Review by chengshiwen — CHANGES_REQUESTED** [review]

File: sql/dolphinscheduler-postgre.sql (hunk 1 above)
Comment (davidzollo) [reply sql/dolphinscheduler-postgre.sql:772]: > Please replace `dolphinscheduler warning group` with `default admin warning group` globally. There should be four places that need to be modified including comments.

Considering this is  yakcy's first time for contributing, replacing the comments could submit another PR

**Review by davidzollo — APPROVED** [review]
+1
happy new year,  thanks for your first contribution, looking forwarding to your deep participation

**Comment by yakcy** [comment]
> +1
> happy new year, thanks for your first contribution, looking forwarding to your deep participation

happy new year，I am very interested in ds, I will ，haha...

**Comment by chengshiwen** [comment]
@yakcy This pr introduced the failed unit test, resulting that this problem occurs in subsequent commit and pr.
**Updated**: the pr #4774 has fixed.

```
Error:  Errors: 
Error:    AlertGroupMapperTest.testQueryAllGroupList:170->createAlertGroups:265->createAlertGroup:228 » DuplicateKey
[INFO] 
Error:  Tests run: 179, Failures: 0, Errors: 1, Skipped: 0
```
