### PR TITLE
[Fix-17050][Master] Fix workflow graph topology logical error

### LINKED ISSUE #17050: [Bug] [Master] Workflow graph topology logical error
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When the number of tasks reaches 1000 or more, the master will be blocked indefinitely. It neither submits tasks nor resubmits the workflow. The command will remain in the command table permanently and cannot be removed by normal means. Only by clearing the corresponding command in the command table and restarting the master can the system return to normal. 

### What you expected to happen

[WI-0][TI-0] - 2025-03-10 21:24:10.101 INFO  [MasterCommandLoopThread] o.a.d.s.m.e.c.IdSlotBasedCommandFetcher:[67] - [Slot-0/1] Fetch 0 commands in 1ms.
[WI-0][TI-0] - 2025-03-10 21:24:11.129 INFO  [MasterCommandLoopThread] o.a.d.s.m.e.c.IdSlotBasedCommandFetcher:[67] - [Slot-0/1] Fetch 1 commands in 2ms.
[WI-0][TI-0] - 2025-03-10 21:24:11.694 INFO  [TaskGroupCoordinator] o.a.d.s.m.e.TaskGroupCoordinator:[186] - Success amend TaskGroupQueue status cost: 0/ms
[WI-0][TI-0] - 2025-03-10 21:24:11.694 INFO  [TaskGroupCoordinator] o.a.d.s.m.e.TaskGroupCoordinator:[240] - Success deal with force start TaskGroupQueue cost: 0/ms
[WI-0][TI-0] - 2025-03-10 21:24:11.694 INFO  [TaskGroupCoordinator] o.a.d.s.m.e.TaskGroupCoordinator:[129] - TaskGroupCoordinator round cost: 3/ms
[WI-0][TI-0] - 2025-03-10 21:24:16.703 INFO  [TaskGroupCoordinator] o.a.d.s.m.e.TaskGroupCoordinator:[186] - Success amend TaskGroupQueue status cost: 0/ms
[WI-0][TI-0] - 2025-03-10 21:24:16.704 INFO  [TaskGroupCoordinator] o.a.d.s.m.e.TaskGroupCoordinator:[240] - Success deal with force start TaskGroupQueue cost: 0/ms
[WI-0][TI-0] - 2025-03-10 21:24:16.705 INFO  [TaskGroupCoordinator] o.a.d.s.m.e.TaskGroupCoordinator:[129] - TaskGroupCoordinator round cost: 3/ms
The above master logs will keep repeating in a loop and will not enter the normal state of fetching commands. As a result, the current workflow cannot be completed, and new workflows cannot be submitted. Normally, the number of tasks should not cause this problem.

### How to reproduce

Submit a workflow with 1000 tasks. Well, it may take some time. You can spend a bit of time designing a script.

### Anything else

_No response_

### Version

3.2.x

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by MYssq**
## Purpose of the pull request

close #17050

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

## Pull Request Notice
[Pull Request Notice](https://github.com/apache/dolphinscheduler/blob/dev/docs/docs/en/contribute/join/pull-request.md)

If your pull request contains incompatible change, you should also add it to `docs/docs/en/guide/upgrade/incompatible.md`

### CODE REVIEW

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/graph/WorkflowGraphTopologyLogicalVisitor.java [hunk 1]
```diff
@@ -143,8 +143,11 @@ private void doVisitationInSubGraph(Set<String> subGraphNodes) {
             }
             for (String successor : successors) {
                 inDegreeMap.put(successor, inDegreeMap.get(successor) - 1);
+                // Add all non-repeating successors to bootstrapTaskCodes
+                if (!bootstrapTaskCodes.contains(successor)) {
+                    bootstrapTaskCodes.add(successor);
+                }
```
Comment (ruanwenjun) [inline dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/graph/WorkflowGraphTopologyLogicalVisitor.java]: There will still exist problem, please use a visited table to record the node which has been visted..

**Review by ruanwenjun — CHANGES_REQUESTED** [review]

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/graph/WorkflowGraphTopologyLogicalVisitor.java (hunk 1 above)
Comment (MYssq) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/graph/WorkflowGraphTopologyLogicalVisitor.java]: Thank you for your advice. The visited table has been added to solve this problem.

**Comment by ruanwenjun** [comment]
LGTM, please fix the code style

**Review by ruanwenjun — APPROVED** [review]
LGTM

**Review by SbloodyS — APPROVED** [review]
+1

**Comment by ruanwenjun** [comment]
Merged, and will be release at 3.3.0. Thanks for your PR.
