### PR TITLE
Fix homepage user statistics result missing filter by user

### LINKED ISSUE #7182: [Bug] [dolphinscheduler-api] Ordinary users do not create project related data. The process status statistics and task status statistics on the home page have data, and the process definition statistics display all user data
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

1.Ordinary users do not create project related data. The process status statistics and task status statistics on the home page have data
image
2.The current user should be displayed, and the data is 0
image

### Version

2.0.1-prepare

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by zhongjiajie**
For now when we create new user, it would see homepage
statisic info as admin user like, cause `projectCodeArray`
would not filter when we render sql. So I add prefix condition
to handle this situation.

fix #7182

### CODE REVIEW

File: dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/User.java [hunk 1]
```diff
@@ -221,6 +221,20 @@ public void setState(int state) {
...
+     * it could see all statistics information, so we return `null` to unlimited statistics
+     * scope, but if user is general user, it could only see himself statistics information
+     * filtering data by user id.
+     *
+     * @return user Integer
+     */
+    public Integer getUserStatId() {
+        return this.userType == UserType.ADMIN_USER ? null : this.id;
+    }
+
```
Comment (zhongjiajie) [inline dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/User.java]: For reviewers, I add attribute `getUserStatId` and add desc about it, to reduce deplicate code in service.

**Comment by zhongjiajie** [comment]
cc: @lenboo

**Review by lenboo — APPROVED** [review]
+1
