### PR TITLE
[Bug](dependent) Dependent downstream trigger error when schedule cycle not day.

### LINKED ISSUE #11709: [Bug] [Dependent] Dependent triger error version downstream
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

The historical version of the workflow is triggered downstream when dependency mode complement is enabled upstream

### What you expected to happen

Use the version of the day of the run.

### How to reproduce

截屏2022-08-31 15 13 54
截屏2022-08-31 15 13 41
截屏2022-08-31 15 13 58
截屏2022-08-31 15 14 07

### Anything else

_No response_

### Version

3.0.0

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### LINKED ISSUE #11732: [Bug] [Dependent] Dependent downstream trigger error when schedule cycle not day.
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Dependent downstream trigger error when schedule cycle not day.

### What you expected to happen

Can normal schedule downstream when upstream rerun use denpendency mode.
```
DependentProcessDefinition.getDependentCycle()
if (this.getProcessDefinitionCode() == dependentItem.getDefinitionCode())
```
this.getProcessDefinitionCode() should use upstream process code.

### How to reproduce

create two workflow, parent, child, child denpend on parent and schedule evert hour.

### Anything else

_No response_

### Version

3.0.0

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by stalary**
## Purpose of the pull request

This pr will close https://github.com/apache/dolphinscheduler/issues/11732 
This pr will close https://github.com/apache/dolphinscheduler/issues/11709

## Brief change log
1. DependentProcessDefinition.getDependentCycle use upstream code. this.getProcessDefinitionCode() before get the code of the downstream dependent task.
2. start downstream command get latest version.

### CODE REVIEW

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ExecutorServiceImpl.java [hunk 1]
```diff
@@ -891,7 +891,13 @@ protected int createComplementDependentCommand(List<Schedule> schedules, Command
 
         dependentCommand.setTaskDependType(TaskDependType.TASK_POST);
         for (DependentProcessDefinition dependentProcessDefinition : dependentProcessDefinitionList) {
-            dependentCommand.setProcessDefinitionCode(dependentProcessDefinition.getProcessDefinitionCode());
+            long processDefinitionCode = dependentProcessDefinition.getProcessDefinitionCode();
+
+            // get dependent downstream version
+            ProcessDefinition processDefinition = processDefinitionMapper.queryByCode(processDefinitionCode);
+            dependentCommand.setProcessDefinitionVersion(processDefinition.getVersion());
```
Comment (SbloodyS) [inline dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ExecutorServiceImpl.java]: I think it's better query the processDefinitionVersion through `org/apache/dolphinscheduler/dao/mapper/WorkFlowLineageMapper.xml:148`. So that we can  reduce the database query.

File: dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/DependentProcessDefinition.java [hunk 2]
```diff
@@ -60,14 +60,14 @@ public class DependentProcessDefinition {
...
-    public CycleEnum getDependentCycle() {
+    public CycleEnum getDependentCycle(long processDefinitionCode) {
         DependentParameters dependentParameters = this.getDependentParameters();
         List<DependentTaskModel> dependentTaskModelList = dependentParameters.getDependTaskList();
 
         for (DependentTaskModel dependentTaskModel : dependentTaskModelList) {
             List<DependentItem> dependentItemList = dependentTaskModel.getDependItemList();
             for (DependentItem dependentItem : dependentItemList) {
-                if (this.getProcessDefinitionCode() == dependentItem.getDefinitionCode()) {
+                if (processDefinitionCode == dependentItem.getDefinitionCode()) {
```
Comment (SbloodyS) [inline dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/DependentProcessDefinition.java]: Why did you change this?

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ExecutorServiceImpl.java (hunk 1 above)
Comment (stalary) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ExecutorServiceImpl.java]: ok, thanks.

File: dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/DependentProcessDefinition.java (hunk 2 above)
Comment (stalary) [reply dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/DependentProcessDefinition.java]: processDefinitionCode should be upstream process code, but current is itself process code, this due to match error.

File: dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/DependentProcessDefinition.java [hunk 3]
```diff
@@ -60,14 +65,14 @@ public class DependentProcessDefinition {
      * get dependent cycle
      * @return CycleEnum
      */
-    public CycleEnum getDependentCycle() {
+    public CycleEnum getDependentCycle(long processDefinitionCode) {
```
Comment (caishunfeng) [inline dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/entity/DependentProcessDefinition.java]: Please update the comment.
```suggestion
    public CycleEnum getDependentCycle(long upstreamProcessDefinitionCode) {
```

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ExecutorServiceImpl.java [hunk 4]
```diff
@@ -923,7 +924,8 @@ private List<DependentProcessDefinition> getComplementDependentDefinitionList(lo
     private List<DependentProcessDefinition> checkDependentProcessDefinitionValid(
                                                                                   List<DependentProcessDefinition> dependentProcessDefinitionList,
                                                                                   CycleEnum processDefinitionCycle,
-                                                                                  String workerGroup) {
+                                                                                  String workerGroup,
+                                                                                  long processDefinitionCode) {
```
Comment (caishunfeng) [inline dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ExecutorServiceImpl.java]:
```suggestion
                                                                                  long upstreamProcessDefinitionCode) {
```

**Comment by stalary** [comment]
done. @caishunfeng

**Review by SbloodyS — APPROVED** [review]
LGTM

**Review by caishunfeng — APPROVED** [review]
LGTM

**Comment by caishunfeng** [comment]
Hi @stalary Please check the fail CI

**Comment by stalary** [comment]
> Hi @stalary Please check the fail CI

`dolphinscheduler-alert-http` seems not modified by my code, and run success in my local env, can you rerun it?

**Comment by stalary** [comment]
> Hi @stalary Please check the fail CI

done.
