### PR TITLE
[Fix-14566][master] Fix serial_wait command_params does not replace global_params

### LINKED ISSUE #14566: [Bug] [dolphinscheduler-master] SERIAL_WAIT command_param does not replace global_params, rendering the parameters passed via the API ineffective
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When I run multiple instances of the same workflow using the API and the execution strategy of the workflow definition is set to serial wait, the state of the workflow instances changes from "state":"SERIAL_WAIT","desc":"wait by serial_wait strategy" to "state":"RUNNING_EXECUTION","desc":"recover serial wait". In this case, the start params passed in through the API does not replace the global_params, which results in the parameters passed through the API becoming ineffective.

API URL: projects/{projectCode}/executors/start-process-instance

### What you expected to happen

The parameters passed through the API should properly replace the global_params.

### How to reproduce

Running multiple instances at once through API.

### Anything else

I rapidly ran multiple instances of the same workflow through the API with the execution policy established as serial waiting. In theory, these instances should execute sequentially. However, I've observed that some instances are executing simultaneously instead of following the expected waiting sequence.

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by CallMeKingsley97**
…bal_params

This closes #14566

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java [hunk 1]
```diff
@@ -784,6 +785,16 @@ public void checkSerialProcess(ProcessDefinition processDefinition) {
...
+        // write the parameters of the nextProcessInstance to command
+        if (StringUtils.isNotEmpty(nextProcessInstance.getCommandParam())) {
+            Map<String, String> commandStartParamsMap = JSONUtils.toMap(nextProcessInstance.getCommandParam());
+            if (MapUtils.isNotEmpty(commandStartParamsMap)) {
+                Map<String, String> paramsMap = JSONUtils.toMap(commandStartParamsMap.get(CMD_PARAM_START_PARAMS));
+                if (MapUtils.isNotEmpty(paramsMap)) {
+                    cmdParam.put(CMD_PARAM_START_PARAMS, JSONUtils.toJsonString(paramsMap));
+                }
+            }
+        }
```
Comment (ruanwenjun) [inline dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java:797]: Why we need to set the workflow instance param to command?

**Review by ruanwenjun — CHANGES_REQUESTED** [review]

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java (hunk 1 above)
Comment (CallMeKingsley97) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java:797]: The next process instance to be awakened will create a new command, and The new command needs to keep the original "StartParams" fields

Comment (CallMeKingsley97) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java:797]: Whether I need to change the code   @ruanwenjun

Comment (ruanwenjun) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java:797]: It should work, but it's better to change the command consumer logic rather than put the param in wakeup command.

**Review by ruanwenjun — APPROVED** [review]

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java (hunk 1 above)
Comment (CallMeKingsley97) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java:797]: > It should work, but it's better to change the command consumer logic rather than put the param in wakeup command.

thanks!

**Review by EricGao888 — APPROVED** [review]

**Comment by SbloodyS** [comment]
So far I've no idea why `SqlServerDataSource` or `HiveDataSource`  e2e-test failed due to timeout error. 

I think may need to try upgrading version `test-containers-java` to see if it can be fixed. But this will take some time. In the mean time, Can we temporarily not perform these two tests?
@EricGao888 @zhongjiajie @ruanwenjun

**Comment by EricGao888** [comment]
> So far I've no idea why `SqlServerDataSource` or `HiveDataSource` e2e-test failed due to timeout error.
> 
> I think may need to try upgrading version `test-containers-java` to see if it can be fixed. But this will take some time. In the mean time, Can we temporarily not perform these two tests? @EricGao888 @zhongjiajie @ruanwenjun

I'm fine with it.

**Comment by zhongjiajie** [comment]
> So far I've no idea why `SqlServerDataSource` or `HiveDataSource` e2e-test failed due to timeout error.
> 
> I think may need to try upgrading version `test-containers-java` to see if it can be fixed. But this will take some time. In the mean time, Can we temporarily not perform these two tests? @EricGao888 @zhongjiajie @ruanwenjun

image

How about we make those tests optional for pr merged by add a new job for it? we still run but not required ci

**Comment by SbloodyS** [comment]
> How about we make those tests optional for pr merged by add a new job for it? we still run but not required ci

That sound good to me. I'll work on it.
