### PR TITLE
[Fix-4905][K8s] Fix incorrect host problem in minikube

### LINKED ISSUE #4905: [Bug][K8s] Incorrect host problem in minikube
**For better global communication, Please describe it in English. If you feel the description in English is not clear, then you can append description in Chinese(just for Mandarin(CN)), thx! **
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Deploy K8s on minikube by `helm`
2. Access `Worker groups manage`
3. See incorrect host

**Expected behavior**
Bug fixed, and the host in the picture below is correct:
image

**Screenshots**

Incorrect host:
image

**Which version of Dolphin Scheduler:**
 -[1.3.x]
 -[dev]

**Additional context**

**Requirement or improvement**
- Please describe about your requirements or improvement suggestions.

### PR DESCRIPTION
**Pull request by chengshiwen**
## What is the purpose of the pull request

*Fix incorrect host problem in minikube*

This closes #4905

## Brief change log

  - *Fix incorrect host problem in minikube*

## Verify this pull request

*(Please pick either of the following options)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

  - *dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/utils/NetUtilsTest.java*

### CODE REVIEW

**Comment by chengshiwen** [comment]
@CalvinKirs Please review

File: dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/NetUtils.java [hunk 1]
```diff
@@ -44,6 +44,7 @@
  */
 public class NetUtils {
 
+    private static final Pattern MASTER_WORKER_STS_PATTERN = Pattern.compile("(master|worker)-\\d+$");
```
Comment (CalvinKirs) [inline dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/NetUtils.java]: to judge by MASTER_WORKER_STS_PATTERN, does not seem to be a good method. NetUtils don't recommend has business mean.

Comment (chengshiwen) [reply dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/NetUtils.java]: I have removed `(master|worker)` and renamed `MASTER_WORKER_STS_PATTERN` to `STS_PATTERN`.

@chenxingchun  tested on minikube in the pod named `dolphinscheduler-worker-0`, and found that the `getHost()` returned `dolphinscheduler-worker-0` which would cause network connection refused, while the correct one should be `dolphinscheduler-worker-0.dolphinscheduler-worker-headless`. So I just gave the changes and the constant `MASTER_WORKER_STS_PATTERN` was really not very good.

**Comment by xingchun-chen** [comment]
+1

**Review by CalvinKirs — APPROVED** [review]
LGTM.
BTW, The test may need to provide a different k8s environment.

**Comment by chengshiwen** [comment]
> LGTM.
> BTW, The test may need to provide a different k8s environment.

I will see if there is a CI solution for testing k8s on GitHub
