### PR TITLE
[bug][plugin]Fix: Correct the way to determine the yarn queue in Flink CommandLine and SQL mode

### LINKED ISSUE #14236: [Bug] [Flink] Yarn queue conf doesn't work in flink command line.
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

The Yarn CommandLine always commits tasks to the default queue, even if the tenant YARN queue is specified.

### What you expected to happen

Task should be committed to the tenant YARN queue.

### How to reproduce

Run a non-sql Flink job >=1.12 with specific tenant YARN queue.

### Anything else

_No response_

### Version

3.1.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by ORuteMa**
## Purpose of the pull request
Correct the way to determine the yarn queue in Flink CommandLine.

closed #14236

## Brief change log

In Flink command line with -t option, Yarn queue should be determined by -Dyarn.application.name=%s rather than -yqu.

## Verify this pull request

This pull request is code cleanup without any test coverage. I test it manually.
image

### CODE REVIEW

**Comment by zhongjiajie** [comment]
run ci

File: dolphinscheduler-task-plugin/dolphinscheduler-task-flink/src/main/java/org/apache/dolphinscheduler/plugin/task/flink/FlinkArgsUtils.java [hunk 1]
```diff
@@ -254,13 +279,6 @@ private static List<String> buildRunCommandLineForOthers(TaskExecutionContext ta
                     args.add(taskManagerMemory);
                 }
 
-                if (StringUtils.isEmpty(others) || !others.contains(FlinkConstants.FLINK_QUEUE)) {
-                    String queue = flinkParameters.getQueue();
-                    if (StringUtils.isNotEmpty(queue)) { // -yqu
-                        args.add(FlinkConstants.FLINK_QUEUE);
-                        args.add(queue);
-                    }
-                }
```
Comment (Radeity) [inline dolphinscheduler-task-plugin/dolphinscheduler-task-flink/src/main/java/org/apache/dolphinscheduler/plugin/task/flink/FlinkArgsUtils.java:263]: I think you should add if-else statement here to set different arg name for yarn queue according to Flink version. Please remove judgement from L195-L244, in which just build run command.

**Review by Radeity — CHANGES_REQUESTED** [review]

File: dolphinscheduler-task-plugin/dolphinscheduler-task-flink/src/main/java/org/apache/dolphinscheduler/plugin/task/flink/FlinkArgsUtils.java (hunk 1 above)
Comment (ORuteMa) [reply dolphinscheduler-task-plugin/dolphinscheduler-task-flink/src/main/java/org/apache/dolphinscheduler/plugin/task/flink/FlinkArgsUtils.java:263]: ok

Comment (ORuteMa) [reply dolphinscheduler-task-plugin/dolphinscheduler-task-flink/src/main/java/org/apache/dolphinscheduler/plugin/task/flink/FlinkArgsUtils.java:263]: > I think you should add if-else statement here to set different arg name for yarn queue according to Flink version. Please remove judgement from L195-L244, in which just build run command.

done, and fix the same wrong in sql mode, pls have a look

File: dolphinscheduler-task-plugin/dolphinscheduler-task-flink/src/main/java/org/apache/dolphinscheduler/plugin/task/flink/FlinkArgsUtils.java [hunk 2]
```diff
@@ -197,16 +196,19 @@ private static List<String> buildRunCommandLineForOthers(TaskExecutionContext ta
                     args.add(FlinkConstants.FLINK_RUN); // run
                     args.add(FlinkConstants.FLINK_EXECUTION_TARGET); // -t
                     args.add(FlinkConstants.FLINK_YARN_PER_JOB); // yarn-per-job
+
```
Comment (Radeity) [inline dolphinscheduler-task-plugin/dolphinscheduler-task-flink/src/main/java/org/apache/dolphinscheduler/plugin/task/flink/FlinkArgsUtils.java]: Please remove redundant blank line.

File: dolphinscheduler-task-plugin/dolphinscheduler-task-flink/src/main/java/org/apache/dolphinscheduler/plugin/task/flink/FlinkArgsUtils.java [hunk 3]
```diff
@@ -197,16 +196,19 @@ private static List<String> buildRunCommandLineForOthers(TaskExecutionContext ta
...
                 } else {
                     args.add(FlinkConstants.FLINK_RUN); // run
                     args.add(FlinkConstants.FLINK_RUN_MODE); // -m
                     args.add(FlinkConstants.FLINK_YARN_CLUSTER); // yarn-cluster
+
```
Comment (Radeity) [inline dolphinscheduler-task-plugin/dolphinscheduler-task-flink/src/main/java/org/apache/dolphinscheduler/plugin/task/flink/FlinkArgsUtils.java]: Ditto.

File: dolphinscheduler-task-plugin/dolphinscheduler-task-flink/src/main/java/org/apache/dolphinscheduler/plugin/task/flink/FlinkArgsUtils.java [hunk 4]
```diff
@@ -197,16 +196,19 @@ private static List<String> buildRunCommandLineForOthers(TaskExecutionContext ta
...
                 }
                 break;
             case APPLICATION:
                 args.add(FlinkConstants.FLINK_RUN_APPLICATION); // run-application
                 args.add(FlinkConstants.FLINK_EXECUTION_TARGET); // -t
                 args.add(FlinkConstants.FLINK_YARN_APPLICATION); // yarn-application
+
```
Comment (Radeity) [inline dolphinscheduler-task-plugin/dolphinscheduler-task-flink/src/main/java/org/apache/dolphinscheduler/plugin/task/flink/FlinkArgsUtils.java]: Ditto.

File: dolphinscheduler-task-plugin/dolphinscheduler-task-flink/src/main/java/org/apache/dolphinscheduler/plugin/task/flink/FlinkArgsUtils.java [hunk 5]
```diff
@@ -164,12 +164,9 @@ public static List<String> buildInitOptionsForSql(FlinkParameters flinkParameter
...
 
             // yarn.application.queue
-            String others = flinkParameters.getOthers();
-            if (StringUtils.isEmpty(others) || !others.contains(FlinkConstants.FLINK_QUEUE)) {
-                String queue = flinkParameters.getQueue();
-                if (StringUtils.isNotEmpty(queue)) {
-                    initOptions.add(String.format(FlinkConstants.FLINK_FORMAT_YARN_APPLICATION_QUEUE, queue));
-                }
+            String queue = flinkParameters.getQueue();
+            if (StringUtils.isNotEmpty(queue)) {
```
Comment (Radeity) [inline dolphinscheduler-task-plugin/dolphinscheduler-task-flink/src/main/java/org/apache/dolphinscheduler/plugin/task/flink/FlinkArgsUtils.java:168]: We will check whether user defines this arg by themselves in `others`, so you just have to modify condition in the original way: `!others.contains(FlinkConstants. FLINK_QUEUE_FOR_TARGETS)`, btw, may I ask why you name them `FLINK_QUEUE_FOR_MODE` and `FLINK_QUEUE_FOR_TARGETS `?

File: dolphinscheduler-task-plugin/dolphinscheduler-task-flink/src/main/java/org/apache/dolphinscheduler/plugin/task/flink/FlinkArgsUtils.java [hunk 6]
```diff
@@ -306,6 +299,41 @@ private static List<String> buildRunCommandLineForOthers(TaskExecutionContext ta
...
+                        }
+                    }
+                }
+            case APPLICATION:
+                if (StringUtils.isEmpty(others) || !others.contains(FlinkConstants.FLINK_QUEUE_FOR_TARGETS)) {
+                    String queue = flinkParameters.getQueue();
+                    if (StringUtils.isNotEmpty(queue)) { // -Dyarn.application.queue=%s
+                        args.add(String.format(FlinkConstants.FLINK_QUEUE_FOR_TARGETS, queue));
+                    }
+                }
```
Comment (Radeity) [inline dolphinscheduler-task-plugin/dolphinscheduler-task-flink/src/main/java/org/apache/dolphinscheduler/plugin/task/flink/FlinkArgsUtils.java]: There are some duplicated code. Can we clean up the logic and try to avoid introducing this new method?

File: dolphinscheduler-task-plugin/dolphinscheduler-task-flink/src/main/java/org/apache/dolphinscheduler/plugin/task/flink/FlinkArgsUtils.java (hunk 5 above)
Comment (ORuteMa) [reply dolphinscheduler-task-plugin/dolphinscheduler-task-flink/src/main/java/org/apache/dolphinscheduler/plugin/task/flink/FlinkArgsUtils.java:168]: The YARN queue should be assigned by property `yarn.application.queue` rather than -yqu option, this option is not available in sql-client.sh.  If we want to specify the YARN queue used by a specific Flink SQL task, it would be more appropriate to have an explicit queue option in the task submission form rather than relying on parameters in the 'others' section. Regarding the naming here, it is because in flink-run, the -yqu option only takes effect within the -m option (for mode). When using the -t option (for target), it is necessary to specify it using -Dyarn.application.queue=%s.

File: dolphinscheduler-task-plugin/dolphinscheduler-task-flink/src/main/java/org/apache/dolphinscheduler/plugin/task/flink/FlinkArgsUtils.java (hunk 6 above)
Comment (ORuteMa) [reply dolphinscheduler-task-plugin/dolphinscheduler-task-flink/src/main/java/org/apache/dolphinscheduler/plugin/task/flink/FlinkArgsUtils.java]: Sure

File: dolphinscheduler-task-plugin/dolphinscheduler-task-flink/src/main/java/org/apache/dolphinscheduler/plugin/task/flink/FlinkArgsUtils.java (hunk 5 above)
Comment (Radeity) [reply dolphinscheduler-task-plugin/dolphinscheduler-task-flink/src/main/java/org/apache/dolphinscheduler/plugin/task/flink/FlinkArgsUtils.java:168]: It seems that we don't have any option for setting yarn queue, `flinkParameters.queue` will be assigned by `taskExecutionContext.queue`, which pass from `processInstance`, however, it's never be assigned.

Comment (ORuteMa) [reply dolphinscheduler-task-plugin/dolphinscheduler-task-flink/src/main/java/org/apache/dolphinscheduler/plugin/task/flink/FlinkArgsUtils.java:168]: The execution of a workflow is tied to a specific tenant, and this tenant holds a queue attribute. This attribute is assigned to the processInstance being executed by the tenant. The queue attribute of the executionContext for any taskInstance belonging to this processInstance will also be consistent. Therefore, the queue of a task is ultimately determined by the queue attribute of the runtime tenant if not explicitly specified.

Comment (Radeity) [reply dolphinscheduler-task-plugin/dolphinscheduler-task-flink/src/main/java/org/apache/dolphinscheduler/plugin/task/flink/FlinkArgsUtils.java:168]: It seems that this logic is missing, I've debugged and find the queue of `processInstance` is null. Also in codes, I don't find where it's assigned by tenant's queue. Would like to help check in your local env?

Comment (ORuteMa) [reply dolphinscheduler-task-plugin/dolphinscheduler-task-flink/src/main/java/org/apache/dolphinscheduler/plugin/task/flink/FlinkArgsUtils.java:168]: Sure. From my practice, the queue is assigned. This logic should be correctly implemented in the current version.

Comment (Radeity) [reply dolphinscheduler-task-plugin/dolphinscheduler-task-flink/src/main/java/org/apache/dolphinscheduler/plugin/task/flink/FlinkArgsUtils.java:168]: It's weird, do you test on branch dev?

Comment (ORuteMa) [reply dolphinscheduler-task-plugin/dolphinscheduler-task-flink/src/main/java/org/apache/dolphinscheduler/plugin/task/flink/FlinkArgsUtils.java:168]: My dolphin env is 3.1.7

Comment (Radeity) [reply dolphinscheduler-task-plugin/dolphinscheduler-task-flink/src/main/java/org/apache/dolphinscheduler/plugin/task/flink/FlinkArgsUtils.java:168]: Have you tested the modification in this PR on branch dev?

Comment (ORuteMa) [reply dolphinscheduler-task-plugin/dolphinscheduler-task-flink/src/main/java/org/apache/dolphinscheduler/plugin/task/flink/FlinkArgsUtils.java:168]: I will test it tomorrow, in my env I cp this pr to my 3.1.7.

**Comment by Radeity** [comment]
Hi, @ORuteMa , any feedback?

**Comment by ORuteMa** [comment]
> Hi, @ORuteMa , any feedback?

Sorry I am busy these days, I will test it later.

**Comment by ORuteMa** [comment]
@caishunfeng @zhongjiajie  pls approve run ci, thanks.

**Comment by SbloodyS** [comment]
> @caishunfeng @zhongjiajie pls approve run ci, thanks.

Done.

**Comment by ORuteMa** [comment]
> > @caishunfeng @zhongjiajie pls approve run ci, thanks.
> 
> Done.

I see some fail in this run, it may have no business to do with my pr. Is it a network problem or something else? Pls have a look.

**Comment by zhongjiajie** [comment]
restarted the failed E2E test

**Review by zhongjiajie — APPROVED** [review]
LGTM, overall do you have addition suggestion? @Radeity

**Review by Radeity — APPROVED** [review]
+1

**Review by SbloodyS — APPROVED** [review]
+1
