### PR TITLE
[fix][plugin]: fix spark sql use custom parma.

### LINKED ISSUE #10820: [Bug] [plugin] spark sql causes npe when parameters are used, and parameters never work.
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

image

image

CustomParams is missing type and direct.
when you use param，the master will npe because property.getDirect() is null.

image

But even if you fix the above problem, custom parameters still won't work because parameters are not replaced.

### What you expected to happen

spark sql can use custom params.

### How to reproduce

create a spark task, choose sql and add custom param.

### Anything else

none.

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by huangchenguang123**
fix #10820

### CODE REVIEW

**Comment by huangchenguang123** [comment]
PTAL

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java [hunk 1]
```diff
@@ -1300,6 +1301,10 @@ public void getPreVarPool(TaskInstance taskInstance, Set<String> preTask) {
             }
             if (allProperty.size() > 0) {
                 taskInstance.setVarPool(JSONUtils.toJsonString(allProperty.values()));
+                Map<String, Object> taskParams = JSONUtils.parseObject(taskInstance.getTaskParams(), new TypeReference<Map<String, Object>>() {
+                });
+                taskParams.put("varPool", JSONUtils.toJsonString(allProperty.values()));
```
Comment (caishunfeng) [inline dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java]: TaskParams and VarPool is different fields, so you can't add varpool into taskParams.

**Review by caishunfeng — CHANGES_REQUESTED** [review]

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java (hunk 1 above)
Comment (huangchenguang123) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java]: org.apache.dolphinscheduler.service.expand.CuringGlobalParams#paramParsingPreparation use taskInstance.varParams to build prepareParamsMap, and prepareParamsMap  was used to replace sql param.But taskInstance.varParams is always null, so I put it.This is why I did it, maybe you have a better idea？

Comment (caishunfeng) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java]: I think this is a unified process for all task, so after you fix the spark ui, the custome params can pass to worker.
BTW, the custome params for the current task is localParams.
This is a shell task example, hope it can help you. 
image

Comment (caishunfeng) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java]: BTW, I found the flink task also has the same issue in ui.

Comment (huangchenguang123) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java]: localParams is currently useful, but this is limited to [in] parameters, but for upstream [out] parameters, spark sql currently doesn't work, which is why I use varPool.

Comment (caishunfeng) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java]: Now ds just support three task types for parameter transfer, see https://dolphinscheduler.apache.org/en-us/docs/dev/user_doc/guide/parameter/context.html
So it's a feature, not a bug, you would better to create another feature issue to do it. WDYT?

Comment (huangchenguang123) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java]: I will create a feature, but do I need to resubmit a mr about parameter transfer?

**Comment by huangchenguang123** [comment]
PTAL @caishunfeng 
I had roll back some code

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java (hunk 1 above)
Comment (caishunfeng) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java]: > I will create a feature, but do I need to resubmit a mr about parameter transfer?

You can submit other pr to the feature issue if you are interested in.

**Review by caishunfeng — APPROVED** [review]
+1

**Comment by zhongjiajie** [comment]
this pr do not cherry pick, but we already add other PR to fix it

**Comment by huangchenguang123** [comment]
> this pr do not cherry pick, but we already add other PR to fix it

Thanks, I'm looking forward to seeing it in release.
