### PR TITLE
[Fix-9717] The failure policy of the task flow takes effect

### LINKED ISSUE #9717: [Bug-RD] When a task flow has multiple nodes and the failure policy is failure to continue, the policy is invalid
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When a task flow has multiple nodes and the failure policy is failure to continue, the policy is invalid

### What you expected to happen

When you set the failure policy to continue, you can continue execution to complete the entire workflow

### How to reproduce

Add a task flow.
Create multiple nodes and child nodes.
Failure Strategy Selection: Continue.
Start execution.

### Anything else

No Response

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by WangJPLeo**
## Purpose of the pull request

The failure policy of the task flow takes effect

## Brief change log

close #9717 
When the current node fails, check whether there is a child node, and continue execution if it exists and the failure strategy is continue.

## Verify this pull request

Manually verified the change by testing locally.

### CODE REVIEW

File: dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/utils/DagHelper.java [hunk 1]
```diff
@@ -565,20 +554,40 @@ public static boolean haveConditionsAfterNode(String parentNodeCode, List<TaskNo
...
         for (String nodeName : subsequentNodes) {
             TaskNode taskNode = dag.getNode(nodeName);
             List<String> preTaskList = JSONUtils.toList(taskNode.getPreTasks(),String.class);
-            if (preTaskList.contains(parentNodeCode) && taskNode.isBlockingTask()) {
-                return true;
+            boolean contains = preTaskList.contains(parentNodeCode);
+            if (typeCheck){
+                return contains && taskNode.getType().equalsIgnoreCase(checkType);
+            } else {
+                return contains;
```
Comment (ruanwenjun) [inline dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/utils/DagHelper.java]: The logic is not a match to the method name.

**Review by ruanwenjun — CHANGES_REQUESTED** [review]

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteThread.java [hunk 2]
```diff
@@ -456,9 +456,9 @@ private void taskFinished(TaskInstance taskInstance) {
             retryTaskInstance(taskInstance);
         } else if (taskInstance.getState().typeIsFailure()) {
             completeTaskMap.put(taskInstance.getTaskCode(), taskInstance.getId());
-            if (taskInstance.isConditionsTask()
```
Comment (caishunfeng) [inline dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteThread.java:459]: Is it OK if remove the task type check?

File: dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/utils/DagHelper.java [hunk 3]
```diff
@@ -565,20 +554,40 @@ public static boolean haveConditionsAfterNode(String parentNodeCode, List<TaskNo
...
      */
     public static boolean haveBlockingAfterNode(String parentNodeCode,
                                                 DAG<String,TaskNode,TaskNodeRelation> dag) {
+        return haveSubAfterNode(parentNodeCode, dag, true, TaskConstants.TASK_TYPE_BLOCKING);
+    }
+
+    /**
+     * is there have all node after the parent node
+     */
+    public static boolean haveAllNodeAfterNode(String parentNodeCode,
```
Comment (ruanwenjun) [inline dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/utils/DagHelper.java:570]: Do you want to mean have any node?

Comment (WangJPLeo) [reply dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/utils/DagHelper.java:570]: A node with child nodes in the process. The conditions for submitting child nodes when the current node fails are: there are child nodes and the failure strategy is continue. @ruanwenjun

File: dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/utils/DagHelper.java (hunk 1 above)
Comment (WangJPLeo) [reply dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/utils/DagHelper.java]: ok, i will fix it.

File: dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/utils/DagHelper.java (hunk 3 above)
Comment (ruanwenjun) [reply dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/utils/DagHelper.java:570]: @WangJPLeo I mean that it better to rename this method name to `haveAnyNodeAfterNode`, since I find you just want to check if there exist any node after the parentNodeCode.

Comment (WangJPLeo) [reply dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/utils/DagHelper.java:570]: ok thanks, i see what you mean.

File: dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/utils/DagHelper.java [hunk 4]
```diff
@@ -565,20 +554,40 @@ public static boolean haveConditionsAfterNode(String parentNodeCode, List<TaskNo
...
-            if (preTaskList.contains(parentNodeCode) && taskNode.isBlockingTask()) {
-                return true;
+            boolean containsParentNodeCode = preTaskList.contains(parentNodeCode);
+            if (additionalNodeTypeFiltering){
+                return containsParentNodeCode && taskNode.getType().equalsIgnoreCase(filterNodeType);
+            } else {
+                return containsParentNodeCode;
             }
         }
         return false;
```
Comment (ruanwenjun) [inline dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/utils/DagHelper.java]: The logic is wrong in your change. In my knowledge, this method is used to check if there exist any subNode(filter by type) of the given parentNode.
See the below case, the input is `parentNodeA` and `Type2 `, the return result might be false, but the expect result is true.
image

BTY, the parameter `additionalNodeTypeFiltering` `filterNodeType` is duplicate, you can just hold `filterNodeType` is enough.

**Review by ruanwenjun — CHANGES_REQUESTED** [review]

File: dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/utils/DagHelper.java (hunk 4 above)
Comment (WangJPLeo) [reply dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/utils/DagHelper.java]: Yes, an error may occur in the case of multiple child nodes, a revision has been committed.

**Review by ruanwenjun — APPROVED** [review]
LGTM

**Review by caishunfeng — APPROVED** [review]
LGTM
