### PR TITLE
[Fix] Fix the line.separator problem for alert-plugin' test case #10277

### LINKED ISSUE #10277: [Bug] [DolphinScheduler-alert-email] Running unit test testGetMessageFromTemplate() fails
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

I can pass this test case on linux, but there is a problem on windows. Through debug, it is found that there is a problem with the newline character of the string generated by the `generateMockTableTypeResultByHand()` method. This method does not consider platform independence and uses `LF` hard-coded as a newline

### What you expected to happen

`generateMockTableTypeResultByHand()` generates platform-independent strings that pass the test case

### How to reproduce

OS : windows 10
JDK : JDK 8
Run `mvn clean test -e` in command line window

### Anything else

Bug info 
`
[INFO] Running org.apache.dolphinscheduler.plugin.alert.email.template.DefaultHTMLTemplateTest
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.004 s <<< FAILURE! - in org.apache.dolphinscheduler.plugin.alert.email.template.DefaultHTMLTemplateTest
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.004 s <<< FAILURE! - in org.apache.dolphinscheduler.plugin.alert.email.template.DefaultHTMLTemplateTest
testGetMessageFromTemplate(org.apache.dolphinscheduler.plugin.alert.email.template.DefaultHTMLTemplateTest)  Time elapsed: 0.004 s  <<< FAILURE!

org.junit.ComparisonFailure: 
]
<tr><td>mysql200</t...> but was:<...er</th></tr></thead>[]
<tr><td>mysql200</t...>
	at org.apache.dolphinscheduler.plugin.alert.email.template.DefaultHTMLTemplateTest.testGetMessageFromTemplate(DefaultHTMLTemplateTest.java:44)
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
Failures: 

]
<tr><td>mysql200</t...> but was:<...er</th></tr></thead>[]
<tr><td>mysql200</t...>
[INFO] 
[ERROR] Tests run: 10, Failures: 1, Errors: 0, Skipped: 0
Tests run: 10, Failures: 1, Errors: 0, Skipped: 0

[INFO] 

`

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by 106umao**
## Purpose of the pull request

Fix the line.separator problem for alert-plugin' test case close #10277

## Brief change log

Modified the line separator

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

### CODE REVIEW

File: dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-email/src/main/java/org/apache/dolphinscheduler/plugin/alert/email/EmailConstants.java [hunk 1]
```diff
@@ -18,6 +18,8 @@
 package org.apache.dolphinscheduler.plugin.alert.email;
 
 public final class EmailConstants {
+    public static final String LINE_SEPARATOR = System.getProperty("line.separator");
```
Comment (kezhenxu94) [inline dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-email/src/main/java/org/apache/dolphinscheduler/plugin/alert/email/EmailConstants.java]: I don't think there is necessity to add a constant, just use `System.lineSeparator()`

Comment (106umao) [reply dolphinscheduler-alert/dolphinscheduler-alert-plugins/dolphinscheduler-alert-email/src/main/java/org/apache/dolphinscheduler/plugin/alert/email/EmailConstants.java:21]: > 

ok ,fine

**Review by kezhenxu94 — APPROVED** [review]

**Review by SbloodyS — APPROVED** [review]
+1
