### PR TITLE
[BUG-6543][Master] process instance state is always running when failure task

### LINKED ISSUE #6543: [Bug] [Master] process instance state is always running when failure task exists
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

process instance state is always running when failure task exists.
the failure task setting: retry times: 1, retry interval: 1 minute

### What you expected to happen

the process instance state is failed when failed task exists.

### How to reproduce

process instance state is always running when failure task exists.
the failure task setting: retry times: 1, retry interval: 1 minute

### Anything else

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by lenboo**
close #6543 process instance state is always running when failure task exists

### CODE REVIEW

File: dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteThread.java [hunk 1]
```diff
@@ -650,18 +662,20 @@ private void notifyProcessHostUpdate(TaskInstance taskInstance) {
...
                 taskInstance.getTaskCode(),
                 taskInstance.getTaskDefinitionVersion()
         );
         taskInstance.setTaskDefine(taskDefinition);
-        if (TimeoutFlag.OPEN == taskDefinition.getTimeoutFlag()) {
-            this.taskTimeoutCheckList.put(taskInstance.getId(), taskInstance);
-            return;
-        }
-        if (taskInstance.isDependTask() || taskInstance.isSubProcess()) {
+        if (TimeoutFlag.OPEN == taskDefinition.getTimeoutFlag() || taskInstance.taskCanRetry()) {
```
Comment (caishunfeng) [inline dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteThread.java:673]: maybe the conditions is &&

**Review by brave-lee — APPROVED** [review]
+1

**Review by CalvinKirs — APPROVED** [review]
