### PR TITLE
[fix-10938]: use dot to replace source and make the default env work in shell

### LINKED ISSUE #10938: [Question] [3.0.0-beta-2] /tmp/dolphinscheduler/exec/process.command: /bin/spark-submit: not found
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

I hava deployed ds by docker-compose and mount the spark-client on localhost，when I submit a spark-task(the example task of sparkPi), the error below happends: 
[INFO] 2022-07-13 08:30:49.424 +0000 [taskAppId=TASK-20220713-6178360895936_1-48-48] TaskLogLogger-class org.apache.dolphinscheduler.plugin.task.spark.SparkTask:[63] -  -> /tmp/dolphinscheduler/exec/process/6169061703072/6178360895936_1/48/48/48_48.command: 4: /tmp/dolphinscheduler/exec/process/6169061703072/6178360895936_1/48/48/48_48.command: source: not found
	/tmp/dolphinscheduler/exec/process/6169061703072/6178360895936_1/48/48/48_48.command: 5: /tmp/dolphinscheduler/exec/process/6169061703072/6178360895936_1/48/48/48_48.command: /bin/spark-submit: not found

### What you expected to happen

the task can run successfully

### How to reproduce

1、deployed dolphinscheduler by docker-compose
2、mount the directory /opt/soft on localhost

### Anything else

_No response_

### Version

3.0.0-beta-2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by itzhang89**
## Purpose of the pull request

fix #10938

## Brief change log

use the .  to replace the source command. this two command not have any different. and the . is  Shell Builtins.

## Verify this pull request

This pull request is code cleanup without any test coverage.

### CODE REVIEW

File: dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/ShellCommandExecutor.java [hunk 1]
```diff
@@ -108,7 +108,7 @@ protected void createCommandFileIfNotExists(String execCommand, String commandFi
                     sb.append(taskRequest.getEnvironmentConfig()).append("\n");
                 } else {
                     if (taskRequest.getEnvFile() != null) {
-                        sb.append("source ").append(taskRequest.getEnvFile()).append("\n");
+                        sb.append(". ").append(taskRequest.getEnvFile()).append("\n");
```
Comment (ruanwenjun) [inline dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/ShellCommandExecutor.java]: I would like to use `#!/bin/bash` to replace `#!/bin/sh`, rather than use `.` to replace `source`

Comment (SbloodyS) [reply dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/ShellCommandExecutor.java]: > I would like to use `#!/bin/bash` to replace `#!/bin/sh`, rather than use `.` to replace `source`

+1

Comment (itzhang89) [reply dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/ShellCommandExecutor.java]: no problem

**Comment by EricGao888** [comment]
@yutianaiqingtian Could you please fix the title of this PR? Thanks.

**Comment by itzhang89** [comment]
> @yutianaiqingtian Could you please fix the title of this PR? Thanks.

@EricGao888  Sorry. I'm not understand what your meaning? What's the title of you want?

**Comment by EricGao888** [comment]
> > @yutianaiqingtian Could you please fix the title of this PR? Thanks.
> 
> @EricGao888 Sorry. I'm not understand what your meaning? What's the title of you want?

@yutianaiqingtian I've fixed it. Part of the previous title seemed missing. 
image

File: dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/ShellCommandExecutor.java (hunk 1 above)
Comment (SbloodyS) [reply dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/ShellCommandExecutor.java]: Hi @yutianaiqingtian , We would like to release it in version 3.0.1. Could you submit this ASAP since we are ready to release version 3.0.1.

**Review by SbloodyS — APPROVED** [review]
LGTM

**Comment by black-06** [comment]
Unlucky, this problem was recurred in 3.1.0  :(
