### PR TITLE
[Fix-7493] Support searching for task node in the DAG.

### LINKED ISSUE #7493: [Feature][UI]Fuzzy search and case-insensitive search should be supported in process definition details page
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

1、click a process and enter   the  process definition details page
eg:http://XXXXX:12345/dolphinscheduler/ui/#/projects/3880463913664/definition/list/3880470637248
2、search node with the search button in the upper right corner of the page 
3、Enter a partial name or enter it regardless of case ,and click search button
[expect]
1、search node successful
[actual]
 1、The corresponding node is not found

### Use case

Fuzzy search and case-insensitive search should be supported。
This is useful when there are many nodes

### Related issues

_No response_

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by calvinjiang**
## Purpose of the pull request

This PR will close #7493 .

## Brief change log
The former input component was replaced by a select component that can be able to support fuzzy search.

## Verify this pull request
This change added tests and can be verified as follows:
  - *Manually verified the change by testing locally.* 
 
Fuzzy searching for a task node:
image

image

### CODE REVIEW

File: dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/canvas/toolbar.vue [hunk 1]
```diff
@@ -74,16 +74,14 @@
...
-          v-model="searchText"
-          placeholder=""
-          prefix-icon="el-icon-search"
-          size="mini"
-          @keyup.enter.native="onSearch"
-          clearable
-          @blur="searchInputBlur"
-          ref="searchInput"
-        ></el-input>
+        <el-select v-if="searchInputVisible" ref="searchInput" v-model="searchText" size="mini" clearable prefix-icon="el-icon-search" @change="onSearch" @keyup.enter.native="onSearch" filterable placeholder="请选择">
```
Comment (zhuangchong) [inline dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/canvas/toolbar.vue]: Please use internationalization

**Review by zhuangchong — APPROVED** [review]
+1
