### PR TITLE
[fix-#11753] send alert error alert data id

### LINKED ISSUE #11753: [Bug] [Alert Server] send alert error alert data id
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

when I want to test Email send when a task finish  , I get a error :

[INFO] 2022-09-02 08:00:11.268 +0000 org.apache.dolphinscheduler.alert.AlertRequestProcessor:[52] - Received command : AlertSendRequestCommand{groupId=0, title='sql_hive query result sets', content='[{"_c0":36816}]', warnType=1}
[ERROR] 2022-09-02 08:00:11.270 +0000 org.apache.dolphinscheduler.alert.AlertSenderService:[148] - Alert GroupId 0 send error : not found alert instance
[ERROR] 2022-09-02 08:00:14.699 +0000 org.apache.dolphinscheduler.alert.AlertSenderService:[244] - send alert error alert data id :57,
java.lang.NullPointerException: User must not be null
        at java.util.Objects.requireNonNull(Objects.java:228)
        at org.apache.dolphinscheduler.plugin.alert.email.MailSender.<init>(MailSender.java:109)
        at org.apache.dolphinscheduler.plugin.alert.email.EmailAlertChannel.process(EmailAlertChannel.java:41)
        at org.apache.dolphinscheduler.alert.AlertSenderService.alertResultHandler(AlertSenderService.java:232)
        at org.apache.dolphinscheduler.alert.AlertSenderService.send(AlertSenderService.java:105)
        at org.apache.dolphinscheduler.alert.AlertSenderService.run(AlertSenderService.java:76)
[INFO] 2022-09-02 08:00:14.699 +0000 org.apache.dolphinscheduler.alert.AlertSenderService:[255] - Alert Plugin Email-Alert send error : User must not be null

### What you expected to happen

I should got a Email when a task finish 

### How to reproduce

create a Email group  ,  smtp   then I create a test task ,  run It  with a Email group ,then will get the same error 

### Anything else

dolphin 3.0 pseudo-cluster  install 

### Version

3.0.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by fuchanghai**
## Purpose of the pull request

 send alert error alert data id

## Brief change log

ATT
## Verify this pull request

This pull request is code cleanup without any test coverage.

this close #11753

### CODE REVIEW

**Review by SbloodyS — COMMENTED** [review]
Please associate issue.

**Comment by fuchanghai** [comment]
> Please associate issue.

done

**Comment by fuchanghai** [comment]
@SbloodyS @caishunfeng  @Amy0104  if  the value of warningGroupId  is null. which effect to front end,or  backend?

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/ExecutorController.java [hunk 1]
```diff
@@ -137,7 +137,7 @@ public Result startProcessInstance(@ApiIgnore @RequestAttribute(value = Constant
                                        @RequestParam(value = "taskDependType", required = false) TaskDependType taskDependType,
                                        @RequestParam(value = "execType", required = false) CommandType execType,
                                        @RequestParam(value = "warningType") WarningType warningType,
-                                       @RequestParam(value = "warningGroupId", required = false, defaultValue = "0") Integer warningGroupId,
+                                       @RequestParam(value = "warningGroupId", required = false) Integer warningGroupId,
```
Comment (stalary) [inline dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/ExecutorController.java:142]: `batch-start-process-instance` also need to modify.

**Review by stalary — CHANGES_REQUESTED** [review]

**Comment by stalary** [comment]
use-modal.ts looks like need to modify.

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/ExecutorController.java (hunk 1 above)
Comment (fuchanghai) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/ExecutorController.java:142]: i agree with u

**Comment by fuchanghai** [comment]
> use-modal.ts



> use-modal.ts looks like need to modify.

the value of warningGroupId that come from front end  is null

File: dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/alert/ProcessAlertManager.java [hunk 2]
```diff
@@ -217,13 +216,7 @@ public void sendAlertWorkerToleranceFault(ProcessInstance processInstance, List<
     public void sendAlertProcessInstance(ProcessInstance processInstance,
                                          List<TaskInstance> taskInstances,
                                          ProjectUser projectUser) {
-
-        if (!isNeedToSendWarning(processInstance)) {
```
Comment (caishunfeng) [inline dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/alert/ProcessAlertManager.java:221]: Why remove this check?

File: dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/AlertDao.java [hunk 3]
```diff
@@ -81,9 +89,15 @@ public class AlertDao {
      * @return add alert result
      */
     public int addAlert(Alert alert) {
+        if (null == alert.getAlertGroupId() || NumberUtils.INTEGER_ZERO.equals(alert.getAlertGroupId())) {
+            return 0;
```
Comment (caishunfeng) [inline dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/AlertDao.java:97]: It's better to add warn log

File: dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/alert/ProcessAlertManager.java (hunk 2 above)
Comment (fuchanghai) [reply dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/alert/ProcessAlertManager.java:221]: Because it has been judged before calling the method sendAlertProcessInstance

File: dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/AlertDao.java (hunk 3 above)
Comment (fuchanghai) [reply dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/AlertDao.java:97]: i agree with u

File: dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/AlertDao.java [hunk 4]
```diff
@@ -81,9 +89,16 @@ public class AlertDao {
      * @return add alert result
      */
     public int addAlert(Alert alert) {
+        if (null == alert.getAlertGroupId() || NumberUtils.INTEGER_ZERO.equals(alert.getAlertGroupId())) {
```
Comment (ruanwenjun) [inline dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/AlertDao.java:95]: Why use `NumberUtils.INTEGER_ZERO` rather than `0 ==alert.getAlertGroupId()` here?

File: dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/alert/ProcessAlertManager.java (hunk 2 above)
Comment (ruanwenjun) [reply dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/alert/ProcessAlertManager.java:221]: It's better don't remove this, since this method mighe be execute by another where, you can remove this check in `WorkflowExecuteRunnable`

File: dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/alert/ProcessAlertManager.java [hunk 5]
```diff
@@ -238,7 +231,6 @@ public void sendAlertProcessInstance(ProcessInstance processInstance,
         alert.setAlertType(processInstance.getState().isSuccess() ? AlertType.PROCESS_INSTANCE_SUCCESS
                 : AlertType.PROCESS_INSTANCE_FAILURE);
         alertDao.addAlert(alert);
-        logger.info("add alert to db , alert: {}", alert);
```
Comment (ruanwenjun) [inline dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/alert/ProcessAlertManager.java:241]: Please don't remove this kind of log, you can change the log level to debug.

Comment (fuchanghai) [reply dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/alert/ProcessAlertManager.java:241]: i remove the log to the method of AlertDao#addAlert

**Comment by fuchanghai** [comment]
@caishunfeng @stalary @SbloodyS @ruanwenjun  PTAL

File: dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/AlertDao.java (hunk 4 above)
Comment (fuchanghai) [reply dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/AlertDao.java:95]: because I want to reduce to use magic value

File: dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/alert/ProcessAlertManager.java (hunk 2 above)
Comment (fuchanghai) [reply dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/alert/ProcessAlertManager.java:221]: done

**Review by caishunfeng — APPROVED** [review]
LGTM
