### PR TITLE
[Fix][UI] Fix data-quality component multi-language support.

### LINKED ISSUE #10138: [Bug] [workflows] Data_quality workflows in Chinese mode are not translated into Chinese
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

image

### What you expected to happen

In Chinese mode, it should be displayed as a Chinese

### How to reproduce

None.

### Anything else

None.

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by songjianet**
## Purpose of the pull request
close [#10138](https://github.com/apache/dolphinscheduler/issues/10138)
image
image

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

### CODE REVIEW

File: dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-rules.ts [hunk 1]
```diff
@@ -67,9 +67,10 @@ export function useRules(
     if (ruleLoading.value) return
     ruleLoading.value = true
     const result = await getRuleFormCreateJson(ruleId)
-    const items = JSON.parse(result).map((item: IResponseJsonItem) =>
-      formatResponseJson(item)
-    )
+    const items = JSON.parse(result).map((item: IResponseJsonItem) => {
+      item.props.placeholder = t('project.node.' + item.props.placeholder.split(' ').join('_').split(',').join('').toLowerCase())
+      return formatResponseJson(item)
+    })
```
Comment (Amy0104) [inline dolphinscheduler-ui/src/views/projects/task/components/node/fields/use-rules.ts]: It's better to handle the placeholder format in the formatResponseJson function as well.

**Review by Amy0104 — APPROVED** [review]
LGTM.
