### PR TITLE
[Fix-17817][Master] Add workflow timeout event and handle

### LINKED ISSUE #17817: [Bug] [Master] Missing workflow timeout alerts
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Image

Configured workflow timeout alerts are not actually effective.

### What you expected to happen

Send workflow timeout alarm.

### How to reproduce

--

### Anything else

--

### Version

dev

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by njnu-seafish**
## Was this PR generated or assisted by AI?
NO

## Purpose of the pull request

close #17817

This bug involves a critical feature and has been stagnant for several months. Since I actually resolved the task timeout and workflow timeout issue quite some time ago, I would like to finalize the process and get it closed.
image

## Brief change log

Add workflow timeout event and handle

## Verify this pull request

add IT case

## Pull Request Notice
[Pull Request Notice](https://github.com/apache/dolphinscheduler/blob/dev/docs/docs/en/contribute/join/pull-request.md)

If your pull request contains incompatible change, you should also add it to `docs/docs/en/guide/upgrade/incompatible.md`

### CODE REVIEW

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/workflow/lifecycle/event/WorkflowTimeoutLifecycleEvent.java [hunk 1]
```diff
@@ -0,0 +1,69 @@
...
+    }
+
+    public static WorkflowTimeoutLifecycleEvent of(IWorkflowExecutionRunnable workflowExecutionRunnable) {
+        final WorkflowInstance workflowInstance = workflowExecutionRunnable.getWorkflowInstance();
+        checkState(workflowInstance != null, "The workflow instance must be initialized before retrying.");
+
+        final int timeout = workflowInstance.getTimeout();
+        checkState(timeout > 0, "The workflow timeout: %s must > 0 minutes", timeout);
+
+        long delayTime = System.currentTimeMillis() - workflowInstance.getStartTime().getTime()
```
Comment (ruanwenjun) [inline dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/workflow/lifecycle/event/WorkflowTimeoutLifecycleEvent.java]: When the workflow instance is rerun the startTime will not change. You should use `restartTime` .

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/workflow/lifecycle/handler/WorkflowStartLifecycleEventHandler.java [hunk 2]
```diff
@@ -38,11 +40,24 @@ public void handle(final IWorkflowStateAction workflowStateAction,
...
 
     @Override
     public ILifecycleEventType matchEventType() {
         return WorkflowLifecycleEventType.START;
     }
+
+    private void workflowTimeoutMonitor(final IWorkflowExecutionRunnable workflowExecutionRunnable) {
+        final WorkflowInstance workflowInstance = workflowExecutionRunnable.getWorkflowInstance();
+        if (workflowInstance.getTimeout() <= 0) {
+            log.debug("The workflow {} timeout {} is invalided, so the timeout monitor will not be started.",
```
Comment (ruanwenjun) [inline dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/workflow/lifecycle/handler/WorkflowStartLifecycleEventHandler.java]: The log is incorrect.

**Review by ruanwenjun — COMMENTED** [review]
Please review your PR first, too many of these comments have been raised repeatedly in previous PRs.

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/workflow/lifecycle/WorkflowLifecycleEventType.java [hunk 3]
```diff
@@ -25,34 +25,47 @@ public enum WorkflowLifecycleEventType implements ILifecycleEventType {
...
+    /**
+     * Do Timeout strategy of the workflow instance.
+     */
+    TIMEOUT,
+
     /**
      * Pause the workflow instance
      */
     PAUSE,
+
```
Comment (ruanwenjun) [inline dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/workflow/lifecycle/WorkflowLifecycleEventType.java]: Please don't change the unrelated code.

**Review by ruanwenjun — COMMENTED** [review]
You should add IT case.

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/workflow/lifecycle/handler/WorkflowStartLifecycleEventHandler.java (hunk 2 above)
[the remark this answers is not in the document]
Comment (njnu-seafish) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/workflow/lifecycle/handler/WorkflowStartLifecycleEventHandler.java]: okok

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/workflow/lifecycle/event/WorkflowTimeoutLifecycleEvent.java [hunk 4]
```diff
@@ -0,0 +1,69 @@
...
+
+    protected WorkflowTimeoutLifecycleEvent(final IWorkflowExecutionRunnable workflowExecutionRunnable,
+                                            final long timeout) {
+        super(timeout);
+        this.workflowExecutionRunnable = workflowExecutionRunnable;
+    }
+
+    public static WorkflowTimeoutLifecycleEvent of(IWorkflowExecutionRunnable workflowExecutionRunnable) {
+        final WorkflowInstance workflowInstance = workflowExecutionRunnable.getWorkflowInstance();
+        checkState(workflowInstance != null, "The workflow instance must be initialized before retrying.");
```
[the remark this answers is not in the document]
Comment (njnu-seafish) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/workflow/lifecycle/event/WorkflowTimeoutLifecycleEvent.java]: ok

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/workflow/lifecycle/event/WorkflowTimeoutLifecycleEvent.java (hunk 1 above)
Comment (njnu-seafish) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/workflow/lifecycle/event/WorkflowTimeoutLifecycleEvent.java]: > When the workflow instance is rerun the startTime will not change. You should use `restartTime` .

good

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/workflow/lifecycle/handler/WorkflowStartLifecycleEventHandler.java (hunk 2 above)
Comment (njnu-seafish) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/workflow/lifecycle/handler/WorkflowStartLifecycleEventHandler.java]: > The log is incorrect.

fix it

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/workflow/lifecycle/WorkflowLifecycleEventType.java (hunk 3 above)
Comment (njnu-seafish) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/workflow/lifecycle/WorkflowLifecycleEventType.java]: > Please don't change the unrelated code.

ok

**Comment by njnu-seafish** [comment]
> You should add IT case.

added

File: dolphinscheduler-master/src/test/resources/it/start/workflow_with_workflow_timeout_alert.yaml [hunk 5]
```diff
@@ -0,0 +1,63 @@
...
+taskRelations:
+  - projectCode: 1
+    workflowDefinitionCode: 1
+    workflowDefinitionVersion: 1
+    preTaskCode: 0
+    preTaskVersion: 0
+    postTaskCode: 1
+    postTaskVersion: 1
+    createTime: 2024-08-12 00:00:00
+    updateTime: 2024-08-12 00:00:00
```
Comment (SbloodyS) [inline dolphinscheduler-master/src/test/resources/it/start/workflow_with_workflow_timeout_alert.yaml]:
```suggestion
    updateTime: 2024-08-12 00:00:00
    
```

We should leave an blank line at the end of each file.

Comment (njnu-seafish) [reply dolphinscheduler-master/src/test/resources/it/start/workflow_with_workflow_timeout_alert.yaml]: > We should leave an blank line at the end of each file.

ok

File: dolphinscheduler-master/src/test/java/org/apache/dolphinscheduler/server/master/integration/WorkflowOperator.java [hunk 6]
```diff
@@ -67,6 +68,7 @@ public Integer manualTriggerWorkflow(final WorkflowTriggerDTO workflowTriggerDTO
                 .dryRun(workflowTriggerDTO.getDryRun())
                 .taskDependType(workflowTriggerDTO.getTaskDependType())
                 .failureStrategy(workflowTriggerDTO.getFailureStrategy())
+                .warningGroupId(workflowTriggerDTO.getWarningGroupId())
```
[the remark this answers is not in the document]
Comment (njnu-seafish) [reply dolphinscheduler-master/src/test/java/org/apache/dolphinscheduler/server/master/integration/WorkflowOperator.java:71]: ok

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/workflow/lifecycle/event/WorkflowTimeoutLifecycleEvent.java [hunk 7]
```diff
@@ -0,0 +1,70 @@
...
+    public static WorkflowTimeoutLifecycleEvent of(IWorkflowExecutionRunnable workflowExecutionRunnable) {
+        final WorkflowInstance workflowInstance = workflowExecutionRunnable.getWorkflowInstance();
+        checkState(workflowInstance != null,
+                "The workflow instance must be initialized before creating workflow timeout event.");
+
+        final int timeout = workflowInstance.getTimeout();
+        checkState(timeout > 0, "The workflow timeout: %s must > 0 minutes", timeout);
+
+        long delayTime = System.currentTimeMillis() - workflowInstance.getRestartTime().getTime()
+                + TimeUnit.MINUTES.toMillis(timeout);
```
[the remark this answers is not in the document]
Comment (njnu-seafish) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/workflow/lifecycle/event/WorkflowTimeoutLifecycleEvent.java:55]: no need, restartTime is not null

**Comment by njnu-seafish** [comment]
@ruanwenjun @SbloodyS  Whenever you have time, I’d be grateful for your review. Thanks so much!

File: dolphinscheduler-master/src/test/java/org/apache/dolphinscheduler/server/master/integration/cases/WorkflowStartTestCase.java [hunk 8]
```diff
@@ -1778,4 +1779,45 @@ public void testTaskRemainsSubmittedSuccess_with_noAvailableWorkerAndTimeoutDisa
         // masterContainer.assertAllResourceReleased();
     }
 
+    @Test
+    @DisplayName("Test start a workflow when timeout should trigger alert when warningGroupId is set")
+    public void testWorkflowTimeout_WithAlertGroup_ShouldSendAlert() {
+        final String yaml = "/it/start/workflow_with_workflow_timeout_alert.yaml";
+        final WorkflowTestCaseContext context = workflowTestCaseContextFactory.initializeContextFromYaml(yaml);
```
[the remark this answers is not in the document]
Comment (njnu-seafish) [reply dolphinscheduler-master/src/test/java/org/apache/dolphinscheduler/server/master/integration/cases/WorkflowStartTestCase.java:1786]: > The PR description says this change has no test coverage, but this commit adds a new master integration test for workflow-timeout alerts. Please update the PR description/verify section to reflect the added coverage (or remove the statement about having no tests) so reviewers and release notes stay accurate.

ok

**Comment by njnu-seafish** [comment]
@ruanwenjun @SbloodyS Whenever you have time, I’d be grateful for your review. Thanks so much!

**Review by SbloodyS — APPROVED** [review]
LGTM

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/workflow/lifecycle/handler/WorkflowTimeoutLifecycleEventHandler.java [hunk 9]
```diff
@@ -0,0 +1,76 @@
...
+
+    @Override
+    public void handle(final IWorkflowStateAction workflowStateAction,
+                       final IWorkflowExecutionRunnable workflowExecutionRunnable,
+                       final WorkflowTimeoutLifecycleEvent workflowTimeoutLifecycleEvent) {
+        final IWorkflowExecutionGraph workflowExecutionGraph = workflowExecutionRunnable.getWorkflowExecutionGraph();
+        if (workflowExecutionGraph.isAllTaskExecutionRunnableChainFinish()) {
+            // all the TaskExecutionRunnable chain in the graph is finish, means the workflow is already finished.
+            return;
+        }
```
Comment (ruanwenjun) [inline dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/workflow/lifecycle/handler/WorkflowTimeoutLifecycleEventHandler.java:53]: Don't need to check here?

**Review by ruanwenjun — APPROVED** [review]
