### PR TITLE
[Fix-9593] Storage Management StorageOperate No Instance

### LINKED ISSUE #9593: [BUG-BD] Files from the Resource Center are not working properly in the workflow
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

In the Resource Center's File Manager, create a shell file. The shell node is then created in the workflow to recall the created file and run it to failure.

### What you expected to happen

Files from the Resource Center can be used normally in the workflow.

### How to reproduce

1. create a shell file in the file manage.
2. create a shell task in the workflow.
3. the resource in the task configuration selects the created shell file.

### Anything else

No Response

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by WangJPLeo**
## Purpose of the pull request

Instantiate StorageOperate in TaskExecuteProcessor class.

## Brief change log

close #9593 
Add StorageOperateManager and Instantiate StorageOperate in TaskExecuteProcessor class.

## Verify this pull request

Manually verified the change by testing locally.

### CODE REVIEW

File: dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/storage/StorageOperateManager.java [hunk 1]
```diff
@@ -0,0 +1,36 @@
+package org.apache.dolphinscheduler.common.storage;
```
Comment (caishunfeng) [inline dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/storage/StorageOperateManager.java:17]: license header

**Review by caishunfeng — APPROVED** [review]
LGTM

File: dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/processor/TaskExecuteProcessor.java [hunk 2]
```diff
@@ -161,7 +163,7 @@ public void process(Channel channel, Command command) {
         }
 
         // submit task to manager
-        boolean offer = workerManager.offer(new TaskExecuteThread(taskExecutionContext, taskCallbackService, alertClientService, taskPluginManager));
+        boolean offer = workerManager.offer(new TaskExecuteThread(taskExecutionContext, taskCallbackService, alertClientService, taskPluginManager, StorageOperateManager.getStorageOperate(ResUploadType.HDFS)));
```
Comment (zhongjiajie) [inline dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/processor/TaskExecuteProcessor.java:166]: I think we support both `HDFS` and `S3` resources, but in this case, we use HDFS default and without the `S3` type. Should we support `S3` too?

Comment (WangJPLeo) [reply dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/processor/TaskExecuteProcessor.java:166]: Yes, the currently created resources do not have a clear file storage mark to which they belong. After confirming with the test, the current default is HDFS. I think this can be optimized in the future. @zhongjiajie

Comment (zhongjiajie) [reply dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/processor/TaskExecuteProcessor.java:166]: we should add an issue to connect this ASAP
