### PR TITLE
[Fix-17173] [JVM Metrics] Fix JVM memory monitoring metrics

### LINKED ISSUE #17173: [Bug] [JVM Metrics] Incorrect Memory Usage Calculation Causes False Master Overload Detection
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

In the DefaultMetricsProvider of DolphinScheduler, there is a logical error in obtaining the JVM memory usage, which causes the Master service to be misjudged as an overload state, thereby preventing the submission of all scheduled tasks.
**Problem phenomenon**
All dispatch tasks cannot be submitted
Master log report Overload error
Actual system metrics and memory snapshot analysis are normal
**Cause of the problem**
The current code gets a single measurement directly from jvm.memory.used and jvm.memory.max without considering that these metrics have multiple tag dimensions
Causes the possibility of incorrect comparison of values ​​of different memory areas (for example, using the used value of Eden Space to the max value of Code Cache, jvmMemoryUsedPercentage is over 1)
From the provided metric data, we can see that JVM memory metrics have multiple dimensions:
area: heap/nonheap
id: Specific memory area name

Image

### What you expected to happen

Master startup parameters：-Xms4g -Xmx4g -Xmn2g

**JVM-related indicators**
jvm_memory_used_bytes{application="master-server",area="nonheap",id="Compressed Class Space",} 1.1395192E7
jvm_memory_used_bytes{application="master-server",area="nonheap",id="Code Cache",} 7.443136E7
jvm_memory_used_bytes{application="master-server",area="heap",id="PS Eden Space",} 1.758794104E9
jvm_memory_used_bytes{application="master-server",area="heap",id="PS Survivor Space",} 1951136.0
jvm_memory_used_bytes{application="master-server",area="nonheap",id="Metaspace",} 9.8894144E7
jvm_memory_used_bytes{application="master-server",area="heap",id="PS Old Gen",} 7.4584848E7

jvm_memory_max_bytes{application="master-server",area="nonheap",id="Compressed Class Space",} 1.073741824E9
jvm_memory_max_bytes{application="master-server",area="nonheap",id="Code Cache",} 2.5165824E8
jvm_memory_max_bytes{application="master-server",area="heap",id="PS Eden Space",} 2.142240768E9
jvm_memory_max_bytes{application="master-server",area="heap",id="PS Survivor Space",} 2621440.0
jvm_memory_max_bytes{application="master-server",area="nonheap",id="Metaspace",} -1.0
jvm_memory_max_bytes{application="master-server",area="heap",id="PS Old Gen",} 2.147483648E9

**Related Code**
@Component
public class DefaultMetricsProvider implements MetricsProvider {

    @Autowired
    private MeterRegistry meterRegistry;

    private SystemMetrics systemMetrics;

    private long lastRefreshTime = 0;

    private static final long SYSTEM_METRICS_REFRESH_INTERVAL = 1_000L;

    @Override
    public SystemMetrics getSystemMetrics() {
        if (System.currentTimeMillis() - lastRefreshTime < SYSTEM_METRICS_REFRESH_INTERVAL) {
            return systemMetrics;
        }

        double systemCpuUsage = meterRegistry.get("system.cpu.usage").gauge().value();
        double processCpuUsage = meterRegistry.get("process.cpu.usage").gauge().value();

        double jvmMemoryUsed = meterRegistry.get("jvm.memory.used").meter().measure().iterator().next().getValue();
        double jvmMemoryMax = meterRegistry.get("jvm.memory.max").meter().measure().iterator().next().getValue();

        long totalSystemMemory = OSUtils.getTotalSystemMemory();
        long systemMemoryAvailable = OSUtils.getSystemAvailableMemoryUsed();

        systemMetrics = SystemMetrics.builder()
                .systemCpuUsagePercentage(systemCpuUsage)
                .processCpuUsagePercentage(processCpuUsage)
                .totalCpuUsedPercentage(systemCpuUsage + processCpuUsage)
                .jvmMemoryUsed(jvmMemoryUsed)
                .jvmMemoryMax(jvmMemoryMax)
                .jvmMemoryUsedPercentage(jvmMemoryUsed / jvmMemoryMax)
                .systemMemoryUsed(totalSystemMemory - systemMemoryAvailable)
                .systemMemoryMax(totalSystemMemory)
                .systemMemoryUsedPercentage((double) (totalSystemMemory - systemMemoryAvailable) / totalSystemMemory)
                .diskUsedPercentage(OSUtils.getDiskUsedPercentage())
                .build();
        lastRefreshTime = System.currentTimeMillis();
        return systemMetrics;
    }

}
In the Micrometer source code,  a single JVM metric in the `JvmMemoryMetrics` class may have multiple tags.
Image

### How to reproduce

To modify the metrics to obtain logic, it should:
The original indicator fields jvmMemoryUsed and jvmMemoryMax are replaced with sum(alltags)
Summarize jvm.memory.used and jvm.memory.max according to the same label dimension
Added 4 new indicators: jvmHeapUsed, jvmNonHeapUsed, jvmHeapMax, jvmNonHeapMax

### Anything else

_No response_

### Version

3.2.x

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by dill21yu**
## Purpose of the pull request

close #17173 

## Brief change log

In the BaseHeartBeat model, add fields for JVM heap memory and non-heap memory usage and maximum values. Modify MasterHeartBeatTask and WorkerHeartBeatTask to collect and report these metrics. Update DefaultMetricsProvider to accurately calculate and provide JVM heap and non-heap memory usage and maximum values. Add corresponding fields in SystemMetrics to store these metrics.

## Verify this pull request

This pull request is already covered by existing tests, such as MasterServerLoadProtectionTest、WorkerServerLoadProtectionTest.

## Pull Request Notice
[Pull Request Notice](https://github.com/apache/dolphinscheduler/blob/dev/docs/docs/en/contribute/join/pull-request.md)

If your pull request contains incompatible change, you should also add it to `docs/docs/en/guide/upgrade/incompatible.md`

### CODE REVIEW

File: dolphinscheduler-meter/src/main/java/org/apache/dolphinscheduler/meter/metrics/DefaultMetricsProvider.java [hunk 1]
```diff
@@ -59,8 +60,19 @@ public SystemMetrics getSystemMetrics() {
...
+
+        double jvmHeapMax = calculateTotalMemory(meterRegistry, "heap", "jvm.memory.max");
+        double jvmNonHeapMax = calculateTotalMemory(meterRegistry, "nonheap", "jvm.memory.max");
+
+        // Calculate totals
+        double jvmMemoryUsed = jvmHeapUsed + jvmNonHeapUsed;
+        double jvmMemoryMax = jvmHeapMax + jvmNonHeapMax;
+
+        // Ensure jvmMemoryMax is not zero
+        double jvmMemoryUsedPercentage = (jvmMemoryMax > 0) ? (jvmMemoryUsed / jvmMemoryMax) : 0.0;
```
Comment (SbloodyS) [inline dolphinscheduler-meter/src/main/java/org/apache/dolphinscheduler/meter/metrics/DefaultMetricsProvider.java:75]: Under what circumstances will `jvmMemoryMax` be less than 0?

Comment (dill21yu) [reply dolphinscheduler-meter/src/main/java/org/apache/dolphinscheduler/meter/metrics/DefaultMetricsProvider.java:75]: The initial value of jvmMemoryMax is 0. It accumulates the maximum memory values and should not be 0 under normal circumstances. However, the Sonar scan reports an issue to avoid a potential division by zero error:"Make sure "jvmMemoryMax" can't be zero before doing this division."

Comment (dill21yu) [reply dolphinscheduler-meter/src/main/java/org/apache/dolphinscheduler/meter/metrics/DefaultMetricsProvider.java:75]: image

Comment (SbloodyS) [reply dolphinscheduler-meter/src/main/java/org/apache/dolphinscheduler/meter/metrics/DefaultMetricsProvider.java:75]: I see. Thanks for clarification.

**Review by SbloodyS — APPROVED** [review]
LGTM.

**Comment by dill21yu** [comment]
Please help review the code @ruanwenjun @Gallardot @EricGao888 @caishunfeng

**Review by ruanwenjun — APPROVED** [review]
LGTM
