### PR TITLE
[Fix-8337] [Master] Process instance can not be kill when task is failure and can be retry

### LINKED ISSUE #8337: [Bug] [Master] Process instance can not be kill when task is failure and can be retry
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Process instance can not be kill when task is failure and can be retry

### What you expected to happen

stop successfully.

### How to reproduce

1.Create a process instance and a shell script that contains content ```exit 1``` and retry times is 3.
2.Running process instance.
3.Kill process instance while process instance in retry delay time.

### Anything else

_No response_

### Version

2.0.3

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by SbloodyS**
## Purpose of the pull request

fix #8337

### CODE REVIEW

**Review by caishunfeng — COMMENTED** [review]
LGTM

File: dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/runner/StateWheelExecuteThread.java [hunk 1]
```diff
@@ -134,6 +134,14 @@ private void checkTask4Retry() {
         }
 
         for (TaskInstance taskInstance : this.taskInstanceRetryCheckList.values()) {
+            ProcessInstance processInstance = processService.findProcessInstanceById(taskInstance.getProcessInstanceId());
+
+            if (processInstance.getState() == ExecutionStatus.READY_STOP) {
```
Comment (lenboo) [inline dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/runner/StateWheelExecuteThread.java]: This 'READY_STOP' state will be sent to master from API, so is it necessary to query from the database again？

**Review by lenboo — APPROVED** [review]
+1
