### PR TITLE
[Fix-9352][datasource-api]data source client uses a cache with an expiration time

### LINKED ISSUE #9352: [Bug] [datasource-api] Hive datasource connection failed when kerberos renew ticket lifetime expire
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

in krb5.conf file, 
>>>
ticket_lifetime = 24h
renew_lifetime = 7d
>>> 
when after renew lifetime expired,  connecting to the hive data source failed ,because the cached hive data source client uses the old ticket ,it cannot get the new ticket

error log
```
[WARN] 2022-04-01 16:59:53.260 org.apache.hive.jdbc.HiveConnection:[237] - Failed to connect to **.**.**.**:****
[ERROR] 2022-04-01 16:59:56.127 org.apache.thrift.transport.TSaslTransport:[315] - SASL negotiation failure
javax.security.sasl.SaslException: GSS initiate failed
        at com.sun.security.sasl.gsskerb.GssKrb5Client.evaluateChallenge(GssKrb5Client.java:211)
        at org.apache.thrift.transport.TSaslClientTransport.handleSaslStartMessage(TSaslClientTransport.java:94)
        at org.apache.thrift.transport.TSaslTransport.open(TSaslTransport.java:271)
        at org.apache.thrift.transport.TSaslClientTransport.open(TSaslClientTransport.java:37)
        at org.apache.hadoop.hive.metastore.security.TUGIAssumingTransport$1.run(TUGIAssumingTransport.java:51)
        at org.apache.hadoop.hive.metastore.security.TUGIAssumingTransport$1.run(TUGIAssumingTransport.java:48)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1698)
        at org.apache.hadoop.hive.metastore.security.TUGIAssumingTransport.open(TUGIAssumingTransport.java:48)
        at org.apache.hive.jdbc.HiveConnection.openTransport(HiveConnection.java:343)
        at org.apache.hive.jdbc.HiveConnection.<init>(HiveConnection.java:228)
        at org.apache.hive.jdbc.HiveDriver.connect(HiveDriver.java:107)
        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364)
        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476)
        at com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71)
        at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:726)
        at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:712)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.ietf.jgss.GSSException: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)
        at sun.security.jgss.krb5.Krb5InitCredential.getInstance(Krb5InitCredential.java:162)
        at sun.security.jgss.krb5.Krb5MechFactory.getCredentialElement(Krb5MechFactory.java:122)
        at sun.security.jgss.krb5.Krb5MechFactory.getMechanismContext(Krb5MechFactory.java:189)
        at sun.security.jgss.GSSManagerImpl.getMechanismContext(GSSManagerImpl.java:224)
        at sun.security.jgss.GSSContextImpl.initSecContext(GSSContextImpl.java:212)
        at sun.security.jgss.GSSContextImpl.initSecContext(GSSContextImpl.java:179)
        at com.sun.security.sasl.gsskerb.GssKrb5Client.evaluateChallenge(GssKrb5Client.java:192)
        ... 23 common frames omitted
```

### What you expected to happen

I think the data source client cache should have an expiration time, for example, use the Guava Cache instead of CurrentHashMap.

### How to reproduce

1. in krb5.conf file, change config renew life to short time, e.g 1h, then restart KDC
2. restart api  server
3. check hive connection, now it's a success
4. after renew life expired, check hive connection, now it's a failed

### Anything else

_No response_

### Version

2.0.5

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by zhuxt2015**
## Purpose of the pull request
This pull request add a cache with an expiration time for all data source client 

close #9352

## Brief change log
use Guava Cache for data source client  instead of  ConcurrentHashMap

## Verify this pull request

This pull request is already covered by existing tests, DatasourceUtilTest.testCheckConnection

### CODE REVIEW

**Comment by lenboo** [comment]
close #9352

**Comment by davidzollo** [comment]
LGTM

File: dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-api/src/main/java/org/apache/dolphinscheduler/plugin/datasource/api/plugin/DataSourceClientProvider.java [hunk 1]
```diff
@@ -55,14 +63,20 @@ public Connection getConnection(DbType dbType, ConnectionParam connectionParam)
...
+                Map<String, DataSourceChannel> dataSourceChannelMap = dataSourcePluginManager.getDataSourceChannelMap();
+                DataSourceChannel dataSourceChannel = dataSourceChannelMap.get(dbType.getDescp());
+                if (null == dataSourceChannel) {
+                    throw new RuntimeException(String.format("datasource plugin '%s' is not found", dbType.getDescp()));
+                }
+                return dataSourceChannel.createDataSourceClient(baseConnectionParam, dbType);
+            });
+        } catch (ExecutionException e) {
+            logger.error("create {} datasource client error.", dbType.getDescp(), e);
+            return null;
```
Comment (zhongjiajie) [inline dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-api/src/main/java/org/apache/dolphinscheduler/plugin/datasource/api/plugin/DataSourceClientProvider.java]: Should we directly throw an exception instead of return null?

File: dolphinscheduler-spi/src/main/java/org/apache/dolphinscheduler/spi/utils/Constants.java [hunk 2]
```diff
@@ -144,6 +144,11 @@ private Constants() {
      */
     public static final String KERBEROS = "kerberos";
 
+    /**
+     * renew_lifetime in kerberos configuration
+     */
+    public static final String KERBEROS_RENEW_LIFETIME_HOURS = "kerberos.renew.lifetime.hours";
```
Comment (zhongjiajie) [inline dolphinscheduler-spi/src/main/java/org/apache/dolphinscheduler/spi/utils/Constants.java]: I can not find this config in our configuration file, should we also add it to configuration?

**Review by zhongjiajie — DISMISSED** [review]
LGTM, @caishunfeng do you have time to take a look at this PR?

File: dolphinscheduler-task-plugin/dolphinscheduler-task-datax/src/main/java/org/apache/dolphinscheduler/plugin/task/datax/DataxTask.java [hunk 3]
```diff
@@ -557,7 +558,7 @@ public String[] tryExecuteSqlResolveColumnNames(DbType sourceType, BaseConnectio
             for (int i = 1; i <= num; i++) {
                 columnNames[i - 1] = md.getColumnName(i);
             }
-        } catch (SQLException e) {
+        } catch (SQLException | ExecutionException e) {
             logger.warn(e.getMessage(), e);
```
Comment (caishunfeng) [inline dolphinscheduler-task-plugin/dolphinscheduler-task-datax/src/main/java/org/apache/dolphinscheduler/plugin/task/datax/DataxTask.java]:
```suggestion
            logger.error(e.getMessage(), e);
```

File: dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-api/src/main/java/org/apache/dolphinscheduler/plugin/datasource/api/plugin/DataSourceClientProvider.java [hunk 4]
```diff
@@ -17,24 +17,33 @@
...
 
-import org.slf4j.Logger;
-import org.slf4j.LoggerFactory;
 
 public class DataSourceClientProvider {
     private static final Logger logger = LoggerFactory.getLogger(DataSourceClientProvider.class);
 
-    private static final Map<String, DataSourceClient> uniqueId2dataSourceClientMap = new ConcurrentHashMap<>();
+    private static long duration = PropertyUtils.getLong(TaskConstants.KERBEROS_EXPIRE_TIME, 24);
+    private static final Cache<String, DataSourceClient> uniqueId2dataSourceClientCache = CacheBuilder.newBuilder()
```
Comment (caishunfeng) [inline dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-api/src/main/java/org/apache/dolphinscheduler/plugin/datasource/api/plugin/DataSourceClientProvider.java:43]: I think the cache can't completely solve the problem, when renew lifetime expired, the cache may not expire yet, and it will still fail at this time.
Can we add the ticket check before using? Or add retry logic when connect fail?  What do you think?

Comment (zhuxt2015) [reply dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-api/src/main/java/org/apache/dolphinscheduler/plugin/datasource/api/plugin/DataSourceClientProvider.java:43]: yes,  I think it's appropriate to add retry logic when connect failed, I will do it later

File: dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-api/src/main/java/org/apache/dolphinscheduler/plugin/datasource/api/plugin/DataSourceClientProvider.java [hunk 5]
```diff
@@ -50,20 +64,26 @@ public static DataSourceClientProvider getInstance() {
...
             Map<String, DataSourceChannel> dataSourceChannelMap = dataSourcePluginManager.getDataSourceChannelMap();
             DataSourceChannel dataSourceChannel = dataSourceChannelMap.get(dbType.getDescp());
             if (null == dataSourceChannel) {
                 throw new RuntimeException(String.format("datasource plugin '%s' is not found", dbType.getDescp()));
             }
             return dataSourceChannel.createDataSourceClient(baseConnectionParam, dbType);
         });
-        return dataSourceClient.getConnection();
+        Connection connection = dataSourceClient.getConnection();
+        if (null == connection && dbType.isHive() && isRetry && PropertyUtils.getBoolean(HADOOP_SECURITY_AUTHENTICATION_STARTUP_STATE, false)) {
```
Comment (caishunfeng) [inline dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-api/src/main/java/org/apache/dolphinscheduler/plugin/datasource/api/plugin/DataSourceClientProvider.java]: Can put this retry logic into `dataSourceClient.getConnection()`?  In this way, we no longer have to judge hive in the outer layer.  What do you think?

Comment (zhuxt2015) [reply dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-api/src/main/java/org/apache/dolphinscheduler/plugin/datasource/api/plugin/DataSourceClientProvider.java]: already put retry logic into dataSourceClient.getConnection()

**Review by caishunfeng — APPROVED** [review]
LGTM
