### PR TITLE
[Fix-17534][Service/Master] Add global parameters and varpool from current workflow instance and add them to start params list of the trigger request of a sub workflow

### LINKED ISSUE #17534: [Bug] [Service/Master] Global variables of sub-workflows not getting inherited by underlying sub-workflows
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

After the upgrade from 3.2.2 to 3.3.1, most of our workflows stopped working due to missing variables. This is due to global parameters from sub-workflows not being correctly set for use within their underlying sub-workflows.

### What you expected to happen

When setting a global parameter in a sub-workflow, it's values should be propagated to all underlying sub-workflows.

### How to reproduce

Create the following situation/workflow:
- Workflow A calls Workflow B as a sub-workflow
- Workflow B calls Workflow C as a sub-workflow
- Workflow B defines a global variable $VALUE
- Workflow C contains a shell script to print the $VALUE value
- If you start execution from Workflow A, Workflow C does not receive the global $VALUE from Workflow B and prints nothing

### Anything else

_No response_

### Version

3.3.1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by kvermeulen**
## Purpose of the pull request

Close [#17534](https://github.com/apache/dolphinscheduler/issues/17534)

## Brief change log

When triggering a sub workflow, lookup all global parameters from the current, and any parent workflow instances and pass them along in the start param list of the trigger request of the sub workflow

## Verify this pull request

This change added tests and can be verified as follows:
- *Added a new integration test for validating the fixed behaviour*
- *Manually verified the change by using the test-case mentioned in issue [#17534](https://github.com/apache/dolphinscheduler/issues/17534)*

## Pull Request Notice
[Pull Request Notice](https://github.com/apache/dolphinscheduler/blob/dev/docs/docs/en/contribute/join/pull-request.md)

This is my very first pull-request, so bear with me on this one. :-)

A colleague of mine opened the original issue. This PR fixes these erroneous workflows for us, but I'm not entirely sure if this is the correct approach taken. I'll try and follow-up to make sure this PR meets all coding conventions and fulfills all requirements. I'll do my best on taking the time on improving the implementation on any pointers/advice given, if the implementation in the PR is not entirely correct or does not cover all use-cases, but I can't make any promises there.

Thank you for reviewing.

### CODE REVIEW

**Comment by ruanwenjun** [comment]
3.3.1 has been closed, please submit PR to dev.

**Comment by kvermeulen** [comment]
I tried rebasing this one on dev. Is this sufficient, or should I create an entire new PR?

**Comment by ruanwenjun** [comment]
> I tried rebasing this one on dev. Is this sufficient, or should I create an entire new PR?

No need to create a new PR.

**Comment by kvermeulen** [comment]
Fixed the 3 issues detected by sonarqube

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/executor/plugin/subworkflow/SubWorkflowLogicTask.java [hunk 1]
```diff
@@ -234,7 +249,7 @@ private SubWorkflowLogicTaskRuntimeContext triggerNewSubWorkflow() {
                 .tenantCode(workflowInstance.getTenantCode())
                 .environmentCode(workflowInstance.getEnvironmentCode())
                 // todo: transport varpool and local params
-                .startParamList(commandParam.getCommandParams())
+                .startParamList(mergeParams(asList(commandParam.getCommandParams(), globalParamsOfParents)))
```
Comment (ruanwenjun) [inline dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/executor/plugin/subworkflow/SubWorkflowLogicTask.java]: We should merge the current workflow instance's command params, global params, varpool as the subworkflow instance's command param is enough, we don't need to find the parant global params here, since the parent global params should already exist in command params.

**Review by ruanwenjun — CHANGES_REQUESTED** [review]

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/executor/plugin/subworkflow/SubWorkflowLogicTask.java (hunk 1 above)
Comment (kvermeulen) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/executor/plugin/subworkflow/SubWorkflowLogicTask.java]: Sorry, I missed that indeed. Parent global params already exist in the command params. I'll update and remove the unnecessary code. Can you maybe verify if the order of merging the params is correct? Before I didn't include the varpool for instance.

I'll update my commit and force push on the PR. I don't know if this is best practice or if we'll loose trace of the previous change. However, I do like a code changes for a fix in a single commit. Makes it more concise maybe. But any advice here is also welcome.

**Comment by kvermeulen** [comment]
Updated and corrected the title of the PR after receiving some review remarks from @ruanwenjun, who pointed out that only the global parameters and varpool of the current workflow instance, need to be passed  when triggering a subflow. Global parameters from any parent workflow(s) will already be in the command params from the current workflow instance. (thanks for pointing out!)

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/executor/plugin/subworkflow/SubWorkflowLogicTask.java (hunk 1 above)
Comment (ruanwenjun) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/executor/plugin/subworkflow/SubWorkflowLogicTask.java]: When the code change submits a commit is better, the commit will be polished when PR merged by committer.

**Comment by kvermeulen** [comment]
Just to be sure, is there still any action needed from my side currently?

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/executor/plugin/subworkflow/SubWorkflowLogicTask.java [hunk 2]
```diff
@@ -222,6 +234,11 @@ private SubWorkflowLogicTaskRuntimeContext triggerNewSubWorkflow() {
         final ICommandParam commandParam =
                 JSONUtils.parseObject(workflowInstance.getCommandParam(), ICommandParam.class);
 
+        final List<Property> paramList = mergeParams(asList(
+                commandParam.getCommandParams(),
+                new ArrayList<>(deserializeVarPool(workflowInstance.getVarPool())),
+                new ArrayList<>(deserializeVarPool(workflowInstance.getGlobalParams()))));
```
Comment (ruanwenjun) [inline dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/executor/plugin/subworkflow/SubWorkflowLogicTask.java]: The varpool's priority should be highest.
```suggestion
                new ArrayList<>(deserializeVarPool(workflowInstance.getGlobalParams()))),
                commandParam.getCommandParams(),
                new ArrayList<>(deserializeVarPool(workflowInstance.getVarPool())));
```

Comment (kvermeulen) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/executor/plugin/subworkflow/SubWorkflowLogicTask.java]: Force pushed again because I committed a compile-time error. The varpool should have the highest priority now when merging parameters.

**Review by ruanwenjun — APPROVED** [review]
LGTM

**Review by SbloodyS — APPROVED** [review]
+1
