### PR TITLE
[Bug][dolphinscheduler-api]validated for duplicate username when creating or registering a user

### LINKED ISSUE #14576: [Bug] [dolphinscheduler-api] validated for duplicate username when creating or registering a user
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

The API calls to `createUser` and `registerUser` were not validated for duplicate username.

https://github.com/apache/dolphinscheduler/blob/c0d776381c20b42135e8f89ba335d7975da00522/dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/UsersController.java#L106-L117

https://github.com/apache/dolphinscheduler/blob/c0d776381c20b42135e8f89ba335d7975da00522/dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/UsersController.java#L565-L574

should refer to the `verifyUserName` for verification

https://github.com/apache/dolphinscheduler/blob/c0d776381c20b42135e8f89ba335d7975da00522/dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/UsersController.java#L494-L496

### What you expected to happen

validated for duplicate username when creating or registering a user.

### How to reproduce

This is verified by repeatedly calling the API with the same parameters.

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Gallardot**
- close #14576 

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

**Review by SbloodyS — COMMENTED** [review]
LGTM

**Review by SbloodyS — APPROVED** [review]

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/UsersServiceImpl.java [hunk 1]
```diff
@@ -1336,7 +1336,7 @@ public Map<String, Object> registerUser(String userName, String userPassword, St
             putMsg(result, Status.REQUEST_PARAMS_NOT_VALID_ERROR, "two passwords are not same");
             return result;
         }
-        User user = createUser(userName, userPassword, email, 1, "", "", Flag.NO.ordinal());
+        User user = createUser(userName, userPassword, email, -1, "", "", Flag.NO.ordinal());
```
Comment (Radeity) [inline dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/UsersServiceImpl.java:1339]: If we set -1, it will cause some possible NPE, like 
`String tenantCode = tenantMapper.queryById(loginUser.getTenantId()).getTenantCode();`
If you want to modify it, plz make sure to fix those NPE, either :D

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/UsersController.java [hunk 2]
```diff
@@ -111,6 +111,10 @@ public Result createUser(@Parameter(hidden = true) @RequestAttribute(value = Con
                              @RequestParam(value = "email") String email,
                              @RequestParam(value = "phone", required = false) String phone,
                              @RequestParam(value = "state", required = false) int state) throws Exception {
+        Result verifyRet = usersService.verifyUserName(userName);
+        if (verifyRet.getCode() != Status.SUCCESS.getCode()) {
+            return verifyRet;
+        }
```
Comment (Radeity) [inline dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/UsersController.java:117]: Can we also add this check in update api?

**Review by Radeity — CHANGES_REQUESTED** [review]

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/UsersController.java (hunk 2 above)
Comment (Gallardot) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/UsersController.java:117]: The update API already does this check.

https://github.com/apache/dolphinscheduler/blob/399d0d0ce9be29724988dcbd9a7dc5fbfab44de0/dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/UsersServiceImpl.java#L408-L432

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/UsersServiceImpl.java (hunk 1 above)
Comment (Gallardot) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/UsersServiceImpl.java:1339]: This risk is already dealt with by DML. By default, a tenant with an id of -1 is added. Instead, there is no tenant with id 1.  That's why I made this change.

https://github.com/apache/dolphinscheduler/blob/399d0d0ce9be29724988dcbd9a7dc5fbfab44de0/dolphinscheduler-dao/src/main/resources/sql/upgrade/3.2.0_schema/mysql/dolphinscheduler_dml.sql#L19-L31

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/UsersController.java (hunk 2 above)
Comment (Radeity) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/UsersController.java:117]: Get it.

**Review by Radeity — APPROVED** [review]

**Review by fuchanghai — APPROVED** [review]

**Review by rickchengx — APPROVED** [review]
