### PR TITLE
[Fix-7525][Feature][UI Next] Provide a common  layout for the module of dolphinscheduler-ui-next.

### LINKED ISSUE #7525: [DSIP-4][Feature][UI Next] Provide a basic layout.
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Need to provide a common layout for the module fo dolphinscheduler-ui-next. 

### Use case

Need to provide a common layout for the module fo dolphinscheduler-ui-next. 

### Related issues

#7332

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by calvinjiang**
## Purpose of the pull request

This PR will close #7525 .

## Brief change log
 Provide a common  layout for the module of dolphinscheduler-ui-next.

## Verify this pull request
This change added tests and can be verified as follows:
  - *Manually verified the change by testing locally.* 
  
image

### CODE REVIEW

File: dolphinscheduler-ui-next/src/layouts/basic/components/header/index.tsx [hunk 1]
```diff
@@ -0,0 +1,93 @@
...
+    },
+    currentMenu: {
+      type: Object
+    },
+    defaultMenuKey: {
+      type: String
+    }
+  },
+  setup(props, context) {
+    const currentMenu = ref({})
```
Comment (songjianet) [inline dolphinscheduler-ui-next/src/layouts/basic/components/header/index.tsx]: currentMenuRef

File: dolphinscheduler-ui-next/src/layouts/basic/components/sider/index.tsx [hunk 2]
```diff
@@ -0,0 +1,79 @@
...
+      type: Object
+    },
+    defaultMenuKey: {
+      type: String
+    }
+  },
+  setup(props) {
+    const currentMenu = ref({})
+
+    function handleMenuClick(key, data) {
```
Comment (songjianet) [inline dolphinscheduler-ui-next/src/layouts/basic/components/sider/index.tsx]: const handleMenuClick = (key, data) => {}

**Review by songjianet — CHANGES_REQUESTED** [review]

**Review by songjianet — APPROVED** [review]
LGTM

**Review by CalvinKirs — APPROVED** [review]
