### PR TITLE
[Fix-12832][API] Fix update worker group exception group name already exists.

### LINKED ISSUE #12832: [Bug] [api] cannot modify worker group
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

cannot modify worker group in worker group manage page. alert worker group already exists.

### What you expected to happen

can modify worker group

### How to reproduce

modify worker group  in worker group manage page.

### Anything else

_No response_

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by zhuangchong**
## Purpose of the pull request

this pr closes: #12832 

Fix update worker group exception group name already exists.

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

**Review by SbloodyS — DISMISSED** [review]
LGTM

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/WorkerGroupServiceImpl.java [hunk 1]
```diff
@@ -165,20 +161,21 @@ protected void handleDefaultWorkGroup(WorkerGroupMapper workerGroupMapper, Worke
...
-                }
+            // update group, the database exists with the same group name except itself
+            Optional<WorkerGroup> sameNameWorkGroupOptional = workerGroupList.stream()
+                    .filter(group -> !Objects.equals(group.getId(), workerGroup.getId())).findFirst();
+            if (sameNameWorkGroupOptional.isPresent()) {
+                return true;
             }
         }
-        // check zookeeper
+        // check registry server
```
Comment (ruanwenjun) [inline dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/WorkerGroupServiceImpl.java]: We don't need to check the worker group exist in registry, we have removed the worker group in registry path.

**Review by ruanwenjun — DISMISSED** [review]

**Review by ruanwenjun — APPROVED** [review]
