### PR TITLE
[Fix][UI Next][V1.0.0-Alpha] Fix the state column of task instance ta…

### LINKED ISSUE #8982: [Bug][UI Next][V1.0.0-Alpha] The state column of  task instance table displays error.
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

The state column of  task instance table displays error.

### What you expected to happen

Same as the old ui.

### How to reproduce

1. Open the task instance page.

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Amy0104**
## Purpose of the pull request

This pull request fixs the state column of task instance table displays error.

## Releated issues

close #8982

### CODE REVIEW

**Comment by songjianet** [comment]
image

File: dolphinscheduler-ui-next/src/views/projects/workflow/instance/use-table.ts [hunk 1]
```diff
@@ -95,45 +93,7 @@ export function useTable() {
...
         key: 'state',
         className: 'workflow-status',
-        render: (_row: IWorkflowInstance) => {
-          const stateIcon = taskStateIcon[_row.state]
-          const iconElement = h(
-            NIcon,
-            {
-              size: '18px',
-              style: 'position: relative; top: 7.5px; left: 7.5px',
-              class: stateIcon.classNames
```
Comment (SbloodyS) [inline dolphinscheduler-ui-next/src/views/projects/workflow/instance/use-table.ts:105]: The ```WorkflowE2ETest``` using class ```success``` to verify the process instance success state. Removing it would lead to the ```WorkflowE2ETest``` failed.

Comment (Amy0104) [reply dolphinscheduler-ui-next/src/views/projects/workflow/instance/use-table.ts:105]: I will add the class by the task type.Such as SUBMITTED_SUCCESS will be submitted_success expect FAILURE which corresponds to failed.

**Review by songjianet — APPROVED** [review]
LGTM
