### PR TITLE
[Fix-10785] Fix state event handle error will not retry

### LINKED ISSUE #10785: [Bug] [Master] State event handle error will not retry
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Right now, when we deal the state change event, we will not retry in some case, due to we catch the state handle error exception, and don't rethrow it.
e.g.
https://github.com/apache/dolphinscheduler/blob/7d79a2165ee5f0bf1aa7c949c852da179d6c0cc9/dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteRunnable.java#L700-L726
When we update the processInstance failed, we shouldn't catch the exception

And when we update the status to database, we need to recover the status in memory, when update to db failed.

### What you expected to happen

xx

### How to reproduce

When the database restart, the workflow status will incorrect.

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by ruanwenjun**
close #10785 

## Purpose of the pull request

Details see #10785 

## Brief change log
- Use StateEventHandleException, StateEventHandleError to distinguish if the exception can recover.
- Recover process instance status when update to database failed.
- Add state event handler to deal with the event, most of the logic is direactly copy form workflowExecuteRunnable

### CODE REVIEW

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/event/StateEventHandler.java [hunk 1]
```diff
@@ -0,0 +1,36 @@
...
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+package org.apache.dolphinscheduler.server.master.event;
+
+import org.apache.dolphinscheduler.common.enums.StateEventType;
+import org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteRunnable;
+
+public interface StateEventHandler {
```
Comment (caishunfeng) [inline dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/event/StateEventHandler.java:23]: :+1:

File: dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/processor/TaskExecuteResponseAckProcessor.java [hunk 2]
```diff
@@ -58,7 +58,15 @@ public void process(Channel channel, Command command) {
         if (taskExecuteResponseAckCommand.getStatus() == ExecutionStatus.SUCCESS.getCode()) {
             ResponseCache.get().removeResponseCache(taskExecuteResponseAckCommand.getTaskInstanceId());
             TaskCallbackService.remove(taskExecuteResponseAckCommand.getTaskInstanceId());
-            logger.debug("remove REMOTE_CHANNELS, task instance id:{}", taskExecuteResponseAckCommand.getTaskInstanceId());
+            if (logger.isDebugEnabled()) {
```
Comment (caishunfeng) [inline dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/processor/TaskExecuteResponseAckProcessor.java]: no need to judge here, when use `logger.debug`, it will check internally.

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/dispatch/executor/NettyExecutorManager.java [hunk 3]
```diff
@@ -116,7 +116,6 @@ public Boolean execute(ExecutionContext context) throws ExecuteException {
             try {
                 doExecute(host, command);
                 success = true;
-                context.setHost(host);
```
Comment (caishunfeng) [inline dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/dispatch/executor/NettyExecutorManager.java]: maybe it's needed

Comment (ruanwenjun) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/dispatch/executor/NettyExecutorManager.java]: Yes, this is needed, I will revert it.

File: dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/processor/TaskExecuteResponseAckProcessor.java (hunk 2 above)
Comment (ruanwenjun) [reply dolphinscheduler-worker/src/main/java/org/apache/dolphinscheduler/server/worker/processor/TaskExecuteResponseAckProcessor.java]: Yes, it will check internally, but this judge can help to speed up this judge, I will revert this.

**Review by caishunfeng — APPROVED** [review]
LGTM, good improvement :+1:
