### PR TITLE
[Fix-11007] [Master] fix forced_success bug

### LINKED ISSUE #11007: [Bug] [Master] Recovery failed and stuck after successful enforcement of failed tasks in sub workflow
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Recovery failed and stuck after successful enforcement of failed tasks in sub workflow

### What you expected to happen

Sub workflow succeeded

### How to reproduce

1. AA workflow have three tasks A, B and C.  A and B run successfully, while C fails
2. AA is a sub workflow of BB
3. Run BB.
4. Forced successfully C task
5. Execute on BB recovery Failed 

### Anything else

_No response_

### Version

2.0.5

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by brave-lee**
close #11007

### CODE REVIEW

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TaskInstanceServiceImpl.java [hunk 1]
```diff
@@ -194,6 +198,24 @@ public Map<String, Object> forceTaskSuccess(User loginUser, long projectCode, In
             return result;
         }
 
+        ProcessInstance processInstance = processService.findProcessInstanceDetailById(task.getProcessInstanceId());
```
Comment (caishunfeng) [inline dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TaskInstanceServiceImpl.java]: Please add some comment.

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TaskInstanceServiceImpl.java [hunk 2]
```diff
@@ -194,6 +198,24 @@ public Map<String, Object> forceTaskSuccess(User loginUser, long projectCode, In
...
+            List<Long> instanceTaskCodeList = validTaskList.stream().map(TaskInstance::getTaskCode).collect(Collectors.toList());
+            List<ProcessTaskRelation> taskRelations = processService.findRelationByCode(processInstance.getProcessDefinitionCode(),
+                processInstance.getProcessDefinitionVersion());
+            List<TaskDefinitionLog> taskDefinitionLogs = processService.genTaskDefineList(taskRelations);
+            List<Long> definiteTaskCodeList = taskDefinitionLogs.stream().filter(definitionLog -> definitionLog.getFlag() == Flag.YES)
+                .map(TaskDefinitionLog::getCode).collect(Collectors.toList());
+            if (CollectionUtils.equalLists(instanceTaskCodeList, definiteTaskCodeList)) {
+                List<Integer> failTaskList = validTaskList.stream().filter(instance -> instance.getState().typeIsFailure() || instance.getState().typeIsCancel())
+                    .map(TaskInstance::getId).collect(Collectors.toList());
+                if (failTaskList.size() == 1 && failTaskList.contains(taskInstanceId)) {
```
Comment (caishunfeng) [inline dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TaskInstanceServiceImpl.java]: It looks strange, why is judgment = 1?

Comment (brave-lee) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TaskInstanceServiceImpl.java]: Because the workflow should succeed only when the last failed task is forced to succeed

Comment (caishunfeng) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TaskInstanceServiceImpl.java]: I think it's better to handle processInstance after updating taskInstance, and then we don't need to use this judgment, WDYT?

Comment (brave-lee) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TaskInstanceServiceImpl.java]: I don't think it's necessary. The update workflow and update task are in the same transaction

Comment (ruanwenjun) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TaskInstanceServiceImpl.java]: It's better to update the taskInstance and then judge if the workflowInstance is success, if the workflow success, we can update the workflow status to success. 

The advantage of creating a method to judge a workflowInstance success it that this method can be used in other place.

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TaskInstanceServiceImpl.java [hunk 3]
```diff
@@ -193,7 +199,26 @@ public Map<String, Object> forceTaskSuccess(User loginUser, long projectCode, In
             putMsg(result, Status.TASK_INSTANCE_STATE_OPERATION_ERROR, taskInstanceId, task.getState().toString());
             return result;
         }
-
+        // Workflow enforcement succeeded
+        ProcessInstance processInstance = processService.findProcessInstanceDetailById(task.getProcessInstanceId());
```
Comment (zhuxt2015) [inline dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TaskInstanceServiceImpl.java]: Suggest extract a method

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TaskInstanceServiceImpl.java (hunk 2 above)
Comment (brave-lee) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TaskInstanceServiceImpl.java]: I think this code is difficult to be universal

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TaskInstanceServiceImpl.java (hunk 3 above)
Comment (brave-lee) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TaskInstanceServiceImpl.java]: The update workflow and update task are in the same transaction, and this code is difficult to be universal. So this was unnecessary

Comment (zhuxt2015) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TaskInstanceServiceImpl.java]: Nobody wants to read long functions.Write the function shorter, the shorter the better.

**Comment by zhongjiajie** [comment]
restart the failed CI

**Comment by zhongjiajie** [comment]
@ruanwenjun   do you have time to review this pr?

**Review by ruanwenjun — APPROVED** [review]

**Comment by caishunfeng** [comment]
@zhongjiajie this pr need to cherry-pick to 3.0.0-prepare.
