### PR TITLE
[FIX-14299][api]: check schedule exists

### LINKED ISSUE #14299: [Bug] [schedule] The interface method creates a scheduled task without data verification
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

image
In version 3.1.7, Multiple timed tasks can be created for the same workflow through the interface. At this time, an error will be reported when querying the workflow list of the project

### What you expected to happen

It is not possible to create a second timed task for the same workflow on the page, so the interface should also limit when the workflow already has a timed task, prompting that the timed task already exists

### How to reproduce

It is not possible to create a second timed task for the same workflow on the page, so the interface should also limit when the workflow already has a timed task, prompting that the timed task already exists

### Anything else

_No response_

### Version

3.1.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by lutongzero**
fix #14299
## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/SchedulerServiceImpl.java [hunk 1]
```diff
@@ -167,6 +167,13 @@ public Map<String, Object> insertSchedule(User loginUser,
         executorService.checkProcessDefinitionValid(projectCode, processDefinition, processDefineCode,
                 processDefinition.getVersion());
 
+        Schedule scheduleExists =
+                scheduleMapper.queryByProcessDefinitionCode(processDefineCode);
+        if (scheduleExists != null) {
+            throw new ServiceException(Status.SCHEDULE_ALREADY_EXISTS, processDefineCode,
```
Comment (rickchengx) [inline dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/SchedulerServiceImpl.java]: Could we put a message in the result to tell the reason to the user, like below:
```
if (scheduleExists != null) {
  log.error("xxx");
  putMsg(result, Status.XXX);
  return result;
}
```

Comment (davidzollo) [inline dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/SchedulerServiceImpl.java]: It's a very good beginning for you to start the first contribution. 
You can prompt the user in a more friendly style, instead of throwing exceptions. Here is an example:
```
log.warn("The schedule already exists.");
putMsg(result, Status.SCHEDULE_ALREADY_EXISTS);
return result;
```

**Review by davidzollo — DISMISSED** [review]

**Comment by rickchengx** [comment]
rerun failed CI

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/SchedulerServiceImpl.java (hunk 1 above)
Comment (lutongzero) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/SchedulerServiceImpl.java]: It seems already okay.

**Review by SbloodyS — APPROVED** [review]
LGTM.

**Review by rickchengx — APPROVED** [review]
LGTM
