### PR TITLE
[Fix-17701][SqlTask] handle duplicate column aliases in SQL result by appending column index suffix

### LINKED ISSUE #17701: [Bug] [SqlTask] When field names are duplicated in a query statement, the result set suffers from name collision, causing values to overwrite each other
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When field names are duplicated in a query statement, the result set suffers from name collision, causing values to overwrite each other;

For example:

SELECT
  user.name AS display_name,
  admin.name AS display_name
FROM user
JOIN admin ON user.id = admin.user_id;

### What you expected to happen

If field names are duplicated, the result set should automatically append suffixes to disambiguate them.

### How to reproduce

When field names are duplicated in a query statement, the result set suffers from name collision, causing values to overwrite each other;

For example:

SELECT
  user.name AS display_name,
  admin.name AS display_name
FROM user
JOIN admin ON user.id = admin.user_id;

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by njnu-seafish**
## Purpose of the pull request

close #17701 

## Brief change log

handle duplicate column aliases in SQL result by appending column index suffix

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

## Pull Request Notice
[Pull Request Notice](https://github.com/apache/dolphinscheduler/blob/dev/docs/docs/en/contribute/join/pull-request.md)

If your pull request contains incompatible change, you should also add it to `docs/docs/en/guide/upgrade/incompatible.md`

### CODE REVIEW

**Review by SbloodyS — COMMENTED** [review]
Please add some ut to test it. @njnu-seafish

**Comment by njnu-seafish** [comment]
> Please add some ut to test it. @njnu-seafish

ok

**Review by SbloodyS — CHANGES_REQUESTED** [review]
Please don't directly use code generated by AI.

File: dolphinscheduler-task-plugin/dolphinscheduler-task-sql/src/main/java/org/apache/dolphinscheduler/plugin/task/sql/SqlTask.java [hunk 1]
```diff
@@ -248,11 +250,38 @@ private String resultProcess(ResultSet resultSet) throws Exception {
             int num = md.getColumnCount();
 
             while (resultSet.next()) {
-                ObjectNode mapOfColValues = JSONUtils.createObjectNode();
+                ObjectNode rowAsJson = JSONUtils.createObjectNode();
+                Set<String> usedLabels = new HashSet<>();
+
                 for (int i = 1; i <= num; i++) {
-                    mapOfColValues.set(md.getColumnLabel(i), JSONUtils.toJsonNode(resultSet.getObject(i)));
+                    // Get the column label (alias) from metadata; fall back to a generic name if null or empty
```
Comment (SbloodyS) [inline dolphinscheduler-task-plugin/dolphinscheduler-task-sql/src/main/java/org/apache/dolphinscheduler/plugin/task/sql/SqlTask.java]:
```suggestion
```

Please remove unnessnary comment.

File: dolphinscheduler-task-plugin/dolphinscheduler-task-sql/src/main/java/org/apache/dolphinscheduler/plugin/task/sql/SqlTask.java [hunk 2]
```diff
@@ -248,11 +250,38 @@ private String resultProcess(ResultSet resultSet) throws Exception {
...
+                    // Generate a unique field key for the JSON object:
+                    // If the base label is already used in this row, append a numeric suffix (e.g., name_2, name_3)
+                    String finalLabel = baseLabel;
+                    int suffix = 2; // Start numbering duplicates from _2 to keep the first occurrence clean
+
+                    while (!usedLabels.add(finalLabel)) {
+                        finalLabel = baseLabel + "_" + suffix++;
+                    }
+
+                    // Read the column value and convert it to a JSON node
```
Comment (SbloodyS) [inline dolphinscheduler-task-plugin/dolphinscheduler-task-sql/src/main/java/org/apache/dolphinscheduler/plugin/task/sql/SqlTask.java]:
```suggestion
```

File: dolphinscheduler-task-plugin/dolphinscheduler-task-sql/src/main/java/org/apache/dolphinscheduler/plugin/task/sql/SqlTask.java [hunk 3]
```diff
@@ -248,11 +250,38 @@ private String resultProcess(ResultSet resultSet) throws Exception {
...
+                    try {
+                        Object value = resultSet.getObject(i);
+                        rowAsJson.set(finalLabel, JSONUtils.toJsonNode(value));
+                    } catch (SQLException e) {
+                        // Log warning but continue processing: avoid failing the entire row due to one problematic
+                        // column
```
Comment (SbloodyS) [inline dolphinscheduler-task-plugin/dolphinscheduler-task-sql/src/main/java/org/apache/dolphinscheduler/plugin/task/sql/SqlTask.java]:
```suggestion
```

File: dolphinscheduler-task-plugin/dolphinscheduler-task-sql/src/main/java/org/apache/dolphinscheduler/plugin/task/sql/SqlTask.java [hunk 4]
```diff
@@ -248,11 +250,38 @@ private String resultProcess(ResultSet resultSet) throws Exception {
...
+                        log.warn("Failed to read column {} (label: '{}') in row {}: {}",
```
Comment (SbloodyS) [inline dolphinscheduler-task-plugin/dolphinscheduler-task-sql/src/main/java/org/apache/dolphinscheduler/plugin/task/sql/SqlTask.java]:
```suggestion
                        log.warn("Failed to read column {}, label: {}, in row {}: {}",
```

**Review by SbloodyS — CHANGES_REQUESTED** [review]

**Comment by njnu-seafish** [comment]
> Please don't directly use code generated by AI.

OK,  revert the unrelated changes.

File: dolphinscheduler-task-plugin/dolphinscheduler-task-sql/src/main/java/org/apache/dolphinscheduler/plugin/task/sql/SqlTask.java (hunk 1 above)
Comment (njnu-seafish) [reply dolphinscheduler-task-plugin/dolphinscheduler-task-sql/src/main/java/org/apache/dolphinscheduler/plugin/task/sql/SqlTask.java]: > Please remove unnessnary comment.

ok, done

File: dolphinscheduler-task-plugin/dolphinscheduler-task-sql/src/main/java/org/apache/dolphinscheduler/plugin/task/sql/SqlTask.java (hunk 2 above)
Comment (njnu-seafish) [reply dolphinscheduler-task-plugin/dolphinscheduler-task-sql/src/main/java/org/apache/dolphinscheduler/plugin/task/sql/SqlTask.java]: > 

ok,done

File: dolphinscheduler-task-plugin/dolphinscheduler-task-sql/src/main/java/org/apache/dolphinscheduler/plugin/task/sql/SqlTask.java (hunk 3 above)
Comment (njnu-seafish) [reply dolphinscheduler-task-plugin/dolphinscheduler-task-sql/src/main/java/org/apache/dolphinscheduler/plugin/task/sql/SqlTask.java]: > 

ok,done

File: dolphinscheduler-task-plugin/dolphinscheduler-task-sql/src/main/java/org/apache/dolphinscheduler/plugin/task/sql/SqlTask.java (hunk 4 above)
Comment (njnu-seafish) [reply dolphinscheduler-task-plugin/dolphinscheduler-task-sql/src/main/java/org/apache/dolphinscheduler/plugin/task/sql/SqlTask.java]: > 

ok, done

File: dolphinscheduler-task-plugin/dolphinscheduler-task-sql/src/test/java/org/apache/dolphinscheduler/plugin/task/sql/SqlTaskTest.java [hunk 5]
```diff
@@ -197,4 +205,228 @@ void testVarPoolSetting() {
...
+        String result = (String) method.invoke(sqlTask, mockRs);
+
+        Assertions.assertNotNull(result);
+        Assertions.assertTrue(result.contains("\"id\":101"));
+        Assertions.assertTrue(result.contains("\"id_2\":102"));
+        Assertions.assertTrue(result.contains("\"id_3\":103"));
+    }
+
+    @Test
+    void testResultProcess_ColumnNames_IdIdId2Id2Id3_HandlesSuffixCollisionCorrectly() throws Exception {
```
[the remark this answers is not in the document]
Comment (njnu-seafish) [reply dolphinscheduler-task-plugin/dolphinscheduler-task-sql/src/test/java/org/apache/dolphinscheduler/plugin/task/sql/SqlTaskTest.java]: > [nitpick] The test name `testResultProcess_ColumnNames_IdIdId2Id2Id3_HandlesSuffixCollisionCorrectly` is quite long and could be simplified. Consider renaming to `testResultProcess_HandlesSuffixCollisionWithDuplicateColumns` for better readability while maintaining clarity about what is being tested.

ok,done

**Review by SbloodyS — DISMISSED** [review]
LGTM

**Review by ruanwenjun — DISMISSED** [review]

**Comment by ruanwenjun** [comment]
We should use list rather than map/set to store the result, then we can keep the origin column name.

File: dolphinscheduler-task-plugin/dolphinscheduler-task-sql/src/main/java/org/apache/dolphinscheduler/plugin/task/sql/SqlTask.java [hunk 6]
```diff
@@ -246,11 +248,26 @@ private String resultProcess(ResultSet resultSet) throws Exception {
...
             int num = md.getColumnCount();
+            String[] columnLabels = new String[num];
+
+            // Check for duplicates in column definitions (across all columns)
+            Set<String> uniqueLabels = new HashSet<>(num);
+            for (int i = 1; i <= num; i++) {
+                String label = md.getColumnLabel(i);
+                if (StringUtils.isEmpty(label)) {
+                    label = "col_" + i;
+                }
```
Comment (ruanwenjun) [inline dolphinscheduler-task-plugin/dolphinscheduler-task-sql/src/main/java/org/apache/dolphinscheduler/plugin/task/sql/SqlTask.java]:
```suggestion
```
We don't need to add prefix `col_`

Comment (njnu-seafish) [reply dolphinscheduler-task-plugin/dolphinscheduler-task-sql/src/main/java/org/apache/dolphinscheduler/plugin/task/sql/SqlTask.java]: > We don't need to add prefix `col_`

ok,will delete it

File: dolphinscheduler-task-plugin/dolphinscheduler-task-sql/src/main/java/org/apache/dolphinscheduler/plugin/task/sql/SqlTask.java [hunk 7]
```diff
@@ -246,11 +248,23 @@ private String resultProcess(ResultSet resultSet) throws Exception {
         if (resultSet != null) {
             ResultSetMetaData md = resultSet.getMetaData();
             int num = md.getColumnCount();
+            String[] columnLabels = new String[num];
```
Comment (ruanwenjun) [inline dolphinscheduler-task-plugin/dolphinscheduler-task-sql/src/main/java/org/apache/dolphinscheduler/plugin/task/sql/SqlTask.java:251]: This variable seems meaningless.

**Review by ruanwenjun — APPROVED** [review]

File: dolphinscheduler-task-plugin/dolphinscheduler-task-sql/src/main/java/org/apache/dolphinscheduler/plugin/task/sql/SqlTask.java (hunk 7 above)
Comment (njnu-seafish) [reply dolphinscheduler-task-plugin/dolphinscheduler-task-sql/src/main/java/org/apache/dolphinscheduler/plugin/task/sql/SqlTask.java:251]: > This variable seems meaningless.

mapOfColValues.set(md.getColumnLabel(i), JSONUtils.toJsonNode(resultSet.getObject(i)));
to
mapOfColValues.set(columnLabels[i - 1], JSONUtils.toJsonNode(resultSet.getObject(i)));

**Review by SbloodyS — APPROVED** [review]
+1
