### PR TITLE
[Fix-9868] A task flow definition isolates the runs of different execution strategies by version numbers.

### LINKED ISSUE #9868: [Bug-BE] Task flow definition cannot execute serial task flow while parallel serial alternate running.
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Task flow definition cannot execute serial task flow while parallel serial alternate running.

### What you expected to happen

the task is running normally

### How to reproduce

1. create two shell node workflow
2. run four times in parallel
3. offline workflow
4. edit workflow
5. run four times in serial

### Anything else

No Response

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by WangJPLeo**
## Purpose of the pull request

A task flow definition isolates the runs of different execution strategies by version numbers.

## Brief change log

close #9868 

## Verify this pull request

Manually verified the change by testing locally.

### CODE REVIEW

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteThread.java [hunk 1]
```diff
@@ -820,6 +820,10 @@ private void endProcess() {
         }
     }
 
+    public boolean checkProcessDefinitionTypeIsSerialWait(){
+        return processService.findProcessDefinitionByCode(processDefinition.getCode()).getExecutionType().typeIsSerialWait();
```
Comment (caishunfeng) [inline dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteThread.java]: I think it's not a good way to solve this issue.

File: dolphinscheduler-master/src/test/java/org/apache/dolphinscheduler/server/master/WorkflowExecuteThreadTest.java [hunk 2]
```diff
@@ -24,9 +24,7 @@
 
 import static org.powermock.api.mockito.PowerMockito.mock;
 
-import org.apache.dolphinscheduler.common.enums.CommandType;
-import org.apache.dolphinscheduler.common.enums.Flag;
-import org.apache.dolphinscheduler.common.enums.ProcessExecutionTypeEnum;
+import org.apache.dolphinscheduler.common.enums.*;
```
Comment (SbloodyS) [inline dolphinscheduler-master/src/test/java/org/apache/dolphinscheduler/server/master/WorkflowExecuteThreadTest.java]: Please avoid import *

**Review by caishunfeng — APPROVED** [review]
LGTM
