### PR TITLE
[Bug-12908][Worker]Fix execute shell task exception no dolphinscheduler_env.sh file execute permission

### LINKED ISSUE #12908: [Bug] [Worker] Execute shell task exception no dolphinscheduler_env.sh file execute permission
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Execute shell task exception no dolphinscheduler_env.sh file execute permission.

iShot_2022-11-15_19 13 54

### What you expected to happen

Execute the shell task to execute the dolphinscheduler_env.sh file normally.

### How to reproduce

Restart the worker-server service, execute shell tasks, and view task logs.

### Anything else

_No response_

### Version

3.1.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by zhuangchong**
…ute permission

## Purpose of the pull request

this pr closes: #12908 

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

File: dolphinscheduler-worker/src/main/bin/start.sh [hunk 1]
```diff
@@ -21,7 +21,6 @@ DOLPHINSCHEDULER_HOME=${DOLPHINSCHEDULER_HOME:-$(cd $BIN_DIR/..; pwd)}
 
 source "$DOLPHINSCHEDULER_HOME/conf/dolphinscheduler_env.sh"
 
-chmod -R 700 ${DOLPHINSCHEDULER_HOME}/conf
```
Comment (DarkAssassinator) [inline dolphinscheduler-worker/src/main/bin/start.sh:24]: chould we change to `755`? WDYT

Comment (zhuangchong) [reply dolphinscheduler-worker/src/main/bin/start.sh:24]: There is account password information in the application.yaml file in the conf directory, so it is not recommended to set the permission to 755.

If it is set to `chmod -R 755 ${DOLPHINSCHEDULER_HOME}/conf/dolphinscheduler_env.sh`, when the conf folder does not have other user execution permissions, it will still report that the dolphinscheduler_env.sh file permissions are insufficient.

Do you have any good suggestions for only setting dolphinscheduler_env.sh file permissions to 755 and other file permissions to 700?

Comment (DarkAssassinator) [reply dolphinscheduler-worker/src/main/bin/start.sh:24]: > There is account password information in the application.yaml file in the conf directory, so it is not recommended to set the permission to 755.
> 
> If it is set to `chmod -R 755 ${DOLPHINSCHEDULER_HOME}/conf/dolphinscheduler_env.sh`, when the conf folder does not have other user execution permissions, it will still report that the dolphinscheduler_env.sh file permissions are insufficient.
> 
> Do you have any good suggestions for only setting dolphinscheduler_env.sh file permissions to 755 and other file permissions to 700?

IMHO, I have the following two ideas：
1. Just keep only one `dolphinscheduler_env.sh` in bin/env/dolphinscheduler_env.sh, all services no longer keep a separate copy of the file. Becasue all these files are same. So we just need chmod -R 755 `bin/env/dolphinscheduler_env.sh`
2. All tmp execution path source a source file in other disk path is not a good idea. May can copy it to execution path and clear it after task finished. This ensures that all files needed for the task to run are stored in the temporary execution directory. WDYT.

Comment (ruanwenjun) [reply dolphinscheduler-worker/src/main/bin/start.sh:24]: Remove `chmod -R 700 ${DOLPHINSCHEDULER_HOME}/conf` is ok for me.

If fact, `${DOLPHINSCHEDULER_HOME}/conf/dolphinscheduler_env.sh` is the default env faile will be sourced by task, we can change this in common.properties `dolphinscheduler.env.path`.

**Review by ruanwenjun — APPROVED** [review]

**Review by SbloodyS — APPROVED** [review]
+1
