### PR TITLE
[Fix-12916] Add permission check when query or download log

### LINKED ISSUE #12916: [Bug] [Log] User can query or download other user's log
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

User can query or download other user's log

### What you expected to happen

There's permission control in loggerService.

### How to reproduce

User (not admin) query the log of a task instance which is created by other user.

截屏2022-11-16 09 55 30

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by rickchengx**
## Purpose of the pull request

* close: #12916 

Currently, there is no permission check when user query or download log by task instance id.

截屏2022-11-16 09 55 30

## Brief change log

Add permission check when query or download log

### Who can query or download log ?

All users **who have the permission of the project** to which the task instance belongs can query or download the log.

1.  Query the project to which the task instance belongs from the database.

3.  Check the permission of project by `projectService.checkProjectAndAuth()`

## Verify this pull request

covered by UT and manually tested as below

Note that the task instance id 1 is not created by current login user.

截屏2022-11-16 14 11 12

截屏2022-11-16 14 10 21

### CODE REVIEW

**Review by SbloodyS — COMMENTED** [review]
I dont't think it's a bug. It need to be disscussed. cc @ruanwenjun @caishunfeng @EricGao888 @zhongjiajie

**Comment by rickchengx** [comment]
> I dont't think it's a bug. It need to be disscussed. cc @ruanwenjun @caishunfeng @EricGao888 @zhongjiajie

Hi, @SbloodyS , thanks for your comment.

Here is an example to illustrate why I think this is a bug:

* `User 1` has a project `project-1`, and an `task-instance-1` (suppose `taskInstanceId`=1)
* `User 2` has no permission on `project-1` , and he cannot see the `project-1` and the `task-instance-1` on the UI. But he can easily query the log of `task-instance-1` by sending a GET http `/dolphinscheduler/log/detail?taskInstanceId=1&skipLineNum=0&limit=1000`. He only needs to set an `taskInstanceId`, which is not randomly generated.

In more serious cases, the logs may contain sensitive information 
* E.g., the log of `Sqoop` task will output the mysql password (BTW, this problem will be fixed in #11589 )
Then `User 2` will get the sensitive information to which **he does not have permission**.

**Comment by Radeity** [comment]
> I dont't think it's a bug. It need to be disscussed. cc @ruanwenjun @caishunfeng @EricGao888 @zhongjiajie

I agree with @rickchengx, users may make bad log decisions which will lead to security issue, so there's a strong need to for this permission check. In addition, i suggest to add request to apply for temporary permission to query and download logs for users who don't have permission, and this application can be approved by administrator.

**Comment by rickchengx** [comment]
> > I dont't think it's a bug. It need to be disscussed. cc @ruanwenjun @caishunfeng @EricGao888 @zhongjiajie
> 
> I agree with @rickchengx, users may make bad log decisions which will lead to security issue, so there's a strong need to for this permission check. In addition, i suggest to add request to apply for temporary permission to query and download logs for users who don't have permission, and this application can be approved by administrator.

Hi, @Radeity Thanks for your comment.

I agree that permission check is required when user query or download task logs.

### Can admin authorize the log permission to the user in this PR?

Currently, admin can authorize users for the following resources: (E.g., project / resource / ....)

截屏2022-11-21 10 08 43

And in the design of this PR:
Only **users with project permissions** to which the task instance belongs can query or download the logs of that task instance.

**Because I think the log of the task can be viewed only if the user can view the task.**

So in this PR, admin can authorize the log permission to the user by authorize users for the `project` resource.



As for what you said, whether the administrator can individually add the log permission of a certain task instance to the user, I think it can be discussed and done after solving this security problem.

WDYT

cc @SbloodyS @EricGao888 @ruanwenjun @caishunfeng @zhongjiajie

**Comment by zhongjiajie** [comment]
> > > I dont't think it's a bug. It need to be disscussed. cc @ruanwenjun @caishunfeng @EricGao888 @zhongjiajie
> > 
> > 
> > I agree with @rickchengx, users may make bad log decisions which will lead to security issue, so there's a strong need to for this permission check. In addition, i suggest to add request to apply for temporary permission to query and download logs for users who don't have permission, and this application can be approved by administrator.
> 
> Hi, @Radeity Thanks for your comment.
> 
> I agree that permission check is required when user query or download task logs.
> 
> ### Can admin authorize the log permission to the user in this PR?
> Currently, admin can authorize users for the following resources: (E.g., project / resource / ....)
> 
> 截屏2022-11-21 10 08 43
> 
> And in the design of this PR: Only **users with project permissions** to which the task instance belongs can query or download the logs of that task instance.
> 
> **Because I think the log of the task can be viewed only if the user can view the task.**
> 
> So in this PR, admin can authorize the log permission to the user by authorize users for the `project` resource.
> 
> As for what you said, whether the administrator can individually add the log permission of a certain task instance to the user, I think it can be discussed and done after solving this security problem.
> 
> WDYT
> 
> cc @SbloodyS @EricGao888 @ruanwenjun @caishunfeng @zhongjiajie

I think we keep permission within the project level is acceptable. we already supported it and it is simple enough

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/LoggerServiceImpl.java [hunk 1]
```diff
@@ -227,4 +235,14 @@ private byte[] getLogBytes(TaskInstance taskInstance) {
...
                 logClient.getLogBytes(host.getIp(), host.getPort(), taskInstance.getLogPath()));
     }
+
+    private boolean checkPermissionByTaskInstanceId(User loginUser, int taskInstanceId, String permissionKey) {
+        Project project = projectMapper.queryProjectByTaskInstanceId(taskInstanceId);
+        if (project == null) {
+            return false;
+        }
+        Map<String, Object> result =
+                projectService.checkProjectAndAuth(loginUser, project, project.getCode(), permissionKey);
```
Comment (zhongjiajie) [inline dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/LoggerServiceImpl.java]: could you use `checkProjectAndAuthThrowException` instead of `checkProjectAndAuth` to make our code more clear? It is may ask to change our UT as well

**Review by zhongjiajie — COMMENTED** [review]
Ohters LGTM

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/LoggerServiceImpl.java (hunk 1 above)
Comment (rickchengx) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/LoggerServiceImpl.java]: Hi, @zhongjiajie Thanks for your suggestion. I've changed to checkProjectAndAuthThrowException.

**Review by EricGao888 — DISMISSED** [review]

**Review by EricGao888 — APPROVED** [review]

**Comment by EricGao888** [comment]
PTAL when available, if no more comments, will proceed to merge.
