### PR TITLE
[BUG][API]Fix format2Duration when parameter has one is null

### LINKED ISSUE #4803: [Bug][API] The reason is that the end time is currently empty when calculating the process duration.
The reason is that the end time is currently empty when calculating the process duration.

当查询工作流实例时，一个流程实例正在运行，查询将会失败

### PR DESCRIPTION
**Pull request by felix-thinkingdata**
ThIs Close #4803 

When querying a workflow instance, a process instance is running and the query will fail。

---

当查询工作流实例时，一个流程实例正在运行，查询将会失败

The reason is that the end time is currently empty when calculating the process duration.
---
原因是因为，计算流程持续时间时，结束时间目前还是空。

So the query failed.

---

所以导致查询失败。

### CODE REVIEW

File: dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/utils/DateUtilsTest.java [hunk 1]
```diff
@@ -196,4 +196,12 @@ public void testFormat2Duration() {
 
     }
 
+    @Test
+    public void testNullDuration() {
+        // days hours minutes seconds
+        Date d1 = DateUtils.stringToDate("2020-01-20 11:00:00");
+        Date d2 = null;
+        Assert.assertEquals("",DateUtils.format2Duration(d1,d2));
```
Comment (chengshiwen) [inline dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/utils/DateUtilsTest.java]: It's better to add a trailing space after each comma

**Review by chengshiwen — CHANGES_REQUESTED** [review]

File: dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/utils/DateUtilsTest.java (hunk 1 above)
Comment (felix-thinkingdata) [reply dolphinscheduler-common/src/test/java/org/apache/dolphinscheduler/common/utils/DateUtilsTest.java]: ok

**Review by chengshiwen — APPROVED** [review]
Maybe it's better to `return null` in `format2Duration`?

**Comment by CalvinKirs** [comment]
hi, let me worry things is if users use this return value (value is  "") calculation，maybe happen error, so, you should check any use this method's method.

File: dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/DateUtils.java [hunk 2]
```diff
@@ -259,6 +259,9 @@ public static String format2Readable(long ms) {
      * @return format time
      */
     public static String format2Duration(Date d1, Date d2) {
+        if (d1 == null || d2 == null) {
+            return "";
```
Comment (vimacro) [inline dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/DateUtils.java]: Better to `return null`

**Review by vimacro — CHANGES_REQUESTED** [review]

File: dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/DateUtils.java (hunk 2 above)
Comment (felix-thinkingdata) [reply dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/DateUtils.java]: ok

**Comment by felix-thinkingdata** [comment]
> hi, let me worry things is if users use this return value (value is "") calculation，maybe happen error, so, you should check any use this method's method.

In three cases, this function is used to calculate the duration of the query.

**Review by vimacro — APPROVED** [review]
+1

**Comment by zhuangchong** [comment]
+1

**Review by CalvinKirs — APPROVED** [review]
LGTM
