### PR TITLE
[Fix-17187][Dependent Task] finish dependent task error

### LINKED ISSUE #17187: [Bug] [Dependent Task] finish dependent task error
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

```
2025-05-15 20:06:55.555 ERROR [shared-task-executor-container-worker-28] - parse list exception!
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `java.util.ArrayList<org.apache.dolphinscheduler.dao.entity.AbstractTaskInstanceContext>` from String value (token `JsonToken.VALUE_STRING`)
 at [Source: (String)""[{\"contextType\":\"DEPENDENT_RESULT_CONTEXT\",\"projectCode\":141157194160992,\"workflowDefinitionCode\":141167447773024,\"taskDefinitionCode\":0,\"dateCycle\":\"currentHour\",\"dependentResult\":\"SUCCESS\"},{\"contextType\":\"DEPENDENT_RESULT_CONTEXT\",\"projectCode\":141157194160992,\"workflowDefinitionCode\":141169219433312,\"taskDefinitionCode\":0,\"dateCycle\":\"currentHour\",\"dependentResult\":\"SUCCESS\"}]""; line: 1, column: 1]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1741)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1515)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1462)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.handleNonArray(CollectionDeserializer.java:392)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromString(CollectionDeserializer.java:326)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:250)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4674)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3629)
	at org.apache.dolphinscheduler.common.utils.JSONUtils.toList(JSONUtils.java:186)
	at org.apache.dolphinscheduler.dao.entity.TaskInstanceContext.getTaskInstanceContext(TaskInstanceContext.java:54)
	at org.apache.dolphinscheduler.dao.repository.impl.TaskInstanceContextDaoImpl.upsertTaskInstanceContext(TaskInstanceContextDaoImpl.java:79)
	at org.apache.dolphinscheduler.dao.repository.impl.TaskInstanceContextDaoImpl$$FastClassBySpringCGLIB$$83f794fe.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
	at org.apache.dolphinscheduler.dao.repository.impl.TaskInstanceContextDaoImpl$$EnhancerBySpringCGLIB$$c86c33e2.upsertTaskInstanceContext(<generated>)
	at org.apache.dolphinscheduler.server.master.engine.executor.plugin.dependent.DependentTaskTracker.lambda$isAllDependentTaskFinished$1(DependentTaskTracker.java:270)
	at java.util.HashMap.forEach(HashMap.java:1289)
	at org.apache.dolphinscheduler.server.master.engine.executor.plugin.dependent.DependentTaskTracker.isAllDependentTaskFinished(DependentTaskTracker.java:243)
	at org.apache.dolphinscheduler.server.master.engine.executor.plugin.dependent.DependentTaskTracker.getDependentTaskStatus(DependentTaskTracker.java:109)
	at org.apache.dolphinscheduler.server.master.engine.executor.plugin.dependent.DependentLogicTask.getTaskExecutionState(DependentLogicTask.java:76)
	at org.apache.dolphinscheduler.server.master.engine.executor.LogicTaskExecutor.doTrackTaskPluginStatus(LogicTaskExecutor.java:44)
	at org.apache.dolphinscheduler.task.executor.AbstractTaskExecutor.trackTaskExecutorState(AbstractTaskExecutor.java:95)
	at org.apache.dolphinscheduler.task.executor.worker.AbstractTaskExecutorWorker.trackTaskExecutorState(AbstractTaskExecutorWorker.java:38)
	at org.apache.dolphinscheduler.task.executor.worker.TaskExecutorWorker.start(TaskExecutorWorker.java:72)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

### What you expected to happen

running normally.

### How to reproduce

aboved.

### Anything else

_No response_

### Version

3.3.0-alpha

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by SbloodyS**
## Purpose of the pull request

close #17187

## Brief change log

- Avoid serialization twice.

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

## Pull Request Notice
[Pull Request Notice](https://github.com/apache/dolphinscheduler/blob/dev/docs/docs/en/contribute/join/pull-request.md)

If your pull request contains incompatible change, you should also add it to `docs/docs/en/guide/upgrade/incompatible.md`

### CODE REVIEW

File: dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/repository/impl/TaskInstanceContextDaoImpl.java [hunk 1]
```diff
@@ -91,7 +90,7 @@ public int upsertTaskInstanceContext(TaskInstanceContext taskInstanceContext) {
             taskInstanceContext.setTaskInstanceContext(deduplicatedDependentResultTaskInstanceContextList);
             return mybatisMapper.updateTaskInstanceContextByTaskInstanceIdAndContextType(
                     taskInstanceContext.getTaskInstanceId(),
-                    taskInstanceContext.getContextType(), JSONUtils.toJsonString(taskInstanceContext.getContext()));
+                    taskInstanceContext.getContextType(), taskInstanceContext.getContext());
```
Comment (ruanwenjun) [inline dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/repository/impl/TaskInstanceContextDaoImpl.java]: It seems we can directly update by dbTaskInstanceContext's id?

Comment (SbloodyS) [reply dolphinscheduler-dao/src/main/java/org/apache/dolphinscheduler/dao/repository/impl/TaskInstanceContextDaoImpl.java]: Yes. I've change it.

**Review by ruanwenjun — COMMENTED** [review]
LGTM

**Review by ruanwenjun — DISMISSED** [review]

**Review by zhongjiajie — DISMISSED** [review]

**Review by zhongjiajie — APPROVED** [review]
🎉

**Review by ruanwenjun — APPROVED** [review]
