### PR TITLE
[Fix-7037][dolphincheduler-server] process instance can not be killed when complement data

### LINKED ISSUE #7037: [Bug] [Data Supplement] process instance can not be killed.
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Starting a job with data supplement in proccess definition ui.

Stopping process instance with stop button in process instance list ui.

Not only did it not stop, it also restart the same task instance.

### What you expected to happen

stopping process instance successfully.

### How to reproduce

Starting a job with data supplement in proccess definition ui.

Stopping process instance with stop button in process instance list ui.

### Anything else

_No response_

### Version

2.0.0

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by SbloodyS**
## Purpose of the pull request

fix #7037

## Brief change log

update WorkflowExecuteThread.java

### CODE REVIEW

File: dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteThread.java [hunk 1]
```diff
@@ -518,7 +518,7 @@ public TaskInstance getTaskInstance(int taskInstanceId) {
     private boolean processStateChangeHandler(StateEvent stateEvent) {
         try {
             logger.info("process:{} state {} change to {}", processInstance.getId(), processInstance.getState(), stateEvent.getExecutionStatus());
-            if (processComplementData()) {
+            if (processInstance.getState() != ExecutionStatus.READY_STOP && processComplementData()) {
```
Comment (caishunfeng) [inline dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteThread.java]: Is it better to move this state condition into `processComplementData()`?

Comment (SbloodyS) [reply dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteThread.java]: please review again.thanks.

**Review by lenboo — APPROVED** [review]
+1
