### PR TITLE
[Bug-13010] [Task] The Flink SQL task page selects the pre-job deployment mode, but the task executed by the worker is the Flink local mode

### LINKED ISSUE #13010: [Bug] [Task] The Flink SQL task page selects the pre-job deployment mode, but the task executed by the worker is the Flink local mode
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

The Flink SQL task page selects the pre-job deployment mode, but the task executed by the worker is the Flink local mode.

### What you expected to happen

The Flink SQL task page selects the pre-job deployment mode, and the task executed by the worker is the Flink per-job mode

### How to reproduce

Select the Flink task type, use SQL, select per-job as the deployment mode, execute this task, and view the flink tasks started by the worker.

### Anything else

_No response_

### Version

3.1.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by zhuangchong**
## Purpose of the pull request

this pr closes: #13010 
Currently flink sql on yarn only supports yarn-per-job mode.

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

**Review by davidzollo — DISMISSED** [review]
LGTM

File: dolphinscheduler-task-plugin/dolphinscheduler-task-flink-stream/src/test/java/org/apache/dolphinscheduler/plugin/task/flink/FlinkArgsUtilsTest.java [hunk 1]
```diff
@@ -117,7 +117,7 @@ public void testRunSql() throws Exception {
     @Test
     public void testInitOptionsInClusterMode() throws Exception {
```
Comment (EricGao888) [inline dolphinscheduler-task-plugin/dolphinscheduler-task-flink-stream/src/test/java/org/apache/dolphinscheduler/plugin/task/flink/FlinkArgsUtilsTest.java]:
```suggestion
    public void testInitOptionsInLocalMode() throws Exception {
```

File: dolphinscheduler-task-plugin/dolphinscheduler-task-flink-stream/src/test/java/org/apache/dolphinscheduler/plugin/task/flink/FlinkArgsUtilsTest.java [hunk 2]
```diff
@@ -126,7 +126,7 @@ public void testInitOptionsInClusterMode() throws Exception {
     @Test
     public void testInitOptionsInApplicationMode() throws Exception {
```
Comment (EricGao888) [inline dolphinscheduler-task-plugin/dolphinscheduler-task-flink-stream/src/test/java/org/apache/dolphinscheduler/plugin/task/flink/FlinkArgsUtilsTest.java]:
```suggestion
    public void testInitOptionsInClusterMode() throws Exception {
```

File: dolphinscheduler-task-plugin/dolphinscheduler-task-flink/src/test/java/org/apache/dolphinscheduler/plugin/task/flink/FlinkArgsUtilsTest.java [hunk 3]
```diff
@@ -117,7 +117,7 @@ public void testRunSql() throws Exception {
     @Test
     public void testInitOptionsInClusterMode() throws Exception {
```
Comment (EricGao888) [inline dolphinscheduler-task-plugin/dolphinscheduler-task-flink/src/test/java/org/apache/dolphinscheduler/plugin/task/flink/FlinkArgsUtilsTest.java]:
```suggestion
    public void testInitOptionsInLocalMode() throws Exception {
```

File: dolphinscheduler-task-plugin/dolphinscheduler-task-flink/src/test/java/org/apache/dolphinscheduler/plugin/task/flink/FlinkArgsUtilsTest.java [hunk 4]
```diff
@@ -126,7 +126,7 @@ public void testInitOptionsInClusterMode() throws Exception {
     @Test
     public void testInitOptionsInApplicationMode() throws Exception {
```
Comment (EricGao888) [inline dolphinscheduler-task-plugin/dolphinscheduler-task-flink/src/test/java/org/apache/dolphinscheduler/plugin/task/flink/FlinkArgsUtilsTest.java]:
```suggestion
    public void testInitOptionsInClusterMode() throws Exception {
```

**Review by EricGao888 — DISMISSED** [review]
LGTM, except few naming inconsistencies.

**Review by EricGao888 — APPROVED** [review]
