### PR TITLE
fix: start param for wf not work

### LINKED ISSUE #15280: [Bug] [parameter] StartParams can't update local params
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When create a workflow, user can set local params in node definition, like the picture below

image

When start a new instanse by webUI, user can set the param value, 
 
image

But according to the document, the priority of params,
> The priority of DolphinScheduler parameters from high to low is: Startup Parameter > Local Parameter > Parameter Context > Global Parameter > Project-level Parameter.

In this case, the value of *datat* should be "bbbb",  but actually, the value of datat is "aaa" which seted in local param. 

### What you expected to happen

according to the document, the priority of params,
> The priority of DolphinScheduler parameters from high to low is: Startup Parameter > Local Parameter > Parameter Context > Global Parameter > Project-level Parameter. 

I think Startup Parameter will update local Parameter

### How to reproduce

Step1: 
Create a workflow, add a shell task.

Step2:
Edit shell task, add stript:
```shell
echo ${datat}
``` 

image

and add a param "datat", default value is "aaa" and then save this workflow. 

Step3:
Start this workflow, and add a startup params, **datat**, set the value to "bbb"

image

Step4:
Check the task log, the value of  param *datat* is still 'aaa'

```
[INFO] 2023-12-05 14:20:24.185 +0800 - process start, process id is: 11226
[INFO] 2023-12-05 14:20:25.185 +0800 -  -> 
	aaa
[INFO] 2023-12-05 14:20:25.186 +0800 - process has exited. execute
```

I check the log, 

```json
"prepareParamsMap" : {
    ...
    "datat" : {
      "prop" : "datat",
      "direct" : "IN",
      "type" : "VARCHAR",
      "value" : "aaa"
    },
    ...
    "StartParams" : {
      "prop" : "StartParams",
      "direct" : "IN",
      "type" : "VARCHAR",
      "value" : "{\"datat\":\"bbbb\"}"
    }
    ...
}

```

### Anything else

Did I misunderstand the document and the type of Parameter ? 

### Version

3.2.x

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by zhongjiajie**
fix: #15280

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

File: dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/expand/CuringParamsServiceImpl.java [hunk 1]
```diff
@@ -199,7 +224,7 @@ public Map<String, Property> paramParsingPreparation(@NonNull TaskInstance taskI
         }
 
         if (MapUtils.isNotEmpty(cmdParam)) {
-            prepareParamsMap.putAll(ParameterUtils.getUserDefParamsMap(cmdParam));
+            prepareParamsMap.putAll(parseWorkflowStartParam(cmdParam));
```
Comment (zhongjiajie) [inline dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/expand/CuringParamsServiceImpl.java:227]: the key reason for this bug.
and others just for some refactor

**Review by caishunfeng — DISMISSED** [review]
LGTM if CI pass

**Comment by rickchengx** [comment]
Hi, @zhongjiajie please fix the CI

**Review by caishunfeng — APPROVED** [review]
LGTM
