### PR TITLE
[Fix-17019][Task Api] Missing execute path in resource limit mode.

### LINKED ISSUE #17019: [Bug] [Task Api] Missing execute path in resource limit mode.
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Missing execute path when using resource limit mode.

Image

### What you expected to happen

There is an execution path when using resource limit mode.

### How to reproduce

1.  Enable `task.task.resource.limit.state`.
2.  Set the `cpuQuota` or `memoryMax` parameter in task definition.
3.  Run workflow.

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by CommandCV**
## Purpose of the pull request

This PR is close https://github.com/apache/dolphinscheduler/issues/17019

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

## Pull Request Notice
[Pull Request Notice](https://github.com/apache/dolphinscheduler/blob/dev/docs/docs/en/contribute/join/pull-request.md)

If your pull request contains incompatible change, you should also add it to `docs/docs/en/guide/upgrade/incompatible.md`

### CODE REVIEW

File: dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/shell/BaseLinuxShellInterceptorBuilder.java [hunk 1]
```diff
@@ -171,6 +171,7 @@ private List<String> bootstrapCommandInResourceLimitMode() {
         }
 
         bootstrapCommand.add(String.format("--uid=%s", runUser));
+        bootstrapCommand.add(shellAbsolutePath().toString());
```
Comment (SbloodyS) [inline dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/shell/BaseLinuxShellInterceptorBuilder.java:174]: Please add some ut.

Comment (CommandCV) [reply dolphinscheduler-task-plugin/dolphinscheduler-task-api/src/main/java/org/apache/dolphinscheduler/plugin/task/api/shell/BaseLinuxShellInterceptorBuilder.java:174]: > Please add some ut.

Done.

**Review by SbloodyS — APPROVED** [review]
LGTM. Thanks for your contribution.

**Review by ruanwenjun — APPROVED** [review]
LGTM
