### PR TITLE
[Fix-8506][Master] process instance stop result wrong

### LINKED ISSUE #8506: [Bug] [Master] process instance stop result wrong
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

1. Stop a process instance which task instance can not find worker group. The state of the stop process instance is success.  If taskInstance.getHost() is empty it will cause WorkflowExecuteThread.taskInstanceMap's taskInstance state wrong In ```org.apache.dolphinscheduler.server.master.runner.task.CommonTaskProcessor#killTask```.
2. Stop a process instance which task instance state is running. The state of the stop process instance is success.
3. When a downstream user uses a dependent node, if the result of kill command is success, the dependent node will judge that the execution is successful. In fact, the execution fails, resulting in an error in the detection result of the dependent node.

### What you expected to happen

The state of the stop process instance is stop.

### How to reproduce

1. Stop a process instance which task instance can not find worker group. 
2. Stop a process instance which task instance state is running. 

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by SbloodyS**
## Purpose of the pull request

This pr will close #8506

### CODE REVIEW

**Comment by SbloodyS** [comment]
Please review. Thanks. @caishunfeng

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteThread.java [hunk 1]
```diff
@@ -455,7 +458,10 @@ private void taskFinished(TaskInstance taskInstance) {
                     killAllTasks();
                 }
             }
+        } else if (taskInstance.getState().typeIsFinished()) {
```
Comment (caishunfeng) [inline dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteThread.java:461]: When will this branch be taken? Does it need to do others processing? like task success or fail.

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteThread.java [hunk 2]
```diff
@@ -1469,8 +1475,6 @@ private ExecutionStatus getProcessInstanceState(ProcessInstance instance) {
                 || CollectionUtils.isNotEmpty(failList)
                 || !isComplementEnd()) {
                 return ExecutionStatus.STOP;
-            } else {
-                return ExecutionStatus.SUCCESS;
```
Comment (caishunfeng) [inline dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteThread.java]: Why to remove this else branch? The state from `READY_STOP` to `SUCCESS` is possible.

Comment (SbloodyS) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteThread.java]: I can't think of any scene where ```ready_stop``` needs to be changed to ```success```. Can you enlight me a bit? @caishunfeng

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteThread.java (hunk 1 above)
Comment (SbloodyS) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteThread.java:461]: It will check in ```org.apache.dolphinscheduler.server.master.runner.WorkflowExecuteThread#getCompleteTaskInstanceMap``` when taskInstance state is cancel(Stop || Kill). This logic exists in 204 branch, but is missing in dev branch.

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteThread.java (hunk 2 above)
Comment (caishunfeng) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteThread.java]: I think when no kill or failure task, the processInstance state can from `ready_stop` to `success`.
Otherwise, if no match `STOP` state, it will always keep `READY_STOP`. What do you think?

Comment (SbloodyS) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/runner/WorkflowExecuteThread.java]: I think of a scenario. When a downstream user uses a dependent node, if the result of kill command is success, the dependent node will judge that the execution is successful. In fact, the execution fails, resulting in an error in the detection result of the dependent node.

**Review by lenboo — DISMISSED** [review]
+1

**Review by lenboo — APPROVED** [review]
+1
