### PR TITLE
[Fix-16063] Fix admin login tenant unspecified issue after upgrade to v3.2.1

### LINKED ISSUE #16063: [Bug] [DAO] When upgrading DS from v3.1.8 to v3.2.1, logging in with the admin account returns the error: "the tenant of the currently login user is not specified"
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

When there are multiple tenants in the dolphinscheduler.t_ds_tenant table in v3.1.8, the binding relationship between admin and default tenant is not updated when upgrading to v3.2.1. Cause admin login to return. the tenant of the current login user is not specified.

### What you expected to happen

To resolve the issue where the admin user is not associated with the default tenant after upgrading DolphinScheduler from v3.1.8 to v3.2.1, need to ensure that the admin user is properly associated with the default tenant.
```
UPDATE `t_ds_user` SET `tenant_id` = '-1' WHERE (`user_name` = 'admin') AND (`tenant_id` = '0');
```

### How to reproduce

1. Create multiple tenants in DS v3.1.8; 
image

2. Upgrade DS from v3.1.8 to v3.2.1; 
After the upgrade is completed, check the t_ds_user table and find that admin and default tenant are not associated.
image

3. Log out of the current login and log in again.
image

### Anything else

_No response_

### Version

3.2.x

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by tinglink**
## Purpose of the pull request
Fix https://github.com/apache/dolphinscheduler/issues/16063
To resolve the issue where the administrator user is not associated with the default tenant after upgrading DolphinScheduler from v3.1.8 to v3.2.1.

## Brief change log
 If the admin account is not associated with a tenant, the admin's tenant will be set to the default tenant.

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

File: dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_h2.sql [hunk 1]
```diff
@@ -1092,6 +1092,9 @@ INSERT INTO t_ds_user
 VALUES ('1', 'admin', '7ad2410b2f4c074479a8937a28a22b8f', '0', 'xxx@qq.com', '', '-1', '2018-03-27 15:48:50',
         '2018-10-24 17:40:22', null, 1, null);
 
+-- If the admin account is not associated with a tenant, the admin's tenant will be set to the default tenant.
+UPDATE `t_ds_user` SET `tenant_id` = '-1' WHERE (`user_name` = 'admin') AND (`tenant_id` = '0');
+
```
Comment (ruanwenjun) [inline dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_h2.sql]:
```suggestion
-- If the admin account is not associated with a tenant, the admin's tenant will be set to the default tenant.
UPDATE `t_ds_user` SET `tenant_id` = '-1' WHERE (`user_name` = 'admin') AND (`tenant_id` = '0');

```


This is not needed, since the default value is -1, and admin's tenantId is -1

File: dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_mysql.sql [hunk 2]
```diff
@@ -1062,6 +1062,9 @@ VALUES (NULL, 1, 'global alert group', 'global alert group', current_timestamp,
 INSERT IGNORE INTO `t_ds_user`
 VALUES ('1', 'admin', '7ad2410b2f4c074479a8937a28a22b8f', '0', 'xxx@qq.com', '', '-1', current_timestamp, current_timestamp, null, 1, null);
 
+-- If the admin account is not associated with a tenant, the admin's tenant will be set to the default tenant.
+UPDATE `t_ds_user` SET `tenant_id` = '-1' WHERE (`user_name` = 'admin') AND (`tenant_id` = '0');
+
```
Comment (ruanwenjun) [inline dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_mysql.sql]:
```suggestion
-- If the admin account is not associated with a tenant, the admin's tenant will be set to the default tenant.
UPDATE `t_ds_user` SET `tenant_id` = '-1' WHERE (`user_name` = 'admin') AND (`tenant_id` = '0');

```

File: dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_postgresql.sql [hunk 3]
```diff
@@ -1053,6 +1053,9 @@ VALUES ('admin', '7ad2410b2f4c074479a8937a28a22b8f', '0', 'xxx@qq.com', '', '-1'
 INSERT INTO t_ds_tenant(id, tenant_code, description, queue_id, create_time, update_time)
 VALUES (-1, 'default', 'default tenant', '1', '2018-03-27 15:48:50', '2018-10-24 17:40:22');
 
+-- If the admin account is not associated with a tenant, the admin's tenant will be set to the default tenant.
+UPDATE `t_ds_user` SET `tenant_id` = '-1' WHERE (`user_name` = 'admin') AND (`tenant_id` = '0');
+
```
Comment (ruanwenjun) [inline dolphinscheduler-dao/src/main/resources/sql/dolphinscheduler_postgresql.sql]:
```suggestion
-- If the admin account is not associated with a tenant, the admin's tenant will be set to the default tenant.
UPDATE `t_ds_user` SET `tenant_id` = '-1' WHERE (`user_name` = 'admin') AND (`tenant_id` = '0');

```

File: dolphinscheduler-dao/src/main/resources/sql/upgrade/3.2.0_schema/mysql/dolphinscheduler_dml.sql [hunk 4]
```diff
@@ -30,6 +30,9 @@ END IF;
 END;
 d//
 
+-- If the admin account is not associated with a tenant, the admin's tenant will be set to the default tenant.
+UPDATE `t_ds_user` SET `tenant_id` = '-1' WHERE (`user_name` = 'admin') AND (`tenant_id` = '0');
+
```
Comment (ruanwenjun) [inline dolphinscheduler-dao/src/main/resources/sql/upgrade/3.2.0_schema/mysql/dolphinscheduler_dml.sql:35]:
```suggestion
-- If the admin account is not associated with a tenant, the admin's tenant will be set to the default tenant.
UPDATE `t_ds_user` SET `tenant_id` = '-1' WHERE `tenant_id` = '0';

```

File: dolphinscheduler-dao/src/main/resources/sql/upgrade/3.2.0_schema/postgresql/dolphinscheduler_dml.sql [hunk 5]
```diff
@@ -21,6 +21,9 @@ INSERT INTO t_ds_tenant(id, tenant_code, description, queue_id, create_time, upd
 UPDATE t_ds_schedules as t1 SET tenant_code = COALESCE(t3.tenant_code, 'default') FROM t_ds_process_definition as t2 LEFT JOIN t_ds_tenant t3 ON t2.tenant_id = t3.id WHERE t1.process_definition_code = t2.code;
 UPDATE t_ds_process_instance SET tenant_code = 'default' WHERE tenant_code IS NULL;
 
+-- If the admin account is not associated with a tenant, the admin's tenant will be set to the default tenant.
+UPDATE `t_ds_user` SET `tenant_id` = '-1' WHERE (`user_name` = 'admin') AND (`tenant_id` = '0');
+
```
Comment (ruanwenjun) [inline dolphinscheduler-dao/src/main/resources/sql/upgrade/3.2.0_schema/postgresql/dolphinscheduler_dml.sql]:
```suggestion
-- If the admin account is not associated with a tenant, the admin's tenant will be set to the default tenant.
UPDATE `t_ds_user` SET `tenant_id` = '-1' WHERE `tenant_id` = '0';

```

**Comment by tinglink** [comment]
@ruanwenjun 
After upgrading from v3.1.8 to v3.2.1, if the admin is not bound to the tenant in v3.1.8, it will not be automatically bound to the tenant after the upgrade is completed, and the admin will not be able to log in directly. 
This problem cannot be ignored. I tried, if v3.2.1 is deployed directly, admin will be automatically associated with the default tenant. If it is a version upgrade, this problem will definitely occur under fixed conditions.

**Comment by ruanwenjun** [comment]
> @ruanwenjun After upgrading from v3.1.8 to v3.2.1, if the admin is not bound to the tenant in v3.1.8, it will not be automatically bound to the tenant after the upgrade is completed, and the admin will not be able to log in directly. This problem cannot be ignored. I tried, if v3.2.1 is deployed directly, admin will be automatically associated with the default tenant. If it is a version upgrade, this problem will definitely occur under fixed conditions.

The bug is imported by 3.2.0 upgrade sql, you only need to fix these at upgrade sql, the initialize sql don't need to be changed.

File: dolphinscheduler-dao/src/main/resources/sql/upgrade/3.2.0_schema/mysql/dolphinscheduler_dml.sql (hunk 4 above)
Comment (tinglink) [reply dolphinscheduler-dao/src/main/resources/sql/upgrade/3.2.0_schema/mysql/dolphinscheduler_dml.sql:35]: Not recommended:
'''
UPDATE t_ds_user SET tenant_id = '-1' WHERE tenant_id = '0';
'''

Response：
Error Code: 1175. You are using safe update mode and you tried to update a table without a WHERE that uses a KEY column. To disable safe mode, toggle the option in Preferences -> SQL Editor and reconnect.

Comment (tinglink) [reply dolphinscheduler-dao/src/main/resources/sql/upgrade/3.2.0_schema/mysql/dolphinscheduler_dml.sql:35]: @ruanwenjun 
Can we just check admin's tenant to ensure that admin can log in normally, and let the user set or adjust his own tenant after logging in?

**Review by ruanwenjun — DISMISSED** [review]
LGTM

**Review by SbloodyS — APPROVED** [review]
+1

**Review by ruanwenjun — APPROVED** [review]
