### PR TITLE
[Fix][Registry]server listener err

### LINKED ISSUE #6137: [Bug][Master] worker cannot be found if worker start earlier than master.
branch : dev
phenomenon：
1 start worker
2 start master
3 start a process instance
4 master cannot find the worker

image

then i restart the master, this problem disappeared！

### PR DESCRIPTION
**Pull request by CalvinKirs**
close #6137 worker cannot be found if worker start earlier than master

### CODE REVIEW

File: dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/registry/ServerNodeManager.java [hunk 1]
```diff
@@ -240,7 +240,7 @@ public void notify(String path, DataChangeEvent dataChangeEvent) {
 
         private String parseGroup(String path) {
             String[] parts = path.split("/");
-            if (parts.length < 6) {
+            if (parts.length < 5) {
```
Comment (lenboo) [inline dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/registry/ServerNodeManager.java]: no magic number

**Review by lenboo — APPROVED** [review]
+1

**Review by zhuangchong — APPROVED** [review]
+1
