### PR TITLE
[Fix-8389][Common] Fix oshi compatibility issues cause it fail to boot on m1 mac

### LINKED ISSUE #8389: [Bug] [common] oshi compatibility issues cause it fail to boot on m1 mac
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

I use a macbook with m1 chip, when starting StandaloneServer, I get the following error

`Caused by: java.lang.UnsatisfiedLinkError: /private/var/folders/k6/h_l1w_m53l76tkylxlc33q4h0000gn/T/jna-113105/jna1882043576609991586.tmp: dlopen(/private/var/folders/k6/h_l1w_m53l76tkylxlc33q4h0000gn/T/jna-113105/jna1882043576609991586.tmp, 0x0001): tried: '/private/var/folders/k6/h_l1w_m53l76tkylxlc33q4h0000gn/T/jna-113105/jna1882043576609991586.tmp' (fat file, but missing compatible architecture (have 'i386,x86_64', need 'arm64e')), '/usr/lib/jna1882043576609991586.tmp' (no such file)
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1950)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1832)
	at java.lang.Runtime.load0(Runtime.java:811)
	at java.lang.System.load(System.java:1088)
	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:947)
	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:922)
	at com.sun.jna.Native.<clinit>(Native.java:190)
	at com.sun.jna.Pointer.<clinit>(Pointer.java:54)
	at com.sun.jna.Structure.<clinit>(Structure.java:2130)
	at oshi.hardware.platform.mac.MacCentralProcessor.<clinit>(MacCentralProcessor.java:53)
	at oshi.hardware.platform.mac.MacHardwareAbstractionLayer.getProcessor(MacHardwareAbstractionLayer.java:54)
	at org.apache.dolphinscheduler.common.utils.OSUtils.cpuUsage(OSUtils.java:136)
	at org.apache.dolphinscheduler.common.utils.HeartBeat.fillSystemInfo(HeartBeat.java:176)
	at org.apache.dolphinscheduler.common.utils.HeartBeat.encodeHeartBeat(HeartBeat.java:204)
	at org.apache.dolphinscheduler.server.registry.HeartBeatTask.getHeartBeatInfo(HeartBeatTask.java:71)
	at org.apache.dolphinscheduler.server.master.registry.MasterRegistryClient.registry(MasterRegistryClient.java:498)
	at org.apache.dolphinscheduler.server.master.registry.MasterRegistryClient.start(MasterRegistryClient.java:120)
	at org.apache.dolphinscheduler.server.master.MasterServer.run(MasterServer.java:136)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157)
	... 18 common frames omitted`

To fix this, we need upgrade oshi-core version , and modify some method calls in OSUtils to adapt the new api.

### What you expected to happen

backend service can run on m1 chip system

### How to reproduce

Start StandaloneServer on a m1 chip macbook

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by ronyang1985**
## Purpose of the pull request

fix [https://github.com/apache/dolphinscheduler/issues/8389](https://github.com/apache/dolphinscheduler/issues/8389)

### CODE REVIEW

File: dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/OSUtils.java [hunk 1]
```diff
@@ -134,7 +135,11 @@ public static double loadAverage() {
      */
     public static double cpuUsage() {
         CentralProcessor processor = hal.getProcessor();
-        double cpuUsage = processor.getSystemCpuLoad();
+
+        long[] preTicks = processor.getSystemCpuLoadTicks();
+        Util.sleep(1000);
```
Comment (zhongjiajie) [inline dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/OSUtils.java]: Why we should sleep here?

Comment (ronyang1985) [reply dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/OSUtils.java]: According to the method annotation, getSystemCpuLoadBetweenTicks(long[] oldTicks)) method  returns the "recent cpu usage" for the whole system by counting ticks between the user-provided value from a previous call. If not sleeping, it will always return value with 0.0D
```
    /**
     * Returns the "recent cpu usage" for the whole system by counting ticks from
     * {@link #getSystemCpuLoadTicks()} between the user-provided value from a
     * previous call.
     *
     * @param oldTicks
     *            A tick array from a previous call to
     *            {@link #getSystemCpuLoadTicks()}
     * @return CPU load between 0 and 1 (100%)
     */
    double getSystemCpuLoadBetweenTicks(long[] oldTicks);
```

File: pom.xml [hunk 2]
```diff
@@ -86,7 +86,7 @@
         <postgresql.version>42.2.5</postgresql.version>
         <hive.jdbc.version>2.1.0</hive.jdbc.version>
         <commons.io.version>2.4</commons.io.version>
-        <oshi.core.version>3.9.1</oshi.core.version>
+        <oshi.core.version>6.1.1</oshi.core.version>
```
Comment (lenboo) [inline pom.xml:89]: This version of 'osh-core' is changed, at the same time  the license need to be checked in './dolphinscheduler-dist/release-docs/' .

Comment (ronyang1985) [reply pom.xml:89]: Hi , i checked and updated the relevant license files

**Comment by zhongjiajie** [comment]
@ronyang1985 Is it ready to go now?

**Comment by ronyang1985** [comment]
> 

@zhongjiajie 
I made some change, and sleep is not required now.
Let's continue

**Review by ruanwenjun — APPROVED** [review]
LGTM

**Comment by zhongjiajie** [comment]
Thanks @ruanwenjun reviewing, I am not sure about the License PTAL @CalvinKirs

**Comment by zhongjiajie** [comment]
If the License is good, we could merge to it

**Review by CalvinKirs — APPROVED** [review]
Well done. License good.

**Review by zhongjiajie — APPROVED** [review]
LGTM, thanks @ronyang1985
