### PR TITLE
[Fix-16224] Add Shell using file E2E case

### LINKED ISSUE #16224: [Bug] Task cannot select resource files since listing is 404
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

Cannot listing files when create new task

### What you expected to happen

xx

### How to reproduce

xx

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by ruanwenjun**
## Purpose of the pull request

close https://github.com/apache/dolphinscheduler/issues/16224

## Brief change log

- Add ShellE2ECase
- Change the default await interval, this can help to speed up the e2e case.

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

## Pull Request Notice
[Pull Request Notice](https://github.com/apache/dolphinscheduler/blob/dev/docs/docs/en/contribute/join/pull-request.md)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

### CODE REVIEW

File: dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/security/SecurityPage.java [hunk 1]
```diff
@@ -68,58 +68,58 @@ public SecurityPage(RemoteWebDriver driver) {
 
     public <T extends SecurityPage.Tab> T goToTab(Class<T> tab) {
         if (tab == TenantPage.class) {
-            new WebDriverWait(driver, Duration.ofSeconds(60)).until(ExpectedConditions.urlContains("/security"));
```
Comment (SbloodyS) [inline dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/security/SecurityPage.java:71]: We should not remove this because some exceptions may occur when jumping to this page from other pages.

File: dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/project/workflow/WorkflowInstanceTab.java [hunk 2]
```diff
@@ -86,6 +86,10 @@ public WorkflowInstanceTab deleteAll() {
     public static class Row {
         private final WebElement row;
 
+        public String name() {
```
Comment (SbloodyS) [inline dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/project/workflow/WorkflowInstanceTab.java]:
```suggestion
        public String workflowName() {
```

File: dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/project/workflow/TaskInstanceTab.java [hunk 3]
```diff
@@ -47,20 +48,32 @@ public List<Row> instances() {
...
             .collect(Collectors.toList());
     }
 
     @RequiredArgsConstructor
     public static class Row {
         private final WebElement row;
 
-        public String state() {
-            return row.findElement(By.className("task-instance-state")).getText();
+        public String name() {
```
Comment (SbloodyS) [inline dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/project/workflow/TaskInstanceTab.java]:
```suggestion
        public String workflowName() {
```

File: dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/project/workflow/TaskInstanceTab.java [hunk 4]
```diff
@@ -35,7 +35,8 @@
 
 @Getter
 public final class TaskInstanceTab extends NavBarPage implements ProjectDetailPage.Tab {
-    @FindBy(className = "items-task-instances")
+
+    @FindBy(css = "tbody > .n-data-table-tr")
```
Comment (SbloodyS) [inline dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/project/workflow/TaskInstanceTab.java]: Please avoid too wide css selector. Id or classname is preferred. If not, it is recommended to use the xpath selector to specify the scope selection, otherwise we may encounter `stale element` exception during the page jumping.

**Review by SbloodyS — CHANGES_REQUESTED** [review]

File: dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/security/SecurityPage.java (hunk 1 above)
Comment (ruanwenjun) [reply dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/security/SecurityPage.java:71]: The url is incorrect, I added 
```
new WebDriverWait(driver, Duration.ofSeconds(60)).until(ExpectedConditions.urlContains("/security/tenant-manage"));
``` 
at the below

File: dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/project/workflow/TaskInstanceTab.java (hunk 4 above)
Comment (ruanwenjun) [reply dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/project/workflow/TaskInstanceTab.java]: The form doesn't have id, and it's hard to use xpath since all class is not unique
image

File: dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/security/SecurityPage.java (hunk 1 above)
Comment (SbloodyS) [reply dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/security/SecurityPage.java:71]: The first `WebDriverWait` is to make sure you're already on the page before you click on it. The second one is to make sure the clicking is finished.

File: dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/project/workflow/TaskInstanceTab.java (hunk 4 above)
Comment (ruanwenjun) [reply dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/project/workflow/TaskInstanceTab.java]: I add class in this form

File: dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/project/workflow/TaskInstanceTab.java (hunk 3 above)
Comment (ruanwenjun) [reply dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/project/workflow/TaskInstanceTab.java]: done

File: dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/project/workflow/WorkflowInstanceTab.java (hunk 2 above)
Comment (ruanwenjun) [reply dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/project/workflow/WorkflowInstanceTab.java]: done

File: dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/security/SecurityPage.java (hunk 1 above)
Comment (ruanwenjun) [reply dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/security/SecurityPage.java:71]: There already exist 
```
new WebDriverWait(driver, Duration.ofSeconds(60)).until(ExpectedConditions.elementToBeClickable(menuTenantManage));
```
This can make sure we already in security page.

File: dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/security/TenantPage.java [hunk 5]
```diff
@@ -133,4 +157,14 @@ public class TenantForm {
         @FindBy(className = "btn-cancel")
         private WebElement buttonCancel;
     }
+
+    @RequiredArgsConstructor
+    public static class Row {
+        private final WebElement row;
+
+        public String name() {
```
Comment (SbloodyS) [inline dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/security/TenantPage.java]:
```suggestion
        public String tenantCode() {
```

File: dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/security/TenantPage.java [hunk 6]
```diff
@@ -61,11 +68,28 @@ public TenantPage(RemoteWebDriver driver) {
...
     }
 
+    public List<Row> tenants() {
+        return tenantList.stream()
+                .filter(WebElement::isDisplayed)
+                .map(Row::new)
+                .collect(Collectors.toList());
+    }
+
+    public boolean containTenant(String tenant) {
```
Comment (SbloodyS) [inline dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/security/TenantPage.java]:
```suggestion
    public boolean containsTenant(String tenant) {
```

File: dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/cases/tasks/ShellTaskE2ETest.java [hunk 7]
```diff
@@ -0,0 +1,256 @@
...
+import org.openqa.selenium.WebElement;
+import org.testcontainers.shaded.org.awaitility.Awaitility;
+import static org.assertj.core.api.Assertions.assertThat;
+import static org.testcontainers.shaded.org.awaitility.Awaitility.await;
+
+@DolphinScheduler(composeFiles = "docker/basic/docker-compose.yaml")
+public class ShellTaskE2ETest extends BaseWorkflowE2ETest {
+
+    @Test
+    void testRunShellTasks_SuccessCase() {
```
Comment (SbloodyS) [inline dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/cases/tasks/ShellTaskE2ETest.java:44]: We should avoid using `_` in function name. WDYT?

File: dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/cases/tasks/ShellTaskE2ETest.java [hunk 8]
```diff
@@ -0,0 +1,256 @@
...
+import org.junit.jupiter.api.Test;
+import org.openqa.selenium.WebElement;
+import org.testcontainers.shaded.org.awaitility.Awaitility;
+import static org.assertj.core.api.Assertions.assertThat;
+import static org.testcontainers.shaded.org.awaitility.Awaitility.await;
+
+@DolphinScheduler(composeFiles = "docker/basic/docker-compose.yaml")
+public class ShellTaskE2ETest extends BaseWorkflowE2ETest {
+
+    @Test
```
Comment (SbloodyS) [inline dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/cases/tasks/ShellTaskE2ETest.java:43]: We should add `Order(xx)` to ensure test order.

Comment (ruanwenjun) [reply dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/cases/tasks/ShellTaskE2ETest.java:43]: done

File: dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/cases/tasks/ShellTaskE2ETest.java (hunk 7 above)
Comment (ruanwenjun) [reply dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/cases/tasks/ShellTaskE2ETest.java:44]: It's suggested to use _ in test case naming, this can help to maintain the case.
https://dzone.com/articles/7-popular-unit-test-naming

File: dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/security/TenantPage.java (hunk 5 above)
Comment (ruanwenjun) [reply dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/security/TenantPage.java]: done

File: dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/security/TenantPage.java (hunk 6 above)
Comment (ruanwenjun) [reply dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/pages/security/TenantPage.java]: done

File: dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/cases/tasks/ShellTaskE2ETest.java (hunk 7 above)
Comment (SbloodyS) [reply dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/cases/tasks/ShellTaskE2ETest.java:44]: Ok. Thanks for clarification.

File: dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/cases/tasks/ShellTaskE2ETest.java [hunk 9]
```diff
@@ -0,0 +1,260 @@
...
+import org.junit.FixMethodOrder;
+import org.junit.jupiter.api.Order;
+import org.junit.jupiter.api.Test;
+import org.junit.runners.MethodSorters;
+import org.openqa.selenium.WebElement;
+import org.testcontainers.shaded.org.awaitility.Awaitility;
+import static org.assertj.core.api.Assertions.assertThat;
+import static org.testcontainers.shaded.org.awaitility.Awaitility.await;
+
+@FixMethodOrder(MethodSorters.NAME_ASCENDING)
```
Comment (SbloodyS) [inline dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/cases/tasks/ShellTaskE2ETest.java:39]: I think this may cause wrong testing order since your testing function is not named in ascending order.

Comment (ruanwenjun) [reply dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/cases/tasks/ShellTaskE2ETest.java:39]: This is ok, since the new test method has no dependency.

Comment (SbloodyS) [reply dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/cases/tasks/ShellTaskE2ETest.java:39]: Ok.

**Review by SbloodyS — APPROVED** [review]
LGTM. Thanks.

**Review by caishunfeng — APPROVED** [review]
LGTM :+1:
