### PR TITLE
[Fix-17758][Master] Mark task as failed if TaskExecutionContext initialization fails

### LINKED ISSUE #17758: [Bug] [Master] If a task fails during initialization, it will neither be dispatched by the Master nor can it be properly killed.
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

1, import a workflow definition.
2, When running the workflow, the task cann‘t be dispatched.  
 some error info from dolphinscheduler-master.log

> [WI-8][TI-0] - 2025-12-01 15:58:06.007 INFO  [ds-workflow-eventbus-worker-14] o.a.d.s.m.e.WorkflowEventBus:[41] - Publish event: TaskDispatchLifecycleEvent{task=sh01}
[WI-8][TI-0] - 2025-12-01 15:58:06.007 INFO  [ds-workflow-eventbus-worker-14] o.a.d.s.m.e.t.l.h.AbstractTaskLifecycleEventHandler:[47] - Fired task sh01 TaskStartLifecycleEvent{task=sh01} with state SUBMITTED_SUCCESS
[WI-8][TI-0] - 2025-12-01 15:58:06.010 ERROR [ds-workflow-eventbus-worker-14] o.a.d.s.m.e.WorkflowEventBusFireWorker:[88] - Fire event failed for WorkflowExecuteRunnable: flow_condition_import_20251201155754777-20251201155805585
org.apache.dolphinscheduler.server.master.engine.exceptions.WorkflowEventFireException: Failed to fire event: TaskDispatchLifecycleEvent{task=sh01}
	at org.apache.dolphinscheduler.server.master.engine.WorkflowEventBusFireWorker.doFireSingleWorkflowEventBus(WorkflowEventBusFireWorker.java:133)
	at org.apache.dolphinscheduler.server.master.engine.WorkflowEventBusFireWorker.fireAllRegisteredEvent(WorkflowEventBusFireWorker.java:86)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.IllegalArgumentException: Cannot find the environment: 144873539254368
	at org.apache.dolphinscheduler.server.master.runner.TaskExecutionContextFactory.getEnvironmentConfigFromDB(TaskExecutionContextFactory.java:217)
	at org.apache.dolphinscheduler.server.master.runner.TaskExecutionContextFactory.createTaskExecutionContext(TaskExecutionContextFactory.java:102)
	at org.apache.dolphinscheduler.server.master.engine.task.runnable.TaskExecutionRunnable.initializeTaskExecutionContext(TaskExecutionRunnable.java:148)
	at org.apache.dolphinscheduler.server.master.engine.task.statemachine.TaskSubmittedStateAction.onDispatchEvent(TaskSubmittedStateAction.java:112)
	at org.apache.dolphinscheduler.server.master.engine.task.lifecycle.handler.TaskDispatchLifecycleEventHandler.handle(TaskDispatchLifecycleEventHandler.java:40)
	at org.apache.dolphinscheduler.server.master.engine.task.lifecycle.handler.TaskDispatchLifecycleEventHandler.handle(TaskDispatchLifecycleEventHandler.java:31)
	at org.apache.dolphinscheduler.server.master.engine.task.lifecycle.handler.AbstractTaskLifecycleEventHandler.handle(AbstractTaskLifecycleEventHandler.java:46)
	at org.apache.dolphinscheduler.server.master.engine.task.lifecycle.handler.AbstractTaskLifecycleEventHandler.handle(AbstractTaskLifecycleEventHandler.java:32)
	at org.apache.dolphinscheduler.server.master.engine.WorkflowEventBusFireWorker.doFireSingleEvent(WorkflowEventBusFireWorker.java:144)
	at org.apache.dolphinscheduler.server.master.engine.WorkflowEventBusFireWorker.doFireSingleWorkflowEventBus(WorkflowEventBusFireWorker.java:122)

3, When manually killing the workflow, it remains stuck in the "waiting to be killed" state.
 some error info from dolphinscheduler-master.log

> [WI-0][TI-0] - 2025-12-01 18:54:51.752 INFO  [MasterRpcServer-methodInvoker-15] o.a.d.s.m.e.WorkflowEventBus:[41] - Publish event: WorkflowStopLifecycleEvent{workflow=flow_condition_import_20251201155754777-20251201155805585}
[WI-8][TI-0] - 2025-12-01 18:54:51.851 INFO  [ds-workflow-eventbus-worker-0] o.a.d.s.m.e.w.l.h.AbstractWorkflowLifecycleEventHandler:[47] - Begin fire workflow flow_condition_import_20251201155754777-20251201155805585 LifecycleEvent[WorkflowStopLifecycleEvent{workflow=flow_condition_import_20251201155754777-20251201155805585}] with state: RUNNING_EXECUTION
[WI-8][TI-0] - 2025-12-01 18:54:51.863 INFO  [ds-workflow-eventbus-worker-0] o.a.d.s.m.e.w.s.AbstractWorkflowStateAction:[161] - Success set WorkflowExecuteRunnable: flow_condition_import_20251201155754777-20251201155805585 state from: RUNNING_EXECUTION to READY_STOP
[WI-8][TI-0] - 2025-12-01 18:54:51.864 INFO  [ds-workflow-eventbus-worker-0] o.a.d.s.m.e.WorkflowEventBus:[41] - Publish event: TaskKillLifecycleEvent{task=sh01, delayTime=0}
[WI-0][TI-0] - 2025-12-01 18:54:51.865 INFO  [ds-workflow-eventbus-worker-0] o.a.d.s.m.e.w.l.h.AbstractWorkflowLifecycleEventHandler:[52] - Fired workflow flow_condition_import_20251201155754777-20251201155805585 LifecycleEvent[WorkflowStopLifecycleEvent{workflow=flow_condition_import_20251201155754777-20251201155805585}] with state: READY_STOP
[WI-0][TI-0] - 2025-12-01 18:54:51.865 INFO  [ds-workflow-eventbus-worker-0] o.a.d.s.m.e.t.d.WorkerGroupDispatcherCoordinator:[74] - Failed to remove Task[id=14] from WorkerGroupDispatcher[name=default], this task has been dispatched
[WI-0][TI-0] - 2025-12-01 18:54:51.866 INFO  [ds-workflow-eventbus-worker-0] o.a.d.s.m.e.t.s.TaskSubmittedStateAction:[158] - The task[id=14] is submitted and already dispatched, cannot kill, will kill it after 5s
[WI-0][TI-0] - 2025-12-01 18:54:51.866 INFO  [ds-workflow-eventbus-worker-0] o.a.d.s.m.e.WorkflowEventBus:[41] - Publish event: TaskKillLifecycleEvent{task=sh01, delayTime=5000}
[WI-0][TI-0] - 2025-12-01 18:54:51.866 INFO  [ds-workflow-eventbus-worker-0] o.a.d.s.m.e.t.l.h.AbstractTaskLifecycleEventHandler:[47] - Fired task sh01 TaskKillLifecycleEvent{task=sh01, delayTime=0} with state SUBMITTED_SUCCESS
[WI-8][TI-0] - 2025-12-01 18:54:56.878 INFO  [ds-workflow-eventbus-worker-16] o.a.d.s.m.e.t.d.WorkerGroupDispatcherCoordinator:[74] - Failed to remove Task[id=14] from WorkerGroupDispatcher[name=default], this task has been dispatched
[WI-8][TI-0] - 2025-12-01 18:54:56.878 INFO  [ds-workflow-eventbus-worker-16] o.a.d.s.m.e.t.s.TaskSubmittedStateAction:[158] - The task[id=14] is submitted and already dispatched, cannot kill, will kill it after 5s
[WI-8][TI-0] - 2025-12-01 18:54:56.878 INFO  [ds-workflow-eventbus-worker-16] o.a.d.s.m.e.WorkflowEventBus:[41] - Publish event: TaskKillLifecycleEvent{task=sh01, delayTime=5000}
[WI-8][TI-0] - 2025-12-01 18:54:56.878 INFO  [ds-workflow-eventbus-worker-16] o.a.d.s.m.e.t.l.h.AbstractTaskLifecycleEventHandler:[47] - Fired task sh01 TaskKillLifecycleEvent{task=sh01, delayTime=5000} with state SUBMITTED_SUCCESS
[WI-8][TI-0] - 2025-12-01 18:55:01.889 INFO  [ds-workflow-eventbus-worker-13] o.a.d.s.m.e.t.d.WorkerGroupDispatcherCoordinator:[74] - Failed to remove Task[id=14] from WorkerGroupDispatcher[name=default], this task has been dispatched
[WI-8][TI-0] - 2025-12-01 18:55:01.890 INFO  [ds-workflow-eventbus-worker-13] o.a.d.s.m.e.t.s.TaskSubmittedStateAction:[158] - The task[id=14] is submitted and already dispatched, cannot kill, will kill it after 5s
[WI-8][TI-0] - 2025-12-01 18:55:01.890 INFO  [ds-workflow-eventbus-worker-13] o.a.d.s.m.e.WorkflowEventBus:[41] - Publish event: TaskKillLifecycleEvent{task=sh01, delayTime=5000}
[WI-8][TI-0] - 2025-12-01 18:55:01.890 INFO  [ds-workflow-eventbus-worker-13] o.a.d.s.m.e.t.l.h.AbstractTaskLifecycleEventHandler:[47] - Fired task sh01 TaskKillLifecycleEvent{task=sh01, delayTime=5000} with state SUBMITTED_SUCCESS
[WI-8][TI-0] - 2025-12-01 18:55:06.900 INFO  [ds-workflow-eventbus-worker-1] o.a.d.s.m.e.t.d.WorkerGroupDispatcherCoordinator:[74] - Failed to remove Task[id=14] from WorkerGroupDispatcher[name=default], this task has been dispatched
[WI-8][TI-0] - 2025-12-01 18:55:06.901 INFO  [ds-workflow-eventbus-worker-1] o.a.d.s.m.e.t.s.TaskSubmittedStateAction:[158] - The task[id=14] is submitted and already dispatched, cannot kill, will kill it after 5s
[WI-8][TI-0] - 2025-12-01 18:55:06.901 INFO  [ds-workflow-eventbus-worker-1] o.a.d.s.m.e.WorkflowEventBus:[41] - Publish event: TaskKillLifecycleEvent{task=sh01, delayTime=5000}
[WI-8][TI-0] - 2025-12-01 18:55:06.901 INFO  [ds-workflow-eventbus-worker-1] o.a.d.s.m.e.t.l.h.AbstractTaskLifecycleEventHandler:[47] - Fired task sh01 TaskKillLifecycleEvent{task=sh01, delayTime=5000} with state SUBMITTED_SUCCESS
[WI-8][TI-0] - 2025-12-01 18:55:11.912 INFO  [ds-workflow-eventbus-worker-14] o.a.d.s.m.e.t.d.WorkerGroupDispatcherCoordinator:[74] - Failed to remove Task[id=14] from WorkerGroupDispatcher[name=default], this task has been dispatched
[WI-8][TI-0] - 2025-12-01 18:55:11.912 INFO  [ds-workflow-eventbus-worker-14] o.a.d.s.m.e.t.s.TaskSubmittedStateAction:[158] - The task[id=14] is submitted and already dispatched, cannot kill, will kill it after 5s
[WI-8][TI-0] - 2025-12-01 18:55:11.912 INFO  [ds-workflow-eventbus-worker-14] o.a.d.s.m.e.WorkflowEventBus:[41] - Publish event: TaskKillLifecycleEvent{task=sh01, delayTime=5000}
[WI-8][TI-0] - 2025-12-01 18:55:11.913 INFO  [ds-workflow-eventbus-worker-14] o.a.d.s.m.e.t.l.h.AbstractTaskLifecycleEventHandler:[47] - Fired task sh01 TaskKillLifecycleEvent{task=sh01, delayTime=5000} with state SUBMITTED_SUCCESS
[WI-8][TI-0] - 2025-12-01 18:55:16.923 INFO  [ds-workflow-eventbus-worker-13] o.a.d.s.m.e.t.d.WorkerGroupDispatcherCoordinator:[74] - Failed to remove Task[id=14] from WorkerGroupDispatcher[name=default], this task has been dispatched
[WI-8][TI-0] - 2025-12-01 18:55:16.923 INFO  [ds-workflow-eventbus-worker-13] o.a.d.s.m.e.t.s.TaskSubmittedStateAction:[158] - The task[id=14] is submitted and already dispatched, cannot kill, will kill it after 5s
[WI-8][TI-0] - 2025-12-01 18:55:16.923 INFO  [ds-workflow-eventbus-worker-13] o.a.d.s.m.e.WorkflowEventBus:[41] - Publish event: TaskKillLifecycleEvent{task=sh01, delayTime=5000}

### What you expected to happen

A workflow that failed during initialization should be able to be killed normally.

### How to reproduce

1, import a workflow definition(The environment code does not exist.).
2, When running the workflow, the task cann‘t be dispatched.
3, When manually killing the workflow, it remains stuck in the "waiting to be killed" state.

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by njnu-seafish**
## Purpose of the pull request

close #17758 

## Brief change log

publish TaskFatalLifecycleEvent if initializeTaskExecutionContext fail when try to dispatch task

## Verify this pull request

This pull request is already covered by existing tests.
First, add it test case
Second, We have already verified and tested this in our actual production environment.

## Pull Request Notice
[Pull Request Notice](https://github.com/apache/dolphinscheduler/blob/dev/docs/docs/en/contribute/join/pull-request.md)

If your pull request contains incompatible change, you should also add it to `docs/docs/en/guide/upgrade/incompatible.md`

### CODE REVIEW

**Comment by njnu-seafish** [comment]
The second version of the code has been verified to work in our actual test environment. The specific logs are as follows:

> [WI-193][TI-0] - 2025-12-25 09:58:53.578 INFO  [ds-workflow-eventbus-worker-5] o.a.d.s.m.e.WorkflowEventBus:[41] - Publish event: TaskStartLifecycleEvent{task=sh01}
[WI-193][TI-0] - 2025-12-25 09:58:53.578 INFO  [ds-workflow-eventbus-worker-5] o.a.d.s.m.e.w.l.h.AbstractWorkflowLifecycleEventHandler:[52] - Fired workflow flow_condition_import_no_environment-20251225095821727 LifecycleEvent[WorkflowTopologyLogicalTransitionWithTaskFinishLifecycleEvent{task=sh001taskState=SUCCESS}] with state: RUNNING_EXECUTION
[WI-193][TI-0] - 2025-12-25 09:58:53.583 INFO  [ds-workflow-eventbus-worker-5] o.a.d.s.m.e.WorkflowEventBus:[41] - Publish event: TaskDispatchLifecycleEvent{task=sh01}
[WI-193][TI-0] - 2025-12-25 09:58:53.583 INFO  [ds-workflow-eventbus-worker-5] o.a.d.s.m.e.t.l.h.AbstractTaskLifecycleEventHandler:[47] - Fired task sh01 TaskStartLifecycleEvent{task=sh01} with state SUBMITTED_SUCCESS
[WI-193][TI-0] - 2025-12-25 09:58:53.585 ERROR [ds-workflow-eventbus-worker-5] o.a.d.s.m.e.t.s.TaskSubmittedStateAction:[117] - Failed to initialize task execution context, taskName: sh01
java.lang.IllegalArgumentException: Cannot find the environment: 144873539254368
	at org.apache.dolphinscheduler.server.master.runner.TaskExecutionContextFactory.getEnvironmentConfigFromDB(TaskExecutionContextFactory.java:217)
	at org.apache.dolphinscheduler.server.master.runner.TaskExecutionContextFactory.createTaskExecutionContext(TaskExecutionContextFactory.java:102)
	at org.apache.dolphinscheduler.server.master.engine.task.runnable.TaskExecutionRunnable.initializeTaskExecutionContext(TaskExecutionRunnable.java:148)
	at org.apache.dolphinscheduler.server.master.engine.task.statemachine.TaskSubmittedStateAction.onDispatchEvent(TaskSubmittedStateAction.java:115)
	at org.apache.dolphinscheduler.server.master.engine.task.lifecycle.handler.TaskDispatchLifecycleEventHandler.handle(TaskDispatchLifecycleEventHandler.java:40)
	at org.apache.dolphinscheduler.server.master.engine.task.lifecycle.handler.TaskDispatchLifecycleEventHandler.handle(TaskDispatchLifecycleEventHandler.java:31)
	at org.apache.dolphinscheduler.server.master.engine.task.lifecycle.handler.AbstractTaskLifecycleEventHandler.handle(AbstractTaskLifecycleEventHandler.java:46)
	at org.apache.dolphinscheduler.server.master.engine.task.lifecycle.handler.AbstractTaskLifecycleEventHandler.handle(AbstractTaskLifecycleEventHandler.java:32)
	at org.apache.dolphinscheduler.server.master.engine.WorkflowEventBusFireWorker.doFireSingleEvent(WorkflowEventBusFireWorker.java:158)
	at org.apache.dolphinscheduler.server.master.engine.WorkflowEventBusFireWorker.doFireSingleWorkflowEventBus(WorkflowEventBusFireWorker.java:125)
	at org.apache.dolphinscheduler.server.master.engine.WorkflowEventBusFireWorker.fireAllRegisteredEvent(WorkflowEventBusFireWorker.java:89)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
[WI-193][TI-0] - 2025-12-25 09:58:53.587 INFO  [ds-workflow-eventbus-worker-5] o.a.d.s.m.e.WorkflowEventBus:[41] - Publish event: TaskFatalLifecycleEvent{task=sh01, endTime=Thu Dec 25 09:58:53 GMT+08:00 2025}
[WI-193][TI-0] - 2025-12-25 09:58:53.587 ERROR [ds-workflow-eventbus-worker-5] o.a.d.s.m.e.WorkflowEventBusFireWorker:[91] - Fire event failed for WorkflowExecuteRunnable: flow_condition_import_no_environment-20251225095821727
org.apache.dolphinscheduler.server.master.engine.exceptions.WorkflowEventFireException: Failed to fire event: TaskDispatchLifecycleEvent{task=sh01}
	at org.apache.dolphinscheduler.server.master.engine.WorkflowEventBusFireWorker.doFireSingleWorkflowEventBus(WorkflowEventBusFireWorker.java:147)
	at org.apache.dolphinscheduler.server.master.engine.WorkflowEventBusFireWorker.fireAllRegisteredEvent(WorkflowEventBusFireWorker.java:89)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: org.apache.dolphinscheduler.server.master.exception.TaskExecutionContextCreateException: Cannot find the environment: 144873539254368
	at org.apache.dolphinscheduler.server.master.engine.task.statemachine.TaskSubmittedStateAction.onDispatchEvent(TaskSubmittedStateAction.java:118)
	at org.apache.dolphinscheduler.server.master.engine.task.lifecycle.handler.TaskDispatchLifecycleEventHandler.handle(TaskDispatchLifecycleEventHandler.java:40)
	at org.apache.dolphinscheduler.server.master.engine.task.lifecycle.handler.TaskDispatchLifecycleEventHandler.handle(TaskDispatchLifecycleEventHandler.java:31)
	at org.apache.dolphinscheduler.server.master.engine.task.lifecycle.handler.AbstractTaskLifecycleEventHandler.handle(AbstractTaskLifecycleEventHandler.java:46)
	at org.apache.dolphinscheduler.server.master.engine.task.lifecycle.handler.AbstractTaskLifecycleEventHandler.handle(AbstractTaskLifecycleEventHandler.java:32)
	at org.apache.dolphinscheduler.server.master.engine.WorkflowEventBusFireWorker.doFireSingleEvent(WorkflowEventBusFireWorker.java:158)
	at org.apache.dolphinscheduler.server.master.engine.WorkflowEventBusFireWorker.doFireSingleWorkflowEventBus(WorkflowEventBusFireWorker.java:125)
	... 8 common frames omitted
[WI-193][TI-0] - 2025-12-25 09:58:53.694 INFO  [ds-workflow-eventbus-worker-10] o.a.d.s.m.e.WorkflowEventBus:[41] - Publish event: WorkflowTopologyLogicalTransitionWithTaskFinishLifecycleEvent{task=sh01taskState=FAILURE}
[WI-193][TI-0] - 2025-12-25 09:58:53.694 INFO  [ds-workflow-eventbus-worker-10] o.a.d.s.m.e.t.l.h.AbstractTaskLifecycleEventHandler:[47] - Fired task sh01 TaskFatalLifecycleEvent{task=sh01, endTime=Thu Dec 25 09:58:53 GMT+08:00 2025} with state SUBMITTED_SUCCESS
[WI-193][TI-0] - 2025-12-25 09:58:53.694 INFO  [ds-workflow-eventbus-worker-10] o.a.d.s.m.e.w.l.h.AbstractWorkflowLifecycleEventHandler:[47] - Begin fire workflow flow_condition_import_no_environment-20251225095821727 LifecycleEvent[WorkflowTopologyLogicalTransitionWithTaskFinishLifecycleEvent{task=sh01taskState=FAILURE}] with state: RUNNING_EXECUTION

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/WorkflowEventBusFireWorker.java [hunk 1]
```diff
@@ -128,6 +131,19 @@ private void doFireSingleWorkflowEventBus(final IWorkflowExecutionRunnable workf
                     ThreadUtils.sleep(5_000);
                     return;
                 }
+
+                // If task initializeTaskExecutionContext before dispatch is failed
+                // construct and publish a dedicated TaskFatalLifecycleEvent
+                // so that the event will be handled by TaskFatalLifecycleEventHandler
```
Comment (ruanwenjun) [inline dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/WorkflowEventBusFireWorker.java]:
```suggestion
```

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/task/statemachine/AbstractTaskStateAction.java [hunk 2]
```diff
@@ -99,6 +100,38 @@ protected void releaseTaskInstanceResourcesIfNeeded(final ITaskExecutionRunnable
...
+
+        // If all successors are condition tasks, then the task will not be marked as failure.
+        // And the DAG will continue to execute.
+        final IWorkflowExecutionGraph workflowExecutionGraph = taskExecutionRunnable.getWorkflowExecutionGraph();
+        if (workflowExecutionGraph.isAllSuccessorsAreConditionTask(taskExecutionRunnable)) {
+            mergeTaskVarPoolToWorkflow(workflowExecutionRunnable, taskExecutionRunnable);
+            publishWorkflowInstanceTopologyLogicalTransitionEvent(taskExecutionRunnable);
+            return;
+        }
+        taskExecutionRunnable.getWorkflowExecutionGraph().markTaskExecutionRunnableChainFailure(taskExecutionRunnable);
```
Comment (ruanwenjun) [inline dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/task/statemachine/AbstractTaskStateAction.java:124]: Need to deal with the workflow failure strategy

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/task/statemachine/TaskSubmittedStateAction.java [hunk 3]
```diff
@@ -109,7 +110,14 @@ public void onDispatchEvent(final IWorkflowExecutionRunnable workflowExecutionRu
                     taskInstance.getDelayTime(),
                     remainTimeMills);
         }
-        taskExecutionRunnable.initializeTaskExecutionContext();
+
+        try {
+            taskExecutionRunnable.initializeTaskExecutionContext();
+        } catch (Exception ex) {
+            log.error("Failed to initialize task execution context, taskName: {}", taskInstance.getName(), ex);
```
Comment (ruanwenjun) [inline dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/task/statemachine/TaskSubmittedStateAction.java:121]: Do not catch all exception here, at least `DataAccessResourceFailureException` should be filter here.

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/WorkflowEventBusFireWorker.java (hunk 1 above)
Comment (njnu-seafish) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/WorkflowEventBusFireWorker.java]: >  OK, I will remove it.   Mainly because I noticed you previously added explanatory comments at key points.

                // If the database connection is failed, do not remove the event from the event bus
                // so that the event can be fired again when the database connection is recovered
                if (ExceptionUtils.isDatabaseConnectedFailedException(ex)) {
                    workflowEventBus.publish(lifecycleEvent);
                    ThreadUtils.sleep(5_000);
                    return;
                }

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/task/statemachine/TaskSubmittedStateAction.java (hunk 3 above)
Comment (njnu-seafish) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/task/statemachine/TaskSubmittedStateAction.java:121]: > Do not catch all exception here, at least `DataAccessResourceFailureException` should be filter here.

yes, You're incredibly thorough—thank you!

File: dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/task/statemachine/TaskSubmittedStateAction.java [hunk 4]
```diff
@@ -109,7 +111,18 @@ public void onDispatchEvent(final IWorkflowExecutionRunnable workflowExecutionRu
...
-        taskExecutionRunnable.initializeTaskExecutionContext();
+
+        try {
+            taskExecutionRunnable.initializeTaskExecutionContext();
+        } catch (DataAccessResourceFailureException ex) {
+            log.error("Database/resource failure during task context initialization, taskName: {}",
+                    taskInstance.getName(), ex);
+            throw ex;
+        } catch (Exception ex) {
+            log.error("Failed to initialize task execution context, taskName: {}", taskInstance.getName(), ex);
```
Comment (ruanwenjun) [inline dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/task/statemachine/TaskSubmittedStateAction.java]:
```suggestion
        catch (Exception ex) {
            if(ExceptionUtils.isDatabaseConnectedFailedException(ex)) {
                throw ex;
            }
            log.error("Failed to initialize task execution context, taskName: {}", taskInstance.getName(), ex);
```

Comment (njnu-seafish) [reply dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/engine/task/statemachine/TaskSubmittedStateAction.java]: > catch (Exception ex) {
>             if(ExceptionUtils.isDatabaseConnectedFailedException(ex)) {
>                 throw ex;
>             }
>             log.error("Failed to initialize task execution context, taskName: {}", taskInstance.getName(), ex);

an excellent suggestion!

**Review by ruanwenjun — APPROVED** [review]
LGTM

**Comment by njnu-seafish** [comment]
@SbloodyS  Whenever you have time, I’d be grateful for your review. Thanks so much!

**Review by SbloodyS — APPROVED** [review]
+1
