### PR TITLE
[Fix-7773][Api] malform batchDeleteProcessInstanceByIds log output

### LINKED ISSUE #7773: [Bug] [Api] malform batchDeleteProcessInstanceByIds log output
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

```
[INFO] 2022-01-03 04:00:57.639 org.apache.dolphinscheduler.api.aspect.AccessLogAspect:[90] - REQUEST TRACE_ID:ecda536d-0f42-485a-9584-a5bb3abb16f9, LOGIN_USER:admin, URI:/dolphinscheduler/projects/4064259691936/process-instances/batch-delete, METHOD:POST, HANDLER:org.apache.dolphinscheduler.api.controller.ProcessInstanceController.batchDeleteProcessInstanceByI
ds, ARGS:{projectCode=4064259691936, processInstanceIds=1234} 
[ERROR] 2022-01-03 04:00:57.642 org.apache.dolphinscheduler.api.controller.ProcessInstanceController:[409] - 工 作 流 实 例 [1,234]不 存 在
```

### What you expected to happen

log output right

### How to reproduce

curl -X POST "http://192.168.1.160:12345/dolphinscheduler/projects/4064259691936/process-instances/batch-delete" -H "Request-Origion:SwaggerBootstrapUi" -H "accept:*/*" -H "Content-Type:application/x-www-form-urlencoded;charset=UTF-8" -d "processInstanceIds=1234" -d "projectName=test" -d "alertGroup=" -d "createTime=" -d "email=" -d "id=" -d "phone=" -d "queue=" -d "queueName=" -d "state=" -d "tenantCode=" -d "tenantId=" -d "updateTime=" -d "userName=" -d "userPassword=" -d "userType=ADMIN_USER"

### Anything else

_No response_

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by SbloodyS**
## Purpose of the pull request

This pr will close #7773

### CODE REVIEW

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessInstanceServiceImpl.java [hunk 1]
```diff
@@ -612,13 +612,13 @@ private void setProcessInstance(ProcessInstance processInstance, String tenantCo
         }
         ProcessInstance processInstance = processService.findProcessInstanceDetailById(processInstanceId);
         if (null == processInstance) {
-            putMsg(result, Status.PROCESS_INSTANCE_NOT_EXIST, processInstanceId);
+            putMsg(result, Status.PROCESS_INSTANCE_NOT_EXIST, String.valueOf(processInstanceId));
```
Comment (caishunfeng) [inline dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessInstanceServiceImpl.java:615]: What's the different of log?

Comment (SbloodyS) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessInstanceServiceImpl.java:615]: eg:
The input processInstanceId is 1234.

Before:  工 作 流 实 例 [1,234]不 存 在
After: 工 作 流 实 例 [1234]不 存 在

Status.PROCESS_INSTANCE_NOT_EXIST using {0} as parameter while input type in integer may cause this problem.

**Review by caishunfeng — APPROVED** [review]
+1
