### PR TITLE
[Fix-9617]New task group project name drop-down data is displayed according to user type.

### LINKED ISSUE #9617: [BUG-RD] [V1.0.0-Beta]New task grouping item selection require
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened

The drop-down box of the project name of the task group created by the non-admin user displays all projects.

### What you expected to happen

New task grouping item selection requir，Non-admin user, no new project created，The dropdown box should be empty

### How to reproduce

Create a non-admin user
Create a task group
Click the project name drop-down box

### Anything else

No Response

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by WangJPLeo**
## Purpose of the pull request

New task group project name drop-down data is displayed according to user type.

## Brief change log

close #9617 

## Verify this pull request

Manually verified the change by testing locally.

### CODE REVIEW

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProjectServiceImpl.java [hunk 1]
```diff
@@ -38,6 +38,7 @@
 import org.springframework.beans.factory.annotation.Autowired;
 import org.springframework.stereotype.Service;
 
+import javax.annotation.PostConstruct;
 import java.util.*;
```
Comment (SbloodyS) [inline dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProjectServiceImpl.java]: Please avoid ```import *```

**Review by SbloodyS — CHANGES_REQUESTED** [review]

File: dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProjectServiceImpl.java (hunk 1 above)
Comment (WangJPLeo) [reply dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProjectServiceImpl.java]: Thank you, I will pay more attention to the code smell of commits.

**Review by SbloodyS — APPROVED** [review]
LGTM if CI passed.
