### PR TITLE
[Fix-5518]:  The data analysis state count interface, projectId change to projectCode

### LINKED ISSUE #5498: [Feature][JsonSplit-api] api module controller design
continuation of #4417 
- [x] 1. processDefinition save/update interface
- [x] 2. processDefinition switch interface
- [x] 3. processDefinition delete interface
- [x] 4. processDefinition copy interface
- [x] 5. processDefinition export interface
- [x] 6. processDefinition list-paging interface
- [x] 7. processDefinition move interface
- [x] 8. processDefinition queryProcessDefinitionAllByProjectId interface
- [x] 9. processDefinition select-by-id interface
- [x] 10. processDefinition view-tree interface
- [x] 11. schedule create interface
- [x] 12. schedule list-paging interface
- [x] 13. schedule update interface
- [x] 14. taskDefinition save interface
- [x] 15. taskDefinition update interface
- [x] 16. taskDefinition switch interface
- [x] 17. taskDefinition query interface
- [x] 18. taskDefinition delete interface
- [x] 19. WorkFlowLineage interface
- [x] 20. analysis interface
- [x] 21. executors interface
- [x] 22. processInstance interface
- [x] 23. project interface
- [x] 24. schedule online/offline interface
- [x] 25. schedule list interface
- [x] 26. schedule preview interface
- [x] 27. schedule delete interface
- [x] 28. font-ent: refactor of locations
- [x] 29. processDefinition: remove connects
- [x] 30. refactor of ProjectService.checkProjectAndAuth

### PR DESCRIPTION
**Pull request by wen-hemin**
from #5518

### CODE REVIEW

File: dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/index/_source/processStateCount.vue [hunk 1]
```diff
@@ -91,7 +91,7 @@
         const myChart = Chart.pie('#process-state-pie', this.processStateList, { title: '' })
         myChart.echart.setOption(pie)
         // 首页不允许跳转
```
Comment (brave-lee) [inline dolphinscheduler-ui/src/js/conf/home/pages/projects/pages/index/_source/processStateCount.vue]: I think it should be English here

**Review by brave-lee — COMMENTED** [review]
+1
