### PR TITLE
[fix-#14537] the branch that needs to be executed overlaps with another branch, it may not be able to complete the normal execution

### LINKED ISSUE #14537: [Bug] [SwitchTask] f the branch that needs to be executed overlaps with another branch, it may not be able to complete the normal execution
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar issues.

### What happened
image

For switch type tasks, if the branch that needs to be executed overlaps with another branch, it may not be able to complete the normal execution

### What you expected to happen

For switch type tasks, if the branch that needs to be executed overlaps with another branch, it may not be able to complete the normal execution

### How to reproduce

only disjoint nodes are stored in the skipNodeList collection

### Anything else

I also want to push to the 3.0.x branch

### Version

dev

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by fuchanghai**
plz close #14537 

- #14537 

## Purpose of the pull request
Only skip the non-common part before the first intersection of the branch executed by the switch and the non-executed branch

## Brief change log
nodes behind the red box are not executed
before:
image

after:
image
## Verify this pull request

This pull request is code cleanup without any test coverage.

### CODE REVIEW

**Comment by fuchanghai** [comment]
PTAL @caishunfeng  cc @Radeity @EricGao888 @rickchengx

**Comment by fuchanghai** [comment]
PTAL @caishunfeng  cc @Radeity @EricGao888

**Comment by davidzollo** [comment]
Please add Unit Test!

**Comment by fuchanghai** [comment]
> Please add Unit Test!

Done

**Comment by fuchanghai** [comment]
@davidzollo @EricGao888 plz rerun

**Comment by fuchanghai** [comment]
@caishunfeng PTAL

File: dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/utils/DagHelper.java [hunk 1]
```diff
@@ -424,19 +424,61 @@ private static List<Long> skipTaskNode4Switch(TaskNode taskNode,
...
+                getSwitchNeedWorkCodes(switchTaskCode, dag, switchNeedWorkCodes);
+            }
         }
         // conditionResultVoList.remove(resultConditionLocation);
         for (SwitchResultVo info : conditionResultVoList) {
             if (CollectionUtils.isEmpty(info.getNextNode())) {
                 continue;
             }
-            setTaskNodeSkip(info.getNextNode().get(0), dag, completeTaskList, skipTaskNodeList);
+            setSwitchTaskNodeSkip(info.getNextNode().get(0), dag, completeTaskList, skipTaskNodeList,
```
Comment (caishunfeng) [inline dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/utils/DagHelper.java]: `info.getNextNode().get(0)` is skipNode? If true, I think it's better to add method like `getFirstSkipNode` for  `SwitchResultVo`, WDYT?

File: dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/utils/DagHelper.java [hunk 2]
```diff
@@ -424,19 +424,61 @@ private static List<Long> skipTaskNode4Switch(TaskNode taskNode,
...
         List<Long> switchTaskList = conditionResultVoList.get(resultConditionLocation).getNextNode();
+        Set<Long> switchNeedWorkCodes = new HashSet<>();
         if (CollectionUtils.isEmpty(switchTaskList)) {
             switchTaskList = new ArrayList<>();
+        } else {
+            // get all downstream nodes of the branch that the switch node needs to execute
+            for (Long switchTaskCode : switchTaskList) {
+                getSwitchNeedWorkCodes(switchTaskCode, dag, switchNeedWorkCodes);
+            }
         }
```
Comment (caishunfeng) [inline dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/utils/DagHelper.java]:
```suggestion
        if (CollectionUtils.isEmpty(switchTaskList)) {
            return new ArrayList<>();
        } 
          // get all downstream nodes of the branch that the switch node needs to execute
          for (Long switchTaskCode : switchTaskList) {
              getSwitchNeedWorkCodes(switchTaskCode, dag, switchNeedWorkCodes);
          }
```

File: dolphinscheduler-service/src/test/java/org/apache/dolphinscheduler/service/utils/DagHelperTest.java [hunk 3]
```diff
@@ -436,11 +454,13 @@ private DAG<Long, TaskNode, TaskNodeRelation> generateDag() throws IOException {
...
      * DAG graph:
-     *    2
-     *    ↑
-     * 0->1(switch)
-     *    ↓
-     *    4
+     *           -> 2->
+     *         /        \
+     *      /               \
+     * 0->1(switch)->5          6
```
Comment (caishunfeng) [inline dolphinscheduler-service/src/test/java/org/apache/dolphinscheduler/service/utils/DagHelperTest.java:460]: :+1:

File: dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/utils/DagHelper.java (hunk 1 above)
Comment (fuchanghai) [reply dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/utils/DagHelper.java]: i will improve this

Comment (fuchanghai) [reply dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/utils/DagHelper.java]: hi @caishunfeng  according to the front-end page, it seems that a switchResult has only one nextNode. So in order to avoid ambiguity, use a loop to traverse (instead of ``` get(0)```), what do you think?

**Review by caishunfeng — DISMISSED** [review]
LGTM

File: dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/utils/DagHelper.java (hunk 1 above)
Comment (caishunfeng) [reply dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/utils/DagHelper.java]: I think it's ok.

**Comment by caishunfeng** [comment]
run CI

**Comment by fuchanghai** [comment]
@davidzollo @caishunfeng @SbloodyS  This PR should also be merged to 3.1.x and 3.0.x

**Comment by SbloodyS** [comment]
> @davidzollo @caishunfeng @SbloodyS This PR should also be merged to 3.1.x and 3.0.x

cc @zhuangchong @zhongjiajie

**Review by ruanwenjun — APPROVED** [review]
